### PR TITLE
sriov-lane: Fix AfterSuite namespaces deletion timeouts

### LINKED ISSUE #3850: Test suite: AfterSuite errors
/kind bug

**What happened**:
SRIOV lane Prow jobs are failing due to AfterSuite error, whether tests passed or not
it also happend once on k8s-1.18 lane:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3755/pull-kubevirt-e2e-k8s-1.18/1280142057649737728
```
[AfterSuite] AfterSuite 
/root/go/src/kubevirt.io/kubevirt/tests/tests_suite_test.go:55
  Timed out after 240.000s.
  Expected
      <bool>: false
  to be true
  /root/go/src/kubevirt.io/kubevirt/tests/utils.go:55
```

Debugging this error, I found that deleting the namespace `kubevirt-test-default` at AfterSuite
causing a timeout, during deletion process of that namespace there is a condition with an error:
```
 NamespaceDeletionDiscoveryFailure 
        True 
        2020-07-13 20:08:40 +0000 UTC 
        DiscoveryFailed 
        Discovery failed for some groups, 1 failing: 
            unable to retrieve the complete list of server APIs: 
                upload.cdi.kubevirt.io/v1alpha1: 
                    the server is currently unable to handle the request
```

**What you expected to happen**:
Not failing on AfterSuite.

**How to reproduce it (as minimally and precisely as possible)**:
Run sriov lane job on prow.

**Anything else we need to know?**:
This issue will not reproduce locally, only on prow.

**Environment**:
- Kubevirt Provider: kind-k8s-sriov-1.17.0
- KubeVirt version (use `virtctl version`): master
- Kubernetes version (use `kubectl version`): 1.17
- VM or VMI specifications: 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
This PR is a workaround for AfterSuite errors on sriov lane by:
- Using customized image for sriov lane test VM's,
  that image includes sriov drivers and qemu-guest-agent and configured to load necessary kernel modules for sriov
- Cancel cdi-operaor deployment for sriov-lane
  
**Which issue(s) this PR fixes**:
Fixes #3850 

**Special notes for your reviewer**:
This error will not reproduce locally, only on prow

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: tests/utils.go [hunk 1]
```diff
@@ -3024,6 +3044,20 @@ func LoggedInFedoraExpecter(vmi *v1.VirtualMachineInstance) (expect.Expecter, er
 		&expect.BSnd{S: "\n"},
 		&expect.BSnd{S: "\n"},
 		&expect.BCas{C: []expect.Caser{
+			// wait for VM to finish booting and cloud-init by
```
Comment (oshoval) [inline tests/utils.go:3047]: you might want to look on
https://github.com/kubevirt/kubevirt/pull/3539

File: automation/test.sh [hunk 2]
```diff
@@ -38,7 +38,7 @@ readonly BAZEL_CACHE="${BAZEL_CACHE:-http://bazel-cache.kubevirt-prow.svc.cluste
 # All the other lanes will fail immediately, saving CI resources,
 # but still guarding from getting the PR merged, until the line
 # is restored to an empty string.
-export KUBEVIRT_LANE_FOCUS=""
+export KUBEVIRT_LANE_FOCUS="kind-k8s-sriov-1.17.0"
```
Comment (rmohr) [inline automation/test.sh:41]: Could you please remove this focus? It will be removed as part of #3832 anyway and cause merge conflicts and it introduces the mentioned issues there.

Comment (rmohr) [reply automation/test.sh:41]: You can make your PR a draft instead and explicitly trigger the lanes you care about.

Comment (ormergi) [reply automation/test.sh]: Thanks for the heads up

**Comment by ormergi** [comment]
When using customized container-disk image w/o CDI operator the AfterSuite errors are gone
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3797/pull-kubevirt-e2e-kind-1.17-sriov/1290711903110172672

File: tests/utils.go [hunk 3]
```diff
@@ -1694,8 +1695,47 @@ func removeNamespaces() {
...
+			if namespaceDeletionError != nil {
+				fmt.Printf("could not get delete '%v':\n %v\n", namespace, namespaceDeletionError)
+			}
+
+			namespaceObject, err := virtCli.CoreV1().Namespaces().Get(namespace, metav1.GetOptions{})
+			if err != nil {
+				fmt.Printf("could not get namespace '%v':\n %v\n", namespace, err)
+			}
+
+			fmt.Printf("deleting namespace '%v':\n %v\n", namespace, err)
```
Comment (alonSadan) [inline tests/utils.go:1709]: why `err` is printed here as well? it could the error from the GET operation which is not related to `deleting namespace`?

File: tests/utils.go [hunk 4]
```diff
@@ -1694,8 +1695,47 @@ func removeNamespaces() {
 	fmt.Println("")
 	for _, namespace := range testNamespaces {
 		fmt.Printf("Waiting for namespace %s to be removed, this can take a while ...\n", namespace)
-		EventuallyWithOffset(1, func() bool { return errors.IsNotFound(virtCli.CoreV1().Namespaces().Delete(namespace, nil)) }, 240*time.Second, 1*time.Second).
-			Should(BeTrue())
+		EventuallyWithOffset(1, func() bool {
```
Comment (alonSadan) [inline tests/utils.go:1698]: I might misunderstood what's happen here, but I think it is better to split this function into some sub-functions returning errors and asserting on that.
As it is now, the test only fails when `IsNotFound` is false, but as I understand it, there are a lot more errors along the way that are just printed and could be missed. should they fail the test?

File: tests/utils.go [hunk 5]
```diff
@@ -1694,8 +1695,47 @@ func removeNamespaces() {
...
+				for _, condition := range apiService.Status.Conditions {
+					if condition.Type == "Available" {
+						if condition.Status == "False" {
+							fmt.Printf("apiservice '%s' '%s' not Available: \n%v\n", apiService.Name, apiService.Spec.Group, condition)
+						}
+					}
+				}
+			}
+
+			return errors.IsNotFound(namespaceDeletionError)
```
Comment (alonSadan) [inline tests/utils.go:1737]: consider returning an error and assert on that using Petr's cool Eventually.
like I commented here : 
https://github.com/kubevirt/ovs-cni/pull/124#discussion_r472140476

**Comment by ormergi** [comment]
> Thanks @ormergi .
> I hope this will make SRIOV solid as a rock.
> 
> Overall looks good.
> My only notes are about: [d462644](https://github.com/kubevirt/kubevirt/commit/d462644b68c2f7f57f7d4cad13e908251e55d63a)
> Can you give some explanation it in the commit message?

Thanks

Sorry I totally forgot to remove this commit, I used it for debugging the namespace errors
I replace it with another commit that add Expect error message.

File: tests/utils.go [hunk 6]
```diff
@@ -1694,8 +1694,9 @@ func removeNamespaces() {
 	fmt.Println("")
 	for _, namespace := range testNamespaces {
 		fmt.Printf("Waiting for namespace %s to be removed, this can take a while ...\n", namespace)
-		EventuallyWithOffset(1, func() bool { return errors.IsNotFound(virtCli.CoreV1().Namespaces().Delete(namespace, nil)) }, 240*time.Second, 1*time.Second).
-			Should(BeTrue())
+		EventuallyWithOffset(1, func() bool {
+			return errors.IsNotFound(virtCli.CoreV1().Namespaces().Delete(namespace, nil))
```
Comment (alonSadan) [inline tests/utils.go:1698]: same here https://github.com/kubevirt/kubevirt/pull/3797#discussion_r472232618

File: tests/vmi_multus_test.go [hunk 7]
```diff
@@ -50,8 +50,8 @@ const (
...
-	sriovConfCRD           = `{"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"name":"%s","namespace":"%s","annotations":{"k8s.v1.cni.cncf.io/resourceName":"%s"}},"spec":{"config":"{ \"name\": \"sriov\", \"type\": \"sriov\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"10.1.1.0/24\" } }"}}`
-	sriovLinkEnableConfCRD = `{"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"name":"%s","namespace":"%s","annotations":{"k8s.v1.cni.cncf.io/resourceName":"%s"}},"spec":{"config":"{ \"name\": \"sriov\", \"type\": \"sriov\", \"link_state\": \"enable\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"10.1.1.0/24\" } }"}}`
+	sriovConfCRD           = `{"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"name":"%s","namespace":"%s","annotations":{"k8s.v1.cni.cncf.io/resourceName":"%s"}},"spec":{"config":"{ \"cniVersion\": \"0.3.1\", \"name\": \"sriov\", \"type\": \"sriov\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"10.1.1.0/24\" } }"}}`
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:53]: not sure here, maybe it is better to use a constant for the cni version and  instead of hard coding it?

File: containerimages/container-disk-images.md [hunk 8]
```diff
@@ -12,3 +12,102 @@ The following images stored at `dockerhub.com/kubevirt` and can be used in Kubev
...
+```bash
+container_pull(
+    name = "fedora_sriov_lane",
+    # digest = ""
+    registry = "localhost:5000",
+    repository = "kubevirt/fedora-sriov-testing",
+    tag = "latest",
+)
+```
+Once you verified the image works reach out to kubevirt CI maintainers and ask to upload the new image
```
Comment (alonSadan) [inline containerimages/container-disk-images.md:73]: sorry if it is a dumb question, how we verify that the image works?

File: tests/vmi_multus_test.go [hunk 9]
```diff
@@ -623,33 +623,28 @@ var _ = Describe("SRIOV", func() {
...
 				network := v1.Network{Name: name, NetworkSource: v1.NetworkSource{Multus: &v1.MultusNetwork{NetworkName: name}}}
 				vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, iface)
 				vmi.Spec.Networks = append(vmi.Spec.Networks, network)
 			}
 
-			// fedora requires some more memory to boot without kernel panics
-			vmi.Spec.Domain.Resources.Requests[k8sv1.ResourceName("memory")] = resource.MustParse("1024M")
-
-			return
+			return vmi
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:647]: nit: since we specify the name of the return object, you can leave the return statement empty, or delete the name of the result parameter from the function signature.
further explanation can be found here: 
https://golang.org/ref/spec#Return_statements

File: containerimages/container-disk-images.md (hunk 8 above)
Comment (ormergi) [reply containerimages/container-disk-images.md:73]: Simplest check you can do is create Kubevirt VM with the customized container-disk and verify it boots and connects to the network.
Next thing to do is run functests with the new image, by manipulating `tests/containerdisks/containerdisks.go` or a specific test code to use the new image.

Comment (alonSadan) [reply containerimages/container-disk-images.md:73]: Thanks for explaining

File: tests/utils.go (hunk 5 above)
Comment (ormergi) [reply tests/utils.go]: Done

File: tests/utils.go (hunk 6 above)
Comment (ormergi) [reply tests/utils.go:1698]: Done

File: tests/vmi_multus_test.go (hunk 7 above)
Comment (ormergi) [reply tests/vmi_multus_test.go:53]: I prefer doing that on following PR, its hard to maintain those json strings 
this is why I plan is to use proper API for creating NAD https://github.com/kubevirt/kubevirt/pull/3479/files#r469123238

File: tests/vmi_multus_test.go (hunk 9 above)
Comment (ormergi) [reply tests/vmi_multus_test.go:647]: I find this convention confusing, I prefer to explicitly remote the object I expect to be returned :)

File: tests/vmi_multus_test.go [hunk 10]
```diff
@@ -923,7 +923,6 @@ func checkMacAddress(vmi *v1.VirtualMachineInstance, interfaceName, macAddress s
 		&expect.BExp{R: "#"},
 		&expect.BSnd{S: cmdCheck},
 		&expect.BExp{R: macAddress},
-		&expect.BExp{R: "#"},
```
Comment (EdDev) [inline tests/vmi_multus_test.go:931]: I think the reason you removed it is because now there is no support for two sequential expecters.
It would have been more correct to fix the previous expect to:
```
&expect.BExp{R: macAddress + "((?s).*)" + PromptExpression},
```

I am fine with you just updating the commit message with the correct reasoning of this change (i.e. CheckForTextExpecter does not support two sequential expecters).

File: tests/vmi_multus_test.go [hunk 11]
```diff
@@ -923,7 +923,6 @@ func checkMacAddress(vmi *v1.VirtualMachineInstance, interfaceName, macAddress s
 		&expect.BExp{R: "#"},
```
Comment (EdDev) [inline tests/vmi_multus_test.go:923]: You can also fix this to: `PromptExpression`

**Review by EdDev — CHANGES_REQUESTED** [review]
Looks good, thanks!

In the commit message I noticed at least to typos:
- CNI version commit: 'DelegaeDel'
- Last commit: sqeuential

File: tests/utils.go (hunk 6 above)
Comment (EdDev) [reply tests/utils.go:1698]: I do not see this change, is it waiting for you to push it?

File: tests/vmi_multus_test.go (hunk 10 above)
Comment (ormergi) [reply tests/vmi_multus_test.go:931]: I removed that expecter case because I saw error in logs about sequential expect cases.
`CheckForTextExpecter` appends `"((?s).*)" ` for each expect case for you
https://github.com/kubevirt/kubevirt/blob/ed4899ce43530db89b082d26d6b31835fe15842f/tests/utils.go#L2823
I will update the commit message

File: hack/cluster-deploy.sh [hunk 12]
```diff
@@ -56,17 +56,24 @@ if [[ "$KUBEVIRT_STORAGE" == "rook-ceph" ]]; then
     done
 fi
 
+# Remove cdi manifests for sriov-lane until kubevirt/kubevirt#3850 is fixed
+if [[ "$KUBEVIRT_PROVIDER" =~ sriov.* ]]; then
+    rm -f _out/manifests/testing/cdi-*
```
[the remark this answers is not in the document]
Comment (ormergi) [reply hack/cluster-deploy.sh]: Done

File: tests/vmi_multus_test.go (hunk 11 above)
Comment (ormergi) [reply tests/vmi_multus_test.go]: Done

**Comment by ormergi** [comment]
> Looks good, thanks!
> 
> In the commit message I noticed at least to typos:
> 
> * CNI version commit: 'DelegaeDel'
> * Last commit: sqeuential

Fixed typos and other change requests

File: tests/utils.go (hunk 4 above)
Comment (ormergi) [reply tests/utils.go:1697]: Any error that is not `IsNotFound` should fail this is the current state
I also about to change this function to return `error` instead of `bool` as you requested

File: tests/utils.go (hunk 6 above)
Comment (ormergi) [reply tests/utils.go:1698]: Sorry I missed that I will push it right away

**Comment by danielBelenky** [comment]
/approve

@ormergi thanks for handling this!

**Comment by phoracek** [comment]
/hold

Waiting for https://github.com/kubevirt/kubevirt/pull/3834

**Comment by alonSadan** [comment]
@phoracek  @ormergi we can un-hold it now, right?

**Comment by ormergi** [comment]
> @phoracek @ormergi we can un-hold it now, right?

Yes 
/unhold

File: tests/vmi_multus_test.go (hunk 10 above)
Comment (EdDev) [reply tests/vmi_multus_test.go:926]: > CheckForTextExpecter appends "((?s).*)" for each expect case for you

It appends it between what was previously sent and what you expect now (in this case, the mac address). It does not handle for you the processing of the buffer until the prompt (i.e. consuming the buffer after what you waited for until the prompt).
Because you leave that buffer, there is a potential wrong matching later. You should always strive to consume the buffer so this will not happen.

**Review by EdDev — APPROVED** [review]
Nice work!
There is one potential bug still hiding in the last commit expecter, but compare to the other changes I think we should be fine. Still, consider it for completeness.

**Comment by phoracek** [comment]
@ormergi I don't believe we need to override the job, it is not supposed to be voting. IIUIC it now retests everything in the merge queue.

**Comment by ormergi** [comment]
> @ormergi I don't believe we need to override the job, it is not supposed to be voting. IIUIC it now retests everything in the merge queue.

Is there something we can do to accelarate this process?

**Comment by phoracek** [comment]
It is part of the tide merge flow, we just need to let it do its thing. It is not down from 7 to 4 retesting jobs
