### PR TITLE
instancetype: Apply instancetype to copy of VM during admission

### LINKED ISSUE #8435: `VirtualMachineSnapshot` of a `VirtualMachine` referencing a `VirtualMachineInstancetype` becomes stuck `InProgress`
/area instancetype
/cc @iholder-redhat 

**What happened**:

Attempting to create a `VirtualMachineSnapshot` of a `VirtualMachine` referencing a `VirtualMachineInstancetype` leaves the `VirtualMachineSnapshot` `InProgress` as the virt-controller appears unable to add the required finalizer.

```
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:40.991015Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume","pos":"source.go:104","timestamp":"2022-09-08T15:24:40.995093Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.002005Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.003315Z"}
E0908 15:24:41.024257       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Attempting to create VolumeSnapshot vmsnapshot-d8a516e8-2c1a-4bb2-acd2-206cfcee8147-volume-datavolumedisk1","pos":"snapshot.go:383","timestamp":"2022-09-08T15:24:41.028147Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.029493Z"}
E0908 15:24:41.045799       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
E0908 15:24:41.049765       1 util.go:73] Operation cannot be fulfilled on virtualmachinesnapshotcontents.snapshot.kubevirt.io "vmsnapshot-content-d8a516e8-2c1a-4bb2-acd2-206cfcee8147": the object has been modified; please apply your changes to the latest version and try again
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.056213Z"}
E0908 15:24:41.081266       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.101474Z"}
E0908 15:24:41.115564       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.155987Z"}
E0908 15:24:41.166481       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.246881Z"}
E0908 15:24:41.257348       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.418062Z"}
E0908 15:24:41.462366       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:41.783144Z"}
E0908 15:24:41.794092       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:42.434222Z"}
E0908 15:24:42.445353       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:43.726139Z"}
E0908 15:24:43.735519       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:46.296614Z"}
E0908 15:24:46.312197       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:24:51.432847Z"}
E0908 15:24:51.476557       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 1 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2022-09-08T15:24:51.864822Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:25:01.717378Z"}
E0908 15:25:01.732811       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:25:22.214830Z"}
E0908 15:25:22.272368       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 1 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2022-09-08T15:25:30.980492Z"}
{"component":"virt-controller","level":"info","msg":"Adding VM snapshot finalizer to vm-cirros-datavolume-with-instancetype","pos":"source.go:104","timestamp":"2022-09-08T15:26:03.251136Z"}
E0908 15:26:03.287764       1 util.go:73] admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Cannot update VM spec until snapshot "snap-cirros-with-instnacetype" completes
{"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 1 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2022-09-08T15:26:07.055528Z"}
```
**What you expected to happen**:

The finalizer is applied and the `VirtualMachineSnapshot` completes.

**How to reproduce it (as minimally and precisely as possible)**:

```
# My local dev env is using the rook-ceph-default storage backend
$ export KUBEVIRT_STORAGE=rook-ceph-default

$ ./cluster-up/kubectl.sh get kubevirt/kubevirt -n kubevirt -o json | jq .spec.configuration.developerConfiguration.featureGates
selecting docker as container runtime
[
  "Snapshot"
]

$ cat <<EOF |  ./cluster-up/kubectl.sh apply -f -
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: csmall
spec:
  cpu:
    guest: 1
  memory:
    guest: 128Mi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros-datavolume-with-instancetype
  name: vm-cirros-datavolume-with-instancetype
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: cirros-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: rook-ceph-block 
      source:
        registry:
          url: docker://registry:5000/kubevirt/cirros-container-disk-demo:devel
  instancetype:
    kind: VirtualMachineInstancetype
    name: csmall
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-datavolume-with-instancetype
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: cirros-dv
        name: datavolumedisk1
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros-datavolume
  name: vm-cirros-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: cirros-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: rook-ceph-block 
      source:
        registry:
          url: docker://registry:5000/kubevirt/cirros-container-disk-demo:devel
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: cirros-dv
        name: datavolumedisk1
EOF

$ ./cluster-up/kubectl.sh get vms
selecting docker as container runtime
NAME                                     AGE     STATUS    READY
vm-cirros-datavolume                     2m57s   Stopped   False
vm-cirros-datavolume-with-instancetype   3m1s    Stopped   False

$ cat <<EOF | ./cluster-up/kubectl.sh apply -f -
---
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  name: snap-cirros-with-instnacetype
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros-datavolume-with-instancetype
---
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  name: snap-cirros       
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros-datavolume       
EOF

$ ./cluster-up/kubectl.sh get virtualmachinesnapshot
selecting docker as container runtime
NAME                            SOURCEKIND       SOURCENAME                               PHASE        READYTOUSE   CREATIONTIME   ERROR
snap-cirros                     VirtualMachine   vm-cirros-datavolume                     Succeeded    true         10s            
snap-cirros-with-instnacetype   VirtualMachine   vm-cirros-datavolume-with-instancetype   InProgress   false                       

 $ ./cluster-up/kubectl.sh get virtualmachinesnapshot/snap-cirros-with-instnacetype -o json | jq .status.conditions
selecting docker as container runtime
[
  {
    "lastProbeTime": null,
    "lastTransitionTime": "2022-09-08T15:24:40Z",
    "reason": "Source not locked",
    "status": "False",
    "type": "Progressing"
  },
  {
    "lastProbeTime": null,
    "lastTransitionTime": "2022-09-08T15:24:40Z",
    "reason": "Not ready",
    "status": "False",
    "type": "Ready"
  }
]

```

**Additional context**:

I've not tested with https://github.com/kubevirt/kubevirt/pull/8431 yet but I wonder if that might help the situation?

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): 1.24
- VM or VMI specifications:  see above
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @akrejcir

**What this PR does / why we need it**:

Previously the VirtualMachine validation webhook would attempt to apply
any referenced instancetype and preferences to the provided
VirtualMachineInstanceSpec within the VirtualMachine before validating
the contents. Doing so however would cause calls to
validateSnapshotStatus to fail when a snapshot was in progress as the
now updated VirtualMachineInstanceSpec differed from the original. In
issue https://github.com/kubevirt/kubevirt/issues/8435 this left the Snapshot controller unable to update the
VirtualMachine with a required finalizer, blocking the progress of the
overall snapshot.

This PR corrects this by applying any referenced instancetype and
preferences to a copy of the VirtualMachine and using this updated copy
to validate the fully rendered VirtualMachineInstanceSpec.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8435

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ShellyKa13** [comment]
This doesnt look like a good solution to me, it hides the real issue - you have the webhook denying the vm update because there is a change in the vm spec after you put the `snapshot in progress`, by changing the order you are allowing this update to happen which probably should not - if the update was only of the finalizer then the webhook would pass since it checks only for change in the spec and the finalizers are not on the spec.
Try to understand whats the difference in the spec the the webhook doesnt like.

**Comment by lyarwood** [comment]
> This doesnt look like a good solution to me, it hides the real issue - you have the webhook denying the vm update because there is a change in the vm spec after you put the `snapshot in progress`, by changing the order you are allowing this update to happen which probably should not - if the update was only of the finalizer then the webhook would pass since it checks only for change in the spec and the finalizers are not on the spec. Try to understand whats the difference in the spec the the webhook doesnt like.

Yeah apologies this was just a quick hack before I started looking into the underlying changes. Ultimately I think we should be patching the finalizer in here instead of the update that's likely rolling back changes already made to the VM. I'll rework this tomorrow and post a better fix and explanation of what's going on.

**Comment by lyarwood** [comment]
@ShellyKa13 thanks again for looking at this, `cmp.Diff` pointed out the issue pretty quickly as documented in the [issue](https://github.com/kubevirt/kubevirt/issues/8435#issuecomment-1245561518), the PR should hopefully resolve the bug now.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 1]
```diff
@@ -99,12 +99,16 @@ func (admitter *VMsAdmitter) Admit(ar *admissionv1.AdmissionReview) *admissionv1
 		return webhookutils.ToAdmissionResponseError(err)
 	}
 
-	causes := admitter.applyInstancetypeToVm(&vm)
+	// We apply any referenced instancetype and preferences early here to the VirtualMachine in order to
+	// validate the resulting VirtualMachineInstanceSpec below. As we don't want to persist these changes
+	// we pass a copy of the original VirtualMachine here and to the validation call below.
+	vmCopy := vm.DeepCopy()
+	causes := admitter.applyInstancetypeToVm(vmCopy)
```
Comment (ShellyKa13) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:106]: I think its better to move the 
vmCopy := vm.DeepCopy()
causes := admitter.applyInstancetypeToVm(vmCopy)
 to inside ValidateVirtualMachineSpec before ValidateVirtualMachineInstanceSpec

Comment (lyarwood) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:106]: That would mean refactoring `ValidateVirtualMachineSpec` quite heavily and adjusting callers such as `ValidateVMPoolSpec` as `applyInstancetypeToVm` needs a reference to the overall `VirtualMachine` in order to work, I don't think it's worth it IMHO.

File: tests/storage/snapshot.go [hunk 2]
```diff
@@ -1283,6 +1284,80 @@ var _ = SIGDescribe("VirtualMachineSnapshot Tests", func() {
...
+					}
+
+					// FIXME - The source remains unlocked here as the snapshot controller is unable to apply a finalizer to the VirtualMachine.
+					c1 := snapshot.Status.Conditions[0]
+					if c1.Type == snapshotv1.ConditionProgressing && c1.Status == corev1.ConditionFalse && strings.Contains(c1.Reason, "Source not locked") {
+						return true
+					}
+
+					return false
+				}, 90*time.Second, 10*time.Second).Should(BeTrue())
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go]: there is an initiative to make the errors more clear for example in eventually like this instead of using true/false use `satisfy` for example: https://github.com/kubevirt/kubevirt/pull/8509/commits/4addf000e93552eac8f046e98ed49f07b7a02ed2
it will give a better informative error message

File: pkg/storage/snapshot/source.go [hunk 3]
```diff
@@ -114,6 +112,7 @@ func (s *vmSnapshotSource) Lock() (bool, error) {
 	}
 
 	if !controller.HasFinalizer(vmCopy, sourceFinalizer) {
+		log.Log.Infof("Adding VM snapshot finalizer to %s", s.vm.Name)
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/source.go:115]: +1

File: tests/storage/snapshot.go [hunk 4]
```diff
@@ -1335,27 +1326,11 @@ var _ = SIGDescribe("VirtualMachineSnapshot Tests", func() {
 				}
 			})
 
-			It("Bug #8435 - should create a snapshot successfully, currently fails as source remains locked", func() {
+			It("Bug #8435 - should create a snapshot successfully", func() {
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go:1329]: should remove the bug number? if this commit fixes it?

Comment (lyarwood) [reply tests/storage/snapshot.go:1329]: Happy to if people don't think it's useful, my entire approach here is based on what [I previously did in the OpenStack Nova project](https://github.com/openstack/nova/commits/master/nova/tests/functional/regressions/test_bug_1937084.py) and might not be suitable for this project so I'm happy to change if required.

**Comment by ShellyKa13** [comment]
Other then the bug number in the test name it look good to me
