### PR TITLE
Fix LimitRange namespace bug

### LINKED ISSUE #7681: Kubevirt VM limits require Namespace to be specified in the manifest when creating
**What happened**:

The following tests in tests/vmi_configuration_test.go:
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace memory limits lower than VMI required memory
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace cpu limits lower than VMI required cpu
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace limits higher than VMI requests

Require metadata.namespace to be specified when a VM(I) is created, becuse the limits are applied/enforced in webhook.
The webhook needs to know the resource namespace in order to apply/enforce the namespace defaults.

This limitation of the feature became apparent in a PR that substitutes VMI creation with functions from libvmi, which do not specify the Namespace explicitly.
- https://github.com/kubevirt/kubevirt/pull/7545

**What you expected to happen**:
We should consider implementing the feature in a controller, instead of in a webhook, or document the limitation, if
we decide to keep it in webhook.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by xpivarc**
**What this PR does / why we need it**:
LimitRange integration had long standing bug
that caused every VMI to require namespace to
be set.

This also fixes situations where we don't apply
limits to VMI if the VMI is missing the label.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7681

**Special notes for your reviewer**:

**Release note**:

```release-note
Bug-fix: LimitRange integration now works when VMI is missing namespace
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Presets integration has same issue

File: pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go [hunk 1]
```diff
@@ -44,10 +44,10 @@ func isResourceRequirementMissing(resourceRequirements kubev1.ResourceRequiremen
 	return memoryOrCpuIsMissing(resourceRequirements.Limits) || memoryOrCpuIsMissing(resourceRequirements.Requests)
 }
 
-func applyNamespaceLimitRangeValues(vmi *kubev1.VirtualMachineInstance, limitrangeInformer cache.SharedIndexInformer) {
+func applyNamespaceLimitRangeValues(vmi *kubev1.VirtualMachineInstance, limitrangeInformer cache.SharedIndexInformer, namespace string) {
 	// Copy namespace limits (if exist) to the VM spec
 	if isResourceRequirementMissing(vmi.Spec.Domain.Resources) {
```
Comment (alicefr) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:49]: Are those limits always specified on the namespace? I assume yes, but worth asking :)

Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:49]: No, but that's alright as we will just not apply anything.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go [hunk 2]
```diff
@@ -44,10 +44,10 @@ func isResourceRequirementMissing(resourceRequirements kubev1.ResourceRequiremen
 	return memoryOrCpuIsMissing(resourceRequirements.Limits) || memoryOrCpuIsMissing(resourceRequirements.Requests)
 }
 
-func applyNamespaceLimitRangeValues(vmi *kubev1.VirtualMachineInstance, limitrangeInformer cache.SharedIndexInformer) {
+func applyNamespaceLimitRangeValues(vmi *kubev1.VirtualMachineInstance, limitrangeInformer cache.SharedIndexInformer, namespace string) {
```
Comment (vladikr) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: can't we take the namespace from *VMI?

**Comment by vladikr** [comment]
In which situations the VMI obejct will miss a namespace?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go (hunk 2 above)
Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: No, the VMI object can be missing the namespace when it's being created.

Comment (fossedihelm) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: @xpivarc Since vmi namespace, if present, must match the request namespace, it might not be correct to simply set `newVMI.Namespace = ar.Request.Namespace`? Thanks

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go [hunk 3]
```diff
@@ -81,8 +81,10 @@ func (mutator *VMIsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1
 			}
 		}
 
+		namespace := ar.Request.Namespace
```
Comment (vladikr) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go:84]: why just not store this in the VMI object?

**Review by fossedihelm — APPROVED** [review]

File: pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go (hunk 2 above)
Comment (vladikr) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: Right, but if we know the namespace from `ar.Request.Namespace` why can't we just set it in the VMI object?

Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: Well, I don't think we should do it. Let's consider the following case. The user has a VMI YAML with namespace `custom` but his `kubectl` is set to work with namespace `test`. What namespace is the intended namespace to be used? Further, this is how any other Kubernetes object would behave.

Comment (vladikr) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: I'm only referring to the case when there is no namespace set in the vmi object.

Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: What is the benefit of handling it if Kubernetes does it for us?

Comment (vladikr) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: I think if we don't, then it creates some kind of confusion.. at least for me. 

I guess what I don't understand is: if `vmi.Namespace` != `ar.Request.Namespace` why are we allowed to use the limits from `ar.Request.Namespace` ?

Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: The request will be denied in the end so I don't see harm here.

Comment (xpivarc) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go:47]: @vladikr pushed test for this

**Comment by xpivarc** [comment]
@fossedihelm PTAL

**Comment by fossedihelm** [comment]
@xpivarc Thanks
/lgtm
/retest-required

**Comment by vladikr** [comment]
/lgtm 
sorry for the delay
