### PR TITLE
Increase memory limit for kubevirt-infra pod

### LINKED ISSUE #3029: OOMKiller shutting down kubevirt-infra sidecar causing VM shutdown
**BUG REPORT**:

/kind bug

**What happened**:

Running on Azure, sequence of events was the following.

- kubevirt-infra container died with OOMKiller
- VM running in hypervisor did clean shutdown
- VMI vanished

**What you expected to happen**:

Neither of the first two.

- The OOMKiller is likely because the pod spec for the kubevirt-infra container has slightly too low a limit on memory. Azure appears to be a bit trigger happy enforcing this limit.
- The clean shutdown is rather odd. I'd guess that the underlying logic is that with kubevirt-infra having blown up, the handler decides that the VMI is sick, sends it a shutdown signal and blows it away. That is arguably correct behaviour given the initial error.

**How to reproduce it (as minimally and precisely as possible)**:

The repro scenario appears to be to run on Azure (or somebody else would have noticed it!), and have a readiness probe on some port. The time from VMI creation to stopping is very uneven. I've seen it vary from a few minutes (so VM doesn't even always finish booting) to a few hours. There's some correlation in timing which I think is some Azure artifact.

I'm happy to test a fix or attempt to repro with a debug build.

**Anything else we need to know?**:

I just realised I am not on the latest kubevirt version; will repro on 0.25 today.

If you can tell me at how to change the memory limit on the sidecar, I'd be happy to test if just raising it slightly helps; I'm 90% sure that would make the problem go away.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.22.0
- Kubernetes version (use `kubectl version`): 
- VM or VMI specifications: 
- Cloud provider or hardware configuration: AKS, standard cluster
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by plwhite**
**What this PR does / why we need it**:

The OOM Killer on Azure is occasionally killing the kubevirt-infra sidecar, causing VMIs to shutdown without warning at random intervals. This fix resolves that problem by increasing the memory limit.

**Which issue(s) this PR fixes** 
Fixes #3029

**Special notes for your reviewer**:
I have manually tested on an Azure platform that I am testing with, and this appears to completely resolve the issue (random shutdowns reduced from every hour or two to none in a couple of days, and still running).

**Release note**:
NONE

### CODE REVIEW

**Comment by plwhite** [comment]
Fixes bug #3029

**Comment by danielBelenky** [comment]
/retest

thanks for the contribution :)

would you mind signing your commit? :)

**Comment by plwhite** [comment]
I haven't got authorisation to sign the CLA yet. I expect this to be just a formality, but there may be a slight delay until the right boxes are ticked here.

File: pkg/virt-controller/services/template.go [hunk 1]
```diff
@@ -870,7 +870,7 @@ func (t *templateService) RenderLaunchManifest(vmi *v1.VirtualMachineInstance) (
 			Resources: k8sv1.ResourceRequirements{
 				Limits: map[k8sv1.ResourceName]resource.Quantity{
 					k8sv1.ResourceCPU:    resource.MustParse("1m"),
-					k8sv1.ResourceMemory: resource.MustParse("12Mi"), // this is the minimum memory limit for cri-o!
+					k8sv1.ResourceMemory: resource.MustParse("40Mi"), // this is the minimum memory limit for cri-o!
```
Comment (slintes) [inline pkg/virt-controller/services/template.go]: Can you remove the comment please? 12Mi was a real minimum limit accepted by cri-o. If we go beyond that. it is not relevant anymore.

**Comment by slintes** [comment]
> I haven't got authorisation to sign the CLA yet. I expect this to be just a formality, but there may be a slight delay until the right boxes are ticked here.

that DCO thing is about signing off commits with `git commit -s` only, see https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s

/ok-to-test

**Comment by rmohr** [comment]
We should also consider moving forward with #2844. Totally fine for me to take this one in, but in general having to request 40Mi is a little bit extreme.

File: pkg/virt-controller/services/template.go (hunk 1 above)
Comment (plwhite) [reply pkg/virt-controller/services/template.go]: Done.

**Comment by plwhite** [comment]
Apologies for the force-push - I had to add the signed-off-by, and in the process I fixed the comment.

**Comment by slintes** [comment]
formatting of the NONE release note seems to be broken, let's fix it with

/release-note-none

**Comment by plwhite** [comment]
I don't see how I could have broken that test case, so going to retest as it suggests.
/retest

**Comment by rmohr** [comment]
@plwhite yep all is good. The tests are just merge-gated, so once a PR gets merged all tests will run again, and sometimes a lane fails, but the retest bot will also take care of writing retest. Just needs some time.
