### PR TITLE
unit test, isolation: Make test agnostic to virt-launcher process name

### LINKED ISSUE #7878: Adapt unit-test detector_test.go to use the new virt-launcher naming
**What happened**:
Since https://github.com/kubevirt/kubevirt/pull/7451, we don't have a forked process named
`*-no-fork`
There is still a unit test that uses the old naming in it's stubs.

**What you expected to happen**:
`pkg/virt-handler/isolation/detector_test.go` should be updated according
the new namings.

**How to reproduce it (as minimally and precisely as possible)**:
Just see the code.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Since https://github.com/kubevirt/kubevirt/pull/7451
virt-launcher processes names were changed.
Adapt the unit test accordingly, by being agnostic
to the binary names, as it doesn't affect the test
as long as the stubs don't have the expected qemu
names.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7878 

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by iholder-redhat** [comment]
Thanks @oshoval!

Two thoughts:
1. IIUC, the binary argument isn't relevant for the test at all, therefore what do we gain by keeping the exact flags? This PR emphasizes that this info is redundant for the test, as not only did it not effect it but also demands updating irrelevant information. Therefore I suggest to remove this info. Instead, I suggest to have processes with fake names.

I imagine something like:
```go

fakeProcess1 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-1"}
fakeProcess2 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-2"}
fakeProcess3 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-3"}

fakeProcesses := []ps.Process{
	fakeProcess1,
	fakeProcess2,
	fakeProcess3}
```

This way the test would have still been 100% valid and nothing would need to change.

2. I would add entries for the opposite cases as well - where the QEMU process is not found. Otherwise, if we have a bug in which the QEMU is always reported to be found, we wouldn't cover it with these tests.

**Comment by oshoval** [comment]
> Thanks @oshoval!
> 
> Two thoughts:
> 
> 1. IIUC, the binary argument isn't relevant for the test at all, therefore what do we gain by keeping the exact flags? This PR emphasizes that this info is redundant for the test, as not only did it not effect it but also demands updating irrelevant information. Therefore I suggest to remove this info. Instead, I suggest to have processes with fake names.
> 
> I imagine something like:
> 
> ```go
> fakeProcess1 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-1"}
> fakeProcess2 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-2"}
> fakeProcess3 := ProcessStub{pid: rand.Int(100), ppid: rand.Int(100), binary: "fake-process-3"}
> 
> fakeProcesses := []ps.Process{
> 	fakeProcess1,
> 	fakeProcess2,
> 	fakeProcess3}
> ```
> 
> This way the test would have still been 100% valid and nothing would need to change.
> 

We can use fake names indeed, but note that the ppid can't be fake, as the search is according the ppid

> 2. I would add entries for the opposite cases as well - where the QEMU process is not found. Otherwise, if we have a bug in which the QEMU is always reported to be found, we wouldn't cover it with these tests.

There is a test there at the end for this case

**Comment by iholder-redhat** [comment]
> We can use fake names indeed, but note that the ppid can't be fake, as the search is according the ppid

Got you :+1: 
 
> There is a test there at the end for this case

Right, I've missed it. Thanks!

**Comment by oshoval** [comment]
Addressed comments

**Comment by iholder-redhat** [comment]
Thanks very much! Next time we wouldn't have to update the binary flags again :)
Great job @oshoval!

/lgtm

File: pkg/virt-handler/isolation/detector_test.go [hunk 1]
```diff
@@ -120,16 +120,16 @@ var _ = Describe("Isolation Detector", func() {
...
-		virtLauncherProc,
-		virtLauncherForkedProc,
-		libvirtdProc}
+		fakeProcess1,
+		fakeProcess2,
+		fakeProcess3}
 
-	qemuKvmProc := ProcessStub{pid: 101, ppid: 1, binary: "qemu-kvm"}
-	qemuSystemProc := ProcessStub{pid: 101, ppid: 1, binary: "qemu-system"}
+	qemuKvmProc := ProcessStub{pid: 101, ppid: virtLauncherPid, binary: "qemu-kvm"}
```
Comment (xpivarc) [inline pkg/virt-handler/isolation/detector_test.go:131]: Should it be 226?

Comment (oshoval) [reply pkg/virt-handler/isolation/detector_test.go:131]: qemu-kvm parent is virt-launcher, else it won't find it

**Review by enp0s3 — COMMENTED** [review]
/approve
/hold
@xpivarc feel free to unhold in case your comment was addresed

**Comment by oshoval** [comment]
> /approve /hold @xpivarc feel free to unhold in case your comment was addresed

Note that it is an non issue, and also not related to the scope of this PR

**Comment by oshoval** [comment]
Not related to this PR, just checking that we can still trigger this manually

/test pull-kubevirt-e2e-k8s-1.23-sig-compute-cgroupsv2
