### PR TITLE
fix virt-launcher panic after migration cancellation on crio

### LINKED ISSUE #2243: target POD remains in Error state after migration cancellation on crio
/kind bug

**What happened**:
In some cases, destination virt-launcher panics after migration cancellation, on CRIO. 
```
{"component":"virt-launcher","level":"info","msg":"stopping cmd server","pos":"server.go:313","timestamp":"2019-05-03T01:37:03.743387Z"}                                                                          
{"component":"virt-launcher","level":"error","msg":"Connection to libvirt lost","pos":"libvirt.go:257","timestamp":"2019-05-03T01:37:07.607429Z"}                                                                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x519680]

goroutine 23 [running]:
kubevirt.io/kubevirt/vendor/github.com/libvirt/libvirt-go.(*Connect).IsAlive(0x0, 0x1638220, 0xc00018b3b0, 0x1)                                                                                                   
        connect.go:568 +0x40
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cli.(*LibvirtConnection).installWatchdog.func1(0xc0002b4420, 0x2540be400)                                                                                         
        pkg/virt-launcher/virtwrap/cli/libvirt.go:248 +0xff
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cli.(*LibvirtConnection).installWatchdog
        pkg/virt-launcher/virtwrap/cli/libvirt.go:238 +0x49
```

### PR DESCRIPTION
**Pull request by vladikr**
**What this PR does / why we need it**:
In some cases, destination virt-launcher panics after migration cancellation, on CRIO.
This PR handles the panic and let the virt-launcher exit cleanly.

Fixes #2243 

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-launcher/virtwrap/cli/libvirt.go [hunk 1]
```diff
@@ -243,9 +247,12 @@ func (l *LibvirtConnection) installWatchdog(checkInterval time.Duration) {
 				return
 
 			case <-time.After(checkInterval):
-				l.reconnectIfNecessary()
-
-				alive, err := l.Connect.IsAlive()
+				var alive bool
+				var err error
+				err = l.reconnectIfNecessary()
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/cli/libvirt.go]: oops... yeah we should have been checking this for an error all along. good catch

**Comment by davidvossel** [comment]
@vladikr do you have a way to reproduce this? Does this have something to do with attempting to shutdown a VMI while migration is taking place?  I'm just curious if there's some issue with shtudown order of libvirt or something that's triggered this.

**Comment by vladikr** [comment]
> @vladikr do you have a way to reproduce this? Does this have something to do with attempting to shutdown a VMI while migration is taking place? I'm just curious if there's some issue with shtudown order of libvirt or something that's triggered this.

Yeah, I can reproduce it, but only on cri-o for some reason. I thought that maybe it takes longer for the watchdog ticker to exit. But I'm not sure yet.
