### PR TITLE
fix(preference): Ensure memory requirements are respected when no memory is specified

### LINKED ISSUE #14551: Creating a VirtualMachine with an instance type that doesn't exist and preference that has resource requirements causing a nil pointer error within virt-api
/area instancetype

**What happened**:
```
$ virtctl create vm --name test --instancetype u1.foo --preference fedora | ./kubevirtci/cluster-up/kubectl.sh apply -f -
selecting podman as container runtime
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "virtualmachine-validator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachines-validate?timeout=10s": EOF
```

```
│ {"component":"virt-api","kind":"VirtualMachine","level":"warning","msg":"ignoring err \"virtualmachineclusterinstancetypes.instancetype.kubevirt.io \\\"u1.foo\\\" not found\" when looki │
│ ng for instance type","name":"test","namespace":"default","pos":"admitter.go:88","timestamp":"2025-04-22T12:47:12.665898Z","uid":"d0d2ee03-6d1c-48b9-84d7-c78f33dcc247"}                  │
│ {"caller":"http: panic serving 192.168.66.101:11548","component":"virt-api","level":"info","msg":"runtime error: invalid memory address or nil pointer dereference\ngoroutine 651 [runnin │
│ g]:\nnet/http.(*conn).serve.func1()\n\tbazel-out/k8-fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:1947 +0xbe\npanic({0x24a4420?, 0x440b5d0?})\n │
│ \tbazel-out/k8-fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/runtime/panic.go:785 +0x132\nkubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/api/resource.(*Quant │
│ ity).Cmp(0xc00251b640?, {{0x80000000, 0x0}, {0x0}, {0xc003842cfc, 0x3}, {0x28b8f37, 0x8}})\n\tvendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:610 +0x34\nkubevirt.io/kubevirt/pkg │
│ /instancetype/preference/requirements.checkMemory(0x0?, 0xc006f5f188, 0xc0042fccf0?)\n\tpkg/instancetype/preference/requirements/memory.go:48 +0x191\nkubevirt.io/kubevirt/pkg/instancety │
│ pe/preference/requirements.(*checker).Check(0xc00251b628?, 0x0?, 0xc006f5f188?, 0xc0042fccf0?)\n\tpkg/instancetype/preference/requirements/checker.go:50 +0x75\nkubevirt.io/kubevirt/pkg/ │
│ virt-api/webhooks/validating-webhook/admitters.(*VMsAdmitter).Admit(0xc002d596d0, {0x2caefd0, 0xc002d59680}, 0xc005ca2270)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admi │
│ tter.go:127 +0x34c\nkubevirt.io/kubevirt/pkg/util/webhooks/validating-webhooks.Serve({0x2c9f8d0, 0xc0042b4b60}, 0xc0042b3b80, {0x2c86cc0, 0xc002d596d0})\n\tpkg/util/webhooks/validating- │
│ webhooks/validating-webhook.go:68 +0xee\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook.ServeVMs({0x2c9f8d0, 0xc0042b4b60}, 0xc0042b3b80, 0xc003b06630, {0x2ce7f80, 0xc000 │
│ 27b680}, 0xc0040a6a80, 0xc001a2e630)\n\tpkg/virt-api/webhooks/validating-webhook/validating-webhook.go:62 +0x127\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerValidatingWebho │
│ oks.func3({0x2c9f8d0?, 0xc0042b4b60?}, 0x872e27?)\n\tpkg/virt-api/api.go:895 +0x38\nnet/http.HandlerFunc.ServeHTTP(0x45683a0?, {0x2c9f8d0?, 0xc0042b4b60?}, 0x3?)\n\tbazel-out/k8-fastbui │
│ ld-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:2220 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x411e85?, {0x2c9f8d0, 0xc0042b4b60}, 0xc0042b3b80)\n\tbazel- │
│ out/k8-fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:2747 +0x1ca\nnet/http.serverHandler.ServeHTTP({0x2c8f218?}, {0x2c9f8d0?, 0xc0042b4b60?}, 0 │
│ x6?)\n\tbazel-out/k8-fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:3210 +0x8e\nnet/http.(*conn).serve(0xc000808120, {0x2caef98, 0xc0030d5b00})\ │
│ n\tbazel-out/k8-fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:2092 +0x5d0\ncreated by net/http.(*Server).Serve in goroutine 142\n\tbazel-out/k8 │
│ -fastbuild-ST-0911a98f3d86/bin/external/io_bazel_rules_go/stdlib_/src/net/http/server.go:3360 +0x485","pos":"stdlib.go:105","timestamp":"2025-04-22T12:47:12.666872Z","ts":"2025/04/22 12 │
│ :47:12"}      
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @0xFelix 
/cc @geetikakay 

### What this PR does

As set out in bug #14551 the VM admission webhook could previously crash with a nil-pointer error while asserting that the VM meets the memory requirements of a referenced preference.

This change corrects this by rewriting the checkMemory function to always default to a `0Mi` resource quantity while also fully asserting that values from the VMI spec (spec.template.spec.domain.memory.guest) are non-nil before use.

Support for validating preference requirements against memory provided within the VM by resource requests and various other clean ups are left for a follow up changes to allow this fix to be backported.

Fixes #14551

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/instancetype/preference/requirements/memory.go [hunk 1]
```diff
@@ -37,17 +40,23 @@ func checkMemory(
...
-		return conflict.Conflicts{conflict.New("spec", "instancetype")},
-			fmt.Errorf(InsufficientInstanceTypeMemoryResourcesErrorFmt, instancetypeMemory, preferenceMemory)
+	errFmt := InsufficientVMMemoryResourcesErrorFmt
+	errConflict := conflict.New("spec", "template", "spec", "domain", "memory")
+	providedMemory := pointer.P(resource.MustParse("0Mi"))
+
+	if instancetypeSpec != nil {
+		errConflict = conflict.New("spec", "instancetype")
+		errFmt = InsufficientInstanceTypeMemoryResourcesErrorFmt
+		providedMemory = &instancetypeSpec.Memory.Guest
```
Comment (jcanocan) [inline pkg/instancetype/preference/requirements/memory.go:50]: Silly question, it is possible to specify a instanceType without `Memory.guest`? If possible, we should check if this is nil?

**Review by 0xFelix — COMMENTED** [review]
/approve

File: pkg/instancetype/preference/requirements/memory.go (hunk 1 above)
Comment (geetikakay) [reply pkg/instancetype/preference/requirements/memory.go:50]: afaik spec.Memory.guest is mandatory

Comment (lyarwood) [reply pkg/instancetype/preference/requirements/memory.go:50]: Yeah `spec.{cpu,memory}.guest` are both required within an instance type at the moment.

Comment (jcanocan) [reply pkg/instancetype/preference/requirements/memory.go:50]: Thanks for the clarifications!
