### PR TITLE
Fix version clash in sidecar manager

### LINKED ISSUE #2052: Mixing sidecar versions leads to endless loop
**BUG REPORT**:
/kind bug

**What happened**:

Mixing sidecare functions (`OnDefineDomain`and `PreCloudInitIso`) in one sidecare leads to an endless loop during VM / virt-launcher pod creation:

```
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvmi-nocloud-with-sidecare","namespace":"default","pos":"manager.go:475","timestamp":"2019-02-25T07:59:33.714513Z","uid":"07c1f97d-38d3-11e9-a564-1866daf32f78"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvmi-nocloud-with-sidecare","namespace":"default","pos":"manager.go:486","timestamp":"2019-02-25T07:59:33.714800Z","uid":"07c1f97d-38d3-11e9-a564-1866daf32f78"}
{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/default/testvmi-nocloud-with-sidecare/noCloud.iso","pos":"cloud-init.go:284","timestamp":"2019-02-25T07:59:33.728067Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-ephemeral-disks/container-disk-data/default/testvmi-nocloud-with-sidecare/disk_containerdisk/disk-image.qcow2 set to none","pos":"converter.go:165","timestamp":"2019-02-25T07:59:33.728272Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-ephemeral-disks/cloud-init-data/default/testvmi-nocloud-with-sidecare/noCloud.iso set to none","pos":"converter.go:165","timestamp":"2019-02-25T07:59:33.728324Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvmi-nocloud-with-sidecare","namespace":"default","pos":"server.go:123","reason":"rpc error: code = Unimplemented desc = unknown service kubevirt.hooks.v1alpha1.Callbacks","timestamp":"2019-02-25T07:59:33.729391Z","uid":"07c1f97d-38d3-11e9-a564-1866daf32f78"}
```

**What you expected to happen**:

New version `v1alpha2` is used also for `OnDefineDomain`

**How to reproduce it (as minimally and precisely as possible)**:

Add `PreCloudInitIso` to smbios example.

**Anything else we need to know?**:
Hooks manager uses v1 client instead of callback.Version for `OnDefineDomain`.

**Environment**:
master branch

### PR DESCRIPTION
**Pull request by mkoderer**
**What this PR does / why we need it**:
Mixing grpc versions caused an endless failure loop during vm creation.
**Which issue(s) this PR fixes**:
Fixes #2052

**Special notes for your reviewer**:
I am open for suggestions how to beautify the code in the hook manager.
Currently every version needs to be seperated which leads to many lines of boilerplate code..
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

File: pkg/hooks/manager.go [hunk 1]
```diff
@@ -196,18 +196,30 @@ func (m *Manager) OnDefineDomain(domainSpec *virtwrapApi.DomainSpec, vmi *v1.Vir
...
 				ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
 				defer cancel()
-				result, err := client.OnDefineDomain(ctx, &hooksV1alpha1.OnDefineDomainParams{
-					DomainXML: domainSpecXML,
-					Vmi:       vmiJSON,
-				})
-				if err != nil {
-					return "", err
+
+				if callback.Version == hooksV1alpha1.Version {
```
Comment (gonzolino) [inline pkg/hooks/manager.go]: To make it easier to add new versions later on, it might be better to use a switch statement here instead of an if-else.

Like so:
```
switch callback.Version {
    case hooksV1alpha1.Version:
        ...
    case hooksV1alpha2.Version:
        ...
    default:
        return nil, fmt.Error(...)
}
```

So to add a new version you could just add a new case statement, and if the version is unknown you get a clear error stating what the problem is.

Comment (greg-bock) [reply pkg/hooks/manager.go]: There are no grpc definitions for OnDefineDomain in valpha1. I'm really not sure why it is being versioned this way when things are only added and not changed tbh. @phoracek may be the best person to weigh in.

Comment (mkoderer) [reply pkg/hooks/manager.go]: Yep, I don't believe that this concept is really working out. If every new version needs to have the same boilerplate code this will be huge and not readable..

File: pkg/hooks/manager.go [hunk 2]
```diff
@@ -196,18 +196,30 @@ func (m *Manager) OnDefineDomain(domainSpec *virtwrapApi.DomainSpec, vmi *v1.Vir
...
+					client := hooksV1alpha1.NewCallbacksClient(conn)
+					result, err := client.OnDefineDomain(ctx, &hooksV1alpha1.OnDefineDomainParams{
+						DomainXML: domainSpecXML,
+						Vmi:       vmiJSON,
+					})
+					if err != nil {
+						return "", err
+					}
+					domainSpecXML = result.GetDomainXML()
+				} else {
```
Comment (greg-bock) [inline pkg/hooks/manager.go]: Do an else if here and check for v2 so the final else/panic will trigger if something bad did happen.

**Comment by rmohr** [comment]
ci test please

File: pkg/hooks/manager.go (hunk 1 above)
Comment (rmohr) [reply pkg/hooks/manager.go]: I agree. We will soon introduce a versioned communication channel betwen virt-handler and virt-launcher too. @slintes looks into that. He will also there use grpc itself to do the whole negotiation.

**Comment by rmohr** [comment]
@mkoderer can you cherry-pick https://github.com/rmohr/kubevirt/commit/e470307bf6497c1ca3ce760e34e201517624d8e7 on this PR? It contains a functional test.

**Comment by gonzolino** [comment]
ci test please

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
hm, I am puzzled regarding to the test results. I saw repeatedly that it took hours to actually compile and start teh tests. Let's try again, looks like an infra issue.

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
Ok, the CI issues are still ongoing but the relevant tests pass.
