### PR TITLE
vmi update admission webhook: fix volume miscount when using filesystems

### LINKED ISSUE #9653: If virtiofs filesystem VPCs are used, disk hotplug fails on validation
**What happened**:

Right now we only allow hot-plugging through our hotplug subresource. When this happens, the actual spec updates are done by our internal user. This triggers in turn additional validation logic:

```go
		if webhooks.IsKubeVirtServiceAccount(ar.Request.UserInfo.Username) {
			hotplugResponse := admitHotplug(newVMI.Spec.Volumes, oldVMI.Spec.Volumes, newVMI.Spec.Domain.Devices.Disks, oldVMI.Spec.Domain.Devices.Disks, oldVMI.Status.VolumeStatus, newVMI, admitter.ClusterConfig)
			if hotplugResponse != nil {
				return hotplugResponse
			}
		}
```

This additional validation check does not consider `spec.domain.devices.filesystems` and will fail because it thinks that one volume does not have a source volume defined:

```json
{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance kubevirt-test-privileged2/testvmi-jv66c","pos":"vmi.go:306","reason":"admission webhook \"virtualmachineinstances-update-validator.kubevirt.io\" denied the request: number of disks (1) does not equal the number of volumes (2)","timestamp":"2023-04-22T18:55:14.513147Z"}
```	

This was discovered as a side-effect of a mistake in a PR.

 * Example job: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8293/pull-kubevirt-e2e-k8s-1.24-sig-compute/1649835730626678784
 * Example virt-controller log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8293/pull-kubevirt-e2e-k8s-1.24-sig-compute/1649835730626678784/artifacts/k8s-reporter-parallel/1/pods/1_kubevirt_virt-controller-7b6d7944fd-f4744-virt-controller.log

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with a virtiofs filesystem attached. Then try to hotplug a disk.
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by epanter-mw**
**What this PR does / why we need it**:

Volumes can be used for both filesystem and disk devices. When validating the VMI's volume count, both need to be considered.

The miscount causes problems when when hotplugging disks to a virtual machine that also uses virtiofs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9653

**Special notes for your reviewer**:

Enabling the `ExperimentalVirtiofsSupport` feature gate during tests was necessary to crate VMIs with filesystems. I am unsure if that is the desired way to do this.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
Hey @epanter-mw Thanks for the PR and happy to see your first contribution!
Let's first check the tests
/test all
/cc @enp0s3

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go [hunk 1]
```diff
@@ -51,7 +51,9 @@ var _ = Describe("Validating VMIUpdate Admitter", func() {
 		},
 		Spec: v1.KubeVirtSpec{
 			Configuration: v1.KubeVirtConfiguration{
-				DeveloperConfiguration: &v1.DeveloperConfiguration{},
+				DeveloperConfiguration: &v1.DeveloperConfiguration{
```
Comment (xpivarc) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go:54]: We should not enable the feature gate for all tests here. We should change
`config, _, _ := testutils.NewFakeClusterConfigUsingKV(kv)`
to 
`config, _, informer:= testutils.NewFakeClusterConfigUsingKV(kv)`

Then we can have the dedicated context to test `ExperimentalVirtiofsSupport` feature gate. In the context we can do
```
testutils.UpdateFakeKubeVirtClusterConfig(kvInformer, &v1.KubeVirt{
			Spec: v1.KubeVirtSpec{
				Configuration: v1.KubeVirtConfiguration{
					DeveloperConfiguration: &v1.DeveloperConfiguration{
                                            FeatureGates: []string{"ExperimentalVirtiofsSupport"},
                                        },
				},
			},
		})
```

**Review by xpivarc — COMMENTED** [review]
Thank you for your contribution. I have one change request.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go (hunk 1 above)
Comment (epanter-mw) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go:54]: Is it acceptable to move the whole existing `DescribeTable("Should return proper admission response", ...)` into this new context or should I only move the `Entry()`s that actually *need* the feature gate into the dedicated context (using a second, similar `DescribeTable(...)`)?

Comment (xpivarc) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go]: We should extract the function that is now inlined as an argument to `DescribeTable`:
```
DescribeTable("Should return proper admission response", func(newVolumes, oldVolumes []v1.Volume, newDisks, oldDisks []v1.Disk, filesystems []v1.Filesystem, volumeStatuses []v1.VolumeStatus, expected *admissionv1.AdmissionResponse) {
newVMI := api.NewMinimalVMI("testvmi")
```

to  
```
func testResponse(newVolumes, oldVolumes []v1.Volume, newDisks, oldDisks []v1.Disk, filesystems []v1.Filesystem, volumeStatuses []v1.VolumeStatus, expected *admissionv1.AdmissionResponse) {
```
and then we can modify the existing `DescribeTable` to

`DescribeTable("Should return proper admission response",  testResponse`

and create new `Context` where we can put new `It("something", testResponse)` or `DescribeTable`.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go [hunk 2]
```diff
@@ -595,9 +620,42 @@ var _ = Describe("Validating VMIUpdate Admitter", func() {
...
-			makeExpected("number of disks (1) does not equal the number of volumes (2)", "")),
+			makeExpected("number of disks and filesystems (1) does not equal the number of volumes (2)", "")),
 	)
 
+	Context("with filesystem devices", func() {
+		BeforeEach(func() {
+			enableFeatureGate(virtconfig.VirtIOFSGate)
+		})
+
+		DescribeTable("Should return proper admission response", func(newVolumes, oldVolumes []v1.Volume, newDisks, oldDisks []v1.Disk, filesystems []v1.Filesystem, volumeStatuses []v1.VolumeStatus, expected *admissionv1.AdmissionResponse) {
```
Comment (xpivarc) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go:631]: This looks good as well, let me know if you want to extract the function or not and I will review after your response.

Comment (epanter-mw) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go]: Extracting the function looks cleaner IMO. You can review again

Comment (epanter-mw) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go]: @xpivarc can you take another look?

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by akalenyu — APPROVED** [review]
thank you!

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go (hunk 2 above)
Comment (xpivarc) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go]: Thanks!
