### PR TITLE
Tools: fix unit-test and ensure execution

### LINKED ISSUE #12790: `./tools` folder fails to build with unit tests that are never triggered
**What happened**:
As @akalenyu mentions in [this comment](https://github.com/kubevirt/kubevirt/pull/12778#discussion_r1751678770), `./tools` fails to build:
```
kubevirt/tools/util/marshaller_test.go:32:195: not enough arguments in call to components.NewHandlerDaemonSet
```

In addition, as he's pointing out, these tests are not attempted to ever run:
https://github.com/kubevirt/kubevirt/blob/941b04cb9f90745ae2038b13c8bb82eea55a16dd/hack/bazel-test.sh#L7

To add an insult to injury, these are lacking the `*_suite_test.go` that's required to make these tests runnable.

**What you expected to happen**:
The tests should either be able to build and run via `make test` or removed.

**How to reproduce it (as minimally and precisely as possible)**:
Trying to build `./tools`

### PR DESCRIPTION
**Pull request by mosheyaku**
### What this PR does

Before this PR:
- The `marshaller_test.go` test file failed to compile due to missing parameters in the `NewHandlerDaemonSet` function call.
- Tests under the `tools` directory were not included in the Bazel test runs.

After this PR:
- Fixed the compilation error in `marshaller_test.go` by providing all required arguments to `NewHandlerDaemonSet`.
- Updated the Bazel test script to include the `tools` directory, ensuring coverage of all testable components.

Fixes #12790

### Release note
```release-note
None

### CODE REVIEW

**Comment by dasionov** [comment]
Hi @mosheyaku Thank you for addressing this!
could you rename the PR title please?

**Comment by mosheyaku** [comment]
> Hi @mosheyaku Thank you for addressing this! could you rename the PR title please?

Thanks, done.

**Comment by dasionov** [comment]
I Don't see the `test_suite` file for the `marsheler_test.go`, i guess it's because we are not compiling the tools target.. so make generate skips this part..

let's see if it's running in the unit-test lane for now
/ok-to-test

File: tools/tools.go [hunk 1]
```diff
@@ -1,8 +0,0 @@
-package tools
-
-// Keep a reference to tool binaries in vendor, so that go mod keeps them
-import (
-	_ "github.com/onsi/ginkgo/v2/ginkgo"
-	_ "github.com/wadey/gocovmerge"
-	_ "mvdan.cc/sh/v3/cmd/shfmt"
-)
```
Comment (dasionov) [inline tools/tools.go:8]: I understand that this file was removed because it wasn’t compiling, I believe it's not by a mistake It was originally introduced in [commit](https://github.com/kubevirt/kubevirt/pull/4051/commits/ac592cecf4f6e38dc0350f3ed3dba457750435e2) introduces this file and it explained it for vendoring of this imports
Please re-add the file, and make sure to run `make format` so that the corresponding `BUILD.bazel` entry is regenerated as well.

File: hack/bazel-test.sh [hunk 2]
```diff
@@ -4,7 +4,7 @@ source hack/common.sh
 source hack/bootstrap.sh
 source hack/config.sh
 
-WHAT=${WHAT:-"//staging/src/kubevirt.io/... //pkg/... //cmd/... //tests/framework/..."}
+WHAT=${WHAT:-"//staging/src/kubevirt.io/... //pkg/... //cmd/... //tools/... //tests/framework/..."}
```
Comment (dasionov) [inline hack/bazel-test.sh:7]:
```suggestion
WHAT=${WHAT:-"//staging/src/kubevirt.io/... //pkg/... //cmd/... //tools/util/... //tools/cache/... //tests/framework/..."}
```

**Review by dasionov — APPROVED** [review]
Thank You!
/lgtm

File: hack/bazel-test.sh (hunk 2 above)
Comment (iholder101) [reply hack/bazel-test.sh]: Hey @dasionov!

Can you please explain the reasoning behind this comment? Wouldn't it be better to cover the whole `./tools` directory, so we wouldn't have to add more specific paths in the future?

Comment (dasionov) [reply hack/bazel-test.sh]: I initially thought the same. The main issue with testing the entire //tools/ directory is that it requires everything to compile. However, the current tools.go files haven’t been compiling since [this commit](https://github.com/kubevirt/kubevirt/pull/4051/commits/ac592cecf4f6e38dc0350f3ed3dba457750435e2), and I couldn’t determine whether the reasoning provided at the time is still relevant today.
wdyt?

Comment (iholder101) [reply hack/bazel-test.sh]: Personally, I tend to think that if the code does not compile for about 5 years, that's more than enough evidence that we should remove it.

In any case, this PR does move things forward. After it's merged we seriously need to re-look into the tools directory.

**Comment by iholder101** [comment]
Thanks @mosheyaku!

/release-note-none
/approve

File: hack/bazel-test.sh (hunk 2 above)
Comment (dasionov) [reply hack/bazel-test.sh]: Agreed, opened #14624 so it can be tracked and not forgotten.
Thanks!
