### PR TITLE
Fix host usb permissions

### LINKED ISSUE #10727: Permissions denied error during USB pass through
**What happened**:
Virt-launcher is failing because USB host pass through doesn't works due to `permission denied` error.
```
{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/kubevirt/testvmlinux/noCloud.iso","pos":"cloud-init.go:690","timestamp":"2023-11-15T11:20:09.531496Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to read from monitor: Connection reset by peer","pos":"qemuMonitorIORead:423","subcomponent":"libvirt","thread":"218","timestamp":"2023-11-15T11:20:09.659000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: QEMU unexpectedly closed the monitor (vm='kubevirt_testvmlinux'): 2023-11-15T11:20:09.658012Z qemu-kvm: -device {\"driver\":\"usb-host\",\"hostdevice\":\"/dev/bus/usb/001/002\",\"id\":\"ua-usb-host-wlan\",\"bus\":\"usb.0\",\"port\":\"2\"}: failed to open /dev/bus/usb/001/002: Permission denied","pos":"qemuProcessReportLogError:1990","subcomponent":"libvirt","thread":"218","timestamp":"2023-11-15T11:20:09.659000Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 217 with status 256","pos":"virt-launcher-monitor.go:192","timestamp":"2023-11-15T11:20:09.721074Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"testvmlinux","namespace":"kubevirt","pos":"manager.go:1082","reason":"virError(Code=1, Domain=10, Message='internal error: QEMU unexpectedly closed the monitor (vm='kubevirt_testvmlinux'): 2023-11-15T11:20:09.658012Z qemu-kvm: -device {\"driver\":\"usb-host\",\"hostdevice\":\"/dev/bus/usb/001/002\",\"id\":\"ua-usb-host-wlan\",\"bus\":\"usb.0\",\"port\":\"2\"}: failed to open /dev/bus/usb/001/002: Permission denied')","timestamp":"2023-11-15T11:20:09.864856Z","uid":"e8ac49dd-8168-4cee-8bae-6cd8a4b7c256"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvmlinux","namespace":"kubevirt","pos":"server.go:202","reason":"virError(Code=1, Domain=10, Message='internal error: QEMU unexpectedly closed the monitor (vm='kubevirt_testvmlinux'): 2023-11-15T11:20:09.658012Z qemu-kvm: -device {\"driver\":\"usb-host\",\"hostdevice\":\"/dev/bus/usb/001/002\",\"id\":\"ua-usb-host-wlan\",\"bus\":\"usb.0\",\"port\":\"2\"}: failed to open /dev/bus/usb/001/002: Permission denied')","timestamp":"2023-11-15T11:20:09.865000Z","uid":"e8ac49dd-8168-4cee-8bae-6cd8a4b7c256"}
```

**What you expected to happen**:
VM is in running state and is exposing USB device.

**How to reproduce it (as minimally and precisely as possible)**:
1) Prepare Baremetal host with USB device
2) Configure Kubevirt CR as specified in https://kubevirt.io/user-guide/virtual_machines/host-devices/#usb-host-passthrough
3) Add USB device to VM's manifest.

**Additional context**:
Most likely issue is caused by fact, that USB devices are in root group, while `107` user, that is used in virt-launcher pod, is not part of it.
```
ubuntu@r1s01-r32:~$ ls -la /dev/bus/usb/001/002
crw-rw-r-- 1 root root 189, 1 Nov 15 11:27 /dev/bus/usb/001/002
```
Managed to workaround this issue by running `sudo chown 107:root /dev/bus/usb/001/002`, after which VM started successfully and had USB device mounted, however such solution isn't good enough for prod environment.

**Environment**:
- KubeVirt version (use `virtctl version`): 
```
ikyrycho@ikyrycho:~/yamls$ k virt version
Client Version: version.Info{GitVersion:"v1.0.0", GitCommit:"579bb66545630d93b29d0399219aaa51c3f0a00b", GitTreeState:"clean", BuildDate:"2023-07-06T17:46:07Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.1.0", GitCommit:"e8e638edc22587ec7be2cc3d983b61763e33f973", GitTreeState:"clean", BuildDate:"2023-11-06T17:30:39Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8+rke2r1", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T15:33:01Z", GoVersion:"go1.20.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Local Rancher instance
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kernel (e.g. `uname -a`):
```
Linux r1s01-r32 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**:
The device plugin for USB host pass though is not properly configuring device permissions prior to allocate the USB device to VMI. This PR fixes it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10727 

**Special notes for your reviewer**:
The fix is a one liner, by prefixing the path with `/proc/1/root`
I've added an extra check to the functional test to verify the emulated USB device has the right permission _after_ the VMI is created.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Fixes device permission when using USB host passthrough
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
Could we manage the permissions of the container rather than the host? That would cover also the external provider.

**Comment by victortoso** [comment]
> Could we manage the permissions of the container rather than the host? That would cover also the external provider.

@xpivarc the problem is that, before the VMI is created `vm.go` does not know which USB devices are going to the VM. The easiest/acceptable solution would be giving permission to all USB devices that match the selectors in KubeVirt CR.

Another possibility is improving virt-handler's device-manager so we can know which devices were allocated by k8s.

If you have any other ideas, I'm all ears. In the meanwhile, this should fix the problem for users and the code was indeed wrong .

**Comment by victortoso** [comment]
Also, I wonder if when using the external provider, wouldn't be its role to set permissions too?

**Comment by victortoso** [comment]
Interesting, the permission check failed for `k8s-1.28-sig-compute-migrations`

```
20:45:08:   [FAILED] Expected
20:45:08:       <string>: "0 0"
20:45:08:       
20:45:08:   to contain substring
20:45:08:       <string>: 107 107 
```

**Comment by victortoso** [comment]
No changes, just a rebase.

I was running the following script in a loop to see if I could trigger the failure as seen in this [comment](https://github.com/kubevirt/kubevirt/pull/10753#issuecomment-1820214901). I've executed it 22 times with no failure. Let's check again with CI.

```fish
#!/usr/bin/fish

set count 0
while true;
    echo $count
    ./cluster-up/ssh.sh node01 "sudo chown root:root -R /dev/bus/usb/*"
    ./cluster-up/ssh.sh node01 "ls -l /dev/bus/usb/* | grep -iq 107 && echo 'Failed to reset'"
    FUNC_TEST_ARGS='-focus-file=usb' make functest
    if test $status != 0
        exit 1
    end

    set count (math $count + 1)
    echo ""
    sleep 1
end;
```

File: tests/usb/usb.go [hunk 1]
```diff
@@ -103,6 +106,22 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
...
+			Expect(err).ToNot(HaveOccurred())
+
+			for _, hostDevice := range domainXml.Devices.HostDevices {
+				if hostDevice.Type != api.HostDeviceUSB {
+					continue
+				}
+				addr := hostDevice.Source.Address
+				path := fmt.Sprintf("%sdev/bus/usb/00%s/00%s", pkgUtil.HostRootMount, addr.Bus, addr.Device)
+				cmd := []string{"stat", "-c", `"%u %g"`, path}
+				stdout, err := tests.ExecuteCommandInVirtHandlerPod(nodeName, cmd)
```
Comment (xpivarc) [inline tests/usb/usb.go:121]: Shouldn't this `nodeName` come from VMI `status`?

File: tests/usb/usb.go [hunk 2]
```diff
@@ -103,6 +106,22 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
...
+				Expect(err).ToNot(HaveOccurred())
+				Expect(stdout).Should(ContainSubstring(fmt.Sprintf("%d %d", pkgUtil.NonRootUID, pkgUtil.NonRootUID)))
```
Comment (xpivarc) [inline tests/usb/usb.go:123]: Let's hardcore these values so we see failure if we ever change them.

Comment (victortoso) [reply tests/usb/usb.go:123]: Ok, will do!

File: tests/usb/usb.go (hunk 1 above)
Comment (victortoso) [reply tests/usb/usb.go:121]:
```diff
-                               stdout, err := tests.ExecuteCommandInVirtHandlerPod(nodeName, cmd)
+                               stdout, err := tests.ExecuteCommandInVirtHandlerPod(vmi.Status.NodeName, cmd)
```

aha. could this be the reason for [previous failure](https://github.com/kubevirt/kubevirt/pull/10753#issuecomment-1820214901)?

Thanks for catching this.

Comment (victortoso) [reply tests/usb/usb.go:121]: `vmi.Status.NodeName` was "", I missed updating the vmi variable after start, so the change actually is
```diff
--- a/tests/usb/usb.go
+++ b/tests/usb/usb.go
@@ -98,7 +98,7 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
                        vmi.Spec.Domain.Devices.HostDevices = hostDevs
                        vmi, err = virtClient.VirtualMachineInstance(util.NamespaceTestDefault).Create(context.Background(), vmi)
                        Expect(err).ToNot(HaveOccurred())
-                       libwait.WaitForSuccessfulVMIStart(vmi)
+                       vmi = libwait.WaitForSuccessfulVMIStart(vmi)
                        Expect(console.LoginToCirros(vmi)).To(Succeed())

                        By("Making sure the usb is present inside the VMI")
@@ -118,9 +118,9 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
                                addr := hostDevice.Source.Address
                                path := fmt.Sprintf("%sdev/bus/usb/00%s/00%s", pkgUtil.HostRootMount, addr.Bus, addr.Device)
                                cmd := []string{"stat", "-c", `"%u %g"`, path}
-                               stdout, err := tests.ExecuteCommandInVirtHandlerPod(nodeName, cmd)
+                               stdout, err := tests.ExecuteCommandInVirtHandlerPod(vmi.Status.NodeName, cmd)
                                Expect(err).ToNot(HaveOccurred())
```

File: tests/usb/usb.go [hunk 3]
```diff
@@ -95,14 +97,30 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
...
+			for _, hostDevice := range domainXml.Devices.HostDevices {
+				if hostDevice.Type != api.HostDeviceUSB {
+					continue
+				}
+				addr := hostDevice.Source.Address
+				path := fmt.Sprintf("%sdev/bus/usb/00%s/00%s", pkgUtil.HostRootMount, addr.Bus, addr.Device)
+				cmd := []string{"stat", "-c", `"%u %g"`, path}
+				stdout, err := tests.ExecuteCommandInVirtHandlerPod(vmi.Status.NodeName, cmd)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(stdout).Should(ContainSubstring("107 107"))
```
Comment (vasiliy-ul) [inline tests/usb/usb.go:122]: nit: I would rather be more strict here and check for equality

```suggestion
				Expect(stdout).Should(BeEqual("107 107"))
```

**Review by vasiliy-ul — APPROVED** [review]
/retest-required

**Comment by victortoso** [comment]
@vasiliy-ul I've also changed the `stat` to use `--printf` to not compare new line, the diff

```diff
--- a/tests/usb/usb.go
+++ b/tests/usb/usb.go
@@ -116,10 +116,10 @@ var _ = Describe("[Serial][sig-compute][USB] host USB Passthrough", Serial, deco
                                }
                                addr := hostDevice.Source.Address
                                path := fmt.Sprintf("%sdev/bus/usb/00%s/00%s", pkgUtil.HostRootMount, addr.Bus, addr.Device)
-                               cmd := []string{"stat", "-c", `"%u %g"`, path}
+                               cmd := []string{"stat", "--printf", `"%u %g"`, path}
                                stdout, err := tests.ExecuteCommandInVirtHandlerPod(vmi.Status.NodeName, cmd)
                                Expect(err).ToNot(HaveOccurred())
-                               Expect(stdout).Should(ContainSubstring("107 107"))
+                               Expect(stdout).Should(Equal(`"107 107"`))
```

**Comment by vasiliy-ul** [comment]
@victortoso thanks!

/lgtm
/unhold
