### PR TITLE
virt-api: Refactor, share and use `VirtualMachineInstanceSpec` defaulting code from VM validation webhook

### LINKED ISSUE #9102: `spec.template.spec.domain.memory.guest` not taken into account by VM validation webhook when checking hugepage size
/area instancetype 

**What happened**:

When creating a `VirtualMachine` we use `ValidateVirtualMachineInstanceSpec` and `validateHugepagesMemoryRequests` checks from the `VirtualMachineInstance` validation webhook to validate that the size of the requested huge pages is greater than that of the memory requested:

https://github.com/kubevirt/kubevirt/blob/4366e522ef56ee0ffbc9f508ef30de4586d20fd3/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1375-L1398

This check relies on `spec.template.spec.domain.resources` being populated with resource requests, something that isn't ensured until the `VirtualMachineInstance` mutation webhook runs later when launching the VM:

https://github.com/kubevirt/kubevirt/blob/4366e522ef56ee0ffbc9f508ef30de4586d20fd3/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L298-L300

This results in the failure to validate perfectly valid `VirtualMachines`.

**What you expected to happen**:

The `VirtualMachineInstance` validation webhook should take `spec.template.spec.domain.memory.guest` into account when checking hugepage size and layout.

**How to reproduce it (as minimally and precisely as possible)**:

```
./cluster-up/kubectl.sh apply -f - << EOF
 ---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices: {}
        memory:
          guest: 4Gi
          hugepages:
            pageSize: 1Gi
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: containerdisk
EOF
selecting docker as container runtime
The request is invalid: spec.template.spec.domain.resources.requests.memory: spec.template.spec.domain.resources.requests.memory '0' must be equal to or larger than page size spec.template.spec.domain.hugepages.size '1Gi'
```

**Additional context**:

I've tagged this with `/area instancetype` as we don't have a way of expressing resource requests through instance types yet and thus this bug stops us from requesting hugepages.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

The code responsible for defaulting the `VirtualMachineInstanceSpec` of a `VirtualMachineInstance` is refactored and moved to a shared location for use by other webhooks such as the `VirtualMachine` validation webhook.

This allows the `VirtualMachine` validation webhook to temporarily apply the same defaults as the `VirtualMachineInstance` mutation webhook to a copy of the `VirtualMachine` being admitted before validating the `VirtualMachineInstanceSpec`.

This in turn resolves issues #9102 where a valid `VirtualMachine` was rejected because this defaulting had not occurred leading to an invalid `VirtualMachineInstanceSpec`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9102 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Thanks, looks good!

/lgtm
/retest

**Comment by lyarwood** [comment]
@davidvossel @vladikr - This came up during downstream testing of instancetypes where we can't define resource requests at the moment and so always hit this when using hugepages. I think we can workaround this in the validation code here but please let me know if I've missed something here!

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go [hunk 1]
```diff
@@ -1372,28 +1372,36 @@ func validateHugepagesMemoryRequests(field *k8sfield.Path, spec *v1.VirtualMachi
...
-			if vmMemory < hugepagesSize.Value() {
+			// Default to spec.domain.resources.requests but use spec.domain.memory.guest if it isn't set as can happen
+			// when this code is called from the VirtualMachine validation webhook before the VirtualMachineInstance mutation
+			// webhook ensures spec.domain.resources.requests is populated.
+			vmMemory := spec.Domain.Resources.Requests.Memory()
+			vmMemoryField := field.Child("domain", "resources", "requests", "memory").String()
+			if vmMemory.IsZero() && spec.Domain.Memory.Guest != nil {
+				vmMemory = spec.Domain.Memory.Guest
+				vmMemoryField = field.Child("domain", "memory", "guest").String()
+			}
```
Comment (davidvossel) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:1383]: i wonder if similar sorts of issues like this will bite us again in the future.

Maybe we should be running our defaulter on the templated spec (the logic in vmi mutate function) in the vms-admitter.go  before processing the vmi.spec there. would that potentially make sense?

Comment (lyarwood) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:1383]: @davidvossel Yeah very true, I would however like to land the current limited approach for `v0.59.0` and backport it to at least fix the hugepages corner case while working on a more complete fix for `v0.60.0`, I doubt that fix will be backportable tbh. Would that be acceptable in the short term?

Slightly OT but I think this class of issue also highlights the need to drive more devs and testers to use `VirtualMachines` as their initial starting point in tests etc rather than `VirtualMachineInstances`. I appreciate some of this is a hangover from how things were previously but packages/tools like `libvmi` that encourage the use of `VirtualMachineInstances` and skip `VirtualMachine` validation are starting to hurt us IMHO. If you agree I can take this up on the ML or some other forum (maybe something at the upcoming summit?) to highlight the need for us to exercise `VirtualMachine` validation more.

Comment (davidvossel) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:1383]: > I doubt that fix will be backportable tbh. Would that be acceptable in the short term?

why wouldn't the systematic fix be backportable?

Comment (lyarwood) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:1383]: > > I doubt that fix will be backportable tbh. Would that be acceptable in the short term?
> 
> why wouldn't the systematic fix be backportable?

Apologies I misunderstood your suggestion, temporarily applying the defaults in the VM validation webhook would be backportable. I thought you were suggesting we apply them in the VM mutation webhook that while possible would be a pretty big behavioural change and likely result in lots of test fallout. 

I'll start working on this now but I'd still like to land this ahead of `v0.59.0`, I can revert it later as part of the eventual fix and backports if it doesn't make it in this week.

**Review by davidvossel — COMMENTED** [review]
/approve

File: pkg/virt-api/webhooks/amd64.go [hunk 2]
```diff
@@ -47,6 +46,6 @@ func setAmd64DefaultDisksBus(vmi *v1.VirtualMachineInstance) {
 }
 
 // SetVirtualMachineInstanceAmd64Defaults is mutating function for mutating-webhook
-func SetVirtualMachineInstanceAmd64Defaults(vmi *v1.VirtualMachineInstance) {
-	setAmd64DefaultDisksBus(vmi)
+func SetVirtualMachineInstanceAmd64Defaults(spec *v1.VirtualMachineInstanceSpec) {
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/amd64.go:49]: Rename to `SetVirtualMachineInstanceSpecAmd64Defaults`?

File: pkg/virt-api/webhooks/arm64.go [hunk 3]
```diff
@@ -150,8 +150,8 @@ func setDefaultDisksBus(vmi *v1.VirtualMachineInstance) {
 }
 
 // SetVirtualMachineInstanceArm64Defaults is mutating function for mutating-webhook
-func SetVirtualMachineInstanceArm64Defaults(vmi *v1.VirtualMachineInstance) {
-	setDefaultCPUModel(vmi)
-	setDefaultBootloader(vmi)
-	setDefaultDisksBus(vmi)
+func SetVirtualMachineInstanceArm64Defaults(spec *v1.VirtualMachineInstanceSpec) {
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/arm64.go:153]: Rename to `SetVirtualMachineInstanceSpecArm64Defaults`?

File: pkg/virt-config/virt-config.go [hunk 4]
```diff
@@ -169,32 +169,32 @@ func (c *ClusterConfig) GetDefaultNetworkInterface() string {
 	return c.GetConfig().NetworkConfiguration.NetworkInterface
 }
 
-func (c *ClusterConfig) SetVMIDefaultNetworkInterface(vmi *v1.VirtualMachineInstance) error {
-	autoAttach := vmi.Spec.Domain.Devices.AutoattachPodInterface
+func (c *ClusterConfig) SetVMIDefaultNetworkInterface(spec *v1.VirtualMachineInstanceSpec) error {
```
Comment (0xFelix) [inline pkg/virt-config/virt-config.go:172]: Rename to `SetVMISpecDefaultNetworkInterface`?

File: pkg/virt-api/webhooks/hyperv.go [hunk 5]
```diff
@@ -199,10 +199,10 @@ func ValidateVirtualMachineInstanceHypervFeatureDependencies(field *k8sfield.Pat
 	return causes
 }
 
-func SetVirtualMachineInstanceHypervFeatureDependencies(vmi *v1.VirtualMachineInstance) error {
+func SetVirtualMachineInstanceHypervFeatureDependencies(spec *v1.VirtualMachineInstanceSpec) error {
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/hyperv.go:202]: Rename to `SetVirtualMachineInstanceSpecHypervFeatureDependencies`?

Comment (0xFelix) [reply pkg/virt-api/webhooks/hyperv.go:202]: Or get rid of `VirtualMachineInstance` in the name to keep it short?

**Review by 0xFelix — COMMENTED** [review]
Added some nits about naming funcs.

File: pkg/virt-api/webhooks/hyperv.go (hunk 5 above)
Comment (lyarwood) [reply pkg/virt-api/webhooks/hyperv.go:202]: Yeah I've just dropped `VirtualMachineInstance` from most of the names now, thanks!

**Comment by lyarwood** [comment]
/unhold

@0xFelix hopefully addressed your nits if you have time this morning to review again

**Comment by 0xFelix** [comment]
/retest
/lgtm

Looks good, thanks!

**Comment by 0xFelix** [comment]
Commented on the wrong PR... just ignore that.

**Comment by xpivarc** [comment]
/hold 
Helping Tide.
The storage lane is currently broken. https://github.com/kubevirt/kubevirt/pull/9135 should fix this.
Feel free to remove the hold once this is merged.
