### PR TITLE
virt-freezer exit 0 if no guest agent

### LINKED ISSUE #7750: Velero Backups fails when no qemu guest agent is running on VM
**What happened**:
Velero backups fail partially because of kubevirt when there are VMIs which are not running the qemu guest agent: the Velero pre/post hooks that are set as annotations to the virt-launcher pods try to run the virt-freezer utility, which however fails because no qemu-guest-agent is running inside the VM. As a result, the backup for such resource fails. 

**What you expected to happen**:
The annotation should not be set to virt-launcher pods automatically so that backups can not fail because of kubevirt.
In general, a configurable behavior (for example an annotation on the vmi) could be more desirable.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with no qemu-guest-agent running on the guest OS, then start a velero backup for the vmi resource.

**Additional context**:
PVCs for such VMIs are not set to be backed up by Velero so there should be no need to freeze the VM.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.52.0
- Kubernetes version (use `kubectl version`): v1.23.6
- VM or VMI specifications: no qemu-guest-agent 
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Currently, velero will consider backups partially failed if a VM does not contain a guest agent.  Not very user friendly, especially when you consider that always add the hook annotations to virt-launcher pods.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7750

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
/lgtm

Do we throw a warning/event if the agent isn't installed?

File: cmd/virt-freezer/main.go [hunk 1]
```diff
@@ -42,6 +43,10 @@ func getGrpcClient() (cmdclient.LauncherClient, error) {
 	return client, err
 }
 
+func isGuestAgentNotConnected(err error) bool {
+	return strings.Contains(err.Error(), "QEMU guest agent is not connected")
```
Comment (rmohr) [inline cmd/virt-freezer/main.go:47]: Would not be the first time we would do something like this. Just so that we ensure that there is no better way: Would it be possible to have a stronger typed error? I guess we could understand from the libvirt returned error what type of error we deal with and could return a clear erro which would be better identifyable than due to string matching?

That would keep the actual error logic close to the source, making things like e.g. the cloud hypervisor POC easier and keeping the qemu related logic close to qemu.

**Review by rmohr — COMMENTED** [review]
One thought I would be happy if we could explore it.

File: cmd/virt-freezer/main.go (hunk 1 above)
Comment (mhenriks) [reply cmd/virt-freezer/main.go:47]: Yeah, I don't love the current implementation either but doing anything more would require extending the protobuf response structure (currently only a (bool, string)).  Which seemed a little much.  But is of course doable.

Comment (oshoval) [reply cmd/virt-freezer/main.go:47]: maybe according the libvirt agent connected event that will raise some flag once it is connected (and until then it will return false?)

**Comment by mhenriks** [comment]
@rmohr what do you think of this solution.  Simple and not specific to qemu?

File: cmd/virt-freezer/main.go [hunk 2]
```diff
@@ -76,6 +76,18 @@ func main() {
 		os.Exit(1)
 	}
 
+	info, err := client.GetGuestInfo()
+	if err != nil {
+		log.Log.Reason(err).Error("Failed to get guest info")
+		os.Exit(1)
+	}
+
+	log.Log.Infof("Guest agent version is %s", info.GAVersion)
```
Comment (rmohr) [inline cmd/virt-freezer/main.go:85]: The log line may be better placed at line 90.

**Review by rmohr — COMMENTED** [review]
Looks great. One small request.

File: cmd/virt-freezer/main.go (hunk 2 above)
Comment (mhenriks) [reply cmd/virt-freezer/main.go]: Yup

File: cmd/virt-freezer/main.go (hunk 1 above)
Comment (mhenriks) [reply cmd/virt-freezer/main.go]: Hi @oshoval I'm not sure I fully understand your suggestion.  How would virt-freezer get the agent connected event?

Do you have any concerns with the current implementation of this PR?

**Comment by rmohr** [comment]
/lgtm
/approve

/hold

Feel free to remove the hold when all conversations are done.

File: tests/storage/snapshot.go [hunk 3]
```diff
@@ -750,6 +749,33 @@ var _ = SIGDescribe("VirtualMachineSnapshot Tests", func() {
 				}, 180*time.Second, time.Second).Should(BeTrue())
 			})
 
+			It("Calling Velero hooks should not error if no guest agent", func() {
+				const noGuestAgentString = "No guest agent, exiting"
```
Comment (oshoval) [inline tests/storage/snapshot.go:753]: nit: can this be part of `cmd/virt-freezer/main.go` ?

File: cmd/virt-freezer/main.go (hunk 1 above)
Comment (oshoval) [reply cmd/virt-freezer/main.go]: I see that the logic of the PR changed,
Meant that maybe `VirtualMachineInstanceAgentConnected` can be used ? but the current implementation looks good enough

Just a question:
Sometimes it takes time until guest agent loads, can be a race where the virt-freezer runs before it, exit 0 ?
or it is a non issue, because it will simply run again afterwards?

Feel free to remove the hold, thanks

**Review by oshoval — COMMENTED** [review]
Just nit
Thanks

File: cmd/virt-freezer/main.go (hunk 1 above)
Comment (mhenriks) [reply cmd/virt-freezer/main.go]: Yeah, I'm not too concerned with that case.  Any solution there will be races.  Thanks!
