### PR TITLE
fix: pkg/virtctl/console lint errors

### LINKED ISSUE #14193: Resolve linting issues in pkg/virtctl/console
**What happened**:

Running the linter against `pkg/virtctl/console` fails.

**What you expected to happen**:

Running the linter against `pkg/virtctl/console` should succeed without errors or warnings.

**How to reproduce it (as minimally and precisely as possible)**:

Add `pkg/virtctl/console` to `hack/linter/lint-paths.txt` and run `make lint`.

/kind cleanup
/label good-first-issue

### PR DESCRIPTION
**Pull request by mohit-nagaraj**
#### Before this PR:
Running the linter against `pkg/virtctl/console` gives errors.
#### After this PR:
Now it succeeds without errors or warnings

### References
- Fixes  #14193

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/virtctl/console/console.go [hunk 1]
```diff
@@ -37,6 +37,12 @@ import (
 	"kubevirt.io/kubevirt/pkg/virtctl/templates"
 )
 
+const (
+	defaultTimeoutMinutes = 5
+	escapeSequenceCode    = 29
+	bufferSize            = 1024
```
Comment (0xFelix) [inline pkg/virtctl/console/console.go]: I'd put these consts closer to where they are used.

Comment (mohit-nagaraj) [reply pkg/virtctl/console/console.go]: Done!

**Comment by jcanocan** [comment]
Thanks!
/lgtm
