### PR TITLE
fix: pkg/virtctl/create/preference linting issues

### LINKED ISSUE #14197: Resolve linting issues in pkg/virtctl/create/preference
**What happened**:

Running the linter against `pkg/virtctl/create/preference` fails.

**What you expected to happen**:

Running the linter against `pkg/virtctl/create/preference` should succeed without errors or warnings.

**How to reproduce it (as minimally and precisely as possible)**:

Add `pkg/virtctl/create/preference` to `hack/linter/lint-paths.txt` and run `make lint`.

/kind cleanup
/label good-first-issue

### PR DESCRIPTION
**Pull request by Ruclo**
#### Before this PR:
pkg/virtctl/create/preference directory was not checked when running `make lint` and linter checks failed
#### After this PR:
pkg/virtctl/create/preference directory is now checked by make lint and successfully passes
### References
- Fixes #14197

### Release note
```
NONE
```

### CODE REVIEW

File: pkg/virtctl/create/preference/preference.go [hunk 1]
```diff
@@ -188,7 +192,8 @@ func (c *createPreference) run(cmd *cobra.Command, _ []string) error {
 	if c.namespaced {
 		preference := c.newPreference()
 
-		if err := c.applyFlags(cmd, &preference.Spec); err != nil {
+		err = c.applyFlags(cmd, &preference.Spec)
+		if err != nil {
```
Comment (lyarwood) [inline pkg/virtctl/create/preference/preference.go:196]: I assume the failure here was a shadow declaration? If so can you leave the `err` check in-line?

Comment (Ruclo) [reply pkg/virtctl/create/preference/preference.go:196]: It was a shadow declaration. When I tried assigning to the declared err variable in the first part of the if statement I got a sloppyReasign failure.

Comment (lyarwood) [reply pkg/virtctl/create/preference/preference.go:196]: Ah okay fair point!

**Comment by lyarwood** [comment]
/test pull-kubevirt-unit-test

https://github.com/kubevirt/kubevirt/issues/15194 captured for the previous unrelated failure.

**Comment by lyarwood** [comment]
@0xFelix can you approve the linting path change?

File: pkg/virtctl/create/preference/preference.go (hunk 1 above)
Comment (0xFelix) [reply pkg/virtctl/create/preference/preference.go:196]: Weird that it complains about this, but I'd say shadowing `err` was actually intended here?

**Review by 0xFelix — COMMENTED** [review]
/approve
