### PR TITLE
virt-api: Improve machine type validation

### LINKED ISSUE #14205: Validation of VM machine type not strict enough
**What happened**:
When creating a VM, the field `spec.domain.machine.type` is validated against the target architectures valid machine types.
However in this validation, all strings containing the valid machine type are accepted.

For example on s390x, it is validated against `s390-ccw-virtio*`, so `s390-ccw-virtio` or `s390-ccw-virtio-rhel-8` are valid. What should not be valid, but is currently accepted is `something-s390-ccw-virtio`. This is the same for other architectures.

**What you expected to happen**:
To accept wildcard patterns and fail when something in the machine type does not match the pattern.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with an invalid machine type like `something-q35` for x86.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): Latest main as of 2025-03-11
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jschintag**
Improve machine type validation by ensuring the pattern is more strictly matched.
Expand unit-tests to cover more possible machine types for testing.

### What this PR does
Before this PR:
API allows machine types like q35-usagduzagd
After this PR:
It is more strict with verifying the glob pattern.

Fixes #14205

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Ensure stricter check for valid machine type when validating VMI
```

### CODE REVIEW

**Comment by iholder101** [comment]
@dasionov you've worked on machine type validations recently. Mind having a look whenever you have the time?

**Review by dasionov — COMMENTED** [review]
Hi @jschintag thank you for this PR!
looking good overall, left a small nit feel free to ignore.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go [hunk 1]
```diff
@@ -495,16 +495,26 @@ var _ = Describe("Validating VMICreate Admitter", func() {
...
-		})
+			Expect(causes[0].Message).To(ContainSubstring(fmt.Sprintf("fake.domain.machine.type is not supported: %s (allowed values:", machineType)))
+		},
+			Entry("Simple wrong value", "amd64", "test"),
+			Entry("Wrong suffix amd64 q35", "amd64", "test-q35"),
+			Entry("Wrong suffix amd64 pc-q35", "amd64", "test-pc-q35"),
+			Entry("Wrong suffix arm64", "arm64", "test-virt"),
+			Entry("Wrong suffix ppc64le", "ppc64le", "test-pseries"),
+			Entry("Wrong suffix s390x", "s390x", "test-s390-ccw-virtio"),
+		)
```
[the remark this answers is not in the document]
Comment (jschintag) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go:517]: Yes, let me fix that. We allow any suffix, only the prefix should be validated.

**Review by dasionov — APPROVED** [review]

**Comment by jschintag** [comment]
> Hi @jschintag thank you for this PR! looking good overall, left a small nit feel free to ignore.

Thank you for the review @dasionov. I have fixed the nit.

**Comment by dasionov** [comment]
> > Hi @jschintag thank you for this PR! looking good overall, left a small nit feel free to ignore.
> 
> Thank you for the review @dasionov. I have fixed the nit.

Awesome !
/lgtm

**Comment by enp0s3** [comment]
@jschintag Hi, sure, will take a look

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go [hunk 2]
```diff
@@ -970,7 +970,8 @@ func validateEmulatedMachine(field *k8sfield.Path, spec *v1.VirtualMachineInstan
 		supportedMachines := config.GetEmulatedMachines(spec.Architecture)
 		var match = false
 		for _, val := range supportedMachines {
-			if regexp.MustCompile(val).MatchString(machine.Type) {
+			// The pattern are hardcoded, so this should not throw an error
+			if ok, _ := filepath.Match(val, machine.Type); ok {
```
Comment (enp0s3) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:974]: From the usage of `filepath` it looks like we do care about the formatting of the machine type field?
But OTOH we ignore the error, why wouldn't we use the regular comparison `val == machine.Type` then?

**Review by enp0s3 — COMMENTED** [review]
@jschintag Thank you for your time! I have a small question below.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go (hunk 2 above)
Comment (jschintag) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:974]: Because the value is a glob pattern for x86 it would be `q35*`. Because as machine type it could be something like `q35-rhel-9.1` or so (i wrote it from memory, so it might be spelled differently).
So a simple `==` does not work, while the previous regex just ensured that `q35` is somewhere in the string. We could hardcode possible values, but i don't know where we would find them and we would need to constantly update it.

The full list of patterns from `pkg/virt-config/virt-config.go`:
```
	DefaultAMD64EmulatedMachines                    = "q35*,pc-q35*"
	DefaultPPC64LEEmulatedMachines                  = "pseries*"
	DefaultAARCH64EmulatedMachines                  = "virt*"
	DefaultS390XEmulatedMachines                    = "s390-ccw-virtio*"
```

**Comment by jschintag** [comment]
Thank you for the review @enp0s3
