### PR TITLE
Remove Dockerfiles and all related stuff

### LINKED ISSUE #2038: Drop Dockerfiles, now that bazel builds and publishes the images
/kind enhancement

**What happened**:

Follow up of #1884. Bazel builds and publishes all images. The Dockerfiles have no use anymore and we don't want to maintain both places. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
Currently, we create and push all images by bazel, so not need
to have Dockerfiles under cmd/ and images/ directories.

TODO:
- remove all related to Dockerfiles stuff from `hack/` scripts

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2038

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: hack/build-docker.sh [hunk 1]
```diff
@@ -22,48 +22,13 @@ set -e
...
 
-if [ -z "$1" ]; then
-    target="build"
-else
-    target=$1
-    shift
-fi
-
 if [ $# -eq 0 ]; then
     args=$docker_images
```
Comment (rmohr) [inline hack/build-docker.sh]: I guess we can remove the docker_images variable from hack/config-defaults.sh. Should be unused at that point.

Comment (rmohr) [reply hack/build-docker.sh]: Oh  is it still used the pre-pull the images into the test nodes? Maybe we can have a more alligned way with bazel.
