### PR TITLE
fix(manifests): Set pull policy for virt-launcher

### LINKED ISSUE #15218: `make cluster-sync` not working after #15061
/assign

**What happened**:

After #15061 it looks like the same images are being used regardless of changes to the code after the initial deployment:

```
$ env | grep KUBEVIRT
KUBEVIRT_PROVIDER=k8s-1.33
KUBEVIRT_MEMORY_SIZE=16384
$ make cluster-up && make cluster-sync
[..]
$ kubectl get pods -n kubevirt -l app.kubernetes.io/component=kubevirt -o json | jq '.items.[] | .status.containerStatuses.[] | .imageID'
"registry:5000/kubevirt/virt-api@sha256:fa370d11ea70c96be0ca466a6c6ad6986672a2cc79c189877b0d77abb0cdb71f"
"registry:5000/kubevirt/virt-controller@sha256:31ae05978ec7e5fb1830e178a62ae7c63ce87f9d69781c0478396634ca15c80c"
"registry:5000/kubevirt/virt-controller@sha256:31ae05978ec7e5fb1830e178a62ae7c63ce87f9d69781c0478396634ca15c80c"
"registry:5000/kubevirt/virt-handler@sha256:a945d1b77819607b035e2359f9918b07f826d80375e1f1fd7ae2eeaa8d103104"

$ git diff
diff --git a/pkg/instancetype/controller/vm/controller.go b/pkg/instancetype/controller/vm/controller.go
index 796ee1577c..f49cdf66de 100644
--- a/pkg/instancetype/controller/vm/controller.go
+++ b/pkg/instancetype/controller/vm/controller.go
@@ -112,6 +112,9 @@ const (
 )
 
 func (c *controller) Sync(vm *virtv1.VirtualMachine, vmi *virtv1.VirtualMachineInstance) (*virtv1.VirtualMachine, error) {
+       if vm.Spec.Instancetype != nil {
+               panic("lyarwood")
+       }
        if vm.Spec.Instancetype == nil && vm.Spec.Preference == nil {
                return vm, nil
        }

$ make cluster-sync
[..]
$ kubectl get pods -n kubevirt -l app.kubernetes.io/component=kubevirt -o json | jq '.items.[] | .status.containerStatuses.[] | .imageID'
"registry:5000/kubevirt/virt-api@sha256:fa370d11ea70c96be0ca466a6c6ad6986672a2cc79c189877b0d77abb0cdb71f"
"registry:5000/kubevirt/virt-controller@sha256:31ae05978ec7e5fb1830e178a62ae7c63ce87f9d69781c0478396634ca15c80c"
"registry:5000/kubevirt/virt-controller@sha256:31ae05978ec7e5fb1830e178a62ae7c63ce87f9d69781c0478396634ca15c80c"
"registry:5000/kubevirt/virt-handler@sha256:a945d1b77819607b035e2359f9918b07f826d80375e1f1fd7ae2eeaa8d103104"
```

Many thanks to @awels for spotting this!

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

By setting `spec.configuration.imagePullPolicy` in manifest-templator, the `compute` container in `virt-launcher` will also respect it.

#### Before this PR:

The `compute` container in `virt-launcher` will use the default `IfNotPresent` pull policy in dev environments.

#### After this PR:

The `compute` container in `virt-launcher` will use the `Always` pull policy in dev environments.

### References

- Fixes #15218

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
/lgtm
/hold
@xpivarc anything against this?

**Comment by fossedihelm** [comment]
We have at least wait for https://github.com/kubevirt/kubevirt/issues/15218
Otherwise test runtime will be affected

**Comment by lyarwood** [comment]
> We have at least wait for #15218 Otherwise test runtime will be affected

@fossedihelm Did you mean https://github.com/kubevirt/kubevirt/pull/15252 ?

**Comment by fossedihelm** [comment]
> > We have at least wait for #15218 Otherwise test runtime will be affected
> 
> @fossedihelm Did you mean #15252 ?

@lyarwood Yup :D Thanks

**Comment by 0xFelix** [comment]
@fossedihelm Can we lift the hold now that #15252 is merged?

**Comment by fossedihelm** [comment]
I am not entirely convinced that 1 flag will handle CR and components pullPolicy.
Looking at the aesthetics, the `kubevirt-cr.yaml` released will include that customization.
Also: https://github.com/kubevirt/kubevirt/issues/15218#issuecomment-3117641648

**Comment by fossedihelm** [comment]
From https://github.com/kubevirt/kubevirt/issues/15218#issuecomment-3117890109
I think it is not worth it to having a change of the `kubevirt-cr.yaml` file for a dev-only one-time error that can be resolved via cluster-down.
My 2 cents.
Thanks

**Comment by lyarwood** [comment]
> From [#15218 (comment)](https://github.com/kubevirt/kubevirt/issues/15218#issuecomment-3117890109) I think it is not worth it to having a change of the `kubevirt-cr.yaml` file for a dev-only one-time error that can be resolved via cluster-down. My 2 cents. Thanks

I disagree, this is a horrid regression for folks working on `virt-launcher`, forcing them to `make cluster-{down,up}` every time they make a change is not acceptable IMHO. The change to `kubevirt-cr.yaml` is completely transparent to consumers and actually helps highlight the duplication of `ImagePullPolicy` in the CR, something that I'm much more worried about.

**Comment by jean-edouard** [comment]
I agree that it's important for `make cluster-sync` to always and automatically give you an environment that matches the current state of the code.
If the only way to get there is to alter the CR then I'm all for it...

**Comment by fossedihelm** [comment]
> I disagree, this is a horrid regression for folks working on `virt-launcher`, forcing them to `make cluster-{down,up}` every time they make a change is not acceptable IMHO. The change to `kubevirt-cr.yaml` is completely transparent to consumers and actually helps highlight the duplication of `ImagePullPolicy` in the CR, something that I'm much more worried about.

Per my understanding, this regression is triggered only if you switch between a branch w/ the SHASUM and a branch w/o it. If this is true, this regression is not permanent.
Or am I missing something?

**Comment by lyarwood** [comment]
> > I disagree, this is a horrid regression for folks working on `virt-launcher`, forcing them to `make cluster-{down,up}` every time they make a change is not acceptable IMHO. The change to `kubevirt-cr.yaml` is completely transparent to consumers and actually helps highlight the duplication of `ImagePullPolicy` in the CR, something that I'm much more worried about.
> 
> Per my understanding, this regression is triggered only if you switch between a branch w/ the SHASUM and a branch w/o it. If this is true, this regression is not permanent. Or am I missing something?

Apologies if I wasn't clear before but the regression here is *anytime* you deploy a kubevirtci env, make changes to `virt-launcher` code and rerun `make cluster-sync`. That's regardless of changing branch, rebasing etc.

**Comment by fossedihelm** [comment]
> > Per my understanding, this regression is triggered only if you switch between a branch w/ the SHASUM and a branch w/o it. If this is true, this regression is not permanent. Or am I missing something?
> 
> Apologies if I wasn't clear before but the regression here is _anytime_ you deploy a kubevirtci env, make changes to `virt-launcher` code and rerun `make cluster-sync`. That's regardless of changing branch, rebasing etc.

Ok, that's bad :slightly_smiling_face: 
Apologies, I thought it was transient.
However, it's just me or the `spec.ImagePullPolicy` is never used anywhere?https://github.com/kubevirt/kubevirt/blob/c0b0af1c8db9f5836957fa65071e03f9bf2f032f/staging/src/kubevirt.io/api/core/v1/types.go#L2318

**Comment by lyarwood** [comment]
> Ok, that's bad 🙂
> Apologies, I thought it was transient.
> However, it's just me or the `spec.ImagePullPolicy` is never used anywhere?

Yeah AFAICT it's not, just the `resource-generator` and a random unit test. Definitely something to clearly deprecate and document in a follow up (that I'm happy to do).

File: tools/resource-generator/resource-generator.go [hunk 1]
```diff
@@ -56,14 +56,15 @@ func newKubeVirtCR(namespace string, pullPolicy v1.PullPolicy, featureGates stri
 		},
 		Spec: virtv1.KubeVirtSpec{
 			ImagePullPolicy: pullPolicy,
+			Configuration: virtv1.KubeVirtConfiguration{
+				ImagePullPolicy: pullPolicy,
+			},
```
Comment (fossedihelm) [inline tools/resource-generator/resource-generator.go:61]:
```suggestion
			Configuration: virtv1.KubeVirtConfiguration{
				ImagePullPolicy: pullPolicy,
			},
```
^ not valid anymore

**Review by fossedihelm — COMMENTED** [review]
In this case I would say that we should not promote the duplication

File: tools/resource-generator/resource-generator.go (hunk 1 above)
Comment (fossedihelm) [reply tools/resource-generator/resource-generator.go:61]: > Yeah AFAICT it's not, just the resource-generator and a random unit test. Definitely something to clearly deprecate and document in a follow up (that I'm happy to do).

Here is where they are used:
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/util/config.go#L69-L88

Comment (lyarwood) [reply tools/resource-generator/resource-generator.go:61]: Wow, that's fun. So I guess this stays after all.

**Comment by fossedihelm** [comment]
/unhold
Let's think of about improvement in a followup
Thanks

File: tools/resource-generator/resource-generator.go (hunk 1 above)
Comment (0xFelix) [reply tools/resource-generator/resource-generator.go:61]: It's used for e.g. virt-operator and other Pods, so it needs to stay. Usage of it is masked though, because the spec is converted to an unstructured map before accessing any values from it...
