### PR TITLE
virt-operator: use domain-qualified KubeVirt CR finalizer

### LINKED ISSUE #12342: Consider renaming kubevirt finalizers
**What happened**:
When creating a VMI we see this warning
```
2024-07-11T15:56:52+03:00	INFO	KubeAPIWarningLogger	metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```

**What you expected to happen**:
We should do as the warning says, and rename the finalizer.
i.e `kubevirt.io/foregroundDeleteVirtualMachine`

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI, and check logs.
During standalone VMI creation, it will be shown directly as part of kubectl command output.

**Additional context**:
Found at at least this two finalizers that should be renamed.
```
pkg/virt-operator/util/client.go:	KubeVirtFinalizer string = "foregroundDeleteKubeVirt"
staging/src/kubevirt.io/api/core/v1/types.go:	VirtualMachineInstanceFinalizer string = "foregroundDeleteVirtualMachine"
```

Need to create backward compatible code, that can remove those finalizers from old running machines.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by dankenigsberg**
#### Before this PR:

The KubeVirt CR carried the finalizer `foregroundDeleteKubeVirt`, a bare
name that triggers the following API server warning:

```
metadata.finalizers: "foregroundDeleteKubeVirt": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```

#### After this PR:

The finalizer is named `kubevirt.io/foregroundDeleteKubeVirt`.

### References

- Fixes #12342

### Why we need it and why it was done in this way

The constant `KubeVirtFinalizer` is renamed to a domain-qualified form.  The 
`deprecatedKubeVirtFinalizer` constant is kept for the upgrade transition: a 
cluster upgraded from a previous release will have a KubeVirt CR carrying the 
old bare string, which would be replaced by the first reconcile. 
 
`AddFinalizer`/`hasFinalizer` are replaced with `SetFinalizer`/ 
`UnsetFinalizer`, backed by a `withoutKubeVirtFinalizers` helper that 
strips both the old and new strings. This code is simpler than alternatives 
and has the benefit of making the deletion path more careful. Previously it set 
`kv.Finalizers = nil`, wiping all finalizers indiscriminately. `UnsetFinalizer` 
replaces that with a surgical removal of only the kubevirt-owned finalizers, 
preserving any finalizers may have been set by foreign controllers. 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [VEP (virtualization enhancement proposal)](https://github.com/kubevirt/enhancements/blob/main/README.md) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
- [x] AI Contributions: The PR abides by the [KubeVirt AI Contribution Policy](https://github.com/kubevirt/community/blob/main/ai-contribution-policy.md).

### Release note
```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-operator/util/client.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ import (
 )
 
 const (
-	KubeVirtFinalizer string = "foregroundDeleteKubeVirt"
+	KubeVirtFinalizer string = "kubevirt.io/foregroundDeleteKubeVirt"
```
Comment (lyarwood) [inline pkg/virt-operator/util/client.go:39]: After an upgrade from a release that used `"foregroundDeleteKubeVirt"`, the existing KubeVirt CR will still carry the old finalizer string. Since `hasFinalizer()` below (line 182) only checks for the new `KubeVirtFinalizer` value, it will not find a match and `AddFinalizer()` will append the new string alongside the old one. The CR ends up with:

```json
["foregroundDeleteKubeVirt", "kubevirt.io/foregroundDeleteKubeVirt"]
```

The old non-domain-qualified string is never removed (only `kv.Finalizers = nil` during deletion clears it), so the API server warning from #12342 would persist on every CR update for the lifetime of the cluster.

The PR description says a deprecated alias is not needed, but that reasoning only considers the removal path. The addition path does need to account for the old string.

Note that PR #15096 (VMI finalizer) has a similar gap - it does not proactively clean up the old finalizer on existing running VMIs either - but VMIs are short-lived compared to the KubeVirt CR.

Suggested fix: add a `DeprecatedKubeVirtFinalizer` constant and either have `AddFinalizer` remove the old string when adding the new one, or have `hasFinalizer` recognise both strings and add cleanup logic to `AddFinalizer`.

Comment (dankenigsberg) [reply pkg/virt-operator/util/client.go:39]: Oh. If I have to do so, I'd like to fix the assymetry between setting and removing finalizers.

File: pkg/virt-operator/util/client.go [hunk 2]
```diff
@@ -173,19 +174,22 @@ func SetConditionTimestamps(kvOrig *virtv1.KubeVirt, kvUpdated *virtv1.KubeVirt)
 	}
 }
 
-func AddFinalizer(kv *virtv1.KubeVirt) {
-	if !hasFinalizer(kv) {
-		kv.Finalizers = append(kv.Finalizers, KubeVirtFinalizer)
-	}
+func SetFinalizer(kv *virtv1.KubeVirt) {
```
Comment (lyarwood) [inline pkg/virt-operator/util/client.go:179]: supernit: `pkg/controller/controller.go` already provides generic `HasFinalizer`, `RemoveFinalizer`, and `AddFinalizer` helpers that work on any `metav1.Object`. These could be reused here instead of the new `withoutKubeVirtFinalizers` helper, e.g.:

```go
func SetFinalizer(kv *virtv1.KubeVirt) {
	controller.RemoveFinalizer(kv, deprecatedKubeVirtFinalizer)
	controller.AddFinalizer(kv, KubeVirtFinalizer)
}

func UnsetFinalizer(kv *virtv1.KubeVirt) {
	controller.RemoveFinalizer(kv, KubeVirtFinalizer)
	controller.RemoveFinalizer(kv, deprecatedKubeVirtFinalizer)
}
```

The old `util.AddFinalizer`/`util.hasFinalizer` were already duplicates of the `pkg/controller` versions, so this would be a chance to consolidate rather than reshape the duplication. Happy to handle in a follow-up if you'd rather not scope-creep this PR.

File: pkg/virt-operator/kubevirt.go [hunk 3]
```diff
@@ -1059,7 +1059,7 @@ func (c *KubeVirtController) syncInstallation(kv *v1.KubeVirt) error {
 	}
 
 	// add finalizer to prevent deletion of CR before KubeVirt was undeployed
-	util.AddFinalizer(kv)
+	util.SetFinalizer(kv)
```
Comment (lyarwood) [inline pkg/virt-operator/kubevirt.go:1062]: nit: The unit tests in `client_test.go` cover `SetFinalizer` replacing the deprecated string, but no controller-level test exercises the full upgrade path where a KV CR starts with the old `"foregroundDeleteKubeVirt"` finalizer and goes through `syncInstallation`. All existing test fixtures in `kubevirt_test.go` use `util.KubeVirtFinalizer` which now resolves to the new value. Consider adding a test case that starts with the old finalizer to verify the upgrade reconcile end-to-end.

**Review by lyarwood — COMMENTED** [review]
/lgtm

File: pkg/virt-operator/kubevirt.go [hunk 4]
```diff
@@ -1196,7 +1196,7 @@ func (c *KubeVirtController) syncDeletion(kv *v1.KubeVirt) error {
 		kv.Status.Phase = v1.KubeVirtPhaseDeleted
 
 		// remove finalizer
-		kv.Finalizers = nil
+		util.UnsetFinalizer(kv)
```
Comment (xpivarc) [inline pkg/virt-operator/kubevirt.go:1199]: Great improvement as previously we would remove any finalizer even external to KV... worth dedicated commit

**Review by xpivarc — COMMENTED** [review]
Should we actively remove the old finalizer upon adding a new one? Otherwise I believe we need to carry the deprecated forever, wdyt?

File: pkg/virt-operator/util/client.go (hunk 2 above)
Comment (dankenigsberg) [reply pkg/virt-operator/util/client.go:179]: I don't like code duplication, but having a small `util` depend on a core `controller` seems far worse to me. I'd prefer to consider this only in a follow up.

File: pkg/virt-operator/kubevirt.go (hunk 4 above)
Comment (dankenigsberg) [reply pkg/virt-operator/kubevirt.go:1199]: Ok, I love small, well-motivated, commits.

File: pkg/virt-operator/kubevirt.go (hunk 3 above)
Comment (dankenigsberg) [reply pkg/virt-operator/kubevirt.go:1062]: It ended up quite ugly; I'd be happy to drop it, but here it is.

File: pkg/virt-operator/kubevirt.go (hunk 4 above)
Comment (dankenigsberg) [reply pkg/virt-operator/kubevirt.go:1199]: I love small well-motivated commits. Done.

**Comment by dankenigsberg** [comment]
> Should we actively remove the old finalizer upon adding a new one? Otherwise I believe we need to carry the deprecated forever, wdyt?

I'm not sure I understand your request, I think `SetFinalizer` already removes the old finalizer upon adding a new one.
```
                                It("Should replace the deprecated finalizer on upgrade", func() {
                                        kv.Finalizers = []string{deprecatedKubeVirtFinalizer}
                                        SetFinalizer(kv)
                                        Expect(kv.Finalizers).To(ConsistOf(KubeVirtFinalizer))
                                })
```

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by lyarwood — APPROVED** [review]
