### PR TITLE
Fix Guestless VMI failure by adding KernelBoot on s390x

### LINKED ISSUE #14489: Guestless VMI fails on s390x due to IPL(Initial Program Load) requirements
**Description:**
Guestless VMIs are created via the following function in the KubeVirt codebase:
https://github.com/kubevirt/kubevirt/blob/47ac60cbb588b7721b47e200b952b7145bf573c9/tests/libvmifact/factory.go#L100

The NewGuestless() function is intended to spin up a minimal virtual machine with no disk or OS, primarily for testing purposes. This works as expected on x86_64 platforms, as QEMU can launch VMs even without a disk or boot image.

However, this approach fails on s390x. The s390x architecture requires an Initial Program Load (IPL) to boot any virtual machine—even for minimal test scenarios.

**Documentation:**
https://www.qemu.org/docs/master/system/s390x/bootdevices.html

**Observed Behavior:**
Attempting to create a guestless VM on s390x results in the following QEMU error:

```
[root@ ~]# /usr/libexec/qemu-kvm  -machine s390-ccw-virtio -display none -nographic -d int
LOADPARM=[        ]
Could not find a suitable boot device (none specified)
Failed to load OS from hard disk
```
The above error/panic is thrown from QEMU code at:

https://gitlab.com/qemu-project/qemu/-/blob/v8.2.0/pc-bios/s390-ccw/main.c#L290

https://gitlab.com/qemu-project/qemu/-/blob/v8.2.0/pc-bios/s390-ccw/main.c#L305

Using -no-shutdown prevents QEMU from exiting immediately, but the error remains and the VM does not boot.

Root Cause:

The s390x platform requires a valid bootloader and an IPL source in order to start any VM. Without a defined disk or boot device, the IPL process cannot begin. This differs from x86_64 behavior, where a VM can be launched without a boot image. 

Since NewGuestless() does not attach a disk, kernel, or initrd, the resulting VM cannot successfully perform IPL on s390x.

From QEMU docs:

"For classical mainframe guests (i.e. LPAR or z/VM installations), you always have to explicitly specify the disk where you want to boot from (or 'IPL' from, in s390x-speak – IPL means 'Initial Program Load')."

**Proposed Workaround:**

As guestless VMIs are incompatible with s390x, we suggest using Alpine-based VMIs (or any minimal VMI with a valid disk and boot path) instead of the NewGuestless() implementation when running tests on s390x.
We need this to enable sig-compute lane for s390x
for example at : https://github.com/kubevirt/kubevirt/blob/28cb4bf47bd457a6b86ad8b47d883b66c8322cd1/tests/compute/vm_lifecycle.go#L213

### PR DESCRIPTION
**Pull request by Davo911**
#### Before this PR:
Tests using [NewGuestless()](https://github.com/kubevirt/kubevirt/blob/8e654da048f0363c110f72f859cfe4e2583a461a/tests/libvmifact/factory.go#L100-L105) failed on s390x, due to architecture specific requirements.
#### After this PR:
Performs KernelBoot from a specialised minimal guest image, when trying to bring up a Guestless VMI on s390x.
The kernel was built using the toolset from [KVM-unit-tests](https://www.linux-kvm.org/page/KVM-unit-tests) and the image pushed to [quay](https://quay.io/repository/tgriedel/kubevirt_s390x_guestless_loop?tab=tags).
[This kernel-code](https://gitlab.com/Davo9111/kvm-unit-tests/-/commit/7e24b00453425b6c5187516719e9b649f09a20a6) is basically just running a simple while loop.

### References
- Fixes #14489

### Why we need it and why it was done in this way
On s390x, virtual machines require an Initial Program Load (IPL) source to start; they cannot be launched completely "empty" or guestless like x86_64 VMs. Attempting to do so results in QEMU failing with `Could not find a suitable boot device.`

The following alternatives were considered:
Simply using Alpine here was also tested successfully, but would come with significantly larger time & resource usage.

Links to places where a discussion took place:
[https://kubernetes.slack.com/archives/C0163DT0R8X/p1726468656344359](https://kubernetes.slack.com/archives/C0163DT0R8X/p1726468656344359)

### Special notes for your reviewer
Image:
https://quay.io/repository/kubevirt/s390x-guestless-kernel

Dockerfile PR on kubevirtci:
https://github.com/kubevirt/kubevirtci/pull/1589

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
NONE
```

### CODE REVIEW

File: tests/containerdisk/containerdisk.go [hunk 1]
```diff
@@ -37,6 +37,7 @@ const (
 	ContainerDiskEmpty                ContainerDisk = "empty"
 	ContainerDiskFedoraRealtime       ContainerDisk = "fedora-realtime"
 	KernelBoot                        ContainerDisk = "alpine-ext-kernel-boot-demo"
+	MicroKernelBoot                   ContainerDisk = "kubevirt_s390x_guestless_loop"
```
Comment (andreabolognani) [inline tests/containerdisk/containerdisk.go]: The word "microkernel" has a very specific meaning already, so I'm concerned this choice of name will cause confusion. I suggest `KernelBootS390xGuestless` or something along those lines instead. Including the architecture name as well is intentional - other images are multi-arch, this one is not.

**Review by andreabolognani — COMMENTED** [review]
Looks reasonable. I assume you will create a kubevirtci PR that introduces the image shortly.

File: tests/containerdisk/containerdisk.go (hunk 1 above)
Comment (Davo911) [reply tests/containerdisk/containerdisk.go]: You're right, fixed that!

**Comment by Davo911** [comment]
> Looks reasonable. I assume you will create a kubevirtci PR that introduces the image shortly.
Indeed, just waiting until i know more about where that kernel binary is hosted
https://github.com/kubevirt/kubevirtci/pull/1589
https://quay.io/repository/kubevirt/s390x-guestless-kernel?tab=tags

File: tests/containerdisk/containerdisk.go [hunk 2]
```diff
@@ -72,6 +73,8 @@ func ContainerDiskFromRegistryFor(registry string, name ContainerDisk) string {
 		return fmt.Sprintf("%s/%s-container-disk:%s", registry, name, flags.KubeVirtUtilityVersionTag)
 	case KernelBoot:
 		return fmt.Sprintf("%s/alpine-ext-kernel-boot-demo:%s", registry, flags.KubeVirtUtilityVersionTag)
+	case KernelBootS390xGuestless:
+		return fmt.Sprintf("%s/kubevirt_s390x_guestless_loop:%s", registry, "latest")
```
Comment (andreabolognani) [inline tests/containerdisk/containerdisk.go]: @Davo911 pre-existing, but it seems weird that you would need to repeat the string `"kubevirt_s390x_guestless_loop"` here after having already specified it as part of the definition of `KernelBootS390xGuestless`. Surely there would be a way to get rid of the `switch` statement and just do something like

```go
func ContainerDiskFromRegistryFor(registry string, name ContainerDisk) string {
    return fmt.Sprintf("%s/%s:%s", registry, name, flags.KubeVirtUtilityVersionTag)
}
```

Possibly using `name` directly this way wouldn't work, I'm not that good at Go O:-) but the point remains that a way to avoid having to put the same exact same string in two places must surely exist.

I notice the tag is `"latest"` in the s390x bootless use case. Does that really need to be special-cased? Can the same tag as other images not be used? Even if that's the case, maybe the rest of the code can still be factored out, reducing complexity to just the choice of tag name.

As I said this is all pre-existing, so it shouldn't necessarily fall on you to address this, or be considered a requirement for your changes to be merged. I just noticed it and thought I should mention it :)

Comment (Davo911) [inline tests/containerdisk/containerdisk.go]: Not sure about the tag part.
Is this fine if it's harcoded here or should I use [flags.KubeVirtVersionTag](https://github.com/kubevirt/kubevirt/blob/a73c90018587ce223cb9557619d2ed57c9b9eba5/tests/flags/flags.go#L30)

We could go with `date_hash` here too, but we won't update this image in my opinion in the future, so in the end that would also be hardcoded

File: tests/libvmifact/factory.go [hunk 3]
```diff
@@ -98,6 +98,27 @@ func NewAlpineWithTestTooling(opts ...libvmi.Option) *kvirtv1.VirtualMachineInst
...
+					vmi.Spec.Domain.Firmware = &kvirtv1.Firmware{}
+				}
+				vmi.Spec.Domain.Firmware.KernelBoot = &kvirtv1.KernelBoot{
+					Container: &kvirtv1.KernelBootContainer{
+						Image:      cd.ContainerDiskFor(cd.KernelBootS390xGuestless),
+						KernelPath: "/boot/kernel",
+					},
+				}
+			},
+			libvmi.WithMemoryRequest("16Mi"),
```
Comment (akalenyu) [inline tests/libvmifact/factory.go:111]: Nice, can you really get away with 16Mi? Heads up on this ARM requirement https://github.com/kubevirt/kubevirt/blob/1c2ca99bbb94849dc2d6943de12f8095fe111dc0/tests/libvmifact/factory.go#L129-L134

File: tests/libvmifact/factory.go [hunk 4]
```diff
@@ -98,6 +98,27 @@ func NewAlpineWithTestTooling(opts ...libvmi.Option) *kvirtv1.VirtualMachineInst
 }
 
 func NewGuestless(opts ...libvmi.Option) *kvirtv1.VirtualMachineInstance {
+	if isS390X() {
+		// We need to use KernelBoot to boot into this container with a kernel
+		// guest operating system only running a few lines of C loop
+		microKernelOpts := []libvmi.Option{
+			func(vmi *kvirtv1.VirtualMachineInstance) {
```
Comment (akalenyu) [inline tests/libvmifact/factory.go]: This should be worth a WithKernelBoot in libvmi which would allow you to get rid of this util - utils.AddKernelBootToVMI

File: tests/containerdisk/containerdisk.go (hunk 2 above)
Comment (Davo911) [reply tests/containerdisk/containerdisk.go]: @andreabolognani 
> Does that really need to be special-cased? Can the same tag as other images not be used?

I wish it could, but that would also mean, that this image needs to be rebuild and pushed regularly, if I understood it correctly.
This kernelboot image is so simple, I'd rather suggest a one-off `1.0.0` or a single hardcoded `20260120_d213058e5` or simply `latest`, what do you think?

For the refactoring a better solution could look like this here:
https://github.com/kubevirt/kubevirt/commit/42a3019075d1d74fdaf911f326b6e80a54c11781
But should this really be done in this PR or shall I propose this in a separate one?

File: tests/libvmifact/factory.go (hunk 3 above)
Comment (Davo911) [reply tests/libvmifact/factory.go]: @akalenyu 
So apparently I cannot push it down to `qemuMinimumMemory()`, resulting in 
```bash
qemu-kvm: not enough RAM to load the BIOS file'
```

The lowest I could go is `4Mi` to pass [test_id:3161](https://github.com/kubevirt/kubevirt/blob/7ddd8eccf581d19210c05df849198310ba52dfe8/tests/vm_test.go#L180-L196)

File: tests/containerdisk/containerdisk.go [hunk 5]
```diff
@@ -72,6 +73,8 @@ func ContainerDiskFromRegistryFor(registry string, name ContainerDisk) string {
 		return fmt.Sprintf("%s/%s-container-disk:%s", registry, name, flags.KubeVirtUtilityVersionTag)
 	case KernelBoot:
 		return fmt.Sprintf("%s/alpine-ext-kernel-boot-demo:%s", registry, flags.KubeVirtUtilityVersionTag)
+	case KernelBootS390xGuestless:
+		return fmt.Sprintf("%s/s390x-guestless-kernel:%s", registry, "1.0.0")
```
Comment (iholder101) [inline tests/containerdisk/containerdisk.go]: Why `"1.0.0"` and not `flags.KubeVirtUtilityVersionTag`?

**Review by iholder101 — COMMENTED** [review]
Thanks @Davo911! Looks good.

Right now, AFAICT, the recipe for this new image is hidden.
Can you add the image to `hack/bazel-push-images.sh` and `BUILD.bazel`? This would ensure that the community can further maintain this image.

Also, can you squash commits so they're additive? I just reviewed the first commit, commented, just to find out these changes are outdated...

**Comment by Davo911** [comment]
> Right now, AFAICT, the recipe for this new image is hidden. Can you add the image to `hack/bazel-push-images.sh` and `BUILD.bazel`? This would ensure that the community can further maintain this image.

@iholder101 Thanks for taking a look at this!
I added the image to the bazel BUILDs, bazel-push.images.sh and WORKSPACE

File: tests/libvmifact/factory.go (hunk 4 above)
Comment (Davo911) [reply tests/libvmifact/factory.go]: Added the WithKernelBoot option, now
Looks cleaner!

File: WORKSPACE [hunk 6]
```diff
@@ -391,6 +385,12 @@ oci_pull(
     image = "quay.io/kubevirtci/fedora-with-test-tooling",
 )
 
+oci_pull(
+    name = "s390x-guestless-kernel",
+    digest = "sha256:3bf6fc355fc9718c088c4c881b2d35a073ea274f6b16dc42236ef5e29db2215d",
+    image = "quay.io/kubevirtci/s390x-guestless-kernel",
```
Comment (jean-edouard) [inline WORKSPACE]: Is this intended to be in a different org than the above? (kubevirt vs kubevirtci)
Was a repository created for this?
@dhiller FYI

Comment (jean-edouard) [reply WORKSPACE]: Looks good now
