### PR TITLE
tests: Rework canary upgrade assertions 

### LINKED ISSUE #15150: de-quarantine [sig-operator]virt-handler canary upgrade should successfully upgrade virt-handler
# What happened

Flaky test detected: [sig-operator]virt-handler canary upgrade should successfully upgrade virt-handler

/kind flake
/priority critical-urgent
/sig compute
/triage accepted

[1](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2025-07-09.html#%5bsig-operator%5dvirt-handler%20canary%20upgrade%20should%20successfully%20upgrade%20virt-handler) with an impact of 9% [2](https://search.ci.kubevirt.io/?search=%5C%5Bsig-operator%5Dvirt-handler+canary+upgrade+should+successfully+upgrade+virt-handler&maxAge=336h&context=1&type=junit&name=&excludeName=periodic-.*&maxMatches=1&maxBytes=20971520&groupBy=job).

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does

This change extracts the `virt-handler=ready` event into an independent
set of assertions after the maxUnavailable behavioural assertions pass.
This is done to avoid races between patch based maxUnavailable updates
and status updates to the DaemonSets causing flakiness in the tests.

Additionally, while running pull-kubevirt-check-dequarantine-test to test the previous
commit the test would often fail during the AfterEach step as a static
timeout was used when determining if the DaemonSets had been
successfully reverted back to their original state. This is different to
the actual tests that have a much longer dynamic timeout based on
DesiredNumberScheduled of the DaemonSets.

This change also aligns the AfterEach timeout with that of the tests and
inlines the assertions of the Eventually.

[pull-kubevirt-check-dequarantine-test](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15132/pull-kubevirt-check-dequarantine-test/1949202445875810304) ran over the weekend and completed 387 successful test runs before an unrelated failure of `ginkgo` locking up.

### References
 
- Fixes #15150

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by enp0s3** [comment]
@lyarwood Hi, thanks for taking care of it. I did some work in that area as well: 
https://github.com/kubevirt/kubevirt/pull/9513
As part of this PR I've fixed the e2e test in way it revealed a bug in the canary method. I don't remember if we have an 
issue about it, however if you want we can sync on this topic.

**Comment by enp0s3** [comment]
@lyarwood When I worked on that PR back then I was under assumption that the canary method should be used both in upgrade scenario, and also in virt-handler rollout scenario. Stand-alone virt-handler rollout scenario can happen if for example you change something in the virt-handler manifest via CustomizeComponents, or when you change the max VMs per node value.
In turns out that Antonio meant the canary deployment method to happen only on upgrades and not on simple roll-outs.
So we need to fix it in a way that canary method will be used only on upgrades.

**Comment by lyarwood** [comment]
> @lyarwood When I worked on that PR back then I was under assumption that the canary method should be used both in upgrade scenario, and also in virt-handler rollout scenario. Stand-alone virt-handler rollout scenario can happen if for example you change something in the virt-handler manifest via CustomizeComponents, or when you change the max VMs per node value.
> In turns out that Antonio meant the canary deployment method to happen only on upgrades and not on simple roll-outs.
> So we need to fix it in a way that canary method will be used only on upgrades.

@enp0s3 can you write this up somewhere and we can look at addressing it in a follow up? For now this PR looks stable enough to get the functional test for the existing behaviour out of quarantine.

**Comment by enp0s3** [comment]
@lyarwood Sure, will do.

File: tests/canary_upgrade_test.go [hunk 1]
```diff
@@ -195,16 +175,29 @@ var _ = Describe("[sig-operator]virt-handler canary upgrade", Serial, decorators
...
+
+			podList, err := virtCli.CoreV1().Pods(flags.KubeVirtInstallNamespace).List(context.Background(), metav1.ListOptions{LabelSelector: "kubevirt.io=virt-handler"})
+			g.Expect(err).ToNot(HaveOccurred())
+
+			updatedPods := slices.DeleteFunc(podList.Items, func(pod corev1.Pod) bool {
+				_, exists := pod.Annotations[e2eCanaryTestAnnotation]
+				return !exists
+			})
+			g.Expect(updatedPods).To(HaveLen(int(ds.Status.DesiredNumberScheduled)))
+		}, updateTimeout*time.Second, 1*time.Second).Should(Succeed())
```
Comment (0xFelix) [inline tests/canary_upgrade_test.go:201]:
```suggestion
		}, updateTimeout, 1*time.Second).Should(Succeed())
```

Is it okay to drop `time.Second` from `updateTimeout`?

File: tests/canary_upgrade_test.go [hunk 2]
```diff
@@ -195,16 +175,29 @@ var _ = Describe("[sig-operator]virt-handler canary upgrade", Serial, decorators
 			},
 		})
 
-		err = updateVirtHandler()
+		err := updateVirtHandler()
 		Expect(err).ToNot(HaveOccurred())
```
Comment (0xFelix) [inline tests/canary_upgrade_test.go:179]:
```suggestion
		Expect(updateVirtHandler()).To(Succeed())
```

nit

File: tests/canary_upgrade_test.go [hunk 3]
```diff
@@ -78,19 +87,14 @@ var _ = Describe("[sig-operator]virt-handler canary upgrade", Serial, decorators
...
-		Eventually(func() bool {
+		Eventually(func(g Gomega) {
 			ds, err := virtCli.AppsV1().DaemonSets(originalKV.Namespace).Get(context.Background(), "virt-handler", metav1.GetOptions{})
-			Expect(err).ToNot(HaveOccurred())
-			return ds.Status.DesiredNumberScheduled == ds.Status.NumberReady && ds.Spec.UpdateStrategy.RollingUpdate.MaxUnavailable.IntValue() == 1
-		}, 60*time.Second, 1*time.Second).Should(BeTrue(), "waiting for virt-handler to be ready")
+			g.Expect(err).ToNot(HaveOccurred())
+			g.Expect(ds.Status.DesiredNumberScheduled).To(Equal(ds.Status.NumberReady))
+			g.Expect(ds.Spec.UpdateStrategy.RollingUpdate.MaxUnavailable.IntValue()).To(Equal(1))
+		}, updateTimeout*time.Second, 1*time.Second).Should(Succeed(), "waiting for virt-handler to be ready")
```
Comment (0xFelix) [inline tests/canary_upgrade_test.go:95]:
```suggestion
		}, updateTimeout, 1*time.Second).Should(Succeed(), "waiting for virt-handler to be ready")
```

Same?

File: tests/canary_upgrade_test.go (hunk 1 above)
Comment (lyarwood) [reply tests/canary_upgrade_test.go:201]: https://pkg.go.dev/time#Duration `Durtation` is stored in nanoseconds so no we can't drop it here without using it during the initial assignment of `updateTimeout`, that's no a bad idea but more of a nit IMHO.

**Comment by xpivarc** [comment]
@enp0s3 Why would we limit this only to updates? Btw if I am not mistake we don't use canary only when we deploy KubeVirt first time.

File: tests/canary_upgrade_test.go [hunk 4]
```diff
@@ -199,12 +176,26 @@ var _ = Describe("[sig-operator]virt-handler canary upgrade", Serial, decorators
...
 		updateTimeout := time.Duration(canaryTestNodeTimeout * nodesToUpdate)
-		Eventually(func() bool {
+		Eventually(func(g Gomega) {
 			expectedEventsLock.Lock()
 			defer expectedEventsLock.Unlock()
-			return len(expectedEvents) == 0
-		}, updateTimeout*time.Second, 1*time.Second).Should(BeTrue(), fmt.Sprintf("events %v were expected but did not occur", expectedEvents))
-
-		Expect(isVirtHandlerUpdated(getVirtHandler())).To(BeTrue())
+			g.Expect(expectedEvents).To(BeEmpty())
```
Comment (xpivarc) [inline tests/canary_upgrade_test.go:184]: Why can we remove the lock?

File: tests/canary_upgrade_test.go [hunk 5]
```diff
@@ -199,12 +176,26 @@ var _ = Describe("[sig-operator]virt-handler canary upgrade", Serial, decorators
...
+		}, updateTimeout*time.Second, 1*time.Second).Should(Succeed(), fmt.Sprintf("events %v were expected but did not occur", expectedEvents))
+
+		Eventually(func(g Gomega) {
```
Comment (xpivarc) [inline tests/canary_upgrade_test.go:187]: Shouldn't this be `Expect` as after the canary it should be all done?

File: tests/canary_upgrade_test.go (hunk 4 above)
Comment (lyarwood) [reply tests/canary_upgrade_test.go:184]: We don't, it's still there?

File: tests/canary_upgrade_test.go (hunk 5 above)
Comment (lyarwood) [reply tests/canary_upgrade_test.go:187]: I think that assumption was the source of the previous flakiness tbh and resulted in the update to status being missed. I'm using `Eventually` here to be defensive and allow for the initial checks to fail.

File: tests/canary_upgrade_test.go (hunk 4 above)
Comment (xpivarc) [reply tests/canary_upgrade_test.go:184]: Sorry, I see t now, somehow I saw red on the Lock lines

File: tests/canary_upgrade_test.go (hunk 5 above)
Comment (xpivarc) [reply tests/canary_upgrade_test.go:187]: Can you elaborate? I am not sure I follow.

Comment (lyarwood) [reply tests/canary_upgrade_test.go:187]: I think I also misunderstood your initial point sorry. Are suggesting L184 should just be `Expect(expectedEvents).To(BeEmpty())` or that `Expect(isVirtHandlerUpdated(getVirtHandler())).To(BeTrue())` should still be asserted here?

**Comment by enp0s3** [comment]
> @enp0s3 Why would we limit this only to updates? Btw if I am not mistake we don't use canary only when we deploy KubeVirt first time.

@xpivarc I've been told by Antonio about it, but maybe I misunderstood him.

**Review by enp0s3 — COMMENTED** [review]
/lgtm
@lyarwood Thank you!

IMO this whole idea of having a bucket of expected events and rely on the client informer is a flaky approach, I would enhance the Kubevirt CR status to reflect the canary upgrade process, and in the e2e to check the status.
