### PR TITLE
virt-launcher: disable isa-debugcon on Arm64

### LINKED ISSUE #7650: E2E tests for Arm64 failed because attach unsupported device `isa-debugcon`
**What happened**:
The test case ` [test_id:8531]enabled when log verbosity is high` in `pull-kubevirt-e2e-arm64` failed, because attach unsupported device `isa-debugcon`
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7637/pull-kubevirt-e2e-arm64/1519545667360395264

### PR DESCRIPTION
**Pull request by zhlhahaha**
Device isa-debugcon does not support on Arm64,
and no good alternative device found, so just
disable it on Arm64.

Signed-off-by: Howard Zhang <howard.zhang@arm.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7650

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by xpivarc — COMMENTED** [review]
/approve
/cc @vladikr

File: pkg/virt-launcher/virtwrap/converter/converter.go [hunk 1]
```diff
@@ -1832,8 +1832,8 @@ func Convert_v1_VirtualMachineInstance_To_api_Domain(vmi *v1.VirtualMachineInsta
 		}
 	}
 
-	if virtLauncherLogVerbosity, err := strconv.Atoi(os.Getenv(services.ENV_VAR_VIRT_LAUNCHER_LOG_VERBOSITY)); err == nil && (virtLauncherLogVerbosity > services.EXT_LOG_VERBOSITY_THRESHOLD) {
-
+	if virtLauncherLogVerbosity, err := strconv.Atoi(os.Getenv(services.ENV_VAR_VIRT_LAUNCHER_LOG_VERBOSITY)); err == nil && (virtLauncherLogVerbosity > services.EXT_LOG_VERBOSITY_THRESHOLD) && !isARM64(c.Architecture) {
```
Comment (maya-r) [inline pkg/virt-launcher/virtwrap/converter/converter.go:1835]: Given that ISA is purely an x86 thing, it would be nice to test for x86 rather than !arm

Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/converter/converter.go:1835]: Make sense.
