### PR TITLE
api: Introduce and use domain-qualified version of the foregroundDeleteVirtualMachine finalizer

### LINKED ISSUE #15095: metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
**What happened**:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14967/pull-kubevirt-e2e-arm64/1942201995842555904

```
W0707 13:05:14.007287  342008 warnings.go:70] metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does

This resolves the following warning often spammed in our e2e test logs:

```
W0707 13:05:14.007287  342008 warnings.go:70] metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```

The original non-FQDN version of this finalizer has been deprecated for removal in a future release.

### References

- Fixes #15095

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
The `foregroundDeleteVirtualMachine` has been deprecated and replaced with the domain-qualified `kubevirt.io/foregroundDeleteVirtualMachine`.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
```
11:54:19: {"component":"","level":"fatal","msg":"Could not merge JUnit files","pos":"junit-merger.go:40","reason":"test 'VirtualMachineInstance watcher On valid VirtualMachineInstance given should remove the fore ground finalizer if no pod is present and the vmi is in  succeeded state' was executed multiple times","timestamp":"2025-08-01T11:54:19.671734Z"}
11:54:19: panic: Could not merge JUnit files
11:54:19: 
11:54:19: goroutine 1 [running]:
11:54:19: kubevirt.io/client-go/log.FilteredLogger.Critical({{0x88ad20, 0xc0001992b0}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x2, {0x88aba0, 0xc000044030}}, ...)
11:54:19: 	staging/src/kubevirt.io/client-go/log/log.go:335 +0x18c
11:54:19: main.main()
11:54:19: 	tools/junit-merger/junit-merger.go:40 +0x505
make: *** [Makefile:49: bazel-test] Error 2
```

/hold

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 1]
```diff
@@ -1653,15 +1653,17 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
 			Expect(updatedVmi.Status.Phase).To(Equal(phase))
-			Expect(updatedVmi.Finalizers).ToNot(ContainElement(virtv1.VirtualMachineInstanceFinalizer))
+			Expect(updatedVmi.Finalizers).ToNot(ContainElement(finalizer))
 		},
-			Entry("succeeded state", virtv1.Succeeded),
-			Entry("failed state", virtv1.Failed),
+			Entry("succeeded state", virtv1.Succeeded, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
+			Entry("failed state", virtv1.Failed, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
+			Entry("succeeded state", virtv1.Succeeded, virtv1.VirtualMachineInstanceFinalizer),
+			Entry("failed state", virtv1.Failed, virtv1.VirtualMachineInstanceFinalizer),
```
Comment (dasionov) [inline pkg/virt-controller/watch/vmi/vmi_test.go]: panic error is because even tho you added an argument to the entrees you still have same test name for both entrees which makes the junit merger mistakenly panic thinking the same test was executed multiple times

```suggestion
			Entry("succeeded state with deprecated finelizer", virtv1.Succeeded, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
			Entry("failed state with deprecated finelizer", virtv1.Failed, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
			Entry("succeeded state with domain-qualified finalizer", virtv1.Succeeded, virtv1.VirtualMachineInstanceFinalizer),
			Entry("failed state with domain-qualified finalizer", virtv1.Failed, virtv1.VirtualMachineInstanceFinalizer),
```

Comment (lyarwood) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: 🤦🏻

Comment (lyarwood) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: Thanks @dasionov, didn't have time to re-spin on Friday. Can you review again?

**Review by dasionov — APPROVED** [review]

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 2]
```diff
@@ -1653,15 +1653,17 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
+			Entry("succeeded state with deprecated finalizer", virtv1.Succeeded, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
+			Entry("failed state with deprecated finalizer", virtv1.Failed, virtv1.DeprecatedVirtualMachineInstanceFinalizer),
+			Entry("succeeded state with domain-qualified finalizer", virtv1.Succeeded, virtv1.VirtualMachineInstanceFinalizer),
+			Entry("failed state with domain-qualified finalizer", virtv1.Failed, virtv1.VirtualMachineInstanceFinalizer),
 		)
 
 		DescribeTable("VM controller finalizer", func(hasOwner, vmExists, expectFinalizer bool) {
 			vmi := newPendingVirtualMachine("testvmi")
-			vmi.Finalizers = append(vmi.Finalizers, virtv1.VirtualMachineControllerFinalizer, virtv1.VirtualMachineInstanceFinalizer)
+			vmi.Finalizers = append(vmi.Finalizers, virtv1.VirtualMachineControllerFinalizer, virtv1.DeprecatedVirtualMachineInstanceFinalizer)
```
Comment (xpivarc) [inline pkg/virt-controller/watch/vmi/vmi_test.go]: Should we append both?

**Review by xpivarc — COMMENTED** [review]
/approve
/hold

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 2 above)
Comment (lyarwood) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: @xpivarc ACK done thanks

**Review by dasionov — APPROVED** [review]
Thank you @lyarwood 
/lgtm
