### PR TITLE
fix(virt-controller): prevent exec probes to be wrapped twice

### LINKED ISSUE #11755: Extra wrap of the `exec` commands by `virt-probe` in liveness/readiness probes in vm/vmi, booted from DataVolume.
**What happened**:
liveness/readiness probes with the exec command do not work if the machine boots with DataVolume. 
```
$ kubectl get vmi
NAME                       AGE   PHASE     IP           NODENAME             READY
vmi-fedora                 15m   Running   10.3.0.127   kube-virt-master-1   False

$ kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
virt-launcher-vmi-fedora-6wnrp   1/2     Running   0          14m

$ kubectl describe  pod virt-launcher-vmi-fedora-6wnrp
...
  Warning  Unhealthy       16m   kubelet            Readiness probe failed: {"component":"virt-probe","level":"fatal","msg":"Failed executing the command","pos":"virt-probe.go:71","reason":"rpc error: code = Unknown desc = virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU agent command 'guest-exec': Guest agent command failed, error was 'Failed to execute child process “virt-probe” (No such file or directory)'')","timestamp":"2024-04-20T08:50:58.153726Z"}
panic: Failed executing the command

goroutine 1 [running]:
kubevirt.io/client-go/log.FilteredLogger.Critical({{0x117c9c0, 0xc0001e9650}, {0xfddaf8, 0xa}, 0x0, 0x0, 0x2, 0x2, {0x117d280, 0xc00011c050}}, ...)
  staging/src/kubevirt.io/client-go/log/log.go:334 +0x189
main.main()
```
**What you expected to happen**:
The test was expected to be successful. The check works if the partition type is not dataVolume (for example, containerDisk).

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy `DataVolume` and `VirtualMachine` (or `VirtualMachineInstance`).
2. View  the VirtualMachine code before the DataVolume is prvissioned.
```
$ kubectl get dv
NAME                                       PHASE             PROGRESS   RESTARTS   AGE
probe-fedora-disk                          ImportScheduled   N/A                   66s
$ kubectl get vmi vmi-fedora -o yaml
...
  readinessProbe:
    exec:
      command:
      - virt-probe
      - --domainName
      - demo_vmi-fedora
      - --timeoutSeconds
      - "5"
      - --command
      - cat
      - --
      - /tmp/healthy.txt
    failureThreshold: 10
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
...
```
3.  View  the VirtualMachine code when the DataVolume is prvissioned and vmi is booted.
```
$ kubectl get dv
NAME                                       PHASE             PROGRESS   RESTARTS   AGE
probe-fedora-disk                          ImportScheduled   N/A                   66s
$ kubectl get vmi vmi-fedora -o yaml
...
  readinessProbe:
    exec:
      command:
      - virt-probe
      - --domainName
      - demo_vmi-fedora
      - --timeoutSeconds
      - "5"
      - --command
      - virt-probe
      - --
      - --domainName
      - demo_vmi-fedora
      - --timeoutSeconds
      - "5"
      - --command
      - cat
      - --
      - /tmp/healthy.txt
    failureThreshold: 10
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
...
```
**Environment**:
- KubeVirt version (use `virtctl version`): 
```
$ virtctl version
Client Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T20:34:24Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+k3s1
```
- VMI and DataVolume specifications:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-base-img
  namespace: demo
spec:
  running: true
  template:
    spec:
      networks:
      - name: vpc_net_0
        multus:
          default: true
          networkName: default/ovn-demo
      domain:
        devices:
          interfaces:
            - name: vpc_net_0
              bridge: {}
          disks:
          - disk: 
              bus: virtio
            name: root-volume
          - name: cloudinitdisk
            disk:
              bus: virtio
          rng: {}
        cpu:
          cores: 1
        memory:
          guest: 4G
      readinessProbe:
        exec:
          command: ["cat", "/tmp/healthy.txt"]
        failureThreshold: 10
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
      terminationGracePeriodSeconds: 60
      volumes:
      - dataVolume:
          name: fedora-base-img
        name: root-volume
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            chpasswd: { expire: False }
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-base-img
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20G
    storageClassName: local-path
  source:
    registry:
      url: "docker://quay.io/containerdisks/fedora"
```
- Cloud provider or hardware configuration: k3s on bare metal servers

### PR DESCRIPTION
**Pull request by BarthV**
### What this PR does
Before this PR:
* There's an unidentified "double reconcile" and/or kind of race condition that is wrapping the exec conmmand twice when processing a VMI.
* Wrapping a `virt-probe` inside another `virt-probe` command definitely breaks the VMI and then requires a manual operation to fix it.

After this PR:
* wrapping function now verfiies that VMI probe exec command is not already wrapped before wrapping it.

**Fixes #11755**

### Why we need it and why it was done in this way
The following tradeoffs were made:
* _none_

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by BarthV** [comment]
Hi everyone, this issue hit me again. So I decided to propose something to fix it.
Feel free to review this PR :) !

Thanks for this project and for all your contributions.

**Comment by BarthV** [comment]
rebased & signed

**Comment by mhenriks** [comment]
> rebased & signed

I don't think you meant to update OWNERS_ALIASES

**Comment by BarthV** [comment]
> > rebased & signed
> 
> I don't think you meant to update OWNERS_ALIASES

yep , my bad. .. this project is going too fast for my git-fu ;D

It should be fixed now

File: pkg/virt-controller/services/rendercontainer.go [hunk 1]
```diff
@@ -254,6 +254,12 @@ func wrapExecProbeWithVirtProbe(vmi *v1.VirtualMachineInstance, probe *k8sv1.Pro
 		"--command", originalCommand[0],
 		"--",
 	}
+
+	// skip wrapping if command is already wrapped with "virt-probe" cli tool
+	if originalCommand[0] == wrappedCommand[0] {
+		return
+	}
```
Comment (fossedihelm) [inline pkg/virt-controller/services/rendercontainer.go:261]: I would have run this check even earlier (line 246):
```golang
	if len(originalCommand) < 1 || originalCommand[0] == "virt-probe" {
		return
	}
```

File: pkg/virt-controller/services/rendercontainer_test.go [hunk 2]
```diff
@@ -243,6 +245,40 @@ var _ = Describe("Container spec renderer", func() {
...
+			}
+
+			It("its pod should feature the same exec probe but wrapped in a virt-probe command", func() {
+				probe := dummyProbe()
+				probe.Handler = v1.Handler{
+					Exec: &k8sv1.ExecAction{Command: []string{"dummy-cli"}},
+				}
+				specRenderer = NewContainerSpecRenderer(containerName, img, pullPolicy, WithLivelinessProbe(
+					vmiWithLivenessProbe(probe)))
+				Expect(specRenderer.Render(exampleCommand).LivenessProbe.Exec.Command).To(Equal(expectedExecCmd))
```
Comment (fossedihelm) [inline pkg/virt-controller/services/rendercontainer_test.go:265]: You can get rid of `expectedExecCmd` context scope variable with:
```golang
				Expect(specRenderer.Render(exampleCommand).LivenessProbe.Exec.Command).To(HaveExactElements(
					"virt-probe",
					"--domainName", "_",
					"--timeoutSeconds", strconv.FormatInt(int64(dummyProbe().TimeoutSeconds), 10),
					"--command", "dummy-cli",
					"--"))
```
OR
please move the `expectedExecCmd` inside the `It` block.
Even if currently there is only one `It`, this could not be true forever in the future, and this global var can lead to errors.

File: pkg/virt-controller/services/rendercontainer_test.go [hunk 3]
```diff
@@ -243,6 +245,40 @@ var _ = Describe("Container spec renderer", func() {
...
+			})
+		})
+
+		Context("pre-wrapped liveness exec probe", func() {
+			var expectedExecCmd = []string{"virt-probe", "--", "dummy-cli"}
```
Comment (fossedihelm) [inline pkg/virt-controller/services/rendercontainer_test.go:270]: Please move to the `It` block below!

**Review by fossedihelm — COMMENTED** [review]
Thank you for your contribution @BarthV.
Looks good overall, just some small comments below. :slightly_smiling_face:

File: pkg/virt-controller/services/rendercontainer_test.go (hunk 3 above)
Comment (BarthV) [reply pkg/virt-controller/services/rendercontainer_test.go]: fixed as requested

File: pkg/virt-controller/services/rendercontainer_test.go (hunk 2 above)
Comment (BarthV) [reply pkg/virt-controller/services/rendercontainer_test.go]: fixed as requested

File: pkg/virt-controller/services/rendercontainer.go (hunk 1 above)
Comment (BarthV) [reply pkg/virt-controller/services/rendercontainer.go]: fixed as requested

**Comment by BarthV** [comment]
Thanks for the review, everything should have been fixed.

**Comment by fossedihelm** [comment]
Thank you!
/lgtm
/test all

**Comment by BarthV** [comment]
_(test failed by exceeding the 1h job duration limit, code seems not faulty here)_

**Comment by fossedihelm** [comment]
@BarthV yes, all good.
/retest

**Comment by BarthV** [comment]
gentle bump :angel:

File: pkg/virt-controller/services/rendercontainer_test.go [hunk 4]
```diff
@@ -243,6 +245,36 @@ var _ = Describe("Container spec renderer", func() {
 				Expect(specRenderer.Render(exampleCommand).LivenessProbe).To(Equal(probeWithDelay(probe)))
 			})
 		})
+
+		Context("liveness exec probe", func() {
+			It("its pod should feature the same exec probe but wrapped in a virt-probe command", func() {
```
Comment (vladikr) [inline pkg/virt-controller/services/rendercontainer_test.go:250]: Could you please rephrase this sentence? Perhaps to something like "should wrap the liveness exec probe command inside virt-probe while preserving the original command"?

File: pkg/virt-controller/services/rendercontainer_test.go [hunk 5]
```diff
@@ -243,6 +245,36 @@ var _ = Describe("Container spec renderer", func() {
...
+					"virt-probe",
+					"--domainName", "_",
+					"--timeoutSeconds", strconv.FormatInt(int64(dummyProbe().TimeoutSeconds), 10),
+					"--command", "dummy-cli",
+					"--"))
+			})
+		})
+
+		Context("pre-wrapped liveness exec probe", func() {
+			It("its pod should feature the same exec probe without getting wrapped again", func() {
```
Comment (vladikr) [inline pkg/virt-controller/services/rendercontainer_test.go:267]: here as well, please.

**Comment by BarthV** [comment]
> Thank you! Please consider updating the test titles.

Hi,

Test titles have been updated + branch rebased

Thanks !

File: pkg/virt-controller/services/rendercontainer_test.go (hunk 5 above)
Comment (BarthV) [reply pkg/virt-controller/services/rendercontainer_test.go]: title updated here too

**Comment by BarthV** [comment]
It might requires a new LGTM

**Comment by BarthV** [comment]
Hi !
do you need anything spécial to make it pass the CI ? (which seems still timeouting for reasons out or the scope of this PR)

Thanks

**Comment by fossedihelm** [comment]
@BarthV Hey, nope. Just unrelated flakiness. Once approved, the bot will retest it automatically.
@vladikr :ping_pong: 
Thanks

**Comment by vladikr** [comment]
/approve

Thank you!

**Comment by xpivarc** [comment]
@BarthV Do we need to backport this? What are affected versions?

**Comment by BarthV** [comment]
I am running v1.1.1, so I suspect many versions to be impacted.

TBH, I dont expect you to go back this long in time. Do your what you can on currently supported versions, and this will be great !

On our side, we're already running with a patched version. And we will plan an upgrade as soon as your new release will be tagged.

Thanks a lot

**Comment by xpivarc** [comment]
/cherry-pick release-1.5
/cherry-pick release-1.4
/cherry-pick release-1.3
/cherry-pick release-1.2
/cherry-pick release-1.1

Let's see how far we can get automatically.
