### PR TITLE
fix(virtctl): support TigerVNC 1.16.0+ path on macOS

### LINKED ISSUE #16755: virtctl vnc MACOS_TIGER_VNC_PATTERN path change
**What happened**:
- Installed latest tiger vnc viewer for MacOS
- Attempted to use `virtctl vnc <vmname>`, received error `error encountered: no supported VNC app found for darwin`

Looking at the [code](https://github.com/kubevirt/kubevirt/blob/a4b697129c05ab45424831c6e6c2d871761895fc/pkg/virtctl/vnc/vnc.go#L52), it expects the path to be `/Applications/TigerVNC Viewer *.app/Contents/MacOS/TigerVNC Viewer` but the latest version 1.16.0 has a different path (`/Applicatons/TigerVNC/Contents/MacOS/vncviewer`), as per the screenshot below showing the app package:

Image

**What you expected to happen**:
TigerVNC is launched and the vnc session starts

**How to reproduce it (as minimally and precisely as possible)**:
Use MacOS, install TigerVNC 1.16.0 as the only VNC client, attempt to launch vnc from `virtctl`, observe failure

**Environment**:
- KubeVirt version (use `virtctl version`): 1.7.0
- Kubernetes version (use `kubectl version`): 1.34.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): MacOS 26.2
- Kernel (e.g. `uname -a`): N/A
- Install tools: TigerVNC 1.16.0
- Others: N/A

### PR DESCRIPTION
**Pull request by shivansh-gohem**
**What this PR does / why we need it**:
TigerVNC 1.16.0 changed its default installation path on macOS from `/Applications/TigerVNC Viewer *.app/...` to `/Applications/TigerVNC.app/...`. This caused `virtctl vnc` to fail to auto-detect the viewer. 

This PR adds the new deterministic path (`/Applications/TigerVNC.app/Contents/MacOS/vncviewer`) and checks it using `os.Stat` before falling back to the legacy wildcard pattern, ensuring both new and old installations of TigerVNC are supported without breaking backward compatibility.

**Which issue(s) this PR fixes**:
Fixes #16755

**Special notes for the reviewer**:
Used `os.Stat` for the new path since it does not contain wildcards, avoiding the overhead of `filepath.Glob`.

**Release note**:
```release-note
Fixed an issue where `virtctl vnc` failed to auto-detect TigerVNC 1.16.0 and newer on macOS due to an application path change.

### CODE REVIEW

File: pkg/virtctl/vnc/vnc.go [hunk 1]
```diff
@@ -50,6 +50,8 @@ const (
 	//# https://github.com/TigerVNC/tigervnc/releases
 	// Compatible with multiple Tiger VNC versions
 	MACOS_TIGER_VNC_PATTERN = `/Applications/TigerVNC Viewer *.app/Contents/MacOS/TigerVNC Viewer`
+	// Tiger VNC 1.16.0+ changed the default app name
+	MACOS_TIGER_VNC_NEW_PATH = `/Applications/TigerVNC.app/Contents/MacOS/vncviewer`
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go]: nit: Call this `MACOS_TIGER_VNC_PATTERN` and rename existing to `MACOS_TIGER_VNC_LEGACY_PATTERN`?

**Comment by shivansh-gohem** [comment]
@0xFelix pushed the changes you requested , ready for review!!!

File: pkg/virtctl/vnc/vnc.go [hunk 2]
```diff
@@ -260,7 +262,9 @@ func getUserSpecifiedVnc(ctx context.Context, osType, vncType, vncPath string, p
 func getAutoDetectedVnc(osType string, port int) (string, []string, error) {
 	switch osType {
 	case "darwin":
-		if matches, err := filepath.Glob(MACOS_TIGER_VNC_PATTERN); err == nil && len(matches) > 0 {
+		if _, err := os.Stat(MACOS_TIGER_VNC_PATTERN); err == nil {
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:265]: Should this check if it is "error not exists"?

**Comment by shivansh-gohem** [comment]
@0xFelix   i have pushed the required changes!

**Comment by shivansh-gohem** [comment]
@0xFelix The `manifests` job failed due to a 1-hour prow timeout, and the `sig-compute` lanes failed on unrelated Live Migration flakes. Could you please run `/retest-required` when you have a chance? Thank you!

**Comment by dhiller** [comment]
Retriggered the tests, awaiting to get whipped by the referee again :-/

**Comment by dhiller** [comment]
Latest CI run has all green except the serial lane, awaitng green CI soon.

/unhold
