### PR TITLE
instancetype, snapshot: Capture and restore instancetype ControllerRevisions

### LINKED ISSUE #8446: `VirtualMachineClones` do not clone or update existing `VirtualMachineInstancetype` `ControllerRevisions` used by a `VirtualMachine`
/area instancetype
/cc @iholder-redhat

**What happened**:

`ControllerRevisions` referenced by a `VirtualMachine` storing copies of `VirtualMachine{ClusterInstancetype,Instancetype,ClusterPreference,Preference} ` are not cloned or updated by the `VirtualMachineClone` API.

**What you expected to happen**:

These `ControllerRevisions` should be cloned when referenced by the `VirtualMachine` or have their `OwnerReferences` updated to reflect that two `VirtualMachines` are now using the same `ControllerRevision`.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ export KUBEVIRT_STORAGE=rook-ceph-default

$ ./cluster-up/kubectl.sh get kubevirt/kubevirt -n kubevirt -o json | jq .spec.configuration.developerConfiguration.featureGates
selecting docker as container runtime
[
  "Snapshot"
]

$ cat <<EOF |  ./cluster-up/kubectl.sh apply -f -
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: csmall
spec:
  cpu:
    guest: 1
  memory:
    guest: 128Mi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros-datavolume-with-instancetype
  name: vm-cirros-datavolume-with-instancetype
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: cirros-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: rook-ceph-block 
      source:
        registry:
          url: docker://registry:5000/kubevirt/cirros-container-disk-demo:devel
  instancetype:
    kind: VirtualMachineInstancetype
    name: csmall
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-datavolume-with-instancetype
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: cirros-dv
        name: datavolumedisk1
EOF

# Until https://github.com/kubevirt/kubevirt/pull/8346 lands we need to start and stop the VM to create an instancetype CR
$ ./cluster-up/virtctl.sh start vm-cirros-datavolume-with-instancetype
$ ./cluster-up/kubectl.sh wait vms/vm-cirros-datavolume-with-instancetype --for condition=Ready
$ ./cluster-up/virtctl.sh stop vm-cirros-datavolume-with-instancetype

$ cat <<EOF | ./cluster-up/kubectl.sh apply -f -
kind: VirtualMachineClone
apiVersion: "clone.kubevirt.io/v1alpha1"
metadata:
  name: testclone
spec:
  # source & target definitions
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros-datavolume-with-instancetype
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: vm-cirros-datavolume-with-instancetype-clone
EOF

$ ./cluster-up/kubectl.sh get vms/vm-cirros-datavolume-with-instancetype -o json | jq .spec.instancetype
selecting docker as container runtime
{
  "kind": "VirtualMachineInstancetype",
  "name": "csmall",
  "revisionName": "vm-cirros-datavolume-with-instancetype-csmall-9282c1d2-87b7-40aa-b364-a2221cf351e7-1"
}

$ ./cluster-up/kubectl.sh get vms/vm-cirros-datavolume-with-instancetype-clone -o json | jq .spec.instancetype
selecting docker as container runtime
{
  "kind": "VirtualMachineInstancetype",
  "name": "csmall",
  "revisionName": "vm-cirros-datavolume-with-instancetype-csmall-9282c1d2-87b7-40aa-b364-a2221cf351e7-1"
}

$ ./cluster-up/kubectl.sh get controllerrevisions/vm-cirros-datavolume-with-instancetype-csmall-9282c1d2-87b7-40aa-b364-a2221cf351e7-1 -o json | jq  .metadata.ownerReferences
selecting docker as container runtime
[
  {
    "apiVersion": "kubevirt.io/v1",
    "blockOwnerDeletion": true,
    "controller": true,
    "kind": "VirtualMachine",
    "name": "vm-cirros-datavolume-with-instancetype",
    "uid": "9e8b9247-fcd0-45ba-81ee-4bb0c99919d3"
  }
]

```

**Additional context**:

I'm still fighting with https://github.com/kubevirt/kubevirt/issues/8435 but wanted to at least document this separate IMHO `VirtualMachineClone` issue with instancetypes.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @iholder-redhat
/cc @akrejcir

**What this PR does / why we need it**:

Previously no attempt was made to capture copies of the original instancetype or preference `ControllerRevisions` or later to restore these. This could obviously lead to issues if later restoring or cloning into a new `VirtualMachine`.

This change now captures fresh copies of these `ControllerRevisions`, associates them with the `VirtualMachineSnapshot` and later restores these `ControllerRevisions` into the target `VirtualMachine`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8446

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/storage/snapshot/restore_test.go [hunk 1]
```diff
@@ -877,8 +881,24 @@ var _ = Describe("Restore controlleer", func() {
...
 
-				})
+					It("without instancetype and preference RevisionNames from original VM", func() {
+						// Add the revisionNames for the original VM instancetype and preference
+						r.Spec.Patches = []string{changeInstancetypePatch, changePreferencePatch}
+
+						vmInterface.EXPECT().Create(gomock.Any()).DoAndReturn(func(newVM *v1.VirtualMachine) (*v1.VirtualMachine, error) {
+							// Assert that these are then dropped when creating the new VirtualMachine
+							Expect(newVM.Spec.Instancetype.RevisionName).To(Equal(""))
+							Expect(newVM.Spec.Preference.RevisionName).To(Equal(""))
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore_test.go:891]: nit: I think `BeEmpty()` is clearer

```go
Expect(newVM.Spec.Instancetype.RevisionName).To(BeEmpty())
Expect(newVM.Spec.Preference.RevisionName).To(BeEmpty())
```

wdyt? :)

File: tests/storage/clone.go [hunk 2]
```diff
@@ -447,6 +450,100 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+
+				It("should create new ControllerRevisions for cloned VM", func() {
+					By("Waiting until the source VM has instancetype and preference RevisionNames")
+					Eventually(func() bool {
+						sourceVM, err = virtClient.VirtualMachine(sourceVM.Namespace).Get(sourceVM.Name, &metav1.GetOptions{})
+						if err != nil {
+							return false
+						}
+						return sourceVM.Spec.Instancetype.RevisionName != "" && sourceVM.Spec.Preference.RevisionName != ""
+					}, 300*time.Second, 1*time.Second).Should(BeTrue())
```
Comment (iholder-redhat) [inline tests/storage/clone.go:528]: Please use description to explain this error, or else it would look like "false is expected to be true" therefore not very readable. You can simply add a description this way:
```go
 300*time.Second, 1*time.Second).Should(BeTrue(), "instance type and preference revisions are expected to not be empty")
```
Or you can use the following style which I find even better:
```go
Eventually(func() error {
	sourceVM, err = virtClient.VirtualMachine(sourceVM.Namespace).Get(sourceVM.Name, &metav1.GetOptions{})
	if err != nil {
		return false
	}
	if sourceVM.Spec.Instancetype.RevisionName != "" {
		return fmt.Errorf("instancetype revision name expected to not be empty")
	}
	
	if sourceVM.Spec.Preference.RevisionName != "" {
		return fmt.Errorf("preference revision name expected to not be empty")
	}
	
	return nil
}, 300*time.Second, 1*time.Second).ShouldNot(HaveOccured())
``

File: tests/storage/clone.go [hunk 3]
```diff
@@ -447,6 +450,100 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+					createCloneAndWaitForFinish(vmClone)
+
+					By("Waiting until the target VM has instancetype and preference RevisionNames")
+					Eventually(func() bool {
+						targetVM, err = virtClient.VirtualMachine(sourceVM.Namespace).Get(targetVMName, &metav1.GetOptions{})
+						if err != nil {
+							return false
+						}
+						return targetVM.Spec.Instancetype.RevisionName != "" && targetVM.Spec.Preference.RevisionName != ""
+					}, 300*time.Second, 1*time.Second).Should(BeTrue())
```
Comment (iholder-redhat) [inline tests/storage/clone.go:540]: same as above

**Review by iholder-redhat — COMMENTED** [review]
Thanks a lot @lyarwood! Looks great.
Left some minor inline comments

/lgtm

File: pkg/storage/snapshot/restore_test.go (hunk 1 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore_test.go:891]: ACK makes sense thanks!

File: tests/storage/clone.go (hunk 2 above)
Comment (lyarwood) [reply tests/storage/clone.go:528]: ACK I also prefer the second style, I'll use that instead thanks!

File: tests/storage/clone.go (hunk 3 above)
Comment (lyarwood) [reply tests/storage/clone.go:540]: ACK

**Comment by iholder-redhat** [comment]
Great work @lyarwood!
/lgtm

I see that your new functest is failing, I'd be happy to re-lgtm when you fix these

**Comment by lyarwood** [comment]
> Great work @lyarwood! /lgtm
> 
> I see that your new functest is failing, I'd be happy to re-lgtm when you fix these

ACK thanks, I've fixed the timeout but I still can't get the test to pass locally. I'm getting the following error now that with practically the same code I wasn't getting in previous environments last week:

```
  Unexpected error:
      <*errors.StatusError | 0xc000656140>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "admission webhook \"vm-clone-validator.kubevirt.io\" denied the request: Virtual Machine volume disk0 does not support snapshots",
              Reason: "Invalid",
              Details: {
                  Name: "",
                  Group: "",
                  Kind: "",
                  UID: "",
                  Causes: [
                      {
                          Type: "FieldValueInvalid",
                          Message: "Virtual Machine volume disk0 does not support snapshots",
                          Field: "spec.Source",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 422,
          },
      }
      admission webhook "vm-clone-validator.kubevirt.io" denied the request: Virtual Machine volume disk0 does not support snapshots
  occurred
  In [It] at: tests/storage/clone.go:89
```

I'll let this run in CI to confirm that it isn't an issue in my env before I look any deeper.

**Comment by iholder-redhat** [comment]
> > Great work @lyarwood! /lgtm
> > I see that your new functest is failing, I'd be happy to re-lgtm when you fix these
> 
> ACK thanks, I've fixed the timeout but I still can't get the test to pass locally. I'm getting the following error now that with practically the same code I wasn't getting in previous environments last week:
> 
> ```
>   Unexpected error:
>       <*errors.StatusError | 0xc000656140>: {
>           ErrStatus: {
>               TypeMeta: {Kind: "", APIVersion: ""},
>               ListMeta: {
>                   SelfLink: "",
>                   ResourceVersion: "",
>                   Continue: "",
>                   RemainingItemCount: nil,
>               },
>               Status: "Failure",
>               Message: "admission webhook \"vm-clone-validator.kubevirt.io\" denied the request: Virtual Machine volume disk0 does not support snapshots",
>               Reason: "Invalid",
>               Details: {
>                   Name: "",
>                   Group: "",
>                   Kind: "",
>                   UID: "",
>                   Causes: [
>                       {
>                           Type: "FieldValueInvalid",
>                           Message: "Virtual Machine volume disk0 does not support snapshots",
>                           Field: "spec.Source",
>                       },
>                   ],
>                   RetryAfterSeconds: 0,
>               },
>               Code: 422,
>           },
>       }
>       admission webhook "vm-clone-validator.kubevirt.io" denied the request: Virtual Machine volume disk0 does not support snapshots
>   occurred
>   In [It] at: tests/storage/clone.go:89
> ```
> 
> I'll let this run in CI to confirm that it isn't an issue in my env before I look any deeper.

It's coming from here: https://github.com/kubevirt/kubevirt/blob/v0.57.1/pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go#L270.

This is a relatively new, so you might tackle this after a rebase. In any case - if you're using a VM with PVC/DV volumes, these volumes have to be snapshotable. My suggestion is to use container disks instead.

**Comment by lyarwood** [comment]
> It's coming from here: https://github.com/kubevirt/kubevirt/blob/v0.57.1/pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go#L270.
> 
> This is relatively new, so you might tackle this after a rebase. In any case - if you're using a VM with PVC/DV volumes, these volumes have to be snapshotable. My suggestion is to use container disks instead.

Yeah apologies I managed to remove the code waiting for the DVs to become ready in the test and also reverse the logic checking for empty revision names, should be fixed now.

File: tests/storage/clone.go [hunk 4]
```diff
@@ -447,6 +450,114 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+
+					for _, dvt := range sourceVM.Spec.DataVolumeTemplates {
+						libstorage.EventuallyDVWith(sourceVM.Namespace, dvt.Name, 180, HaveSucceeded())
+					}
+
+				})
+
+				It("should create new ControllerRevisions for cloned VM", Label("instancetype", "clone"), func() {
+					By("Waiting until the source VM has instancetype and preference RevisionNames")
+					Eventually(checkForVMInstancetypeRevisionNames(util.NamespaceTestDefault, sourceVM.Name), 300*time.Second, 1*time.Second).ShouldNot(HaveOccurred())
```
Comment (iholder-redhat) [inline tests/storage/clone.go:545]: nit: you can introduce a `waitForVMInstanceTypeRevisionNames(vmName string)` that would wrap this up nicely.

**Review by iholder-redhat — COMMENTED** [review]
/lgtm

File: tests/storage/clone.go (hunk 4 above)
Comment (lyarwood) [reply tests/storage/clone.go:545]: Yup fair point, updated.

File: pkg/storage/snapshot/restore.go [hunk 5]
```diff
@@ -562,6 +562,16 @@ func (t *vmRestoreTarget) reconcileSpec() (bool, error) {
...
+		// Drop ControllerRevision names for any referenced preference or instancetype
+		// before we create a new VM. This will force the VirtualMachine controller to
+		// recreate these for the new VM.
+		if newVM.Spec.Instancetype != nil {
+			newVM.Spec.Instancetype.RevisionName = ""
+		}
+		if newVM.Spec.Preference != nil {
+			newVM.Spec.Preference.RevisionName = ""
+		}
+
```
Comment (davidvossel) [inline pkg/storage/snapshot/restore.go:574]: what if the instancetype or preference doesn't exist anymore in the cluster? should that impact the restore?

Were any alternative solutions considered? For example, what about making a copy of the instancetype/preference controller revision when the snapshot is created?

Unless we snapshot the controller revisions as well, we might not be getting the exact same VM after a restore.

Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:574]: > Another approach might be to add the snapshot and any cloned VirtualMachines as owners of the ControllerRevision to avoid cloning?

Sounds good to me.
Further to our online conversation, I think that in order for it to work we would have to remove owner references from ControllerRevision once the owners are being deleted.

In order to do so, a controller should:
* Be informer of a resource deletion
* Search for ControllerRevisions that are owned by that resource (possibly using an informer's indexer)
* Delete the owner reference from the ControllerRevision

Once no owners are left for the ControllerRevision, it would be automatically deleted.

Or is there a better (i.e. more automatic) way to do that? I wonder how other controllers are coping with this.

Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:574]: > > Another approach might be to add the snapshot and any cloned VirtualMachines as owners of the ControllerRevision to avoid cloning?
> 
> Sounds good to me. Further to our online conversation, I think that in order for it to work we would have to remove owner references from ControllerRevision once the owners are being deleted.
> 
> In order to do so, a controller should:
> 
> * Be informer of a resource deletion
> * Search for ControllerRevisions that are owned by that resource (possibly using an informer's indexer)
> * Delete the owner reference from the ControllerRevision
> 
> Once no owners are left for the ControllerRevision, it would be automatically deleted.
> 
> Or is there a better (i.e. more automatic) way to do that? I wonder how other controllers are coping with this.

This was easy enough to do for `VirtualMachineSnapshots` but will require a new `VirtualMachine` finalizer to allow the controller to actually see the resource during deletion. @iholder-redhat I can continue with this approach if you think it's valid but I'm worried I'm introducing too much complexity here given we can just clone the `ControllerRevision` for the `VirtualMachineSnapshot`. Thoughts?

Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:574]: I think that using owner references is the better approach here. It has two advantages; it avoids duplicating data on etcd, and it's easier to debug and reason about (revision X is being used by VMs a, b, c etc).

Saying that, I don't think this is urgent at this point. It might be more significant in situations where many VMs are cloned, and even then it's probably not that big of a deal.

I'd say we can keep it to future PRs if we need to.
Thanks @lyarwood for this discussion!

Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:574]: > I think that using owner references is the better approach here. It has two advantages; it avoids duplicating data on etcd, and it's easier to debug and reason about (revision X is being used by VMs a, b, c etc).

Agreed but we already create fresh `ControllerRevisions` for each `VirtualMachine` even if they share the same data as existing `ControllerRevisions` for other `VirtualMachines`.

> Saying that, I don't think this is urgent at this point. It might be more significant in situations where many VMs are cloned, and even then it's probably not that big of a deal.
> 
> I'd say we can keep it to future PRs if we need to. Thanks @lyarwood for this discussion!

ACK, yeah I agree that this is a future improvement, I've write up an [issue](https://github.com/kubevirt/kubevirt/issues/8591) and target it at the [`v1beta1` tracker](https://github.com/kubevirt/kubevirt/issues/8235).

For now I'll switch over to cloning the CRs for each `VirtualMachineSnapshot` and each resulting `VirtualMachine`.

Comment (lyarwood) [reply pkg/storage/snapshot/restore.go]: The current series should address the original offline clone bug by copying the `ControllerRevisions`, associating them with the `VirtualMachineSnapshot` before copying them again during restore and associating them with the target `VirtualMachine`.

I still need to write tests and look into online snapshots as the `vmSnapshotSource` code is doing weird things with the `VirtualMachineInstanceSpec` there that might be incompatible with instancetypes.

Comment (lyarwood) [reply pkg/storage/snapshot/restore.go]: > I still need to write tests and look into online snapshots as the [`vmSnapshotSource` code is doing weird things with the `VirtualMachineInstanceSpec`](https://github.com/lyarwood/kubevirt/blob/04fa82725efc0e5de5cc9d977570ed0fd370a52f/pkg/storage/snapshot/source.go#L259-L280) there that might be incompatible with instancetypes.

I've pushed the following commit to prompt some discussion on this:

https://github.com/kubevirt/kubevirt/pull/8466/commits/35f82c3462fc62a7f9336cce5626f6d0afed11bd

This code originally came from https://github.com/kubevirt/kubevirt/pull/6642

/cc @ShellyKa13 

Apologies for dragging you into this PR, I'm trying to get my head around why we are fetching the `VirtualMachineInstance` here? Your PR suggested we wanted to include hot plugged disks in the snapshot but AFAICT you're overwriting the disks in the `VirtualMachineInstance` with the original disks from the `VirtualMachine`?

As I've set out in the commit above when instancetypes are used the `VirtualMachineInstanceSpec` in the `VirtualMachienInstance` isn't compatible with the `VirualMachine` anymore. If possible I'd like to stop copying it across while still persisting any hot plugged disks. Thoughts?

File: pkg/storage/snapshot/restore.go [hunk 6]
```diff
@@ -596,6 +606,125 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
 	return createdDV || waitingDV, nil
 }
 
+func isControllerRevisionOwnedByObject(cr *appsv1.ControllerRevision, objMeta metav1.ObjectMeta) bool {
+	for _, ownerRef := range cr.OwnerReferences {
```
Comment (lyarwood) [inline pkg/storage/snapshot/restore.go:610]: This should actually use [`metav1.GetControllerOf`](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#GetControllerOf)

File: pkg/storage/snapshot/restore.go [hunk 7]
```diff
@@ -596,6 +606,125 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		return nil, err
+	}
+
+	vmSnapshot, err := t.getVirtualMachineSnapshot(vm.Namespace, vmSnapshotName)
+	if err != nil {
+		return nil, err
+	}
+
+	// If the CR is owned by the VirtualMachineSnapshot restore it and attempt to claim it if the VirtualMachine exists
+	if isControllerRevisionOwnedByObject(existingCR, vmSnapshot.ObjectMeta) {
```
Comment (lyarwood) [inline pkg/storage/snapshot/restore.go:654]: https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#IsControlledBy

File: pkg/storage/snapshot/restore_test.go [hunk 8]
```diff
@@ -936,6 +950,235 @@ var _ = Describe("Restore controller", func() {
...
+				preferenceOriginalCR, err = instancetype.CreateControllerRevision(originalVM, preferenceObj)
+				Expect(err).ToNot(HaveOccurred())
+				crSource.Add(preferenceOriginalCR)
+
+				preferenceSnapshotCR = createInstancetypeVirtualMachineSnapshotCR(originalVM, vmSnapshot, preferenceObj)
+				crSource.Add(preferenceSnapshotCR)
+
+			})
+
+			It("should restore instancetype ControllerRevision into existing VirtualMachine", func() {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1037]: Can you make tables of the instancetype/preference tests? They look very similar.

File: pkg/storage/snapshot/snapshot_test.go [hunk 9]
```diff
@@ -1924,6 +1934,102 @@ var _ = Describe("Snapshot controlleer", func() {
...
+
+					// Expect the clone of the preference CR to be referenced from within VMSnapshotContent
+					expectedSnapshotContentVM := vm.DeepCopy()
+					expectedSnapshotContentVM.Spec.Preference.RevisionName = vmSnapshotName + strings.Replace(vm.Spec.Preference.RevisionName, vm.Name, "", 1)
+					expectedVMSnapshotContent := createVirtualMachineSnapshotContent(vmSnapshot, expectedSnapshotContentVM, nil)
+					expectVMSnapshotContentCreate(vmSnapshotClient, expectedVMSnapshotContent)
+
+					vmSource.Add(vm)
+					vmSnapshotSource.Add(vmSnapshot)
+					addVirtualMachineSnapshot(vmSnapshot)
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:2027]: No `syncCaches` needed here?

File: pkg/storage/snapshot/snapshot_test.go [hunk 10]
```diff
@@ -1924,6 +1934,102 @@ var _ = Describe("Snapshot controlleer", func() {
...
+					crSource.Add(instancetypeCR)
+
+					preferenceObj = createPreference()
+					preferenceCR, err = instancetype.CreateControllerRevision(vm, preferenceObj)
+					Expect(err).ToNot(HaveOccurred())
+					crSource.Add(preferenceCR)
+
+				})
+
+				It("should capture ControllerRevision clone of instancetype and reference it from VirtualMachineSnapshotContent", func() {
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:1984]: The tests look very similar, can you make them a table?

File: pkg/storage/snapshot/snapshot_test.go [hunk 11]
```diff
@@ -1970,6 +2076,7 @@ func expectVMSnapshotUpdate(client *kubevirtfake.Clientset, vmSnapshot *snapshot
 		Expect(ok).To(BeTrue())
 
 		updateObj := update.GetObject().(*snapshotv1.VirtualMachineSnapshot)
+
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:2079]: Empty line

File: pkg/storage/snapshot/source.go [hunk 12]
```diff
@@ -179,6 +184,69 @@ func (s *vmSnapshotSource) getVMRevision() (*snapshotv1.VirtualMachine, error) {
...
+func (s *vmSnapshotSource) getControllerRevision(namespace, name string) (*appsv1.ControllerRevision, error) {
+	crKey := cacheKeyFunc(namespace, name)
+	obj, exists, err := s.controller.CRInformer.GetStore().GetByKey(crKey)
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return nil, fmt.Errorf("Unable to fetch ControllerRevision %s", crKey)
+	}
+	return obj.(*appsv1.ControllerRevision), nil
```
Comment (0xFelix) [inline pkg/storage/snapshot/source.go:196]: Check for successful cast?

File: pkg/storage/snapshot/source.go [hunk 13]
```diff
@@ -179,6 +184,69 @@ func (s *vmSnapshotSource) getVMRevision() (*snapshotv1.VirtualMachine, error) {
...
+		return "", err
+	}
+	snapshot, ok := obj.(*snapshotv1.VirtualMachineSnapshot)
+	if !ok {
+		return "", fmt.Errorf("Unexpected object format returned from EnsureKubeVirtGroupVersionKind")
+	}
+	snapshotCR.OwnerReferences = []metav1.OwnerReference{*metav1.NewControllerRef(snapshot, snapshot.GroupVersionKind())}
+
+	snapshotCR, err = s.controller.Client.AppsV1().ControllerRevisions(s.snapshot.Namespace).Create(context.Background(), snapshotCR, metav1.CreateOptions{})
+	if err != nil && !errors.IsAlreadyExists(err) {
```
Comment (0xFelix) [inline pkg/storage/snapshot/source.go:223]: How can it happen that a CR already exists for this snapshot? Can the content of the CRs differ?

File: pkg/util/util.go [hunk 14]
```diff
@@ -258,3 +260,14 @@ func GenerateSecureRandomString(n int) (string, error) {
 
 	return string(ret), nil
 }
+
+func EnsureKubeVirtGroupVersionKind(obj runtime.Object) (runtime.Object, error) {
```
Comment (0xFelix) [inline pkg/util/util.go:264]: Can you add some reference why this is needed in the first place?

File: tests/storage/clone.go [hunk 15]
```diff
@@ -447,6 +451,133 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+						Spec: instancetypev1alpha2.VirtualMachinePreferenceSpec{
+							CPU: &instancetypev1alpha2.CPUPreferences{
+								PreferredCPUTopology: instancetypev1alpha2.PreferSockets,
+							},
+						},
+					}
+					preference, err := virtClient.VirtualMachinePreference(util.NamespaceTestDefault).Create(context.Background(), preference, metav1.CreateOptions{})
+					Expect(err).ToNot(HaveOccurred())
+
+					sourceVM = tests.NewRandomVMWithDataVolumeWithRegistryImport(
```
Comment (0xFelix) [inline tests/storage/clone.go:522]: Is it possible to use `libvmi` here?

**Review by 0xFelix — COMMENTED** [review]
Looks quite good, added some comments and some small nits.

File: pkg/instancetype/instancetype.go [hunk 16]
```diff
@@ -23,6 +23,8 @@ import (
 	"kubevirt.io/client-go/kubecli"
 	"kubevirt.io/client-go/log"
 
+	utils "kubevirt.io/kubevirt/pkg/util"
+
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/instancetype/instancetype.go:27]: ACK, done.

File: pkg/storage/snapshot/restore.go [hunk 17]
```diff
@@ -596,6 +606,115 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return nil, fmt.Errorf("Unable to find VirtualMachineSnapshot %s", vmSnapshotKey)
+	}
+	return obj.(*snapshotv1.VirtualMachineSnapshot), nil
+}
+
+func (t *vmRestoreTarget) restoreInstancetypeControllerRevision(revisionName, vmSnapshotName string, vm *kubevirtv1.VirtualMachine) (*appsv1.ControllerRevision, error) {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:633]: There are some assumptions made about the `ControllerRevisoin` within this func that means I'd rather not make it appear generic. Namely that the CR could be currently controlled by the `VirtualMachineSnapshot` and if so should be modified to be controlled by the `VirtualMachine`.

File: pkg/storage/snapshot/restore.go [hunk 18]
```diff
@@ -596,6 +606,115 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		cr.OwnerReferences = []metav1.OwnerReference{*metav1.NewControllerRef(vm, kubevirtv1.VirtualMachineGroupVersionKind)}
+		_, err = t.controller.Client.AppsV1().ControllerRevisions(vm.Namespace).Update(context.Background(), cr, v1.UpdateOptions{})
+		if err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
+func (t *vmRestoreTarget) claimInstancetypeControllerRevisionOwnership(vm *kubevirtv1.VirtualMachine) error {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:702]: ACK, I've also renamed `claimControllerRevisionOwnership` to `claimInstancetypeControllerRevisionOwnership` to be inline with the above func naming on the restore side.

File: pkg/storage/snapshot/restore_test.go [hunk 19]
```diff
@@ -936,6 +950,235 @@ var _ = Describe("Restore controller", func() {
...
+				newVM.UID = "newvm-uid"
+				restore.Spec.Target.Name = newVM.Name
+
+				expectedCreatedCR := instancetypeOriginalCR.DeepCopy()
+				expectedCreatedCR.Name = newVM.Name + strings.Replace(expectedCreatedCR.Name, originalVM.Name, "", 1)
+				expectedCreatedCR.OwnerReferences = nil
+				newVM.Spec.Instancetype.RevisionName = expectedCreatedCR.Name
+				expectControllerRevisionCreate(k8sClient, expectedCreatedCR)
+
+				// We need to be able to find the created CR from the controller so add it tothe source
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/restore_test.go:1091]: ACK thanks

File: pkg/storage/snapshot/source.go (hunk 13 above)
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:223]: When restoring to the original `VirtualMachine` it's actually likely to already exist, the contents shouldn't differ as the name includes the UID and generation of the resource contained within. That said we do have code within `pkg/instancetype` I could refactor and call here:

https://github.com/kubevirt/kubevirt/blob/73d78d58ca6b48c8d88ce3ec5a03e3e6355689bd/pkg/instancetype/instancetype.go#L278-L306

I'll add another commit putting this in place.

File: tests/storage/clone.go (hunk 15 above)
Comment (lyarwood) [reply tests/storage/clone.go:522]: This is actually using libvmi under the hood there's just a boat load of complexity here because of the use of `DataVolumes`:

https://github.com/kubevirt/kubevirt/blob/73d78d58ca6b48c8d88ce3ec5a03e3e6355689bd/tests/utils.go#L502-L521

File: pkg/util/util.go (hunk 14 above)
Comment (lyarwood) [reply pkg/util/util.go:264]: ACK done.

File: pkg/storage/snapshot/source.go (hunk 12 above)
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:196]: I can to be complete but I'm not sure that it's possible for this informer to return anything other than this type (for now at least).

File: pkg/storage/snapshot/restore_test.go (hunk 8 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore_test.go:1037]: ACK done.

File: pkg/storage/snapshot/snapshot_test.go (hunk 9 above)
Comment (lyarwood) [reply pkg/storage/snapshot/snapshot_test.go:2027]: This isn't actually required.

File: pkg/storage/snapshot/snapshot_test.go (hunk 10 above)
Comment (lyarwood) [reply pkg/storage/snapshot/snapshot_test.go:1984]: ACK done.

File: pkg/storage/snapshot/source.go (hunk 13 above)
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:223]: /cc @akrejcir 

I've pushed 451a2fbaff09093d989169f1e088a4ff7923bce1 to extract and refactor the original `ControllerRevision` comparison code in the instancetypes package. I've then wired this up in e8b279702e7beb4c7021154f9f8664442436f0bd but tbh this could be a follow up PR to close this gap. Thoughts appreciated, I've marked this PR as draft for now as the above commits need some additional test coverage but the existing tests are passing locally for me.

Comment (lyarwood) [reply pkg/storage/snapshot/source.go:223]: I've created PR #8674 to track this refactor and comparison during a restore as I'd like to land and backport this series to v0.58.0 as soon as possible. IMHO #8674 is just a useful follow up. Any objections to this @0xFelix ?

Comment (0xFelix) [reply pkg/storage/snapshot/source.go:223]: No objections, a follow-up PR for the comparison enhancement is fine for me.

File: pkg/storage/snapshot/source.go (hunk 12 above)
Comment (0xFelix) [reply pkg/storage/snapshot/source.go:196]: I think it's still worth checking for the cast to be successful. Ideally there would be a policy covering the whole project whether unchecked cast should be allowed or not.

File: pkg/storage/snapshot/restore_test.go [hunk 20]
```diff
@@ -936,6 +950,222 @@ var _ = Describe("Restore controller", func() {
 			addVirtualMachineRestore(r)
 			controller.processVMRestoreWorkItem()
 		})
+
+		Describe("restore vm with instancetypes and preferences", func() {
+
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:955]: Empty line?

File: pkg/storage/snapshot/snapshot_test.go [hunk 21]
```diff
@@ -1924,6 +1934,107 @@ var _ = Describe("Snapshot controlleer", func() {
 
 				Expect(updateCalled).To(BeTrue())
 			})
+			Describe("it should snapshot vm with instancetypes and preferences", func() {
+
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:1938]: Empty line?

File: pkg/storage/snapshot/snapshot_test.go (hunk 11 above)
Comment (0xFelix) [reply pkg/storage/snapshot/snapshot_test.go:2084]: Still empty line

**Review by 0xFelix — COMMENTED** [review]
Added some nits about empty lines and a comment about the unchecked cast.

**Comment by 0xFelix** [comment]
Looks good, thank you!

/lgtm

File: pkg/storage/snapshot/restore.go [hunk 22]
```diff
@@ -596,6 +606,115 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		restoredCR := existingCR.DeepCopy()
+		restoredCR.ObjectMeta.Reset()
+
+		// We remove the snapshot name prefix from the CR and add the name of the restored VM
+		restoredCR.Name = vm.Name + strings.Replace(existingCR.Name, vmSnapshotName, "", 1)
+
+		// Make the VirtualMachine the controller of the CR if it already exists, otherwise we will do this later once it has been created.
+		if t.doesTargetVMExist() {
+			restoredCR.OwnerReferences = []metav1.OwnerReference{*metav1.NewControllerRef(vm, kubevirtv1.VirtualMachineGroupVersionKind)}
+		}
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore.go:655]: This is confusing to me.
IIUC, if `t.doesTargetVMExist()` is true it means that we're restoring to the same VM, and that basically means that we're going to choose the original CR as this VM's CR. If that's indeed the case, this VM already owns the CR, which must exist already. Why not simply return if that's the case? Or am I missing anything?

I would expect the opposite to happen here - if `t.doesTargetVMExist()` is false, meaning we're performing a clone, we would have to create a new CR and make sure it's owned by this VM. I also don't really understand why we're waiting for `claimInstancetypeControllerRevisionsOwnership()` to do it (which also implicates adding an update action permission to the controller).

File: pkg/storage/snapshot/restore.go [hunk 23]
```diff
@@ -596,6 +606,115 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		return nil, err
+	}
+
+	vmSnapshot, err := t.getVirtualMachineSnapshot(vm.Namespace, vmSnapshotName)
+	if err != nil {
+		return nil, err
+	}
+
+	// If the CR is controlled by the VirtualMachineSnapshot restore it and attempt to claim it if the VirtualMachine exists
+	if metav1.IsControlledBy(existingCR, vmSnapshot) {
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore.go:645]: Isn't this always the case?
IIUC (in your first commit) the snapshot controller would clone the CR and unconditionally set it to be the source's CR.

File: pkg/storage/snapshot/restore.go [hunk 24]
```diff
@@ -596,6 +606,115 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		restoredCR := existingCR.DeepCopy()
+		restoredCR.ObjectMeta.Reset()
+
+		// We remove the snapshot name prefix from the CR and add the name of the restored VM
+		restoredCR.Name = vm.Name + strings.Replace(existingCR.Name, vmSnapshotName, "", 1)
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore.go:650]: So IIUC this makes a non-clone restore to point at the original CR (which obviously already exists), right?
So why not call `restoreInstancetypeControllerRevision()` only if it's a cloning restore (i.e. if the target doesn't exist)?

File: pkg/util/util.go [hunk 25]
```diff
@@ -258,3 +260,17 @@ func GenerateSecureRandomString(n int) (string, error) {
 
 	return string(ret), nil
 }
+
+// EnsureKubeVirtGroupVersionKind ensures a provided object registered with KubeVirts generated schema
+// has GVK set correctly. This is required as client-go continues to return objects without
+// TypeMeta set as set out in the following issue: https://github.com/kubernetes/client-go/issues/413
+func EnsureKubeVirtGroupVersionKind(obj runtime.Object) (runtime.Object, error) {
```
Comment (iholder-redhat) [inline pkg/util/util.go:267]: nit: I think that `Ensure` is a bit misleading. I think something like `Get..` or `Generate..` fits better here to emphasize that we're not performing assertions here, but rather generating a new object

**Review by iholder-redhat — COMMENTED** [review]
Awesome work @lyarwood! Left some questions / thoughts.

I'd just want to emphasize that we're now duplicating the CRs twice per clone, since the CR is both copied to the snapshot object and the new VM object. This is ok for now, but this might be an issue that would need to be addressed in follow-up PRs.

File: pkg/storage/snapshot/restore.go (hunk 23 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:645]: It should be yes but I wanted to be sure we were working on the current CR so this seemed like a valid check.

File: pkg/storage/snapshot/restore.go (hunk 24 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:650]: That's a valid assumption but I was worried about a corner case where a user has created a VirtualMachineSnapshot, modified the VirtualMachine to say point to a different instancetype CR, maybe deleted the original CR and then wants to restore to the original VirtualMachine. It's definitely a corner case but I think it's still valid to at least attempt to create the CR, if it exists great otherwise we should always get back to the state captured by the VirtualMachineSnapshot.

File: pkg/storage/snapshot/restore.go (hunk 22 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:655]: As above, just covering the corner case where we have to restore the CR for an existing VM whatever reason.

Also, we have to wait and claim ownership for a newly created VirtualMachine as you can't generate an OwnerReference for an object without a UID, we only get the UID after creation.

File: pkg/storage/snapshot/snapshot_test.go [hunk 26]
```diff
@@ -1924,6 +1932,106 @@ var _ = Describe("Snapshot controlleer", func() {
...
+						vm.Spec.Instancetype = getInstancetypeMatcher()
+						vm.Spec.Preference = getPreferenceMatcher()
+
+						// Expect the clone of the instancetype CR to be created and owned by the VMSnapshot
+						expectControllerRevisionCreate(k8sClient, getExpectedCR())
+
+						// Expect the clone of the CR to be referenced from within VMSnapshotContent
+						expectedSnapshotContentVM := vm.DeepCopy()
+						if expectedSnapshotContentVM.Spec.Instancetype != nil {
+							expectedSnapshotContentVM.Spec.Instancetype.RevisionName = vmSnapshotName + strings.Replace(vm.Spec.Instancetype.RevisionName, vm.Name, "", 1)
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/snapshot_test.go:1993]: ACK will do thanks.

File: pkg/storage/snapshot/source.go [hunk 27]
```diff
@@ -179,6 +184,71 @@ func (s *vmSnapshotSource) getVMRevision() (*snapshotv1.VirtualMachine, error) {
...
+		return nil, fmt.Errorf("Unable to fetch ControllerRevision %s", crKey)
+	}
+	cr, ok := obj.(*appsv1.ControllerRevision)
+	if !ok {
+		return nil, fmt.Errorf("Unexpected object format returned by informer")
+	}
+	return cr, nil
+}
+
+func (s *vmSnapshotSource) captureInstancetypeControllerRevision(namespace, name string) (string, error) {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:203]: ACK thanks.

File: pkg/storage/snapshot/source.go [hunk 28]
```diff
@@ -179,6 +184,71 @@ func (s *vmSnapshotSource) getVMRevision() (*snapshotv1.VirtualMachine, error) {
...
+	existingCR, err := s.getControllerRevision(namespace, name)
+	if err != nil {
+		return "", err
+	}
+
+	snapshotCR := existingCR.DeepCopy()
+	snapshotCR.ObjectMeta.Reset()
+
+	// We strip out the source VM name from the CR name and replace it with the snapshot name
+	snapshotCR.Name = s.snapshot.Name + strings.ReplaceAll(existingCR.Name, s.snapshot.Spec.Source.Name, "")
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:213]: Repeat clones would generate unqiue VirtualMachineSnapshot names right?

Do you mean using the VirtualMachineSnapshot itself as a source instead of a VirtualMachine?

File: pkg/storage/snapshot/source.go [hunk 29]
```diff
@@ -179,6 +184,71 @@ func (s *vmSnapshotSource) getVMRevision() (*snapshotv1.VirtualMachine, error) {
...
+	snapshotCR, err = s.controller.Client.AppsV1().ControllerRevisions(s.snapshot.Namespace).Create(context.Background(), snapshotCR, metav1.CreateOptions{})
+	if err != nil && !errors.IsAlreadyExists(err) {
+		return "", err
+	}
+
+	return snapshotCR.Name, nil
+}
+
+func (s *vmSnapshotSource) captureInstancetypeControllerRevisions(vm *snapshotv1.VirtualMachine) error {
+	if vm.Spec.Instancetype != nil && len(vm.Spec.Instancetype.RevisionName) > 0 {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:235]: Bad habits unfortunatly, happy to switch.

File: tests/storage/clone.go [hunk 30]
```diff
@@ -447,6 +451,133 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+
+					Expect(targetVM.Spec.Instancetype.RevisionName).ToNot(Equal(sourceVM.Spec.Instancetype.RevisionName))
+					Expect(targetVM.Spec.Preference.RevisionName).ToNot(Equal(sourceVM.Spec.Preference.RevisionName))
+
+					By("Asserting that the source and target ControllerRevisions contain the same Object")
+					sourceInstancetypeCR, err := virtClient.AppsV1().ControllerRevisions(sourceVM.Namespace).Get(context.Background(), sourceVM.Spec.Instancetype.RevisionName, v1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred())
+					targetInstancetypeCR, err := virtClient.AppsV1().ControllerRevisions(targetVM.Namespace).Get(context.Background(), targetVM.Spec.Instancetype.RevisionName, v1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred())
+					Expect(equality.Semantic.DeepEqual(sourceInstancetypeCR.Data.Object, targetInstancetypeCR.Data.Object)).To(BeTrue())
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply tests/storage/clone.go:572]: ACK will do.

File: tests/storage/clone.go [hunk 31]
```diff
@@ -447,6 +451,133 @@ var _ = SIGDescribe("[Serial]VirtualMachineClone Tests", func() {
...
+
+					sourcePreferenceCR, err := virtClient.AppsV1().ControllerRevisions(sourceVM.Namespace).Get(context.Background(), sourceVM.Spec.Preference.RevisionName, v1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred())
+					targetPreferenceCR, err := virtClient.AppsV1().ControllerRevisions(targetVM.Namespace).Get(context.Background(), targetVM.Spec.Preference.RevisionName, v1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred())
+					Expect(equality.Semantic.DeepEqual(sourcePreferenceCR.Data.Object, targetPreferenceCR.Data.Object)).To(BeTrue())
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply tests/storage/clone.go:578]: ACK.

File: tests/storage/restore.go [hunk 32]
```diff
@@ -543,6 +545,160 @@ var _ = SIGDescribe("VirtualMachineRestore Tests", func() {
...
+					if vm.Spec.Preference.RevisionName == "" {
+						return fmt.Errorf("preference revision name is expected to not be empty")
+					}
+					return nil
+				}
+			}
+
+			waitForVMInstanceTypeRevisionNames := func(vmName string) {
+				Eventually(checkForVMInstancetypeRevisionNames(util.NamespaceTestDefault, vmName), 300*time.Second, 1*time.Second).ShouldNot(HaveOccurred())
+			}
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply tests/storage/restore.go:576]: ACK apologies I forgot to remove these thanks!

**Comment by lyarwood** [comment]
> Awesome work @lyarwood! Left some questions / thoughts.
> 
> I'd just want to emphasize that we're now duplicating the CRs twice per clone, since the CR is both copied to the snapshot object and the new VM object. This is ok for now, but this might be an issue that would need to be addressed in follow-up PRs.

Many thanks Itamar and apologies I forgot to reply to this comment. It is true that we are duplicating the CRs during a clone but that's only because the clone workflow itself is a wrapper around snapshot and restore. If there was separate logic around this flow we could easily avoid this, without that I'm hesitant to hack in some behaviour only triggered for clones.

File: pkg/storage/snapshot/source.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (iholder-redhat) [reply pkg/storage/snapshot/source.go:213]: Let's say we have a VM, named `"vm1"`, and a snapshot, named `"snapshot1"`. Now let's say we have a CR named `"snapshot1-vm1-randomString"`. In this case `s.snapshot.Spec.Source.Name` (which would be replaced by an empty string) is `vm1`.

So if we snapshot this VM again (via a new `"snapshot2"` object), we would get: `snapshot2-snapshot1-randomString`. So we stripped the VM name, but now we're left only with snapshot names.

If we do that again: `snapshot3-snapshot2-snapshot1-randomString`, and so on.

Am I completely off here?

File: pkg/storage/snapshot/restore.go (hunk 23 above)
Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:645]: IMHO it should be clear from the code, as someone without context would have hard time figuring this out.

Is there a reason in your opinion we should return an error if `metav1.IsControlledBy(existingCR, vmSnapshot)` is false?
Either way, if not an error, I think a warning log entry is necessary here.

File: pkg/storage/snapshot/restore.go (hunk 24 above)
Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:650]: I don't think the scenario you mentioned is possible. Let's say we have a VM and a snapshot. The user can change the VM and replace the instancetype / preference, but he cannot delete the original CR, as the snapshot owns it. In order to delete the CR, the snapshot needs to also be deleted, which makes the restore impossible. IOW, whenever we restore there needs to be a snapshot which owns a CR, which means it necessarily exists.

My main problem with the code right now is that I feel I understand what's going on only because I have a lot of context, and that's also not easy :) I think we should try hard to simplify this as much as we can. WDYT?

Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:650]: BTW, what we can do just to completely be on the safe side, is validate (through an informer for example) that the CR truly exists when a non-clone restore occurs. This way we can capture errors in the future if something changes, but would still be able to maintain a code which is straight forward

File: pkg/storage/snapshot/restore.go (hunk 22 above)
Comment (iholder-redhat) [reply pkg/storage/snapshot/restore.go:655]: Let me correct myself, as the following statement is wrong:

> ... If that's indeed the case, this VM already owns the CR ...

This isn't true, as the VM could switch to another preference / instancetype.

> Also, we have to wait and claim ownership for a newly created VirtualMachine as you can't generate an OwnerReference for an object without a UID, we only get the UID after creation.

ACK, makes sense :+1:

File: pkg/storage/snapshot/source.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/storage/snapshot/source.go:213]: I think you're missing that when we restore we clone the CR again and rename it to be `vmName + randomString` where `randomString` is the instancetype/preference name, UID and generation. So `vm1-randomString` becomes `snapshot1-randomString` and is then restore to `newVM-randomString`. Additional snapshots of `vm1` would be `snapshot2-randomString` etc.

File: pkg/storage/snapshot/restore.go (hunk 23 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:645]: ACK as discussed I've dropped this check.

File: pkg/storage/snapshot/restore.go (hunk 24 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:650]: ACK again as discussed I've reworked this.

File: pkg/storage/snapshot/restore.go [hunk 33]
```diff
@@ -571,6 +577,10 @@ func (t *vmRestoreTarget) reconcileSpec() (bool, error) {
 	}
 	t.vm = newVM
 
+	if err = t.claimInstancetypeControllerRevisionsOwnership(t.vm); err != nil {
+		return false, err
+	}
+
```
Comment (davidvossel) [inline pkg/storage/snapshot/restore.go:583]: Is there any trick we can do here to set the ownership on the controller revisions at creation time instead of afterwards?

For example, what would happen if we created a VM with a controller revision that didn't exist yet, and then posted the CR afterwards? Would that confuse the VM into thinking it needed to create a new CR because it couldn't find the revision temporarily?

**Review by davidvossel — COMMENTED** [review]
/approve

File: pkg/storage/snapshot/restore.go [hunk 34]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+	if t.doesTargetVMExist() {
+		existingCR, err := t.getControllerRevision(vm.Namespace, restoredCRName)
+		if err != nil && !errors.IsNotFound(err) {
+			return nil, err
+		}
+		if existingCR != nil {
+			// TODO - Check the contents of the existing CR here against that of the snapshot CR
+			return existingCR, nil
+		}
+	}
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore.go:649]: What about the case where `errors.IsNotFound(err) == true`? Shouldn't we log a warning in that case since it's not expected?

File: pkg/storage/snapshot/restore.go [hunk 35]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+}
+
+func (t *vmRestoreTarget) claimInstancetypeControllerRevisionOwnership(revisionName string, vm *kubevirtv1.VirtualMachine) error {
+	cr, err := t.getControllerRevision(vm.Namespace, revisionName)
+	if err != nil {
+		return err
+	}
+
+	if !metav1.IsControlledBy(cr, vm) {
+		cr.OwnerReferences = []metav1.OwnerReference{*metav1.NewControllerRef(vm, kubevirtv1.VirtualMachineGroupVersionKind)}
```
Comment (iholder-redhat) [inline pkg/storage/snapshot/restore.go:695]: Shouldn't we instead append the VM to `cr.OwnerReferences`? What if the CR is also owned by a snapshot object?

**Review by iholder-redhat — COMMENTED** [review]
Thanks @lyarwood! Awesome job!
Huge +1 for the rework you made here

File: pkg/storage/snapshot/restore.go (hunk 34 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:649]: I don't think so, while it's unexpected it's entirely possible for a user to mutate the original `VirtualMachine` in such a way that the original CR is no longer used and could even be deleted by the user. I'd rather not tbh.

File: pkg/storage/snapshot/restore.go (hunk 35 above)
Comment (lyarwood) [reply pkg/storage/snapshot/restore.go:695]: That isn't a possibility here, the CR referenced by the restored VM we are looking at here can only be owned by the restored VM.

**Review by lyarwood — COMMENTED** [review]
Just back from sick leave, I'll get this rebased now, thanks all!

File: pkg/storage/snapshot/restore.go [hunk 36]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return nil, fmt.Errorf("Unable to find VirtualMachineSnapshot %s", vmSnapshotKey)
+	}
+	return obj.(*snapshotv1.VirtualMachineSnapshot), nil
+}
+
+func (t *vmRestoreTarget) restoreInstancetypeControllerRevision(VMSnapshotRevisionName, vmSnapshotName string, vm *kubevirtv1.VirtualMachine) (*appsv1.ControllerRevision, error) {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go:633]: `VMSnapshotRevisionName` with capital starting letter looks weird.

File: pkg/storage/snapshot/restore.go [hunk 37]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+	restoredCR, err = t.controller.Client.AppsV1().ControllerRevisions(vm.Namespace).Create(context.Background(), restoredCR, metav1.CreateOptions{})
+	if err != nil {
+		return nil, err
+	}
+
+	return restoredCR, nil
+}
+
+func (t *vmRestoreTarget) restoreInstancetypeControllerRevisions(vm *kubevirtv1.VirtualMachine) error {
+	if vm.Spec.Instancetype != nil && len(vm.Spec.Instancetype.RevisionName) > 0 {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go:669]: Keep this style over `vm.Spec.Instancetype.RevisionName != ""`?

File: pkg/storage/snapshot/restore.go [hunk 38]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		restoredCR, err := t.restoreInstancetypeControllerRevision(vm.Spec.Instancetype.RevisionName, t.vmRestore.Spec.VirtualMachineSnapshotName, vm)
+		if err != nil {
+			return err
+		}
+		vm.Spec.Instancetype.RevisionName = restoredCR.Name
+	}
+
+	if vm.Spec.Preference != nil && len(vm.Spec.Preference.RevisionName) > 0 {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go:677]: Keep this style over `vm.Spec.Preference.RevisionName != ""`?

File: pkg/storage/snapshot/restore.go [hunk 39]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		_, err = t.controller.Client.AppsV1().ControllerRevisions(vm.Namespace).Update(context.Background(), cr, v1.UpdateOptions{})
+		if err != nil {
+			return err
+		}
+	}
+	return nil
+}
+
+func (t *vmRestoreTarget) claimInstancetypeControllerRevisionsOwnership(vm *kubevirtv1.VirtualMachine) error {
+	if vm.Spec.Instancetype != nil && len(vm.Spec.Instancetype.RevisionName) > 0 {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go:705]: Keep this style over `vm.Spec.Instancetype.RevisionName != ""`?

File: pkg/storage/snapshot/restore.go [hunk 40]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+		if err := t.claimInstancetypeControllerRevisionOwnership(vm.Spec.Instancetype.RevisionName, vm); err != nil {
+			return err
+		}
+	}
+
+	if vm.Spec.Preference != nil && len(vm.Spec.Preference.RevisionName) > 0 {
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go:711]: Keep this style over `vm.Spec.Preference.RevisionName != ""`?

File: pkg/storage/snapshot/snapshot_test.go [hunk 41]
```diff
@@ -1924,6 +1934,106 @@ var _ = Describe("Snapshot controlleer", func() {
...
+					instancetypeObj = createInstancetype()
+					instancetypeCR, err = instancetype.CreateControllerRevision(vm, instancetypeObj)
+					Expect(err).ToNot(HaveOccurred())
+					crSource.Add(instancetypeCR)
+
+					preferenceObj = createPreference()
+					preferenceCR, err = instancetype.CreateControllerRevision(vm, preferenceObj)
+					Expect(err).ToNot(HaveOccurred())
+					crSource.Add(preferenceCR)
+
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:1979]: nit: newline

File: tests/clone_test.go [hunk 42]
```diff
@@ -591,6 +595,103 @@ var _ = Describe("[Serial][sig-compute]VirtualMachineClone Tests", func() {
 					Expect(err.Error()).To(ContainSubstring("not backed up in snapshot"))
 				})
 			})
+
+			Context("with instancetype and preferences", func() {
+
```
Comment (0xFelix) [inline tests/clone_test.go:600]: nit: newline

File: tests/clone_test.go [hunk 43]
```diff
@@ -591,6 +595,103 @@ var _ = Describe("[Serial][sig-compute]VirtualMachineClone Tests", func() {
...
+						Kind: "VirtualMachinePreference",
+					}
+
+					sourceVM, err = virtClient.VirtualMachine(sourceVM.Namespace).Create(sourceVM)
+					Expect(err).ToNot(HaveOccurred())
+
+					for _, dvt := range sourceVM.Spec.DataVolumeTemplates {
+						libstorage.EventuallyDVWith(sourceVM.Namespace, dvt.Name, 180, HaveSucceeded())
+					}
+
```
Comment (0xFelix) [inline tests/clone_test.go:668]: nit: newline

File: tests/libinstancetype/instancetype.go [hunk 44]
```diff
@@ -0,0 +1,64 @@
...
+
+		if vm.Spec.Preference.RevisionName == "" {
+			return fmt.Errorf("preference revision name is expected to not be empty")
+		}
+		return nil
+	}
+}
+
+func WaitForVMInstanceTypeRevisionNames(vmName string, virtClient kubecli.KubevirtClient) {
+	Eventually(CheckForVMInstancetypeRevisionNames(vmName, virtClient), 300*time.Second, 1*time.Second).ShouldNot(HaveOccurred())
```
Comment (0xFelix) [inline tests/libinstancetype/instancetype.go:55]: Maybe `ThisVM()` can be used here instead of getting the VM by hand?

File: tests/storage/restore.go [hunk 45]
```diff
@@ -543,6 +545,130 @@ var _ = SIGDescribe("VirtualMachineRestore Tests", func() {
 
 			})
 		})
+		Context("with instancetype and preferences", func() {
+
```
Comment (0xFelix) [inline tests/storage/restore.go:549]: nit: newline

**Review by 0xFelix — COMMENTED** [review]
Added some comments.

File: tests/libinstancetype/instancetype.go (hunk 44 above)
Comment (lyarwood) [reply tests/libinstancetype/instancetype.go:55]: Possibly but I'd rather replace both `WaitForVMInstanceTypeRevisionNames` and `CheckForVMInstancetypeRevisionNames` with a matcher in a follow up if that's okay?

File: pkg/storage/snapshot/restore_test.go [hunk 46]
```diff
@@ -936,6 +950,221 @@ var _ = Describe("Restore controller", func() {
...
+				crSource.Add(instancetypeSnapshotCR)
+
+				preferenceObj = createPreference()
+				preferenceOriginalCR, err = instancetype.CreateControllerRevision(originalVM, preferenceObj)
+				Expect(err).ToNot(HaveOccurred())
+				crSource.Add(preferenceOriginalCR)
+
+				preferenceSnapshotCR = createInstancetypeVirtualMachineSnapshotCR(originalVM, vmSnapshot, preferenceObj)
+				crSource.Add(preferenceSnapshotCR)
+
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1038]: nit: newline

File: pkg/storage/snapshot/snapshot_test.go [hunk 47]
```diff
@@ -1924,6 +1934,106 @@ var _ = Describe("Snapshot controlleer", func() {
 
 				Expect(updateCalled).To(BeTrue())
 			})
+			Describe("it should snapshot vm with instancetypes and preferences", func() {
+				var (
+					vm                           *v1.VirtualMachine
+					vmSnapshot                   *snapshotv1.VirtualMachineSnapshot
+					instancetypeObj              *instancetypev1alpha2.VirtualMachineInstancetype
+					preferenceObj                *instancetypev1alpha2.VirtualMachinePreference
+					instancetypeCR, preferenceCR *appsv1.ControllerRevision
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:1943]: Declare each on separate line?

File: pkg/storage/snapshot/snapshot_test.go [hunk 48]
```diff
@@ -2277,3 +2387,109 @@ func updateVMWithMemoryDump(vm *v1.VirtualMachine) *v1.VirtualMachine {
...
+		},
+	}
+}
+
+func createInstancetypeVirtualMachineSnapshotCR(vm *v1.VirtualMachine, vmSnapshot *snapshotv1.VirtualMachineSnapshot, obj runtime.Object) *appsv1.ControllerRevision {
+	cr, err := instancetype.CreateControllerRevision(vm, obj)
+	Expect(err).ToNot(HaveOccurred())
+
+	// Replace the VM name with the vmSnapshot name and clear the namespace as we don't expect to see this set during creation, only after.
+	cr.Name = vmSnapshot.Name + strings.ReplaceAll(cr.Name, vm.Name, "")
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go]: What about `cr.Name = strings.Replace(cr.name, vm.Name, vmSnapshot.Name, 1)`?

File: pkg/storage/snapshot/restore.go [hunk 49]
```diff
@@ -596,6 +606,117 @@ func (t *vmRestoreTarget) reconcileDataVolumes() (bool, error) {
...
+	}
+	if !exists {
+		return nil, fmt.Errorf("Unable to find VirtualMachineSnapshot %s", vmSnapshotKey)
+	}
+	return obj.(*snapshotv1.VirtualMachineSnapshot), nil
+}
+
+func (t *vmRestoreTarget) restoreInstancetypeControllerRevision(VMSnapshotRevisionName, vmSnapshotName string, vm *kubevirtv1.VirtualMachine) (*appsv1.ControllerRevision, error) {
+	// Switch the snapshot and vm names for the restored CR name
+	restoredCRName := vm.Name + strings.Replace(VMSnapshotRevisionName, vmSnapshotName, "", 1)
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore.go]: What about `restoredCRName := strings.Replace(VMSnapshotRevisionName, vmSnapshotName, vm.Name, 1)`?

File: pkg/storage/snapshot/snapshot_test.go [hunk 50]
```diff
@@ -2277,3 +2387,109 @@ func updateVMWithMemoryDump(vm *v1.VirtualMachine) *v1.VirtualMachine {
...
+
+	// TODO - share with pkg/instancetype somewhere
+	vmSnapshotCopy := vmSnapshot.DeepCopy()
+	gvks, _, err := generatedscheme.Scheme.ObjectKinds(vmSnapshotCopy)
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:2439]: Can `util.GenerateKubeVirtGroupVersionKind` be used?

File: pkg/storage/snapshot/snapshot_test.go (hunk 48 above)
Comment (0xFelix) [reply pkg/storage/snapshot/snapshot_test.go]: Also, the namespace is not cleared although the comment mentions it.

File: pkg/storage/snapshot/snapshot_test.go [hunk 51]
```diff
@@ -2277,3 +2387,109 @@ func updateVMWithMemoryDump(vm *v1.VirtualMachine) *v1.VirtualMachine {
...
+
+		updateObj := update.GetObject().(*appsv1.ControllerRevision)
+		Expect(*updateObj).To(Equal(*expectedCR))
+
+		return true, update.GetObject(), nil
+	})
+}
+
+func getControllerRevisionSnapshotName(snapName, crName, vmName string) string {
+	return snapName + strings.Replace(crName, vmName, "", 1)
```
Comment (0xFelix) [inline pkg/storage/snapshot/snapshot_test.go:2493]: -> `strings.Replace(crName, vmName, snapName, 1)`

File: pkg/storage/snapshot/source.go (hunk 28 above)
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/storage/snapshot/source.go]: -> `strings.Replace(existingCR.Name, s.snapshot.Spec.Source.Name, s.snapshot.Name, 1)`

File: tests/libinstancetype/instancetype.go [hunk 52]
```diff
@@ -0,0 +1,64 @@
...
+
+import (
+	"context"
+	"fmt"
+	"time"
+
+	. "github.com/onsi/gomega"
+
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+
```
Comment (0xFelix) [inline tests/libinstancetype/instancetype.go:30]: nit: newline

File: tests/libinstancetype/instancetype.go (hunk 44 above)
Comment (0xFelix) [reply tests/libinstancetype/instancetype.go:55]: Of course, a follow up makes sense.

**Review by iholder-redhat — APPROVED** [review]
