### PR TITLE
virt-controller: fix panic when VM udate fails

### LINKED ISSUE #10811: virt-controller: panic when the handling request vm operation failed
**What happened**:
virt-controller panic after run virtctl addvolume/removevolume.
errorlog like:
```
{component"; "vin controllen"ind."level":"error", "msg": " Reconciling the VirtualMachine failed," , "xxxx" "nanespace":"xxxx","pos": vm.go:344" "reason":"Error encountered when trying todate vm according to add volune and/or merory durp requests: Cperation cannot be fulfilled on virtualmachinesaubevirt.io \"xxxxx: the object has been modified; please apply your changes to the latest versionnd try again""timestarp":"2023-09-12103:01:20 3800192" "uid": xxxx 03:01:20 3803871 
runtime.go:78] 0bserved a panic: "invalid memory address or nil pointerce" (runtime error: invalid memoryaddress or nil pointer dereference)27) 
goroutine 1371 [runningl: kubevirt. io/kubevirt/Vendor/k8s .io/apimachinery/pkg/util/runtime logpanic(10x1bd6940?, 0x33136a0))vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 10x86ubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtimeHandleCrash((0x0, 0x0, 0x20?))vendor/k8s io/apimachinery/pkg/utiruntime/runtimego:48 +0x75anic((0x1bd6940，0x3313601)
GOR00T/src/runtime/panic.go:884 +0x212
kubevirt. io/kubevirt/pkg/virt-controller/natch.("WController).isVirtualMachinestatusDatavoluneError(0x10?,0xn27)68164ce00，0x1?)pkg/virt-controtler/watch/vm.go:2026 +0x50aubevirt,io/kubevirt/pkg/virt-controller/natch.(“WMController),setprintablestatus(0xc0003b4d80, 0xc001b4ce00,K0?)
pkg/virt-controller/watch/vm.go:1892 +0x4df0xc081bf4208，6x8，kubevirtio/kubevirt/oka/virt-controller/watch.( WController)updateSx22e0550，0xc001004e80okowvirt controller /watch/m.oo:1831 -x365

```

**What you expected to happen**:
operation correct.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
A failed update returns a nil for the VM. This
commit fixes a potential panic.

Fixes #10811

### Release note

```release-note
Bug-fix: Fix nil panic if VM update fails
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]

File: pkg/virt-controller/watch/vm.go [hunk 1]
```diff
@@ -3056,9 +3056,11 @@ func (c *VMController) sync(vm *virtv1.VirtualMachine, vmi *virtv1.VirtualMachin
 
 		if syncErr == nil {
 			if !equality.Semantic.DeepEqual(vm, vmCopy) {
-				vm, err = c.clientset.VirtualMachine(vmCopy.Namespace).Update(context.Background(), vmCopy)
+				updatedVm, err := c.clientset.VirtualMachine(vmCopy.Namespace).Update(context.Background(), vmCopy)
```
Comment (EdDev) [inline pkg/virt-controller/watch/vm.go:3059]: This whole `sync` method is a mess. The fact we need this complexity here is a sign of its problem.

It is very hard to even understand on what changes this`Update` works on. The only hint is the error message.

Nevertheless, the small fix seems correct.
You could embed it in the condition (`if`) but it is nit.

**Review by EdDev — APPROVED** [review]
