### PR TITLE
net, VMI UpdateStatus: Keep guest internal ifaceStatuses

### LINKED ISSUE #13115: flaky test: [sig-network] [Serial]Multus [rfe_id:1758][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachineInstance definition with qemu guest agent [test_id:1757] should report guest interfaces in VMI status
# What happened

Flaky test detected: `[sig-network] [Serial]Multus [rfe_id:1758][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachineInstance definition with qemu guest agent [test_id:1757] should report guest interfaces in VMI status` [1]

/kind flake
/priority critical-urgent

/sig network

[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-10-23.html#%5bsig-network%5d%20%5bSerial%5dMultus%20%5brfe_id%3a1758%5d%5bcrit%3amedium%5d%5bvendor%3acnv-qe%40redhat.com%5d%5blevel%3acomponent%5dVirtualMachineInstance%20definition%20with%20qemu%20guest%20agent%20%5btest_id%3a1757%5d%20should%20report%20guest%20interfaces%20in%20VMI%20status

## Additional context
The reduction of the parallelism has already landed a couple days ago, so this can be excluded as a possible reason for this flake.

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
virt-handler adds interface status entries for guest-internal interfaces, discovered by QEMU guest agent.
They have an empty name and their infoSource is `guest-agent`.

Prior to PR https://github.com/kubevirt/kubevirt/pull/13018, the UpdateStatus function (called by VMI controller) used to work directly on the `vmi.Status.Interfaces` slice.
Thus, it implicitly kept the guest-internal interface statuses.

PR https://github.com/kubevirt/kubevirt/pull/13018 changed the interface statuses calculation to be explicit, and unintentionally dropped the guest-internal interface statuses -
which caused the e2e tests to flake.

Currently, the logic adds / updates interface status entries for all interfaces existing in the VMI spec.

Explicitly preserve interface status entries that do not exist in the VMI spec without modifying them.

Fixes #13115.

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

File: pkg/network/vmispec/interface.go [hunk 1]
```diff
@@ -188,3 +188,19 @@ func HasBindingPluginDeviceInfo(iface v1.Interface, bindingPlugins map[string]v1
 	}
 	return false
 }
+
+// FilterInterfaceStatuses returns a filtered slice of interface statues by some criteria
+// f must not be nil
+func FilterInterfaceStatuses(
```
Comment (nirdothan) [inline pkg/network/vmispec/interface.go:194]: since this function is "half" generic,  why don't we write it completely generic?  so that it wold take a `[]T` and a ` func(item T) bool` returning the filtered `[]T` 
Or do we not use generics in this project?

File: pkg/network/vmicontroller/status.go [hunk 2]
```diff
@@ -51,6 +51,16 @@ func UpdateStatus(clusterConfig clusterConfigChecker, vmi *v1.VirtualMachineInst
 
 	interfaceStatuses = append(interfaceStatuses, secondaryIfaceStatuses...)
 
+	// virt-handler adds status for interfaces only existing inside the guest that were discovered by QEMU GuestAgent
+	guestInternalIfaceStatuses := vmispec.FilterInterfaceStatuses(
+		vmi.Status.Interfaces,
+		func(ifaceStatus v1.VirtualMachineInstanceNetworkInterface) bool {
+			return ifaceStatus.Name == "" && ifaceStatus.InfoSource == vmispec.InfoSourceGuestAgent
```
Comment (nirdothan) [inline pkg/network/vmicontroller/status.go:58]: just curious, why should the name be empty?

**Review by nirdothan — APPROVED** [review]
nice

File: pkg/network/vmicontroller/status.go (hunk 2 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go:58]: virt-handler implicitly sets the name of guest-internal interface statuses to an empty string:
https://github.com/kubevirt/kubevirt/blob/7fade41f9138d787476b2e429c86222a2fc951cd/pkg/network/setup/netstat.go#L293-L295

File: pkg/network/vmispec/interface.go (hunk 1 above)
Comment (orelmisan) [reply pkg/network/vmispec/interface.go:194]: > since this function is "half" generic, why don't we write it completely generic? so that it wold take a []T and a  func(item T) bool returning the filtered []T

That is an Interesting idea that might be worth exploring in a follow up - as it would probably generate a vibrant discussion (and we need to fix this flake ASAP).

> Or do we not use generics in this project?

There is at least one place in the code-base that uses generics:
 
https://github.com/kubevirt/kubevirt/blob/7b7a6fd86dbe57bbadcb09d25bdbf3be1d3291cf/pkg/pointer/pointer.go#L22-L24

File: pkg/network/vmicontroller/status.go [hunk 3]
```diff
@@ -51,6 +51,16 @@ func UpdateStatus(clusterConfig clusterConfigChecker, vmi *v1.VirtualMachineInst
 
 	interfaceStatuses = append(interfaceStatuses, secondaryIfaceStatuses...)
 
+	// virt-handler adds status for interfaces only existing inside the guest that were discovered by QEMU GuestAgent
+	guestInternalIfaceStatuses := vmispec.FilterInterfaceStatuses(
```
Comment (Acedus) [inline pkg/network/vmicontroller/status.go:55]: Might be misunderstanding, but do we need to account for the case where the `InfoSource` is `InfoSourceDomainAndGA` in the case of older virt-launchers?

**Review by Acedus — APPROVED** [review]
Thank you.

File: pkg/network/vmicontroller/status.go (hunk 3 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go:55]: Changed the filter condition to account for this scenario.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/76877c6c0a014aebfdf5b154a902c8c7b2a1778e..3232ee01456f69955e75ac299a76c8082c78989e): Addressed @Acedus's [comment](https://github.com/kubevirt/kubevirt/pull/13146#discussion_r1823970093).

File: pkg/network/vmicontroller/status.go [hunk 4]
```diff
@@ -51,6 +51,16 @@ func UpdateStatus(clusterConfig clusterConfigChecker, vmi *v1.VirtualMachineInst
...
+		vmi.Status.Interfaces,
+		func(ifaceStatus v1.VirtualMachineInstanceNetworkInterface) bool {
+			return ifaceStatus.Name == "" && vmispec.ContainsInfoSource(ifaceStatus.InfoSource, vmispec.InfoSourceGuestAgent)
```
Comment (Acedus) [inline pkg/network/vmicontroller/status.go:58]: Is the `ifaceStatus.Name` empty when the `InfoSource` is `InfoSourceDomainAndGA`? I'm pretty sure we hit this case when the domain status iface name is populated.

Comment (Acedus) [reply pkg/network/vmicontroller/status.go:58]: Also perhaps we should consider adding a test for this case specifically.

File: pkg/network/vmispec/interface.go (hunk 1 above)
Comment (nirdothan) [reply pkg/network/vmispec/interface.go:194]: See this [function]( https://github.com/samber/lo?tab=readme-ov-file#filter) (  [source code](https://github.com/samber/lo/blob/407b62d3f12eece919463f556c798661f5aabbbf/slice.go#L12)).
I don't think that it's worth adding this lib to project dependencies just for this, though HCO [did it](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/go.mod#L29) for even less

File: pkg/network/vmicontroller/status.go (hunk 4 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go:58]: https://github.com/kubevirt/kubevirt/blob/4e49259b9036478b2232c5ad3bab34a6103dc165/staging/src/kubevirt.io/api/core/v1/types.go#L695-L696

Since the interface is internal to the guest (does not exist in the VMI spec), per my understanding its ifaceStatus.Name should be empty.

Comment (Acedus) [reply pkg/network/vmicontroller/status.go:58]: Fair enough.

**Review by Acedus — APPROVED** [review]

File: pkg/network/vmispec/interface.go (hunk 1 above)
Comment (ormergi) [reply pkg/network/vmispec/interface.go:194]: Please consider following example of `FilterInterfacesSpec` nameing in that file for better consistency, and rename the function to `FilterInterfacesStatus`.

In general I agree we can make use of generics for filtering in various places, I think it should be done on different PR.

File: pkg/network/vmicontroller/status.go [hunk 5]
```diff
@@ -51,6 +51,16 @@ func UpdateStatus(clusterConfig clusterConfigChecker, vmi *v1.VirtualMachineInst
...
+		},
+	)
```
Comment (ormergi) [inline pkg/network/vmicontroller/status.go:60]: Please consider export this to function as other examples in this context (calc. secondary/primary ifaces..) 
I could make the code less bulky and easier to follow, having descriptive name can eliminate the need for commenting what the code does.

**Review by ormergi — COMMENTED** [review]
Thanks for the PR, please see my comments

File: pkg/network/vmispec/interface.go (hunk 1 above)
Comment (orelmisan) [reply pkg/network/vmispec/interface.go]: @ormergi Done.

File: pkg/network/vmicontroller/status.go (hunk 5 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go]: Done.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/3232ee01456f69955e75ac299a76c8082c78989e..c2552c3319e4e1cae09cc3cc51490ba138328f2f): Addressed @ormergi's [comments](https://github.com/kubevirt/kubevirt/pull/13146#pullrequestreview-2407565634).

File: pkg/network/vmicontroller/status.go [hunk 6]
```diff
@@ -124,3 +128,11 @@ func calculateSecondaryIfaceStatuses(
 
 	return interfaceStatuses, nil
 }
+
+func filterGuestInternalInterfaces(ifaceStatuses []v1.VirtualMachineInstanceNetworkInterface) []v1.VirtualMachineInstanceNetworkInterface {
```
Comment (ormergi) [inline pkg/network/vmicontroller/status.go:132]: nit: "internal" my imply some subsystem thing, I dont have better suggestion though..
I wonder how we should call interfaces exist in guest but not in spec.

**Review by ormergi — APPROVED** [review]
Thanks for the changes, LGTM

File: pkg/network/vmicontroller/status.go (hunk 6 above)
Comment (Acedus) [reply pkg/network/vmicontroller/status.go:132]: Doesn't the term `guest` already suggest an interface that is internal to the guest with its information exposed through the qemu-ga?

> //   - domain.Status.Interfaces: interfaces reported by the guest agent (empty if Qemu agent not running).

I think the `Internal` suffix may be redundant.

**Comment by orelmisan** [comment]
The [failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13146/pull-kubevirt-unit-test/1851938702863896576) is unrelated.
/test pull-kubevirt-unit-test

File: pkg/network/vmicontroller/status.go (hunk 6 above)
Comment (EdDev) [reply pkg/network/vmicontroller/status.go:132]: Continuing the feedback here, I think all will get solved by dropping this wrapper.
If you keep it, then I would express that the function filters interfaces that have been detected from "other" sources. But it is hard to name this.

File: pkg/network/vmicontroller/status.go [hunk 7]
```diff
@@ -124,3 +128,11 @@ func calculateSecondaryIfaceStatuses(
...
+	return vmispec.FilterInterfacesStatus(
+		ifaceStatuses,
+		func(ifaceStatus v1.VirtualMachineInstanceNetworkInterface) bool {
+			return ifaceStatus.Name == "" && vmispec.ContainsInfoSource(ifaceStatus.InfoSource, vmispec.InfoSourceGuestAgent)
```
Comment (EdDev) [inline pkg/network/vmicontroller/status.go:136]: I find this hard to understand.

I understand that in theses cases, we should preserve the entries:
- The infoSource has only `InfoSourceGuestAgent`.
- The infoSource has only `InfoSourceDomain`.
- The infoSource has only `InfoSourceGuestAgent` and `InfoSourceGuestAgent`.

The above should also imply that it is already in the already-calculated interfaces.
I would prefer to see it is indeed the case by expressing it in the unit-tests. It may be a bit tricky.
(I mean, how we are sure it cannot happen)

I am unsure about the `Name` relevance, it seems like a dependency on some side-effect. If that is the case, I consider the logic fragile.

File: pkg/network/vmispec/interface.go [hunk 8]
```diff
@@ -188,3 +188,19 @@ func HasBindingPluginDeviceInfo(iface v1.Interface, bindingPlugins map[string]v1
 	}
 	return false
 }
+
+// FilterInterfacesStatus returns a filtered slice of interface statues by some criteria
+// f must not be nil
+func FilterInterfacesStatus(
+	ifaceStatuses []v1.VirtualMachineInstanceNetworkInterface,
+	f func(ifaceStatus v1.VirtualMachineInstanceNetworkInterface) bool) []v1.VirtualMachineInstanceNetworkInterface {
```
Comment (EdDev) [inline pkg/network/vmispec/interface.go:196]: I would call it `predicate` like the other filter we have.
But this is not a must.

File: pkg/network/vmicontroller/status.go [hunk 9]
```diff
@@ -51,6 +51,10 @@ func UpdateStatus(clusterConfig clusterConfigChecker, vmi *v1.VirtualMachineInst
 
 	interfaceStatuses = append(interfaceStatuses, secondaryIfaceStatuses...)
 
+	// virt-handler adds status entries for interfaces that only exist inside the guest.
+	// These interfaces were discovered by QEMU GuestAgent
```
Comment (EdDev) [inline pkg/network/vmicontroller/status.go:55]: I would prefer this description to be more generic at this place. E.g. preserve already-discovered interfaces from the virt-handler. That should also hint about the name for such a function helper name.

**Review by EdDev — CHANGES_REQUESTED** [review]

File: pkg/network/vmicontroller/status.go (hunk 9 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go]: Done.

File: pkg/network/vmispec/interface.go (hunk 8 above)
Comment (orelmisan) [reply pkg/network/vmispec/interface.go]: This code was removed.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/c2552c3319e4e1cae09cc3cc51490ba138328f2f..4bf40a93549666f5c593db847415b0ed57a325c3): Addressed @EdDev's comments.
Preserve interface status entries that do not are not present in the VMI spec.

File: pkg/network/vmicontroller/status.go [hunk 10]
```diff
@@ -124,3 +127,20 @@ func calculateSecondaryIfaceStatuses(
 
 	return interfaceStatuses, nil
 }
+
+func filterUnspecifiedIfaces(
```
Comment (EdDev) [inline pkg/network/vmicontroller/status.go:131]: nit: It is unclear to what "unspecified" refers to. Maybe `filterUnspecifiedSpecIfaces`.

**Review by EdDev — COMMENTED** [review]
Very elegant, thanks!

/approve

File: pkg/network/vmicontroller/status.go (hunk 10 above)
Comment (orelmisan) [reply pkg/network/vmicontroller/status.go]: Done.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/4bf40a93549666f5c593db847415b0ed57a325c3..65f0d7141be6ec7b0e7c8c8db24b4416184efcd8): Addressed @EdDev's [comment](https://github.com/kubevirt/kubevirt/pull/13146#discussion_r1826946303).
