### PR TITLE
workload-updater: avoid cancelling the migration when the migration has finished

### LINKED ISSUE #12297: Abort of workload updates is missbehaiving.
**What happened**:
Running hotplug tests, a wild error appears
```
[FAILED] Timed out after 240.000s.
  migration should succeed after 240 s
  Unexpected error:
      <*errors.StatusError | 0xc0009006e0>: 
      virtualmachineinstancemigrations.kubevirt.io "kubevirt-workload-update-nzvbs" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "virtualmachineinstancemigrations.kubevirt.io \"kubevirt-workload-update-nzvbs\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "kubevirt-workload-update-nzvbs",
                  Group: "kubevirt.io",
                  Kind: "virtualmachineinstancemigrations",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  occurred
  In [It] at: tests/libmigration/migration.go:63 @ 07/08/24 10:50:30.315

  Full Stack Trace
    kubevirt.io/kubevirt/tests/libmigration.ExpectMigrationToSucceedWithDefaultTimeout(...)
    	tests/libmigration/migration.go:63
    kubevirt.io/kubevirt/tests/hotplug.init.func4.2.7()
    	tests/hotplug/memory.go:346 +0xb3e
```

Upon closer look it appears https://github.com/xpivarc/kubevirt/commit/be31f56df104aa999f3dbff95ec4dd13328fc472 is not handling all cases correctly because A) Migration can be finished B) Hotplug might be done

**What you expected to happen**:
Keep a successful migration around.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by alicefr**
Make sure that the migration has completed by checking if the target domain is ready. In certain cases, the migration can be  still in running phase but the migration process has already completed and the object hasn't been updated yet. In order to prevent the race condition of deleting the migration object, we check if the target is ready.

Fixes #12297

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by alicefr** [comment]
@xpivarc it seems no flakes for the memory hotplug test suite

**Comment by alicefr** [comment]
/unhold
Removed the last commit since the CI was green

File: pkg/virt-controller/watch/workload-updater/workload-updater.go [hunk 1]
```diff
@@ -352,6 +352,9 @@ func (c *WorkloadUpdateController) shouldAbortMigration(vmi *virtv1.VirtualMachi
 	if isVolumesUpdateInProgress(vmi) {
 		return false
 	}
+	if vmi.Status.MigrationState != nil && vmi.Status.MigrationState.TargetNodeDomainReadyTimestamp != nil {
```
Comment (xpivarc) [inline pkg/virt-controller/watch/workload-updater/workload-updater.go:355]: The only thing I wonder is when do we clear this and if that can affect this logic. Can we have a look at this?

File: pkg/virt-controller/watch/workload-updater/workload-updater_test.go [hunk 2]
```diff
@@ -550,6 +552,29 @@ var _ = Describe("Workload Updater", func() {
 			controller.Execute()
 			testutils.ExpectEvent(recorder, FailedChangeAbortionReason)
 		})
+
+		It("shouldn't cancel the migration if the migration object is still in running phase but the domain is ready on the target", func() {
```
Comment (xpivarc) [inline pkg/virt-controller/watch/workload-updater/workload-updater_test.go:556]: This doesn't seem to reproduce the problem.

File: pkg/virt-controller/watch/workload-updater/workload-updater_test.go [hunk 3]
```diff
@@ -550,6 +552,29 @@ var _ = Describe("Workload Updater", func() {
...
+				Type:   v1.VirtualMachineInstanceMemoryChange,
+				Status: k8sv1.ConditionTrue,
+			})
+			vmi.Status.MigrationState = &v1.VirtualMachineInstanceMigrationState{
+				StartTimestamp:                 pointer.P(metav1.Now()),
+				Completed:                      false,
+				Failed:                         false,
+				TargetNodeDomainReadyTimestamp: pointer.P(metav1.Now()),
+			}
+			vmiSource.Add(vmi)
```
Comment (xpivarc) [inline pkg/virt-controller/watch/workload-updater/workload-updater_test.go:572]: This is async operation, we need to sync the state otherwise this is flaky.

File: pkg/virt-controller/watch/workload-updater/workload-updater_test.go (hunk 2 above)
Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:556]: Isn't the flakes happening when the state of the migration isn't finalized by the actual migration has already finished?

Comment (xpivarc) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:556]: @alicefr I tried to run this test alone without the fix and this did not fail for me. What I am trying to say is that I expect it to fail.

Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go]: You were right, the unit test was wrong, I add the change condition while the VMI shouldn't have it anymoe

File: pkg/virt-controller/watch/workload-updater/workload-updater_test.go (hunk 3 above)
Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go]: This has been replaced by the store in the controller, does it still require a sync?

File: pkg/virt-controller/watch/workload-updater/workload-updater_test.go [hunk 4]
```diff
@@ -519,6 +521,25 @@ var _ = Describe("Workload Updater", func() {
...
+			vmi.Status.MigrationState = &v1.VirtualMachineInstanceMigrationState{
+				StartTimestamp:                 pointer.P(metav1.Now()),
+				Completed:                      false,
+				Failed:                         false,
+				TargetNodeDomainReadyTimestamp: pointer.P(metav1.Now()),
+			}
+			controller.vmiStore.Add(vmi)
+			createMig(vmi.Name, v1.MigrationRunning)
+			controller.Execute()
+			Expect(recorder.Events).To(BeEmpty())
```
Comment (xpivarc) [inline pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: Can we leave a comment or explicitly use mock to express we do not expect `Delete` call?

Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: I can add a comment, if there is a call to Delete then the test will panic. Otherwise, I don't how to use mock to state that there wasn't that call. Any idea?

Comment (xpivarc) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: You use `.Times(0)`

Comment (xpivarc) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: And the reason why I ask for this is for us to not forget about this when we convert the tests to use fake client

Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: > You use `.Times(0)`

Aaah, nice trick

Comment (alicefr) [reply pkg/virt-controller/watch/workload-updater/workload-updater_test.go:540]: Let me add with a comment as well

**Review by xpivarc — COMMENTED** [review]
/approve

**Review by fossedihelm — APPROVED** [review]
Looks good! Thank you @alicefr!
So sad for incoming conflicts in my PR https://github.com/kubevirt/kubevirt/pull/12241
:)
