### PR TITLE
virt-operator: Use informer stores for instance types and preferences

### LINKED ISSUE #12382: virt-operator taking a considerable amount of time to reconcile common-instancetypes post deployment
/area instancetype

**What happened**:
```
$ ./cluster-up/kubectl.sh patch kv/kubevirt -n kubevirt --type merge -p '{"spec":{"configuration":{"developerConfiguration":{"featureGates": ["CommonInstancetypesDeploymentGate"]}}}}'
[..]
$ git diff HEAD~1
diff --git a/pkg/virt-operator/resource/apply/reconcile.go b/pkg/virt-operator/resource/apply/reconcile.go
index 37dc8639ed..898ddeb026 100644
--- a/pkg/virt-operator/resource/apply/reconcile.go
+++ b/pkg/virt-operator/resource/apply/reconcile.go
@@ -717,12 +717,14 @@ func (r *Reconciler) Sync(queue workqueue.RateLimitingInterface) (bool, error) {
        }
 
        if r.commonInstancetypesDeploymentEnabled() {
+               deploymentStart := time.Now()
                if err := r.createOrUpdateInstancetypes(); err != nil {
                        return false, err
                }
                if err := r.createOrUpdatePreferences(); err != nil {
                        return false, err
                }
+               log.Log.Infof("common-instancetypes reconcile took %s", time.Since(deploymentStart))
        } else {
                if err := r.deleteInstancetypes(); err != nil {
                        return false, err
```
```json
{"component":"virt-operator","level":"info","msg":"common-instancetypes reconcile took 26.798231021s","pos":"reconcile.go:727","timestamp":"2024-07-17T14:39:38.655132Z"}                                                                                                                                                              
{"component":"virt-operator","level":"info","msg":"common-instancetypes reconcile took 14.193423225s","pos":"reconcile.go:727","timestamp":"2024-07-17T14:39:53.253314Z"}                                                                                                                                                             
{"component":"virt-operator","level":"info","msg":"common-instancetypes reconcile took 14.194449755s","pos":"reconcile.go:727","timestamp":"2024-07-17T14:40:07.853836Z"}                                                                                                                                                             
{"component":"virt-operator","level":"info","msg":"common-instancetypes reconcile took 14.191635599s","pos":"reconcile.go:727","timestamp":"2024-07-17T14:40:22.453306Z"} 
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/cc @0xFelix 
/cc @xpivarc 

### What this PR does

As set out in #12382 virt-operator was taking a considerable amount of time to reconcile common-instancetypes when deployment was enabled. This change provides informer stores to the `Reconciler` and uses them during both deployment and removal reconciliation to improve this drastically:

```
$ ./cluster-up/kubectl.sh patch kv/kubevirt --type merge -n kubevirt -p '{"spec":{"configuration":{"developerConfi
guration":{"logVerbosity":{"virtOperator": 6}, "featureGates": []}}}}'
$ ./cluster-up/kubectl.sh logs -n kubevirt pods/virt-operator-5d445769bf-ws2w8 -f | grep common-instancetypes
{"component":"virt-operator","level":"info","msg":"common-instancetypes removal reconcile took 3.036µs","pos":"reconcile.go:736","timestamp":"2024-07-18T13:13:32.963926Z"}
{"component":"virt-operator","level":"info","msg":"common-instancetypes removal reconcile took 3.537µs","pos":"reconcile.go:736","timestamp":"2024-07-18T13:13:34.989852Z"}
```
```
$ ./cluster-up/kubectl.sh patch kv/kubevirt -n kubevirt --type merge -p '{"spec":{"configuration":{"developerConfiguration":{"logVerbosity":{"virtOperator": 6}, "featureGates": ["CommonInstancetypesDeploymentGate"]}}}}'
$ ./cluster-up/kubectl.sh logs -n kubevirt pods/virt-operator-5d445769bf-ws2w8 -f | grep common-instancetypes
{"component":"virt-operator","level":"info","msg":"common-instancetypes deployment reconcile took 12.602676484s","pos":"reconcile.go:727","timestamp":"2024-07-18T13:15:11.457165Z"}
{"component":"virt-operator","level":"info","msg":"common-instancetypes deployment reconcile took 7.054016ms","pos":"reconcile.go:727","timestamp":"2024-07-18T13:15:11.870037Z"}
{"component":"virt-operator","level":"info","msg":"common-instancetypes deployment reconcile took 1.272848ms","pos":"reconcile.go:727","timestamp":"2024-07-18T13:15:16.514382Z"}
```

```
$ ./cluster-up/kubectl.sh patch kv/kubevirt -n kubevirt --type=json -p="[{'op': 'remove', 'path': '/spec/configura
tion/developerConfiguration/featureGates'}]"
$ ./cluster-up/kubectl.sh logs -n kubevirt pods/virt-operator-5d445769bf-ws2w8 -f | grep common-instancetypes
{"component":"virt-operator","level":"info","msg":"common-instancetypes removal reconcile took 134.222116ms","pos":"reconcile.go:736","timestamp":"2024-07-18T13:17:57.102284Z"}
{"component":"virt-operator","level":"info","msg":"common-instancetypes removal reconcile took 3.367µs","pos":"reconcile.go:736","timestamp":"2024-07-18T13:17:59.980601Z"}
```

Fixes #12382

### Why we need it and why it was done in this way
The following tradeoffs were made:

Both the instance type and preference informers are started ahead of the CRDs being available in the cluster. While this does generate some limited noise in the tests we will always have the CRDs present in the cluster by the time we need to reconcile common-instancetypes.

The following alternatives were considered:

I did look at delaying the start of the informers but this requires passing the informerFactory through a few layers into the `Reconciler` and doesn't really add any value IMHO.

Links to places where the discussion took place: 

### Special notes for your reviewer

This is very much WIP, I'll remove the fallback client code now that the store is always there. In previous local iterations of this series it wasn't thus the fallback was needed. 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 1]
```diff
@@ -57,31 +68,30 @@ var _ = Describe("Apply Instancetypes", func() {
...
-			getCalled := expectGetReturnNotFound(fakeClient, apiinstancetype.ClusterPluralResourceName)
 			createCalled := expectCreate(fakeClient, apiinstancetype.ClusterPluralResourceName, instancetype)
 			Expect(reconciler.createOrUpdateInstancetype(instancetype)).To(Succeed())
-			Expect(*getCalled).To(BeTrue())
 			Expect(*createCalled).To(BeTrue())
 		})
 
 		It("should not update instancetypes on sync when they are equal", func() {
-			getCalled := expectGet(fakeClient, apiinstancetype.ClusterPluralResourceName, instancetype)
+			reconciler.stores.ClusterInstancetype.Add(instancetype)
```
Comment (0xFelix) [inline pkg/virt-operator/resource/apply/instancetype_test.go:85]: Can we assert create/update was not called?

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 2]
```diff
@@ -95,11 +105,16 @@ var _ = Describe("Apply Instancetypes", func() {
...
-		It("should delete all instancetypes managed by virt-operator", func() {
+		It("should delete all deployed instance types managed by virt-operator", func() {
+			reconciler.stores.ClusterInstancetype.Add(instancetype)
 			deleteCollectionCalled := expectDeleteCollection(fakeClient, reconciler.kv, apiinstancetype.ClusterPluralResourceName)
 			Expect(reconciler.deleteInstancetypes()).To(Succeed())
 			Expect(*deleteCollectionCalled).To(BeTrue())
 		})
+
+		It("should not call delete if no instance types have been deployed by virt-operator", func() {
+			Expect(reconciler.deleteInstancetypes()).To(Succeed())
```
Comment (0xFelix) [inline pkg/virt-operator/resource/apply/instancetype_test.go:116]: How does this assert delete was not called?

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 3]
```diff
@@ -121,31 +136,30 @@ var _ = Describe("Apply Instancetypes", func() {
...
-			getCalled := expectGetReturnNotFound(fakeClient, apiinstancetype.ClusterPluralPreferenceResourceName)
 			createCalled := expectCreate(fakeClient, apiinstancetype.ClusterPluralPreferenceResourceName, preference)
 			Expect(reconciler.createOrUpdatePreference(preference)).To(Succeed())
-			Expect(*getCalled).To(BeTrue())
 			Expect(*createCalled).To(BeTrue())
 		})
 
 		It("should not update preferences on sync when they are equal", func() {
-			getCalled := expectGet(fakeClient, apiinstancetype.ClusterPluralPreferenceResourceName, preference)
+			reconciler.stores.ClusterPreference.Add(preference)
```
Comment (0xFelix) [inline pkg/virt-operator/resource/apply/instancetype_test.go:153]: Same

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 4]
```diff
@@ -155,41 +169,23 @@ var _ = Describe("Apply Instancetypes", func() {
...
 
-func expectGet(fakeClient *fake.Clientset, resource string, object runtime.Object) *bool {
-	called := false
-	fakeClient.Fake.PrependReactor("get", resource, func(action testing.Action) (bool, runtime.Object, error) {
-		_, ok := action.(testing.GetAction)
-		Expect(ok).To(BeTrue())
-		called = true
-		return true, object, nil
+		It("should not call delete if no preferences have been deployed by virt-operator", func() {
+			Expect(reconciler.deleteInstancetypes()).To(Succeed())
```
Comment (0xFelix) [inline pkg/virt-operator/resource/apply/instancetype_test.go:184]: Same

File: pkg/virt-operator/resource/apply/reconcile.go [hunk 5]
```diff
@@ -717,19 +717,23 @@ func (r *Reconciler) Sync(queue workqueue.RateLimitingInterface) (bool, error) {
 	}
 
 	if r.commonInstancetypesDeploymentEnabled() {
+		deploymentStart := time.Now()
```
Comment (0xFelix) [inline pkg/virt-operator/resource/apply/reconcile.go:720]: Move this to L718 and use a common `time.Now()` for both if branches?

File: pkg/virt-operator/resource/apply/instancetype_test.go (hunk 2 above)
Comment (lyarwood) [reply pkg/virt-operator/resource/apply/instancetype_test.go:116]: L34 asserts that no unexpected calls were made by the client.

File: pkg/virt-operator/resource/apply/instancetype_test.go (hunk 1 above)
Comment (lyarwood) [reply pkg/virt-operator/resource/apply/instancetype_test.go:85]: https://github.com/kubevirt/kubevirt/blob/681ccd0543235f87975480b05e71b057339790f5/pkg/virt-operator/resource/apply/instancetype_test.go#L34-L38

File: pkg/virt-operator/resource/apply/instancetype_test.go (hunk 3 above)
Comment (lyarwood) [reply pkg/virt-operator/resource/apply/instancetype_test.go:153]: https://github.com/kubevirt/kubevirt/blob/681ccd0543235f87975480b05e71b057339790f5/pkg/virt-operator/resource/apply/instancetype_test.go#L34-L38

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

File: pkg/virt-operator/resource/apply/reconcile.go [hunk 6]
```diff
@@ -716,20 +716,23 @@ func (r *Reconciler) Sync(queue workqueue.RateLimitingInterface) (bool, error) {
 		return false, err
 	}
 
+	commonInstancetypesStart := time.Now()
```
Comment (xpivarc) [inline pkg/virt-operator/resource/apply/reconcile.go:719]: I wonder if we can drop b57f1e4cfb7656703cc877b6db72ff28dce3fa9d now

File: pkg/virt-operator/resource/generate/install/strategy.go [hunk 7]
```diff
@@ -218,10 +218,18 @@ func (ins *Strategy) Instancetypes() []*instancetypev1beta1.VirtualMachineCluste
 	return ins.instancetypes
 }
 
+func (ins *Strategy) SetInstancetypes(instancetypes []*instancetypev1beta1.VirtualMachineClusterInstancetype) {
+	ins.instancetypes = instancetypes
+}
+
```
Comment (xpivarc) [inline pkg/virt-operator/resource/generate/install/strategy.go:224]: I wouldn't want to introduce this just for testing. Can we workaround this differently?

File: pkg/virt-operator/resource/apply/reconcile.go (hunk 6 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/apply/reconcile.go]: Dropped.

File: pkg/virt-operator/resource/generate/install/strategy.go (hunk 7 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/generate/install/strategy.go]: I replaced the setters with an interface, PTAL.

Comment (xpivarc) [reply pkg/virt-operator/resource/generate/install/strategy.go]: Thanks, the approach looks good. There are some build issues. I can have a proper look once these are addressed.

File: pkg/virt-operator/resource/apply/reconcile.go (hunk 6 above)
Comment (lyarwood) [reply pkg/virt-operator/resource/apply/reconcile.go]: FWIW given these are trace level logs I think they are perfectly acceptable even with the fix.

File: pkg/virt-operator/resource/apply/instancetypes.go [hunk 8]
```diff
@@ -23,19 +23,29 @@ func (r *Reconciler) createOrUpdateInstancetypes() error {
...
+	}
+	foundObj, ok := obj.(*instancetypev1beta1.VirtualMachineClusterInstancetype)
+	if !ok {
+		return nil, fmt.Errorf("unknown object within VirtualMachineClusterInstancetype store")
 	}
+	return foundObj, nil
+}
+
+func (r *Reconciler) createOrUpdateInstancetype(instancetype *instancetypev1beta1.VirtualMachineClusterInstancetype) error {
+	foundObj, err := r.findInstancetype(instancetype.Name)
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/instancetypes.go:42]: We should cover the case where the returned error is `not nil && is different from IsNotFound`

File: pkg/virt-operator/resource/apply/instancetypes.go [hunk 9]
```diff
@@ -83,19 +93,29 @@ func (r *Reconciler) createOrUpdatePreferences() error {
...
+	}
+	foundObj, ok := obj.(*instancetypev1beta1.VirtualMachineClusterPreference)
+	if !ok {
+		return nil, fmt.Errorf("unknown object within VirtualMachineClusterPreference store")
 	}
+	return foundObj, nil
+}
+
+func (r *Reconciler) createOrUpdatePreference(preference *instancetypev1beta1.VirtualMachineClusterPreference) error {
+	foundObj, err := r.findPreference(preference.Name)
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/instancetypes.go:122]: same as above

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 10]
```diff
@@ -20,6 +29,111 @@ import (
 	"kubevirt.io/kubevirt/pkg/virt-operator/util"
 )
 
+type fakeStrategy struct {
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/instancetype_test.go:32]: I think this should be under its own `fake` pkg

**Review by fossedihelm — COMMENTED** [review]
Thank you @0xFelix @lyarwood 
Some comments below.
PTAL

File: pkg/virt-operator/resource/apply/instancetypes.go (hunk 8 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/apply/instancetypes.go:42]: Added a check for this case.

File: pkg/virt-operator/resource/apply/instancetypes.go (hunk 9 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/apply/instancetypes.go:125]: Added a check for this case.

File: pkg/virt-operator/resource/apply/instancetype_test.go (hunk 10 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/apply/instancetype_test.go]: Added a new pkg.

File: pkg/virt-operator/resource/apply/instancetypes.go (hunk 8 above)
Comment (fossedihelm) [reply pkg/virt-operator/resource/apply/instancetypes.go:42]: I'd have preferred previous style:
```
if err != nil && !errors.IsNotFound(err) {
		return err
```
:)

File: pkg/virt-operator/resource/apply/instancetypes.go [hunk 11]
```diff
@@ -72,6 +72,16 @@ func (r *Reconciler) createOrUpdateInstancetype(instancetype *instancetypev1beta
 }
 
 func (r *Reconciler) deleteInstancetypes() error {
+	foundInstancetype := false
+	for _, instancetype := range r.targetStrategy.Instancetypes() {
+		if _, exists, _ := r.stores.ClusterInstancetype.GetByKey(instancetype.Name); exists {
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/instancetypes.go:77]: I think we need to cover the case where an error is returned as we do, for example, for deployment
```
	if err != nil {
		return err
	}
```

File: pkg/virt-operator/resource/apply/instancetypes.go [hunk 12]
```diff
@@ -145,6 +155,16 @@ func (r *Reconciler) createOrUpdatePreference(preference *instancetypev1beta1.Vi
 }
 
 func (r *Reconciler) deletePreferences() error {
+	foundPreference := false
+	for _, preference := range r.targetStrategy.Preferences() {
+		if _, exists, _ := r.stores.ClusterPreference.GetByKey(preference.Name); exists {
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/instancetypes.go:160]: same as above

File: pkg/virt-operator/resource/apply/fake/fakestrategy.go [hunk 13]
```diff
@@ -0,0 +1,120 @@
+package fake
```
Comment (fossedihelm) [inline pkg/virt-operator/resource/apply/fake/fakestrategy.go:1]: missing header

**Review by fossedihelm — COMMENTED** [review]
@0xFelix Sorry for splitted review, but I didn't notice them before

File: pkg/virt-operator/util/types.go [hunk 14]
```diff
@@ -160,6 +162,8 @@ type Informers struct {
 	ConfigMap                        cache.SharedIndexInformer
 	ValidatingAdmissionPolicyBinding cache.SharedIndexInformer
 	ValidatingAdmissionPolicy        cache.SharedIndexInformer
+	ClusterInstancetype              cache.SharedIndexInformer
+	ClusterPreference                cache.SharedIndexInformer
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virt-operator/util/types.go:166]: I hooked the informers up.

File: pkg/virt-operator/kubevirt.go [hunk 15]
```diff
@@ -511,6 +511,36 @@ func NewKubeVirtController(
 		return nil, err
 	}
 
+	_, err = c.informers.ClusterInstancetype.AddEventHandler(cache.ResourceEventHandlerFuncs{
```
Comment (fossedihelm) [inline pkg/virt-operator/kubevirt.go:514]: We should:
```
	cache.WaitForCacheSync(stopCh, c.informers.ClusterInstancetype.HasSynced)
	cache.WaitForCacheSync(stopCh, c.informers.ClusterPreference.HasSynced)
```

File: pkg/virt-operator/kubevirt.go [hunk 16]
```diff
@@ -511,6 +511,36 @@ func NewKubeVirtController(
...
+		AddFunc: func(obj interface{}) {
+			c.genericAddHandler(obj, nil)
```
Comment (fossedihelm) [inline pkg/virt-operator/kubevirt.go:516]: Do we need to add an expectations for cluster instancetype and preference?
```
	ClusterInstancetype *controller.UIDTrackingControllerExpectations
	ClusterPreference     *controller.UIDTrackingControllerExpectations
```
@xpivarc

**Review by fossedihelm — COMMENTED** [review]
Still some doubts :)

File: pkg/virt-operator/kubevirt.go (hunk 15 above)
Comment (0xFelix) [reply pkg/virt-operator/kubevirt.go:514]: I'm not sure it's possible because initially these CRDs won't be available (deployed by virt-operator) and the operator would therefore never start. They can only sync after the CRDs are installed on the cluster.

Comment (xpivarc) [reply pkg/virt-operator/kubevirt.go:514]: I think this is the same for other CRDs as Felix says.

File: pkg/virt-operator/kubevirt.go (hunk 16 above)
Comment (xpivarc) [reply pkg/virt-operator/kubevirt.go:516]: `expectations` are optimization, I don't we need them

File: pkg/virt-operator/resource/apply/instancetype_test.go [hunk 17]
```diff
@@ -62,26 +72,22 @@ var _ = Describe("Apply Instancetypes", func() {
 		})
 
 		It("should create instancetype", func() {
-			getCalled := expectGetReturnNotFound(fakeClient, apiinstancetype.ClusterPluralResourceName)
 			createCalled := expectCreate(fakeClient, apiinstancetype.ClusterPluralResourceName, instancetype)
 			Expect(reconciler.createOrUpdateInstancetype(instancetype)).To(Succeed())
-			Expect(*getCalled).To(BeTrue())
```
Comment (xpivarc) [inline pkg/virt-operator/resource/apply/instancetype_test.go:68]: As a follow up, I think you can reduce the complexity of `expectCreate` (or rather fix?) by interrogating the fake client if it contains them...

**Review by xpivarc — COMMENTED** [review]
/approve
Approach looks good, I am leaving proper review for @fossedihelm

**Review by fossedihelm — APPROVED** [review]
Nothing else from my side :) 
Thank you for this work
