### PR TITLE
test, sriov: Configure ip addresses using cloud init network data

### LINKED ISSUE #4432: [Flaky CI] Sriov lane flaky tests 3956, 3957
/kind bug

**What happened**:
Tests 3956, 3957 might flake with the error (one of the those tests use same flow but ipv4)
```
error: ping -6 fc00::2 -c 1 -w 5 failed
```
I investigated it and saw the IP disappers from the VM after around 1 minute,
the reason is how we configure the ips with nmcli.

saw it for example 2 of 3 here.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4424/pull-kubevirt-e2e-kind-1.17-sriov/1320997424440807424

possible solutions:
1. install NetworkManager-config-server in the VM, preferably by customizing the image.
2. use the right set of nmcli commands.

**What you expected to happen**:
Should be stable, at least the ip in the machine, and afterwards see what is the status.

**How to reproduce it (as minimally and precisely as possible)**:
Wait a bit and the ip would be gone and then try to ping

**Anything else we need to know?**:
Let #4001 be merged first to fix other issue of those tests.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
There is an issue with sriov test lane related to NetworkManager overrid ing the ip
configuration set by the tests using 'virtcl console'.
To fix that this PR will configure the ip address at cloud-init network data using
the "match" feature with the "macaddres attribute [1].

[1] https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4432

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by qinqon** [comment]
/hold sriov has to be ok 
Also looks like the yaml parser is not correctly marshaling it, it's ignoring the golang tags with yaml field names.
```yaml
STEP: Ethernets:
  id0:
    AcceptRA: null
    Addresses:
    - fd10:0:2::2/120
    - 10.1.1.2/24
    DHCP4: null
    DHCP6: null
    DHCPIdentifier: ""
    Gateway4: ""
    Gateway6: fd10:0:2::1
    MACAddress: ""
    MTU: 0
    Match:
      MACAddress: 50:00:00:00:90:0d
    Nameservers:
      Addresses:
      - 10.96.0.10
      Search:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
    Routes: null
Version: 2

```

**Review by maiqueb — CHANGES_REQUESTED** [review]
> /hold sriov has to be ok
> Also looks like the yaml parser is not correctly marshaling it, it's ignoring the golang tags with yaml field names.
> 
> ```yaml
> Ethernets:

`ethernets` is a list.

>   id0:
>     AcceptRA: null
>     Addresses:
>     - fd10:0:2::2/120
>     - 10.1.1.2/24
>     DHCP4: null
>     DHCP6: null
>     DHCPIdentifier: ""
>     Gateway4: ""
>     Gateway6: fd10:0:2::1
>     MACAddress: ""

Shouldn't this feature the mac as well ?.. 

>     MTU: 0
>     Match:
>       MACAddress: 50:00:00:00:90:0d
>     Nameservers:
>       Addresses:
>       - 10.96.0.10
>       Search:
>       - default.svc.cluster.local
>       - svc.cluster.local
>       - cluster.local
>     Routes: null
> Version: 2
> ```

**Comment by oshoval** [comment]
Can you please add that it fixes #4432 ?

also you might find this function interesting, to add to it wait for IPs exists
https://github.com/kubevirt/kubevirt/pull/4335/files#diff-ac233e621be1a1855fe741915d860d91484c7f061fc42beb213f4f9e0a756f86R1258
PR isnt merged yet

**Review by oshoval — COMMENTED** [review]
Can you please add that it fixes #4432 ?

also you might find this function interesting, to add to it wait / verify for IPs exists in vmi status
https://github.com/kubevirt/kubevirt/pull/4335/files#diff-ac233e621be1a1855fe741915d860d91484c7f061fc42beb213f4f9e0a756f86R1258
PR isnt merged yet

**Comment by qinqon** [comment]
Added dependency to https://github.com/kubevirt/kubevirt/pull/4486

**Comment by qinqon** [comment]
Split into separatre commits

File: tests/libnet/cloudinit.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ import (
 type CloudInitNetworkData struct {
 	Version   int                           `yaml:"version"`
 	Ethernets map[string]CloudInitInterface `yaml:"ethernets,omitempty"`
+	Match     CloudInitMatch                `yaml:"match,omitempty"`
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libnet/cloudinit.go]: That was wrong, and removed, take a look at the last re-roganization, this PR was not ready for review.

File: tests/vmi_multus_test.go [hunk 2]
```diff
@@ -924,11 +930,9 @@ var _ = Describe("[Serial]Macvtap", func() {
 	})
 
 	newCirrosVMIWithMacvtapNetwork := func(macvtapNetworkName string) *v1.VirtualMachineInstance {
-		macvtapMultusNetwork := libvmi.MultusNetwork(macvtapNetworkName)
-
 		return libvmi.NewCirros(
 			libvmi.WithInterface(*v1.DefaultMacvtapNetworkInterface(macvtapNetworkName)),
-			libvmi.WithNetwork(&macvtapMultusNetwork))
+			libvmi.WithNetwork(libvmi.MultusNetwork(macvtapNetworkName)))
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/vmi_multus_test.go:930]: I was using this too for SRIOV tests and found that the original strict is a pointer does not make sense the helper `MultusNetwork`  does not return a pointer too.

Returning a pointer at `MultusNetwork` function allows us to inline this kind of things

File: tests/libvmi/network.go [hunk 3]
```diff
@@ -61,8 +61,8 @@ func InterfaceDeviceWithBridgeBinding() kvirtv1.Interface {
 }
 
 // MultusNetwork returns a Network with the given name
-func MultusNetwork(networkName string) kvirtv1.Network {
-	return kvirtv1.Network{
+func MultusNetwork(networkName string) *kvirtv1.Network {
+	return &kvirtv1.Network{
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libvmi/network.go:65]: ditto, https://github.com/kubevirt/kubevirt/pull/4448#discussion_r516641262

File: tests/libnet/cloudinit.go [hunk 4]
```diff
@@ -47,6 +49,10 @@ type CloudInitNameservers struct {
 	Addresses []string `yaml:"addresses,omitempty,flow"`
 }
 
+type CloudInitMatch struct {
+	MACAddress string `yaml:"macaddress,omitempty"`
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libnet/cloudinit.go]: this is the type needed by cloud-init so it has to be string.

File: tests/login.go [hunk 5]
```diff
@@ -104,6 +104,17 @@ func LoggedInAlpineExpecter(vmi *v1.VirtualMachineInstance) (expect.Expecter, er
...
+	expecter, err := LoggedInFedoraExpecterWithoutIPv6Address(vmi)
+	if err != nil {
+		return expecter, err
+	}
+	return expecter, configureIPv6OnVMI(vmi, expecter, virtClient)
+}
+
+// LoggedInFedoraExpecter return prepared and ready to use console expecter for
+// Fedora test VM
+func LoggedInFedoraExpecterWithoutIPv6Address(vmi *v1.VirtualMachineInstance) (expect.Expecter, error) {
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/login.go:117]: Yep I am ok, but I want to make this retro compatible and don't want to change All the others... another option I was thinking is create a `liblogin` or `libconsole` with this function and it will be `liblogin.LoggedInFedoraExpecter` and make the one a utils.go call `liblogin.LoggedInFedoraExpecter` and then configure ipv6, what do you think ?

File: tests/libnet/cloudinit.go [hunk 6]
```diff
@@ -97,6 +103,44 @@ func CreateDefaultCloudInitNetworkData() (string, error) {
...
+// CreateCloudInitNetworkDataWithIPv4AddressByMacAddress generates a configuration
+// for the Cloud-Init Network Data, in version 2 format.
+// It try to match a devices with the mac address and set a static IPv4 and IPv6 addresses,
+// inclusing DNS settings of the cluster nameserver IP and search domains.
+//
+// Example of using match on ethernet at cloud-init documentation [1]
+//
+// [1] https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples
+func CreateCloudInitNetworkDataWithIPv4AddressByMacAddress(macAddress, ipv4Address string) (string, error) {
+	dnsServerIP, err := ClusterDNSServiceIP()
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libnet/cloudinit.go:115]: Maybe what we need is to start to think on a composition mechanism for all this.

File: tests/vmi_multus_test.go [hunk 7]
```diff
@@ -856,6 +854,12 @@ var _ = Describe("[Serial]SRIOV", func() {
 			mac2, err := tests.GenerateRandomMac()
 			Expect(err).ToNot(HaveOccurred())
 
+			// start peer machines with sriov interfaces from the same resource pool
+			// manually configure IP/link on sriov interfaces because there is
+			// no DHCP server to serve the address to the guest
+			vmi1 := getSriovVmi([]string{"sriov-link-enabled"}, cloudInitNetworkDataWithStaticIPsByMac(mac1.String(), cidrA))
+			vmi2 := getSriovVmi([]string{"sriov-link-enabled"}, cloudInitNetworkDataWithStaticIPsByMac(mac2.String(), cidrB))
```
Comment (oshoval) [inline tests/vmi_multus_test.go:861]: for testing you should remove the skip please, unless you did it manually
x2

Comment (qinqon) [reply tests/vmi_multus_test.go:861]: What skip ?

Comment (oshoval) [reply tests/vmi_multus_test.go:861]: https://github.com/kubevirt/kubevirt/pull/4448/files#diff-ac233e621be1a1855fe741915d860d91484c7f061fc42beb213f4f9e0a756f86R882 

L 882
L 887

Comment (qinqon) [reply tests/vmi_multus_test.go:861]: Done, thanks!

**Comment by qinqon** [comment]
Pushed new commit removing the skip from a pair of fixed PRs.

File: tests/network/primary_pod_network.go [hunk 8]
```diff
@@ -114,7 +114,6 @@ var _ = SIGDescribe("[Serial]Primary Pod Network", func() {
 				})
 
 			})
-
```
Comment (oshoval) [inline tests/network/primary_pod_network.go:117]: not related ?

File: go.mod [hunk 9]
```diff
@@ -70,6 +70,7 @@ require (
 	k8s.io/utils v0.0.0-20200720150651-0bdb4ca86cbc
 	kubevirt.io/client-go v0.0.0-00010101000000-000000000000
 	kubevirt.io/containerized-data-importer v1.25.0
+	kubevirt.io/controller-lifecycle-operator-sdk v0.1.1
```
Comment (oshoval) [inline go.mod:73]: u need it to this PR ?
i saw other PRs had it just because the author env caused it

**Comment by oshoval** [comment]
From what i understand you took here just 1 commit from #4486
As Edy suggested there, i would also suggest to either split #4486 to 2 PRs, one if them is just the 1 commit you need here,
or just cherry-pick the whole #4486 here ?

File: go.mod (hunk 9 above)
Comment (qinqon) [reply go.mod:73]: My fault, sometimes I run `go test` directly to build without wait for bazel.

**Comment by qinqon** [comment]
Rebased in top of https://github.com/kubevirt/kubevirt/pull/4492

**Comment by qinqon** [comment]
Addressed @oshoval comments

**Comment by qinqon** [comment]
Rebased on master

File: tests/vmi_multus_test.go (hunk 7 above)
Comment (oshoval) [reply tests/vmi_multus_test.go:864]: Can you add please those 2 issues that were mentioned on the skip to the fix list ?

**Comment by qinqon** [comment]
SRIOV lane is fine and tests are not skipped

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/d58dfb596ef229b71a4a261a01af93724d576ad7..2b14c2b31871d72526dfdfa1059de3ed36e78e3e): Fixed linux bridge test failure

File: tests/libvmi/factory.go [hunk 10]
```diff
@@ -34,6 +34,18 @@ const (
 // NewFedora instantiates a new Fedora based VMI configuration,
 // building its extra properties based on the specified With* options.
 func NewFedora(opts ...Option) *kvirtv1.VirtualMachineInstance {
+	return newFedora(cd.ContainerDiskFedora, opts...)
+}
+
+// NewCustomFedora instantiates a new Fedora based VMI configuration,
+// building its extra properties based on the specified With* options.
+func NewSriovFedora(opts ...Option) *kvirtv1.VirtualMachineInstance {
```
Comment (EdDev) [inline tests/libvmi/factory.go:42]: Can you call it `NewExtendedFedora`? It should have been generalized as such in the first place IMO.
We can use it in other places, not only in an SRIOV context.

File: tests/libvmi/vmi.go [hunk 11]
```diff
@@ -71,6 +71,13 @@ func WithResourceMemory(value string) Option {
 	}
 }
 
+// WithNamespace specifies the vmi namespace
+func WithNamespace(value string) Option {
```
Comment (EdDev) [inline tests/libvmi/vmi.go:75]: It has been raised that we should not specify the namespace in the spec, it should be left up to the `Create` to add it on creation.

File: tests/vmi_multus_test.go [hunk 12]
```diff
@@ -375,27 +375,34 @@ var _ = Describe("[Serial]Multus", func() {
...
+					libvmi.WithNetwork(&linuxBridgeNetwork),
+					libvmi.WithCloudInitNoCloudNetworkData(cloudInitNetworkDataWithStaticIPsByMac(customMacAddress, "10.1.1.1/24"), false))
+				vmiOne = tests.StartVmOnNode(vmiOne, nodes.Items[0].Name)
+
+				tests.WaitUntilVMIReady(vmiTwo, console.LoginToFedora)
+				tests.WaitUntilVMIReady(vmiOne, console.LoginToFedora)
 
 				By("Verifying the desired custom MAC is the one that were actually configured on the interface.")
-				ipLinkShow := fmt.Sprintf("ip link show eth0 | grep -i \"%s\" | wc -l\n", customMacAddress)
+				ipLinkShow := fmt.Sprintf("ip link show id0 | grep -i \"%s\" | wc -l\n", customMacAddress)
```
Comment (EdDev) [inline tests/vmi_multus_test.go:405]: `id0` is hidden inside the helpers. I hope we can use the build pattern here and not do this magic.

File: tests/vmi_multus_test.go [hunk 13]
```diff
@@ -375,27 +375,34 @@ var _ = Describe("[Serial]Multus", func() {
...
+					libvmi.WithNetwork(v1.DefaultPodNetwork()),
+					libvmi.WithInterface(linuxBridgeInterfaceWithCustomMac),
+					libvmi.WithNetwork(&linuxBridgeNetwork),
+					libvmi.WithCloudInitNoCloudNetworkData(cloudInitNetworkDataWithStaticIPsByMac(customMacAddress, "10.1.1.1/24"), false))
+				vmiOne = tests.StartVmOnNode(vmiOne, nodes.Items[0].Name)
+
+				tests.WaitUntilVMIReady(vmiTwo, console.LoginToFedora)
+				tests.WaitUntilVMIReady(vmiOne, console.LoginToFedora)
 
 				By("Verifying the desired custom MAC is the one that were actually configured on the interface.")
```
Comment (EdDev) [inline tests/vmi_multus_test.go:404]: This is probably unrelated to this PR:
- The guest Agent is reporting the mac address, but do we use it to populate the status fields of the VMI?
- Tests that are interested to check actual VM config, should probably use the GA as it is the only public API we support. I think we should avoid tests using inner implementations and should focus on using the API to get what we need. If it is not there, it means we either do not need to check it, we need to expose it or we need to use other means. Obviously this is not a hard rule, there will be always that will require digging in too much.

File: tests/vmi_multus_test.go [hunk 14]
```diff
@@ -625,28 +632,29 @@ var _ = Describe("[Serial]SRIOV", func() {
...
-
-			// newer fedora kernels may require hardware RNG to boot
-			vmi.Spec.Domain.Devices.Rng = &v1.Rng{}
-
-			// pod network interface
-			vmi.Spec.Domain.Devices.Interfaces = []v1.Interface{{Name: "default", Ports: []v1.Port{}, InterfaceBindingMethod: v1.InterfaceBindingMethod{Masquerade: &v1.InterfaceMasquerade{}}}}
-			vmi.Spec.Networks = []v1.Network{*v1.DefaultPodNetwork()}
+		getSriovVmi := func(networks []string, cloudInitNetworkData string) *v1.VirtualMachineInstance {
 
+			withSriovOptions := []libvmi.Option{
```
Comment (EdDev) [inline tests/vmi_multus_test.go:638]: No SRIOV options here yet, the name is confusing.
How about just `vmiOptions` ?

File: tests/vmi_multus_test.go [hunk 15]
```diff
@@ -625,28 +632,29 @@ var _ = Describe("[Serial]SRIOV", func() {
...
-				iface := v1.Interface{Name: name, InterfaceBindingMethod: v1.InterfaceBindingMethod{SRIOV: &v1.InterfaceSRIOV{}}}
-				network := v1.Network{Name: name, NetworkSource: v1.NetworkSource{Multus: &v1.MultusNetwork{NetworkName: name}}}
-				vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, iface)
-				vmi.Spec.Networks = append(vmi.Spec.Networks, network)
+				withSriovOptions = append(withSriovOptions, libvmi.WithInterface(
+					v1.Interface{
+						Name:                   name,
+						InterfaceBindingMethod: v1.InterfaceBindingMethod{SRIOV: &v1.InterfaceSRIOV{}},
+					}))
+				withSriovOptions = append(withSriovOptions, libvmi.WithNetwork(libvmi.MultusNetwork(name)))
```
Comment (EdDev) [inline tests/vmi_multus_test.go:651]: You can append once: `s = append(s, a, b)`

File: tests/vmi_multus_test.go [hunk 16]
```diff
@@ -625,28 +632,29 @@ var _ = Describe("[Serial]SRIOV", func() {
...
+
 			}
 
+			// Pre-configured container-disk image for sriov-lane
```
Comment (EdDev) [inline tests/vmi_multus_test.go:655]: The comment is redundant IMO.

**Review by EdDev — CHANGES_REQUESTED** [review]

File: tests/libnet/cloudinit.go [hunk 17]
```diff
@@ -38,15 +38,21 @@ type CloudInitInterface struct {
...
 }
 
 type CloudInitNameservers struct {
 	Search    []string `json:"search,omitempty,flow"`
 	Addresses []string `json:"addresses,omitempty,flow"`
 }
 
+type CloudInitMatch struct {
+	MACAddress string `json:"macaddress,omitempty"`
+}
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:54]: Maybe you should add the other available options.
But this is not a must, whatever you prefer.

File: tests/libvmi/factory.go (hunk 10 above)
Comment (qinqon) [reply tests/libvmi/factory.go:42]: Looks like is more than just GA and friends it really contains SRIOV specific bits:
```
 Fedora cloud edition image with contains all necessary configuration and drivers for sriov lane tests.
    - This image contained the packages:                                        
        - kernel-modules (includes sriov drivers)                               
        - qemu-guest-agent                                                      
    - Configurations:                                                           
        - Enable and start qemu-guest-agent                                     
        - Load kernel modules needed for sriov                                  
          mlx4, mlx5, i40e, igb                          
```

We can create a follow up PR with fedra + GA + whatever we feel is needed and use it on `NewExtendedFedor`

File: tests/libvmi/vmi.go (hunk 11 above)
Comment (qinqon) [reply tests/libvmi/vmi.go:75]: Done

File: tests/vmi_multus_test.go (hunk 14 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:638]: done renamed to `withVmiOptions` so we have `NewSriovFedora(withVmiOptions)`

File: tests/vmi_multus_test.go (hunk 15 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:651]: Done

File: tests/vmi_multus_test.go (hunk 16 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:655]: Done

File: tests/libvmi/factory.go (hunk 10 above)
Comment (EdDev) [reply tests/libvmi/factory.go:42]: It has just additional drivers, how is that a problem?
The current Fedora has much more installations we do not need, so a few more drivers should not matter here.

I do not think we have interest in maintaining multiple images when we do not need to.

File: tests/libnet/cloudinit.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libnet/cloudinit.go:115]: Done

File: tests/vmi_multus_test.go (hunk 13 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:404]: +1, I will use the Status as much as possible, it will also help get rid of `id0` check.

File: tests/vmi_multus_test.go (hunk 12 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:405]: Let's use VMI Status https://github.com/kubevirt/kubevirt/pull/4448#discussion_r526675594.

File: tests/libnet/cloudinit.go (hunk 17 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:54]: Done

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/2b14c2b31871d72526dfdfa1059de3ed36e78e3e..404a2db2a2979c5e5f4d13ea0b4e1ad0fc0ef2d0): Addressed @EdDev comments

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/404a2db2a2979c5e5f4d13ea0b4e1ad0fc0ef2d0..a488a84185eea705336f5fe9c60cd9bc8a00c4c5): Fixing CI the `set-name` networkData field was missing.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/a488a84185eea705336f5fe9c60cd9bc8a00c4c5..345a89b29e4f68fb72350714c478fa3d966622f6): Removing noise from my env.

File: tests/libnet/cloudinit.go [hunk 18]
```diff
@@ -23,12 +23,106 @@ import (
...
+		if networkData.Ethernets == nil {
+			networkData.Ethernets = map[string]CloudInitInterface{}
+		}
+
+		networkDataInterface := CloudInitInterface{name: name}
+
+		for _, option := range options {
+			err := option(&networkDataInterface)
+			if err != nil {
+				return nil
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:57]: err?

File: tests/libnet/cloudinit.go [hunk 19]
```diff
@@ -23,12 +23,106 @@ import (
...
+	return func(networkDataInterface *CloudInitInterface) error {
+		if networkDataInterface.Addresses == nil {
+			networkDataInterface.Addresses = []string{}
+		}
+		networkDataInterface.Addresses = append(networkDataInterface.Addresses, addresses...)
+		return nil
+	}
+}
+
+func WithDHCP4() NetworkDataInterfaceOption {
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:76]: Don't we need an `enabled bool` argument?

File: tests/libnet/cloudinit.go [hunk 20]
```diff
@@ -23,12 +23,106 @@ import (
...
+	return func(networkDataInterface *CloudInitInterface) error {
+		enabled := true
+		networkDataInterface.DHCP4 = &enabled
+		return nil
+	}
+}
+
+func WithStaticIPv6Address() NetworkDataInterfaceOption {
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:84]: I guess you mean `WithIPv6GWAddress`.
Now it looks like it is the option to add an IPv6 static address, but this is not the case. It is specific to the gateway.

File: tests/libnet/cloudinit.go [hunk 21]
```diff
@@ -23,12 +23,106 @@ import (
...
+	return func(networkDataInterface *CloudInitInterface) error {
+		WithAddresses(DefaultIPv6Address)(networkDataInterface)
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:86]: I do not understand this side effect here. Why do you mix them?
It looks like a default, which I expect the caller to compose, there is no need to a default `With` IMO. That can be left to the factory to do.

File: tests/libnet/cloudinit.go [hunk 22]
```diff
@@ -23,12 +23,106 @@ import (
...
+		}
+		networkDataInterface.Nameservers = CloudInitNameservers{
+			Addresses: []string{dnsServerIP},
+			Search:    SearchDomains(),
+		}
+		return nil
+	}
+}
+
+func MatchingMAC(macAddress string) NetworkDataInterfaceOption {
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:106]: Does the `With` prefix not a fit here?

File: tests/libnet/cloudinit.go [hunk 23]
```diff
@@ -23,12 +23,106 @@ import (
...
+		networkDataInterface.Match = CloudInitMatch{
+			MACAddress: macAddress,
+		}
+		networkDataInterface.SetName = networkDataInterface.name
+		return nil
+	}
+}
+
+type NetworkDataOption func(*CloudInitNetworkData) error
+type NetworkDataInterfaceOption func(*CloudInitInterface) error
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:117]: I think these fit at the head of the file.

File: tests/vmi_networking_test.go [hunk 24]
```diff
@@ -817,7 +817,13 @@ var _ = Describe("[Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][le
 				var err error
 
 				By("Create masquerade VMI")
-				networkData, err := libnet.CreateDefaultCloudInitNetworkData()
```
Comment (EdDev) [inline tests/vmi_networking_test.go:820]: I would keep the default factory there for now. If we will start using cloud init on other tests, it will be a shame not to re-use the same factory.
But even if we are to move it (I do not have a hard opinion on this), it better be on a separate PR/commit with a proper reasoning.

**Review by EdDev — CHANGES_REQUESTED** [review]

File: tests/libnet/cloudinit.go (hunk 19 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:76]: `WithDHCP4` is clearly activating it if we need deactivation we can add `WithoutDHCP4`

File: tests/libnet/cloudinit.go (hunk 20 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:84]: Maybe better `WithStaticIPv6Config` since the function set the address and the gw.

File: Makefile [hunk 25]
```diff
@@ -55,7 +55,7 @@ go-build:
 
 gosec:
 	hack/dockerized "./hack/gosec.sh"
-	
+
```
[the remark this answers is not in the document]
Comment (qinqon) [reply Makefile:58]: Done

File: tests/libnet/cloudinit.go [hunk 26]
```diff
@@ -23,12 +23,106 @@ import (
...
 
+func NewNetworkData(options ...NetworkDataOption) (string, error) {
+	networkData := CloudInitNetworkData{
+		Version: 2,
+	}
+
+	for _, option := range options {
+		err := option(&networkData)
+		if err != nil {
+			return "", nil
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/libnet/cloudinit.go:34]: Done

File: tests/libnet/cloudinit.go (hunk 18 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:57]: Done

File: tests/libnet/cloudinit.go (hunk 22 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:106]: Done

File: tests/libnet/cloudinit.go (hunk 23 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:117]: Done

File: tests/vmi_networking_test.go (hunk 24 above)
Comment (qinqon) [reply tests/vmi_networking_test.go:820]: Done

File: tests/libnet/cloudinit.go (hunk 21 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:86]: Will split between IPv6 address and gateway6.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/345a89b29e4f68fb72350714c478fa3d966622f6..a0799ad7e39eb9d375543d8609165cfc2aa4ac26): Adressed  @EdDev comments

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/a0799ad7e39eb9d375543d8609165cfc2aa4ac26..b5e11991ad2fa45c2df3ef108290197d88169ecb): Fixed failing test using ests.WaitUntilVMIReady since we need virtctl console to be ready to run ping command between VMs.

**Comment by qinqon** [comment]
force-push: Rebased and splitted in three commits, the refactoring the linux-bridge CNI test change and the SRIOV test change.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/b5e11991ad2fa45c2df3ef108290197d88169ecb..c85de87da36e9e0835a2f38c91a83a2962e14913): Fix error handling at cloud-init

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/8343dfdcaf14f63c41f681fee29520603da328ad..197e182a78dac6a58b8c936657ea72f447e333f8): Move networkData builder structs to the beginning of go file.

**Comment by qinqon** [comment]
sriov lane is failing https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4448/pull-kubevirt-e2e-kind-1.17-sriov/1329721990516314114:

```
tests/vmi_multus_test.go:866
Unexpected error:
    <*errors.errorString | 0xc001622a50>: {
        s: "an empty namespace may not be set when a resource name is provided",
    }
    an empty namespace may not be set when a resource name is provided
occurred
tests/vmi_multus_test.go:859
```

and

```
Expected success, but got an error:
    <*fmt.wrapError | 0xc001654380>: {
        msg: "could not check interface: interface eth0 was not found in the VMI testvmishzjlz4v7xgdr2vnzb94v6vfprj77ngg6ztb9n89jxznh6z7: Can't connect to websocket (301): websocket: bad handshake\n",
        err: {
            err: "Can't connect to websocket (301): websocket: bad handshake\n",
            StatusCode: 301,
        },
    }
    could not check interface: interface eth0 was not found in the VMI testvmishzjlz4v7xgdr2vnzb94v6vfprj77ngg6ztb9n89jxznh6z7: Can't connect to websocket (301): websocket: bad handshake
    
```

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/197e182a78dac6a58b8c936657ea72f447e333f8..a431109f2dd14c98d2e44910dfa0061e1cd053de): Use default tests namespace at SRIOV tests

File: tests/libnet/cloudinit.go (hunk 19 above)
Comment (EdDev) [reply tests/libnet/cloudinit.go:81]: Well, that is the default anyway (enabled).
`WithDHCP4` may also mean: With this attribute, so adding a flag makes sense.

But if you prefer it this way, ok.

File: tests/libnet/cloudinit.go [hunk 27]
```diff
@@ -63,42 +166,13 @@ const (
 	DefaultIPv6Gateway = "fd10:0:2::1"
 )
 
-// CreateDefaultCloudInitNetworkData generates a default configuration
-// for the Cloud-Init Network Data, in version 2 format.
-// The default configuration sets dynamic IPv4 (DHCP) and static IPv6 addresses,
-// inclusing DNS settings of the cluster nameserver IP and search domains.
```
Comment (EdDev) [inline tests/libnet/cloudinit.go:69]: Any reason to remove the doctext?

File: tests/libvmi/factory.go [hunk 28]
```diff
@@ -34,6 +34,18 @@ const (
...
+	return newFedora(cd.ContainerDiskFedoraSRIOVLane, opts...)
+}
+
+// NewFedora instantiates a new Fedora based VMI configuration,
```
Comment (EdDev) [inline tests/libvmi/factory.go:46]: NewFedora -> newFedora

Please add that the flavor of the image is provided (that is the main difference from the public one).

File: tests/libvmi/factory.go [hunk 29]
```diff
@@ -34,6 +34,18 @@ const (
 // NewFedora instantiates a new Fedora based VMI configuration,
 // building its extra properties based on the specified With* options.
 func NewFedora(opts ...Option) *kvirtv1.VirtualMachineInstance {
+	return newFedora(cd.ContainerDiskFedora, opts...)
```
Comment (EdDev) [inline tests/libvmi/factory.go:37]: This change appears in the first commit, but I think it does not belong here... right?
If it does, just update the commit message.

**Review by EdDev — CHANGES_REQUESTED** [review]
Review `tests, libnet: Add Match feature and expression builder to networkData`.

File: tests/vmi_multus_test.go [hunk 30]
```diff
@@ -1240,3 +1258,35 @@ func validatePodKubevirtResourceName(virtClient kubecli.KubevirtClient, vmiPod *
 
 	return nil
 }
+
+func defaultCloudInitNetworkData() string {
```
Comment (EdDev) [inline tests/vmi_multus_test.go:1251]: Seems like this is no longer used now.

File: tests/vmi_multus_test.go [hunk 31]
```diff
@@ -1240,3 +1258,35 @@ func validatePodKubevirtResourceName(virtClient kubecli.KubevirtClient, vmiPod *
...
+	networkData, err := libnet.CreateDefaultCloudInitNetworkData()
+	ExpectWithOffset(1, err).ToNot(HaveOccurred(), "should success creating default cloud init network data for SRIOV")
+	return networkData
+}
+
+func cloudInitNetworkDataWithStaticIPsByMac(macAddress, ipv4Address string) string {
```
Comment (EdDev) [inline tests/vmi_multus_test.go:1257]: The DHCP was not mentioned here and I am not sure if it absence is not an implicit "enabled". Could you please confirm from inside the VM?

File: tests/vmi_multus_test.go [hunk 32]
```diff
@@ -1240,3 +1258,35 @@ func validatePodKubevirtResourceName(virtClient kubecli.KubevirtClient, vmiPod *
...
+			libnet.WithNameserverFromCluster(),
+			libnet.WithMatchingMAC(macAddress),
+		),
+	)
+	ExpectWithOffset(1, err).ToNot(HaveOccurred(), "should success creating static IPs by mac address cloud init network data")
+	return networkData
+}
+
+func cloudInitNetworkDataWithStaticIPsByDevice(deviceName, ipv4Address string) string {
+	networkData, err := libnet.NewNetworkData(
```
Comment (EdDev) [inline tests/vmi_multus_test.go:1271]: Seems like the "default" is exactly this one, right?

**Review by EdDev — CHANGES_REQUESTED** [review]
Commit `tests, linux-bridge CNI: Configure networking at one of the tests with cloud-init`.

Please limit the commit message row length.

File: tests/vmi_multus_test.go [hunk 33]
```diff
@@ -643,29 +643,25 @@ var _ = Describe("[Serial]SRIOV", func() {
...
 			for _, name := range networks {
-				iface := v1.Interface{Name: name, InterfaceBindingMethod: v1.InterfaceBindingMethod{SRIOV: &v1.InterfaceSRIOV{}}}
-				network := v1.Network{Name: name, NetworkSource: v1.NetworkSource{Multus: &v1.MultusNetwork{NetworkName: name}}}
-				vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, iface)
-				vmi.Spec.Networks = append(vmi.Spec.Networks, network)
+				withVmiOptions = append(withVmiOptions, libvmi.WithInterface(
+					v1.Interface{
+						Name:                   name,
+						InterfaceBindingMethod: v1.InterfaceBindingMethod{SRIOV: &v1.InterfaceSRIOV{}},
+					}),
```
Comment (EdDev) [inline tests/vmi_multus_test.go:660]: This seems to merit `InterfaceWithSRIOVBinding(name)`.
And we should sync all other bindings to accept a name (not in this PR).

File: tests/vmi_multus_test.go [hunk 34]
```diff
@@ -793,7 +789,7 @@ var _ = Describe("[Serial]SRIOV", func() {
 			var interfaceName string
 			Eventually(func() error {
 				var err error
-				vmi, err = virtClient.VirtualMachineInstance(vmi.Namespace).Get(vmi.Name, &metav1.GetOptions{})
+				vmi, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmi.Name, &metav1.GetOptions{})
```
Comment (EdDev) [inline tests/vmi_multus_test.go:792]: ditto

File: tests/vmi_multus_test.go [hunk 35]
```diff
@@ -857,21 +855,15 @@ var _ = Describe("[Serial]SRIOV", func() {
 			waitVmi(vmi1)
 			waitVmi(vmi2)
 
-			vmi1, err = virtClient.VirtualMachineInstance(vmi1.Namespace).Get(vmi1.Name, &metav1.GetOptions{})
+			vmi1, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmi1.Name, &metav1.GetOptions{})
```
Comment (EdDev) [inline tests/vmi_multus_test.go:858]: ditto

File: tests/vmi_multus_test.go [hunk 36]
```diff
@@ -857,21 +855,15 @@ var _ = Describe("[Serial]SRIOV", func() {
...
 			Expect(err).NotTo(HaveOccurred())
-			vmi2, err = virtClient.VirtualMachineInstance(vmi2.Namespace).Get(vmi2.Name, &metav1.GetOptions{})
+			vmi2, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmi2.Name, &metav1.GetOptions{})
```
Comment (EdDev) [inline tests/vmi_multus_test.go:860]: ditto

**Review by EdDev — CHANGES_REQUESTED** [review]
> There is an issue with sriov test lane related to NetworkManager overriding the ip
> configuration set by the tests using 'virtcl console'.

When the VM configuration is manipulated through the console (using the `ip` command) and NetworkManager is active, it may override the configuration with its own configuration.
 
> To fix that this PR will configure the ip address at cloud-init network data using
> the "match" introduced by the cloud-init refactoring

at ==> using
using the "match" option.
(no need to mention the "refactoring", in this change it already exists).

File: tests/libnet/cloudinit.go (hunk 27 above)
Comment (qinqon) [reply tests/libnet/cloudinit.go:69]: Nope, resurrecting it.

File: tests/libvmi/factory.go (hunk 28 above)
Comment (qinqon) [reply tests/libvmi/factory.go:46]: Done

File: tests/libvmi/factory.go (hunk 29 above)
Comment (qinqon) [reply tests/libvmi/factory.go:37]: Right, we need this ony for the SRIOV part I will add it to that commit.

File: tests/libvmi/factory.go (hunk 10 above)
Comment (qinqon) [reply tests/libvmi/factory.go:42]: I prefer to do all or nothing, meaning a followup PR renaming both image and factory name, mixing both is missleading.

File: tests/vmi_multus_test.go [hunk 37]
```diff
@@ -375,32 +375,50 @@ var _ = Describe("[Serial]Multus", func() {
...
+					libvmi.WithNetwork(&linuxBridgeNetwork),
+					libvmi.WithCloudInitNoCloudUserData(tests.GetGuestAgentUserData(), false),
+					libvmi.WithCloudInitNoCloudNetworkData(cloudInitNetworkDataWithStaticIPsByMac(customMacAddress, "10.1.1.1/24"), false))
+				vmiOne = tests.StartVmOnNode(vmiOne, nodes.Items[0].Name)
+
+				tests.WaitUntilVMIReady(vmiOne, console.LoginToFedora)
+				tests.WaitAgentConnected(virtClient, vmiOne)
+
+				tests.WaitUntilVMIReady(vmiTwo, console.LoginToFedora)
+				tests.WaitAgentConnected(virtClient, vmiTwo)
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/vmi_multus_test.go:407]: No need for that, the VMIs have start in parallel since we have already call `Create`, so second call at test to `WaitUntiVMIReady` and `WaitAgentConnected` will be almost ready.

File: tests/vmi_multus_test.go (hunk 30 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1251]: Done

File: tests/vmi_multus_test.go (hunk 31 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1257]: originally it was not enabled either, I will check though just to be sure.

File: tests/vmi_multus_test.go (hunk 32 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1271]: It's being used with "eth1" and not with "eth0" so it's not the default.

File: tests/vmi_multus_test.go [hunk 38]
```diff
@@ -375,32 +375,50 @@ var _ = Describe("[Serial]Multus", func() {
...
+					vmiOne, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmiOne.Name, &metav1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred(), "should find vmiOne to check nic0 MAC at Status")
+
+					for _, iface := range vmiOne.Status.Interfaces {
+						if iface.Name == linuxBridgeInterfaceWithCustomMac.Name {
+							return iface.MAC
+						}
+					}
+					return ""
+				}).Should(Equal(customMacAddress), "should set linux bridge interface with the custom MAC address")
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/vmi_multus_test.go:421]: > BUT, all the above may be irrelevant as it seems we read the mac address for non-SRIOV and non-custom (created by user in the VM itself) from the domain spec and not from the GA. Only in case of SRIOV or an interface that was created by the user inside the VM, we report the mac from the GA.
Therefore, I think we do not need GA at all in this test and there is no need to wait with Eventually. Have you seen this needed while testing?

Then we have an issue here, the original version of this test looks inside the VMI to check the mac address, but the version at this PR check the Status I though status was being set by guest agent, but looks like it's not ? then we cannot use status here.

[the remark this answers is not in the document]
Comment (EdDev) [reply tests/vmi_multus_test.go:421]: IMO we can, as we are not tracking of libvirt is working well or not here.
On the other hand, we should make sure to overwrite the mac address if it is different from the one reported (or add a warning about it).
Sound like an issue we have not covered in both production and tests (but I may be wrong here).

File: tests/vmi_multus_test.go (hunk 31 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1257]: For IPv4 I see `static` 
```bash
[root@testvmi6pqv6lnzqh2j4wkngpz5bwpqffbxpj9lt8gkczf9xt24tv6j fedora]# nmcli c show "System eth1" |grep ipv4.method
ipv4.method:                            auto
```

For IPv6 Is auto, I suppose we don't care here.
```bash
[root@testvmi6pqv6lnzqh2j4wkngpz5bwpqffbxpj9lt8gkczf9xt24tv6j fedora]# nmcli c show "System eth1" |grep ipv6.method
ipv6.method:                            auto
```

File: tests/vmi_multus_test.go [hunk 39]
```diff
@@ -676,7 +672,7 @@ var _ = Describe("[Serial]SRIOV", func() {
 
 		waitVmi := func(vmi *v1.VirtualMachineInstance) {
 			// Need to wait for cloud init to finish and start the agent inside the vmi.
-			vmi, err := virtClient.VirtualMachineInstance(vmi.Namespace).Get(vmi.Name, &metav1.GetOptions{})
+			vmi, err := virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmi.Name, &metav1.GetOptions{})
```
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/vmi_multus_test.go:675]: the `vmi.Namespace` is empty with the factory we have a libvmi, it was not the case with previous factory and looks like adding `WithNamespace` is not a good idea.

File: tests/vmi_multus_test.go (hunk 34 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:792]: https://github.com/kubevirt/kubevirt/pull/4448#discussion_r528560676

File: tests/vmi_multus_test.go (hunk 35 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:858]: https://github.com/kubevirt/kubevirt/pull/4448#discussion_r528560676

File: tests/vmi_multus_test.go (hunk 36 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:860]: https://github.com/kubevirt/kubevirt/pull/4448#discussion_r528560676

File: tests/vmi_multus_test.go (hunk 31 above)
Comment (EdDev) [reply tests/vmi_multus_test.go:1257]: Ok, thanks!

File: tests/vmi_multus_test.go (hunk 39 above)
[the remark this answers is not in the document]
Comment (EdDev) [reply tests/vmi_multus_test.go:675]: The VMI has been already created, are you saying that on creation we have not updated the `vmi` variable with the returned updated object?

File: tests/vmi_multus_test.go (hunk 33 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:660]: Done

**Comment by qinqon** [comment]
https://github.com/kubevirt/kubevirt/compare/a431109f2dd14c98d2e44910dfa0061e1cd053de..705307a308d3e91629c3dc3811c271b0257aae97: @EdDev comments

/hold
Let's wait for sriov lane.

File: tests/vmi_multus_test.go (hunk 39 above)
[the remark this answers is not in the document]
Comment (qinqon) [reply tests/vmi_multus_test.go:672]: Looks like we are not updateing the vmi object at `Creation`
```golang
startVmi := func(vmi *v1.VirtualMachineInstance) {
			_, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Create(vmi)
			Expect(err).ToNot(HaveOccurred())
			return
		}
```

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/705307a308d3e91629c3dc3811c271b0257aae97..8f001d88d6e268974d4e5d0451b6405bac57e109): Updating `vmi` at creation so `vmi.Namespace` can be used.

File: tests/vmi_multus_test.go (hunk 39 above)
[the remark this answers is not in the document]
Comment (EdDev) [reply tests/vmi_multus_test.go]: This is one of the reasons I dislike overusing lambdas.

File: tests/libvmi/factory.go [hunk 40]
```diff
@@ -34,6 +34,20 @@ const (
...
 // building its extra properties based on the specified With* options.
 func NewFedora(opts ...Option) *kvirtv1.VirtualMachineInstance {
+	return newFedora(cd.ContainerDiskFedora)
+}
+
+// NewSriovFedora instantiates a new Fedora based VMI configuration,
+// building its extra properties based on the specified With* options, the
+// image used include Guest Agent and some moduled needed by SRIOV.
+func NewSriovFedora(opts ...Option) *kvirtv1.VirtualMachineInstance {
+	return newFedora(cd.ContainerDiskFedoraSRIOVLane)
```
Comment (alonSadan) [inline tests/libvmi/factory.go:44]: I think you need to pass `opts` here as well:
`return newFedora(cd.ContainerDiskFedoraSRIOVLane, opts)`

File: tests/vmi_multus_test.go [hunk 41]
```diff
@@ -375,32 +375,50 @@ var _ = Describe("[Serial]Multus", func() {
...
-			interfaces := []v1.Interface{linuxBridgeInterface}
-			networks := []v1.Network{linuxBridgeNetwork}
-			linuxBridgeIfIdx := 0
 			customMacAddress := "50:00:00:00:90:0d"
 
 			It("[test_id:676]should configure valid custom MAC address on Linux bridge CNI interface.", func() {
 				By("Creating a VM with Linux bridge CNI network interface and default MAC address.")
-				vmiTwo := createVMIOnNode(interfaces, networks)
-				tests.WaitUntilVMIReady(vmiTwo, console.LoginToAlpine)
+				vmiTwo := libvmi.NewFedora(
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:382]: nit: consider extracting the vmi object creation  to a helper that will receive networks and interfaces and return the vmi object. pretty much the same process is repeated here and on line 395, and also it is a long list of `libvmi.WithSomething`, and perhaps could be abstracted. I don't think it is that important, because it only repeated twice, but perhaps it will be useful in the future.

File: tests/vmi_multus_test.go [hunk 42]
```diff
@@ -375,32 +375,50 @@ var _ = Describe("[Serial]Multus", func() {
...
-					&expect.BSnd{S: ipLinkShow},
-					&expect.BExp{R: "1"},
-				}, 15)
-				Expect(err).ToNot(HaveOccurred())
+				Eventually(func() string {
+
+					vmiOne, err = virtClient.VirtualMachineInstance(tests.NamespaceTestDefault).Get(vmiOne.Name, &metav1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred(), "should find vmiOne to check nic0 MAC at Status")
+
+					for _, iface := range vmiOne.Status.Interfaces {
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:415]: nit: Consider extracting this for-loop to a general helper :  `getInterfaceMacByName`

Another option is to use `getInterfaceNameByMAC` and use the eventually on the name of the interface instead of the mac.

File: tests/vmi_multus_test.go [hunk 43]
```diff
@@ -1240,3 +1244,35 @@ func validatePodKubevirtResourceName(virtClient kubecli.KubevirtClient, vmiPod *
 
 	return nil
 }
+
+func defaultCloudInitNetworkData() string {
+	networkData, err := libnet.CreateDefaultCloudInitNetworkData()
+	ExpectWithOffset(1, err).ToNot(HaveOccurred(), "should success creating default cloud init network data for SRIOV")
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:1250]: nit: "should succeed in creating..."
or you can: "should successfully create..."

File: tests/vmi_multus_test.go [hunk 44]
```diff
@@ -1240,3 +1244,35 @@ func validatePodKubevirtResourceName(virtClient kubecli.KubevirtClient, vmiPod *
...
+func cloudInitNetworkDataWithStaticIPsByMac(macAddress, ipv4Address string) string {
+	networkData, err := libnet.NewNetworkData(
+		libnet.WithEthernet("nic0",
+			libnet.WithAddresses(ipv4Address, libnet.DefaultIPv6Address),
+			libnet.WithGateway6(libnet.DefaultIPv6Gateway),
+			libnet.WithNameserverFromCluster(),
+			libnet.WithMatchingMAC(macAddress),
+		),
+	)
+	ExpectWithOffset(1, err).ToNot(HaveOccurred(), "should success creating static IPs by mac address cloud init network data")
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:1263]: ditto

**Review by alonSadan — COMMENTED** [review]
Thank you Quique!
I added one note and some nits.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/0cff7e84b18f5dc291efd68aba6e61277dc1d61c..e8f12326fe27a343fbbd6db7500a644971cf9ded):  Checking MAC address also at VMI as suggested offline by Alona.

File: tests/vmi_multus_test.go [hunk 45]
```diff
@@ -375,32 +375,37 @@ var _ = Describe("[Serial]Multus", func() {
...
+				tests.WaitUntilVMIReady(vmiTwo, console.LoginToFedora)
 
 				By("Verifying the desired custom MAC is the one that were actually configured on the interface.")
-				ipLinkShow := fmt.Sprintf("ip link show eth0 | grep -i \"%s\" | wc -l\n", customMacAddress)
-				err = console.SafeExpectBatch(vmiOne, []expect.Batcher{
-					&expect.BSnd{S: ipLinkShow},
-					&expect.BExp{R: "1"},
-				}, 15)
-				Expect(err).ToNot(HaveOccurred())
+				Expect(vmiOne.Status.Interfaces[1].MAC).To(Equal(customMacAddress), "should set linux bridge interface with the custom MAC address at VMI Status")
```
Comment (oshoval) [inline tests/vmi_multus_test.go:407]: 1. Do you know for sure it will be on `vmiOne.Status.Interfaces[1]` ?
Order until now could be changed in VMI status
2. You need Eventually here, please see test 3985, else you might have the race condition between the GA and the VMI status.

Comment (qinqon) [reply tests/vmi_multus_test.go:407]: > Do you know for sure it will be on vmiOne.Status.Interfaces[1] ?
Order until now could be changed in VMI status

ack, will add a check

> You need Eventually here, please see test 3985 or your PR which fixes the race, else you might have the race condition between the GA and the VMI status.

The MAC is not taken from Guest Agent is taken from libvirt domxml so there is no need for Eventually.

File: tests/libvmi/factory.go (hunk 40 above)
Comment (qinqon) [reply tests/libvmi/factory.go:44]: Second time I end with the same issue, thanks Alon !!!

File: tests/vmi_multus_test.go (hunk 41 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:382]: Let's follow the rule of three and keep it like this for now.

File: tests/vmi_multus_test.go (hunk 45 above)
Comment (oshoval) [reply tests/vmi_multus_test.go:407]: > > Do you know for sure it will be on vmiOne.Status.Interfaces[1] ?
> > Order until now could be changed in VMI status
> 
> ack, will add a check
> 
> > You need Eventually here, please see test 3985 or your PR which fixes the race, else you might have the race condition between the GA and the VMI status.
> 
> The MAC is not taken from Guest Agent is taken from libvirt domxml so there is no need for Eventually.

But the status might not be "ready" yet, since `WaitUntilVMIReady` just wait for AgentConnected,
which in turn just start the pollers, but it doesn't mean the status has already been updated.

File: tests/vmi_multus_test.go (hunk 43 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1237]: Done

File: tests/vmi_multus_test.go (hunk 44 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:1250]: Done

File: tests/vmi_multus_test.go [hunk 46]
```diff
@@ -375,32 +375,37 @@ var _ = Describe("[Serial]Multus", func() {
...
+				Expect(console.RunCommand(vmiOne, fmt.Sprintf("ip link show eth0 | grep -i \"%s\" | wc -l\n", customMacAddress), 15)).To(Succeed(), "should should set linux bridge interface with the custom MAC address at VMI")
```
Comment (oshoval) [inline tests/vmi_multus_test.go:408]: i dont think we should use the command, i would suggest please to do something as Alon did, poll the VMI status until it has the info.
Using the feature as VMI status, will give e2e coverage and would allow us to find problems.
"Low level" access skip some e2e testing imo

File: tests/vmi_multus_test.go (hunk 45 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:407]: Mac is not taken from guest agent we don't need to wait for guest agent that's why I removed it.

File: tests/vmi_multus_test.go (hunk 46 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:408]: I have already this discussion offline with @AlonaKaplan mac address is not taken from guest agent so we have to be sure that the guest is having the mac.

File: tests/vmi_multus_test.go (hunk 45 above)
Comment (oshoval) [reply tests/vmi_multus_test.go:407]: > Mac is not taken from guest agent we don't need to wait for guest agent that's why I removed it.

Mac is part of the reported part of guest agent for SRIOV for example, hence prone to the races,
and it should go all the way to VMI.status from what i understand.

```
{"return":[{"name":"lo","ip-addresses":[{"ip-address-type":"ipv4","ip-address":"127.0.0.1","prefix":8},{"ip-address-type":"ipv6","ip-address":"::1","prefix":128}],"statistics":{"tx-packets":0,"tx-errs":0,"rx-bytes":0,"rx-dropped":0,"rx-packets":0,"rx-errs":0,"tx-bytes":0,"tx-dropped":0},"hardware-address":"00:00:00:00:00:00"},{"name":"eth0","ip-addresses":[{"ip-address-type":"ipv4","ip-address":"10.0.2.2","prefix":24},{"ip-address-type":"ipv6","ip-address":"fe80::ff:feb4:ee86","prefix":64}],"statistics":{"tx-packets":13474,"tx-errs":0,"rx-bytes":123253841,"rx-dropped":0,"rx-packets":86812,"rx-errs":0,"tx-bytes":961261,"tx-dropped":0},"hardware-address":"02:00:00:b4:ee:86"},{"name":"eth1","hardware-address":"fe:00:a6:75:3b:b7"}]}
```

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/e8f12326fe27a343fbbd6db7500a644971cf9ded..339dbd95a83567f88233fa299c2b046b140bcb1a): Address @alonSadan  comments

File: tests/vmi_multus_test.go (hunk 46 above)
Comment (oshoval) [reply tests/vmi_multus_test.go:408]: See here please
https://github.com/kubevirt/kubevirt/pull/4448#discussion_r529412328
Mac is reported by guest agent, with all the derivations which are:
We should check it (even if not on this PR, we already check for example on test_id:3985).
Its prone for a race between test and Ga.
If we check, we should not use console imo, but just the VMI status, as this is the feature under testing.

File: tests/vmi_multus_test.go (hunk 45 above)
Comment (EdDev) [reply tests/vmi_multus_test.go:407]: This is not the case with non-sriov ifaces, so why we should do it here?

File: tests/vmi_multus_test.go (hunk 46 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:408]: I have to find the source code but looks like we are ignoring MAC from guest agent and setting the one at libvirt domxml at least for linux bridge CNI for SRIOV it may be different.

Comment (EdDev) [reply tests/vmi_multus_test.go]: This is incorrect for this setup, please review the production code to confirm the answer quique provided earlier.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/pull/4448#discussion_r529412328): Addressing @oshoval comments

File: tests/vmi_multus_test.go (hunk 45 above)
Comment (oshoval) [reply tests/vmi_multus_test.go]: Lost the code line, because it was updated since,
is it a secondary interface with bridge binding ?
if so it is also reported by GA i think ?
else you are right

File: tests/vmi_multus_test.go (hunk 46 above)
Comment (oshoval) [reply tests/vmi_multus_test.go]: > I have to find the source code but looks like we are ignoring MAC from guest agent and setting the one at libvirt domxml at least for linux bridge CNI for SRIOV it may be different, but still I am going to wait for guest agent and use @alonSadan helpers.

Ok thanks, i understand (since it takes from `domain.Spec.Devices.Interfaces`)
Btw, not part of this PR:
Ignoring the MAC from guest agent maybe should have an offline discussion if this is the right behavior,
as it looks on the Spec, without verifying actual GA, and update the VMI status accordingly as you said.

File: tests/vmi_multus_test.go [hunk 47]
```diff
@@ -375,32 +375,48 @@ var _ = Describe("[Serial]Multus", func() {
...
+				tests.WaitAgentConnected(virtClient, vmiTwo)
+
+				var interfaceName string
+				Eventually(func() error {
+					var err error
+					vmiOne, err = virtClient.VirtualMachineInstance(vmiOne.Namespace).Get(vmiOne.Name, &metav1.GetOptions{})
+					Expect(err).NotTo(HaveOccurred())
+					interfaceName, err = getInterfaceNameByMAC(vmiOne, customMacAddress)
+					return err
+				}, 140*time.Second, 5*time.Second).Should(Succeed())
```
Comment (EdDev) [inline tests/vmi_multus_test.go:415]: I do not understand this one.
- Why do we need it at all?
- Whey do we need a retry here?

Comment (qinqon) [reply tests/vmi_multus_test.go:415]: > Why do we need it at all?
The order of interfaces at vmiOne.Status.Interfaces can change so we need to search in them to get the proper interface name, @alonSadan put in place some nice helpers to do so.

> Whey do we need a retry here?
Interface name depends on Guest Agent and we know it takes some time for it to kick in.

Comment (oshoval) [reply tests/vmi_multus_test.go:415]: I think that since i mixed here, and it disregard GA as you said, 
both of the issues won't occur ?

Comment (EdDev) [reply tests/vmi_multus_test.go:415]: > The order of interfaces at vmiOne.Status.Interfaces can change so we need to search in them to get the proper interface name, @alonSadan put in place some nice helpers to do so.

We enforce the name-mac pair with cloud-init, so looking for the iface name to match the mac is not needed.

> 
> > Whey do we need a retry here?
> 
> Interface name depends on Guest Agent and we know it takes some time for it to kick in.

Interesting, I am not sure this is true or not, but the previous answer may make it irrelevant anyway.
(i.e what happens if GA is not there, we do not report iface name?)

Comment (qinqon) [reply tests/vmi_multus_test.go:415]: @oshoval going to put back my original code with the twist of using the network name as the interface name.

**Comment by qinqon** [comment]
force-push: Still using @alonSadan helpers but not retrieving interfaceName from status since we can force it to whatever we want at cloud init.

File: tests/vmi_multus_test.go [hunk 48]
```diff
@@ -375,32 +375,39 @@ var _ = Describe("[Serial]Multus", func() {
...
+				tests.WaitAgentConnected(virtClient, vmiTwo)
 
 				By("Verifying the desired custom MAC is the one that were actually configured on the interface.")
-				ipLinkShow := fmt.Sprintf("ip link show eth0 | grep -i \"%s\" | wc -l\n", customMacAddress)
-				err = console.SafeExpectBatch(vmiOne, []expect.Batcher{
-					&expect.BSnd{S: ipLinkShow},
-					&expect.BExp{R: "1"},
-				}, 15)
-				Expect(err).ToNot(HaveOccurred())
+				Expect(getInterfaceNameByMAC(vmiOne, customMacAddress)).To(Equal(linuxBridgeInterfaceWithCustomMac.Name), "should set linux bridge interface with the custom MAC address at VMI Status")
```
Comment (EdDev) [inline tests/vmi_multus_test.go:409]: - I think you need to re-fetch the vmiOne object before all these asserts.
- I would expect the tests to show that we do not need a mac lookup:

```
vmiIfaceStatusByName := indexVMIInterfacesStatusByName(vmiOne)
Expect(vmiIfaceStatusByName).To(ContainElement(linuxBridgeInterfaceWithCustomMac.Name))
Expect(vmiIfaceStatusByName[linuxBridgeInterfaceWithCustomMac.Name].MAC)To(Equal(customMacAddress))
```

File: tests/vmi_multus_test.go [hunk 49]
```diff
@@ -375,32 +375,39 @@ var _ = Describe("[Serial]Multus", func() {
...
+				Expect(checkMacAddress(vmiOne, linuxBridgeInterfaceWithCustomMac.Name, customMacAddress)).To(Succeed(), "should should set linux bridge interface with the custom MAC address at VMI")
```
Comment (EdDev) [inline tests/vmi_multus_test.go:410]: typo: double `should`.

File: tests/vmi_multus_test.go (hunk 48 above)
Comment (qinqon) [reply tests/vmi_multus_test.go]: Done

File: tests/vmi_multus_test.go (hunk 49 above)
Comment (qinqon) [reply tests/vmi_multus_test.go]: Done

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/ad940471b07fea52dcd16182764b1c2175fb4da8..c441536f60a7ef05cf654d838ba1ec2ccd48a08e): Introduce `libvmi.GetInterfaceStatusByName` to address last @EdDev comments, not sure we need to use `Eventually` there.

File: tests/libvmi/status.go [hunk 50]
```diff
@@ -38,3 +38,15 @@ func GetPodByVirtualMachineInstance(vmi *v1.VirtualMachineInstance, namespace st
 
 	return controlledPod
 }
+
+func GetInterfaceStatusByName(vmi *v1.VirtualMachineInstance) (map[string]v1.VirtualMachineInstanceNetworkInterface, error) {
+	if vmi == nil {
+		return nil, fmt.Errorf("failed GetInterfaceStatusByName vmi is nil")
+	}
```
Comment (EdDev) [inline tests/libvmi/status.go:45]: The error is of the caller and not the operation of this function.
I would recommend to avoid this defensive pattern in general.

File: tests/libvmi/status.go [hunk 51]
```diff
@@ -38,3 +38,15 @@ func GetPodByVirtualMachineInstance(vmi *v1.VirtualMachineInstance, namespace st
 
 	return controlledPod
 }
+
+func GetInterfaceStatusByName(vmi *v1.VirtualMachineInstance) (map[string]v1.VirtualMachineInstanceNetworkInterface, error) {
```
Comment (EdDev) [inline tests/libvmi/status.go:42]: This hints it is a getter, but it is an indexer.
Can you replace `Get` with `Index` ?

File: tests/vmi_multus_test.go [hunk 52]
```diff
@@ -375,32 +375,41 @@ var _ = Describe("[Serial]Multus", func() {
...
+					libvmi.WithInterface(linuxBridgeInterfaceWithCustomMac),
+					libvmi.WithNetwork(&linuxBridgeNetwork),
+					libvmi.WithCloudInitNoCloudUserData(tests.GetGuestAgentUserData(), false),
+					libvmi.WithCloudInitNoCloudNetworkData(cloudInitNetworkDataWithStaticIPsByMac(linuxBridgeInterfaceWithCustomMac.Name, customMacAddress, "10.1.1.1/24"), false))
+				vmiOne = tests.StartVmOnNode(vmiOne, nodes.Items[0].Name)
+
+				vmiOne = tests.WaitUntilVMIReady(vmiOne, console.LoginToFedora)
+				tests.WaitAgentConnected(virtClient, vmiOne)
+				vmiTwo = tests.WaitUntilVMIReady(vmiTwo, console.LoginToFedora)
+				tests.WaitAgentConnected(virtClient, vmiTwo)
```
Comment (EdDev) [inline tests/vmi_multus_test.go:406]: vmiTwo object is not needed anymore from this point and waiting to the agent is for sure redundant.
Perhaps it will be better to relocate it under the "ping" `By` section to show its relevance.

File: tests/vmi_multus_test.go [hunk 53]
```diff
@@ -375,32 +375,41 @@ var _ = Describe("[Serial]Multus", func() {
...
 
 				By("Verifying the desired custom MAC is the one that were actually configured on the interface.")
-				ipLinkShow := fmt.Sprintf("ip link show eth0 | grep -i \"%s\" | wc -l\n", customMacAddress)
-				err = console.SafeExpectBatch(vmiOne, []expect.Batcher{
-					&expect.BSnd{S: ipLinkShow},
-					&expect.BExp{R: "1"},
-				}, 15)
-				Expect(err).ToNot(HaveOccurred())
+				vmiIfaceStatusByName, err := libvmi.GetInterfaceStatusByName(vmiOne)
+				Expect(err).ToNot(HaveOccurred(), "should successfully index the VMI network interface status by name")
```
Comment (EdDev) [inline tests/vmi_multus_test.go:410]: If you use a VMI "get" and check it has no error it will look much better IMO.
You are right that the returned object from `WaitUntilVMIReady` is enough, but for consistency I would recommend an explicit get here nevertheless. But it is not a must, whatever you prefer.

BTW, I think it is unlikely `vmiOne` to even be `nil` at this point, as that will cause the waiting part to explode.

File: tests/libvmi/status.go (hunk 51 above)
Comment (qinqon) [reply tests/libvmi/status.go:42]: Done

File: tests/libvmi/status.go (hunk 50 above)
Comment (qinqon) [reply tests/libvmi/status.go:45]: Ok, removing the check.

File: tests/vmi_multus_test.go (hunk 52 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:406]: Done

File: tests/vmi_multus_test.go (hunk 53 above)
Comment (qinqon) [reply tests/vmi_multus_test.go:410]: I prefer to just use the vmi from `WaitUntilVMIReady`.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/c441536f60a7ef05cf654d838ba1ec2ccd48a08e..839f6a5bfb86ea6f7bba50fd4d44c9f7f6a002c5): nits from @EdDev

**Review by EdDev — APPROVED** [review]
Thank you!

**Comment by EdDev** [comment]
> /hold sriov has to be ok

SRIOV should be good now.
/hold cancel

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/839f6a5bfb86ea6f7bba50fd4d44c9f7f6a002c5..61dc8b105baf405ed1596643c2e9198db2015083): Use HaveKey instead of Contains to fix the test.
[force-push](https://github.com/kubevirt/kubevirt/compare/61dc8b105baf405ed1596643c2e9198db2015083..0b73439e4aace27c9bbc0234b9382eac6f8ab469): rebase

**Review by EdDev — APPROVED** [review]

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/0b73439e4aace27c9bbc0234b9382eac6f8ab469..bf876200c7c25b85e4fadcee01c834df2b53700d): Removed .log file

**Comment by phoracek** [comment]
/approve
/lgtm

Really nice.

**Comment by qinqon** [comment]
/hold

Again the issue with namespace at SRIOV lane https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4448/pull-kubevirt-e2e-kind-1.17-sriov/1331538968642064384

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/bf876200c7c25b85e4fadcee01c834df2b53700d..3e7e5037029383bc4c86cdb19e4b6ffe177a49fc):  `vmi.Namespace` is not filled in at `.Create` that was breaking SRIOV lane.

**Comment by phoracek** [comment]
The change matches the approach taken in `startVmi` and is minimal. Raising lgtm again.

/lgtm

**Comment by EdDev** [comment]
> [force-push](https://github.com/kubevirt/kubevirt/compare/bf876200c7c25b85e4fadcee01c834df2b53700d..3e7e5037029383bc4c86cdb19e4b6ffe177a49fc): `vmi.Namespace` is not filled in at `.Create` that was breaking SRIOV lane.

It is filled with `Create`. The problem is due to `startVMI` that is not updating it (so the caller will get the update). :/
It is sad, but we will have to solve it in a following change.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/3e7e5037029383bc4c86cdb19e4b6ffe177a49fc..ddcf826557821ace6f59f1189b0d294609e2d364): More empty namespaces

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4448/pull-kubevirt-e2e-kind-1.17-sriov/1331569922983071746

**Comment by qinqon** [comment]
/hold cancel 
sriov failures re not related 
```
Can't connect to websocket (301): websocket: bad handshake\n
```

**Comment by qinqon** [comment]
/hold
The webhook handshake issue is related to this PR.

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/ddcf826557821ace6f59f1189b0d294609e2d364..7a7324b45d4c538f9a90dc163286457889ed39f6): fixed rebase after https://github.com/kubevirt/kubevirt/pull/4217 merged

**Comment by qinqon** [comment]
[force-push](https://github.com/kubevirt/kubevirt/compare/7a7324b45d4c538f9a90dc163286457889ed39f6..fa0712a87395889336d84691353e7ff7e32e3858): Fix webhook handshake issue

**Comment by qinqon** [comment]
/hold cancel

SRIOV lane is green https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4448/pull-kubevirt-e2e-kind-1.17-sriov/1331918476075339777
