### PR TITLE
Use nftable rules for coreOS servers on masquerade

### LINKED ISSUE #2400: iptables on OKD
We fail to configure iptables on OKD since they are not initialized on the host (and maybe we are also missing some kernel modules). I think we have two options: Enable and initialize iptables on OKD host **or** use nftables in case we run on OKD.

```
{"component":"virt-launcher","level":"error","msg":"failed to create nat rules for vm error: running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64\niptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","pos":"podinterface.go:435","timestamp":"2019-06-19T14:29:18.393389Z"} {"component":"virt-launcher","level":"fatal","msg":"failed to prepared pod networking","pos":"podinterface.go:88","reason":"running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64\niptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.\n","timestamp":"2019-06-19T14:29:18.393440Z"} panic: running [/usr/sbin/iptables -t nat -N KUBEVIRT_PREINBOUND --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.1.2.el8_0.x86_64 iptables v1.6.2: can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded. goroutine 69 [running]: kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*PodInterface).Plug(0x22a98b0, 0xc000740300, 0xc00014e630, 0xc00034bbf0, 0xc000330000, 0x14dec7d, 0x4, 0x10, 0x12f7140) pkg/virt-launcher/virtwrap/network/podinterface.go:89 +0x536 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.SetupNetworkInterfaces(0xc000740300, 0xc000330000, 0x0, 0x0) pkg/virt-launcher/virtwrap/network/network.go:83 +0x520 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).preStartHook(0xc0004a9340, 0xc000740300, 0xc000330000, 0x1698e00, 0x0, 0x166c820) pkg/virt-launcher/virtwrap/manager.go:728 +0x3ad kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).SyncVMI(0xc0004a9340, 0xc000740300, 0xc0003ca900, 0x0, 0x0, 0x0) pkg/virt-launcher/virtwrap/manager.go:881 +0x5e2 kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server.(*Launcher).SyncVirtualMachine(0xc00001c460, 0x1686540, 0xc00034acf0, 0xc00034ad20, 0xc00001c460, 0xc00034ac60, 0x135df40) pkg/virt-launcher/virtwrap/cmd-server/server.go:159 +0x81 kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1._Cmd_SyncVirtualMachine_Handler(0x1426cc0, 0xc00001c460, 0x1686540, 0xc00034acf0, 0xc00073eb40, 0x0, 0x0, 0x0, 0xc000582b00, 0x55c) bazel-out/k8-fastbuild/bin/pkg/handler-launcher-com/cmd/v1/linux_amd64_stripped/kubevirt_cmd_go_proto%!/(MISSING)kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1/cmd.pb.go:515 +0x23e google.golang.org/grpc.(*Server).processUnaryRPC(0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300, 0xc00049d2c0, 0x21e5760, 0x0, 0x0, 0x0) external/org_golang_google_grpc/server.go:971 +0x4a2 google.golang.org/grpc.(*Server).handleStream(0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300, 0x0) external/org_golang_google_grpc/server.go:1250 +0xd61 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000018320, 0xc00046af00, 0x1692140, 0xc00055e180, 0xc000734300) external/org_golang_google_grpc/server.go:690 +0x9f created by google.golang.org/grpc.(*Server).serveStreams.func1 external/org_golang_google_grpc/server.go:688 +0xa1 {"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:558","reason":"exit status 2","time
```

Kudos to @cynepco3hahue for reporting the issue.

### PR DESCRIPTION
**Pull request by SchSeba**
Use nftable rules for coreOS servers on masquerade

This PR check if iptables are enable and if not use nftables to configure rules for the masquerade interface binding.

related to: 
* https://github.com/kubevirt/libvirt/pull/26
* https://github.com/kubevirt/kubevirt/pull/2428

Fixes #2400

**Special notes for your reviewer**:

**Release note**:

```release-note
support nftable for coreOS
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/2430)

### CODE REVIEW

File: pkg/virt-launcher/virtwrap/network/common.go [hunk 1]
```diff
@@ -138,6 +154,26 @@ func (h *NetworkUtilsHandler) IptablesAppendRule(table, chain string, rulespec .
 
 	return iptablesObject.Append(table, chain, rulespec...)
 }
+func (h *NetworkUtilsHandler) NftablesNewChain(table, chain string) error {
+	output, err := exec.Command("nft", "add", "chain", "ip", table, chain).CombinedOutput()
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/network/common.go]: did you look into using this package instead of forking child processes for nft? https://github.com/google/nftables

File: pkg/virt-launcher/virtwrap/network/podinterface.go [hunk 2]
```diff
@@ -516,7 +516,13 @@ func (p *MasqueradePodInterface) createBridge() error {
 }
 
 func (p *MasqueradePodInterface) createNatRules() error {
+	if Handler.UseIptables() == nil {
+		return p.createNatRulesUsingIptables()
+	}
+	return p.createNatRulesUsingNftable()
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/network/podinterface.go]: should usage of nftable actually be the default, and iptables be the fallback?

File: pkg/virt-launcher/virtwrap/network/podinterface.go [hunk 3]
```diff
@@ -593,7 +599,83 @@ func (p *MasqueradePodInterface) createNatRules() error {
...
+	return nil
+}
+
+func (p *MasqueradePodInterface) createNatRulesUsingNftable() error {
+	err := Handler.NftablesLoad("ipv4-nat")
+	if err != nil {
+		return err
+	}
+
+	err = Handler.NftablesNewChain("nat", "KUBEVIRT_PREINBOUND")
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/network/podinterface.go]: are all the functions here idempotent? meaning if "createNatRulesUsingNftable()" happens to get called multiple times during startup, will this logic not cause any errors?

**Comment by SchSeba** [comment]
Hi @davidvossel thanks for the comments

>Do we have any ci lanes that use nftables yet? or do we need to enable an okd lane before this is possible?

yes we need to wait for the okd-4.1 lane to test it here. I test it locally

> I'd be in favor of removing the oc-3.11 lanes and introducing okd-4.1

I am not sure this is a good idea.
There are a lot of ocp 3.11 user that probably want to use kubevirt and as we already saw there is a big different between the two versions I think we should test on both for now.

File: pkg/virt-launcher/virtwrap/network/podinterface.go (hunk 3 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/podinterface.go]: yes you can call this as many times as you want without returning any error.

File: pkg/virt-launcher/virtwrap/network/common.go (hunk 1 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/common.go]: I try to use this package but I have some issues with it:
1. It's not recommended as production
2. It's a very complex package in my opinion for the easy task the we need here.

File: pkg/virt-launcher/virtwrap/network/podinterface.go (hunk 2 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/podinterface.go]: I don't think so. If iptables are enable in the host and we configure nftables it will not work ( it will let you configure the nftables but they will not work).

I wrote it this way so if we have an error in the iptables this mean the host is using nftables.

File: pkg/virt-launcher/virtwrap/network/common.go (hunk 1 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/network/common.go]: alrighty, just wanted to make sure it was investigated.

**Comment by davidvossel** [comment]
> There are a lot of ocp 3.11 user that probably want to use kubevirt and as we already saw there is a big different between the two versions I think we should test on both for now.

I'm only aware of the downstream CNV use case for ocp 3.11, and that is not tracking kubevirt master anymore.

**Comment by phoracek** [comment]
> I'm only aware of the downstream CNV use case for ocp 3.11, and that is not tracking kubevirt master anymore.

@davidvossel just curious. OpenShift is upstream too and may have users. Shoudn't we keep it (at least for a while)? Also, why do we still run Kubernetes 1.11.0?

**Comment by SchSeba** [comment]
@davidvossel @rmohr @fabiand @cynepco3hahue can you please take another look on this PR

I just add the related packages and install nftable using bazel instead of update the libvirt image.

**Comment by davidvossel** [comment]
>@davidvossel just curious. OpenShift is upstream too and may have users. Shoudn't we keep it (at least for a while)? Also, why do we still run Kubernetes 1.11.0?

we'll likely be dropping k8s 1.11.0 from the test matrix soon as well. There are CRD features related to versioning we'd like to take advantage of soon that are not stable in k8s versions < 1.13.x. We'll see though :) There will be a discussion before anything happens.

File: pkg/virt-launcher/virtwrap/network/common.go [hunk 4]
```diff
@@ -122,6 +128,16 @@ func (h *NetworkUtilsHandler) AddrAdd(link netlink.Link, addr *netlink.Addr) err
 func (h *NetworkUtilsHandler) LinkSetMaster(link netlink.Link, master *netlink.Bridge) error {
 	return netlink.LinkSetMaster(link, master)
 }
+func (h *NetworkUtilsHandler) UseIptables() error {
```
Comment (booxter) [inline pkg/virt-launcher/virtwrap/network/common.go]: returning an error for a function that gives a binary answer is not ideal. consider returning a `bool` instead.

File: pkg/virt-launcher/virtwrap/network/common.go [hunk 5]
```diff
@@ -138,6 +154,26 @@ func (h *NetworkUtilsHandler) IptablesAppendRule(table, chain string, rulespec .
 
 	return iptablesObject.Append(table, chain, rulespec...)
 }
+func (h *NetworkUtilsHandler) NftablesNewChain(table, chain string) error {
```
Comment (booxter) [inline pkg/virt-launcher/virtwrap/network/common.go]: this function always returns nil, even if the backend will fail to add the chain. is it really your intention? I think we should return nil only when we are sure that the chain is present (either b/c it existed before we called the function, or b/c we created it). Otherwise we should know that an error occurred.

File: pkg/virt-launcher/virtwrap/network/common.go [hunk 6]
```diff
@@ -138,6 +154,26 @@ func (h *NetworkUtilsHandler) IptablesAppendRule(table, chain string, rulespec .
...
+}
+func (h *NetworkUtilsHandler) NftablesAppendRule(table, chain string, rulespec ...string) error {
+	cmd := append([]string{"add", "rule", "ip", table, chain}, rulespec...)
+	return exec.Command("nft", cmd...).Run()
+}
+func (h *NetworkUtilsHandler) NftablesNewTable(table string) error {
+	return exec.Command("nft", "add", "table", table).Run()
+}
+func (h *NetworkUtilsHandler) NftablesLoad(fnName string) error {
+	return exec.Command("nft", "-f", fmt.Sprintf("/etc/nftables/%s.nft", fnName)).Run()
```
Comment (booxter) [inline pkg/virt-launcher/virtwrap/network/common.go]: just curious: who creates the file inside launcher pod? why do we need to load it?

**Comment by fabiand** [comment]
Something wrong with the PR maybe?

**Comment by SchSeba** [comment]
Yes I know I am working to make it ready for another review.

File: pkg/virt-launcher/virtwrap/network/common.go (hunk 6 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/common.go]: the nftable package create the files.

this is the file we use it's a base line for the nat table equals to `iptables -t nat`
```bash
#!/usr/sbin/nft -f

table filter {
	chain input		{ type filter hook input priority 0; }
	chain forward		{ type filter hook forward priority 0; }
	chain output		{ type filter hook output priority 0; }
}
```

File: pkg/virt-launcher/virtwrap/network/common.go (hunk 5 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/common.go]: nice catch!

File: pkg/virt-launcher/virtwrap/network/common.go (hunk 4 above)
Comment (SchSeba) [reply pkg/virt-launcher/virtwrap/network/common.go]: done

File: pkg/virt-launcher/virtwrap/network/podinterface.go [hunk 7]
```diff
@@ -516,7 +516,13 @@ func (p *MasqueradePodInterface) createBridge() error {
 }
 
 func (p *MasqueradePodInterface) createNatRules() error {
+	if Handler.UseIptables() {
+		return p.createNatRulesUsingIptables()
+	}
+	return p.createNatRulesUsingNftable()
```
Comment (phoracek) [inline pkg/virt-launcher/virtwrap/network/podinterface.go]: Naming is not consistent. createNatRulesUsingIptable**s** vs createNatRulesUsingNFtable. Just a nit if you find other problems, I don't think it's worth running all tests again.

**Comment by cynepco3hahue** [comment]
@SchSeba I rebuild the OKD image because of kubelet certificate valid only for one month.

File: pkg/virt-launcher/virtwrap/network/podinterface_test.go [hunk 8]
```diff
@@ -426,6 +435,50 @@ var _ = Describe("Pod Network", func() {
...
+					"dnat",
+					"to", "10.0.2.2").Return(nil).AnyTimes()
+
+				domain := NewDomainWithBridgeInterface()
+				vm := newVMIMasqueradeInterface("testnamespace", "testVmName")
+
+				api.SetObjectDefaults_Domain(domain)
+				TestPodInterfaceIPBinding(vm, domain)
+			})
+			It("should define a new VIF bind to a bridge and create a specific nat rule using nftable", func() {
```
Comment (booxter) [inline pkg/virt-launcher/virtwrap/network/podinterface_test.go]: nit: nftables

**Comment by cynepco3hahue** [comment]
I ran tests locally on okd-4.1.7 and it works fine, it still has failures(migration, configuration, and data volume), but it not connected to this PR.
