### PR TITLE
pool: support secret ref indexing for CloudInit volumes

### LINKED ISSUE #15810: VirtualMachinePool appendIndexToSecretRefs Does Not Work for cloudInitNoCloud Secret References
**What happened**:

When using `VirtualMachinePool` with `spec.nameGeneration.appendIndexToSecretRefs: true`, the index is NOT appended to secret references in `cloudInitNoCloud.secretRef` and `cloudInitNoCloud.networkDataSecretRef` fields.

The VMs created by the pool all reference the same base secret name without the index suffix (e.g., `test-userdata` instead of `test-userdata-0`, `test-userdata-1`), causing all VMs to attempt to use the same cloud-init configuration. Since the base secret names without indices don't exist (only the indexed versions exist), the VMs fail to properly initialize with cloud-init data.

**What you expected to happen**:

When `appendIndexToSecretRefs: true` is set in a VirtualMachinePool, secret references in `cloudInitNoCloud.secretRef` and `cloudInitNoCloud.networkDataSecretRef` should have the VM's sequential index appended to the secret name.

For example:
- VMPool template references: `secretRef.name: "test-userdata"` and `networkDataSecretRef.name: "test-networkdata"`
- VM 0 should reference: `secretRef.name: "test-userdata-0"` and `networkDataSecretRef.name: "test-networkdata-0"`
- VM 1 should reference: `secretRef.name: "test-userdata-1"` and `networkDataSecretRef.name: "test-networkdata-1"`

This would allow each VM in the pool to have unique cloud-init configuration (different hostnames, IP addresses, SSH keys, etc.) as documented in the KubeVirt user guide.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create indexed cloud-init secrets for each VM in the pool:

```yaml
---
# Indexed cloud-init userdata secret for VM 0
apiVersion: v1
kind: Secret
metadata:
  name: test-userdata-0
  namespace: default
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: test-pool-0
    user: almalinux
    password: almalinux
    chpasswd:
      expire: false
    ssh_pwauth: true
    disable_root: false

---
# Indexed cloud-init networkdata secret for VM 0
apiVersion: v1
kind: Secret
metadata:
  name: test-networkdata-0
  namespace: default
type: Opaque
stringData:
  networkdata: |
    version: 2
    ethernets:
      eth0:
        dhcp4: true

---
# Indexed cloud-init userdata secret for VM 1
apiVersion: v1
kind: Secret
metadata:
  name: test-userdata-1
  namespace: default
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: test-pool-1
    user: almalinux
    password: almalinux
    chpasswd:
      expire: false
    ssh_pwauth: true
    disable_root: false

---
# Indexed cloud-init networkdata secret for VM 1
apiVersion: v1
kind: Secret
metadata:
  name: test-networkdata-1
  namespace: default
type: Opaque
stringData:
  networkdata: |
    version: 2
    ethernets:
      eth0:
        dhcp4: true
```

2. Create a VirtualMachinePool with `appendIndexToSecretRefs: true`:

```yaml
---
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: test-pool
  namespace: default
spec:
  replicas: 2
  nameGeneration:
    appendIndexToSecretRefs: true
  selector:
    matchLabels:
      kubevirt.io/vmpool: test-pool
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: test-pool
    spec:
      runStrategy: Always
      instancetype:
        kind: VirtualMachineClusterInstancetype
        name: u1.medium
      preference:
        kind: VirtualMachineClusterPreference
        name: rhel.9
      dataVolumeTemplates:
      - metadata:
          name: bootdisk
        spec:
          pvc:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: longhorn-vm-sc
          source:
            pvc:
              name: almalinux-9-base
              namespace: default
      template:
        spec:
          domain:
            devices: {}
          volumes:
          - name: bootdisk
            dataVolume:
              name: bootdisk
          - name: cloudinitdisk
            cloudInitNoCloud:
              secretRef:
                name: test-userdata
              networkDataSecretRef:
                name: test-networkdata
```

3. Check the created VMs' volume configurations:

```bash
kubectl get vm test-pool-0 -n default -o jsonpath='{.spec.template.spec.volumes}' | jq
kubectl get vm test-pool-1 -n default -o jsonpath='{.spec.template.spec.volumes}' | jq
```

**Actual Result:**

VM test-pool-0:
```json
[
  {
    "dataVolume": {
      "name": "bootdisk-0"
    },
    "name": "bootdisk"
  },
  {
    "cloudInitNoCloud": {
      "networkDataSecretRef": {
        "name": "test-networkdata"
      },
      "secretRef": {
        "name": "test-userdata"
      }
    },
    "name": "cloudinitdisk"
  }
]
```

VM test-pool-1:
```json
[
  {
    "dataVolume": {
      "name": "bootdisk-1"
    },
    "name": "bootdisk"
  },
  {
    "cloudInitNoCloud": {
      "networkDataSecretRef": {
        "name": "test-networkdata"
      },
      "secretRef": {
        "name": "test-userdata"
      }
    },
    "name": "cloudinitdisk"
  }
]
```

**Observations:**
- ❌ Cloud-init secret references are NOT indexed: both VMs reference `test-userdata` and `test-networkdata` (without index)

**Expected Result:**

VM test-pool-0 should reference:
- `secretRef.name: "test-userdata-0"`
- `networkDataSecretRef.name: "test-networkdata-0"`

VM test-pool-1 should reference:
- `secretRef.name: "test-userdata-1"`
- `networkDataSecretRef.name: "test-networkdata-1"`

**Additional context**:

This bug prevents using VirtualMachinePool for VMs that require unique cloud-init configurations (different hostnames, static IP addresses, SSH keys, etc.). The feature is documented in the KubeVirt user guide (https://kubevirt.io/user-guide/user_workloads/pool/#using-unique-cloudinit-and-configmap-volumes-with-virtualmachinepools) but does not work for cloud-init secret references.

It appears the code path that processes `cloudInitNoCloud.secretRef` and `cloudInitNoCloud.networkDataSecretRef` fields does not apply the index transformation when `appendIndexToSecretRefs: true` is set. https://github.com/kubevirt/kubevirt/commit/e23fdb373aac73c9b4d75713f4533ad195f7694f
https://github.com/kubevirt/kubevirt/blame/main/pkg/virt-controller/watch/pool/pool.go#L692-L719
@0xFelix 

**Environment**:
- KubeVirt version (use `virtctl version`): v1.5.0 (GitCommit: 522b44c0ce8d1909618324cb083d69e5c7a0a234)
- Kubernetes version (use `kubectl version`): v1.33.4+rke2r1
- VM or VMI specifications: shared above
- Cloud provider or hardware configuration: Bare metal RKE2 cluster
- OS (e.g. from /etc/os-release): AlmaLinux 9 based VMs
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A

### PR DESCRIPTION
**Pull request by frank-gen**
#### Before this PR:
   When using `VirtualMachinePool` with `spec.nameGeneration.appendIndexToSecretRefs: true`, the index was NOT appended to secret references in `cloudInitNoCloud.secretRef`, `cloudInitNoCloud.networkDataSecretRef`,
   `cloudInitConfigDrive.userDataSecretRef`, and `cloudInitConfigDrive.networkDataSecretRef` fields.
   This caused all VMs in the pool to reference the same base secret names (e.g., `test-userdata` instead of `test-userdata-0`, `test-userdata-1`), preventing each VM from having unique cloud-init configurations. Since only the indexed secret names
   existed, VMs would fail to properly initialize with cloud-init data.
   #### After this PR:
   When `appendIndexToSecretRefs: true` is set in a VirtualMachinePool, secret references in CloudInit volumes now correctly have the VM's sequential index appended to the secret name:
   - VM 0 references: `test-userdata-0`, `test-networkdata-0`
   - VM 1 references: `test-userdata-1`, `test-networkdata-1`
   - VM 2 references: `test-userdata-2`, `test-networkdata-2`
   This allows each VM in the pool to have unique cloud-init configurations (different hostnames, IP addresses, SSH keys, etc.) as documented in the KubeVirt user guide.
   ### References
   - Fixes #15810
   ### Why we need it and why it was done in this way
   - Fixes #15810
   ### Special notes for your reviewer
   - The fix adds support for both `CloudInitNoCloud` and `CloudInitConfigDrive` volume types
   - Each volume type supports both `UserDataSecretRef` and `NetworkDataSecretRef` indexing
   ### Checklist
   This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
   Approvers are expected to review this list.
   - [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
   - [x] PR: The PR description is expressive enough and will help future contributors
   - [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
   - [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
   - [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
   - [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
   - [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
   - [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
   ### Release note
   
```release-note
VirtualMachinePool now correctly appends index to CloudInit secret references when appendIndexToSecretRefs: true is set, enabling unique cloud-init configurations for each VM in the pool.
```

### CODE REVIEW

File: pkg/virt-controller/watch/pool/pool.go [hunk 1]
```diff
@@ -715,6 +715,20 @@ func indexVMSpec(poolSpec *poolv1.VirtualMachinePoolSpec, idx int) *virtv1.Virtu
 			volume.VolumeSource.ConfigMap.Name += "-" + strconv.Itoa(idx)
 		} else if volume.VolumeSource.Secret != nil && appendIndexToSecretRefs {
 			volume.VolumeSource.Secret.SecretName += "-" + strconv.Itoa(idx)
+		} else if volume.VolumeSource.CloudInitNoCloud != nil && appendIndexToSecretRefs {
+			if volume.VolumeSource.CloudInitNoCloud.UserDataSecretRef != nil {
+				spec.Template.Spec.Volumes[i].CloudInitNoCloud.UserDataSecretRef.Name += "-" + strconv.Itoa(idx)
```
Comment (0xFelix) [inline pkg/virt-controller/watch/pool/pool.go]:
```suggestion
				volume.CloudInitNoCloud.UserDataSecretRef.Name += "-" + strconv.Itoa(idx)
```

Can you use `volume` here and in the lines below?

Comment (0xFelix) [reply pkg/virt-controller/watch/pool/pool.go]: On a side note: Might be worth constructing the suffix only once, i.e. `suffix := "-" + strconv.Itoa(idx)` above the for loop.

**Comment by frank-gen** [comment]
apology for the delay, will try to address the comments and provide an updated patch this week (if not next).

**Comment by 0xFelix** [comment]
No worries, the release note block needs to start with 

```
```release-note
```

File: pkg/virt-controller/watch/pool/pool.go (hunk 1 above)
Comment (frank-gen) [reply pkg/virt-controller/watch/pool/pool.go]: Hello Felix, I have integrated the suggested changes to the PR. Please advise if further changes are needed. Thanks

**Review by 0xFelix — COMMENTED** [review]
Thanks!

/approve
/cherry-pick release-1.7

PTAL @fossedihelm

**Comment by fossedihelm** [comment]
@frank-gen Can you please squash the commits, using rebase instead of merge? I'd expect only one commit. Thanks.

@Sreeja1725 @rthallisey  FYI

**Comment by frank-gen** [comment]
> @frank-gen Can you please squash the commits, using rebase instead of merge? I'd expect only one commit. Thanks.
> 
> @Sreeja1725 @rthallisey FYI

squashed as a single commit now.

**Comment by fossedihelm** [comment]
Thank you!
/lgtm
I would like to get feedback from @Sreeja1725 or @rthallisey 
/hold

**Comment by Sreeja1725** [comment]
Thank you
/lgtm
