### PR TITLE
instancetype: Do not overwrite EFI or BIOS with PreferredEfi

### LINKED ISSUE #12985: `PreferredEfi` applied when `BIOS` already enabled within `VirtualMachineInstanceSpec`
/area instancetype

**What happened**:
$subject, as with the now deprecated `PreferredUseEfi` this should only be used when the user hasn't already enabled `BIOS` within the `VirtualMachineInstanceSpec`.

**What you expected to happen**:
 As above.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to use a preference with `PreferredEfi` when the underlying `VirtualMachine` has `BIOS` enabled.

**Additional context**:

Raised downstream as https://github.com/kubevirt-ui/kubevirt-plugin/pull/2133 started to enable `BIOS` for all `VirtualMachines` created for that flow and resulted in both `BIOS` and `EFI` being enabled when using preferences that used `PreferredUseEfi`.

https://github.com/kubevirt-ui/kubevirt-plugin/blob/760f0d6b8ea44e070e5117a2cb5453c0228f65fb/src/views/catalog/CreateFromInstanceTypes/utils/utils.ts#L226-L274

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does
3a31137abe464d1560e9b693e91d311273ec69cd did not duplicate the original logic of PreferredUseEfi to ensure that we only apply PreferredEfi when a user has not provided their own EFI configuration *and* BIOS is additionally not enabled.

Fixes #12985 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
The `PreferredEfi` preference is now only applied when a user has not already enabled either `EFI` or `BIOS` within the underlying `VirtualMachine`.
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

File: pkg/instancetype/instancetype_test.go [hunk 1]
```diff
@@ -2228,6 +2228,45 @@ var _ = Describe("Instancetype and Preferences", func() {
...
+						PreferredEfi: &v1.EFI{
+							SecureBoot: pointer.P(true),
+							Persistent: pointer.P(true),
+						},
+					},
+				}
+				Expect(instancetypeMethods.ApplyToVmi(field, instancetypeSpec, preferenceSpec, &vmi.Spec, &vmi.ObjectMeta)).To(BeEmpty())
+				Expect(vmi.Spec.Domain.Firmware.Bootloader.EFI).ToNot(BeNil())
+				Expect(vmi.Spec.Domain.Firmware.Bootloader.EFI.SecureBoot).ToNot(BeNil())
+				Expect(*vmi.Spec.Domain.Firmware.Bootloader.EFI.SecureBoot).To(BeFalse())
```
Comment (fossedihelm) [inline pkg/instancetype/instancetype_test.go:2251]:
```suggestion
				Expect(vmi.Spec.Domain.Firmware.Bootloader.EFI.SecureBoot).To(PointTo(BeFalse()))
```
:)

File: pkg/instancetype/instancetype_test.go [hunk 2]
```diff
@@ -2228,6 +2228,45 @@ var _ = Describe("Instancetype and Preferences", func() {
 				Expect(*vmi.Spec.Domain.Firmware.Bootloader.EFI.Persistent).To(BeTrue())
 				Expect(vmi.Spec.Domain.Firmware.Bootloader.EFI.SecureBoot).To(BeNil())
 			})
+
+			It("should not overwrite EFI when using PreferredEfi - bug #12985", func() {
```
Comment (fossedihelm) [inline pkg/instancetype/instancetype_test.go:2232]: nit: Maybe several `It`s can be merged in a `DescribeTable`.
For a followup maybe, not here :)

**Review by fossedihelm — APPROVED** [review]

File: pkg/instancetype/instancetype_test.go (hunk 1 above)
Comment (lyarwood) [reply pkg/instancetype/instancetype_test.go:2251]: TIL about `PointTo` thanks. I'll definitely switch over to using this.

File: pkg/instancetype/instancetype_test.go (hunk 2 above)
Comment (lyarwood) [reply pkg/instancetype/instancetype_test.go:2232]: I'd just end up duplicating the assertions in the table so meh. We are starting to heavily refactor these tests in 1.4 so I'll take another look then thanks.
