### PR TITLE
instancetype: Fix `PreferredUse{BiosSerial,SecureBoot}`

### LINKED ISSUE #10313: `PreferredUseSecureBoot` and `PreferredUseBiosSerial` overwrite user values from `VirtualMachine`
/area instancetype

**What happened**:

$subject, this goes against the design of preferences and is a simple oversight in the code:

https://github.com/kubevirt/kubevirt/blob/b0bbb1d25d1f841c8d06413a4446d3f699b5f9a5/pkg/instancetype/instancetype.go#L1378-L1380

https://github.com/kubevirt/kubevirt/blob/b0bbb1d25d1f841c8d06413a4446d3f699b5f9a5/pkg/instancetype/instancetype.go#L1386-L1388

**What you expected to happen**:

These preferences shouldn't overwrite values already present in the `VirtualMachine`.

**How to reproduce it (as minimally and precisely as possible)**:

Create a preference with `PreferredUseSecureBoot` and `PreferredUseBiosSerial`, reference the prefreference from a `VirtualMachine` also providing these values.

**Additional context**:

Preferred value is not overwritten by value in VM spec
https://bugzilla.redhat.com/show_bug.cgi?id=2233049

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @jean-edouard 

**What this PR does / why we need it**:

Previously when provided the values of these preferences always overwrote any corresponding user values provided in the `VirtualMachine`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10313

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/instancetype/instancetype_test.go [hunk 1]
```diff
@@ -1670,6 +1670,42 @@ var _ = Describe("Instancetype and Preferences", func() {
...
+					},
+				}
+				Expect(instancetypeMethods.ApplyToVmi(field, instancetypeSpec, preferenceSpec, &vmi.Spec)).To(BeEmpty())
+				Expect(*vmi.Spec.Domain.Firmware.Bootloader.BIOS.UseSerial).To(BeFalse())
+			})
+
+			It("should not overwrite user defined value with PreferredUseSecureBoot - bug #10313", func() {
+				preferenceSpec = &instancetypev1beta1.VirtualMachinePreferenceSpec{
+					Firmware: &instancetypev1beta1.FirmwarePreferences{
+						PreferredUseEfi:        pointer.Bool(true),
```
Comment (jean-edouard) [inline pkg/instancetype/instancetype_test.go:1695]: Could we add 2 more tests to ensure `PreferredUseEfi` and `PreferredUseBios` do nothing if the VM spec contains a bootloader?

**Review by jean-edouard — COMMENTED** [review]
/approve
/hold
Just a suggestion in-line for 2 more unit tests.

**Review by 0xFelix — APPROVED** [review]
Thanks!

/lgtm
