### PR TITLE
Ensure labels and selectors for export services and pods are under max length

### LINKED ISSUE #12658: VirtualMachineExports with long names breaks VMExportController's ability to apply export service and pod
**What happened**:

When creating a VirtualMachineExport with a long name (e.g. greater than 63 characters) (I used a VirtualMachine as a source, but I'm not sure it matters), the VirtualMachineExport resource will not receive any status updates.

This happens because the Service it will try to apply passes through VirtualMachineExport's name without length validation.

https://github.com/kubevirt/kubevirt/blob/021e9b42f79b098fc50e76062e5388e13d31e235/pkg/storage/export/export/export.go#L814

https://github.com/kubevirt/kubevirt/blob/021e9b42f79b098fc50e76062e5388e13d31e235/pkg/storage/export/export/export.go#L872

**What you expected to happen**:
An end-user would probably expect _some_ indication that something has broken, or would expect the associated service to make a correct decision about how to handle that long value. The latter is done in several places (e.g. the generated service's name, the pod's name, etc, all use openshift/library-go's `naming` package to sanitize these values deterministically).

**How to reproduce it (as minimally and precisely as possible)**:

Create a VirtualMachineExport with a really long name (one greater than 63 characters), and observe that _nothing happens on the VirtualMachineExport resources_. The user is left wondering why they received no feedback.

Then observe the running `virt-controller` pod's logs, which should tell you that the APIServer is rejecting creation of the corresponding service. Something like:

```
E0822 19:21:35.711610       1 util.go:72] Service "virt-export-786029af" is invalid: spec.selector: Invalid value: "example-really-long-name-goes-here-to-see-if-we-can-trigger-the-failure": must be no more than 63 characters
```

**Additional context**:
N/A
**Environment**:
- KubeVirt version (use `virtctl version`):

```
./virtctl-v1.3.0-linux-amd64 version
Client Version: version.Info{GitVersion:"v1.3.0", GitCommit:"6a4481910c353dc43be36fd1c9a4444ad701d0b7", GitTreeState:"clean", BuildDate:"2024-07-17T15:19:15Z", GoVersion:"go1.22.2 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.2.2-91-ga27e5ef19", GitCommit:"a27e5ef1935a7d340466f02ef78719278b0ef930", GitTreeState:"clean", BuildDate:"2024-07-22T10:28:08Z", GoVersion:"go1.21.11 (Red Hat 1.21.11-1.el9_4) X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`): 

```
❯ oc version
Client Version: 4.15.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.16.4
Kubernetes Version: v1.29.6+aba1e8d
```

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by komish**
### What this PR does
Before this PR:

VirtualMachineExports with long names would cause the controller to fail to apply virt-export service/pod resources because the VirtualMachineExport's name would violate selector (for the service) /label (for the pod) length restrictions.

After this PR:

The selector and label are passed through the same naming filter that the pod's name itself uses, which restricts its length down in a reliable way.

Fixes #12658

### Why we need it and why it was done in this way
The following tradeoffs were made:

N/A

The following alternatives were considered:

This opts to make a sane decision on behalf of the user to avoid rejecting the VirtualMachineExport at creation simple because the name is too long for generated resources.

### Special notes for your reviewer

N/A

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/storage/export/export/export.go [hunk 1]
```diff
@@ -811,7 +811,7 @@ func (ctrl *VMExportController) createServiceManifest(vmExport *exportv1.Virtual
 				},
 			},
 			Selector: map[string]string{
-				exportServiceLabel: vmExport.Name,
+				exportServiceLabel: ctrl.getExportPodName(vmExport),
```
Comment (ShellyKa13) [inline pkg/storage/export/export/export.go:814]: It does the same thing but I think you should use: ctrl.getExportServiceName(vmExport)

**Review by ShellyKa13 — COMMENTED** [review]
Thanks for the PR!
One comment, but looks good

File: pkg/storage/export/export/export.go (hunk 1 above)
Comment (komish) [reply pkg/storage/export/export/export.go:814]: I’ll fix this next week and ping you back when done. Thanks.

Comment (komish) [reply pkg/storage/export/export/export.go]: @ShellyKa13 All done. Both lines should now be using `getExportServiceName` instead of `getExportPodName`.

**Comment by komish** [comment]
Hey folks, @ShellyKa13, @akalenyu - is there anything else I need to do to have this reviewed and considered for merge?

**Comment by alicefr** [comment]
@komish @ShellyKa13 one question, doesn't this change break any assumption for the filtering using labels? Here, you are changing the value assigned to that label

**Comment by komish** [comment]
@alicefr Yes, if a caller is attempting to filter export pods using `kubevirt.io.virt-export-service=myVMName`, that would break. As I read it, it's a limitation of the underling string length truncating logic (from the `naming` package), in that it is called with a prefix, and so the output will _always_ have a prefix (`"virt-export"`). 

What would you like to see instead? I could just return the VM name in cases where it's < `validation.DNS1035LabelMaxLength`, and otherwise use the `getExportServiceName` value. Should be backwards compatible, but also fix the bug at the cost of an extra function call.

**Comment by mhenriks** [comment]
> What would you like to see instead? I could just return the VM name in cases where it's <= validation.DNS1035LabelMaxLength, and otherwise use the getExportServiceName value. Should be backwards compatible, but also fix the bug at the cost of an extra function definition.

Although I assume that that end users do not care about this label I think it is a good idea to be backwards compatible

File: pkg/storage/export/export/export.go [hunk 2]
```diff
@@ -766,6 +766,15 @@ func (ctrl *VMExportController) getExportPodName(vmExport *exportv1.VirtualMachi
 	return naming.GetName(exportPrefix, vmExport.Name, validation.DNS1035LabelMaxLength)
 }
 
+// getExportLabelValue will return the virtual machine's name if it is under the
+// DNS1035-specified max length, or a normalized name otherwise.
+func (ctrl *VMExportController) getExportLabelValue(vmExport *exportv1.VirtualMachineExport) string {
+	if len(vmExport.Name) <= validation.DNS1035LabelMaxLength {
```
Comment (mhenriks) [inline pkg/storage/export/export/export.go:772]: maybe just add a comment that this is here for backwards compatibility, otherwise looks great

**Comment by komish** [comment]
@mhenriks @alicefr @ShellyKa13 PTAL - This should be backwards compatible now, preserving the original design of using the `exportv1.VirtualMachineExport{}.Name` for the label's value if it complies with the max length constraint. And users who had export names longer than the constraint should no longer see an error.

File: pkg/storage/export/export/export.go (hunk 2 above)
Comment (komish) [reply pkg/storage/export/export/export.go:774]: Done! I opted to put it in the logic vs. the doc comment as it _felt_ more clear to me, but I can put it anywhere if you have strong feelings otherwise.

**Comment by mhenriks** [comment]
@awels what do you think?

**Comment by awels** [comment]
So I just fixed the same thing here: https://github.com/kubevirt/kubevirt/pull/13039 note that the check is not actually needed. `naming.GetName` actually just returns the name if it is short enough.

**Comment by komish** [comment]
@awels 

Am I misreading https://github.com/openshift/library-go/blob/master/pkg/build/naming/namer.go#L19-L22 - which would return the "{base}-{suffix}"?

Also, wouldn't #13039 be a duplicate of the work here?

**Comment by awels** [comment]
Also note we use the vmexport name in the export server pod template, and it needs to be fixed there as well otherwise it will not create pod properly.

**Comment by awels** [comment]
> @awels
> 
> Am I misreading https://github.com/openshift/library-go/blob/master/pkg/build/naming/namer.go#L19-L22 - which would return the "{base}-{suffix}"?

Right but all the created resources (pod/service/etc) all have a prefix, so we would want the labels to have them as well. That is why I used the existing functions in my PR.
> 
> Also, wouldn't #13039 be a duplicate of the work here?

It is, I didn't realize you were working on this until just now. I was just working my queue and fixing that was next on the list. Note I think with this PR the export server pod won't start due to the same length issue if you pass in a longer vmexport name.

**Comment by awels** [comment]
@mhenriks @alicefr The preserve the label instead of adding the prefix is probably a non issue. I don't care that much either way. But we will have two different formats for the label now. Without prefix if length < 63 and with prefix if length > 63. Which seems inconsistent to me. But either way I don't think it will matter that much.

**Comment by mhenriks** [comment]
> @mhenriks @alicefr The preserve the label instead of adding the prefix is probably a non issue. I don't care that much either way. But we will have two different formats for the label now. Without prefix if length < 63 and with prefix if length > 63. Which seems inconsistent to me. But either way I don't think it will matter that much.

I think the backward compat is nice just in case. The > 63 case is inconsistent by design (format includes hash) so I really see no difference wrt consistency < 63 its one thing, > 63 it's another.

Can @awels and @komish decide who wants to carry the torch here? If we stick with this PR, may have to include some stuff from #13039

**Comment by komish** [comment]
@mhenriks, already discussed with @awels - They've let me pull their changes in here. I've left the backwards compatible function in place, but I can swap it out if it's decided that consistency in the naming scheme is preferred (over backwards compatibility).

As far as the Pod template, it should be backwards compatible, given the outgoing implementation stuck to the same structure as the naming.GetName (e.g. `{base}-{suffix}`).

The last thing to note is that the pod template calls the `naming` package directly because (a) `getExportPodName` is a method on VMExportController. Little bit of duplication there.

File: pkg/virt-controller/services/template.go [hunk 3]
```diff
@@ -1104,7 +1107,7 @@ func (t *templateService) RenderHotplugAttachmentTriggerPodTemplate(volume *v1.V
 func (t *templateService) RenderExporterManifest(vmExport *exportv1.VirtualMachineExport, namePrefix string) *k8sv1.Pod {
 	exporterPod := &k8sv1.Pod{
 		ObjectMeta: metav1.ObjectMeta{
-			Name:      fmt.Sprintf("%s-%s", namePrefix, vmExport.Name),
+			Name:      naming.GetName(namePrefix, vmExport.Name, validation.DNS1035LabelMaxLength),
```
Comment (awels) [inline pkg/virt-controller/services/template.go:1110]: As @mhenriks pointed out in my PR, naming.GetPodName is slightly more appropriate here, no need to pass the validation parameter (same otherwise).

Comment (komish) [reply pkg/virt-controller/services/template.go]: Makes sense - updated.

**Comment by awels** [comment]
So definitely need to also make sure the template containers does the same thing. in my test environment if I leave as vmExport.Name I get the following error:
```
E1009 18:54:06.041204       1 util.go:72] Pod "virt-export-b61ea7f7" is invalid: spec.containers[0].name: Invalid value: "rhel9-pink-raccoon-24-export-123456789123456789012345678901234567890123456789012345678901234567890": must be no more than 63 characters
```
Its line 1127 of template.go

File: pkg/virt-controller/services/template.go [hunk 4]
```diff
@@ -1121,7 +1122,7 @@ func (t *templateService) RenderExporterManifest(vmExport *exportv1.VirtualMachi
 			RestartPolicy: k8sv1.RestartPolicyNever,
 			Containers: []k8sv1.Container{
 				{
-					Name:            vmExport.Name,
+					Name:            naming.GetPodName(namePrefix, vmExport.Name),
```
Comment (komish) [inline pkg/virt-controller/services/template.go:1125]: @awels Like so?

Comment (awels) [reply pkg/virt-controller/services/template.go:1125]: Yes

File: pkg/storage/export/export/export_test.go [hunk 5]
```diff
@@ -844,7 +844,7 @@ var _ = Describe("Export controller", func() {
 			Expect(ok).To(BeTrue())
 			pod, ok := create.GetObject().(*k8sv1.Pod)
 			Expect(ok).To(BeTrue())
-			Expect(pod.GetName()).To(Equal(fmt.Sprintf("%s-%s", exportPrefix, testVMExport.Name)))
+			Expect(pod.GetName()).To(Equal(controller.getExportPodName(testVMExport)))
```
Comment (awels) [inline pkg/storage/export/export/export_test.go:847]: this should probably be `controller.getExportLabelValue(testVMExport)`
Maybe also ensure that the length of pod.GetName() <= validation.DNS1035LabelMaxLength

Comment (komish) [reply pkg/storage/export/export/export_test.go:847]: As in, the test only? Or where the pod name is set in the template as well? The latter is in a different package IIRC, so I’d have to duplicate some logic or move the method call to a functions in a library available to both packages.

Comment (komish) [reply pkg/storage/export/export/export_test.go:847]: Ah, I see the test logs now. I’ll take a closer look in the AM

Comment (komish) [reply pkg/storage/export/export/export_test.go:847]: @awels

The problem here seems to be that getExportPodName uses DNS1035LabelMaxLength (i.e. <= 63)
https://github.com/kubevirt/kubevirt/blob/main/pkg/storage/export/export/export.go#L770

But when Rendering the pod manifest, we use `naming.GetPodName` which uses DNS1123SubdomainMaxLength (i.e. <= 253). https://github.com/openshift/library-go/blob/master/pkg/build/naming/namer.go#L41

The rendered value ends up being <= 253, so it's passed through as is. 

The naming package seems to align with k8s upstream https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L254

This could go either way, but for now I'll force the renderer to use the shorter length. Let me know if you want me to go the other way (and change the getExportPodName to use DNS1123SubdomainMaxLength)

Comment (komish) [reply pkg/storage/export/export/export_test.go:848]: https://github.com/kubevirt/kubevirt/commit/114474c1020d526625afc1ddea1a955331f6004c should contain the fix as described, as well as the length assertion in testing.

**Review by awels — APPROVED** [review]
