### PR TITLE
virtctl console wait until the virtual machine is in running state

### LINKED ISSUE #1001: Make virtctl console wait for console to become ready
When I start a VM, I would like to immediately connect to its serial console to see all the output it may produce during boot. But I can't do it right away, because I get the error:

```
[ihar@ws kubevirt]$ ./cluster/virtctl.sh console ovm-cirros                                                                                                                                     
Escape sequence is ^]                                                                                                                                                                                       
                     Can't connect to websocket (400): Unable to connect to VM because phase is Scheduling instead of Running                                                                               
```

To mitigate the impact of it, I need to use a "while true; do virtctl console ...; done" command to get connected as soon as possible.

While I appreciate that the infrastructure to provide console output may be not ready at this point, I think virtctl could spin / wait for console to become ready and connect me to it at the earliest possibility, so that I don't miss some of boot messages.

### PR DESCRIPTION
**Pull request by SchSeba**
**What this PR does / why we need it**:
virtctl console wait until the virtual machine is in running state

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1001 

**Special notes for your reviewer**:

**Release note**:

```release-note
virtctl console wait until the virtual machine is in running state
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/1323)

### CODE REVIEW

File: pkg/virtctl/console/console.go [hunk 1]
```diff
@@ -93,19 +93,53 @@ func (c *Console) Run(cmd *cobra.Command, args []string) error {
 	writeStop := make(chan error)
 	readStop := make(chan error)
 
+	// Wait until the virtual machine is in running phase, user interrupt or timeout
+	runningChan := make(chan error)
+	timeoutChan := time.Tick(time.Duration(timeout) * time.Minute)
```
Comment (booxter) [inline pkg/virtctl/console/console.go]: this ticker goroutine never stops though we don't need it running while interacting with the console. I think we should switch to time.NewTicker and explicitly Stop() it when it's no longer needed.

File: pkg/virtctl/console/console.go [hunk 2]
```diff
@@ -93,19 +93,53 @@ func (c *Console) Run(cmd *cobra.Command, args []string) error {
...
+		runningChan <- nil
 		resChan <- con.Stream(kubecli.StreamOptions{
 			In:  stdinReader,
 			Out: stdoutWriter,
 		})
 	}()
 
+	select {
+	case <-timeoutChan:
+		return fmt.Errorf("Timeout trying to connect to the virtual machine instance")
```
Comment (booxter) [inline pkg/virtctl/console/console.go]: there is a chance now that a timeout happens while the goroutine above actually succeeds to connect. Is there anything to clean up in this particular case? Particularly, doesn't con.Stream hold a connection state that would be better off closed with explicit close() call?

Comment (SchSeba) [reply pkg/virtctl/console/console.go]: Because this is a command line program if the timeout or the interrupt channel is active the program will exit so the connection will be closed anyway.

**Comment by SchSeba** [comment]
> Nice work. One thing to improve beyond the code is commit message. It currently has a very long title that wraps. There is a common guideline about titles being quite short, and descriptions expanding on the titles. For example, see: https://chris.beams.io/posts/git-commit/

Sure no problem I will make the tittle shorter.

> It would also make sense to refer to the issue you are solving in the commit messages. For that, you may refer to https://help.github.com/articles/closing-issues-using-keywords/ It's just putting "Closes #..." in the commit message. Then whenever we merge the PR, the issue will be closed. (And also, references between PR and the issue will be established.)

About the closes our bot is making the same thing by adding the `Fixes #1001` in the PR

File: pkg/virtctl/console/console.go (hunk 1 above)
Comment (SchSeba) [reply pkg/virtctl/console/console.go]: Done

File: pkg/virtctl/console/console.go [hunk 3]
```diff
@@ -93,19 +93,53 @@ func (c *Console) Run(cmd *cobra.Command, args []string) error {
...
+	timeoutChan := time.Tick(time.Duration(timeout) * time.Minute)
+	waitInterrupt := make(chan os.Signal, 1)
+	signal.Notify(waitInterrupt, os.Interrupt)
+
 	go func() {
 		con, err := virtCli.VirtualMachineInstance(namespace).SerialConsole(vmi)
-		if err != nil {
-			resChan <- err
-			return
+		if strings.Contains(fmt.Sprint(err), "not found") {
```
[the remark this answers is not in the document]
Comment (SchSeba) [reply pkg/virtctl/console/console.go]: Done

File: pkg/virtctl/console/console.go [hunk 4]
```diff
@@ -93,19 +93,53 @@ func (c *Console) Run(cmd *cobra.Command, args []string) error {
...
+			runningChan <- err
+		}
+
+		for err != nil {
+			// Sleep to prevent denial of service on the api server
+			time.Sleep(500 * time.Millisecond)
+			con, err = virtCli.VirtualMachineInstance(namespace).SerialConsole(vmi)
```
[the remark this answers is not in the document]
Comment (SchSeba) [reply pkg/virtctl/console/console.go]: I changed the check now its inside the for loop.

File: pkg/virtctl/console/console.go [hunk 5]
```diff
@@ -93,19 +93,60 @@ func (c *Console) Run(cmd *cobra.Command, args []string) error {
...
+	timeoutChan := time.NewTicker(time.Duration(timeout) * time.Minute)
+	waitInterrupt := make(chan os.Signal, 1)
+	signal.Notify(waitInterrupt, os.Interrupt)
+
 	go func() {
 		con, err := virtCli.VirtualMachineInstance(namespace).SerialConsole(vmi)
-		if err != nil {
-			resChan <- err
-			return
+		for err != nil {
```
Comment (stu-gott) [inline pkg/virtctl/console/console.go]: Sorry for the tardy review. I thought I had reviewed yesterday but my comment seems to have disappeared.

It might be worth looking into the "k8s.io/apimachinery/pkg/util/wait" library. There's a PollImmediate function that already handles the busywork of polling on an interval with a timeout/error conditions. Using that could possibly simplify this code a bit.

File: pkg/virtctl/console/console.go (hunk 2 above)
Comment (booxter) [reply pkg/virtctl/console/console.go]: Do you mean some deferred callback handles it for us? If so, great.

**Comment by booxter** [comment]
The latest code changes are spot on, thanks (I would split the ticker change from error type change into separate commits since they are not both related to the commit message of the commit they are lumped into), but that's probably a minor issue.

The commit message title for one of the commits is still too long so it would be nice to see this fixed. Also to clarify, the reason why we may want to mention the issue number in PR commit messages and not just PR description on github.com is that in the former case, we have a direct link to the issue; while in the latter case, there are several levels of indirection (the reader needs to first identify which merge commit introduced a commit in the master tree; then follow the PR number from the merge commit message to the PR; then finally follow the link to the issue). [It's not a major thing, but may alleviate some of the pain in the future.]

One thing that I've missed in the previous round of review, and I am sorry for not pointing it out right away, is that the PR lacks new tests for the change. I think it would benefit from a functional test case that would start a VMI and immediately call to console and check that the tool actually connects to the VMI (after some time when the guest is up and ready) and not bails out on the user with an error, as it did before the PR. I haven't checked if we already have functional test cases for the CLI, but if not, that's an invitation to add some.

Thanks.

File: pkg/virtctl/console/console.go (hunk 5 above)
Comment (SchSeba) [reply pkg/virtctl/console/console.go]: I take a look into the function and make the implementation but this not simplify the code.
This help with the timeout but not with the user interrupt.
Also we need to create a new goroutine after the PollImmediate success to create a new connection to the console service for the connection stream.

**Comment by SchSeba** [comment]
@booxter 
> The commit message title for one of the commits is still too long so it would be nice to see this fixed.
Changed.

> One thing that I've missed in the previous round of review, and I am sorry for not pointing it out right away, is that the PR lacks new tests for the change. I think it would benefit from a functional test case that would start a VMI and immediately call to console and check that the tool actually connects to the VMI (after some time when the guest is up and ready) and not bails out on the user with an error, as it did before the PR. I haven't checked if we already have functional test cases for the CLI, but if not, that's an invitation to add some.

I Changed how the console functional tests works by removing the waitForVMIStart call before we call the console.

We don't have functional test cases for the CLI and I am not sure how to test the console because if I call the console command from the code a get an error that he cant find a `tty` related to this line `terminal.MakeRaw(int(os.Stdin.Fd()))`

File: tests/utils.go [hunk 6]
```diff
@@ -1130,10 +1131,21 @@ func NewConsoleExpecter(virtCli kubecli.KubevirtClient, vmi *v1.VirtualMachineIn
 	expecterReader, expecterWriter := io.Pipe()
 	resCh := make(chan error)
 	go func() {
-		con, err := virtCli.VirtualMachineInstance(vmi.ObjectMeta.Namespace).SerialConsole(vmi.ObjectMeta.Name)
-		if err != nil {
-			resCh <- err
-			return
+		con, err := virtCli.VirtualMachineInstance(vmi.Namespace).SerialConsole(vmi.Name)
```
Comment (booxter) [inline tests/utils.go]: I think the idea of making functional tests implicitly validate console waiting for scheduler is great and better than having one or two cases to cover this behavior explicitly.

But it doesn't seem that you really validate the change in the tool here. This code below is a duplicate of what is added in the tool; you don't reuse the code from there. I think the right thing to do is to reuse the code from the tool here. It may require spinning up some of the tool code into a separate helper function ready to use.

As-is, I suspect the tests changes would pass even without the fix in the tool.

**Comment by booxter** [comment]
I understand that if you just call the tool from inside tests directly then you get `terminal.MakeRaw(int(os.Stdin.Fd()))` called, which would be wrong. I think it suggests that you may need to spin up the goroutine, or its part, that establishes connection to the console (or fails when the timeout is reached or the VMI is not found) into a separate function that you would be able to call to from both the tool `main` body as well as from `tests/utils.go`.

**Comment by stu-gott** [comment]
retest this please

File: pkg/kubecli/vmi.go [hunk 7]
```diff
@@ -246,7 +247,21 @@ func (v *vmis) VNC(name string) (StreamInterface, error) {
 	return v.asyncSubresourceHelper(name, "vnc")
 }
 func (v *vmis) SerialConsole(name string) (StreamInterface, error) {
-	return v.asyncSubresourceHelper(name, "console")
+	con, err := v.asyncSubresourceHelper(name, "console")
+	for err != nil {
```
Comment (booxter) [inline pkg/kubecli/vmi.go]: Isn't it an issue that the function may never exit? The change may hang functional tests indefinitely, among other things.

**Comment by cynepco3hahue** [comment]
@SchSeba you need to use affinity from k8s API to avoid
```
# kubevirt.io/kubevirt/tests_test
tests/console_test.go:113:26: undefined: "kubevirt.io/kubevirt/pkg/api/v1".Affinity
make: *** [goveralls] Error 2
```

**Comment by SchSeba** [comment]
Look like there is a problem with the travis-ci.
Complain on `git status --porcelain` and `tests/console_test.go:113:26: undefined: "kubevirt.io/kubevirt/pkg/api/v1".Affinity` but the tests runs without any problem on my local environment and my git status is empty.

**Comment by cynepco3hahue** [comment]
@SchSeba Rebase on master I saw Roman merged some change to use k8s `Affinity` instead of creating our own.

**Comment by SchSeba** [comment]
Rebase do the magic thanks @cynepco3hahue :)

File: pkg/kubecli/vmi.go [hunk 8]
```diff
@@ -245,8 +246,55 @@ func (ws *wsStreamer) Stream(options StreamOptions) error {
...
+				connectionChan <- connectionStruct{con: nil, err: err}
+				return
+			}
+		}
+		connectionChan <- connectionStruct{con: con, err: nil}
+	}()
+
+	select {
+	case <-timeoutChan:
+		return nil, fmt.Errorf("Timeout trying to connect to the virtual machine instance")
```
Comment (booxter) [inline pkg/kubecli/vmi.go]: it's nice that we eventually exit but shouldn't we also shut down the goroutine?

File: tests/utils.go [hunk 9]
```diff
@@ -1130,7 +1130,7 @@ func NewConsoleExpecter(virtCli kubecli.KubevirtClient, vmi *v1.VirtualMachineIn
 	expecterReader, expecterWriter := io.Pipe()
 	resCh := make(chan error)
 	go func() {
-		con, err := virtCli.VirtualMachineInstance(vmi.ObjectMeta.Namespace).SerialConsole(vmi.ObjectMeta.Name)
+		con, err := virtCli.VirtualMachineInstance(vmi.Namespace).SerialConsole(vmi.Name, int(timeout))
```
Comment (booxter) [inline tests/utils.go]: I think now that you reuse the same timeout both to wait for serial console to start AND later for the expecter, you should track how much time it took to connect to the serial console, and reduce the timeout that is used for expecter by that much. Otherwise this function may take significantly longer than expected by the caller, in case when it took significant time for serial console to connect.

File: pkg/kubecli/vmi.go (hunk 8 above)
Comment (SchSeba) [reply pkg/kubecli/vmi.go]: I don't think we need to stop the goroutine because we have 3 scenarios:
1. the helper return the con or error i will exit the goroutine
2. timeout this return an error an the virctl exit
3. user interrupt the virtctl exit

all of them will stop the goroutine.

File: tests/utils.go (hunk 9 above)
Comment (SchSeba) [reply tests/utils.go]: if it took a lot of time to connect the test will exit because of the test time out no?

I don't think we need to make this complex because the test have timeout for all the test scenario (create vmi, wait for console, wait for the expecter).

File: pkg/kubecli/vmi.go (hunk 8 above)
Comment (booxter) [reply pkg/kubecli/vmi.go]: And when it's used in a functional test, do you terminate the goroutine (before the whole suite exits)? I don't think it's generate a good idea to leak it to outside even if the caller will eventually exit.

File: tests/utils.go (hunk 9 above)
Comment (booxter) [reply tests/utils.go]: Yes but your timeout semantics is now broken (in some cases): the function receives a timeout argument but then doesn't satisfy it (by taking up to twice the expected time). While indeed it probably works (=passes tests) in most cases, it's not ideal.

File: tests/utils.go [hunk 10]
```diff
@@ -1129,13 +1129,15 @@ func NewConsoleExpecter(virtCli kubecli.KubevirtClient, vmi *v1.VirtualMachineIn
...
 	expecterReader, expecterWriter := io.Pipe()
 	resCh := make(chan error)
-	go func() {
-		con, err := virtCli.VirtualMachineInstance(vmi.Namespace).SerialConsole(vmi.Name, int(timeout))
-		if err != nil {
-			resCh <- err
-			return
-		}
 
+	startTime := time.Now()
```
Comment (booxter) [inline tests/utils.go]: Nice!

**Comment by booxter** [comment]
@vladikr I think this PR is good to go; I am not sure about CI failures. I tried to deduce what failed in the jobs but couldn't find a place to extract more detailed logs for the failures. Are these failures known?

**Comment by vladikr** [comment]
ok to test

**Comment by vladikr** [comment]
not sure why kubevirt functional tests didn't run.

**Comment by SchSeba** [comment]
@booxter @vladikr All the tests looks good now.

**Comment by booxter** [comment]
I don't have full exposure as to which jobs are supposed to pass, but I see that 1.10.3 all pass (except openshift that is expected to fail at least because of custom MAC address issue; and other failures don't seem related either). I will take it upon myself to merge this patch. I hope that's ok.

File: pkg/kubecli/vmi.go [hunk 11]
```diff
@@ -245,8 +246,59 @@ func (ws *wsStreamer) Stream(options StreamOptions) error {
...
+	connectionChan := make(chan connectionStruct)
+	isWaiting := true
+
+	go func() {
+		con, err := v.asyncSubresourceHelper(name, "console")
+		for err != nil && isWaiting {
+			if asyncSubresourceError, ok := err.(*AsyncSubresourceError); ok {
+				if asyncSubresourceError.GetStatusCode() == http.StatusBadRequest {
+					// Sleep to prevent denial of service on the api server
+					time.Sleep(1 * time.Second)
```
Comment (rmohr) [inline pkg/kubecli/vmi.go]: I think it is better to use watches instead of polling. That should be much cheaper once the connection is established.
