### PR TITLE
Fix migration monitor busy loop after successful migration

### LINKED ISSUE #17281: busy loop and log spam at the end of live migration
**What happened**:
At the end of live migration when the VM is handed off to the destination the migration monitoring code busy loops and spams log with thousands of errors, until the pod is destroyed up to few seconds later.

**What you expected to happen**:
once the execution stops there's nothing else to monitor, logs should be concise

**How to reproduce it (as minimally and precisely as possible)**:
Live migrate a VM and observe source pod logs. log excerpt:
`{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.760288Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.760448Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.760566Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.760876Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.760986Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to get domain job info, will retry","name":"hcp-06-workers-tsk8v-gx8lr","namespace":"hcp-06-hcp-06","pos":"live-migration-source.go:691","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2026-03-23T10:06:52.761081Z","uid":"6dbc5de3-77d7-4afa-9ad7-c534eb2a28cf"}`

**Environment**:
- KubeVirt version (use `virtctl version`): v1.7.1-19-g94614edb71
- Kubernetes version (use `kubectl version`): v1.34.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): RHCOS 9.6.20260225-1
- Kernel (e.g. `uname -a`): 5.14.0-570.94.1.el9_6.x86_64
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by michalskrivanek**
### What this PR does

When a migration completes successfully, the source domain transitions to Shutoff/Migrated and the migrate() function returns, closing migrationErrorChan. 
The monitor goroutine's select then returns immediately on every iteration (reading nil from a closed channel), and GetJobStats(0) fails because the domain is inactive. The original code logged a warning and called continue, creating a busy loop that spins at 100% CPU for the lifetime of the virt-launcher pod.
Fix this by simplifying the monitor loop by removing the inconsequential handling of various errors and calling GetJobStats(0) unconditionally each iteration, and enhance logMigrationInfo to show actual Downtime/DowntimeNet (instead of ExpectedDowntime) when completed job data is available. The completed job is not queried at all, instead an async event carries all the data and logs them.

Assisted-by: claude-4.6-opus

#### Before this PR:

on successful migration there's a 100% CPU busy loop until the pod dies, spamming log and causing more libvirt contention

#### After this PR:

no more log flood, more accurate final stats information

### References

- Fixes #17281 

### Why we need it and why it was done in this way
The following tradeoffs were made:

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [VEP (virtualization enhancement proposal)](https://github.com/kubevirt/enhancements/blob/main/README.md) was considered and is present (link) or not required
- [X] PR: The PR description is expressive enough and will help future contributors
- [X] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [X] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [X] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
- [X] AI Contributions: The PR abides by the [KubeVirt AI Contribution Policy](https://github.com/kubevirt/community/blob/main/ai-contribution-policy.md).

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by michalskrivanek** [comment]
rebased, improved behavior on manual abort. job disappears but the current loop code runs once more to pick up possible stats, but in case of abort the job is NONE, and there's no completed data either - resulting in confusing "migration not started" message. 

There's one more gap in existing code that hasn't been addressed here either - if libvirt never starts the job this loops indefinitely. It should never happen, but guarding it would be easy, since we already have a time e.g. the CompletionTimeoutPerGiB that we can use.
But I would consider it a different bug

**Comment by michalskrivanek** [comment]
>     * When `GetJobStats(libvirt.DOMAIN_JOB_STATS_COMPLETED | libvirt.DOMAIN_JOB_STATS_KEEP_COMPLETED)` fails, the loop immediately `continue`s with no delay, which could still create a tight retry loop under persistent errors; consider adding a small backoff or sleep before retrying to avoid CPU spinning in this path.

that is intentional. The completed stat should be there already, and we want to pick it up quickly in case the completion tears down the pod happens fast. Moreover, the code path is entirely different internally and there is no qemu roundtrip so no reason for the call to block or conflict with others.

>     * In the `DOMAIN_JOB_NONE` case you now only log "Migration job didn't start yet" when `lastProgressUpdate <= start` and otherwise do nothing; it may be worth explicitly documenting or handling the case where a job transitions to `NONE` after having progressed (e.g. failed or completed without completed stats) so future readers know why this branch intentionally does not set a result.

it happens only when the domain continues to live (i.e. migration abort/failure), and this case is guarded by the code at the top of the loop. I can add log but I think it's more sensible to address that together with https://github.com/kubevirt/kubevirt/pull/17301#issuecomment-4142227616 to handle the very unlikely case when a job mysteriously disappears without libvirt erroring out.

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 1]
```diff
@@ -708,13 +679,19 @@ func logMigrationInfo(logger *log.FilteredLogger, uid string, info *libvirt.Doma
 		return bytes * 8 / 1000000
 	}
 
+	// For completed jobs, Downtime is the final downtime, DowntimeNet contains the actual network overhead during the cutover
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:665]: I think in this case, it is better to avoid relying on this implementation detail.

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 2]
```diff
@@ -688,8 +691,16 @@ func (m *migrationMonitor) startMonitor() {
 			if logInterval%monitorLogInterval == 0 {
 				logMigrationInfo(logger, string(migrationUID), jobStats)
 			}
+		case libvirt.DOMAIN_JOB_COMPLETED:
+			logMigrationInfo(logger, string(migrationUID), jobStats)
+			return
 		case libvirt.DOMAIN_JOB_NONE:
-			completedJobInfo = m.determineNonRunningMigrationStatus(dom)
+			jobStats = m.determineNonRunningMigrationStatus(dom)
+			if jobStats != nil && jobStats.Type == libvirt.DOMAIN_JOB_CANCELLED {
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go]: I was reviewing changes commit by commit and in 40bd906d408c1734dd9bc42a26f78ff11331c92a, the code change that added: `jobStats.Type == libvirt.DOMAIN_JOB_CANCELLED` can never trigger.

It's probably cleaner to edit this commit to undo the change in this `libvirt.DOMAIN_JOB_NONE` block entirely for a cleaner commit history (though at least I don't really care but some other reviewers do).

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 3]
```diff
@@ -619,8 +619,12 @@ func (m *migrationMonitor) startMonitor() {
 
 		var jobStats *libvirt.DomainJobInfo
 		jobStats, err = dom.GetJobStats(0)
-		if err != nil {
-			logger.Reason(err).Info("failed to get domain job info, checking for completed job")
+		if err != nil || (jobStats.Type == libvirt.DOMAIN_JOB_NONE && m.lastProgressUpdate > m.start) {
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go]: Just to confirm my understanding of this:
`if err != nil || (jobStats.Type == libvirt.DOMAIN_JOB_NONE && m.lastProgressUpdate > m.start)`

When `err != nil` that means domain no longer exists and when `jobStats.Type == libvirt.DOMAIN_JOB_NONE && m.lastProgressUpdate > m.start` that means domain still exists but job must have been finished.

Also about this commit message:
`Typically on successful migration this doesn't trigger since we get migrationErr channel closure earlier than that. But it's worth a try.`

How about instead we call dom.GetJobStats(libvirt.DOMAIN_JOB_STATS_COMPLETED) AFTER the call to dom.MigrateToURI3 succeeds to report final stats? Because I think you are right that if channel closes, you might not see those downtime stats anyways.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 1 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:665]: it's unavoidable - the final stat is obviously available only once migration finishes. Sadly libvirt's interface is the same API call just with different flags, and the returned fields are mostly overlapping.
I think it will only be significant when we later expose this value to users (for now it's just a log)

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 2 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: in 40bd906 there's no change to `CANCELLED` nor `NONE`, only the new `COMPLETED` state is added that is set when the `DOMAIN_JOB_STATS_COMPLETED` lag is passed to `GetJobStats`
Or did you mean anything else?

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 3 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: correct - either it's gone (after successful migration), or there's no job. To guard against potential initial startup where we would poll _before_ the migration started we need at least one successful poll before that. This is aligned with the current logic that uses this to determine progress.

calling final stats after `migrateToURI3` finishes would be ideal, however that's a different thread. I do not mind revamping it more seriously, but AFAICT it would mean duplication in stats err handling between the migration and monitor threads to some degree, this way the "logic" is in one place.
Moreover, currently this also fixes the busy loop as this final stats poll serves as the exit of the monitoring loop.

I wonder what others think - perhaps reusing the migrationErr channel to signal the end of monitoring is "nicer" indeed. Challenge is we would need to wait for the final stats poll, or move the poll (including retry) into the migration thread.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 1 above)
Comment (Aseeef) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:665]: To clarify: I mean that right now you differentiate between calling `info.Downtime` ExpectedDowntime vs (Actual)Downtime in the logs based on whether DowntimeNet is set. The assumption here is if DowntimeNet is set, that means migration has completed.

I don't think it's safe to rely on this assumption. It seems plausible to me that some point in the future Libvirt devs will also choose to supply the Expected DowntimeNet just like they do with Downtime.

The better alternative here I think could be to use info.JobSuccessSet/info.JobSuccess to determine if the migration completed and hence if info.Downtime is the expected downtime or the actual downtime.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 2 above)
Comment (Aseeef) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: I mean if you go to commit 40bd906d408c1734dd9bc42a26f78ff11331c92a, then ideally inside this commit, lines 698-703 should not be touched. Technically, the change is incorrect and overridden anyway in 243304fabe912effb8b716b076ec65a7d154d1e1.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 3 above)
Comment (Aseeef) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: Actually ignore what I said above. I had misunderstood that purpose of this section. Claude explain to its purpose (though could you validate what it said?).

The reason `if err != nil || (jobStats.Type == libvirt.DOMAIN_JOB_NONE && m.lastProgressUpdate > m.start)` exists is that there is a small window where `dom.GetJobStats(0)` succeeds on a completed query (instead of having to call `dom.GetJobStats(libvirt.DOMAIN_JOB_STATS_COMPLETED | libvirt.DOMAIN_JOB_STATS_KEEP_COMPLETED)` and in such a case this block of code here saves us a redundant iteration.

If this explanation is not correct, could you clarify the purpose of thise code block?

Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: in addition to what I said above that is correct. It _also_ saves that one iteration. When migration completes and before it bubbles up in kubevirt to close the channel there is a small window when indeed `GetJobStats(0)` then returns `DOMAIN_JOB_NONE`, and so in case the migration ever started we can directly query the final stats.
It's likely not too significant since in case of successful migration the channel gets closed pretty quickly and the next iteration would cause error, getting into this block. However since the pod is about to be destroyed I prefer trying to get the stats quickly

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 4]
```diff
@@ -659,11 +658,15 @@ func (m *migrationMonitor) startMonitor() {
 			return
 		}
 
-		jobStats := completedJobInfo
-		if jobStats == nil {
-			jobStats, err = dom.GetJobStats(0)
+		var jobStats *libvirt.DomainJobInfo
+		jobStats, err = dom.GetJobStats(0)
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go]: Can't we simply do ?
```
jobStats, err := dom.GetJobStats(0)
```

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 5]
```diff
@@ -609,7 +609,6 @@ func (m *migrationMonitor) processInflightMigration(dom cli.VirDomain, stats *li
 }
 
 func (m *migrationMonitor) startMonitor() {
-	var completedJobInfo *libvirt.DomainJobInfo
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:613]: I wonder once we have the `migrationErr` closed don't we expect only completed jobs? and at the same time if nil is returned it's successful and err is failure? + cancellation ?

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 6]
```diff
@@ -688,8 +691,16 @@ func (m *migrationMonitor) startMonitor() {
 			if logInterval%monitorLogInterval == 0 {
 				logMigrationInfo(logger, string(migrationUID), jobStats)
 			}
+		case libvirt.DOMAIN_JOB_COMPLETED:
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go]: Should we handle bounded as well... last one that we miss

**Review by xpivarc — COMMENTED** [review]
Didn't make it pass the first commit, to be honest it was overloaded with changes and information. I have a question that might change the patch so rather ask before I finish the review. Today we set migration result on successful migration independently from monitor. We now have a way to pass "migration ended without error" by closing the channel. What's left here is to just log some "aftermatch" stats, right? I wonder why we don't switch to that routine in the select?

**Comment by Aseeef** [comment]
I was testing this PR and I observed occasionally my logs are flooded with this:
"failed to get completed job stats, will retry"

**Comment by michalskrivanek** [comment]
> I was testing this PR and I observed occasionally my logs are flooded with this:
> "failed to get completed job stats, will retry"
> 
> 

@Aseeef how long/how many lines? Succesful or failed attempt? Postcopy?

I left a busy loop in to pick up stats before pod is terminated, and therr still is a contention (that #17340 is trying to reduce) so it can happen. Just curios in what scenario you've seen it

**Comment by michalskrivanek** [comment]
> Didn't make it pass the first commit, to be honest it was overloaded with changes and information. I have a question that might change the patch so rather ask before I finish the review. Today we set migration result on successful migration independently from monitor. We now have a way to pass "migration ended without error" by closing the channel. What's left here is to just log some "aftermatch" stats, right? I wonder why we don't switch to that routine in the select?

The result is also set from within the monitor. Would you want to try to eliminate that?

We can also pass "success" via the channel before closing, but then we will also want to wait for it to retrieve the completed stats before termination. Would be best to split out from the busy loop fix

**Comment by Aseeef** [comment]
> > I was testing this PR and I observed occasionally my logs are flooded with this:
> > "failed to get completed job stats, will retry"
> 
> @Aseeef how long/how many lines? Succesful or failed attempt? Postcopy?
> 
> I left a busy loop in to pick up stats before pod is terminated, and therr still is a contention (that #17340 is trying to reduce) so it can happen. Just curios in what scenario you've seen it

Over a hundred lines. It only occasionally happens and I cannot consistently reproduce it. Attempts are still successful attempts. And no post-copy.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 2 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: in 40bd906 I'm replacing the renamed function call (+ inlining the handling of the cancellation that has been originally in the next cycle), that is indeed later in 243404f dropped entirely.
The `CANCELLED` case *can* trigger since the function is injecting a fake one in https://github.com/kubevirt/kubevirt/commit/243304fabe912effb8b716b076ec65a7d154d1e1#diff-99bc3793c1cd75cb9339bcc7ff9b949b154bd27c0f48294835642af173314bf5L469

I don't think it's particularly important since it was all dropped, but I think it's consistent across commits, even if not optimal:)

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 1 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:665]: right now it's just a log(well, only comment right here:) and it's the same structure for both cases on the libvirt side, these are optional fields. You indeed need to decide based on the GetJobStats flags.
I agree that once we make final stats fully reliable we want to distinguish more clearly. Including exposing that metric in the migrations stats and probably in the UI as well.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 4 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: sure, it remained from the original code

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 6 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: we don't call that so it shouldn't happen. But sure, why not, perhaps as a default case to log unexpected types?

**Comment by michalskrivanek** [comment]
> Over a hundred lines. It only occasionally happens and I cannot consistently reproduce it. Attempts are still successful attempts. And no post-copy.

then it is likely the contention. Would be interesting if you still see it at such high volume with #17340 .
I do not think it's so significant, if it makes sense I would suggest to then indeed separate out the final stats retrieval from monitoring loop. @xpivarc can you finish up the first pass and see if it makes sense, i.e. in next patch:
- remove the failure handling from monitoring loop (keep just logging and abort/post-copy/pause timeout decisions) This would be aligned with the similar change https://github.com/kubevirt/kubevirt/commit/a7e2b6faae62483a63a7cd992c82ce6db6d17add . I.e. the loop shouldn't be settings outcomes that are observable from the sync code.
- cancel the monitoring loop explicitly, so it's obvious what we're trying to do. there's nothing else to monitor. No need to wait on it, on channel close we can just exit as well.
- move the completed GetJobStats to the main thread after the migratetHelper() MigrateToURI3 call returns - with it's own small retry to work around contention and its own interpretation of results - just log for now, eventually this is something we want to keep in migration stats or propagate up to the UI

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 6 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: I went the opposite way, limiting what the monitoring function handles in favor of more explicit synchronous handling outside of the monitoring subroutine. As noted in https://github.com/kubevirt/kubevirt/commit/a7e2b6faae62483a63a7cd992c82ce6db6d17add as well, trying to set states/results from an async monitoring loop is racy and there's no need for that except for the timeout-based actions.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 3 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: updated to move the final stats from the monitor loop completely. it is cleaner despite a little more boilerplate

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 7]
```diff
@@ -708,13 +719,19 @@ func logMigrationInfo(logger *log.FilteredLogger, uid string, info *libvirt.Doma
 		return bytes * 8 / 1000000
 	}
 
+	// For completed jobs, Downtime is the final downtime, DowntimeNet contains the actual network overhead during the cutover
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:665]: This should be separate commit

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 8]
```diff
@@ -659,11 +658,15 @@ func (m *migrationMonitor) startMonitor() {
 			return
 		}
 
-		jobStats := completedJobInfo
-		if jobStats == nil {
-			jobStats, err = dom.GetJobStats(0)
+		var jobStats *libvirt.DomainJobInfo
+		jobStats, err = dom.GetJobStats(0)
+		if err != nil {
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:617]: Please split [0879536](https://github.com/kubevirt/kubevirt/commit/08795369bb7433af1e38d733aced0f8a187338b6)

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 9]
```diff
@@ -695,12 +654,7 @@ func (m *migrationMonitor) startMonitor() {
 			logMigrationInfo(logger, string(migrationUID), jobStats)
 			return
 		case libvirt.DOMAIN_JOB_NONE:
-			jobStats = m.determineNonRunningMigrationStatus(dom)
-			if jobStats != nil && jobStats.Type == libvirt.DOMAIN_JOB_CANCELLED {
-				logger.Info("Migration was canceled")
-				m.l.setMigrationResult(true, "Live migration aborted ", v1.MigrationAbortSucceeded)
-				return
-			}
+			logger.Info("Migration job is not active")
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:640]: We should determine if job is not started or is gone

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 8 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:617]: done

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 9 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:640]: the "is gone" state is captured by the main thread - exit from migrateToURI3. There should be a very brief moment where JOB_NONE is seen - either at the start when we start the monitor loop but for whatever reason the job setup in libvirt gets delayed (eventually timing out and returning in main thread, closing the channel and in turn exiting the monitoring, or it could be seen briefly at the end of migration (before the job completion propagates to the main thread)
We should handle a potential corner error case when libvirt never starts the job and never times out - I would suggest to use one of the time-based timeouts for that. In fact with most of the job states eliminated we can as well just simplify and let monitor call processInflightMigration() always. Do you want this in a followup or within this PR, @xpivarc ?

**Comment by michalskrivanek** [comment]
@xpivarc 
as a followup I would suggest to remove [0d57aa4](https://github.com/kubevirt/kubevirt/commit/0d57aa4cac215198822b964954d34048886b6444) and instead rely on the lifecycle events that we're already listening to (and ignore the payload, currently). It carries the same information but it eliminates the narrow but real window of "migrations finished" and "things are destroyed, the stats are gone".
it's another async path, but since there's no relation between the monitor and the final stats now so it's not an issue

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 10]
```diff
@@ -632,50 +589,43 @@ func (m *migrationMonitor) startMonitor() {
...
-			logger.Info("Didn't manage to get a job status. Post the received error and finalize.")
-			logger.Reason(m.migrationFailedWithError).Error(liveMigrationFailed)
+		if err != nil {
+			logger.Reason(err).Error(liveMigrationFailed)
 			var abortStatus v1.MigrationAbortStatus
-			if strings.Contains(m.migrationFailedWithError.Error(), "canceled by client") {
+			if strings.Contains(err.Error(), "canceled by client") {
 				abortStatus = v1.MigrationAbortSucceeded
 			}
-			// Improve the error message when the volume migration fails because the destination size is smaller then the source volume
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:652]: I see this comment was removed. But was this comment addressed?

File: pkg/virt-launcher/virtwrap/live-migration-source.go
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:1082]: Both startMonitor and retrieveCompletedStats make calls to:
```go
	domName := api.VMINamespaceKeyFunc(vmi)
	dom, err := l.virConn.LookupDomainByName(domName)
```
While not all that expensive, it's still an RPC call. I think its worth refactoring this call inside migrate and them passing the `dom` object to startMonitor and retrieveCompletedStats

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 11]
```diff
@@ -686,20 +636,57 @@ func (m *migrationMonitor) startMonitor() {
...
+	if err != nil {
+		logger.Reason(err).Warning("failed to look up domain for completed migration stats")
+		return
+	}
+	defer dom.Free()
+
+	var jobStats *libvirt.DomainJobInfo
+	err = virtwait.PollImmediately(200*time.Millisecond, 2*time.Second, func(_ context.Context) (bool, error) {
+		var getErr error
+		jobStats, getErr = dom.GetJobStats(libvirt.DOMAIN_JOB_STATS_COMPLETED)
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go]: Shouldn't this have the ` | libvirt.DOMAIN_JOB_STATS_KEEP_COMPLETED` as well?

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 12]
```diff
@@ -708,13 +695,19 @@ func logMigrationInfo(logger *log.FilteredLogger, uid string, info *libvirt.Doma
 		return bytes * 8 / 1000000
 	}
 
+	// For completed jobs, Downtime is the final downtime, DowntimeNet contains the actual network overhead during the cutover
+	downtimeInfo := fmt.Sprintf("ExpectedDowntime:%dms", info.Downtime)
+	if info.DowntimeNetSet && info.DowntimeNet > 0 {
```
Comment (Aseeef) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:667]: Reminder: I still think it's better to use JobSuccessSet/JobSuccess to determine if this is the final downtime or an estimation.

**Review by Aseeef — COMMENTED** [review]
Tested the changes, seem to be working fine on my end. Also, I like the use of PollImmediately to prevent a busy loop/log spam. The only complaint I have is that some of the commits are a bit confusing because you make a change but undo the change in a following commit. So if someone is reviewing commit by commit, they'll probably be very confused. Otherwise the changes look good to me.

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 10 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:652]: oh, that slipped through the refactorings. i meant to keep it intact for now. 
Though this is a horrible place for such a thing, moreover when this is not the only place where error could be set

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 12 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:667]: but what's the point? You can 100% tell by the presence of DowntimeNet without knowing the context. Or you can trivially add another log helper specific just to final stats with different message altogether (since then you do have the context of calling stats with the COMPLETED flag)
Note compression adds a few optional fields as well.
I slightly prefer a single generic logger that's handling optional fields on its own rather than multiple helpers. But I do not feel strongly about it at all

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 11 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: I was pondering on that...on one hand KEEP_COMPLETED makes it safe when you query multiple times, but now after https://github.com/kubevirt/kubevirt/pull/17340 got merged and here the final stats was untangled from monitoring loop I believe there is no other place that would query the final stats. And in that case it makes sense to me to "clean up"
But maybe it's just being overly conservative since the pod is going to disappear anyway?

**Comment by michalskrivanek** [comment]
> Tested the changes, seem to be working fine on my end. Also, I like the use of PollImmediately to prevent a busy loop/log spam. The only complaint I have is that some of the commits are a bit confusing because you make a change but undo the change in a following commit. So if someone is reviewing commit by commit, they'll probably be very confused. Otherwise the changes look good to me.

Thank you for testing! Yes, it's becoming a bit longer when looking per-commit, but I think they are still pretty small and logical (when you follow how it evolved:) There are few more things I'd like to pile on top
- use job completion event instead of retrieveCompletedStats call
- further streamline monitor loop - refactor processInflightMigration to process everything, not just job reports (to handle corner cases like "job never starts")
- further cleanup and removal of non-time-based decisions in monitor loop, instead rely on synchronous migrate/abort calls

File: pkg/virt-launcher/virtwrap/live-migration-source.go
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:1082]: yes indeed it causes unnecessary delay and increase the chances that the pod shutdown happens before reaching the jobstats call. I think even better would be to instead trigger the final stats via completed job event (as per https://github.com/kubevirt/kubevirt/pull/17301#issuecomment-4244410769) since it won't return anything meaningful in other cases anyway, it would be sufficient to handle just this event, it fires sooner than the migrateToURI3 returns, and it already carries the data so no need to query. It has been recently introduced for block jobs but it would work for migration as well

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 10 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:652]: done(restored)

**Comment by michalskrivanek** [comment]
ok, I hope this way it's more easy to follow.
reworked the top 2 commits to use the job event instead. It's significantly less code and it aligns with future followups better

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 11 above)
Comment (Aseeef) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: Hmm.. I thought as much. While no strong preference from me I think it might be marginally better to include it just in case especially when considering future changes.

Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: I agree. especially with the retries it could maybe slip through. either way, in the current event-based final stats i've just pushed this is not needed and the poll is completely removed. Apologies for the surprise:)

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 12 above)
Comment (Aseeef) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:667]: My concern is specifically the semantics of using whether DowntimeNet is set to differentiate Estimated Downtimes from Actual Downtimes. I don't think that is reliable behavior (for example in the future there might be an estimated DowntimeNet). Still, I know this just changes the field label in the log message so not a huge concern.

Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:667]: in a followup I think this value deserves bubbling up to metrics, separately. ongoing estimate (alongside the current dirty rate, data transferred, etc) as well as final result - currently we only capture success/failure and duration, I think adding a metric on "how smooth that migration was" is important and interesting.

as for the naming semantics, I blame libvirt for that, it's all their fault!:-)

File: pkg/virt-launcher/virtwrap/live-migration-source.go [hunk 13]
```diff
@@ -457,47 +457,6 @@ func (m *migrationMonitor) isMigrationProgressing() bool {
 	return true
 }
 
-func (m *migrationMonitor) determineNonRunningMigrationStatus(dom cli.VirDomain) *libvirt.DomainJobInfo {
```
Comment (xpivarc) [inline pkg/virt-launcher/virtwrap/live-migration-source.go:460]: Please move 755b00bdbbb83a66c1ed27564e736e70547c228f as first commit.

Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:460]: done

**Review by xpivarc — COMMENTED** [review]
/approve
/cc @vladikr

**Comment by michalskrivanek** [comment]
/override pull-kubevirt-e2e-kind-1.34-sev

The AMD SEV cluster certificate has expired. A previous run succeeded on an earlier force-push of this branch.

File: pkg/virt-launcher/virtwrap/live-migration-source.go
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:1082]: refactored to use job event instead

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 11 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go]: resolved by event

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 9 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:640]: there's already a lot in this PR, let's keep it for followup (mentioned in todo already)

File: pkg/virt-launcher/virtwrap/live-migration-source.go (hunk 1 above)
Comment (michalskrivanek) [reply pkg/virt-launcher/virtwrap/live-migration-source.go:665]: we've discussed the need to surface these in metrics offline. 
Beyond the scope of this refactoring

**Comment by tiraboschi** [comment]
Minor: `DOMAIN_JOB_CANCELLED` now unhandled in the `jobStats.Type` switch.
But even in the unlikely case it gets `DOMAIN_JOB_CANCELLED` before `migrateToURI3` exits, in practice it will only cost a couple of additional cheap iterations before closing the channel.
Not worth adding code complexity for this.
/lgtm
