### PR TITLE
bridge, discover: Don't filter static routes in wider subnets

### LINKED ISSUE #12413: Missing route entries in virt-launcher pods when using the OVS CNI. Issue observed with Kubevirt ver 1.1.x and later releases.
**What happened**:
The virt-launcher pod is inaccessible when using OVS CNI.
There was an observed issue with missing route entries in virt-launcher pods when using the OVS CNI. 
This problem has been identified in kubevirt versions 1.1.x and later releases.
Initially, the eth0 interface in the pod had 4 route entries configured. However, after virt-handler created the virt-launcher pod, only 3 route entries remained for eth0.
The missing route entry is "172.30.0.0      0.0.0.0         255.255.0.0     U     100    0        0  eth0"

In Case 1, the scenario functions correctly with kubevirt version 1.0.0. 
[root@vinod-centos ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1446
        inet 172.30.4.4  netmask 255.255.252.0  broadcast 172.30.7.255
        inet6 fe80::8fc4:4ba9:a542:ef7d  prefixlen 64  scopeid 0x20<link>
        ether 02:98:90:9e:b0:75  txqueuelen 1000  (Ethernet)
        RX packets 399  bytes 37116 (36.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 379  bytes 32016 (31.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:be:d2:1c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@vinod-centos ~]# 
[root@vinod-centos ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.30.4.1      0.0.0.0         UG    100    0        0 eth0
10.0.0.0        172.30.4.1      255.255.255.0   UG    100    0        0 eth0
172.30.0.0      0.0.0.0         255.255.0.0     U     100    0        0 eth0
172.30.4.0      0.0.0.0         255.255.252.0   U     100    0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
[root@vinod-centos ~]# 
[root@vinod-centos ~]# ping 172.30.0.2 -c 1
PING 172.30.0.2 (172.30.0.2) 56(84) bytes of data.
64 bytes from 172.30.0.2: icmp_seq=1 ttl=64 time=0.762 ms

--- 172.30.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.762/0.762/0.762/0.000 ms
[root@vinod-centos ~]# 

----------

In Case 2, the scenario does not work as expected with kubevirt versions >= 1.1.x.
diamanti@test-centos-1 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1446
        inet 172.30.8.7  netmask 255.255.252.0  broadcast 172.30.11.255
        inet6 fe80::7664:2ae9:d8e2:221e  prefixlen 64  scopeid 0x20<link>
        ether 76:e8:88:d4:3f:0a  txqueuelen 1000  (Ethernet)
        RX packets 910  bytes 331801 (324.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1068  bytes 81304 (79.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:be:d2:1c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[diamanti@test-centos-1 ~]$
[diamanti@test-centos-1 ~]$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.30.8.1      0.0.0.0         UG    100    0        0 eth0
10.0.0.0        172.30.8.1      255.255.255.0   UG    100    0        0 eth0
172.30.8.0      0.0.0.0         255.255.252.0   U     100    0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
[diamanti@test-centos-1 ~]$ ping 172.30.4.5 -c 1
PING 172.30.4.5 (172.30.4.5) 56(84) bytes of data.

--- 172.30.4.5 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

**What you expected to happen**:
We expect the same route entry in the virt-launcher pod as was present in the pod container before. Upon reviewing the kubevirt code, we identified an issue in the function 'filterRoutesByNonLocalDestination', which eliminates local route entries.

**How to reproduce it (as minimally and precisely as possible)**:
You can use any OVS cni binaries OR you can use Diamanti cluster.

**Additional context**:
I have attached the virt-handler log file 'virt-handler-1.0.0.log' from a working kubevirt version 1.0.0, and the log file 'virt-handler-1.2.0.log' from a non-working kubevirt version 1.2.0.

Case-1 Working virt-handler-1.0.0.log
----
{"component":"virt-handler","level":"info","msg":"got to add 4 routes to the DhcpConfig","pos":"bridge.go:93","timestamp":"2024-07-19T14:19:19.995872Z"}
{"component":"virt-handler","level":"info","msg":"the default route is: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"bridge.go:179","timestamp":"2024-07-19T14:19:19.995915Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995933Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995948Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 172.30.0.0/16 Src: <nil> Gw: <nil> Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995964Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 172.30.4.0/22 Src: 172.30.4.4 Gw: <nil> Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995980Z"}
{"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 172.30.4.4/22 eth0, IPv6: <nil>, MAC: 02:98:90:9e:b0:75, AdvertisingIPAddr: <nil>, MTU: 0, Gateway: 172.30.4.1, IPAMDisabled: false}","pos":"podnic.go:199","timestamp":"2024-07-19T14:19:19.996003Z"}
{"component":"virt-handler","level":"info","msg":"The generated libvirt domain interface: {Address:<nil> Type: TrustGuestRxFilters: Source:{Network: Device: Bridge: Mode: Address:<nil>} Target:<nil> Model:<nil> MAC:0xc00190d290 MTU:<nil> BandWidth:<nil> BootOrder:<nil> LinkState:<nil> FilterRef:<nil> Alias:<nil> Driver:<nil> Rom:<nil> ACPI:<nil>}","pos":"podnic.go:208","timestamp":"2024-07-19T14:19:19.996425Z"}
----

Case-2: Not working virt-handler-1.2.0.log
-----
{"component":"virt-handler","level":"info","msg":"Current pod network: {\"interfaces\":[{\"name\":\"lo\",\"index\":1,\"type\":\"device\",\"state\":\"unknown\",\"mtu\":65536,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"127.0.0.1\",\"prefix-length\":8}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"::1\",\"prefix-length\":128}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null},{\"name\":\"mgmt0\",\"index\":2,\"type\":\"veth\",\"state\":\"up\",\"mac-address\":\"92:31:67:ee:c2:f3\",\"mtu\":1500,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"172.20.0.18\",\"prefix-length\":24}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"fe80::9031:67ff:feee:c2f3\",\"prefix-length\":64}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null},{\"name\":\"eth0\",\"index\":3,\"type\":\"veth\",\"state\":\"up\",\"mac-address\":\"76:e8:88:d4:3f:0a\",\"mtu\":1446,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"172.30.8.7\",\"prefix-length\":22}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"fe80::74e8:88ff:fed4:3f0a\",\"prefix-length\":64}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null}],\"routes\":{\"running\":[{\"destination\":\"0.0.0.0/0\",\"next-hop-interface\":\"eth0\",\"next-hop-address\":\"172.30.8.1\",\"table-id\":254},{\"destination\":\"0.0.0.0/0\",\"next-hop-interface\":\"mgmt0\",\"next-hop-address\":\"172.20.0.1\",\"table-id\":254},{\"destination\":\"10.0.0.0/24\",\"next-hop-interface\":\"eth0\",\"next-hop-address\":\"172.30.8.1\",\"table-id\":254},{\"destination\":\"172.20.0.0/24\",\"next-hop-interface\":\"mgmt0\",\"table-id\":254},{\"destination\":\"172.30.0.0/16\",\"next-hop-interface\":\"eth0\",\"table-id\":254},{\"destination\":\"172.30.8.0/22\",\"next-hop-interface\":\"eth0\",\"table-id\":254},{\"destination\":\"fe80::/64\",\"next-hop-interface\":\"mgmt0\",\"table-id\":254},{\"destination\":\"fe80::/64\",\"next-hop-interface\":\"eth0\",\"table-id\":254}]},\"linux-stack\":{\"ipv4\":{\"arp-ignore\":0,\"forwarding\":true,\"ping-group-range\":[1,0],\"unprivileged-port-start\":1024},\"ipv6\":{\"forwarding\":false}}}","pos":"netpod.go:159","timestamp":"2024-07-19T14:29:23.062384Z"}
{"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 172.30.8.7/22, IPv6: <nil>, MAC: 76:e8:88:d4:3f:0a, AdvertisingIPAddr: <nil>, MTU: 0, Gateway: 172.30.8.1, IPAMDisabled: false, Routes: &[{Ifindex: 0 Dst: <nil> Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0} {Ifindex: 0 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0}]}\nRoutes: &[{Ifindex: 0 Dst: <nil> Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0} {Ifindex: 0 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0}]","pos":"discoverbridge.go:76","timestamp":"2024-07-19T14:29:23.062729Z"}
{"component":"virt-handler","level":"info","msg":"The generated domain interface data: mac = 76:e8:88:d4:3f:0a","pos":"discoverbridge.go:92","timestamp":"2024-07-19T14:29:23.063080Z"}
------
[virt-handler-1.0.0.log](https://github.com/user-attachments/files/16314595/virt-handler-1.0.0.log)
[virt-handler-1.2.0.log](https://github.com/user-attachments/files/16314602/virt-handler-1.2.0.log)
[virt-handler-1.2.0.log](https://github.com/user-attachments/files/16314614/virt-handler-1.2.0.log)
[virt-handler-1.0.0.log](https://github.com/user-attachments/files/16314615/virt-handler-1.0.0.log)

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.28.9
- VM or VMI specifications: 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-centos-1
  namespace: default
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: test-centos-1
      annotations:
        diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 10
        devices:
          blockMultiQueue: true
          disks:
          - disk:
              bus: virtio
            name: test-centos-1-os-disk
          - dedicatedIOThread: true
            disk:
              bus: virtio
            name: test-centos-1-data
        ioThreadsPolicy: auto
        machine:
          type: q35
        resources:
          requests:
            memory: 10Gi
      volumes:
      - name: test-centos-1-os-disk
        persistentVolumeClaim:
          claimName: test-centos-1-os
      - name: test-centos-1-data
        persistentVolumeClaim:
          claimName: test-centos-1-data

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by orelmisan**
### What this PR does
PR #10396 had changed the logic deciding which routes will be passed into the VM via the DHCP server:
All non-default routes whose destination subnet contains the pod NIC's address are filtered out.

If a [CNI](https://www.cni.dev/) has defined a static route to a subnet wider than the local network of the pod's NIC - it will be filtered out.

For example, assuming the pod NIC IP address is 192.168.1.3/24, and there is the following static route:
`192.168.0.0/16 dev eth0`
it would be filtered-out.

Filter only non-default routes whose destination exactly matches the local subnet of the pod's NIC.

Fixes #12413

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Bridge binding: Static routes to subnets containing the pod's NIC IP address are passed to the VM.
```

### CODE REVIEW

**Comment by oshoval** [comment]
Nice thanks
Please consider rewriting Release note, better be a free text, rather than commit title style

**Comment by orelmisan** [comment]
> Nice thanks Please consider rewriting Release note, better be a free text, rather than commit title style

Thank you for the suggestion. Could you please provide an example for how you envision the release note written as free text?

**Comment by oshoval** [comment]
Don't filter static routes in wider subnets when bridge binding is used

File: pkg/network/setup/netpod/discoverbridge.go [hunk 1]
```diff
@@ -121,14 +121,21 @@ func translateNmstateToNetlinkRoutes(otherRoutes []nmstate.Route) ([]vishnetlink
...
+
 	var otherRoutes []nmstate.Route
 	for _, route := range linkRoutes {
 		_, dstIPNet, perr := net.ParseCIDR(route.Destination)
 		if perr != nil {
 			return nil, perr
 		}
 		isDefaultRoute := route.Destination == nmstate.DefaultDestinationRoute(vishnetlink.FAMILY_V4).String()
-		localDestination := !isDefaultRoute && dstIPNet.Contains(addr.IP)
+		localDestination := !isDefaultRoute && dstIPNet.String() == localNetworkStr
```
Comment (oshoval) [inline pkg/network/setup/netpod/discoverbridge.go:138]: instead using `dstIPNet.String()` you can keep localNetwork as int and just compare both please

File: pkg/network/setup/netpod/discoverbridge.go [hunk 2]
```diff
@@ -121,14 +121,21 @@ func translateNmstateToNetlinkRoutes(otherRoutes []nmstate.Route) ([]vishnetlink
 // filterRoutesByNonLocalDestination filters out local routes (the destination is of the local link).
 // Default routes should not be filter out.
 func filterRoutesByNonLocalDestination(linkRoutes []nmstate.Route, addr *vishnetlink.Addr) ([]nmstate.Route, error) {
+	_, localNetwork, err := net.ParseCIDR(addr.String())
```
Comment (oshoval) [inline pkg/network/setup/netpod/discoverbridge.go:124]: Please consider renaming localNetwork such that it express it is a subnet mask
imho it can make it easier to grasp without checking what `ParseCIDR` returns

**Review by oshoval — APPROVED** [review]
Thanks

File: pkg/network/setup/netpod/discoverbridge.go (hunk 1 above)
Comment (oshoval) [inline pkg/network/setup/netpod/discoverbridge.go:138]: Can we just use == without `.String` on both ?
Since all the fields are comparable, in go it should work

Comment (oshoval) [inline pkg/network/setup/netpod/discoverbridge.go:138]: what about narrower subnet ? or it can't happen

Comment (orelmisan) [reply pkg/network/setup/netpod/discoverbridge.go:138]: > What about narrower subnet ? it won't be filtered, it is ok right ? Maybe worth to add an unit test for that, and to mention it on PR desc ?

The commit message and PR description state: "Filter only non-default routes whose destination **exactly matches** the local subnet of the pod's NIC."
This means that narrower subnets will not be filtered and will be passed to the VM.

Since at the moment we are not aware of a use case that requires passing the narrower subnet, I don't think its worth adding such a test case.

Comment (oshoval) [reply pkg/network/setup/netpod/discoverbridge.go:138]: I saw that, just the fact "wider" was emphasized and then it goes "general" caused me to ask that, anyhow we are good, thanks

File: pkg/network/setup/netpod/netpod_test.go [hunk 3]
```diff
@@ -1675,7 +1682,7 @@ func (c *tempCacheCreator) New(filePath string) *cache.Cache {
 	return cache.NewCustomCache(filePath, kfs.NewWithRootPath(c.tmpDir))
 }
 
-func expectedDHCPConfig(podIfaceCIDR, podIfaceMAC, defaultGW, staticRouteDst string) (*cache.DHCPConfig, error) {
+func expectedDHCPConfig(podIfaceCIDR, podIfaceMAC, defaultGW, staticRouteDst, staticRouteToWiderSubnet string) (*cache.DHCPConfig, error) {
```
Comment (EdDev) [inline pkg/network/setup/netpod/netpod_test.go:1685]: IMO `staticRouteDst` should have been made a slice.

File: pkg/network/setup/netpod/netpod_test.go [hunk 4]
```diff
@@ -1688,9 +1695,16 @@ func expectedDHCPConfig(podIfaceCIDR, podIfaceMAC, defaultGW, staticRouteDst str
...
+
+	staticRouteToWiderSubnetDest, err := vishnetlink.ParseAddr(staticRouteToWiderSubnet)
+	if err != nil {
+		return nil, err
+	}
+
 	routes := []vishnetlink.Route{
 		{Gw: net.ParseIP(defaultGW)},
 		{Dst: destAddr.IPNet, Gw: net.ParseIP(defaultGW)},
+		{Dst: staticRouteToWiderSubnetDest.IPNet},
```
Comment (EdDev) [inline pkg/network/setup/netpod/netpod_test.go:1707]: This is odd. What is the meaning of a route without a GW/next-hop?

Comment (orelmisan) [reply pkg/network/setup/netpod/netpod_test.go]: The GW is implicitly set to `nil`.
When the route's Gw is set to `nil` the DHCP server sends "0.0.0.0" as the gateway:
https://github.com/kubevirt/kubevirt/blob/12c11b1808703367a8cdef54ce8839197def26a1/pkg/network/dhcp/server/server.go#L270-L273

Which according to RFC 3442[1] is the expected behavior when the link in question is directly connected to the wider subnet.

I've explicitly set the Gw to `nil`.

[1] https://www.rfc-editor.org/rfc/rfc3442.html

File: pkg/network/setup/netpod/netpod_test.go (hunk 3 above)
Comment (orelmisan) [reply pkg/network/setup/netpod/netpod_test.go:1685]: Since `staticRouteDst` and `staticRouteToWiderSubnet` are treated differently (one has a gateway and the other does not), we cannot use a slice here.

We can consider extracting the routes building to the caller in a follow up.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/e6eed4bd58f31ec0ea5d937dbd3a787e5c8805e4..d9fe046f3f652d27a0c308a0661a0bd4e6c24a2c) : Answered @EdDev's comment.

**Comment by oshoval** [comment]
nice
/lgtm

**Review by EdDev — APPROVED** [review]
Thanks!

/approve

**Comment by EdDev** [comment]
@orelmisan , do you think it is worth backporting to v1.3.x branch?
