### PR TITLE
Fix ginkgo bootstrapping script

### LINKED ISSUE #12774: A PR could be merged without actual unit tests execution
**What happened**:
PR #12480 introduced a new package (pkg/network/multus) that had unit tests.
Due to a missing `*_suite_test.go` file, the unit tests were not actually executed [1].

The `hack/bootstrap-ginkgo.sh` script exists in order to protect us from this situation, but it didn't prevent the PR from merging.

[1] https://github.com/kubevirt/kubevirt/pull/12756

**What you expected to happen**:
A PR that introduces a new package with unit tests should not be merged in case the tests are not actually running.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
Additional directories containing unit tests without the `*_suite_test.go` file:
- ./staging/src/kubevirt.io/api/apitesting
- ./staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1
- ./tools/util

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
Some logical errors were present in this script:
- Does not check all folders
- Path to ginkgo binary wrong

Fixes #12774 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]
Thank you!

File: hack/bootstrap-ginkgo.sh [hunk 1]
```diff
@@ -4,12 +4,16 @@ set -e
...
+$ginkgobin version
 # Find every folder containing tests
-for dir in $(find ${KUBEVIRT_DIR}/pkg/ -type f -name '*_test.go' -printf '%h\n' | sort -u); do
+for dir in $(find ${FOLDERS} -type f -name '*_test.go' -printf '%h\n' | sort -u); do
     # If there is no file ending with _suite_test.go, bootstrap ginkgo
     SUITE_FILE=$(find $dir -maxdepth 1 -type f -name '*_suite_test.go')
     if [ -z "$SUITE_FILE" ]; then
-        (cd $dir && ginkgo bootstrap || :)
+        echo "Missing test suite entrypoint; attempt to create one automatically"
+        (cd $dir && $ginkgobin bootstrap)
```
Comment (orelmisan) [inline hack/bootstrap-ginkgo.sh:17]: I want to verify my understanding: The purpose of this command is to dirty the git tree and fail the make generate lane, right?
If so, could we just create any file (even an empty one) and not depend on Ginkgo's utility?

And in case this assumption is wrong, isn't the file we use has a custom function call?
https://github.com/kubevirt/kubevirt/blob/1a50ec56c184c25fcb4e88777e3dd3e4c184daee/pkg/network/multus/multus_suite_test.go#L29

File: hack/bootstrap-ginkgo.sh [hunk 2]
```diff
@@ -4,12 +4,16 @@ set -e
 
 source $(dirname "$0")/common.sh
 
-_out/tests/ginkgo version
+FOLDERS="${KUBEVIRT_DIR}/staging/src/kubevirt.io/ ${KUBEVIRT_DIR}/pkg/ ${KUBEVIRT_DIR}/cmd/ ${KUBEVIRT_DIR}/tests/framework/"
```
Comment (orelmisan) [inline hack/bootstrap-ginkgo.sh:7]: nit: Could be nice nave the directories ordered by name:
```suggestion
FOLDERS="${KUBEVIRT_DIR}/cmd/ ${KUBEVIRT_DIR}/pkg/ ${KUBEVIRT_DIR}/staging/src/kubevirt.io/   ${KUBEVIRT_DIR}/tests/framework/"
```

**Review by orelmisan — COMMENTED** [review]
Thank you for addressing this issue so quickly @akalenyu!
Just one question.

File: hack/bootstrap-ginkgo.sh (hunk 2 above)
Comment (iholder101) [inline hack/bootstrap-ginkgo.sh:7]: I think you should also add `./tools`
```shell
> find ./tools/ -regex .*_test.go
./tools/util/marshaller_test.go
./tools/cache/cache_suite_test.go
./tools/cache/time-defined-cache_test.go
```


I think that in general we better search in the entire repo, except for specific folders like `./vendor` and `./tests` to ensure we cover everything (even tests that will be added in the future).

Comment (iholder101) [reply hack/bootstrap-ginkgo.sh:7]: Okay after a small research, it seems that doing so will be a bit ugly (`find` requires all excluded folders to be provided separately):
```shell
EXCLUDE_DIRS="./vendor ./tests"
find . $(for dir in $EXCLUDE_DIRS; do echo -path $dir -prune -o; done) -name '*_test.go' -print
```

So I'm not sure if it worths making the code this ugly :)
WDYT?

File: hack/bootstrap-ginkgo.sh [hunk 3]
```diff
@@ -4,12 +4,16 @@ set -e
...
+
+ginkgobin=$(realpath _out/tests/ginkgo)
+$ginkgobin version
```
Comment (iholder101) [inline hack/bootstrap-ginkgo.sh:10]: Do we just print it here for debugging purposes?

File: staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go
Comment (iholder101) [inline staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go:1]: That's still a mystery to me. Is this folder auto-generated? If so, how does it contain tests?

**Review by iholder101 — COMMENTED** [review]
Awesome @akalenyu! Thank you!
General question, does this script run as part of `make generate`, hence is running as part of the make-generate lane?

File: staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go
Comment (fossedihelm) [reply staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go:1]: The folder contains both auto-generated and non-auto-generated files.
In particular: I moved `websocket.go` and `websocket_test.go` files there (they were required to switch to generated client), but clearly forgot to add the suite_test file. :)

File: hack/bootstrap-ginkgo.sh (hunk 1 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh:17]: > I want to verify my understanding: The purpose of this command is to dirty the git tree and fail the make generate lane, right?

Yes

> If so, could we just create any file (even an empty one) and not depend on Ginkgo's utility?
> 
> And in case this assumption is wrong, isn't the file we use has a custom function call?

Interesting idea. This would force the developer to spend some time understanding what needs to go where, so I am not sure. It would be great if we could rely on the ginkgo CLI and not have to reinvent things

File: hack/bootstrap-ginkgo.sh (hunk 2 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh:7]: So apparently the `/tools` tests don't even compile
```
kubevirt/tools/util/marshaller_test.go:32:195: not enough arguments in call to components.NewHandlerDaemonSet
```

And are not even attempted to run https://github.com/kubevirt/kubevirt/blob/941b04cb9f90745ae2038b13c8bb82eea55a16dd/hack/bazel-test.sh#L7

File: hack/bootstrap-ginkgo.sh (hunk 3 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh:10]: Yeah though it's not needed anymore since we don't `|| true` the ginkgo bootstrap call
Will remove

File: staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go
Comment (akalenyu) [reply staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go:1]: > but clearly forgot to add the suite_test file. :)

no one should really remember doing those things, unfortunately, this check was broken so you were not notified :(

Comment (iholder101) [reply staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go:1]: > The folder contains both auto-generated and non-auto-generated files.

Well, tbh it's very confusing that non-auto-generated files live under a `generated` directory :)
Perhaps we should think of a way to make it clear that these are written by a human.

File: hack/bootstrap-ginkgo.sh (hunk 2 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh]: Fixed

File: hack/bootstrap-ginkgo.sh (hunk 1 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh:16]: I would assume it's the generated one by ginkgo, but maybe we just have more requirements

Comment (orelmisan) [reply hack/bootstrap-ginkgo.sh:16]: It does a bit more:
https://github.com/kubevirt/kubevirt/blob/d096f82c3382cfaeda2467deeb711e20a5c59b4a/staging/src/kubevirt.io/client-go/testutils/setup.go#L28

I wonder if this logic is still relevant today.

File: staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go
Comment (iholder101) [reply staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/v1_suite_test.go:1]: Sounds good to me!
You're welcome to create an issue to track that if you want to :)

**Comment by iholder101** [comment]
Tested this in https://github.com/kubevirt/kubevirt/pull/12806. Seems to [work](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12806/pull-kubevirt-generate/1833896212076433408) perfectly!
```
15:59:50: ERROR: git tree state is not clean!
15:59:50: You probably need to run 'make generate' or 'make' and commit the changes
15:59:50: On branch main
15:59:50: Changes not staged for commit:
15:59:50:   (use "git add <file>..." to update what will be committed)
15:59:50:   (use "git restore <file>..." to discard changes in working directory)
15:59:50: 	modified:   cmd/virtctl/BUILD.bazel
15:59:50: 
15:59:50: Untracked files:
15:59:50:   (use "git add <file>..." to include in what will be committed)
15:59:50: 	cmd/virtctl/virtctl_suite_test.go
15:59:50: 
```

As a follow-up, we may present the error more clearly.

Thanks @akalenyu!
/approve

File: hack/bootstrap-ginkgo.sh (hunk 1 above)
Comment (akalenyu) [reply hack/bootstrap-ginkgo.sh:16]: Yeah not sure tbh.. I wouldn't want to enforce this way of initializing ^ and would also not want to have to explain to developers that they should be creating a suite file manually

**Review by orelmisan — APPROVED** [review]
Thank you @akalenyu
