### PR TITLE
virt-handler, isolation: Allow pinning maxMemory+overheads

### LINKED ISSUE #15952: SRIOV/mem hotplug: cannot limit locked memory
**What happened**:
When performing memory hot-plug in VM with SR-IOV interface, memory hotplug succeeds, but SR-IOV network interface is lost during migration.
More specifically: SR-IOV host device is unplugged from the source pod and its reattachment fails in the target pod with the following error message:
```json
{"component":"virt-launcher","kind":"","level":"error","msg":"failed to hot-plug host-devices: failed to attach host-device <hostdev type=\"pci\" managed=\"no\"><source><address type=\"pci\" domain=\"0x0000\" bus=\"0x99\" slot=\"0x06\" function=\"0x0\"></address></source><alias name=\"ua-sriov-sriov-network\"></alias></hostdev>, err: virError(Code=38, Domain=0, Message='cannot limit locked memory of process 96 to 5368709120: Operation not permitted')\n","name":"testvmi-txhzt","namespace":"kubevirt-test-default1","pos":"manager.go:597","timestamp":"2025-10-21T16:44:48.691524Z","uid":"5b89afa5-825c-4091-ac31-06a28e88afec"}
```
The problem does not always reproduce, and it depends on the memory requests and maxGuest value that is either set by the user of automatically by the system

It was reproduced with a VM that had 1GB mem requested, 2 GB maxGuest was automatically set, and the memory hotplug was to 3 GB. 

https://github.com/kubevirt/kubevirt/pull/15910 adds a test that demonstrates the problem

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.7 (main)
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Alpine 
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by nirdothan**
### What this PR does
Per https://github.com/kubevirt/kubevirt/issues/15952, SR-IOV host device fails to attach to migration target when memory hotplug is performed, with the following message:
```json
{"component":"virt-launcher","kind":"","level":"error","msg":"failed to hot-plug host-devices: failed to attach host-device <hostdev type=\"pci\" managed=\"no\"><source><address type=\"pci\" domain=\"0x0000\" bus=\"0x99\" slot=\"0x06\" function=\"0x0\"></address></source><alias name=\"ua-sriov-sriov-network\"></alias></hostdev>, err: virError(Code=38, Domain=0, Message='cannot limit locked memory of process 96 to 5368709120: Operation not permitted')\n","name":"testvmi-txhzt","namespace":"kubevirt-test-default1","pos":"manager.go:597","timestamp":"2025-10-21T16:44:48.691524Z","uid":"5b89afa5-825c-4091-ac31-06a28e88afec"}
```

The root cause seems to be a mismatch in RLIMIT_MEMLOCK calculation between KubeVirt and libvirt in case of memory hotplug + VFIO host-device hot plug (it can be seen in debug logs [1]), causing libvirt to attempt to lock more memory than virt-handler had allowed it. Since libvirt is unprivileged, it cannot raise RLIMIT_MEMLOCK and thus fails to add the host device.  

For example, when hotpluging 3Gi and maxGuest was 4Gi, the following
was printed to the  virt-launcher target log:
`memlock rlimits to: Cur: 4548723217 Max:4548723217`
then virt-handler shows:
 `cannot limit locked memory of process 97 to 5368709120`.
The calculation that libvirt performs is based on max memory + 1GB overhead for VFIO, whereas Kubevirt calculates just the memory request + overheads.

Based on [2] since memory hotplug implemented with virtio-mem, the entire memory, including all the available virtio-mem, needs to be pinned and not just the requested memory.

Thus this code change sets a higher RLIMIT_MEMLOCK, which includes both the entire max memory + overheads required for host-device. 

[1] https://github.com/kubevirt/kubevirt/blob/release-1.6/pkg/virt-handler/isolation/detector.go#L170
[2] https://virtio-mem.gitlab.io/user-guide/user-guide-qemu.html#important-current-limitations
### References

Fixes #15952

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by nirdothan** [comment]
/test-subset pull-kubevirt-e2e-kind-sriov --focus-file="sriov:320"

File: pkg/virt-handler/isolation/detector.go [hunk 1]
```diff
@@ -155,8 +155,12 @@ func AdjustQemuProcessMemoryLimits(podIsoDetector PodIsolationDetector, vmi *v1.
 	qemuProcessID := qemuProcess.Pid()
 	// make the best estimate for memory required by libvirt
 	memlockSize := services.GetMemoryOverhead(vmi, runtime.GOARCH, additionalOverheadRatio)
-	// Add base memory requested for the VM
-	vmiMemoryReq := vmi.Spec.Domain.Resources.Requests.Memory()
+	// Add max memory assigned to the VM
+	vmiMemoryReq := vmi.Spec.Domain.Memory.MaxGuest
+	if vmiMemoryReq == nil {
+		vmiMemoryReq = vmi.Spec.Domain.Resources.Requests.Memory()
+	}
```
Comment (orelmisan) [inline pkg/virt-handler/isolation/detector.go]: Consider testing for `nil` values on these struct fields, as most of them are pointers.

**Comment by oshoval** [comment]
might fix https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15947/pull-kubevirt-e2e-kind-sriov/1981397993986723840
since it seems vmiMemoryReq != nil cause it (worth to check deeper)

panic here
```
	kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/api/resource.(*Quantity).ScaledValue(0xc000b9ec08?, 0x27280c3?)
		vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:828 +0xe
	kubevirt.io/kubevirt/pkg/virt-handler/isolation.AdjustQemuProcessMemoryLimits({0x2ac86c0?, 0x4397a40?}, 0xc000b9ec08, 0x0)
		pkg/virt-handler/isolation/detector.go:163 +0x21e
```

if so it appears on
AdjustResources and AdjustQemuProcessMemoryLimits

File: pkg/virt-handler/isolation/detector.go [hunk 2]
```diff
@@ -155,8 +155,12 @@ func AdjustQemuProcessMemoryLimits(podIsoDetector PodIsolationDetector, vmi *v1.
 	qemuProcessID := qemuProcess.Pid()
 	// make the best estimate for memory required by libvirt
 	memlockSize := services.GetMemoryOverhead(vmi, runtime.GOARCH, additionalOverheadRatio)
-	// Add base memory requested for the VM
-	vmiMemoryReq := vmi.Spec.Domain.Resources.Requests.Memory()
+	// Add max memory assigned to the VM
+	vmiMemoryReq := vmi.Spec.Domain.Memory.MaxGuest
+	if vmiMemoryReq == nil {
+		vmiMemoryReq = vmi.Spec.Domain.Resources.Requests.Memory()
```
Comment (oshoval) [inline pkg/virt-handler/isolation/detector.go]: vmi.Spec.Domain.Resources.Requests.Memory() is always valid ?

if not, it leaves `vmiMemoryReq` invalid, and will fail on L164
so it is better to skip doing that in such case

File: pkg/virt-handler/isolation/detector.go [hunk 3]
```diff
@@ -155,8 +155,12 @@ func AdjustQemuProcessMemoryLimits(podIsoDetector PodIsolationDetector, vmi *v1.
 	qemuProcessID := qemuProcess.Pid()
 	// make the best estimate for memory required by libvirt
 	memlockSize := services.GetMemoryOverhead(vmi, runtime.GOARCH, additionalOverheadRatio)
-	// Add base memory requested for the VM
-	vmiMemoryReq := vmi.Spec.Domain.Resources.Requests.Memory()
+	// Add max memory assigned to the VM
+	vmiMemoryReq := vmi.Spec.Domain.Memory.MaxGuest
```
Comment (oshoval) [inline pkg/virt-handler/isolation/detector.go]: https://github.com/kubevirt/kubevirt/pull/15947/files#diff-37a55089116106db3657ea41678e1d960d532bcd4df0def3ead832df9f269d78R125

need to be changed as well wrt to this PR change / nil checks ?

Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go]: Done.

File: pkg/virt-handler/isolation/detector.go (hunk 2 above)
Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go]: Done.

File: pkg/virt-handler/isolation/detector.go (hunk 1 above)
Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go]: Done. Except for `vmi.Spec.Domain.Resources.Requests.Memory()`  which was already used as is.

**Comment by nirdothan** [comment]
[Nil checks](https://github.com/kubevirt/kubevirt/compare/b81534e07a7d67449a6be5216e9d5ddb503168a8..e8335611bdfe563e75b0ff46a863d7fec13f1e69) and [Rebase](https://github.com/kubevirt/kubevirt/compare/e8335611bdfe563e75b0ff46a863d7fec13f1e69..7d60ea520993f7fb57b78ede75e6cc677230c8ac).

File: pkg/virt-handler/isolation/detector.go [hunk 4]
```diff
@@ -155,9 +155,15 @@ func AdjustQemuProcessMemoryLimits(podIsoDetector PodIsolationDetector, vmi *v1.
...
-	memlockSize.Add(*resource.NewScaledQuantity(vmiMemoryReq.ScaledValue(resource.Kilo), resource.Kilo))
+	// Add max memory assigned to the VM
+	var vmiBaseMemory *resource.Quantity
+	if vmi.Spec.Domain.Memory != nil && vmi.Spec.Domain.Memory.MaxGuest != nil {
+		vmiBaseMemory = vmi.Spec.Domain.Memory.MaxGuest
+	} else {
+		vmiBaseMemory = vmi.Spec.Domain.Resources.Requests.Memory()
+	}
+
+	memlockSize.Add(*resource.NewScaledQuantity(vmiBaseMemory.ScaledValue(resource.Kilo), resource.Kilo))
```
Comment (oshoval) [inline pkg/virt-handler/isolation/detector.go:176]: you need to skip this line in case vmiBaseMemory is nil after all the conditions above please
else panic like https://github.com/kubevirt/kubevirt/pull/15947#issuecomment-3450563579 would happen
as far as i understand

File: pkg/virt-handler/isolation/detector.go (hunk 3 above)
Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go]: doesnt seems it is done ?
it talks about `AdjustResources` which is other func

File: pkg/virt-handler/isolation/detector.go (hunk 2 above)
Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go]: it still doesnt answer please
if `vmi.Spec.Domain.Resources.Requests.Memory()` can be nil (according mentioned panic it can), then it is still problematic, because vmiBaseMemory will stay nil and deref on the Add

Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go]: It was like this before, and I trust the original author who didn't check for Nil. ~~There was no panic mentioned. Just an incorrect calculation~~.
[updated] I think that the panic that you've quoted was from before the code change that checked if maxGuest was Nil.

Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go]: there is a panic about it fyi
https://github.com/kubevirt/kubevirt/pull/15947#issuecomment-3450563579

File: pkg/virt-handler/isolation/detector.go (hunk 3 above)
Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go]: I didn't change the behavior of that function. It still has the same potential of receiving Nil as it originally did.

Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go]: there are 3 problems / questions here
1. does it need fix of calculation ?
2. nil problem checking
3. deref of nil on the Add

choose whatever you want to address in this PR, raising for awareness

File: pkg/virt-handler/isolation/detector.go (hunk 4 above)
Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go:176]: I think that you guys are missing the essence of this PR. Please focus on the decision to use maxGuest instead of request.Memory.

**Comment by nirdothan** [comment]
Updated commit message and PR desc.

File: pkg/virt-handler/isolation/detector.go (hunk 4 above)
Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go:176]: it is so close to this code, and should be small
anyhow opened
https://github.com/kubevirt/kubevirt/pull/15965

Comment (iholder101) [reply pkg/virt-handler/isolation/detector.go:176]: Nice catch @oshoval! Thanks for opening the PR!

This is exactly the [Boy Scout Rule](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html) mentioned in the PR description :smile: :heart:

File: tests/network/sriov.go [hunk 5]
```diff
@@ -309,6 +316,89 @@ var _ = Describe(SIG("SRIOV", Serial, decorators.SRIOV, func() {
...
+
+				currentKv := libkubevirt.GetCurrentKv(virtClient)
+				config.WaitForConfigToBePropagatedToComponent(
+					"kubevirt.io=virt-controller",
+					currentKv.ResourceVersion,
+					config.ExpectResourceVersionToBeLessEqualThanConfigVersion,
+					time.Minute)
+			})
+
+			It("Should succeed", func() {
```
Comment (iholder101) [inline tests/network/sriov.go]: Can you please improve the description to reflect what you're trying to validate here?

File: pkg/virt-handler/isolation/detector.go (hunk 4 above)
Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go:176]: Closed that PR, will open according needs, from brief view (keep me honest please),
it seems it is needed and if so on both of the functions (missing on one of them).

if `vmi.Spec.Domain.Resources.Requests.Memory()` is not set to some default in case the user didnt add it, it will be nil,
and `MaxGuest` can also be nil, it shows the max extra for hotplug, so if it is nil, we should skip the Add to avoid the panic, and the memory will stay the same.

```
	// MaxGuest allows to specify the maximum amount of memory which is visible inside the Guest OS.
	// The delta between MaxGuest and Guest is the amount of memory that can be hot(un)plugged.
	MaxGuest *resource.Quantity `json:"maxGuest,omitempty"`
```

Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go:176]: I don't think that the code can get to this point of memory hotplug migration target without having max-memory or memory requests defined.
If it ever does, I'd rather have it blow up and panic in e2e tests, than set a much too low memory limit (only overheads without the actual memory), which may be much harder to identify.
In any case we can discuss that in a followup PR.

File: tests/network/sriov.go (hunk 5 above)
Comment (nirdothan) [reply tests/network/sriov.go]: Correct! Done.

File: pkg/virt-handler/isolation/detector.go (hunk 4 above)
Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go:176]: I tried to define a VM without memory I and got this error: 
```
 Error creating virtual machine instance: admission webhook "virtualmachineinstances-create-validator.kubevirt.io" denied the request: no memory requested, at least one of 'spec.domain.memory.guest', 'spec.domain.memory.hugepages.size' or 'spec.domain.resources.requests.memory' must be set
```
I supposed that a VM that only has hugepages cannot be mem hotplugged right?

Comment (oshoval) [reply pkg/virt-handler/isolation/detector.go:176]: but you can set `spec.domain.memory.hugepages.size` and then the other 2 might be nil ? 
more or less as you asked, maybe worth to try for both functions that use `ScaledValue`, to see the flow.

also what about the 2nd function `AdjustResources`, you didnt change it, so it depends only on the req.memory, can it be nil ?

note that having panic kills the pod, and breaks SLA, so i am not sure i agree about the statement
anyhow if you prefer lets delegate it to follow-up discussion

**Comment by iholder101** [comment]
I think this looks good from my perspective. Thanks a lot @nirdothan!
/approve

CC @enp0s3 @vladikr to have a look :eyes:

**Comment by nirdothan** [comment]
Corrected mistake in commit message (virt-handler and virt-launcher logs were switched)

File: pkg/virt-handler/isolation/detector.go (hunk 4 above)
Comment (enp0s3) [reply pkg/virt-handler/isolation/detector.go:176]: @nirdothan The default VM rollout strategy is LiveUpdate so memory hotplug is enabled by default. However its possible to configure the strategy to Stage which means no hotplug.  
In that case MaxGuest will be nil. It leads to a scenario where you can have a migratable VM with memory set in the domain guest, w/o memory request. In that case the base memory can be empty. It worth to check whether MaxGuest and Mem req is empty and take the guest memory in that case.

From what I see `AdjustQemuProcessMemoryLimits` isn't called only on memory hotplug event.

Comment (enp0s3) [reply pkg/virt-handler/isolation/detector.go:176]: @oshoval @nirdothan it is also possible to specify only the huge pages fields but the VMI mutator will copy the page size to the domain memory guest field, IOW there is option that all the three memory fields are empty

Comment (enp0s3) [reply pkg/virt-handler/isolation/detector.go:176]: Sorry for the typo - there is **NO** option that all the three memory fields are empty

Comment (nirdothan) [reply pkg/virt-handler/isolation/detector.go:176]: @enp0s3 Implemented the requested changes per my understanding.

**Comment by nirdothan** [comment]
Following @enp0s3's comment, [added](https://github.com/kubevirt/kubevirt/compare/412e4e98303abd25ff57860a847271ce8b057a2d..098a7000cbfce9eaada0595d1e208539d38aa54f) support for cases where both maxMemory and memory requests are not defined, and [rebased](https://github.com/kubevirt/kubevirt/compare/098a7000cbfce9eaada0595d1e208539d38aa54f..13611600b8c846958bb7a1037fb82540314edcab).

**Review by enp0s3 — APPROVED** [review]
@nirdothan Thank you!

**Comment by brianmcarey** [comment]
@nirdothan it looks like these is an issue with one of the SRIOV tests  - https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=15947

**Comment by nirdothan** [comment]
> @nirdothan it looks like these is an issue with one of the SRIOV tests - https://prow.ci.kubevirt.io/pr-history/?org=kubevirt&repo=kubevirt&pr=15947

@iholder101 @enp0s3 @vladikr 
It seems that the last rebase broke this logic. Now the initial pod before the mem hotplug fails with `cannot limit locked memory of process 100 to 2147483648: Operation not permitted`. I assume that it is related to the recent removal mutating web-hook changes. WDYT?

**Comment by nirdothan** [comment]
[Fixed a bug](https://github.com/kubevirt/kubevirt/compare/13611600b8c846958bb7a1037fb82540314edcab..df0990331a6d25bf746e73aee3a8253ae0b02700)  that occurred after rebasing over https://github.com/kubevirt/kubevirt/pull/15896 and [rebased](https://github.com/kubevirt/kubevirt/compare/df0990331a6d25bf746e73aee3a8253ae0b02700..eec2938a1dd1b8aad8302a794945063ef95247c6).
/cc @jean-edouard

**Comment by enp0s3** [comment]
/unhold

The flaky test was validated on SRIOV environment
