### PR TITLE
bug-fix: persist VM firmware UUID Phase 1

### LINKED ISSUE #11166: Hashing the VM name for the UUID leads to duplicates
**What happened**:
We created VMs with the same names in different namespaces.  VMs with the same name had the same UUID.

**What you expected to happen**:
We expected each VM to have a unique UUID (our system depends on it).  The UU in UUID stands for Universally Unique, after all :).

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two VMs with the same name in different namespaces.
2. Look at their UUIDs.

**Additional context**:
The relevant code is here:
https://github.com/kubevirt/kubevirt/blob/655022fb79329eada1de1ff58b59205aed84a98a/pkg/virt-controller/watch/vm.go#L1708

Suggestions:
1. Include the namespace in the string that you hash
2. Use uuid.New() and store it in the resource

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by dasionov**
### What this PR does

This PR implements the persistence phase of the design proposal [#347](https://github.com/kubevirt/community/pull/347) to finalize the handling of UUID calculation for both new and existing VMs, as well as VM restores.

Before this PR:
* New and existing VMs had UUIDs calculated based on their names, which could easily collide when two VMs with the same name existed in different namespaces.

After this PR:
* New VMs: A random UUID is assigned by the VM mutator webhook.
* Existing VMs: The UUID is now persisted in `vm.spec.template.spec.domain.firmware.uuid`.
* VM Restores: During a restore from a Snapshot that don't have a UUID, the Restored VM will be updated with the legacy calculation to maintain backward compatibility.

Fixes #11166

### Special notes for your reviewer
* The logic in the VM controller responsible for persisting the firmware UUID for existing VMs has been separated into a distinct controller. This separation is intended to make future removal easier when we implement the second phase of the design. We can discuss this approach further.

* In the VM restore controller, the logic to update old snapshot VMs was applied to target VMs during restore. It would be useful to verify whether the source snapshot VM's name differs from the VM being restored. If the names match, we could consider applying the legacy UUID calculation as well.

* in the design [#347](https://github.com/kubevirt/community/pull/347)  I initially considered adding a validation check to prevent an empty UUID. However, after further evaluation, I realized that it makes more sense to ensure the mutator assigns a new UUID when updating a VM. This way, if a user removes an existing firmware UUID, the VM will receive a new one.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
bug-fix: persist VM's firmware UUID for existing VMs
```

### CODE REVIEW

File: pkg/virt-controller/watch/vm/firmware.go [hunk 1]
```diff
@@ -0,0 +1,157 @@
...
+				Clock: clock.RealClock{},
+			},
+		),
+		vmIndexer: vmInformer.GetIndexer(),
+		recorder:  recorder,
+	}
+
+	_, err := vmInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc:    c.enqueueVM,
+		UpdateFunc: func(old, new interface{}) { c.enqueueVM(new) },
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:45]:
```suggestion
		UpdateFunc: func(_, new any) { c.enqueueVM(new) },
```

File: pkg/virt-controller/watch/vm/firmware.go [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+		return
+	}
+	c.queue.Add(key)
+}
+
+func (c *FirmwareController) Run(threadiness int, stopCh <-chan struct{}) {
+	defer c.queue.ShutDown()
+	log.Log.Info("Starting FirmwareController")
+
+	for i := 0; i < threadiness; i++ {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:67]: nit: Use `for i := range threadiness`

File: pkg/virt-controller/watch/vm/vm.go [hunk 3]
```diff
@@ -3262,3 +3262,7 @@ func (c *Controller) handleMemoryHotplugRequest(vm *virtv1.VirtualMachine, vmi *
 
 	return nil
 }
+
+func calculateLegacyFirmwareUUID(name string) types.UID {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/vm.go:3266]: Can you export this func and use it from the snapshot restore too?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+	if vmCopy.Spec.Template.Spec.Domain.Firmware.UUID == "" {
+		vmCopy.Spec.Template.Spec.Domain.Firmware.UUID = calculateLegacyFirmwareUUID(vmCopy.Name)
+		return true
+	}
+
+	return false
+}
+
+// Create a patch to replace the firmware field in the VM spec.
+func createFirmwarePatch(firmware *virtv1.Firmware) ([]byte, error) {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:149]: I'd almost tend to inline this helper. Doesn't add much, right?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+}
+
+// ensureFirmwareExistsAndUUIDIsSet ensures the Firmware field and UUID exist.
+// Returns true if changes were made, false otherwise.
+func ensureFirmwareExistsAndUUIDIsSet(vmCopy *virtv1.VirtualMachine) bool {
+	if vmCopy.Spec.Template.Spec.Domain.Firmware == nil {
+		vmCopy.Spec.Template.Spec.Domain.Firmware = &virtv1.Firmware{
+			UUID: calculateLegacyFirmwareUUID(vmCopy.Name),
+		}
+		return true
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:137]: You could use the same pattern as above, assiging `&virtv1.Firmware{}` but calculating the uuid only once in the block below.

File: pkg/virt-controller/watch/vm/firmware.go [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+	vm := obj.(*virtv1.VirtualMachine)
+	vmCopy := vm.DeepCopy()
+
+	if shouldPatch := ensureFirmwareExistsAndUUIDIsSet(vmCopy); shouldPatch {
+		patchBytes, err := createFirmwarePatch(vmCopy.Spec.Template.Spec.Domain.Firmware)
+		if err != nil {
+			return err
+		}
+
+		_, err = c.clientset.VirtualMachine(vm.Namespace).Patch(context.Background(), vm.Name, types.JSONPatchType, patchBytes, metav1.PatchOptions{})
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:115]: What will happen in the upgrade case, will it mark a running VM with the restart required condition?

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+	"kubevirt.io/kubevirt/pkg/testutils"
+)
+
+var _ = Describe("FirmwareController", func() {
+	var controller *FirmwareController
+	var recorder *record.FakeRecorder
+	var mockQueue *testutils.MockWorkQueue[string]
+	var virtClient *kubecli.MockKubevirtClient
+	var vmInformer cache.SharedIndexInformer
+	var vmInterface *kubecli.MockVirtualMachineInterface
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:31]: nit: use var block

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+
+	BeforeEach(func() {
+		ctrl := gomock.NewController(GinkgoT())
+		virtClient = kubecli.NewMockKubevirtClient(ctrl)
+		vmInterface = kubecli.NewMockVirtualMachineInterface(ctrl)
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:36]: Can you make use off the kubevirtfake client instead?

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 9]
```diff
@@ -0,0 +1,106 @@
...
+		controllertesting.SanityExecute(controller, []cache.Store{controller.vmIndexer}, Default)
+	}
+
+	It("should patch VM if firmware UUID is missing and contains correct legacy UUID", func() {
+		vm := libvmi.NewVirtualMachine(libvmi.New())
+		addVirtualMachine(vm)
+
+		expectedUUID := calculateLegacyFirmwareUUID(vm.Name)
+
+		var capturedPatch []byte
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:66]: With the fake client we could simply assert if the VM has a UUID after `sanityExecute` returns instead of asserting patches etc..

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+		Expect(string(patchedFirmware.UUID)).To(Equal(string(expectedUUID)), "Expected patched UUID to match calculated legacy UUID")
+	})
+
+	It("should not patch VM if firmware UUID is already set", func() {
+		vm := libvmi.NewVirtualMachine(libvmi.New())
+		vm.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{UUID: "existing-uuid"}
+
+		addVirtualMachine(vm)
+
+		vmInterface.EXPECT().Patch(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Times(0)
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:101]: We could assert that the UUID stays the same here instead.

File: pkg/storage/snapshot/restore.go [hunk 11]
```diff
@@ -866,6 +868,8 @@ func (t *vmRestoreTarget) reconcileSpec(restoredVM *kubevirtv1.VirtualMachine) (
 		}
 		restoredVM, err = t.controller.Client.VirtualMachine(t.vmRestore.Namespace).Create(context.Background(), restoredVM, metav1.CreateOptions{})
 	} else {
+		// TODO remove this in release 1.9
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: ok

File: pkg/storage/snapshot/restore.go [hunk 12]
```diff
@@ -26,6 +26,8 @@ import (
 	"strings"
 	"time"
 
+	"github.com/google/uuid"
+
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: removed the line

File: pkg/storage/snapshot/restore.go [hunk 13]
```diff
@@ -1497,3 +1501,14 @@ func getRestoreVolumeBackup(volName string, content *snapshotv1.VirtualMachineSn
 	}
 	return &snapshotv1.VolumeBackup{}, fmt.Errorf("volume backup for volume %s not found", volName)
 }
+
+func setLegacyFirmwareUUID(vm *kubevirtv1.VirtualMachine) {
+	if vm.Spec.Template.Spec.Domain.Firmware == nil {
+		vm.Spec.Template.Spec.Domain.Firmware = &kubevirtv1.Firmware{}
+	}
+	if vm.Spec.Template.Spec.Domain.Firmware.UUID == "" {
+		const magicUUID = "6a1a24a1-4061-4607-8bf4-a3963d0c5895"
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: exported as `firmware.FirmwareUUIDns`

File: pkg/virt-controller/watch/vm/firmware.go (hunk 6 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go:117]: will refactor this so it won't trigger the restart required condition

File: pkg/storage/snapshot/restore.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: exported the firmware.CalculateLegacyFirmwareUUID from the controller instead :+1:

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 14]
```diff
@@ -22,8 +22,11 @@ import (
 	"fmt"
 	"net/http"
 
+	"github.com/google/uuid"
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:25]: done

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 15]
```diff
@@ -443,6 +444,22 @@ func (admitter *VMsAdmitter) validateVolumeRequests(ctx context.Context, vm *v1.
 
 }
 
+func validateFirmwareUUID(field *k8sfield.Path, spec *v1.VirtualMachineSpec) []metav1.StatusCause {
+	var causes []metav1.StatusCause
+
+	if spec.Template.Spec.Domain.Firmware != nil {
+		if spec.Template.Spec.Domain.Firmware.UUID == "" {
+			causes = append(causes, metav1.StatusCause{
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go]: done

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go [hunk 16]
```diff
@@ -1890,6 +1890,28 @@ var _ = Describe("Validating VM Admitter", func() {
 		Expect(resp.Result.Details.Causes[0].Type).To(Equal(metav1.CauseTypeFieldValueNotSupported))
 		Expect(resp.Result.Details.Causes[0].Message).To(Equal(fgMessage))
 	})
+
+	It("should reject VM with empty firmware UUID", func() {
+		vmi := libvmi.New()
+		vm := &v1.VirtualMachine{
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go]: thanks, fixed

File: pkg/virt-controller/watch/vm/firmware.go (hunk 1 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: Thanks !

File: pkg/virt-controller/watch/vm/firmware.go (hunk 2 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: went with `for range threadiness`

File: pkg/virt-controller/watch/vm/vm.go (hunk 3 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go]: yep

File: pkg/virt-controller/watch/vm/firmware.go (hunk 4 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: done

File: pkg/virt-controller/watch/vm/firmware.go (hunk 5 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: fixed

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 7 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: done

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 9 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go:68]: I found references to k8s fake client that gives you field management (which i believe will support patch operations), but don't think we have this for virt client as well.

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 10 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go:103]: done

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 8 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: PTAL :pray: 
i think it can be further improved

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 17]
```diff
@@ -109,3 +115,17 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
...
+		return
+	}
+
+	if firmware := vm.Spec.Template.Spec.Domain.Firmware; firmware != nil && firmware.UUID != "" {
+		return
+	}
+
+	if vm.Spec.Template.Spec.Domain.Firmware == nil {
+		vm.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{UUID: types.UID(uuid.New().String())}
+	}
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:130]:
```suggestion
	if firmware := vm.Spec.Template.Spec.Domain.Firmware; firmware == nil || firmware.UUID == "" {
		firmware = &v1.Firmware{UUID: types.UID(uuid.New().String())}
	}
```

Comment (0xFelix) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:130]: Might work

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 18]
```diff
@@ -443,6 +444,17 @@ func (admitter *VMsAdmitter) validateVolumeRequests(ctx context.Context, vm *v1.
 
 }
 
+func validateFirmwareUUID(field *k8sfield.Path, spec *v1.VirtualMachineSpec) []metav1.StatusCause {
+	if spec.Template.Spec.Domain.Firmware != nil && spec.Template.Spec.Domain.Firmware.UUID == "" {
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:448]: That will let VMI's pass which have `spec.Template.Spec.Domain.Firmware == nil`?

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go [hunk 19]
```diff
@@ -1890,6 +1890,21 @@ var _ = Describe("Validating VM Admitter", func() {
 		Expect(resp.Result.Details.Causes[0].Type).To(Equal(metav1.CauseTypeFieldValueNotSupported))
 		Expect(resp.Result.Details.Causes[0].Message).To(Equal(fgMessage))
 	})
+
+	It("should reject VM with empty firmware UUID", func() {
+		vmi := libvmi.New()
+		vm := libvmi.NewVirtualMachine(vmi)
+		vm.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go:1897]: What if `vm.Spec.Template.Spec.Domain.Firmware` is `nil`? That would not fail in the current admitter IIUC.

File: pkg/virt-controller/watch/vm/firmware.go [hunk 20]
```diff
@@ -0,0 +1,156 @@
...
+		}
+
+		log.Log.Infof("Patched firmware UUID for VM %s", vm.Name)
+	}
+	return nil
+}
+
+// ensureFirmwareExistsAndUUIDIsSet ensures the Firmware field and UUID exist.
+// Returns true if changes were made, false otherwise.
+func ensureFirmwareExistsAndUUIDIsSet(vmCopy *virtv1.VirtualMachine) bool {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:135]: Almost same as setFirmwareUUID in the webhook, can we dedup?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 21]
```diff
@@ -0,0 +1,156 @@
...
+	}
+	if !exists {
+		return nil
+	}
+
+	vm := obj.(*virtv1.VirtualMachine)
+	vmCopy := vm.DeepCopy()
+
+	if shouldPatch := ensureFirmwareExistsAndUUIDIsSet(vmCopy); shouldPatch {
+		firmware := vmCopy.Spec.Template.Spec.Domain.Firmware
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:112]: What happens when `firmware == nil`? Won't a replace patch fail?

File: pkg/virt-controller/watch/vm/vm.go [hunk 22]
```diff
@@ -2922,6 +2915,7 @@ func (c *Controller) addRestartRequiredIfNeeded(lastSeenVMSpec *virtv1.VirtualMa
 		lastSeenVM.Spec.Template.Spec.NodeSelector = currentVM.Spec.Template.Spec.NodeSelector
 		lastSeenVM.Spec.Template.Spec.Affinity = currentVM.Spec.Template.Spec.Affinity
 		lastSeenVM.Spec.Template.Spec.Tolerations = currentVM.Spec.Template.Spec.Tolerations
+		lastSeenVM.Spec.Template.Spec.Domain.Firmware.UUID = currentVM.Spec.Template.Spec.Domain.Firmware.UUID
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/vm.go:2918]: Does it make sense to set UUID to be live-updatable? IIUC it can only be changed on restarts?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 17 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:130]: Nice!

File: pkg/virt-controller/watch/vm/vm.go (hunk 22 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go:2918]: The firmware controller will only save the uuid in the vm spec, it won't change the current uuid being used.. eventually we don't want the restart condition to be affected by the change.

File: pkg/virt-controller/watch/vm/firmware.go (hunk 21 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: refactored the code a bit, so now it's fixed.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 17 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:126]: Actually this might introduce a bug, where someone might configure firmware other settings like bootloader and other fields, and leave uuid empty, your approach will remove the configurations for those cases, and initialize new firmware struct with uuid field only.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go (hunk 18 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go]: For now, I’ve removed the validation to avoid breaking existing VMs.

If a user upgrades and tries to update a VM without a firmware UUID, the webhook would block the change. This could prevent legitimate updates to other fields.

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 9 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: never-mind, it's done !

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 8 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: fixed

File: pkg/virt-controller/watch/vm/firmware.go (hunk 20 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: did my best de-duping it hopefully well enough

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 23]
```diff
@@ -81,6 +84,10 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
 		return response
 	}
 
+	if ar.Request.Operation == admissionv1.Create {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: not sure... if the uuid is cleared then the controller will assign old uuid based on the name. 
we cant allow the the webhook to have a race condition with the controller

[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: Not sure we want an old uuid? I would expect it to add a new uuid again?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 24]
```diff
@@ -0,0 +1,169 @@
...
+		return nil
+	}
+
+	defaults.EnsureFirmwareUUID(vmCopy, CalculateLegacyFirmwareUUID(vmCopy.Name))
+
+	firmware := vmCopy.Spec.Template.Spec.Domain.Firmware
+	patchOp := patch.WithReplace(FirmwarePatchPath, firmware)
+	if patchType == AddFirmware {
+		patchOp = patch.WithAdd(FirmwarePatchPath, firmware)
+	}
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:140]: I'd make this a switch case, adding either patch.WithAdd or patch.WithTest + patch.WithReplace in the corresponding case. No need to maintain `patchType`.

File: pkg/defaults/defaults.go [hunk 25]
```diff
@@ -394,3 +395,14 @@ func setDefaultArchitecture(clusterConfig *virtconfig.ClusterConfig, spec *v1.Vi
 		spec.Architecture = clusterConfig.GetDefaultArchitecture()
 	}
 }
+
+// EnsureFirmwareUUID sets the VM's firmware UUID to the provided value if none exists
+func EnsureFirmwareUUID(vm *v1.VirtualMachine, uuid types.UID) {
```
Comment (0xFelix) [inline pkg/defaults/defaults.go:400]: Sorry to be picky about it, but thinking about it again, I don't think a helper like this makes a lot of sense. If not possible, then better duplicate this rather simple code.

File: pkg/virt-controller/watch/vm/vm.go (hunk 22 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/vm.go]: To me that conflicts with the concept of a field being live-updatable. If it is live-updatable, then it should be applied immediately. I think the RestartCondition is valid in that case.

File: pkg/defaults/defaults.go (hunk 25 above)
Comment (dasionov) [reply pkg/defaults/defaults.go:400]: are you sure that duplicating is better ?

File: pkg/virt-controller/watch/vm/vm.go (hunk 22 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go]: The concept of a live-updatable field is indeed concerning. However, on the other hand, raising a "restart required" condition when it's not actually necessary could be misleading.

File: pkg/virt-controller/watch/vm/firmware.go (hunk 24 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: done

File: pkg/defaults/defaults.go (hunk 25 above)
Comment (dasionov) [reply pkg/defaults/defaults.go]: fixed

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 26]
```diff
@@ -24,6 +24,8 @@ import (
 	"net/http"
 	rt "runtime"
 
+	"k8s.io/apimachinery/pkg/types"
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:27]: nit: import order

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 27]
```diff
@@ -682,6 +686,46 @@ var _ = Describe("VirtualMachine Mutator", func() {
...
+			err := json.Unmarshal(resp.Patch, &patchOps)
+			Expect(err).ToNot(HaveOccurred())
+			Expect(patchOps).NotTo(BeEmpty())
+			Expect(vmSpec.Template.Spec.Domain.Firmware).ToNot(BeNil())
+			Expect(vmSpec.Template.Spec.Domain.Firmware.UUID).ToNot(BeEmpty())
+		})
+
+		It("should preserve existing UUID when VM template spec has one", func() {
+			testUUID := types.UID("existing-test-uid")
+			oldVM.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{UUID: testUUID}
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:712]: Can you use a different value in `oldVM`, to show it respects the UUID which was set by a user?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 28]
```diff
@@ -0,0 +1,165 @@
...
+
+	if patchOps.IsEmpty() {
+		return nil
+	}
+
+	patchBytes, err := patchOps.GeneratePayload()
+	if err != nil {
+		return fmt.Errorf("failed to generate patch payload: %w", err)
+	}
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:141]: Can you perhaps break this out into a separate func? (Maybe not all of it, however you see fit)

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 29]
```diff
@@ -0,0 +1,89 @@
...
+		updatedVM, err := virtfakeClient.KubevirtV1().VirtualMachines(vm.Namespace).Get(context.TODO(), vm.Name, metav1.GetOptions{})
+		Expect(err).ToNot(HaveOccurred())
+		Expect(updatedVM.Spec.Template.Spec.Domain.Firmware).ToNot(BeNil())
+		Expect(updatedVM.Spec.Template.Spec.Domain.Firmware.UUID).To(Equal(CalculateLegacyFirmwareUUID(vm.Name)))
+	})
+
+	It("should not modify firmware UUID if already set", func() {
+		vm := libvmi.NewVirtualMachine(libvmi.New(libvmi.WithNamespace(metav1.NamespaceDefault)))
+
+		vm.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{UUID: "existing-uuid"}
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:77]: This is the 100th PR I'm reviewing today, which could make use of a `libvmi.WithUID`. :) (also, I saw at least two PRs already adding it)

File: pkg/virt-controller/watch/vm/vm.go [hunk 30]
```diff
@@ -2922,6 +2915,10 @@ func (c *Controller) addRestartRequiredIfNeeded(lastSeenVMSpec *virtv1.VirtualMa
 		lastSeenVM.Spec.Template.Spec.NodeSelector = currentVM.Spec.Template.Spec.NodeSelector
 		lastSeenVM.Spec.Template.Spec.Affinity = currentVM.Spec.Template.Spec.Affinity
 		lastSeenVM.Spec.Template.Spec.Tolerations = currentVM.Spec.Template.Spec.Tolerations
+
+		if lastSeenVM.Spec.Template.Spec.Domain.Firmware != nil {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/vm.go:2919]: @alicefr @vladikr What do you think about this? I don't think it should be live updatable.

Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go:2919]: After an offline sync with @enp0s3, we have identified several options for handling UUID changes in the VM lifecycle:

1. Allow UUID changes with a restart requirement:
   - If we permit UUID modifications, any change to this field will always require a VM restart.

2. Enforce UUID immutability
   -  The UUID would be immutable once assigned, preventing any modifications via the validation webhook.
   -  In this case, when evaluating restartRequiredCondition, we would not treat the UUID as a live-updateable field but as an immutable one that should be ignored.
   -  If a user requires a new UUID, they must create a new VM instead of modifying the existing one.

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 29 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go:77]: Sry :disappointed: i was searching for this option actually

Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware_test.go:77]: No, don't be sorry, I was just rambling around how this could actually be useful, since I saw so many PRs with UIDs lately. :)

Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: done, and good point, thank you !

File: pkg/virt-controller/watch/vm/firmware.go (hunk 28 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: done

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go (hunk 27 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:712]: yes, fixed

File: pkg/virt-controller/watch/vm/vm.go (hunk 30 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/vm.go:2919]: Are there downsides to making it immutable? If a user wants to restore to a specific UUID they can recreate the VM. Any other use cases we might be missing?

File: pkg/storage/snapshot/restore_test.go
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore_test.go:1]: added a test

File: pkg/virt-controller/watch/vm/firmware.go [hunk 31]
```diff
@@ -0,0 +1,179 @@
...
+		c.queue.AddRateLimited(key)
+	} else {
+		log.Log.V(4).Infof("processed VirtualMachine %v", key)
+		c.queue.Forget(key)
+	}
+	return true
+}
+
+const (
+	FirmwarePatchPath     = "/spec/template/spec/domain/firmware"
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:99]: I'd move these into `generateFirmwarePatch`

File: pkg/virt-controller/watch/vm/firmware.go [hunk 32]
```diff
@@ -0,0 +1,179 @@
...
+	return patchOps, nil
+}
+
+// no special meaning, randomly generated on my box.
+// TODO: do we want to use another constants? see examples in RFC4122
+const magicUUID = "6a1a24a1-4061-4607-8bf4-a3963d0c5895"
+
+var firmwareUUIDns = uuid.MustParse(magicUUID)
+
+func CalculateLegacyFirmwareUUID(name string) types.UID {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:177]:
```suggestion
func CalculateLegacyUUID(name string) types.UID {
```

Makes it flow a little better when using this as an import in another pkg.

File: pkg/libvmi/vmi.go [hunk 33]
```diff
@@ -289,6 +290,15 @@ func WithTPM(persistent bool) Option {
 	}
 }
 
+func WithUID(uid string) Option {
```
Comment (0xFelix) [inline pkg/libvmi/vmi.go:293]:
```suggestion
func WithFirmwareUUID(uid string) Option {
```

Otherwise this might be confused with `spec.metadata.uid`. There are other PRs introducing an option with the same name for this field.

File: pkg/virt-controller/watch/vm/firmware.go (hunk 31 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: done

File: pkg/virt-controller/watch/vm/firmware.go (hunk 32 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: true, fixed

File: pkg/libvmi/vmi.go (hunk 33 above)
Comment (dasionov) [reply pkg/libvmi/vmi.go]: fixed

File: pkg/libvmi/vmi.go [hunk 34]
```diff
@@ -289,6 +290,15 @@ func WithTPM(persistent bool) Option {
 	}
 }
 
+func WithFirmwareUUID(uid string) Option {
```
Comment (0xFelix) [inline pkg/libvmi/vmi.go:293]: @EdDev Would you like to see `types.UID` or `string` as type of `uid` here?

File: pkg/virt-controller/watch/vm/firmware.go [hunk 35]
```diff
@@ -0,0 +1,180 @@
...
+	log.Log.Infof("Patched firmware UUID for VM %s", vm.Name)
+	return nil
+}
+
+// generateFirmwarePatch handles the firmware UUID patching logic and returns patch operations
+func (c *FirmwareController) generateFirmwarePatch(vm *virtv1.VirtualMachine) (patch.PatchSet, error) {
+
+	const (
+		FirmwarePatchPath     = "/spec/template/spec/domain/firmware"
+		FirmwareUUIDPatchPath = "/spec/template/spec/domain/firmware/uuid"
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:143]: nit: they can be unexported :)

File: pkg/virt-controller/watch/vm/firmware.go [hunk 36]
```diff
@@ -0,0 +1,180 @@
...
+			FirmwarePatchPath,
+			vm.Spec.Template.Spec.Domain.Firmware,
+		))
+	}
+
+	return patchOps, nil
+}
+
+// no special meaning, randomly generated on my box.
+// TODO: do we want to use another constants? see examples in RFC4122
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:173]: I think we can never change this UUID again, right? Therefore, does it make sense to keep the comment any longer?

File: pkg/virt-controller/watch/vm/vm.go (hunk 30 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/vm.go:2919]: Still need to address this.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 37]
```diff
@@ -109,3 +113,13 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
 		PatchType: &jsonPatchType,
 	}
 }
+
+func setFirmwareUUIDIfNeeded(vm *v1.VirtualMachine) {
+	if vm.Spec.Template.Spec.Domain.Firmware == nil {
+		vm.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{}
+	}
+
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:121]: nittiest of nits: Drop this empty line

File: pkg/virt-controller/watch/vm/firmware.go (hunk 36 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go:173]: true

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 37 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:121]: dropped

File: pkg/virt-controller/watch/vm/vm.go (hunk 30 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go:2919]: @enp0s3 could you share your perspective for this matter?

Comment (mhenriks) [reply pkg/virt-controller/watch/vm/vm.go:2919]: My preference would be for option 1 above, don't think the field should be immutable. Deleting/recreating a VM is a major operation if there is any persistent data

File: pkg/virt-controller/watch/vm/vm.go [hunk 38]
```diff
@@ -2922,6 +2915,10 @@ func (c *Controller) addRestartRequiredIfNeeded(lastSeenVMSpec *virtv1.VirtualMa
...
+			lastSeenVM.Spec.Template.Spec.Domain.Firmware.UUID = currentVM.Spec.Template.Spec.Domain.Firmware.UUID
```
Comment (mhenriks) [inline pkg/virt-controller/watch/vm/vm.go:2920]: I don't think it is safe to assume `currentVM.Spec.Template.Spec.Domain.Firmware != nil`

**Review by mhenriks — COMMENTED** [review]
VM restore stuff looks good

File: pkg/virt-controller/watch/vm/vm.go (hunk 38 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go:2920]: what do you mean?

Comment (mhenriks) [reply pkg/virt-controller/watch/vm/vm.go:2920]: I mean `currentVM.Spec.Template.Spec.Domain.Firmware` is a pointer. Pointers can be nil. If you dereference a nil pointer the application will crash. 

There is no guarantee that your new firmware controller will set this field before vm controller reconciles

Comment (dasionov) [reply pkg/virt-controller/watch/vm/vm.go:2920]: Thanks for clarifying. Since it seems the uuid field should remain mutable, I'll remove this check entirely to ensure the restart condition is properly triggered when this field changes.

File: pkg/virt-controller/watch/application.go [hunk 39]
```diff
@@ -737,31 +738,36 @@ func (vca *VirtControllerApp) initVirtualMachines() {
...
-		instancetypecontroller.New(
-			vca.instancetypeInformer.GetStore(),
-			vca.clusterInstancetypeInformer.GetStore(),
-			vca.preferenceInformer.GetStore(),
-			vca.clusterPreferenceInformer.GetStore(),
-			vca.controllerRevisionInformer.GetStore(),
+	vca.firmwareController, err = vm.NewFirmwareController(
+		vca.vmInformer, vca.clientSet, recorder,
+	)
+	if err == nil {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/application.go:744]: nit: Can you make it an early return / panic instead? Just a personal preference though.

File: pkg/virt-controller/watch/vm/firmware.go [hunk 40]
```diff
@@ -0,0 +1,178 @@
...
+		),
+		vmIndexer: vmInformer.GetIndexer(),
+		recorder:  recorder,
+	}
+
+	_, err := vmInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc:    c.enqueueVM,
+		UpdateFunc: func(_, new any) { c.enqueueVM(new) },
+	})
+	if err != nil {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:48]: nit: could be inlined

File: pkg/virt-controller/watch/vm/firmware.go [hunk 41]
```diff
@@ -0,0 +1,178 @@
...
+func (c *FirmwareController) enqueueVM(obj interface{}) {
+	key, err := cache.MetaNamespaceKeyFunc(obj)
+	if err != nil {
+		log.Log.Errorf("Failed to get key for VM: %v", err)
+		return
+	}
+	c.queue.Add(key)
+}
+
+func (c *FirmwareController) Run(threadiness int, stopCh <-chan struct{}) {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:64]: If I'm not totally mislead, then you never actually call `Run` and so this controller is never actually started? A proper functional test should show that it's not working right now.

Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware.go:64]: See e.g. here https://github.com/kubevirt/kubevirt/blob/b59fe0fb66a4e937a59616aba7da633fc177180d/pkg/virt-controller/watch/application.go#L580

Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware.go:64]: There's also no `vca.firmwareControllerThreads`.

File: pkg/virt-controller/watch/vm/firmware.go [hunk 42]
```diff
@@ -0,0 +1,178 @@
...
+		return fmt.Errorf("failed to patch VM firmware UUID: %w", err)
+	}
+
+	log.Log.Infof("Patched firmware UUID for VM %s", vm.Name)
+	return nil
+}
+
+// generateFirmwarePatch handles the firmware UUID patching logic and returns patch operations
+func (c *FirmwareController) generateFirmwarePatch(vm *virtv1.VirtualMachine) (patch.PatchSet, error) {
+
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:140]: nit: empty line

File: pkg/virt-controller/watch/vm/firmware.go (hunk 40 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go:48]: like this?
```
	if _, err := vmInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc:    c.enqueueVM,
		UpdateFunc: func(_, new any) { c.enqueueVM(new) },
	}); err != nil {
		return nil, err
	}
```

File: pkg/virt-controller/watch/vm/firmware.go (hunk 42 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go:140]: fixed

File: pkg/virt-controller/watch/vm/firmware.go (hunk 41 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go:63]: Thanks! good catch, fixed.

File: pkg/virt-controller/watch/application.go (hunk 39 above)
Comment (dasionov) [reply pkg/virt-controller/watch/application.go]: done

File: tests/operator/operator.go [hunk 43]
```diff
@@ -915,6 +920,31 @@ var _ = Describe("[sig-operator]Operator", Serial, decorators.SigOperator, func(
 					return nil
 				}, 60*time.Second, 1*time.Second).Should(BeNil())
 
+				By(fmt.Sprintf("Verifying firmware UUID for vm %s", vmYaml.vmName))
+				Eventually(func() error {
```
Comment (0xFelix) [inline tests/operator/operator.go:924]:
```suggestion
				Eventually(func(g Gomega) {
```

Change to this and make g.Expect in the func instead of returning errors.

Comment (dasionov) [reply tests/operator/operator.go]: done, but note that we should probably remove assertions in this test in the next release since, the mutator webhook will create a new uuid, and the assert here will fail the test:
`Expect(vm.Spec.Template.Spec.Domain.Firmware).To(BeNil())`

File: pkg/libvmi/vmi.go (hunk 34 above)
Comment (0xFelix) [reply pkg/libvmi/vmi.go:293]: Ping @EdDev

**Review by 0xFelix — COMMENTED** [review]
Other than the ping, from what I can tell it looks good to me.

**Comment by dasionov** [comment]
> Ping @EdDev

Initially, a string seemed like a good choice because, when adding an option to the builder pattern, it's important to keep it simple for the user. If I handle the casting internally, the user can just provide a string instead of explicitly casting it to types.UID("some-uid"). This makes the API more convenient and reduces unnecessary friction IMO.

File: pkg/libvmi/vmi.go (hunk 34 above)
Comment (0xFelix) [reply pkg/libvmi/vmi.go:299]: Now we have `func WithUID(uid types.UID) Option {` above...

Comment (dasionov) [reply pkg/libvmi/vmi.go:299]: i guess i should aligned to it

File: pkg/virt-controller/watch/vm/firmware.go [hunk 44]
```diff
@@ -0,0 +1,176 @@
...
+	firmware := vm.Spec.Template.Spec.Domain.Firmware
+	switch {
+	case firmware == nil:
+		vm.Spec.Template.Spec.Domain.Firmware = &virtv1.Firmware{
+			UUID: legacyUUID,
+		}
+		patchOps.AddOption(patch.WithAdd(
+			firmwarePatchPath,
+			vm.Spec.Template.Spec.Domain.Firmware,
+		))
```
Comment (jean-edouard) [inline pkg/virt-controller/watch/vm/firmware.go:156]:
```suggestion
		firmware := &virtv1.Firmware{
			UUID: legacyUUID,
		}
		patchOps.AddOption(patch.WithAdd(
			firmwarePatchPath,
			firmware,
		))
```

File: pkg/virt-controller/watch/vm/firmware.go [hunk 45]
```diff
@@ -0,0 +1,176 @@
...
+	obj, exists, err := c.vmIndexer.GetByKey(key)
+	if err != nil {
+		return err
+	}
+	if !exists {
+		return nil
+	}
+
+	vm := obj.(*virtv1.VirtualMachine)
+	vmCopy := vm.DeepCopy()
```
Comment (jean-edouard) [inline pkg/virt-controller/watch/vm/firmware.go:107]: We can probably tweak `generateFirmwarePatch()` so it doesn't alter the VM (see in-line suggestion), that way we won't need the expensive deepcopy.

File: pkg/virt-controller/watch/application.go [hunk 46]
```diff
@@ -737,6 +740,12 @@ func (vca *VirtControllerApp) initVirtualMachines() {
 	var err error
 	recorder := vca.newRecorder(k8sv1.NamespaceAll, "virtualmachine-controller")
 
+	vca.firmwareController, err = vm.NewFirmwareController(
```
Comment (jean-edouard) [inline pkg/virt-controller/watch/application.go:743]: That's probably discussed in the VEP, pardon my laziness, but do we really need a new controller for this? Can't we just add to the VM controller? This adds 3 pretty active threads to virt-controller to manage a single field...

**Review by jean-edouard — COMMENTED** [review]
See in-line. Thanks!

File: pkg/storage/snapshot/restore_test.go [hunk 47]
```diff
@@ -1259,6 +1261,30 @@ var _ = Describe("Restore controller", func() {
 					Entry("wait for dvs when dv phase pending", true, cdiv1.Pending, false),
 					Entry("create dvs when dv doesnt exists", false, cdiv1.PhaseUnset, false),
 				)
+
+				It("should not override existing firmware UUID", func() {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore_test.go:1283]: Added a test case for snapshot content without a firmware, didn't have it before because there were other tests that already covered this case implicitly.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 48]
```diff
@@ -81,6 +83,8 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
 		return response
 	}
 
+	setFirmwareUUIDIfNeeded(vm)
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go]: make sense, adjusted it to `IfEmpty`

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 49]
```diff
@@ -682,6 +685,47 @@ var _ = Describe("VirtualMachine Mutator", func() {
 				Expect(resp.Allowed).To(BeFalse())
 			})
 		})
+
+		It("should assign new UUID when VM template spec lacks one on update", func() {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:682]: Just to clarify—by "upgrade," are we referring specifically to a KubeVirt upgrade? Are we assuming that users or clients might try to modify the VM resource during the virt-operator upgrade or while new virt-api/virt-controller pods are being deployed?

Or did you mean a regular VM update?

If it's the latter, the virt-controller should patch all existing VMs so that, on the next resource update, they will already have a firmware UUID set.

File: pkg/virt-controller/watch/vm/firmware.go (hunk 44 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: Nice, fixed.

File: pkg/virt-controller/watch/application.go (hunk 46 above)
Comment (dasionov) [reply pkg/virt-controller/watch/application.go:743]: true

**Comment by dasionov** [comment]
Change: [d5b96a0](https://github.com/kubevirt/kubevirt/commit/d5b96a012984dec96e3a6816a073ccd47dac7ced), [a79e072](https://github.com/kubevirt/kubevirt/commit/a79e07258079f0028c0ed873c73a1a1f1f7e3059): Rebases

File: pkg/virt-controller/watch/vm/firmware.go (hunk 45 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: True, done.

File: pkg/virt-controller/watch/application.go (hunk 46 above)
Comment (jean-edouard) [reply pkg/virt-controller/watch/application.go:743]: I do believe it is too much and not worth it, but I'd like to hear other opinions.
A function in the VM controller feels separate enough.
This was somehow marked as resolved, not sure how to undo.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go (hunk 49 above)
[the remark this answers is not in the document]
Comment (jean-edouard) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:683]: KubeVirt upgrade.
Say you:
- Deploy KubeVirt 1.5
- Create and start a VM, it will have a legacy UUID and an empty `vm.Spec.Template.Spec.Domain.Firmware.UUID`, right?
- Stop the VM (so it won't be updated by the controller)
- Upgrade KubeVirt to 1.6
- Edit the VM to change an unrelated field

That will trigger the mutator, which will see the empty UUID and set a new UUID, effectively changing the VM's UUID, no?
Again, I'm sure I'm missing something here, just trying to get the big picture.

File: pkg/virt-controller/watch/application.go (hunk 46 above)
Comment (dasionov) [reply pkg/virt-controller/watch/application.go:743]: My apologies, probably miss clicked :(

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go (hunk 49 above)
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:683]: If I understand informers correctly, they start by listing all resources in the cluster and then populate their cache. As a result, when the new controller is deployed in KubeVirt 1.6, the vmInformer will list all VMs—both stopped and running—and enqueue them for processing. This ensures that all VMs are patched with firmware and UUIDs during the upgrade. I’m relying on this behavior to guarantee that all VMs are updated, leaving users with no opportunity to modify their VMs during this brief window.

To further ensure this, we could deploy virt-controller before deploying virt-api.
However, IMO, this step might  be taking this too far.

[the remark this answers is not in the document]
Comment (jean-edouard) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:683]: @vladikr WDYT?

File: pkg/virt-controller/watch/application.go [hunk 50]
```diff
@@ -978,6 +987,9 @@ func (vca *VirtControllerApp) AddFlags() {
 	flag.IntVar(&vca.vmControllerThreads, "vm-controller-threads", defaultControllerThreads,
 		"Number of goroutines to run for vm controller")
 
+	flag.IntVar(&vca.firmwareControllerThreads, "vm-firmware-controller-threads", defaultControllerThreads,
```
Comment (akalenyu) [inline pkg/virt-controller/watch/application.go:990]: If we end up going the new controller path, do we really need 3 threads here? Since this controller does very little and the control loop is blazing fast, maybe 1 is enough?

File: pkg/virt-controller/watch/application.go (hunk 46 above)
Comment (akalenyu) [reply pkg/virt-controller/watch/application.go:743]: Summarizing some offline chats;
We found the new controller path a little concerning since it's only ever going to run once and remain idle for eternity
(Upgrade->New controller image->Control loop executed for all matching VMs->Success->Idle)

Could we maybe have the operator manage a job that accomplishes this?

/cc @EdDev @enp0s3

File: pkg/virt-controller/watch/vm/firmware.go [hunk 51]
```diff
@@ -0,0 +1,169 @@
...
+				Clock: clock.RealClock{},
+			},
+		),
+		vmIndexer: vmInformer.GetIndexer(),
+		recorder:  recorder,
+	}
+
+	if _, err := vmInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc:    c.enqueueVM,
+		UpdateFunc: func(_, new any) { c.enqueueVM(new) },
```
Comment (akalenyu) [inline pkg/virt-controller/watch/vm/firmware.go:46]: Again, if we end up going the new controller path, should we harden the requirement for actually executing the control loop? So it's not invoked when not needed?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go (hunk 49 above)
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go]: @dasionov @jean-edouard I'm a bit confused too...
I thought that we are only setting a new UUID in the mutator on NEW and not on UPDATE - is it not the case?

Also, @dasionov, I'm not sure that this is guaranteed behaviour with the informer...  @xpivarc are we sure that all VMs we get re-enqueued?

[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go]: > @dasionov @jean-edouard I'm a bit confused too... I thought that we are only setting a new UUID in the mutator on NEW and not on UPDATE - is it not the case?

My apologies for the confusion — let me clarify.
You're right, the original design was to assign a new UUID only during VM creation in the mutator. However, due to [this comment](https://github.com/kubevirt/kubevirt/pull/14130#discussion_r1986831059), I initially assumed that if a user explicitly removes the UUID, it's an indication that they want a new one to be generated. Based on that interpretation, I added logic to also assign a UUID on update.

That turned out to be a mistake, as it introduced a race condition between the controller and the mutator. I've since reverted the change and restored the original behavior: the UUID is now only assigned during VM creation. Sorry again for the confusion around this.

This is also why we can't enforce the presence of the firmware field through a validating webhook — doing so would introduce a similar race during upgrades. For example, if a user tries to update an unrelated field on a VM that hasn't yet been processed by the controller, the webhook would reject the update due to the missing firmware field, even though it's not the user's fault.

> Also, @dasionov, I'm not sure that this is guaranteed behaviour with the informer... @xpivarc are we sure that all VMs we get re-enqueued?

Since the UUID is now only assigned on VM creation, I believe the race condition issue should be resolved, right?

File: pkg/virt-controller/watch/application.go (hunk 50 above)
Comment (dasionov) [reply pkg/virt-controller/watch/application.go]: reverted this controller to work as synchronizer in the main controller, so no new flags, no new controller
just a simple patch when needed

File: pkg/virt-controller/watch/vm/firmware.go (hunk 51 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: removed this part to work with synchronizer over a full new controller

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: Also, the controller will never see the VM without UUID if the webhook mutates it

File: pkg/virt-controller/watch/vm/firmware.go [hunk 52]
```diff
@@ -0,0 +1,110 @@
...
+
+func (fc *FirmwareController) Sync(vm *v1.VirtualMachine, _ *v1.VirtualMachineInstance) (*v1.VirtualMachine, error) {
+	vmCopy := vm.DeepCopy()
+	legacyUUID := CalculateLegacyUUID(vmCopy.Name)
+
+	if vmCopy.Spec.Template.Spec.Domain.Firmware == nil {
+		vmCopy.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{UUID: legacyUUID}
+	} else if vmCopy.Spec.Template.Spec.Domain.Firmware.UUID == "" {
+		vmCopy.Spec.Template.Spec.Domain.Firmware.UUID = legacyUUID
+	}
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware.go:73]:
```suggestion
	if vmCopy.Spec.Template.Spec.Domain.Firmware == nil {
		vmCopy.Spec.Template.Spec.Domain.Firmware = &v1.Firmware{}
	} 
	if vmCopy.Spec.Template.Spec.Domain.Firmware.UUID == "" {
		vmCopy.Spec.Template.Spec.Domain.Firmware.UUID = legacyUUID
	}
```

Keep that pattern?

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 53]
```diff
@@ -0,0 +1,97 @@
...
+	"k8s.io/client-go/testing"
+
+	v1 "kubevirt.io/api/core/v1"
+	"kubevirt.io/client-go/kubevirt/fake"
+
+	"kubevirt.io/kubevirt/pkg/libvmi"
+)
+
+var _ = Describe("VM Firmware Controller", func() {
+	It("sync does nothing when", func() {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:37]: when what?

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 54]
```diff
@@ -0,0 +1,97 @@
...
+		vm := libvmi.NewVirtualMachine(libvmi.New())
+		vm.Spec.Template.Spec.Domain.Firmware = nil
+
+		_, err := clientset.KubevirtV1().VirtualMachines(vm.Namespace).Create(context.Background(), vm, k8smetav1.CreateOptions{})
+		Expect(err).NotTo(HaveOccurred())
+
+		originalVM := vm.DeepCopy()
+		updatedVM, err := fc.Sync(vm, nil)
+		Expect(err).To(HaveOccurred())
+		Expect(err).To(MatchError(ContainSubstring(injectedPatchError.Error())))
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:67]:
```suggestion
		Expect(err).To(MatchError(injectedPatchError))
```

Does that work?

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 55]
```diff
@@ -0,0 +1,97 @@
...
+
+		vm := libvmi.NewVirtualMachine(libvmi.New())
+		vm.Spec.Template.Spec.Domain.Firmware = nil
+
+		_, err := clientset.KubevirtV1().VirtualMachines(vm.Namespace).Create(context.Background(), vm, k8smetav1.CreateOptions{})
+		Expect(err).NotTo(HaveOccurred())
+
+		originalVM := vm.DeepCopy()
+		updatedVM, err := fc.Sync(vm, nil)
+		Expect(err).To(HaveOccurred())
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:66]: Not necessary when using MatchError

File: pkg/virt-controller/watch/vm/firmware_test.go [hunk 56]
```diff
@@ -0,0 +1,97 @@
...
+			})
+
+		vm := libvmi.NewVirtualMachine(libvmi.New())
+		vm.Spec.Template.Spec.Domain.Firmware = nil
+
+		_, err := clientset.KubevirtV1().VirtualMachines(vm.Namespace).Create(context.Background(), vm, k8smetav1.CreateOptions{})
+		Expect(err).NotTo(HaveOccurred())
+
+		originalVM := vm.DeepCopy()
+		updatedVM, err := fc.Sync(vm, nil)
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vm/firmware_test.go:65]: Do we need some kind of sanityExecute as for other controllers? To make sure the informer caches are not corrupted?

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 54 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go:67]:
```
  [FAILED] Expected
      <*vm.syncError | 0xc00032e580>: 
      error encountered when trying to patch VM firmware: test patch error
      {
          err: <*errors.errorString | 0xc0005a8a30>{
              s: "error encountered when trying to patch VM firmware: test patch error",
          },
          reason: "FirmwareUUIDError",
      }
  to match error
      <*errors.errorString | 0xc0005a83c0>: 
      test patch error
      {
          s: "test patch error",
      }
```

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 56 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go:65]: we only manipulate a copy

**Comment by dasionov** [comment]
[Change:](https://github.com/kubevirt/kubevirt/compare/e354f2e3207bfe490705252bc86a32761c1e3617..a2e3c9a3592e939e334e0c10ec683046af4c86ee) Adress @0xFelix comments

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 53 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware_test.go]: fixed the test name

File: pkg/virt-controller/watch/vm/firmware.go (hunk 52 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vm/firmware.go]: fixed

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: The web-hook will mutate only new vms, existing ones will be handled by the controller, and patched with legacy uuid calculation to make sure it's persisted.

i am not fully understand your concern here

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 56 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware_test.go:65]: That's the point of sanityExecute, it ensures we are only working on copies. :)

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: That means we can go from `VM with new UUID > VM without UUID > VM with legacy UUID` again?

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 56 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware_test.go:65]: If we don't have an informer there might be no point in adding it though.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: Yes, the scope of this PR is to fix a bug that has existed in KubeVirt for many years.
It might not be perfect, but it solves the core issue and prevents it from spreading further to other clients — which is the main priority.

Your concern is valid in cases where users manually remove their own UUIDs for some reason.
However, I believe we can't fully support such scenarios, and IMO users who take these actions should be held responsible for the consequences.

[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:86]: I don't understand what speaks against letting this hook also mutate the UUID on an update?

**Review by Acedus — COMMENTED** [review]
Preliminary review, please see inline comments.

File: pkg/storage/snapshot/restore.go [hunk 57]
```diff
@@ -867,13 +868,24 @@ func (t *vmRestoreTarget) reconcileSpec(restoredVM *kubevirtv1.VirtualMachine) (
 		return false, err
 	}
 
+	sourceVM, err := t.getSnapshotVM()
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go:871]: it does make sense, but the main issue i have is how do i handle restore case when someone want to change the vm name.
changed name -> changed uuid -> no need to restore uuid based on the old name in this case.
if i call the `setLegacyFirmwareUUID` at `generateRestoredVMSpec` it will be too soon

[the remark this answers is not in the document]
Comment (Acedus) [reply pkg/storage/snapshot/restore.go:871]: Maybe I'm missing something, shouldn't it just be something along the lines of:
```go
if newVM.Name == snapshotVM.Name {
    setLegacyFirmwareUUID(newVM)
}
```

[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go:871]: after we restore a vm, under `reconcileSpec` if the target doesn't exist we apply patches to it, the patches can include a name patch to change the name of the vm, at this point i perform the check:
```
restoredVM, err = patchVM(restoredVM, t.vmRestore.Spec.Patches)
if err != nil {
	return false, fmt.Errorf("error patching VM %s: %v", restoredVM.Name, err)
}
if restoredVM.Name == sourceVM.Name {
	setLegacyFirmwareUUID(restoredVM)
}
```
can't do it before that, unless you want me to ensure the patches aren't including one for the `metadata/name`

[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: fixed, thanks!

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/623d2b23a60b76e6473e14770862bc383296e863..773f7aa84c70f8bf17725819fd1844b353db4d97): Rebase

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/a2e3c9a3592e939e334e0c10ec683046af4c86ee..623d2b23a60b76e6473e14770862bc383296e863): Address @Acedus comments

File: pkg/storage/snapshot/restore.go [hunk 58]
```diff
@@ -855,6 +856,7 @@ func (t *vmRestoreTarget) generateRestoredVMSpec(snapshotVM *snapshotv1.VirtualM
 	newVM.Spec.DataVolumeTemplates = newTemplates
 	newVM.Spec.Template.Spec.Volumes = newVolumes
 	setLastRestoreAnnotation(t.vmRestore, newVM)
+	setLegacyFirmwareUUID(newVM)
```
Comment (Acedus) [inline pkg/storage/snapshot/restore.go:859]: What if `t.vmRestore.Spec.Target.Name != snapshotVM.Name`?

Comment (dasionov) [reply pkg/storage/snapshot/restore.go]: I changed the condition so It only restore the uuid for snapshot vms that have the same name as the target.

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/bae5a4d70b329e23b04c6bccd98b8bea6ae7a92c..7e57a8f6988e601781dd46c0d17350dfb406c7d2): Rebase

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/7e57a8f6988e601781dd46c0d17350dfb406c7d2..9d7f90f56f78326b683b1f39cbad90d845fcf2ec): Document that on updates vms without uuid won't be assigned new uuid

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/16a2e2f8db0e28c30b0e00023a4baa668a4058d3..c55874d6f2fc471d85a4a33a70529c197de54f94): Rebase

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/c55874d6f2fc471d85a4a33a70529c197de54f94..4f7451848a8716e42bebf758c2ba2b005960e6f0): Rebase

**Review by enp0s3 — COMMENTED** [review]
/approve
@dasionov Thank you!

File: pkg/storage/snapshot/restore_test.go [hunk 59]
```diff
@@ -1259,6 +1261,48 @@ var _ = Describe("Restore controller", func() {
...
+					vmRestoreSource.Add(r)
+
+					addVM(vm)
+					updatedVM := createSnapshotVM()
+					updatedVM.Status.RestoreInProgress = &vmRestoreName
+					updatedVM.ResourceVersion = "1"
+					updatedVM.Annotations = map[string]string{"restore.kubevirt.io/lastRestoreUID": "restore-uid"}
+					updatedVM.Spec.DataVolumeTemplates[0].Name = "restore-uid-disk1"
+					updatedVM.Spec.Template.Spec.Volumes[0].DataVolume.Name = "restore-uid-disk1"
+					setLegacyFirmwareUUID(updatedVM)
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1276]: I understood the controller should set the UUID?

File: pkg/storage/snapshot/restore_test.go [hunk 60]
```diff
@@ -1259,6 +1261,48 @@ var _ = Describe("Restore controller", func() {
...
+					expectVMUpdate(kubevirtClient, updatedVM)
+					res, err := targetVM.Reconcile()
+					Expect(err).ShouldNot(HaveOccurred())
+					Expect(res).To(BeTrue())
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1280]: Shouldn't you check the UUID is not empty here?

File: pkg/storage/snapshot/restore_test.go [hunk 61]
```diff
@@ -1259,6 +1261,48 @@ var _ = Describe("Restore controller", func() {
...
+					updatedVM.Status.RestoreInProgress = &vmRestoreName
+					updatedVM.ResourceVersion = "1"
+					updatedVM.Annotations = map[string]string{"restore.kubevirt.io/lastRestoreUID": "restore-uid"}
+					updatedVM.Spec.DataVolumeTemplates[0].Name = "restore-uid-disk1"
+					updatedVM.Spec.Template.Spec.Volumes[0].DataVolume.Name = "restore-uid-disk1"
+					updatedVM.Spec.Template.Spec.Domain.Firmware = &kubevirtv1.Firmware{UUID: uid}
+					expectVMUpdate(kubevirtClient, updatedVM)
+					res, err := targetVM.Reconcile()
+					Expect(err).ShouldNot(HaveOccurred())
+					Expect(res).To(BeTrue())
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1304]: Same, shouldn't you assert here that the UUID has not changed?

File: pkg/storage/snapshot/restore_test.go [hunk 62]
```diff
@@ -1761,6 +1803,7 @@ var _ = Describe("Restore controller", func() {
 
 					updatedVM := originalVM.DeepCopy()
 					updatedVM.Annotations = map[string]string{lastRestoreAnnotation: "restore-uid"}
+					setLegacyFirmwareUUID(updatedVM)
```
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1806]: What does this prevent here?

File: pkg/storage/snapshot/restore_test.go
Comment (0xFelix) [inline pkg/storage/snapshot/restore_test.go:1]: Can you help me to understand why adding `setLegacyFirmwareUUID` to seemingly unrelated tests is required?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 63]
```diff
@@ -677,11 +680,51 @@ var _ = Describe("VirtualMachine Mutator", func() {
 				Expect(resp.Allowed).To(BeFalse())
 			})
 		})
+
+		It("should NOT assign new UUID when VM template spec lacks one on update", func() {
+			oldVM.Spec.Template.Spec.Domain.Firmware = nil
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:685]: `oldVM` should have a UUID in this case?

File: pkg/virt-controller/watch/vm/firmware_test.go (hunk 56 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vm/firmware_test.go:65]: Sanity execute might still be a thing, i.e. checking that VMs that are passed in to this controller are not modified. The VMs source could still be an informer.

File: pkg/storage/snapshot/restore_test.go
Comment (dasionov) [reply pkg/storage/snapshot/restore_test.go:1]: see [explanation](https://github.com/kubevirt/kubevirt/pull/14130#discussion_r2084629584)

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go (hunk 63 above)
Comment (dasionov) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:685]: it's doesn't matter IMO, since we only want to see nil stays nil
i don't mind adding some "existing-uid" and asserting it stays "existing-uid"

File: pkg/storage/snapshot/restore_test.go (hunk 61 above)
Comment (dasionov) [reply pkg/storage/snapshot/restore_test.go:1304]: No need for that, if there was a change in the controller, the fake api call to Update would have failed here

https://github.com/kubevirt/kubevirt/blob/0feef3b9bec37286a2a098eb714e84337be65964/pkg/storage/snapshot/restore_test.go#L2070

File: pkg/storage/snapshot/restore_test.go (hunk 60 above)
Comment (dasionov) [reply pkg/storage/snapshot/restore_test.go:1280]: I don't think it's needed in this case

**Review by 0xFelix — COMMENTED** [review]
Can you please keep the Expects that assert the firmware controller does not alter objects that were passed into it?

**Comment by dasionov** [comment]
> Can you please keep the Expects that assert the firmware controller does not alter objects that were passed into it?

Added `Expect(vm).To(Equal(originalVM))` after calling the `Sync` and passing the vm into it
should be fine like this

**Review by 0xFelix — APPROVED** [review]
Thanks

/lgtm

**Comment by Barakmor1** [comment]
It would be nice to add a comment in the virt-controller firmware default logic, noting that it can be removed in X releases, so it isn’t forgotten.

**Comment by dasionov** [comment]
> It would be nice to add a comment in the virt-controller firmware default logic, noting that it can be removed in X releases, so it isn’t forgotten.

We got https://github.com/kubevirt/enhancements/issues/14 to track the removal of this legacy code in kubevirt-1.9
