### PR TITLE
Use fedora VMI for testing soft-reboot w/ ACPI enabled

### LINKED ISSUE #16114: Incorrect check in soft reboot test for vmi with ACPI feature enabled
**What happened**:
In the test `Softreboot a VirtualMachineInstance soft reboot vmi with ACPI feature enabled should succeed`, the check that verifies whether the VMI actually rebooted is broken and is causing false-positive success. That is, the check `waitForVMIRebooted` passes even if the VMI is not actually rebooted. This also creates a race condition where the condition check is evaluated even before reboot is triggered, and the test passes even if the VMI is unable to successfully carry out the reboot.

This is because of two reasons that work together:
1. The test uses the `CirrOS` OS image to create the VMI. In CirrOS, there is no service (such as `systemd-update-utmp`) that would update the `/var/log/wtmp` file with reboot timestamp information. Therefore the output of the command `last reboot` is always the following.
    ```
    $ last reboot
    BusyBox v1.23.2 (2017-11-20 02:37:12 UTC) multi-call binary.

    Usage: last

    Show listing of the last users that logged into the system

    ```

2. In the `waitForVMIRebooted` function, the output of the `last reboot | grep reboot |  wc -l` command is compared against a regular expression using the `&expect.BExp{R: "2"},` expression. This expression resolves to a regular expression `fmt.Sprintf("%s%s%s%s%s", previousSend, "((?s).*)", bExp.R, "((?s).*)", PromptExpression)`. The resolved regular expression is thus checking whether the output contains a substring `2`. And currently it is using the output of both `stdout` and `stderr` for checking the regular expression.
The `stderr` output of the `last reboot` command contains the text `BusyBox v1.23.2...` which matches the regular expression, and the `waitForVMIRebooted` function returns with success, even if there are no lines captured by `grep reboot`.

**What you expected to happen**:
The  `waitForVMIRebooted` function should wait until there are the expected number of lines containing the `reboot` string in the output of the `last reboot` command.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

Run the test `Softreboot a VirtualMachineInstance soft reboot vmi with ACPI feature enabled should succeed`.

**Environment**:
- KubeVirt version (use `virtctl version`): `Server Version: version.Info{GitVersion:"v1.6.3", GitCommit:"37a6d88ca6616ba222ff2d78267222aa16e8e7dc", GitTreeState:"clean", BuildDate:"2025-11-11T11:31:51Z", GoVersion:"go1.23.9 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"32", GitVersion:"v1.32.9", GitCommit:"cea7087b31eb788b75934d769a28f058ab309318", GitTreeState:"clean", BuildDate:"2025-09-09T19:37:59Z", GoVersion:"go1.23.12", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: 
    ```yaml
    apiVersion: kubevirt.io/v1
    kind: VirtualMachineInstance
    metadata:
      name: cirros-working
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          maxSockets: 4
          model: host-model
          sockets: 1
          threads: 1
        devices:
          autoattachGraphicsDevice: false
          disks:
          - disk:
              bus: virtio
            name: disk0
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
        features:
          acpi:
            enabled: true
        firmware: {}
        machine:
          type: q35
        memory:
          guest: 128Mi
        resources:
          requests:
            memory: 128Mi
      evictionStrategy: None
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo:devel
          imagePullPolicy: IfNotPresent
        name: disk0
      - cloudInitNoCloud:
          userDataBase64: IyEvYmluL2Jhc2gKZWNobyAnaGVsbG8nCg==
        name: cloudinitdisk
    ```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by harshitgupta1337**
#### Before this PR: 
The soft reboot test uses a CirrOS-based VMI, which does not log the reboot timestamps in the `/var/log/wtmp` file. The tests still pass as false positives as described issue #16114 .

#### After this PR: 
The soft reboot test is updated to use a Fedora based VMI (with explicit disabling of the Qemu Guest Agent service). Fedora has the `systemd-update-utmp` service, which logs reboot timestamps to the `/var/log/wtmp` file.

### References
- Fixes #16114

### Why we need it and why it was done in this way
The following alternatives were considered: Another option is to add the missing utility in CirrOS that logs reboot timestamps. However, CirrOS lacks a package manager and it is non-trivial to add components to a VM based on a minimal image at runtime.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
/lgtm cancel

Leaving that for someone else

File: tests/vmi_lifecycle_test.go [hunk 1]
```diff
@@ -1399,15 +1399,20 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
 
 		It("soft reboot vmi with ACPI feature enabled should succeed", decorators.Conformance, func() {
-			vmi := libvmops.RunVMIAndExpectLaunch(libvmifact.NewCirros(), vmiLaunchTimeout)
+			vmi := libvmops.RunVMIAndExpectLaunch(libvmifact.NewFedora(), vmiLaunchTimeout)
+			Expect(console.LoginToFedora(vmi)).To(Succeed())
 
-			Expect(console.LoginToCirros(vmi)).To(Succeed())
+			By("Disabling qemu-guest-agent service inside the VMI")
+			err := console.RunCommand(vmi, "sudo systemctl disable --now qemu-guest-agent", 10*time.Second)
+			Expect(err).ToNot(HaveOccurred(), "Should disable qemu-guest-agent service in the VMI")
```
Comment (orelmisan) [inline tests/vmi_lifecycle_test.go]: Could you please elaborate on why the qemu-guest-agent needs to be disabled?

Comment (harshitgupta1337) [reply tests/vmi_lifecycle_test.go]: Sure. Currently the test already expects the VMI to have the `VirtualMachineInstanceAgentConnected` condition missing or false. This is to ensure that when the Libvirt domain is rebooted, the `DOMAIN_REBOOT_ACPI_POWER_BTN` reboot flag is set to reboot via ACPI. If agent is connected, then the reboot takes place via the guest agent.

Previously, the CirrOS image did not have the QEMU Guest Agent, so it was not necessary to explicitly disable the guest agent service.

File: tests/vmi_lifecycle_test.go [hunk 2]
```diff
@@ -1399,15 +1399,20 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
 			Eventually(matcher.ThisVMI(vmi), 30*time.Second, 2*time.Second).Should(matcher.HaveConditionMissingOrFalse(v1.VirtualMachineInstanceAgentConnected))
 
-			err := kubevirt.Client().VirtualMachineInstance(testsuite.GetTestNamespace(vmi)).SoftReboot(context.Background(), vmi.Name)
+			By("Trigger soft reboot")
+			err = kubevirt.Client().VirtualMachineInstance(testsuite.GetTestNamespace(vmi)).SoftReboot(context.Background(), vmi.Name)
 			Expect(err).ToNot(HaveOccurred())
 
-			waitForVMIRebooted(vmi, console.LoginToCirros)
+			By("Waiting for VMI to reboot")
+			waitForVMIRebooted(vmi, console.LoginToFedora)
```
Comment (xpivarc) [inline tests/vmi_lifecycle_test.go:1415]: Should we also improve this assert ?

Comment (harshitgupta1337) [reply tests/vmi_lifecycle_test.go:1415]: Do you mean making the regex check more strict?

Comment (xpivarc) [reply tests/vmi_lifecycle_test.go:1415]: yes

Comment (harshitgupta1337) [reply tests/vmi_lifecycle_test.go:1415]: Yes I think that would be a good improvement. Currently the regular expression is just looking for the presence of a substring in the command's output (including both stdout and stderr). I suppose it can be restricted by only allowing leading and trailing whitespace characters (e.g., \r or \n) but nothing else.

Comment (harshitgupta1337) [reply tests/vmi_lifecycle_test.go:1415]: Although it would be better to carry out this improvement in a separate PR.

File: tests/vmi_lifecycle_test.go (hunk 1 above)
Comment (orelmisan) [reply tests/vmi_lifecycle_test.go]: Thanks, I wasn't aware of this [logic](https://github.com/kubevirt/kubevirt/blob/8fc858ec90e451cb62b2d623497f38c1f26168b3/pkg/virt-launcher/virtwrap/manager.go#L2068).

@xpivarc, I'm wondering if we need to explicitly control the reboot mechanism here, as according to the libvirt [docs](https://www.libvirt.org/html/libvirt-libvirt-domain.html#virDomainReboot):
> If flags is set to zero, then the hypervisor will choose the method of shutdown it considers best. 

If setting flags to zero allows the hypervisor to select the optimal method, do we really need this level of explicit control in our logic?
