### PR TITLE
instancetype: Refactor and fix inferFromVolume functional tests

### LINKED ISSUE #9805: `inferFromVolume` functional tests skipped in `sig-compute` jobs
/area instancetype

**What happened**:

As highlighted in #9804 the `inferFromVolume` functional tests are currently skipped by the compute job:

https://github.com/kubevirt/kubevirt/blob/cc55a57526331102cd73b59e8ddf285f25e7d9fb/tests/instancetype_test.go#L992-L995

This really shouldn't be the case as there's not direct requirement between the feature and underlying storage class being used.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

Using the `local` SC is causing more headaches as the underlying size of the disk provided to the nodes isn't big enough to accommodate the `34Gi` `PVs`.

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

As discovered in #9805 these functional tests have actually not been
running for some time now. The ultimate goal of this refactor is to
allow these tests to run once again under the default `local`
storageclass provided by kubevirtci.

The following changes were made to the tests to accommodate this:

- Remove the use of Ordered
- Remove the dependency on a RWO block StorageClass
- Validate the VirtualMachine prior to any attempt to start
- Use a DataVolume to orchestrate the creation of the source PVC
- Use of the ForceBinding annotation to ensure the PVC is bound
- Use libdv to build DataVolume objects
- Add TODOs for possible libdv and other follow ups (posted as a draft https://github.com/kubevirt/kubevirt/pull/9885 to avoid blocking this PR)
-  Remove unlabelled DataVolume but labelled source tests until bug #9894 is resolved

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9805

**Special notes for your reviewer**:

Depends on https://github.com/kubevirt/kubevirt/pull/9810

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: tests/instancetype_test.go [hunk 1]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-
-		BeforeEach(func() {
-			By("Creating an annotated source PVC")
-			sourcePVC = libstorage.NewPVC(pvcSourceName, "1Gi", blockStorageClass)
-			sourcePVCVolumeBlockMode := k8sv1.PersistentVolumeBlock
-			sourcePVC.Spec.VolumeMode = &sourcePVCVolumeBlockMode
-			sourcePVC.Labels = map[string]string{
+			By("Creating source DataVolume and PVC")
+			sourceDV = libdv.NewDataVolume(
+				libdv.WithNamespace(util.NamespaceTestDefault),
```
Comment (0xFelix) [inline tests/instancetype_test.go:1007]: Same as above.

File: tests/instancetype_test.go [hunk 2]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+				libdv.WithForceBindAnnotation(),
+				libdv.WithBlankImageSource(),
+				libdv.WithPVC(libdv.PVCWithAccessMode(k8sv1.ReadWriteOnce), libdv.PVCWithVolumeSize("1G")),
+			)
+			// TODO - Add withDefault{Instancetype,Preference}Label support to libdv
```
Comment (0xFelix) [inline tests/instancetype_test.go:1012]: Do this right away? Doesn's seem to be too big of a change.

File: tests/instancetype_test.go [hunk 3]
```diff
@@ -1325,86 +1094,112 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+								},
 							},
 						},
-					},
+					}
+					dataSource, err := virtClient.CdiClient().CdiV1beta1().DataSources(util.NamespaceTestDefault).Create(context.Background(), dataSource, metav1.CreateOptions{})
+					Expect(err).ToNot(HaveOccurred())
+
+					dataVolume := libdv.NewDataVolume(
+						libdv.WithNamespace(util.NamespaceTestDefault),
```
Comment (0xFelix) [inline tests/instancetype_test.go:1185]: Same as above.

File: tests/instancetype_test.go [hunk 4]
```diff
@@ -1325,86 +1094,112 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+						libdv.WithForceBindAnnotation(),
+						libdv.WithPVC(libdv.PVCWithAccessMode(k8sv1.ReadWriteOnce), libdv.PVCWithVolumeSize("1G")),
+					)
+
+					// TODO - Add WithDataVolumeSourceRef support to libdv and use here
+					dataVolume.Spec.SourceRef = &cdiv1beta1.DataVolumeSourceRef{
+						Kind:      "DataSource",
+						Namespace: &util.NamespaceTestDefault,
```
Comment (0xFelix) [inline tests/instancetype_test.go:1193]: Same as above.

File: tests/instancetype_test.go [hunk 5]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-			preference.Name = preferenceName
 			preferredCPUTopology := instancetypev1beta1.PreferCores
 			preference.Spec = instancetypev1beta1.VirtualMachinePreferenceSpec{
 				CPU: &instancetypev1beta1.CPUPreferences{
 					PreferredCPUTopology: &preferredCPUTopology,
 				},
 			}
-			preference, err = virtClient.VirtualMachinePreference(util.NamespaceTestDefault).
-				Create(context.Background(), preference, metav1.CreateOptions{})
+			preference, err = virtClient.VirtualMachinePreference(util.NamespaceTestDefault).Create(context.Background(), preference, metav1.CreateOptions{})
```
Comment (0xFelix) [inline tests/instancetype_test.go:1003]: Same as above.

File: tests/instancetype_test.go [hunk 6]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+			)
+			// TODO - Add withDefault{Instancetype,Preference}Label support to libdv
+			sourceDV.Labels = map[string]string{
 				instancetypeapi.DefaultInstancetypeLabel:     instancetype.Name,
 				instancetypeapi.DefaultInstancetypeKindLabel: instancetypeapi.SingularResourceName,
 				instancetypeapi.DefaultPreferenceLabel:       preference.Name,
 				instancetypeapi.DefaultPreferenceKindLabel:   instancetypeapi.SingularPreferenceResourceName,
 			}
-			sourcePVC, err = virtClient.CoreV1().PersistentVolumeClaims(util.NamespaceTestDefault).Create(context.Background(), sourcePVC, metav1.CreateOptions{})
+			sourceDV, err = virtClient.CdiClient().CdiV1beta1().DataVolumes(util.NamespaceTestDefault).Create(context.Background(), sourceDV, metav1.CreateOptions{})
```
Comment (0xFelix) [inline tests/instancetype_test.go:1019]: Same as above.

File: tests/instancetype_test.go [hunk 7]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-			sourcePVC = libstorage.NewPVC(pvcSourceName, "1Gi", blockStorageClass)
-			sourcePVCVolumeBlockMode := k8sv1.PersistentVolumeBlock
-			sourcePVC.Spec.VolumeMode = &sourcePVCVolumeBlockMode
-			sourcePVC.Labels = map[string]string{
+			By("Creating source DataVolume and PVC")
+			sourceDV = libdv.NewDataVolume(
+				libdv.WithNamespace(util.NamespaceTestDefault),
+				libdv.WithForceBindAnnotation(),
+				libdv.WithBlankImageSource(),
+				libdv.WithPVC(libdv.PVCWithAccessMode(k8sv1.ReadWriteOnce), libdv.PVCWithVolumeSize("1G")),
```
Comment (0xFelix) [inline tests/instancetype_test.go:1010]: `1G` or `1Gi`?

File: tests/instancetype_test.go [hunk 8]
```diff
@@ -946,102 +947,77 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-			if !blockStorageClassExists {
-				Skip("Skip test when RWOBlock storage class is not present")
-			}
-
 			By("Creating a VirtualMachineInstancetype")
 			instancetype = newVirtualMachineInstancetype(nil)
-			instancetype.Name = instancetypeName
-			instancetype, err = virtClient.VirtualMachineInstancetype(util.NamespaceTestDefault).
-				Create(context.Background(), instancetype, metav1.CreateOptions{})
+			instancetype, err = virtClient.VirtualMachineInstancetype(util.NamespaceTestDefault).Create(context.Background(), instancetype, metav1.CreateOptions{})
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply tests/instancetype_test.go:992]: There are too many occurences of `util.NamespaceTestDefault` to mention them all separately.

File: tests/instancetype_test.go (hunk 2 above)
Comment (lyarwood) [reply tests/instancetype_test.go:1012]: I'd like to backport this to `release-1.0` so I'd rather not include it here.

File: tests/instancetype_test.go [hunk 9]
```diff
@@ -1427,86 +1182,112 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+						Namespace: &namespace,
+						Name:      dataSource.Name,
+					}
+
+					return []v1.DataVolumeTemplateSpec{{
+						ObjectMeta: metav1.ObjectMeta{
+							Name: dataVolumeTemplateName,
+						},
+						Spec: dataVolume.Spec,
+					}}
```
Comment (0xFelix) [inline tests/instancetype_test.go:1242]: Maybe dedup this and same block below?

File: tests/instancetype_test.go [hunk 10]
```diff
@@ -1427,86 +1182,112 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-					},
-					Spec: cdiv1beta1.DataSourceSpec{
-						Source: cdiv1beta1.DataSourceSource{
-							PVC: &cdiv1beta1.DataVolumeSourcePVC{
-								Name:      pvcSourceName,
-								Namespace: util.NamespaceTestDefault,
+						Spec: cdiv1beta1.DataSourceSpec{
+							Source: cdiv1beta1.DataSourceSource{
+								PVC: &cdiv1beta1.DataVolumeSourcePVC{
+									Name:      sourceDV.Name,
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply tests/instancetype_test.go:1263]: Yeah fair, this could pickup the labels from the underlying `PVC` instead of this `DataSource`. I'll create a blank `PVC` here.

File: tests/instancetype_test.go (hunk 9 above)
Comment (lyarwood) [reply tests/instancetype_test.go:1242]: Yup will do

File: tests/instancetype_test.go [hunk 11]
```diff
@@ -1427,86 +1193,113 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-						Name: dataVolumeTemplateName,
-					},
-					Spec: cdiv1beta1.DataVolumeSpec{
-						SourceRef: &cdiv1beta1.DataVolumeSourceRef{
-							Name:      dataSourceName,
-							Kind:      "DataSource",
-							Namespace: &util.NamespaceTestDefault,
+			Entry(", DataVolumeSourceRef and DataSource with labels",
+				func() []v1.DataVolumeTemplateSpec {
+					By("Createing a blank DV and PVC without labels")
```
Comment (0xFelix) [inline tests/instancetype_test.go:1253]: nit: typo

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks!

File: tests/instancetype_test.go [hunk 12]
```diff
@@ -1427,86 +1193,113 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
+							Name: dataVolumeTemplateName,
 						},
-						Storage: &cdiv1beta1.StorageSpec{},
-					},
-				}}, nil,
+						Spec: dv.Spec,
+					}}
+				},
 			),
 			Entry(", DataVolumeSourceRef and DataSource",
```
Comment (iholder101) [inline tests/instancetype_test.go:1214]: nit
```suggestion
			Entry("DataVolumeSourceRef and DataSource",
```

**Review by iholder101 — COMMENTED** [review]
Thank you @lyarwood!

File: tests/instancetype_test.go [hunk 13]
```diff
@@ -1048,107 +1050,95 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
...
-			preference              *instancetypev1beta1.VirtualMachinePreference
-			sourcePVC               *k8sv1.PersistentVolumeClaim
-			blockStorageClass       string
-			blockStorageClassExists bool
+			err          error
+			vm           *v1.VirtualMachine
+			instancetype *instancetypev1beta1.VirtualMachineInstancetype
+			preference   *instancetypev1beta1.VirtualMachinePreference
+			sourceDV     *cdiv1beta1.DataVolume
+			namespace    string
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply tests/instancetype_test.go:1060]: https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-runs-parallel-specs

Thankfully this isn't required, when ran in parallel the specs actually end up in different processes with their own memory allocations so we don't have to worry about tests racing each other here.

File: tests/instancetype_test.go (hunk 12 above)
Comment (lyarwood) [reply tests/instancetype_test.go:1214]: This should result in a description of `should infer defaults from DataVolumeTemplates,  DataVolumeSourceRef and DataSource`?

File: tests/instancetype_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (iholder101) [reply tests/instancetype_test.go:1060]: Interesting!
You learn something new everyday :smile: 

Thanks!

**Comment by iholder101** [comment]
Thanks a lot @lyarwood!
/approve

File: tests/instancetype_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (xpivarc) [reply tests/instancetype_test.go:1060]: Still "global" variables often decrease the readability of the tests because the variable is modified in multiple places.
