### PR TITLE
virt-api: skip clone auth check when DataVolume already exists

### LINKED ISSUE #12204: Should the permissions to clone a PVC (DV's source) while creating VM, still be checked if the DV and PVC are already created?
It's more of a question than a bug. 

**What happened**:
I am trying to create a VM that has datavolume source set to a PVC from different namespace. Let's say [this is](https://gist.github.com/viveksinghggits/92d12aa7dea782cf9f81ea2af0c0e57b) the VM that I have. When I create this VM this is the error that I see

```
The request is invalid: spec.dataVolumeTemplates[0]: Authorization failed, message is: User system:serviceaccount:vmtwo:default has insufficient permissions in clone source namespace vm-source
```

This error message seems logical that the SA is not authz to clone the other namespace, but I was thinking if we should even do this validation if in this particular case the datavolume and respective PVC for the VM are already available in the VM's namespace. Or in other words for this example should we even do this validation if the VM's DV `rhel8-vm-02` and PVC `rhel8-vm-02` are already available in the  `vmtwo` namespace?  

**How to reproduce it (as minimally and precisely as possible)**:
Create the VM mentioned above and we would see an authz related problem.

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does
Before this PR:

Would always do clone authorization check, even if the DataVolume exists.  This can be problematic with clones because the original clone source namespace may have been deleted.  Or in the case of restoring to a different cluster, never exist

After this PR:

Only do clone auth check when DataVolume does not exist.

Fixes #12204

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

Eventually we will probably entirely remove the auth check from virt-api. virt-controller checks auth as well

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
virt-api: skip clone auth check when DataVolume already exists
```

### CODE REVIEW

**Comment by mhenriks** [comment]
cc @akalenyu

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 1]
```diff
@@ -354,16 +357,24 @@ func (admitter *VMsAdmitter) authorizeVirtualMachineSpec(ar *admissionv1.Admissi
...
+				ObjectMeta: dataVolume.ObjectMeta,
+				Spec:       dataVolume.Spec,
+			}
+			dv.Namespace = targetNamespace
+			proxy := &authProxy{client: admitter.VirtClient, dataSourceInformer: admitter.DataSourceInformer, namespaceInformer: admitter.NamespaceInformer}
+			allowed, message, err = admitter.cloneAuthFunc(dv, ar.Namespace, ar.Name, proxy, targetNamespace, serviceAccountName)
+			if err != nil && err != cdiv1.ErrNoTokenOkay {
+				return nil, err
+			}
+		}
```
Comment (akalenyu) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:377]: Can't the auth call remain outside the if branch? I was thinking something like
```suggestion
		if dv == nil {
			dv = &cdiv1.DataVolume{
				ObjectMeta: dataVolume.ObjectMeta,
				Spec:       dataVolume.Spec,
			}
			dv.Namespace = targetNamespace
		}
```
And then initialization of allowed,msg could be dropped

**Review by akalenyu — COMMENTED** [review]
looks good couple of suggestions :pray:

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 2]
```diff
@@ -354,16 +357,24 @@ func (admitter *VMsAdmitter) authorizeVirtualMachineSpec(ar *admissionv1.Admissi
...
-		dv := &cdiv1.DataVolume{
-			ObjectMeta: dataVolume.ObjectMeta,
-			Spec:       dataVolume.Spec,
-		}
-		dv.Namespace = targetNamespace
-		allowed, message, err := admitter.cloneAuthFunc(dv, ar.Namespace, ar.Name, proxy, targetNamespace, serviceAccountName)
-		if err != nil && err != cdiv1.ErrNoTokenOkay {
+		allowed := true
+		message := ""
+		dv, err := storagetypes.GetDataVolumeFromCache(targetNamespace, dataVolume.Name, admitter.DataVolumeInformer.GetStore())
```
Comment (xpivarc) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:362]: Can we do a real request instead?

Comment (akalenyu) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:362]: TBH I am not sure what is best here - this would amplify the request
(many DVs for VM, though not common in practice so still constant).

This webhook runs on create/update but maybe this part is skipped if no spec change occurred,
if not, I think informer makes more sense

File: pkg/virt-api/api.go [hunk 3]
```diff
@@ -1089,13 +1089,16 @@ func (app *virtAPIApp) Run() {
 	app.clusterConfig.SetConfigModifiedCallback(app.shouldChangeRateLimiter)
 
 	var dataSourceInformer cache.SharedIndexInformer
+	var dataVolumeInformer cache.SharedIndexInformer
```
[the remark this answers is not in the document]
Comment (mhenriks) [reply pkg/virt-api/api.go:1092]: That can happen in a follow up didn't want to do anything unnecessary or inconsistent here

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go (hunk 1 above)
Comment (mhenriks) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:377]: Not exactly sure what you are suggesting but I can clean that up

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go (hunk 2 above)
Comment (mhenriks) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:362]: Using informers for other types so being consistent with DataVolumes makes the most sense to me.  THe same auth check is done by virt controller so minor races here are fine this check is just for more obvious user feedback

File: pkg/virt-api/api.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (akalenyu) [reply pkg/virt-api/api.go:1092]: Sure

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 4]
```diff
@@ -354,12 +357,20 @@ func (admitter *VMsAdmitter) authorizeVirtualMachineSpec(ar *admissionv1.Admissi
...
 		}
 
-		proxy := &authProxy{client: admitter.VirtClient, dataSourceInformer: admitter.DataSourceInformer, namespaceInformer: admitter.NamespaceInformer}
-		dv := &cdiv1.DataVolume{
+		dv, err := storagetypes.GetDataVolumeFromCache(targetNamespace, dataVolume.Name, admitter.DataVolumeInformer.GetStore())
+		if err != nil {
+			return nil, err
+		}
+		if dv != nil {
+			continue
```
Comment (akalenyu) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:365]: oh okay so you're skipping auth if dv exists. you could have also passed those to cloneAuthFunc if you wanted but not a must

**Review by akalenyu — APPROVED** [review]

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go (hunk 4 above)
Comment (mhenriks) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:365]: passing to the clone auth func would require that the dv have `prePopulated` annotation and I think that is an unnecessary requirement

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go (hunk 2 above)
Comment (xpivarc) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:360]: >This webhook runs on create/update but maybe this part is skipped if no spec change occurred,
if not, I think informer makes more sense

On update I would assume you could skip the check under some conditions...

>THe same auth check is done by virt controller so minor races here are fine this check is just for more obvious user feedback

Sounds good.

Comment (mhenriks) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:375]: @xpivarc adding a commit to skip auth if dataVolumeTemplates unchanged on update

**Comment by alicefr** [comment]
@mhenriks do you think the flake might be related to this change?

**Comment by akalenyu** [comment]
> @mhenriks do you think the flake might be related to this change?

Sounds exactly like https://github.com/kubevirt/project-infra/pull/3543#issuecomment-2244974070. I'll open a PR

**Comment by mhenriks** [comment]
Thanks @akalenyu!

**Comment by ShellyKa13** [comment]
/hold
you mentioned that you want this PR to get merged before mine : #12628 but the whole point of that PR is to remove this webhook check. So why do we need this PR??

**Comment by mhenriks** [comment]
> /hold So I understand that you want to get this merged to backport it further away and my PR #12628 to revert this changes and do what it does. but why is this PR easier to backport? btw my PR also fixes the issue you mentioned #12204

@ShellyKa13 the issue is that the other PR introduces a change in default API behavior. Across the board API behavior changes are okay for new releases (sometimes) but should not be backported.

**Comment by ShellyKa13** [comment]
Ok then

**Comment by ShellyKa13** [comment]
A new bug was just filed regarding this webhook check, when restoring a vm with dvtemplate with clone. your fix is not enough to fix the bug. I think my PR is the best solutions for all related bugs, and so its more of a bug fix rather then new API change so I think it is ok to backport it.

**Comment by mhenriks** [comment]
> A new bug was just filed regarding this webhook check, when restoring a vm with dvtemplate with clone. your fix is not enough to fix the bug. I think my PR is the best solutions for all related bugs, and so its more of a bug fix rather then new API change so I think it is ok to backport it.

A link to the bug please

**Comment by ShellyKa13** [comment]
https://issues.redhat.com/browse/CNV-47105

**Comment by mhenriks** [comment]
> A new bug was just filed regarding this webhook check, when restoring a vm with dvtemplate with clone. your fix is not enough to fix the bug. I think my PR is the best solutions for all related bugs, and so its more of a bug fix rather then new API change so I think it is ok to backport it.

@ShellyKa13 #12628 is not sufficient to address https://issues.redhat.com/browse/CNV-47105.  The authorization check in the webhook is advisory for the user and yes we want to eventually get rid of it. However, authorization also, and more importantly, happens in virt-controller [here](https://github.com/kubevirt/kubevirt/blob/a0fd036429d074f0abb452f67024e5433ef4df44/pkg/virt-controller/watch/vm.go#L434-L437) and if the namespace still does not exist with appropriate permission virt-controller will not create the DataVolume

Given that this PR directly addresses the issue in a way that is [not controversial](https://github.com/kubevirt/kubevirt/pull/12547#issuecomment-2310056211) to backport I respectfully ask you to remove the hold on this PR and focus discussion on the specific issue addressed here

**Comment by ShellyKa13** [comment]
/unhold
The hold was never applied. but just for the sake of the reader. 
This PR does address the issue mentioned in the description. Can have different discussion about the other bugs.

**Comment by ShellyKa13** [comment]
@mhenriks we want to backport this at least to 1.1 right?
