### PR TITLE
Use native go library for selinux and stop labeling host directories

### LINKED ISSUE #2664: Unable to launch virt-handler v0.20.4 on CoreOS with selinux
/kind bug

**What happened**:
I started kubevirt v0.20.4 using some instructions from https://kubevirt.io/quickstart_minikube/ on a Kubernetes v1.15 cluster running on bare-metal nodes with CoreOS 1883.0.0 (~1yo ...).

**What you expected to happen**:
`virt-handler` fails to start with:
```
{"component":"virt-handler","hostname":"carmd-er-lxtb0cc47a4c27b6","level":"info","pos":"virt-handler.go:187","timestamp":"2019-09-04T06:02:51.362115Z"}
panic: failed to list labels:  

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc0001f6000)
	cmd/virt-handler/virt-handler.go:205 +0x1ad6
main.main()
	cmd/virt-handler/virt-handler.go:457 +0x6e
```

**How to reproduce it (as minimally and precisely as possible)**:
I think running kubevirt on CoreOS should be enough, but hard to say.

**Anything else we need to know?**:
It looks like the `selinux/labels.go` is calling `semanage`, and I couldn't find it in the image.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.20.4
- Kubernetes version (use `kubectl version`): v1.15.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: bare-metal x86-64 servers
- OS (e.g. from /etc/os-release): CoreOS 1883.0.0 (w/ ACS patch)
- Kernel (e.g. `uname -a`): 4.18.5-coreos
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

On some operating systems like CoreOS, python tools like `semanage` are not availabe. `semodule` is written in C and should also be available on CoreOS.

This PR removes the deprecated labeling of shared directories which we needed in the past and uses the native selinux library on as many places as possible.

**Upgrade Considerations**

virt-handler will still work for VMIs which still rely on the correctly labelled directories, since the only way they could ever successfully started is due to the fact that the old virt-handler already labelled the directory accordingly. virt-handler can also still start VMIs during upgrades when it is confronted with a VMI which still relies on it for the same reason: The directory already has the right permissions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2664

**Special notes for your reviewer**:

**Release note**:
```release-note
Use native go libraries for selinux to not rely on python-selinux tools like semanage, which are not always present.
```

### CODE REVIEW

**Comment by CoRfr** [comment]
Still no luck with latest patch:
```
{"component":"virt-handler","hostname":"carmd-er-lxtbd4bed9b5f162","level":"info","pos":"virt-handler.go:187","timestamp":"2019-09-13T15:10:38.492419Z"}
panic: failed to install virt-launcher selinux policy: failed to install policy /var/run/kubevirt/base_container.cil - out: "libsemanage.semanage_create_store: Could not create module store at /var/lib/selinux/mcs. (No such file or directory).\nlibsemanage.semanage_direct_connect: could not establish direct connection (No such file or directory).\n/sbin/semodule:  Could not connect to policy handler\n", error: exit status 1
goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000302300)
	cmd/virt-handler/virt-handler.go:211 +0x1aa2
main.main()
	cmd/virt-handler/virt-handler.go:453 +0x6e
```

**Comment by rmohr** [comment]
> Still no luck with latest patch:

But #2670 works for you, right? We will bring it in first and I will fix this PR in the meantime.

**Comment by CoRfr** [comment]
I tried to see if I could get this PR to work in my env but so far no luck.
I'm not seeing where 'Permissive' (returned by getenforce) returns 'permissive' (lower-case, trimmed) as used is `se.mode == "permissive"`. I tried to print some logs to see things, but it would not show anything in the pod log.

As for #2670 I confirm it still works for me.

**Comment by rmohr** [comment]
> I tried to see if I could get this PR to work in my env but so far no luck.
> I'm not seeing where 'Permissive' (returned by getenforce) returns 'permissive' (lower-case, trimmed) as used is `se.mode == "permissive"`. I tried to print some logs to see things, but it would not show anything in the pod log.

Oh I forgot to trim the output. Updated. It is lowercase because it is not coming from `getenfore`. Instead our go binary directly checks the status.

File: pkg/virt-handler/selinux/labels.go [hunk 1]
```diff
@@ -53,10 +53,11 @@ func (se *SELinuxImpl) IsPresent() (present bool, mode string, err error) {
 	if err != nil {
 		return false, string(out), err
 	}
-	if strings.Contains(string(out), "disabled") {
-		return false, string(out), nil
+	outStr := strings.TrimSpace(string(out))
```
Comment (CoRfr) [inline pkg/virt-handler/selinux/labels.go]: What about the conversion to lower case?

`getenforce` returns `Permissive` and I'm not seeing any ToLower(), so I would be surprised if `outStr == "disabled"` works.

Comment (rmohr) [reply pkg/virt-handler/selinux/labels.go]: the code is here: https://github.com/kubevirt/kubevirt/pull/2694/files#diff-7ff8c074056848ec8628c964418672bfR13, the PR is not using the `getenforce` binary anymore.

Comment (CoRfr) [reply pkg/virt-handler/selinux/labels.go]: Oh right I missed that, it looks like trimming would also be unnecessary then.

Comment (rmohr) [reply pkg/virt-handler/selinux/labels.go]: Hm, it still writes a "newline" which we need to trim.

**Comment by LorbusChris** [comment]
This issue popped up in https://github.com/openshift/okd/issues/77 - and as we're not going to pull python into Fedora CoreOS again, I'd much prefer something like this here.

Any chance we could get this rebased and reviewed again? :)

**Comment by LorbusChris** [comment]
@rmohr friendly ping :)

**Comment by rmohr** [comment]
@LorbusChris thx for the ping. Yes, will rebase it. Thanks for the ping!

File: vendor/github.com/opencontainers/selinux/go-selinux/BUILD.bazel [hunk 2]
```diff
@@ -0,0 +1,9 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_library")
+
+go_library(
+    name = "go_default_library",
+    srcs = ["selinux_stub.go"],
+    importmap = "kubevirt.io/kubevirt/vendor/github.com/opencontainers/selinux/go-selinux",
+    importpath = "github.com/opencontainers/selinux/go-selinux",
+    visibility = ["//visibility:public"],
+)
```
Comment (vladikr) [inline vendor/github.com/opencontainers/selinux/go-selinux/BUILD.bazel]: @rmohr tests are failing because of this file that should look like the below, but it keeps changing after each make generate... 
What did I do wrong? :) 

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "selinux_linux.go",
        "xattrs.go",
    ],
    importmap = "kubevirt.io/kubevirt/vendor/github.com/opencontainers/selinux/go-selinux",
    importpath = "github.com/opencontainers/selinux/go-selinux",
    visibility = ["//visibility:public"],
    deps = select({
        "@io_bazel_rules_go//go/platform:linux": [
            "//vendor/golang.org/x/sys/unix:go_default_library",
        ],
        "//conditions:default": [],
    }),
)

Comment (rmohr) [reply vendor/github.com/opencontainers/selinux/go-selinux/BUILD.bazel]: What was the issue?

Comment (vladikr) [reply vendor/github.com/opencontainers/selinux/go-selinux/BUILD.bazel]: As I understand it and my understanding is very limited :) ,
 `# gazelle:build_tags selinux` was missing from the BUILD.bazel 
and the build command should have looked like `build --define gotags=selinux`

File: cmd/virt-handler/virt-handler.go [hunk 3]
```diff
@@ -312,35 +328,6 @@ func (app *virtHandlerApp) Run() {
 	defer close(stop)
 	factory.Start(stop)
 
-	selinuxLauncherType := clusterConfig.GetSELinuxLauncherType()
```
Comment (davidvossel) [inline cmd/virt-handler/virt-handler.go]: do we not support custom selinux labels for virt-launcher now? maybe that's fine. I don't understand why this existed in the first place.

Comment (vladikr) [reply cmd/virt-handler/virt-handler.go]: As I understand this, the problem was that we didn't manage to install (use `semanage`) on RHCOS / FCOS because this binary wasn't present. As a workaround, we would allow the installation upstream, but on RHCOS we would use a custom policy and that would prevent the installation.
With this PR, we are no longer dependent on python binaries and will use the native selinux library, which will make this workaround irrelevant.

Going forward, we should remove our custom selinux policy completely, I think @jean-edouard is working on a PR.

Comment (vladikr) [reply cmd/virt-handler/virt-handler.go]: The setting of the customer policy is still happening in https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-controller/services/template.go#L988

Comment (rmohr) [reply cmd/virt-handler/virt-handler.go:315]: But we still support our default policy. So istn't removing the `clusterConfig.GetSELinuxLauncherType()` happening due to the fact that the  PR is older than allowing overriding the type? I would expect that we keep this in this PR.

**Comment by LorbusChris** [comment]
Friendly ping, as this needs another rebase :)

**Comment by LorbusChris** [comment]
bumping this again :)

**Comment by vladikr** [comment]
> bumping this again :)

@LorbusChris I'm wondering whether this is required... How do you plan to use it?

**Comment by LorbusChris** [comment]
@vladikr this is needed to run kubevirt on OKD/Fedora CoreOS which doesn't ship `semanage` in the base OS

**Comment by LorbusChris** [comment]
@rmohr friendly ping :)

**Comment by rmohr** [comment]
/hold cancel

Looks good.

**Comment by dustymabe** [comment]
I'm cheering you on @rmohr. I want to test this out as soon as I can.

**Comment by dustymabe** [comment]
anything holding this up other than code review at this point?

**Comment by rmohr** [comment]
Just code review.

**Comment by rmohr** [comment]
> One minor suggestion would be to replace "enabled" by "enforcing" to match the SELinux vocabulary.
> Technically "enabled" would mean not disabled, so either permissive or enforcing, but it's used here to mean enforcing.

:+1: addressed.
