### PR TITLE
instancetype: Apply PreferredStorageClassName to StorageSpec if provided

### LINKED ISSUE #10025: `PreferredStorageClassName` only used when `vm.Spec.DataVolumeTemplates.Spec.PVC` populated
/area instancetype
/cc @RoniKishner

**What happened**:

$subject, not 100% sure if it's safe to always provide `spec.PVC` within a `DataVolume` but at the moment the preference code requires it before applying a storage class:

https://github.com/kubevirt/kubevirt/blob/9292b3ce6faa9841ee9d2d0e98e4f4e97c9d1c70/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go#L199-L205

**What you expected to happen**:

`PreferredStorageClassName` to always be applied when a user has not specified a storage class.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

DataVolumeSpec provides two mutually exclusive ways of defining attributes of the destination volume through either a PersistentVolumeClaimSpec [2] or StorageSpec [3].

Both provide ways of controlling the storageClass of the eventual PVC but as outlined in bug #10025 previously PreferredStorageClassName was only applied to the PersistentVolumeClaimSpec of a DataVolumeSpec.

This change corrects this ensuring PreferredStorageClassName is applied to the StorageSpec if provided within a DataVolumeSpec.

[1] http://kubevirt.io/api-reference/main/definitions.html#_v1beta1_datavolumespec
[2] http://kubevirt.io/api-reference/main/definitions.html#_k8s_io_api_core_v1_persistentvolumeclaimspec
[3] http://kubevirt.io/api-reference/main/definitions.html#_v1beta1_storagespec

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10025

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 1]
```diff
@@ -415,10 +427,20 @@ var _ = Describe("VirtualMachine Mutator", func() {
...
 			vmSpec, _ := getVMSpecMetaFromResponse(rt.GOARCH)
-			Expect(vmSpec.DataVolumeTemplates).To(HaveLen(1))
-			for _, dv := range vmSpec.DataVolumeTemplates {
-				Expect(*dv.Spec.PVC.StorageClassName).To(Equal(storageClass))
-			}
+			assertPVCStorageClassName(vmSpec.DataVolumeTemplates, storageClass)
+		})
+
+		It("should not overwrite storageclass already defined in Storage of DataVolumeTemplate", func() {
+			storageClass := "local"
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:434]: nit: You could make this a const

**Review by 0xFelix — APPROVED** [review]
/lgtm

Just one nit, otherwise lgtm :) Thanks!

**Review by xpivarc — COMMENTED** [review]
/approve
