### PR TITLE
tests/infrastructure/prometheus: remove test_id:4146

### LINKED ISSUE #16858: test_id:4146 is a no-op: filters virt-handler metrics by phase label that doesn't exist
## Description

`test_id:4146` ("should include VMI phase metrics for all running VMs") in `tests/infrastructure/prometheus.go` is a no-op test that always passes vacuously.

## Root cause

The test scrapes metrics from **virt-handler** and filters by `phase=Running`:

```go
metricsPayload := libmonitoring.GetKubevirtVMMetrics(pod) // pod = virt-handler

fetcher := metricsutil.NewMetricsFetcher("")
fetcher.AddNameFilter("kubevirt_vmi_")
fetcher.AddLabelFilter("phase", "Running")

metrics, err := fetcher.LoadMetrics(metricsPayload)
// ...
for _, results := range metrics {
    for _, metricResult := range results {
        Expect(metricResult.Value).To(Equal(float64(len(preparedVMIs))))
    }
}
```

However, **no virt-handler metric carries a `phase` label**. The `phase` label only exists on `kubevirt_vmi_info`, which is a **virt-controller** metric (defined in `pkg/monitoring/metrics/virt-controller/vmistats_collector.go`).

As a result, `metrics` is always an empty map, the `for range` loop never executes, and the test passes without asserting anything.

## Additional note on the value assertion

Even if the test were fixed to scrape virt-controller, the original assertion is wrong:

```go
Expect(metricResult.Value).To(Equal(float64(len(preparedVMIs))))
```

`kubevirt_vmi_info` is a gauge with a value of 0 or 1 (present/absent per VMI), while `float64(len(preparedVMIs))` is 2 (the number of VMs the test prepares). This assertion would never pass on real data. The fact that it never failed in CI further confirms the test was always a no-op — the loop body was never reached.

The correct check after fixing the data source should assert the **count of results** (one `kubevirt_vmi_info` entry per running VMI), not the metric value.

## Impact

- The test spins up 2 VMs in `BeforeEach` for no reason (wasted CI time).
- It gives a false sense of coverage for VMI phase metrics.

## Suggested fix

Move the test to scrape **virt-controller** metrics instead of virt-handler, similar to the "VMI eviction blocker status" context in the same file. The `phase` label lives on `kubevirt_vmi_info` which is emitted by virt-controller.

### PR DESCRIPTION
**Pull request by dasionov**
### What this PR does

test_id:4146 was filtering virt-handler metrics by phase=Running, but no virt-handler metric carries a "phase" label. The phase label exists only on kubevirt_vmi_info emitted by virt-controller, so the test always got an empty result and passed vacuously.

~~Fix by scraping the virt-controller leader endpoint and filtering for kubevirt_vmi_info{phase=Running}, then asserting one entry per running VMI.~~

~~Also move test_id:4146 into a "virt-controller metrics" Context alongside the eviction blocker tests, keeping controllerMetricIPs scoped to tests that actually need them.~~

fix by removing the test, since it's covered by unit tests already at vmistats_collector.go

### References

- Fixes #16858 

### Release note
```release-note
none
```

### CODE REVIEW

File: tests/infrastructure/prometheus.go [hunk 1]
```diff
@@ -520,6 +502,24 @@ var _ = Describe(SIGSerial("[rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com]
 			controllerMetricIPs = nil
 		})
 
+		It("[test_id:4146]should include VMI phase metrics for all running VMs", func() {
+			libnet.SkipWhenClusterNotSupportIPFamily(k8sv1.IPv4Protocol)
+
+			ip := libnet.GetIP(controllerMetricIPs, k8sv1.IPv4Protocol)
+			metricsPayload := libmonitoring.GetKubevirtVMMetricsByIP(pod, ip) //nolint:staticcheck
```
Comment (0xFelix) [inline tests/infrastructure/prometheus.go]: Can we do better?

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: i don't think so. since we have to query virt-controller this is the only way without making it ugly, there was a discussion about this in https://github.com/kubevirt/kubevirt/pull/16476#discussion_r2690561666

Comment (0xFelix) [reply tests/infrastructure/prometheus.go]: By that I meant at least make it compatible with IPv6 too (`DescribeTable`, as below)

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: sure

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: done

File: tests/infrastructure/prometheus.go [hunk 2]
```diff
@@ -520,6 +502,27 @@ var _ = Describe(SIGSerial("[rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com]
...
+
+			metrics, err := fetcher.LoadMetrics(metricsPayload)
+			Expect(err).ToNot(HaveOccurred())
+			Expect(metrics).ToNot(BeEmpty())
+
+			results := metrics["kubevirt_vmi_info"]
+			Expect(results).To(HaveLen(len(preparedVMIs)))
+		},
+			Entry("[test_id:4146] by IPv4", k8sv1.IPv4Protocol),
+			Entry(" by IPv6", k8sv1.IPv6Protocol),
```
Comment (0xFelix) [inline tests/infrastructure/prometheus.go]: nit: remove leading whitespace

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: without the white sapce it is joined to the title:
`should include VMI phase metrics for all running VMsby IPv6`

File: tests/infrastructure/prometheus.go [hunk 3]
```diff
@@ -520,6 +502,27 @@ var _ = Describe(SIGSerial("[rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com]
 			controllerMetricIPs = nil
 		})
 
+		DescribeTable("[test_id:4146]should include VMI phase metrics for all running VMs", func(family k8sv1.IPFamily) {
+			libnet.SkipWhenClusterNotSupportIPFamily(family)
```
Comment (machadovilaca) [inline tests/infrastructure/prometheus.go]: cant this check be done through test labels?

File: tests/infrastructure/prometheus.go [hunk 4]
```diff
@@ -520,6 +502,27 @@ var _ = Describe(SIGSerial("[rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com]
...
+
+			ip := libnet.GetIP(controllerMetricIPs, k8sv1.IPv4Protocol)
+			metricsPayload := libmonitoring.GetKubevirtVMMetricsByIP(pod, ip) //nolint:staticcheck
```
Comment (machadovilaca) [inline tests/infrastructure/prometheus.go]: why the nolint? if really needed add justification

File: tests/infrastructure/prometheus.go (hunk 3 above)
Comment (dasionov) [reply tests/infrastructure/prometheus.go]: no, we wont be able to extract the metric on specific environments
for example ipv6 only cluster, ipv4 entree will fail to extract metrics. 
same for ipv4 only cluster.

File: tests/infrastructure/prometheus.go (hunk 4 above)
Comment (dasionov) [reply tests/infrastructure/prometheus.go]: added in the commit, since we are using a deprecated function, instead of `GetKubevirtVMMetrics`

File: tests/infrastructure/prometheus.go (hunk 3 above)
Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: ok, might not exist now, but can't we add one that tracks the same as SkipWhenClusterNotSupportIPFamily?

File: tests/infrastructure/prometheus.go (hunk 4 above)
Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: then we should really avoid adding new code with deprecated functions imo

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: True, but the other option is to not test this metric at all then.
and remove the test.

Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: https://github.com/kubevirt/kubevirt/blob/f86dda907ba9c3d081f0725034c4e3c184766606/tests/infrastructure/prometheus.go#L228

https://github.com/kubevirt/kubevirt/blob/f86dda907ba9c3d081f0725034c4e3c184766606/tests/infrastructure/prometheus.go#L389

that wouldnt work?

File: tests/infrastructure/prometheus.go (hunk 3 above)
Comment (dasionov) [reply tests/infrastructure/prometheus.go]: thought you said metric labels.. by test labels i assume you mean the decorators.

Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: yes, that, sorry

File: tests/infrastructure/prometheus.go (hunk 4 above)
Comment (dasionov) [reply tests/infrastructure/prometheus.go]: unfortunately, no.
the reason is kubevirt_vmi_info is collected by virt-controller.
virt-handler dont expose it. this is exactly the false positive case and why this test was passing all this time without really validating the metric.

File: tests/infrastructure/prometheus.go (hunk 3 above)
Comment (dasionov) [reply tests/infrastructure/prometheus.go]: done. 
now environments that don't have ipv4 or ipv6 needs to filter the test themselves

File: tests/infrastructure/prometheus.go (hunk 4 above)
Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: theres no method for controller? cant we create?

Comment (akalenyu) [reply tests/infrastructure/prometheus.go]: GetKubevirtVMMetrics queries localhost on the pod to get rid of the ipv4/v6 differentiation, and virt-controller doesn't have curl. I've tackled many of these ipv4/v6 tabled tests in https://github.com/kubevirt/kubevirt/pull/16476 so it would be a lose to sacrifice test entries for the ipv4/v6 thing again, when the test itself doesn't care.
Maybe we can use prometheus for these tests? 

Using prometheus would be the more "complete" e2e form of this test case anyway

Comment (akalenyu) [reply tests/infrastructure/prometheus.go]: Alternatively, how feasible would it be to unit test this instead of e2e?
I mean what value is added by the e2e test compared to an isolated virt-controller unit test?

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: https://github.com/kubevirt/kubevirt/blob/9a3ba8e66633660e38edd3af12b9b8244e7cb211/pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go#L57

IMO this unit tests already covers that.
@machadovilaca can we drop the e2e test?

**Comment by dasionov** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/94d2797ae34b6e8db511ac35eef2b5bfc753576a..8afbce121b300e3e99618147e394787215a786d9): remove the e2e test completley since it's covered by unit tests

File: tests/infrastructure/prometheus.go (hunk 4 above)
Comment (machadovilaca) [reply tests/infrastructure/prometheus.go]: fine by me, not the phase, but we already test the presence of the metric in other locations
since it's already approved, @sradco can you ok this and lgtm?

Comment (dasionov) [reply tests/infrastructure/prometheus.go]: /cc @sradco gentle ping

**Comment by dasionov** [comment]
/cherry-pick release-1.8 release-1.7 release-1.6 release-1.5 release-1.4 release-1.3
