### PR TITLE
Provide ServiceAccount token etc. to VM

### LINKED ISSUE #1541: Support for the default ServiceAccount token
/kind enhancement

**What happened**:
Within a VM I want to use kubectl to access the kubernetes cluster the VM is rnuning on.

Pods have a [default SA token](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) which they can use to access the cluster.
This - or whatever token the pod has - should be consumable from the VM as well.

**What you expected to happen**:
kubectl can use the pods SA token.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubectl in a VM and try to access the cluster

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by slintes**
**What this PR does / why we need it**:

Added a `ServiceAccountVolumeSource`.
When used, the given service account token etc. will be provided to the pod and VM in the same way as secrets and configMaps.

**Which issue(s) this PR fixes** :
Fixes #1541

**Special notes for your reviewer**:

n/a

**Release note**:
```release-note
Provide service account token etc. to the VM
```

### CODE REVIEW

File: pkg/virt-controller/services/template_test.go [hunk 1]
```diff
@@ -1030,6 +1030,38 @@ var _ = Describe("Template", func() {
...
+				ObjectMeta: metav1.ObjectMeta{
+					Name: "testvmi", Namespace: "default", UID: "1234",
+				},
+				Spec: v1.VirtualMachineInstanceSpec{ServiceAccountName: serviceAccountName, Domain: v1.DomainSpec{}},
+			}
+
+			pod, err := svc.RenderLaunchManifest(&vmi)
+			Expect(err).ToNot(HaveOccurred())
+			Expect(pod.Spec.ServiceAccountName).To(Equal(serviceAccountName), "ServiceAccount matches")
+			Expect(*pod.Spec.AutomountServiceAccountToken).To(BeTrue(), "Token automount is enabled")
```
Comment (stu-gott) [inline pkg/virt-controller/services/template_test.go]: The service account credentials are also mapped inside the VM, correct? Is that something that's realistic to check for here? At the very least, we could inspect the dom XML?

File: pkg/virt-launcher/virtwrap/api/converter_test.go [hunk 2]
```diff
@@ -451,6 +453,12 @@ var _ = Describe("Converter", func() {
       <driver name="qemu" type="raw" iothread="1"></driver>
       <alias name="ua-pvc_block_test"></alias>
     </disk>
+    <filesystem type="mount">
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/api/converter_test.go]: Are there any drawbacks to using type="mount" here. I'm curious why we had to go with .iso for exposing the configmap and secret disks.

File: pkg/virt-controller/services/template_test.go (hunk 1 above)
Comment (slintes) [reply pkg/virt-controller/services/template_test.go]: The dom XML is tested in `converter_test.go`. Besides that, I have a func test on my todo list, which will test for the token inside the running VM. Does that answer your question?

File: pkg/virt-launcher/virtwrap/api/converter_test.go (hunk 2 above)
Comment (slintes) [reply pkg/virt-launcher/virtwrap/api/converter_test.go]: good question, I just looked at the dom xml options, and found this as the most appropriate way to go. Maybe @mfranczy can explain?

**Comment by slintes** [comment]
ci test please

File: pkg/virt-launcher/virtwrap/api/converter_test.go (hunk 2 above)
Comment (mfranczy) [reply pkg/virt-launcher/virtwrap/api/converter_test.go]: According to [design doc](https://docs.google.com/document/d/1TcxytalN8CLVnoP7IHh2mFx-xL197w7_obNLUe_z9c0/edit#heading=h.fyb6k0pywmjg) ```iso``` format has been chosen because of 

> The disk will be format with the read-only ISO-9660 file-system (chosen because of it’s wide guest support) and will use the same file-system hierarchy as the Kubernetes Secret/ConfigMap Volumes.

However, I created a trello task to check ```9p``` (few weeks ago), because we need to provide update propagation functionality for configmap and secrets. I don't know about any drawbacks, this is what I wanted to check (maybe it's good enough and should be used as first)

Comment (fabiand) [reply pkg/virt-launcher/virtwrap/api/converter_test.go]: 9p has a to narrow guest support.

Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/api/converter_test.go]: > However, I created a trello task to check 9p (few weeks ago), because we need to provide update propagation functionality for configmap and secret

We might end up needing to support iso and 9p. Since guest support is limited, maybe we can make a enabling 9p support for these disks a value that's toggled in the domianSpec feature section on the VMI.

For this PR the right approach is to start with iso for now.  If token rotation becomes a thing within the pod, It's possible in the future we might encounter something similar to the config-map/secret issue with regards to change propagation.

Comment (fabiand) [reply pkg/virt-launcher/virtwrap/api/converter_test.go]: I'm close to your position, @davidvossel - we probably want to enable 9p at some point. After all it has some benefits on supported platforms (i.e. "live updates"), but by then we might also have nfs-over-virtio which will also be a first class citizen on linux at least.

Now, anyway - to see how valuable features are to users, we can start with the iso9660 approach, and if it flies we can improve it.
If we add it in one place, then we probably want to use it everywhere where we used iso9660 (secret/cm, cloudinit, here)

**Comment by slintes** [comment]
@fabiand how should the API look like? Atm I just added a "serviceAccountName" field to the VMI: when it's given, it will be mounted, else not. So no automount of the default account. Is that ok? Or should I always mount the default account? Or should this be a new VolumeSource type?

**Comment by fabiand** [comment]
so ... a little bit of a good question.

I initially assumed to take the pod's serviceAccount token.
But it doesn't make much sense to change the serviceAccount of the pod, as it's usually set by kubevirt.

I actually wonder if we could leave it to the user to set the pod/VM ServiceAccount. It sounds reasonable, but I am not sure about any side effects atm.

**Comment by slintes** [comment]
> I initially assumed to take the pod's serviceAccount token.
> But it doesn't make much sense to change the serviceAccount of the pod, as it's usually set by kubevirt.

Kubevirt currently doesn't set a service account, so we just get the default one. But it's not used/needed (virt-launcher doesn't use the k8s client)

> I actually wonder if we could leave it to the user to set the pod/VM ServiceAccount. It sounds reasonable, but I am not sure about any side effects atm.

That was my idea: let the user decide. If no account is set, also the pod won't get the default anymore. If an account is set, might be the default one or any other, that one will be configured for the pod and vm. I'm not aware of side effetcs (as virt-launcher doesn't use the account itself).

**Comment by davidvossel** [comment]
> That was my idea: let the user decide. If no account is set, also the pod won't get the default anymore. If an account is set, might be the default one or any other, that one will be configured for the pod and vm. I'm not aware of side effetcs (as virt-launcher doesn't use the account itself).

:+1:  that should be fine. Virt-launcher is designed to never need k8s api access and we have no plans to ever require k8s api access for virt-launcher.

**Comment by slintes** [comment]
> please update the user guide with a brief explanation of how to use this feature.

will do, and thx for review :)

**Comment by fabiand** [comment]
Amazing!
