### PR TITLE
Fix various things in the device plugin manager

### LINKED ISSUE #2098: kvm, tun and vhost-net resources are not reported after kubelet restart
/kind bug

**What happened**:

After `systemctl restart kubelet` (or `systemctl restart origin-node` on OpenShift), `kvm`, `tun` and `vhost-net` resources are reported empty.

**What you expected to happen**:

Those resource should keep their original value.

**How to reproduce it**:

Prepare the cluster:

```shell
make cluster-up
make cluster-sync
```

List node resources:

```shell
./cluster/kubectl.sh get nodes -o yaml
```

```yaml
...
    allocatable:
      cpu: "5"
      devices.kubevirt.io/kvm: "110"
      devices.kubevirt.io/tun: "110"
      devices.kubevirt.io/vhost-net: "110"
      hugepages-1Gi: "0"
      hugepages-2Mi: 128Mi
      memory: 4679260Ki
      pods: "110"
...
```

Restart kubelet:

```shell
./cluster/cli.sh ssh node01 'sudo systemctl restart kubelet'
```

After a while, list node resources again:

```shell
./cluster/kubectl.sh get nodes -o yaml
```

```yaml
...
    allocatable:
      cpu: "5"
      devices.kubevirt.io/kvm: "0"
      devices.kubevirt.io/tun: "0"
      devices.kubevirt.io/vhost-net: "0"
      hugepages-1Gi: "0"
      hugepages-2Mi: 128Mi
      memory: 4679260Ki
      pods: "110"
...
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version: used master branch
- Cloud provider or hardware configuration: local kubevirtci, tested with os-3.11.0-crio and k8s-multus-1.13.3

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

 * Re-register if the kubelet restarts. Otherwise we only offer 0
   devices. See https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-implementation for details.
 * Catch errors in fsnotify from the error channel
 * Ensure that the device plugin goes down if the health go-routine
   exits
 * Watch devices in /proc/1/root/dev/, since /dev from the host is not mounted
 * Allow that the kubelet can restart during every stage of the plugin-manager startup

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2098

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix multiple sutations where the device-plugins stop working and the node reports a quantity of 0 for devices exposed as devices.kubevirt.io/*.
```

### CODE REVIEW

**Comment by rmohr** [comment]
@davidvossel @stu-gott ready for a review.

File: pkg/virt-handler/device-manager/device_controller.go [hunk 1]
```diff
@@ -62,73 +59,26 @@ func (c *DeviceController) nodeHasDevice(devicePath string) bool {
...
+func (c *DeviceController) startDevicePlugin(dev GenericDevice, stop chan struct{}) {
 	logger := log.DefaultLogger()
+	deviceName := dev.GetDeviceName()
 
-	_, err := os.Stat(target)
-	if err != nil {
-		if !os.IsNotExist(err) {
-			return err
+	for {
+		err := dev.Start(stop)
```
Comment (cynepco3hahue) [inline pkg/virt-handler/device-manager/device_controller.go]: do we want to re-register device each second, why we can not run `health check` before and if it returns ok, just continue without re-register?

Comment (rmohr) [reply pkg/virt-handler/device-manager/device_controller.go]: It tries every second if it can't register with the kubelet. I could exchange that with a back-off, so taht we don't pollute the logs too much. Blind retries might not be the most elegant solution, but even if the kubelet socket file is there we might not be able to connect (e.g. kubelet crashed and is not running).
 
In all other cases it stays connected and only switches the devices to healthy/unhealthy. That is different to before, where it waited until the device showed up and had similar checks also inside the plugin. I collapsed that to one health check.

Comment (cynepco3hahue) [reply pkg/virt-handler/device-manager/device_controller.go]: hm if kubelet crashed re-register will not help until kubelet is back, and I believe when it will back it will re-create socket or do I miss something?

Comment (rmohr) [reply pkg/virt-handler/device-manager/device_controller.go]: Yes, it re-creates it, but I am not sure on how to distinguish a kubelet restart or crash from other connection errors. There might be various reasons why we have a disconnect. In all these cases,  the socket file stays there and we would not re-connect.

Comment (rmohr) [reply pkg/virt-handler/device-manager/device_controller.go]: @cynepco3hahue added the back-off logic.

File: tests/vmi_lifecycle_test.go [hunk 2]
```diff
@@ -422,6 +431,42 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
+					[]string{
+						"rm",
+						// We want to fail if the file does not exist, but don't want to be asked
+						// if we really want to remove write-protected files
+						"--interactive=never",
+						device_manager.SocketPath(device_manager.KVMName),
+					})
+				Expect(err).ToNot(HaveOccurred())
+
+				// Give the kubelet and virt-handler some time to re-synchronize
```
Comment (davidvossel) [inline tests/vmi_lifecycle_test.go]: Is there something we can key off here to prove the re-registration took place? Like maybe a log message or something?

File: pkg/virt-handler/device-manager/device_controller.go [hunk 3]
```diff
@@ -62,73 +60,30 @@ func (c *DeviceController) nodeHasDevice(devicePath string) bool {
...
+		if err != nil {
+			logger.Reason(err).Errorf("Error starting %s device plugin", deviceName)
+			retries = int(math.Min(float64(retries+1), 3))
```
Comment (davidvossel) [inline pkg/virt-handler/device-manager/device_controller.go]: len(backoff)-1 instead of '3'? it would be more safe.

File: pkg/virt-handler/device-manager/device_controller_test.go [hunk 4]
```diff
@@ -73,43 +71,6 @@ var _ = Describe("Device Controller", func() {
 			res = deviceController.nodeHasDevice(devicePath)
 			Expect(res).To(BeTrue())
 		})
-
```
Comment (davidvossel) [inline pkg/virt-handler/device-manager/device_controller_test.go]: can we get a unit test that exercise the retry/re-register logic now that these "blocking" unit tests are removed?

**Comment by rmohr** [comment]
ci test please

File: tests/vmi_lifecycle_test.go (hunk 2 above)
Comment (rmohr) [reply tests/vmi_lifecycle_test.go]: Done

File: pkg/virt-handler/device-manager/device_controller.go (hunk 3 above)
Comment (rmohr) [reply pkg/virt-handler/device-manager/device_controller.go]: Done

File: pkg/virt-handler/device-manager/device_controller_test.go (hunk 4 above)
Comment (rmohr) [reply pkg/virt-handler/device-manager/device_controller_test.go]: Done

**Comment by rmohr** [comment]
ci test please

**Comment by rmohr** [comment]
@davidvossel should be ready for another review round.

**Comment by rmohr** [comment]
ci test please
