### PR TITLE
Decentralized Libvirt

### LINKED ISSUE #196: Qemu instances are killed if the Libvirt pod goes down.
Our current approach leverages Libvirt inside a container. This libvirt process starts qemu instances as virt-handler requests them. Since this libvirt container originally started those processes, if that pod goes down or is restarted each qemu instance it created is also killed.

In the normal workflow, this is not an issue. If Libvirt stays running, so will each qemu instance. If the libvirt pod needs to be updated, an admin can simply evacuate the host before updating. The concern here is error/edge cases. If libvirt were to crash for some reason, each qemu instance spawned by it would be terminated.

Possible mitigation strategies include:

1) Adding systemd to the libvirt container (so that the pod will continue to run even if the libvirt process terminates--and systemd will restart it). This doesn address the case where the pod itself goes down for some reason.
2) Make the virt-launcher pod responsible for starting the qemu process. This will require some changes to our qemu-kvm wrapper script and some glue on the virt-launcher side. This obviously increases the complexity of our approach a bit so we'll need to ensure this mechanism is robust/secure if we choose this approach.

### LINKED ISSUE #364: Drop qemu-wrapper
The wrapper needs to be dropped to use libvirt as intended.

Opening this tracker because it might not happen in one PR but in several steps.

### LINKED ISSUE #421: cleanup virt-launcher socket directories
#337 The directories created for the virt-launcher pods need to be cleaned up after stopping each vm.

### PR DESCRIPTION
**Pull request by davidvossel**
# Overview

This patch moves KubeVirt's design from one that depends on a centralized libvirtd per a node, to one that uses a decentralized libvirtd per a VM pod.

With this new decentralized approach, each VM's qemu process now lives directly within the VM Pod's cgroups and namespaces which means that any storage/network devices in the Pod are available to the VM.

# Notable Changes
## Cloud-init and Registry Disks
Generation and lifecycle management of ephemeral disks have moved from virt-handler to virt-launcher.

This data is now completely self contained (no shared host mounts) within the VM Pod, which means cleanup occurs automatically as a part of the kubelet tearing down the Pod's environment.

## Notifications Server and Domain Informer 

Previously virt-handler received events about lifecycle changes to a domain through a libvirt event callback.

Now virt-handler receives domain lifecycle events through its notification server.  Virt-handler starts a notification server that listens on a unix socket. Each virt-launcher acts as a client to this notification server and forwards domain lifecycle events to it.

The virt-handler domain informer uses this notification server for its Watch function.  The informer's List function iterates over every known virt-launcher present on the local host and requests the latest information about all defined domains.

## Virt-launcher Command Server

Each virt-launcher starts a command server that listens on a unix socket as part of the virt-launcher process's initialization.

By design, Virt-launcher has no connection to the k8s api server. The command server allows virt-handler to manage the VM's lifecycle by posting VM specs to virt-launcher to start/stop.

This command server is also how the virt-handler's Domain informer perform's its List function. There's a directory of unix sockets belonging to each virt-launcher. The domain informer List function iterates over each of these sockets and creates a cache of all the active domains on the local node.

## Migrations have been disabled

The reasoning for this is migrations depend on network access to the libvirtd process managing the VM. Our plan for networking has the IP provided to each VM pod being taken over by the VM itself, which means processes running in the pod (other than the qemu process) will not have network access in the near future.

This doesn't mean we are abandoning live migrations. It just means we are accepting that migrations are a feature we're willing to sacrifice in the short term in order to simplify the move to a more desirable overall KubeVirt design.

Re-enabling migrations is being tracked in this issue #676

## Libvirtd and Virtlogd

The libvirtd and virtlogd processes are now launched as part of virt-launcher's initialization sequence.

Originally I had libvirtd and virtlogd in their own respective containers in the VM pod, however this caused issues with startup and shutdown ordering. 

Virt-launcher intercepts posix signals to shutdown and uses that as a signal to begin gracefully shutting down the VM. We need to ensure that the libvirtd process does not shutdown until after the VM has exited. This was hard to guarantee with libvirtd not being in the same container and controlled by virt-launcher.

## Code Removal and Relocation

* Everything under /pkg/virt-handler/virtwrap moved to /pkg/virt-launcher/virtwrap
* The isolation pkg was used for detecting cgroups and namespaces of a qemu process. We don't nee this anymore
* The config-disk pkg was used as a job wrapper around cloud-init to prevent blocking virt-handler. Cloud-init disk creation has now moved to virt-launcher.
* libvirt daemonset manifests have been removed
* libvirt-kubevirt container has been removed. Virt-launcher now consumes the libvirt base container.
* Migrations CRD manifest has been removed. We can reintroduce this CRD once migrations are enabled again.
* Virt-handler's migration info rest endpoint has been removed.

## Networking

Nothing with involved with networking was impacted by this patch series. The VM pods remain in the host network namespace for now simply because the Pod network work hasn't been completed yet. 

## Testing Changes

* The introduction of libvirtd per a pod impacted the VM startup time slightly. As a result, some functional test's timeouts have been increased.
* Unit tests for all new functionality (command server, notify server, domain informer) have been introduced.
* No loss of test coverage is expected.  Any unit tests that were removed had their functionality moved to another unit test or where dropped entirely as a result of the functionality no longer existing. 
* Migration Functional tests remain in the src tree but are inactive. 
* Tests that involve multiple VMs launching in parallel have "fail test on warning" disabled. Libvirt complains about making macvtap devices sometimes because two libvirtds are attempting to do something in parallel. The VMs still launch fine, it just involves a retry.  This will get fixed with the networking changes. 

# Issues resolved by these changes.

Fixes #421, fixes #364, fixes #196

### CODE REVIEW

File: pkg/virt-launcher/virtwrap/manager.go [hunk 1]
```diff
@@ -174,6 +168,32 @@ func (l *LibvirtDomainManager) SyncVMSecret(vm *v1.VirtualMachine, usageType str
 	return nil
 }
 
+// All local environment setup that needs to occur before VM starts
+// can be done in this function. This includes things like...
+//
+// - storage prep
+// - network prep
+// - cloud-init
+func (l *LibvirtDomainManager) preStartHook(vm *v1.VirtualMachine, domain *api.Domain) error {
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/manager.go]: @vladikr This is an entry point you can use for setting up anything in the environment that needs to be setup for networking. It occurs right before the VM starts.

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
@fabiand @rmohr I don't consider this WIP anymore. All the functionality and tests are present now.

**Comment by davidvossel** [comment]
The description has been updated with a detailed account of what has been changed in this patch series.

**Comment by rmohr** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go [hunk 2]
```diff
@@ -0,0 +1,238 @@
...
+	}
+	args := &Args{
+		VMJSON: string(vmJSON),
+	}
+	_, err = c.genericSendCmd(args, cmd)
+
+	return err
+}
+
+func (c *VirtLauncherClient) ListDomains() ([]*api.Domain, error) {
```
Comment (rmohr) [inline pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: Shouldn't that be `ListDomain`?

File: pkg/virt-launcher/virtwrap/cache/cache.go [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ * Copyright 2017 Red Hat, Inc.
+ *
+ */
+
+package cache
```
Comment (rmohr) [inline pkg/virt-launcher/virtwrap/cache/cache.go]: Looks like a better place for this file would be inside virt-handler?

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go [hunk 4]
```diff
@@ -0,0 +1,238 @@
...
+	SecretUsageID   string
+	SecretValue     string
+}
+
+type LauncherClient interface {
+	StartVirtualMachine(vm *v1.VirtualMachine, secrets map[string]*k8sv1.Secret) error
+	ShutdownVirtualMachine(vm *v1.VirtualMachine) error
+	KillVirtualMachine(vm *v1.VirtualMachine) error
+	SyncSecret(vm *v1.VirtualMachine, usageType string, usageID string, secretValue string) error
+	ListDomains() ([]*api.Domain, error)
```
Comment (rmohr) [inline pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: Shouldn't that be more something like `GetDomain()(*api.Domain, error)`?

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go [hunk 5]
```diff
@@ -0,0 +1,238 @@
...
+	if err != nil {
+		return err
+	}
+	secretJSON, err := json.Marshal(secrets)
+	if err != nil {
+		return err
+	}
+
+	args := &Args{
+		VMJSON:          string(vmJSON),
```
Comment (rmohr) [inline pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: I would feel better if we understand the  issue we are facing, which we are working around by using json.

File: cmd/virt-launcher/libvirtd.sh [hunk 6]
```diff
@@ -36,27 +36,27 @@ mkdir /dev.container && {
...
 # If no cpuacct,cpu is present, symlink it to cpu,cpuacct
 # Otherwise libvirt and our emulator get confused
-if [ ! -d "/host-sys/fs/cgroup/cpuacct,cpu" ]; then
-    echo "Creating cpuacct,cpu cgroup symlink"
-    mount -o remount,rw /host-sys/fs/cgroup
-    cd /host-sys/fs/cgroup
-    ln -s cpu,cpuacct cpuacct,cpu
-    mount -o remount,ro /host-sys/fs/cgroup
-fi
+#if [ ! -d "/host-sys/fs/cgroup/cpuacct,cpu" ]; then
```
[the remark this answers is not in the document]
Comment (davidvossel) [reply cmd/virt-launcher/libvirtd.sh]: yep, i'll remove that now. it was commented out for that reason

File: pkg/virt-handler/vm.go [hunk 7]
```diff
@@ -353,8 +341,18 @@ func (d *VirtualMachineController) execute(key string) error {
...
 	} else if watchdogExpired && vm.IsRunning() {
-		log.Log.Object(vm).V(3).Info("Shutting down due to expired watchdog.")
+		log.Log.Object(vm).Info("Shutting down due to expired watchdog.")
 		shouldShutdownAndDelete = true
+		if domainExists {
+			// Virt-launcher provids domain state. If virt-launcher
+			// is down, the domain needs to be deleted from the cache.
+			err = d.domainInformer.GetStore().Delete(domain)
+			if err != nil {
+				return err
```
[the remark this answers is not in the document]
Comment (davidvossel) [reply pkg/virt-handler/vm.go]: Under normal operation, the listwatcher will process all of this correctly. Delete events come in and domains are removed from the cache by the informer. 

This is an edge case where the informer never receives the Delete event from the VM Pod. The watchdog expires and we remove the cache entry here.  This condition could occur if virt-handler is down when the final delete notification is sent, or if virt-launcher forcibly exits in a way that results in the final delete notification not being sent.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 4 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: I wanted to use the ListAllDomains libvirt api call rather than having the cmd server maintain any state related to the name of the domain it is managing. I could hide that we're using the ListAllDomain's function and just return the first domain entry for the command client's GetDomain function. I didn't see a reason to do that though.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 2 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: This translates to ListAllDomains on the backend.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]:
```
type ResourceList map[ResourceName]resource.Quantity
```

Anything that uses that map (like memory or cpu requests/limits) gets lost if we don't serialize/deserialize the VirtualMachine as a JSON object.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 4 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: That is very confusing, since we know that it can always only ever return one domain (I think we even know the name of the domain to look up).

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: Could you give me a before RPC and after RPC example?

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 4 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: how do we know the name of the domain to look up?  This function is used by the domain informer's List function to sync the cache. There's no knowledge on the client side as to what domain they're requesting at that point.

Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: Still, it can just return one domain, or am I at the wrong place in the code?

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: before
```
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm
spec:   
  terminationGracePeriodSeconds: 0                                  
  domain:
    resources:
      requests:
        memory: 64M
```

after
```apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm
spec:   
  terminationGracePeriodSeconds: 0                                  
  domain:
    resources:
      requests:
        memory:
```

the memory quantity gets lost

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 4 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: yes, we can hind the fact that the command server is using the ListAllDomain libivrt api function and just call the command client's function GetDomain.  I'm fine with that

File: pkg/virt-launcher/virtwrap/cache/cache.go (hunk 3 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cache/cache.go]: yup, i agree. I'll move this

File: pkg/virt-handler/vm.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/vm.go]: > This condition could occur if virt-handler is down when the final delete notification is sent or if virt-launcher forcibly exits in a way that results in the final delete notification not being sent.

That should normally not be necessary. A few mechanisms should be sufficient to prevent that:

 * warming up the domain cache with the vm cluster-state. If we then don't find a domain, matching the expectation based on the vm, the informer should delete the object from the cache automatically
 * If we know which socket belongs to which vm, we can infer from that, that if the socket connection gets closed, or if no one listens on the socket, which vm got removed.

@davidvossel can you think of a scenario where we can miss a delete if the above conditions are met?

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 4 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: fixed :)

File: cmd/virt-launcher/libvirtd.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (davidvossel) [reply cmd/virt-launcher/libvirtd.sh]: fixed

File: pkg/virt-launcher/virtwrap/cache/cache.go (hunk 3 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cache/cache.go]: fixed

File: pkg/virt-handler/vm.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (davidvossel) [reply pkg/virt-handler/vm.go]: i'll give this part some more attention this afternoon. There were some things i was trying to avoid with regards to coupling the client connection to the domain's status. I think this can be simplified though.

[the remark this answers is not in the document]
Comment (davidvossel) [reply pkg/virt-handler/vm.go]: @rmohr 

I've removed the watchdog informer entirely. The domain informer now polls for stale watchdog files and fires a delete event when one is encountered.

I'm hesitant to tie any of this Delete event logic directly to the unix socket, which is why i'm still using the watchdog files. I don't want the presence, or lack of presence of the unix socket file to infer a stale domain needs to be processed.

File: pkg/virt-handler/cache/cache.go [hunk 8]
```diff
@@ -0,0 +1,197 @@
...
+
+	d.wg.Add(1)
+	go func() {
+		defer d.wg.Done()
+
+		expiredWatchdogTicker := time.NewTicker(time.Duration(d.watchdogTimeout) * time.Second).C
+		srvErr := make(chan error)
+		go func() {
+			defer close(srvErr)
+			err := notifyserver.RunServer(d.virtShareDir, d.stopChan, d.eventChan)
```
Comment (rmohr) [inline pkg/virt-handler/cache/cache.go]: The whole notify server might also be better placed in the virt-handler package.

File: pkg/virt-launcher/virtwrap/cmd-server/server.go [hunk 9]
```diff
@@ -0,0 +1,237 @@
...
+		reply.Success = false
+		reply.Message = err.Error()
+		return nil
+	}
+
+	log.Log.Object(vm).Info("Synced vm secrets")
+	return nil
+}
+
+func (s *Launcher) Start(args *cmdclient.Args, reply *cmdclient.Reply) error {
```
Comment (rmohr) [inline pkg/virt-launcher/virtwrap/cmd-server/server.go]: I think that `Start` is misleading. Having something like `Sync` in the name is more correct. Also right now, virt-handler would try to unpause a VM, if it is in an unexpected pause mode, so to some degree it really already tries to synchronize the vm and the domain state.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: ok, so the reason is that the Quantity type has hidden fields, and the serializer by default only takes public fields. Therefore it keeps the format, but not the actual value ... A custom MarshalBinary() might solve that. However not sure if it is easy to do ...

Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: ok, so I think I have a solution. Could you implement "MarshalBinary()" and "UnmarshalBinary()" on our VM type? In there just marshal the whole struct into json and convert it to bytes. Then you can remove all custom json marshalling actions regarding to RPC. That would give me a better feeling.

File: pkg/virt-handler/vm.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/vm.go]: works for me. Just modifying the cache outside of the informer is a no go afaik (locking, ...).

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: I think on the long run, we should use protopuf for rpc, since k8s takes care that their types work with protobuf (and aparently don't care about normal rpc).

File: pkg/virt-handler/cache/cache.go (hunk 8 above)
Comment (davidvossel) [reply pkg/virt-handler/cache/cache.go]: i'm torn about that one. The notify client depends on libvirt. I could move the server to virt-handler but I'd want to keep the client package under virt-launcher.  i thought it was better to keep them both together in one place.

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: > Could you implement "MarshalBinary()" and "UnmarshalBinary()" on our VM type

that seems a little overkill. Is there a simple way of doing this?  The binary encoding that golang provides is the same thing that rpc uses, which stripped the memory requests.

File: pkg/virt-handler/cache/cache.go (hunk 8 above)
Comment (davidvossel) [reply pkg/virt-handler/cache/cache.go]: fixed. I moved notify server and cmd client to virt-handler

File: pkg/virt-launcher/virtwrap/cmd-server/server.go (hunk 9 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/server.go]: fixed

File: pkg/virt-launcher/virtwrap/cmd-server/client/client.go (hunk 5 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: i see what you're getting at now.  We'll just use the a MarshalBinary function and wrap the json encode in it. I'm fine with doing that.

Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/cmd-server/client/client.go]: fixed
