### PR TITLE
tests: Move storage VM tests to sig-storage lanes

### LINKED ISSUE #16679: regression: test_id:1521 and test_id:1525 failing on all periodic sig-compute lanes
**What happened**:
Tests failing:
* `KubeVirt Tests Suite.[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]VirtualMachine A valid VirtualMachine given [test_id:1521]should remove VirtualMachineInstance once the VM is marked for deletion [storage-req]with Block Disk`
* `KubeVirt Tests Suite.[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]VirtualMachine A valid VirtualMachine given [test_id:1525]should stop VirtualMachineInstance if running set to false [storage-req]with Block Disk`

Both tests failing with error message:
```
{ Failure tests/vm_test.go:265
Block storage (RW) is not present
Expected
    <bool>: false
to be true
tests/vm_test.go:117}
```

Example run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.35-sig-compute/2016164457234829312

Likely either a test configuration error or an accidental selection for the sig-compute whereas they should be in sig-storage.

**What you expected to happen**:
Tests should not fail.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
/sig compute
/priority critical-urgent
/kind bug

FYI @fossedihelm @xpivarc 

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by Aneesh-Hegde**
#### Before this PR:
Tests `test_id:1521` and `test_id:1525` with Block Disk entries were failing in periodic sig-compute lanes with error:
```
Block storage (RW) is not present
Expected <bool>: false to be true
```

These tests were running in sig-compute lanes which do not have block storage infrastructure configured. Additionally, Block Disk test entries were redundant with Filesystem Disk entries as both test the same VM lifecycle logic.

#### After this PR:
- Storage-dependent test entries now have `decorators.SigStorage` and run in sig-storage lanes
- Redundant Block Disk test entries removed (only DataVolume entries remain)
- Generic volume mode used (no specific Block/Filesystem - lets storage class decide)
- Focus kept on the important test behavior: graceful termination

### References
- Fixes #16679

### Why we need it and why it was done in this way

**Why we need it:**
Storage-dependent VM lifecycle tests were incorrectly running in sig-compute lanes, which don't have the required storage infrastructure (Rook Ceph). This caused consistent test failures in periodic builds.

**Why it was done this way:**
1. Added `decorators.SigStorage` to route tests to sig-storage lanes where storage is configured
2. Removed redundant Block Disk entries - both Block and Filesystem tested the same VM deletion/stop logic
3. Made volume mode generic - the important test behavior is graceful termination, not the specific storage type

Per `automation/test.sh`:
- sig-compute lanes filter: `(sig-compute && !(sig-storage))` - excludes tests with SigStorage decorator
- sig-storage lanes filter: `(sig-storage)` - includes tests with SigStorage decorator  
- sig-storage lanes configure `KUBEVIRT_STORAGE="rook-ceph-default"` providing required storage

**Links to places where the discussion took place:** 
- Issue #16679 

### Checklist
This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.
- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by ShellyKa13** [comment]
Check out my comment on the original issue: https://github.com/kubevirt/kubevirt/issues/16679#issuecomment-3811771943
I believe this test cases are irrelevant and should just be deleted

File: tests/vm_test.go [hunk 1]
```diff
@@ -262,7 +256,6 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
 		},
 			Entry("with ContainerDisk", func() (*v1.VirtualMachineInstance, *cdiv1.DataVolume) { return libvmifact.NewAlpine(), nil }, false),
 			Entry("[storage-req]with Filesystem Disk", decorators.StorageReq, newVirtualMachineInstanceWithFileDisk, true),
```
Comment (akalenyu) [inline tests/vm_test.go:258]: The important bit in this is ensureGracefulTermination so if we keep this we're ok

**Review by akalenyu — COMMENTED** [review]
Thank you!
I would adjust the remaining filesystem entry to create a datavolume with no specific volume mode specified since it doesn't matter for these cases

If you could also adjust the title that would be awesome 🙏

File: tests/vm_test.go (hunk 1 above)
Comment (ShellyKa13) [reply tests/vm_test.go:258]: @akalenyu dont you think testing with the containerDisk is enough here? do we need persistent storage to verify shutdowns and stop commands?

**Comment by Aneesh-Hegde** [comment]
@akalenyu PTAL

File: tests/vm_test.go [hunk 2]
```diff
@@ -109,13 +109,7 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
...
 			Expect(foundSC).To(BeTrue(), "Filesystem storage is not present")
 
-			return newVirtualMachineInstanceWithDV(cd.DataVolumeImportUrlForContainerDisk(cd.ContainerDiskAlpine), sc, k8sv1.PersistentVolumeFilesystem)
-		}
-
-		newVirtualMachineInstanceWithBlockDisk := func() (*v1.VirtualMachineInstance, *cdiv1.DataVolume) {
-			sc, foundSC := libstorage.GetAvailableRWBlockStorageClass()
-			Expect(foundSC).To(BeTrue(), "Block storage (RW) is not present")
-			return newVirtualMachineInstanceWithDV(cd.DataVolumeImportUrlForContainerDisk(cd.ContainerDiskAlpine), sc, k8sv1.PersistentVolumeBlock)
+			return newVirtualMachineInstanceWithDV(cd.DataVolumeImportUrlForContainerDisk(cd.ContainerDiskAlpine), sc, "")
```
Comment (akalenyu) [inline tests/vm_test.go]: I think you could just drop volumemode from newVirtualMachineInstanceWithDV and use it instead of the wrapping func

**Comment by Aneesh-Hegde** [comment]
@akalenyu Updated per feedback: I've removed the redundant block storage tests/wrapper and refactored newVirtualMachineInstanceWithDV to default to Filesystem mode (removing the volumeMode argument) across all call sites.

File: tests/vm_test.go (hunk 1 above)
Comment (akalenyu) [reply tests/vm_test.go:258]: yeah good point, but I would keep the persistent storage entry over containerdisk just in any case there was some integration point
(I doubt there is or ever will be but persistent storage is the "real" scenario)

Comment (akalenyu) [reply tests/vm_test.go:258]: anyways im totally okay with tackling it outside this pr

**Comment by Aneesh-Hegde** [comment]
@ShellyKa13 The CI failure in tests/container_disk_test.go (unexpected guest-console-log) appears unrelated to my changes. Do I need to make any adjustments to resolve this?
PS:If there are other specific issues that need attention, please let me know—I’d be happy to take a look

**Comment by ShellyKa13** [comment]
@Aneesh-Hegde you are right, the CI is a bit of in a bad shape currently :)
you dont need to do any adjustments
/unhold

**Comment by akalenyu** [comment]
/test pull-kubevirt-e2e-k8s-1.34-sig-compute-serial

@Aneesh-Hegde bear with us haha, rough days for CI

**Comment by Aneesh-Hegde** [comment]
No problem🙃
