### PR TITLE
virt-handler: Unmount() now does best-effort volume cleanup

### LINKED ISSUE #16537: virt-handler: Unmount() returns on first error and skips other stale hotplug mount paths
### Summary
`volumeMounter.Unmount()` stops on the first unmount error and returns early, which can prevent other eligible hotplug mount paths from being unmounted in the same reconcile. If the first failing path remains stuck across retries, virt-handler can repeatedly retry the same failing path while never attempting to unmount other "ready" paths, leading to prolonged cleanup backlog and extra reconcile work. This behavior became visible during RCA for #16520.

### What happened
During RCA for #16520 we noticed that in `volumeMounter.Unmount()`, virt-handler iterates over `vmiMountTargetRecord.MountTargetEntries` and attempts to unmount every entry whose target path is not present in `currentHotplugPaths`:
https://github.com/kubevirt/kubevirt/blob/18554600db136336b08514fb6338ac5847ea89e1/pkg/virt-handler/hotplug-disk/mount.go#L730-L745
However, `Unmount()` returns an error immediately when it fails to unmount the first such path. It does not continue to process the remaining stale/unmount-ready entries.
This creates a problematic failure mode:
- If a single stale entry is “stuck” (e.g. `EBUSY`) and stays stuck across retries,
- Then every subsequent reconcile will hit the same first failing target and return early,
- While other mount targets that are also stale (not in `currentHotplugPaths`) may never be attempted and therefore never get unmounted.
In the #16520 scenario, reconcile retries may also inflate the mount target record with duplicates (as described in #16532), increasing the iteration cost and amplifying the impact: virt-handler repeatedly re-processes a growing list, fails early on the same entry, and delays unmounting other eligible targets.

### What is expected to happen
`Unmount()` should behave like a “best-effort unmount all stale paths” operation:
- Attempt to unmount all entries not present in `currentHotplugPaths` during a single call.
- Do not return early on the first error; instead:
  - log/collect the error,
  - continue unmounting other targets,
- and return a combined error (or the first error) at the end.
This is consistent with how `UnmountAll()` handles errors today (logs a warning and proceeds):
https://github.com/kubevirt/kubevirt/blob/18554600db136336b08514fb6338ac5847ea89e1/pkg/virt-handler/hotplug-disk/mount.go#L814-L826

### Why this matters
Even if one target remains stuck, unmounting the other stale targets can:
- reduce leaked/stale mounts,
- shrink the backlog for later reconciles,
- and reduce repeated work / time spent iterating and retrying.

### Suggested fix direction
Align `Unmount()` error handling with `UnmountAll()`:
- On per-path unmount failure: log a warning and continue with the next path.
- After iterating: return an aggregated error (or a representative error) so the reconcile still signals failure when necessary, but does not block progress on other cleanup.

### Environment
- KubeVirt version: 1.1.0
- Kubernetes version: 1.31.13
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS: Ubuntu 24.04.2
- Kernel: 6.14.8-5
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by keinsword**
### What this PR does
Improves hotplug filesystem volume unmount robustness in `virt-handler` by continuing cleanup on per-path failures and reporting an aggregate error at the end.
#### Before this PR:
`Unmount()` returned early on the first error, which could prevent cleanup of remaining hotplug paths and didn’t preserve a reduced “still mounted / failed” record for retry.
#### After this PR:
`Unmount()` attempts to process all recorded hotplug paths, keeps failed paths in a new record for retry, and reports a summarized error only after finishing the loop.
### References
- Fixes #16537
### Why we need it and why it was done in this way
**The following tradeoffs were made:**
- Pros: Best-effort cleanup makes progress even when one mount path is stuck (busy, missing, transient). This reduces “one bad entry blocks everything” behavior during reconcile retries.
- Cons: A single failing path no longer stops the function immediately; instead you get an aggregated failure signal and must rely on logs/record persistence to see which path(s) failed.
### Checklist
- [x] Design: A design document is not required, this is a targeted bug fix
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: Included a unit test ensuring `Unmount()` now attempts all unmount-ready paths instead of returning early on 1st failure
- [x] Documentation: A user-guide update is not required
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
### Release note
```release-note
Improve Unmount() cleanup by processing all entries and preserving failed paths for retry.
```

### CODE REVIEW

**Comment by awels** [comment]
lets wait for #16737 to merge so we can properly review what is going on here.  I lgtm'ed that one, so hopefully should merge soon.

**Comment by keinsword** [comment]
@awels now that #16737 has been merged, could you please take a look at this one and the issue #16537 it fixes?

**Comment by keinsword** [comment]
Hi @0xFelix,
Would appreciate your review as well 🙃

File: pkg/virt-handler/hotplug-disk/mount.go [hunk 1]
```diff
@@ -729,24 +729,38 @@ func (m *volumeMounter) Unmount(vmi *v1.VirtualMachineInstance, cgroupManager cg
 		newRecord := vmiMountTargetRecord{
 			MountTargetEntries: make([]vmiMountTargetEntry, 0),
 		}
+		unmountErrCount := 0
+		logErrAndKeepMount := func(path string, format string, args ...any) {
+			log.Log.Object(vmi).Errorf(format, args...)
+			newRecord.appendPath(path)
+			unmountErrCount++
+		}
```
Comment (0xFelix) [inline pkg/virt-handler/hotplug-disk/mount.go]: Can't you simply have a `var errs []error` you append to in the failure branches and on L775 you `return errors.Join(err, errs...)`?

Comment (keinsword) [reply pkg/virt-handler/hotplug-disk/mount.go]: I considered collecting the unmount failures into `[]error` and returning `errors.Join(...)` at the end. I went with the current shape mainly for observability: each failed unmount is logged at the point where it happens, which makes it easier to search/filter individual failures, while the final returned error remains a higher-level "cleanup hotplug mounts" failure.

That said, these approaches aren’t exclusive. We could also keep the per-error logging and still accumulate the errors for the final return if you think that would make the code cleaner. I’m happy to change it.

Comment (0xFelix) [reply pkg/virt-handler/hotplug-disk/mount.go]: Let's go with your suggestion then

Comment (keinsword) [reply pkg/virt-handler/hotplug-disk/mount.go]: Done, please have a look 🙃

**Comment by 0xFelix** [comment]
@enp0s3 Can you PTAL?

**Comment by keinsword** [comment]
@0xFelix it appears that CI is stuck, right?

**Comment by 0xFelix** [comment]
Let's wait for the lanes running currently

**Comment by dhiller** [comment]
Retest initiated due to sev lane unstable and github issues present yesterday

**Comment by dhiller** [comment]
This has been one of the cases of `/retest-required` not working - as pointed out on kubevirt-dev.

**Comment by keinsword** [comment]
@dhiller thanks for helping with this one!

/retest-required

**Comment by keinsword** [comment]
@0xFelix @awels can we have this one approved once again please? Looks like CI is OK now.

**Comment by 0xFelix** [comment]
It needs approval.

@mhenriks Can you PTAL?

**Comment by mhenriks** [comment]
/approve
Thanks @keinsword!

**Comment by keinsword** [comment]
Thank you @mhenriks and @0xFelix!

/retest-required
