### PR TITLE
Cache healthz version response and clear when informers error

### LINKED ISSUE #5058: virt-handler calls GET "/version" each healthcheck and liveness probe
/kind bug

**What happened**:

I'm playing with the k8s audit logs and if I'm reading this right, the vast majority of API calls from virt-handler are for "/version". I have a test cluster with a dozen nodes, and over the course of 5 minutes "userAgent: virt-handler/v0.0.0" made 1287 requests, 722 of these were for "/version".

Looking at some other larger clusters, virt-handler accounts for about 12%-40% of all API calls.

**What you expected to happen**:

Should figure out a way to reduce this traffic. I haven't looked into it far enough to determine whether or not this is actually a necessary thing to do each loop.

**How to reproduce it (as minimally and precisely as possible)**:

As far as I'm aware, by simply running virt-handler and collecting Kubernetes API audit logs.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.35.0
- Kubernetes version (use `kubectl version`): v1.18.9

### PR DESCRIPTION
**Pull request by mlsorensen**
Add functional test for healthz endpoint on virt-handler

Signed-off-by: Marcus Sorensen <mls@apple.com>

**What this PR does / why we need it**:

The change moves the Kubernetes API version check that is performed by the controller /healthz endpoints to a struct that acts as a cache. So long as the controller watches don't encounter errors, the result of /healthz is served from this cache.  If the controller watch fails, the watch error handler function is called, which clears the cache. This is reflected as unhealthy in the /healthz response, and the /healthz cache then checks connectivity to the Kubernetes API until it is re-established.

**Which issue(s) this PR fixes**:
Fixes #5058 

**Special notes for your reviewer**:
I wasn't sure how to come up with a proper test_id for the functional tests, so I took a guess.  This test is not fast, because it requires a certain amount of time for the watch to time out, if there's a more acceptable way to do this I'm happy to rework it. 

Ideally I would have liked to test the /healthz behavior against virt-api, virt-controller, and virt-handler, but the current virt-handler container is the only one with the tools necessary to block connectivity. It at least functionally tests the package.  I also considered trying to block this connectivity from the node level, but I'm not certain that would be as portable/compatible with various node configurations and networking types. Could also add ip utils to the virt-controller and virt-api but I didn't want to assume that it's worthwhile for just this one test.

```release-note
Controller health checks will no longer actively test connectivity to the Kubernetes API. They will rely in health of their watches to determine if they have API connectivity.
```

### CODE REVIEW

**Comment by rmohr** [comment]
> I wasn't sure how to come up with a proper test_id for the functional tests, so I took a guess.

You can ignore test_id. It is not needed.

File: tests/virt_control_plane_test.go [hunk 1]
```diff
@@ -230,6 +230,49 @@ var _ = Describe("[Serial][ref_id:2717]KubeVirt control plane resilience", func(
 
 		})
 
+		When("[test_id:2807]Control plane pods temporarily lose connection to Kubernetes API", func() {
```
Comment (xpivarc) [inline tests/virt_control_plane_test.go:233]: We usually use `Describe`, `Context`, `It`. Let's keep it that way for consistency if there is no benefit.
We need to add [Serial] because this affects kubevirt health and it would cause other tests to fail.
I think Ginkgo shuffles test cases so these `It` would not run one after another. We need to use `BeforeEach` and `AfterEach` to setup and remove blackhole

File: pkg/virt-api/api.go [hunk 2]
```diff
@@ -732,6 +735,11 @@ func (app *virtAPIApp) Run() {
 	kubevirtCAConfigInformer := kubeInformerFactory.KubeVirtCAConfigMap()
 	kubeVirtInformer := kubeInformerFactory.KubeVirt()
 
+	// Wire up health check trigger
+	configMapInformer.SetWatchErrorHandler(func(r *cache.Reflector, err error) {
+		apiHealthVersion.Clear()
```
Comment (xpivarc) [inline pkg/virt-api/api.go:740]: I would also keep the default behavior of `WatchErrorhandler` here.

**Review by xpivarc — CHANGES_REQUESTED** [review]
Thanks for the PR and investigation of this issue! I think we need a little bit of work on tests.

File: tests/virt_control_plane_test.go (hunk 1 above)
Comment (mlsorensen) [reply tests/virt_control_plane_test.go:233]: Just want to clarify here, you are saying the convention is to only have a single "When" in each "Context" - you want me to break this out into its own context?  Or that there should be no "When"? Trying to match convention within the existing test file.

I think I'll merge the recovery and just have a single 'It' case, if that is ok, to highlight that we want to have an explicit test of the recovery and it's not just a cleanup thing.

Comment (xpivarc) [reply tests/virt_control_plane_test.go:233]: Nevermind, seems we have used `When` in past, I apologize. 

>I think I'll merge the recovery and just have a single 'It' case, if that is ok, to highlight that we want to have an explicit test of the recovery and it's not just a cleanup thing.
Sounds good.

File: pkg/healthz/healthz.go [hunk 3]
```diff
@@ -32,32 +33,75 @@ import (
...
+			if err != nil {
+				unhealthy(err, clusterConfig, response)
+				return
+			}
+
+			hVersion.Update(version)
 		}
-		res["apiserver"] = map[string]interface{}{"connectivity": "ok", "version": version}
+
+		res["apiserver"] = map[string]interface{}{"connectivity": "ok", "version": hVersion.GetVersion()}
```
[the remark this answers is not in the document]
Comment (mlsorensen) [reply pkg/healthz/healthz.go]: I think I've got this covered now...

File: pkg/virt-api/api.go (hunk 2 above)
Comment (mlsorensen) [reply pkg/virt-api/api.go:740]: Calling the default error handler now. Looks like it just does some logging at the moment but who knows what it will do in the future.

**Comment by mlsorensen** [comment]
/retest

It doesn't look like the failure in pull-kubevirt-e2e-k8s-1.19 is related to this change, but if it continues to fail and other PRs are passing that I'll investigate.

**Comment by xpivarc** [comment]
/lgtm
@rmohr can you have a look, please?

**Comment by mlsorensen** [comment]
Does this need more work, @rmohr @xpivarc, or just waiting to be swept into next release?

**Comment by rmohr** [comment]
> Does this need more work, @rmohr @xpivarc, or just waiting to be swept into next release?

Sorry I missed the ping and was on PTO then. Looking now.

**Comment by mlsorensen** [comment]
@rmohr just wanted to check in on this again, hoping to get a fix for this into an official release. Thanks for the help.
