### PR TITLE
container-disk tests: fix alpine vs cirros mismatch

### LINKED ISSUE #15976: periodic-kubevirt-e2e-k8s-1.35-sig-compute: failing tests for new k8s provider 1.35
# What happened

Failing tests detected: [flakestats]
* ~`[sig-compute]SecurityFeatures Check virt-launcher securityContext With selinuxLauncherType defined as spc_t [test_id:3787]Should honor custom SELinux type for virt-launcher`~ [t1] (stopped failing after [Dec 18th](https://github.com/kubevirt/kubevirt/issues/15976#issuecomment-3701780441))
* `[rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]ContainerDisk Simulate an upgrade from a version where ImageVolume was disabled to a version where it is enabled Migration from a source launcher with the bind mount workaround to a target launcher without the bind mount workaround should succeed when using Cirros vmi with kernel boot` [t2]
* `[rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]ContainerDisk Simulate an upgrade from a version where ImageVolume was disabled to a version where it is enabled Migration from a source launcher with the bind mount workaround to a target launcher without the bind mount workaround should succeed when using simple Cirros vmi` [t3]
* `[rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-compute]ContainerDisk Simulate an upgrade from a version where ImageVolume was disabled to a version where it is enabled Migration from a source launcher with the bind mount workaround to a target launcher without the bind mount workaround should succeed when using Cirros vmi with custom location` [t4]

/kind failing-test

/sig compute

[flakestats]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2025-10-29.html#%5bsig-compute%5dSecurityFeatures%20Check%20virt-launcher%20securityContext%20With%20selinuxLauncherType%20defined%20as%20spc_t%20%5btest_id%3a3787%5dShould%20honor%20custom%20SELinux%20type%20for%20virt-launcher
[t1]: https://github.com/kubevirt/kubevirt/blob/1114d4874f134e4c5bb03c8f1bec6df70eb0ce96/tests/security_features_test.go#L130
[t2]: https://github.com/kubevirt/kubevirt/blob/1114d4874f134e4c5bb03c8f1bec6df70eb0ce96/tests/container_disk_test.go#L275
[t3]: https://github.com/kubevirt/kubevirt/blob/1114d4874f134e4c5bb03c8f1bec6df70eb0ce96/tests/container_disk_test.go#L262
[t4]: https://github.com/kubevirt/kubevirt/blob/1114d4874f134e4c5bb03c8f1bec6df70eb0ce96/tests/container_disk_test.go#L268

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### LINKED ISSUE #16757: Kernel-boot guests fail to boot to disk
**What happened**:
All the kernel-boot VMIs we start in our test suite look stuck on BIOS screen.
The screen reads:
```
SeaBIOS (version 1.16.3-4.el9)
Machine UUID xxx
Booting from ROM...
```
Guests actually start, which is only shown in the serial console, but fail to boot to disk and go to recovery mode instead.
Tests are currently passing because we never check if the guest actually started...

**What you expected to happen**:
The feature should work, guests should start and tests should make sure they can log in.

**How to reproduce it (as minimally and precisely as possible)**:
Add `Expect(console.LoginToAlpine(vmi)).To(Succeed())` to any kernel-boot test and watch it fail. VNCing to the test guest should show it stuck in BIOS. Console will show a recovery shell.

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): 1.35
- VM or VMI specifications: Alpine with kernel boot

### PR DESCRIPTION
**Pull request by jean-edouard**
#### Before this PR:
2 periodic container-disk tests are failing, for 2 different reasons.

#### After this PR:
One test was trying to migrate from Alpine to Cirros, which doesn't make sense, it's now fixed.
The other test uses kernel-boot, which needed an image update, done by the second commit.

### References
Fixes #15976
Fixes #16757

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by fossedihelm** [comment]
@jean-edouard Can u add the Fixes https://github.com/kubevirt/kubevirt/issues/15976?

File: tests/container_disk_test.go [hunk 1]
```diff
@@ -259,23 +259,27 @@ var _ = Describe("[rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:comp
...
 				libvmifact.NewAlpine(
 					libvmi.WithInterface(libvmi.InterfaceDeviceWithMasqueradeBinding()),
 					libvmi.WithNetwork(v1.DefaultPodNetwork()),
 				),
+				console.LoginToAlpine,
 			),
-			Entry("using  Alpine vmi with custom location", decorators.Periodic,
-				libvmifact.NewAlpine(
+			Entry("using Cirros vmi with custom location", decorators.Periodic,
+				libvmifact.NewCirros(
```
Comment (xpivarc) [inline tests/container_disk_test.go:272]: Didn't S390x folks changed to Alpine?

Comment (jean-edouard) [reply tests/container_disk_test.go:272]: Yes, but the custom location is still Cirros, so that breaks this test. Switching the custom location to Alpine is undesirable, since it would mean adding a big image to the build (Cirros is a few MBs, Alpine is a few hundreds)

Comment (xpivarc) [reply tests/container_disk_test.go:272]: Ok, let's just notify folks...

Comment (dhiller) [reply tests/container_disk_test.go:272]: > Didn't S390x folks changed to Alpine?

@vamsikrishna-siddu ICYMI please check whether there's some other action required

**Comment by dhiller** [comment]
/test pull-kubevirt-e2e-k8s-1.34-sig-compute-serial

cluster failure, retesting this

File: tests/container_disk_test.go (hunk 1 above)
Comment (vamsikrishna-siddu) [reply tests/container_disk_test.go:272]: @dhiller  I have checked, The changes are fine. No further action is required. The test should use cirros only.

**Comment by dhiller** [comment]
/override pull-kubevirt-e2e-k8s-1.34-sig-storage
/override pull-kubevirt-e2e-k8s-1.33-sig-storage

Both have been passing in a previous run on latest commit
