### PR TITLE
Do not create Host Disks for Virtio-FS PVCs

### LINKED ISSUE #4440: Disk image files are being created for Virtio-FS mounted volumes
/kind bug

**What happened**:
https://github.com/kubevirt/kubevirt/blob/2ae3155b63d3667bca960c27f2ef55e1cfd715f6/pkg/host-disk/host-disk.go creates a disk image for every mounted disk. When using Virtio-FS and mounting in a PVC to be mapped as a filesystem, a disk image should not be created.

**What you expected to happen**:
No disk image should be created on volumes used as filesystems.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VM as detailed in the Virtio-FS issue: https://github.com/kubevirt/kubevirt/pull/3493

**Anything else we need to know?**:
This fixed it. PR coming: https://github.com/salanki/kubevirt/commit/35d370fc1ef99ee420728716e3977f65735f4d32

**Environment**:
- KubeVirt version (use `virtctl version`): master

### PR DESCRIPTION
**Pull request by salanki**
**What this PR does / why we need it**:
`host-disk.go` assumes that all PVCs mounted into the Pod will be used to mount a Block Volume to the VM. Therefor it converts the PVCs to a `HostDisk` and later on creates a `disk.img` in there. This fix checks to see if the PVC is used in a `Filesystem`. If it is, it does not convert the PVC to a `HostDisk` and no disk image is created.

Fixes #4440

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix a bug where a disk.img file was created on filesystems mounted via Virtio-FS
```

### CODE REVIEW

**Comment by vladikr** [comment]
Thanks @salanki !

**Comment by vladikr** [comment]
@salanki will you be able to also add unit tests to make sure the code behaves as expected?
Please let me know if you need help/guidance wrt writing these.

**Comment by salanki** [comment]
I am sorry, but I have still not found the time to figure out unit tests for this :/

**Comment by salanki** [comment]
Can we get this merged?

**Comment by vladikr** [comment]
We need to add tests to verify this logic. 
I hope I'll have some time to add these this week if you can't.

File: pkg/virt-launcher/virtwrap/manager.go [hunk 1]
```diff
@@ -1259,6 +1265,12 @@ func (l *LibvirtDomainManager) SyncVMI(vmi *v1.VirtualMachineInstance, useEmulat
 	isBlockDVMap := make(map[string]bool)
 	diskInfo := make(map[string]*containerdisk.DiskInfo)
 	for i, volume := range vmi.Spec.Volumes {
+		for i := range vmi.Spec.Domain.Devices.Filesystems {
+			if vmi.Spec.Domain.Devices.Filesystems[i].Name == volume.Name {
+				volume.VolumeSource.PersistentVolumeClaim = nil
+				break
+			}
+		}
```
Comment (vladikr) [inline pkg/virt-launcher/virtwrap/manager.go:1273]: @salanki I'm wondering why is this needed?

File: pkg/virt-launcher/virtwrap/manager.go [hunk 2]
```diff
@@ -862,6 +862,12 @@ func (l *LibvirtDomainManager) PrepareMigrationTarget(vmi *v1.VirtualMachineInst
...
```
Comment (vladikr) [inline pkg/virt-launcher/virtwrap/manager.go:870]: This too?

**Review by vladikr — COMMENTED** [review]
I finally had some time to work on this. I've added tests and some minor changes. I'll push to your repo @salanki for this PR , if you don't mind.

Also one question in line.

**Review by jean-edouard — APPROVED** [review]
/ok-to-test
/approve

**Comment by jean-edouard** [comment]
/hold
Accidentally approved + lgtm-ed. Next reviewer, please cancel hold if lgty.

**Review by davidvossel — APPROVED** [review]
/lgtm

**Comment by salanki** [comment]
Thank you!
