### PR TITLE
tests: remove explicit CPU count in VM node selector test

### LINKED ISSUE #17021: periodic-kubevirt-e2e-test-S390X: failing `[sig-compute]VM Affinity Updating VMs node affinity [test_id:11208]should successfully update node selector`
# What happened

Failing test detected: `[sig-compute]VM Affinity Updating VMs node affinity [test_id:11208]should successfully update node selector` [1]

Example run: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-test-S390X/2029051815487606784

Log message:
```
{ Failure tests/hotplug/affinity.go:94
Timed out after 360.001s.
Expected
    <string>: VirtualMachine
to match fields: {
.Status.Ready:
	Expected
	    <bool>: false
	to be true
}

tests/hotplug/affinity.go:103}
```

/kind flake
/priority critical-urgent

/wg arch-s390x

FYI @vamsikrishna-siddu @jschintag 

[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2026-03-04.html#%5bsig-compute%5dVM%20Affinity%20Updating%20VMs%20node%20affinity%20%5btest_id%3a11208%5dshould%20successfully%20update%20node%20selector

## Additional context
See https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-test-S390X&width=20

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by tomlin7**
### What this PR does
**Learning from the flake:**
The root cause of this flake on `periodic-kubevirt-e2e-test-S390X` was test isolation. The test `[test_id:11208]should successfully update node selector` was explicitly requesting two CPU cores using `libvmi.WithCPUCount(1, 2, 1)`. In resource-constrained CI environments (like S390X VMs), this led to the VM pod hanging in the `Pending` state, which would eventually time out after 360 seconds while waiting to become `Ready`. Tests verifying high-level behaviors that are hardware-agnostic (like node-selectors) should avoid enforcing explicit resource requirements, as it makes them sensitive to the environment they run on.
#### Before this PR:
The test timed out in the CI environment because the VM pod got stuck in `Pending` due to the lack of CPU resources.
#### After this PR:
The unnecessary high CPU requirement is removed from the VM initialization for this test. The test VM now schedules reliably with minimal default resource requests, eliminating the flaky timeouts.
### References

Fixes #17021

### Why we need it and why it was done in this way
The following tradeoffs were made:
N/A - The explicit CPU topology has no effect on testing node selector hot-plugging. Dropping the requirement reduces resource demands without changing test validity.
The following alternatives were considered:
N/A
Links to places where the discussion took place: 
### Special notes for your reviewer
This fixes a critical-urgent flake (#17021).
/triage accepted

### Checklist
This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.
- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
- [ ] AI Contributions: The PR abides by the [KubeVirt AI Contribution Policy](https://github.com/kubevirt/community/blob/main/ai-contribution-policy.md).
### Release note

```release-note
NONE

### CODE REVIEW

**Comment by tomlin7** [comment]
@dankenigsberg @orelmisan Good suggestion, thanks!
I switched the test to `NewGuestless` in a separate commit to make it lighter.

File: tests/hotplug/affinity.go [hunk 1]
```diff
@@ -93,8 +93,8 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
 
 		It("[test_id:11208]should successfully update node selector", func() {
 
-			By("Creating a running VM")
-			vmi := libvmifact.NewAlpineWithTestTooling(libnet.WithMasqueradeNetworking(), libvmi.WithCPUCount(1, 2, 1))
+			By("Creating a guestless VM")
```
Comment (dankenigsberg) [inline tests/hotplug/affinity.go]: please don't change unrelated strings.
```suggestion
			By("Creating a running VM")
```

Comment (tomlin7) [reply tests/hotplug/affinity.go]: I thought that would be suitable, I'll revert it. Thanks.

**Comment by tomlin7** [comment]
Unrelated, but `"kubevirt.io/kubevirt/tests/libnet"` is an import that is not being used, should that be kept?

**Comment by orelmisan** [comment]
> Unrelated, but `"kubevirt.io/kubevirt/tests/libnet"` is an import that is not being used, should that be kept?

If it is not being used - the code will not compile.

**Comment by tomlin7** [comment]
> > Unrelated, but `"kubevirt.io/kubevirt/tests/libnet"` is an import that is not being used, should that be kept?
> 
> If it is not being used - the code will not compile.

I have removed the unused import, which was caused by my recent change.

**Review by dankenigsberg — APPROVED** [review]

**Comment by dhiller** [comment]
@tomlin7 thanks for this contribution, this is highly appreciated! :1st_place_medal: 

If you are willing to contribute further and can make it feel free to join sig-ci meeting next Monday 10 AM CET.

**Comment by tomlin7** [comment]
thanks, i'm glad! 
I'll do my best to join the meeting next Monday.
