### PR TITLE
Skip correct number of frames

### LINKED ISSUE #646: Log messages show incorrect position
A snippet from the virt-controller logs:

```
level=info timestamp=2018-01-11T22:05:29.479986Z pos=application.go:177 component=virt-controller service=http action=listening interface=0.0.0.0 port=8182
level=info timestamp=2018-01-11T22:05:29.489594Z pos=log.go:265 component=virt-controller service=http msg="STARTING informer migrationInformer"
level=info timestamp=2018-01-11T22:05:29.489617Z pos=log.go:265 component=virt-controller service=http msg="STARTING informer kubeVirtPodInformer"
level=info timestamp=2018-01-11T22:05:29.489623Z pos=log.go:265 component=virt-controller service=http msg="STARTING informer vmrsInformer"
level=info timestamp=2018-01-11T22:05:29.489628Z pos=log.go:265 component=virt-controller service=http msg="STARTING informer vmInformer"
level=info timestamp=2018-01-11T22:05:29.489644Z pos=log.go:261 component=virt-controller service=http msg="Starting VirtualMachineReplicaSet controller."
level=info timestamp=2018-01-11T22:05:29.490747Z pos=log.go:261 component=virt-controller service=http msg="Starting controller."
level=info timestamp=2018-01-11T22:05:29.490773Z pos=log.go:261 component=virt-controller service=http msg="Starting controller."
```

Shows a large number of messages being emitted from the "log.go" module (as opposed to the actual module that logged the original message). This is most likely due to incorrect counting of stack frames when looking up the calling function from within the log.go module.

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Fixes #646 

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

File: pkg/log/log.go [hunk 1]
```diff
@@ -147,11 +147,11 @@ func (e LogError) Error() string {
 }
 
 func (l FilteredLogger) Msg(msg interface{}) {
-	l.log(2, "msg", msg)
+	l.log(3, "msg", msg)
 }
 
 func (l FilteredLogger) Msgf(msg string, args ...interface{}) {
-	l.log(2, "msg", fmt.Sprintf(msg, args...))
+	l.log(3, "msg", fmt.Sprintf(msg, args...))
```
Comment (rmohr) [inline pkg/log/log.go]: I think that if you are now using Msgf or Msg directly, then it will show the wrong frame. for Errorf, ... we need here 3, for direct invocatoins 2.

Comment (cynepco3hahue) [reply pkg/log/log.go]: @rmohr I checked code and not found direct call to `Msgf` or to `Msg`, except calls in the `log.go` file and `log_test.go`.
I believe I can travel on the stack and check `callers` names, but for me looks more nice way just to restrict to import `Msgf` and `Msg`.
What do you think?

Comment (rmohr) [reply pkg/log/log.go]: Yes please make `msgf` and `msg` private that would work for me.

**Comment by rmohr** [comment]
ok to test
