### PR TITLE
Move our manifests to kube-system namespace

### LINKED ISSUE #300: Put all cloud admin controlled kubevirt resources in kubevirt namespace
Currently the manifests we include put all resources in the "default" namespace. In an anticipated production like deployment, all the kubevirt resources that are controlled by the cloud admin would want to be in a separate namespace than the tenant user created resources, so they are not visible or accessible to tenants by default. 

This entails updating the yaml.in files in manifests/ to add the 'kubevirt' namespace to them. The exception would be the PersistentVolumeClaim resources which should remain in the default namespace, since they must be accessible to the testvm resource.

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Resolves #300 

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
The single test that fails
```
09:56:27 [check-patch.el7.x86_64] [Fail] RegistryDisk Ephemeral RegistryDisk [It] should be able to start and stop the same VM multiple times. 
09:56:27 [check-patch.el7.x86_64] /home/jenkins/workspace/kubevirt_kubevirt_standard-check-pr/go/src/kubevirt.io/kubevirt/tests/utils.go:723
```
I ran it locally and all worked fine.

**Comment by rmohr** [comment]
ok to test

**Comment by cynepco3hahue** [comment]
@rmohr Can we redeploy our `https://rfenkhuber.fedorapeople.org/jenkins` environment, because I think it has a lot of remainings.
I changed namespace of all manifests, so when we will run `kubectl delete -f manifest` on the environment that still has resources under `default` namespace, it will not affect it, so we will have duplication of all resources under two different namespaces

**Comment by rmohr** [comment]
@cynepco3hahue permissions and service accounts are not clean up. That should be everything, and it actually should be cleaned up. That is actually a bug in the automation script.

The simplest option might be to do a PR first which can clean up both scenarios and then after this PR is merged, we can bring in that PR. That would be the least disruptive change for CI and engineers which use Vagrant. Later we can remove the outdated cleanup code. That is how I handled this in the past.

We also have a few options to improve the overall concept for such scenarios, by still keeping the same amount of caching, but I think it is easier if we don't change there too much inside this PR.

**Comment by cynepco3hahue** [comment]
@rmohr Ok will create additional PR for this one.

**Comment by cynepco3hahue** [comment]
@rmohr Can you please check #561

**Comment by cynepco3hahue** [comment]
@rmohr Retest please

**Comment by rmohr** [comment]
retest this please

**Comment by kfox1111** [comment]
I believe the kubernetes cores are trying to move stuff out of kube-system. a kubevirt namespace might be more appropriate.

**Comment by rmohr** [comment]
> I believe the kubernetes cores are trying to move stuff out of kube-system. a kubevirt namespace might be more appropriate.

Interesting. Do you have any links or an idea when that will land? We need to track that then. 

At least right now I think it is the place where it should most of the time be: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by rmohr** [comment]
retest this please

**Comment by kfox1111** [comment]
I'll try to dig up a refreence. I think it was mentioned in an issue with one of the other core components, like kube-dashboard or something where someone offhand mentioned they settled on the idea that there were too may things in kube-system and should be making more namespaces to ease permissions or something like that.

**Comment by cynepco3hahue** [comment]
The definition said that to make addon **critical**, you must move it to kube-system namespace, to be honest, I do not sure that KubeVirt components are critical for k8s cluster(like DNS for example), on the other side, the article uses UI and Heapster as examples for critical components, so I believe it very specific to k8s environment usage.

**Comment by rmohr** [comment]
> so I believe it very specific to k8s environment usage.

We are not critical to the k8s clusters native functionality (so isn't heapster either), but we add another workload type to k8s and even have operations like migrations running on it. We are part of the infrastructure. If someone honestly wants to run VMs, it is definitely expected that our controllers and APIs are available when there is high load on the cluster. The same for our host daemon which allows you to stop VMs in a well defined way, to reduce the load (killing qemu with sigkill is definitely only the last resort).

**Comment by cynepco3hahue** [comment]
convincingly enough :smile:

**Comment by cynepco3hahue** [comment]
Some strange things happen with our jenkins, we have double containers
```
libvirt-7pjjv                                 3/3       Running   0          43s
libvirt-8nztg                                 3/3       Running   0          43s
spice-proxy-7bc5cb46b5-w7h8l                  1/1       Running   0          43s
virt-api-568bd885f8-pmshw                     1/1       Running   0          42s
virt-controller-6cb9b89b84-8scj7              1/1       Running   0          41s
virt-controller-6cb9b89b84-txrkq              0/1       Running   0          41s
virt-handler-2r7nq                            1/1       Running   0          40s
virt-handler-q2jzm                            1/1       Running   0          40s
virt-manifest-6c948ccf94-mp6nc                2/2       Running   1          40s
weave-net-gkw8v                               2/2       Running   22         5d
weave-net-q5pzz         
```

**Comment by cynepco3hahue** [comment]
I do not sure, but it can be side effect of removing k8s service
`kubectl -n ${i} delete services -l '!k8s-app'`
I will create PR

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
@davidvossel could you also have a look at this one?

File: cluster/vagrant/setup_kubernetes_common.sh [hunk 1]
```diff
@@ -79,7 +79,7 @@ yum install -y \
 # Latest docker on CentOS uses systemd for cgroup management
 cat << EOT >>/etc/systemd/system/kubelet.service.d/09-kubeadm.conf
 [Service]
-Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --fail-swap-on=false"
+Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --fail-swap-on=false --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"
```
Comment (rmohr) [inline cluster/vagrant/setup_kubernetes_common.sh]: Why is this line changed? I didn't need that so far ...

Comment (cynepco3hahue) [reply cluster/vagrant/setup_kubernetes_common.sh]: ah this will clean a little `journalctl` from messages like
```
Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
```
it does not relate to the namespace, I just added it when I debug problems, so I can leave or remove it. Give me know what do you prefer

Comment (rmohr) [reply cluster/vagrant/setup_kubernetes_common.sh]: sounds looks like it is good to have it.

**Comment by fabiand** [comment]
This PR should have only moved the system but not demo components (i.e. iscsi demo targets) to the kube-system namespace.

We should separate between the components which belong to the runtime, and the components which are testing infrastructure.
