### PR TITLE
Fix deep subresource truncation in SubjectAccessReview

### LINKED ISSUE #17337: virt-api may truncate deep subresources when creating SubjectAccessReviews
**What happened**:

While reviewing `virt-api` authz flow, I noticed that deep subresources appear to be truncated when `virt-api` constructs a `SubjectAccessReview`.

In `pkg/virt-api/rest/authorizer.go`, `addNamespacedResourceAttributes()` parses the path with fixed indexes and sets:

https://github.com/kubevirt/kubevirt/blob/88326c3fa3702eaa35db636fbdc4581e8c1abf8c/pkg/virt-api/rest/authorizer.go#L214-L222

   For deep paths, this seems to keep only the first subresource segment, for example:
   •  /apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvmi/vnc/screenshot
     •  current SAR subresource appears to be: vnc
     •  expected: vnc/screenshot

   This kinda looks inconsistent with other places in the repo that use full deep subresource names like in:
   •  pkg/virt-operator/resource/generate/rbac/cluster.go
   •  tests/access_test.go

   Examples there include:
   •  virtualmachineinstances/vnc/screenshot
   •  virtualmachineinstances/sev/querylaunchmeasurement
   •  virtualmachineinstances/sev/setupsession
   •  virtualmachineinstances/sev/injectlaunchsecret
   •  virtualmachineinstances/evacuate/cancel
   •  virtualmachines/evacuate/cancel

   So there may be a mismatch between the exposed route / RBAC resource names, and the SAR that virt-api sends.

**What you expected to happen**:
   I expected virt-api to preserve the full deep subresource when building the SubjectAccessReview, so authz is evaluated against the same resource names KubeVirt
   defines and tests.

   Examples:
   •  vnc/screenshot → Subresource: "vnc/screenshot"
   •  sev/querylaunchmeasurement → Subresource: "sev/querylaunchmeasurement"
   •  evacuate/cancel → Subresource: "evacuate/cancel"

**How to reproduce it (as minimally and precisely as possible)**:
I have not yet verified this end-to-end in a live cluster, so I am filing this as a likely authz correctness issue.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by 0xFelix**
#### Before this PR:

`addNamespacedResourceAttributes()` uses `pathSplit[8]` to extract the subresource from the URL path, capturing only the first segment. Deep subresources like `vnc/screenshot`, `sev/fetchcertchain`, and `evacuate/cancel` are truncated to `vnc`, `sev`, `evacuate` - causing the SAR to check authorization against the wrong (broader) subresource name.

#### After this PR:

All remaining path segments are joined into the subresource name. For `portforward`, where trailing segments are dynamic parameters (port, protocol), only `portforward` is used. Single-segment subresources are unaffected.

### References

- Fixes #17337

### Why we need it and why it was done in this way

The SAR subresource must match the RBAC resource names defined in `pkg/virt-operator/resource/generate/rbac/cluster.go` (e.g. `virtualmachineinstances/vnc/screenshot`, `virtualmachineinstances/sev/fetchcertchain`). The truncation causes a mismatch between the authorization check and the actual RBAC rules.

The fix joins all remaining path segments with `strings.Join(pathSplit[8:], "/")`. `portforward` is special-cased because its trailing segments (`{port}`, `{protocol}`) are dynamic path parameters, not part of the subresource name.

### Special notes for your reviewer

The change is minimal and self-contained in two files for easy backporting.

### Checklist

- [x] Design: A [VEP (virtualization enhancement proposal)](https://github.com/kubevirt/enhancements/blob/main/README.md) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered
- [x] AI Contributions: The PR abides by the [KubeVirt AI Contribution Policy](https://github.com/kubevirt/community/blob/main/ai-contribution-policy.md).

### Release note
```release-note
Fixed virt-api truncating deep subresources (vnc/screenshot, sev/*, evacuate/cancel) when constructing SubjectAccessReviews, causing authorization checks against incorrect subresource names.
```

### CODE REVIEW

**Review by fossedihelm — COMMENTED** [review]
/lgtm

File: pkg/virt-api/rest/authorizer.go [hunk 1]
```diff
@@ -219,7 +219,12 @@ func addNamespacedResourceAttributes(pathSplit []string, requestMethod string, r
 	namespace := pathSplit[5]
 	resource := pathSplit[6]
 	resourceName := pathSplit[7]
-	subresource := pathSplit[8]
+	var subresource string
+	if pathSplit[8] == "portforward" {
```
Comment (xpivarc) [inline pkg/virt-api/rest/authorizer.go:226]: Please leave comment why

**Review by xpivarc — COMMENTED** [review]
/approve
/cherry-pick release-1.8 release-1.7 release-1.6 release-1.5 release-1.4 release-1.3 release-1.2 release-1.1 release-1.0

File: pkg/virt-api/rest/authorizer.go (hunk 1 above)
Comment (0xFelix) [reply pkg/virt-api/rest/authorizer.go:226]: Added

**Comment by 0xFelix** [comment]
/cherry-pick release-1.8 release-1.7 release-1.6 release-1.5 release-1.4 release-1.3 release-1.2 release-1.1 release-1.0
