### PR TITLE
template: set fsGroup unconditionally

### LINKED ISSUE #13141: flaky test: `[sig-storage] virtiofs VirtIO-FS with multiple PVCs [Serial] should be successfully started and accessible (unprivileged virtiofsd) `
# What happened

Flaky test detected: `[sig-storage] virtiofs VirtIO-FS with multiple PVCs [Serial] should be successfully started and accessible (unprivileged virtiofsd) ` [1] [2]

/kind flake
/priority critical-urgent

/sig compute

FYI @xpivarc asking you whether the storage-root test lane is still relevant?

[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-10-29-024h.html#row4
[2]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-10-28-024h.html#row5

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by germag**
With the "root" feature gate enabled a PVC will be mounted with root permissions, making virtiofsd to fail when writing to a PVC, since the virtiofs container runs unprivileged even if the pod runs as root.

### What this PR does
Before this PR:
virtiofsd fails to write to a PVC with the root feature gate enabled

After this PR:

Fixes #13141

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by germag** [comment]
cc @jcanocan

**Comment by alicefr** [comment]
@germag doesn't virtiofs runs with uid 0? If so, why setting the fsgroup to 107?

**Comment by germag** [comment]
> @germag doesn't virtiofs runs with uid 0? If so, why setting the fsgroup to 107?

No, the virtiofs container will run as 107 even if the root FG is enabled (this changed when the virtiofs FGs were adjusted)

Moreover, even when https://github.com/kubevirt/kubevirt/pull/14115 will be merged, all files will be created with the 107 uid/gid. So, the user will not be able to create root-owned files in the PVC. I think it's a good default, until there is a way to restrict the PVC for VMs only (maybe something similar on how the PVC are/will be protected with user namespace)

**Comment by alicefr** [comment]
@germag the unit tests needs to adjust but otherwise, it looks good

File: pkg/virt-controller/services/template_test.go [hunk 1]
```diff
@@ -3812,6 +3812,7 @@ var _ = Describe("Template", func() {
 				return api.NewMinimalVMI("fake-vmi")
 			}, &k8sv1.PodSecurityContext{
 				RunAsUser: new(int64),
+				FSGroup:   &nonRootUser,
```
[the remark this answers is not in the document]
Comment (germag) [reply pkg/virt-controller/services/template_test.go:3815]: I have to revert it. It seems the generic parameter of pointer.P is resolved before the `BeforeEach()` is called, so the test fails because it creates `PodSecurityContext{ ..., FSGroup: 0 }`

**Comment by germag** [comment]
> @germag the unit tests needs to adjust but otherwise, it looks good

do you mean the `pointer.P()`?

File: pkg/virt-controller/services/template_test.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (germag) [reply pkg/virt-controller/services/template_test.go]: Ok, cast the constant (I was trying to avoid it).

I can avoid that if we set the value of `nonRootUser` when is defined instead of inside the `BeforeEach()`

**Comment by alicefr** [comment]
> > @germag the unit tests needs to adjust but otherwise, it looks good
> 
> do you mean the `pointer.P()`?

CI was failing but I guess you already saw

File: pkg/virt-controller/services/template.go [hunk 2]
```diff
@@ -336,12 +336,15 @@ func generateQemuTimeoutWithJitter(qemuTimeoutBaseSeconds int) string {
 func computePodSecurityContext(vmi *v1.VirtualMachineInstance, seccomp *k8sv1.SeccompProfile) *k8sv1.PodSecurityContext {
 	psc := &k8sv1.PodSecurityContext{}
 
+	// virtiofs container will run unprivileged even if the pod runs as root,
+	// so we need to allow the NonRootUID for virtiofsd to be able to write into the PVC
+	nonRootUser := int64(util.NonRootUID)
+	psc.FSGroup = pointer.P(nonRootUser)
```
Comment (0xFelix) [inline pkg/virt-controller/services/template.go:342]:
```suggestion
	psc.FSGroup = &nonRootUser
```

Comment (0xFelix) [reply pkg/virt-controller/services/template.go:342]: nit

Comment (0xFelix) [inline pkg/virt-controller/services/template.go:342]:
```suggestion
	psc.FSGroup = pointer.P(int64(util.NonRootUID))
```

or like this :)

Comment (germag) [reply pkg/virt-controller/services/template.go]: done

**Review by 0xFelix — APPROVED** [review]
/lgtm

Thanks
