### PR TITLE
instancetype: Apply PreferredMachineType during VM mutation

### LINKED ISSUE #8338: PreferredMachineType never applied to VirtualMachineInstance
/area instancetype 

**What happened**:

Preferences are only applied to a `VirtualMachineInstance` when a user has not already provided a corresponding value within their `VirtualMachine` [1]. This is an issue for `PreferredMachineType` however as the `VirtualMachine` mutation webhook *always* provides some kind of default [2], resulting in the `PreferredMachineType` never being applied to the `VirtualMachineInstance`.
                                         
[1] https://github.com/kubevirt/kubevirt/blob/bcfbd78d803e9868e0665b51878a2a093e9b74c2/pkg/instancetype/instancetype.go#L950-L952     
[2] https://github.com/kubevirt/kubevirt/blob/bcfbd78d803e9868e0665b51878a2a093e9b74c2/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go#L98-L112   

**What you expected to happen**:

`setDefaultMachineType` within the `VirtualMachine` mutation webhook needs to lookup and apply a preference if provided, overwriting any configured default.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat <<EOF | ./cluster-up/kubectl.sh apply -f - 
> ---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachineInstancetype
metadata:
  name: clarge
spec:
  cpu:
    guest: 4
  memory:
    guest: 2Gi
---
apiVersion: instancetype.kubevirt.io/v1alpha1
kind: VirtualMachinePreference
metadata:
  name: machinetype
spec:
  machine:
    preferredMachineType: "pc-q35-6.2"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: example
spec:
  instancetype:
    kind: VirtualMachineInstancetype
    name: clarge
  preference:
    kind: VirtualMachinePreference
    name: machinetype
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: containerdisk
          - disk: {}
            name: cloudinitdisk
        resources: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk
> EOF
$ ./cluster-up/kubectl.sh get vm/example -o json | jq .spec.template.spec.domain.machine
selecting docker as container runtime
{
  "type": "q35"
}
$ ./cluster-up/kubectl.sh get vmi/example -o json | jq .spec.domain.machine
selecting docker as container runtime
{
  "type": "q35"
}

```

**Additional context**:

This was missed by the current functional tests as they also used the default value of `q35`. It was only picked up when running the functional tests against an environment with a configured default that differed to `q35`.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @akrejcir 

**What this PR does / why we need it**:

Previously the MachineType of a VirtualMachine was *always* populated by
the VirtualMachine mutation webhook, either by user input, cluster
configuration or a default. This would cause any attempt to later apply
the PreferredMachineType preference within the VirtualMachine controller
to fail as it was assumed this value was provided by the user.

This change corrects this by looking up any referenced preferences and
applying PreferredMachineType to the VirtualMachine before falling back
to the cluster config and default values. Any errors raised by this
lookup are ignored as they will be caught by the validation webhook
later during the admission.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8338

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 1]
```diff
@@ -96,19 +98,39 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
...
-		vm.Spec.Template.Spec.Domain.Machine = &v1.Machine{Type: machineType}
+	if machine := vm.Spec.Template.Spec.Domain.Machine; machine != nil && machine.Type != "" {
+		return
+	}
+
+	if vm.Spec.Template.Spec.Domain.Machine == nil {
+		vm.Spec.Template.Spec.Domain.Machine = &v1.Machine{}
+	}
+
+	if vm.Spec.Preference != nil {
```
Comment (akrejcir) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:114]: No need to check for `nil` here, because `mutator.InstancetypeMethods.FindPreferenceSpec(vm)` will return nil if preference is not assigned to the VM.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 2]
```diff
@@ -96,19 +98,39 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
...
+		vm.Spec.Template.Spec.Domain.Machine.Type = mutator.setPreferenceMachineType(vm)
+	}
+
+	// Only use the cluster default if the user hasn't provided a machine type or referenced a preference with PreferredMachineType
+	if vm.Spec.Template.Spec.Domain.Machine.Type == "" {
+		vm.Spec.Template.Spec.Domain.Machine.Type = mutator.ClusterConfig.GetMachineType()
+	}
+}
+
+func (mutator *VMsMutator) setPreferenceMachineType(vm *v1.VirtualMachine) string {
```
Comment (akrejcir) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:124]: Name of this method is confusing, it does not set anything.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 3]
```diff
@@ -96,19 +98,39 @@ func (mutator *VMsMutator) Mutate(ar *admissionv1.AdmissionReview) *admissionv1.
...
+	preferenceSpec, err := mutator.InstancetypeMethods.FindPreferenceSpec(vm)
+	if preferenceSpec != nil && preferenceSpec.Machine != nil {
+		return preferenceSpec.Machine.PreferredMachineType
+	}
+	// Log but ultimately swallow any preference lookup errors here and let the validating webhook handle them
+	if err != nil {
```
Comment (akrejcir) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:130]: Error checking is usually done before using the first return value. Can you move this `if` directly below the call to `mutator.InstancetypeMethods.FindPreferenceSpec(vm)` ?

**Review by akrejcir — COMMENTED** [review]
Looks good. I only have small codestyle comments, but you can ignore them if you want.

/lgtm

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 2 above)
Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:124]: ACK apoloigies this should be `getPreferenceMachineType`.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 3 above)
Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:130]: Yeah apologies I was just trying to avoid multiple returns when one would do but I take your point, this doesn't look correct.

**Comment by lyarwood** [comment]
@vladikr Any thoughts on this? I was toying with the idea of moving all of the machinetype defaulting to the VM controller but I might be missing something and could always attempt that in a follow up once this bugfix lands. Anyway, thoughts appreciated!

**Review by davidvossel — COMMENTED** [review]
/approve
/hold

@vladikr did you want to look at this before it goes in?

**Comment by lyarwood** [comment]
@brianmcarey any idea how I can get `tide` to trigger correctly here given `pull-kubevirt-fossa` has been dropped AFAIK?
