### PR TITLE
virt-api: unencode authorization extra headers

### LINKED ISSUE #12459: Unable to do virtctl image-upload on GKE
**What happened**:
When I try to do a `virtctl image-upload` I always get  the following error ` the server has asked for the client to provide credentials (post uploadtokenrequests.upload.cdi.kubevirt.io)`. The PVC is created but the actual image is never uploaded.

**What you expected to happen**:
I expect to have the example `cirros` image to be uploaded to the PVC.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

```
$ virtctl image-upload --pvc-name=cirros-vm-disk2  --access-mode=ReadWriteOnce --storage-class=csi-filestore-multishare-sharedvpc --pvc-size=10Gi --image-path=/tmp/ cirros-0.4.0-x86_64-disk.img --uploadproxy-url=https://100.65.219.185:31001 --insecure
```
**Additional context**:
```
$virtctl image-upload --pvc-name=cirros-vm-disk2  --access-mode=ReadWriteOnce --storage-class=csi-filestore-multishare-sharedvpc --pvc-size=10Gi --image-path=/tmp/cirros-0.4.0-x86_64-disk.img --uploadproxy-url=https://100.65.219.185:31001 --insecure

Flag --pvc-name has been deprecated, specify the name as the second argument instead.
Flag --pvc-size has been deprecated, use --size instead.
Using existing PVC default/cirros-vm-disk2
Uploading data to https://100.65.219.185:31001
the server has asked for the client to provide credentials (post uploadtokenrequests.upload.cdi.kubevirt.io)
```

Logs from `cdi-apiserver`:

```
│ I0725 10:06:41.923083       1 apiserver.go:92] Note: increase the -v level in the api deployment for more detailed logging, eg. -v=2 or -v=3                                                                                                            │
│ W0725 10:06:41.923378       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.                                                                                                  │
│ I0725 10:06:42.138395       1 certwatcher.go:125] Updated current TLS certificate                                                                                                                                                                       │
│ I0725 10:06:42.150976       1 certwatcher.go:81] Starting certificate watcher                                                                                                                                                                           │
│ 2024/07/25 10:06:58 http: TLS handshake error from 10.88.2.181:49753: EOF                                                                                                                                                                               │
│ 2024/07/25 10:06:59 http: TLS handshake error from 10.88.2.181:2411: EOF                                                                                                                                                                                │
│ I0725 10:07:05.982325       1 apiserver.go:320] Rejected Request:                                                                                                                                                                                       │
│ 2024/07/25 10:07:58 http: TLS handshake error from 10.88.2.181:38192: EOF                                                                                                                                                                               │
│ I0725 10:08:22.153585       1 apiserver.go:320] Rejected Request:                                                                                                                                                                                       │
│ 2024/07/25 10:08:59 http: TLS handshake error from 10.88.2.181:6220: EOF  
```

**Environment**:
- KubeVirt version (use `virtctl version`): `v1.3.0`
- Kubernetes version (use `kubectl version`): `v1.29.4-gke.1043002`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mhenriks**
### What this PR does
Before this PR:

virt-api is broken on GKE because not decoding "extra" authorization header named X-Remote-Extra-Iam.gke.io%2fuser-Assertion:

After this PR:

Correctly decode header

Fixes #12459

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
virt-api: unencode authorization extra headers
```

### CODE REVIEW

File: pkg/virt-api/rest/authorizer.go [hunk 1]
```diff
@@ -115,13 +116,25 @@ func (a *authorizor) getUserName(header http.Header) (string, error) {
...
+
 func (a *authorizor) getUserExtras(header http.Header) map[string]authv1.ExtraValue {
 	extras := map[string]authv1.ExtraValue{}
 
 	for _, prefix := range a.userExtraHeaderPrefixes {
 		for k, v := range header {
-			if strings.HasPrefix(k, prefix) {
-				extraKey := strings.TrimPrefix(k, prefix)
+			if hasPrefixIgnoreCase(k, prefix) {
+				extraKey := unescapeExtraKey(strings.ToLower(k[len(prefix):]))
```
Comment (mhenriks) [inline pkg/virt-api/rest/authorizer.go:137]: Changes "inspired" by: https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/request/headerrequest/requestheader.go#L180-L204

**Review by 0xFelix — APPROVED** [review]
Awesome find!

Looks good to me.

/lgtm

**Comment by 0xFelix** [comment]
It should also fix https://github.com/kubevirt/kubevirt/issues/11221

File: pkg/virt-api/rest/authorizer.go (hunk 1 above)
Comment (davidvossel) [reply pkg/virt-api/rest/authorizer.go:137]: @mhenriks I understand the unescape logic, i don't understand the implications of reducing the key to lower case though. Why is that done here?

Comment (mhenriks) [reply pkg/virt-api/rest/authorizer.go:137]: @davidvossel not exactly sure why, probably subjectaccessreview API expects lower case? Nevertheless I think it is best to do exactly what the k8s reference apiserver does

Comment (mhenriks) [reply pkg/virt-api/rest/authorizer.go:137]: Maybe this explains it:  https://github.com/kubernetes/apiserver/blob/c8097e3f30c749fa023c708d54ba855cbd53fbc6/pkg/authentication/user/user.go#L39-L41

**Review by davidvossel — COMMENTED** [review]
/approve

**Comment by 0xFelix** [comment]
@mhenriks @davidvossel Do we want to backport this to `release-1.3`, `release-1.2` and `release-1.1`?
