### PR TITLE
virt-controller: render hp-volume- pod should respect blockdevices

### LINKED ISSUE #9263: The hotplug volume pod killed more time would lead the iSCSI re-login
**What happened**:
The VM with hotplug volume. If the hotplug volume pod `hp-volume-` is dead more than twice. The iSCSI connection on the host would logout/login. That makes the above hotplug volume not used anymore. If the user tries to access this device, that will trigger an IO error.

**What you expected to happen**:
The hotplug volume should normally work even if the `hp-volume-` pod is dead more than twice.

**How to reproduce it (as minimally and precisely as possible)**:
1. create one VM instance.
2. attach the hotplug volume.
3. manually delete the `hp-volume-xxx`.
4. manually delete the `hp-volume-xxx` (newly hp-volume- pod) again.
5. You could check the iSCSI connection will logout then login. Also, the disk on the VM should be also broken.

**Additional context**:
We found that because the global path is detached by kubelet when we delete `hp-volume-` pod first time.
Then when we delete the `hp-volume-` pod again. The kubelet would detach from the node directly. Then after the new `hp-volume- pod` comes back, attach it to the node again.
The brief flow is as follows:
```
hp-volume-aaa
  -> killed, then hp-volume-bbb creating
  -> kubelet try to detach but fail (because the volume is still mounted (global path), then new pod is coming back, everything is fine)
  -> umount global/staging path
hp-volume-bbb
  -> killed, then hp-volume-ccc creating
  -> kubelet try to detach from node and success (because now the global path is unmounted)
hp-volume-ccc
```

**Environment**:
- KubeVirt version (use `virtctl version`): 0.54.0
- Kubernetes version (use `kubectl version`): 1.24.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Longhorn CSI
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**What this PR does / why we need it**:
This PR would render the VolumeDevices on the `hp-volume-` pod, no matter if it is ever generated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9263 

**Special notes for your reviewer**:
I already had some discussions with @awels on this [thread](https://kubernetes.slack.com/archives/C8ED7RKFE/p1675734184935669).
We could continue here and also make it a note.

Thanks for your review!

**Release note**:
```
Render VolumeDevices to hp-volume- no matter if it is ever generated.
```

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
Hi @0xFelix 
I am not sure about some failure cases because look like does not relate to my changes.
I tried re-run and it passed. Are some test cases unstable now?

Thanks!

**Comment by 0xFelix** [comment]
Hi @Vicente-Cheng,

test lanes fail from time to time due to external factors. If they succeed on a second try (as they did now) usually everything is fine with your change.

Regarding your change, can you give a little more context how your fix works? IIUC it is a workaround for wonky iSCSI implementations?

File: pkg/virt-controller/services/template.go [hunk 1]
```diff
@@ -845,20 +841,21 @@ func (t *templateService) RenderHotplugAttachmentPodTemplate(volumes []*v1.Volum
...
+		if pvc == nil {
+			continue
+		}
+		if types.IsPVCBlock(pvc.Spec.VolumeMode) {
+			pod.Spec.Containers[0].VolumeDevices = append(pod.Spec.Containers[0].VolumeDevices, k8sv1.VolumeDevice{
+				Name:       volume.Name,
+				DevicePath: fmt.Sprintf("/path/%s/%s", volume.Name, pvc.GetUID()),
+			})
+		} else {
+			if !skipMount {
```
Comment (vasiliy-ul) [inline pkg/virt-controller/services/template.go:854]: I remember that at the times when hotplug volumes with a single attachment pod and live migration support were introduced, we also had some conversations with @awels regarding `VolumeMounts/VolumeDevices`. But as of now I cannot recall the details why it was decided to not add the already attached volumes. Perhaps it was related to issues with some specific CSI... Anyway, with a single attachment pod and current implementation, I cannot think of any particular problem that may arise if we mount the volume here. When adding new volumes, we first delete the existing pod and then create a new one... so I guess it should not cause troubles with making it available for multiple pods.

However, if doing it for block volumes, then I suppose the same behavior should also be used for filesystem. Or is there any reason why we would want hotplug volumes to behave differently depending on the type?

Actually, a similar approach was suggested in https://github.com/kubevirt/kubevirt/pull/6728#issuecomment-1081062069. But seems it never moved from there.

Ping @awels, @alicefr, @mhenriks, Maybe you guys have thoughts here?

**Review by vasiliy-ul — COMMENTED** [review]
Hi @Vicente-Cheng, 

The proposed change may work, I think. Though would be nice to have some feedback from storage folks here as this potentially may affect some CSIs in a bad way. I cannot think of any particular issue as of now. The only thing that I see missing is the test for the described use case. I think if the approach is agreed, we definitely need to have the test.

**Comment by vasiliy-ul** [comment]
> create one VM instance.
attach the hotplug volume.
manually delete the hp-volume-xxx.
manually delete the hp-volume-xxx (newly hp-volume- pod) again.
You could check the iSCSI connection will logout then login. Also, the disk on the VM should be also broken.

Hm... thinking a bit more about the issue: how does this change solve the problem? It just adds one more step: when hp-volume-xxx pod is deleted, the volume will be unmounted. The rest shall behave the same way, no?

**Comment by Vicente-Cheng** [comment]
> Hi @Vicente-Cheng,
> 
> test lanes fail from time to time due to external factors. If they succeed on a second try (as they did now) usually everything is fine with your change.
> 
> Regarding your change, can you give a little more context on how your fix works? IIUC it is a workaround for wonky iSCSI implementations?

Hi @0xFelix, thanks for the explanation for the test lanes!

Yap, this change focused on the iSCSI-like CSI driver. I am curious about the wonky iSCSI implementation. Would you like to describe it in more detail? Thanks!

For this change, I would like to make publish/staging again when the second `hp-volume-` pod comes back.
The problems we meet are brief as follows:
1. the first `hp-volume-` pod is somehow killed
1.1. the `kubelet` tries to detach this volume, but the global path is still in use. Failed. 
1.2 the global path is unmounted with `kubelet`
1.3 the second `hp-volume-` pod comes back, and kubelet would not try to detach this volume more.

2. the second `hp-volume-` pod is somehow killed again
2.1 the `kubelet` tries to detach this volume, and the global path does not exist. Successed.
2.2 the detachment would lead iSCSI logout
2.3 the third `hp-volume-` pod comes back, and the controllerpublish stage is called again. iSCSI login.

Now, the VM volume is no longer used due to the iSCSI reset.

The changes I would like to introduce is that the global/staging path should be here (means that do NodePublish/NodeStage again) when the second (third, fourth ...etc)`hp-volume-` pod comes back.

File: pkg/virt-controller/services/template.go (hunk 1 above)
Comment (Vicente-Cheng) [reply pkg/virt-controller/services/template.go:854]: Thanks, @vasiliy-ul. I checked the https://github.com/kubevirt/kubevirt/pull/6728#issuecomment-1081062069 you mentioned. Yes, that is a similar approach. I do not know more details about this skipping, so I only change a few works (as you see, I do not change the FS-related behavior). I describe more detail with my changes in the following https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436764795.

Thanks for your help here!

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: > Thanks, @vasiliy-ul. I checked the [#6728 (comment)](https://github.com/kubevirt/kubevirt/pull/6728#issuecomment-1081062069) you mentioned. Yes, that is a similar approach. I do not know more details about this skipping, so I only change a few works (as you see, I do not change the FS-related behavior). I describe more detail with my changes in the following [#9269 (comment)](https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436764795).
> 
> Thanks for your help here!

You aren't changing the FS but the block devices yes. I'm not sure if we can always assign a block device to the hotplug pod. This might work for ISCSI csi protocol but not for other storage providers. Before accepting this change, we need to be sure about the behavior of the block devices

Comment (vasiliy-ul) [reply pkg/virt-controller/services/template.go:854]: While going through the previous discussions about this topic, I've got an impression that the main problem here is that CSI implementations behave differently. Some of them do not support attaching RWO to several pods, hence we need to first delete the existing attachment pod and then create a new one. Some others (like in this case) on the opposite does not like such a flow and requires that a new attachment pod is created before the old one gets dropped. I wonder: can we support both use cases in KubeVirt? Like by introducing a policy setting in the CR (e.g. `attachmentPodCreationPolicy`) which will allow configuring the creation/deletion order of attachment pods?

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: @vasiliy-ul how would you know when you need to assign this policy? Generally, kubevirt doesn't introspect which kind of storage class is the PVC. In this case, you would also need some kind of mapping that recognize if that storage class conflict with the default hotplug attachment policy

Comment (vasiliy-ul) [reply pkg/virt-controller/services/template.go:854]: I think the policy should be adjusted by the end-user. Not proposing to keep a mapping of storage classes. Probably the default behavior would be to keep the existing flow (i.e. delete-and-create). But when needed, this can be changed to create-and-delete by modifying the setting in the CR.

Comment (vasiliy-ul) [reply pkg/virt-controller/services/template.go:854]: ... ah, you mean a mapping to handle the case when there are multiple storage classes in the cluster from different providers. And how to assign individual policy to each of them, right?

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: yes, such a policy depends on the storage class of the PVC and you might have different storage providers with different behaviors. It is a tricky problem to solve. 
For example, certain storage providers implement differently the RWO mode. In general, this should mean attaching to a single node, but multiple pods on the same node could access the storage. However, in certain cases, this means a single pod. That wasn't one of the reasons why https://github.com/kubevirt/kubevirt/pull/6728 was raising concerns

Comment (vasiliy-ul) [reply pkg/virt-controller/services/template.go:854]: Yeah, that is a valid point. The policy setting in the CR will not solve all the problems. However, it might still be an improvement and a short-term fix for some use cases while elaborating a better solution.

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: I'm not sure if it should be a policy in the CR or rather an annotation set by the user. It depends on who is responsible to know this information.

Comment (Vicente-Cheng) [reply pkg/virt-controller/services/template.go:854]: Thanks @alicefr,
I agree that changes might introduce some side-effect on other storage providers. 

For the behavior of block devices on the hot-plug pod. The `kubelet` would call node stage/publish again if the `voluemDevices` contain the item.
For now, we set up the volume in `Volumes` but not in the `VolumeDevices` when rendering the second `hp-volume-` pod.
At this moment, the `kubelet` would think this volume is unused, so it would do no-op. I am confused why we want to make`kubelet` think this volume is unused. (with the second `hp-volume-` pod handling)

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: @Vicente-Cheng I think @awels's comment [here](https://github.com/kubevirt/kubevirt/pull/5649#issuecomment-865913057) might answer your question

Comment (Vicente-Cheng) [reply pkg/virt-controller/services/template.go:854]: Thanks, @alicefr. 
That's good tips for the reason that we using the skipMount.

I thought that was the reason (from the comment), right?
> We were having issues with for instance rook-ceph-rbd RWO filesystem volumes, where attempting to mount on the second pod would fail because there was a RW file system mounted somewhere else (in the VM). At first we attempted a read only mount in the flip flop pod, but some provisioners don't support read only volumes (in particular longhorn). But we then realized the real purpose of the attachment pods is to attach the volume to the node and have a reference that can properly clean up the attachment, but we don't really care if the volume is mounted in that pod once the VM is using it.

A quick checking for the rbd CSI behavior. (If I got some misunderstanding, please correct me. Thanks!)
On the NodeStage path, it looks like two following cases:
1. Block volume, use the bind mount
2. FS volume, use mount directly
On the NodePublish path, it looks similar to the above.
1. Block volume, create mount path
2. FS volume, create mount directory

Does the above problem have happened on the FS volume?

Comment (alicefr) [reply pkg/virt-controller/services/template.go:854]: On this, we need to ask @awels, I don't know if we have encounter the problem on fs volumes

Comment (Vicente-Cheng) [reply pkg/virt-controller/services/template.go:854]: Sure, we could wait for his thoughts. Then, he would be able to tell me more about this situation. And indeed, we need to consider more about both fs volumes/block volumes. Thanks!

Comment (awels) [reply pkg/virt-controller/services/template.go:854]: Note I don't know https://github.com/kubevirt/kubevirt/pull/6728 and this PR are solving the same issue. The approach is definitely different. In the other PR we create a new pod first, and then delete the old pod. In this PR the order remains the same, it is just that for block volumes, we go through the CSI publish stage because we are specifying the volumeDevices section in the new pod for existing volumes.

@Vicente-Cheng have you verified this fixes the issue for your provisioner?

Comment (awels) [reply pkg/virt-controller/services/template.go:854]: And when you verify, have you also verified that if you use a filesystem volume on your provisioner that you don't have the exact same issue?

**Comment by awels** [comment]
So just to re-iterate, I have no issues with this PR.

**Comment by Vicente-Cheng** [comment]
> So just to re-iterate, I have no issues with this PR.

Thanks, @awels, I will still verify on fs volume with this change. And try to update here ASAP.

**Comment by Vicente-Cheng** [comment]
Hi @awels, sorry for the late update.
I tested with the filesystem PVC by using nfs-ganesha and its csi-provisioner as follows:
1. create pvc with nfs
2. create disk.img for hotplug attaching
3. attached to VM
4. Run IO on this hotplug device by fio
5. delete hp-volume- pod serval times

And IO looks good. Also doesn't see any errors on virt-handler.  So I thought this PR would also be OK with fs volume part.
Would we continue with this PR?

**Comment by awels** [comment]
Thanks, lets get an approver in here to approve the PR. @mhenriks or @vasiliy-ul can you review and approve?
/lgtm

**Comment by vasiliy-ul** [comment]
The code looks good from my perspective. I just think that it would be nice to have this covered with some tests. If it is hard to test it end-to-end in CI, maybe we can add a unit test then? E.g. like here:

https://github.com/kubevirt/kubevirt/blob/6c87184a5c688d730d819fa9d9092f6bbff1ece4/pkg/virt-controller/services/template_test.go#L3785

In this PR, we change the behavior: previously with `vmi.Status.VolumeStatus` equal to `v1.VolumeReady` or `v1.HotplugVolumeMounted` the `VolumeDevices` section was not rendered. Now it is rendered irrespective of the status. Would it make sense to fix and document the new behavior by adding a test?

**Comment by vasiliy-ul** [comment]
> I still fail to understand why this fixes the ISCSI logout problem. I'd assume that when the first hp pod is deleted then, it will basically log out and break the storage on the VM? How does this fix prevent the ISCSI plugin from logging out from the node?

That was also my concern https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436643861. If I understood it correctly from https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436781391, this does not fix the logout. But when the pod is restored after being deleted, it will login again due to `VolumeDevices`.

**Comment by alicefr** [comment]
> > I still fail to understand why this fixes the ISCSI logout problem. I'd assume that when the first hp pod is deleted then, it will basically log out and break the storage on the VM? How does this fix prevent the ISCSI plugin from logging out from the node?
> 
> That was also my concern [#9269 (comment)](https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436643861). If I understood it correctly from [#9269 (comment)](https://github.com/kubevirt/kubevirt/pull/9269#issuecomment-1436781391), this does not fix the logout. But when the pod is restored after being deleted, it will login again due to `VolumeDevices`.

Thanks, yes this makes sense.

**Comment by Vicente-Cheng** [comment]
> The code looks good from my perspective. I just think that it would be nice to have this covered with some tests. If it is hard to test it end-to-end in CI (as I understand, this requires a specific iSCSI storage provisioner), maybe we can add a unit test then? E.g. like here:
> 
> https://github.com/kubevirt/kubevirt/blob/6c87184a5c688d730d819fa9d9092f6bbff1ece4/pkg/virt-controller/services/template_test.go#L3785
> 
> In this PR, we change the behavior: previously with `vmi.Status.VolumeStatus` equal to `v1.VolumeReady` or `v1.HotplugVolumeMounted` the `VolumeDevices` section was not rendered. Now it is rendered irrespective of the status. Would it make sense to fix and document the new behavior by adding a simple test verifying that `VolumeDevices` is always rendered?

Thanks @vasiliy-ul for the review.
I would like to add some tests for verifying `VolumeDevices` is always rendered!

**Comment by Vicente-Cheng** [comment]
> Let me ask again about this fix.
> 
> Basically, now we are assuming for Block PVCs that the storage device plugin will never fail to mount the device on the hp pod, while for FS PVC if the path is already mounted in virt-launcher, it only performs the attachment.
> 
> I still fail to understand why this fixes the ISCSI logout problem. I'd assume that when the first hp pod is deleted then, it will basically log out and break the storage on the VM? How does this fix prevent the ISCSI plugin from logging out from the node?

Thanks @alicefr for giving this thought.
Yap, briefly, as @vasiliy-ul says.
render the new `hp-volume-` pod with volumeDevices would make iSCSI login again for the global path. 
Then kubelet would not detach it.

I would like to give some timelines that may be present as the figure for the detail.

**Comment by Vicente-Cheng** [comment]
Hi @vasiliy-ul, @alicefr

I add the unittest with this PR. Please help to recheck it.

Also, describe the behavior change with the following figures.
The original behavior:
hotplugvolume_orig

We could know that because the global path is mounted after hp-volume- pod is killed the first time, the second time when hp-volume- pod is killed. The kubelet will trigger the csi driver to do controllerUnpublish. That will make some iSCSI-liked CSI driver logout of the connection, and it will cause the IO error.

The new behavior:
hotplugvolume_new

The changed behavior will still generate the volumeDevice, which means the CSI driver will keep the staging/global path alive. That even next time we try to kill the hp-volume- pod, the kubelet volume manager did not call the controllerUnpublish because we still have a global path (that will return an error with resource busy). The iSCSI-liked CSI driver would still work well.

Hope that will be more clarify with the above discussions. Thanks!

**Review by vasiliy-ul — APPROVED** [review]
LGTM

File: pkg/virt-controller/services/template_test.go [hunk 2]
```diff
@@ -3751,6 +3746,96 @@ var _ = Describe("Template", func() {
...
+			mode := kubev1.PersistentVolumeBlock
+			pvc := kubev1.PersistentVolumeClaim{
+				TypeMeta:   metav1.TypeMeta{Kind: "PersistentVolumeClaim", APIVersion: "v1"},
+				ObjectMeta: metav1.ObjectMeta{Namespace: namespace, Name: pvcName},
+				Spec: kubev1.PersistentVolumeClaimSpec{
+					VolumeMode: &mode,
+				},
+			}
+			claimMap := map[string]*kubev1.PersistentVolumeClaim{volumeName: &pvc}
+			Expect(claimMap[volumeName]).To(Equal(&pvc))
```
[the remark this answers is not in the document]
Comment (Vicente-Cheng) [reply pkg/virt-controller/services/template_test.go]: ditto, fixed!

**Comment by vasiliy-ul** [comment]
/lgtm

> I'd like confirmation from @awels and @vasiliy-ul that the PR is fine

I think @awels already lgtm'ed the PR... just in case that was missed...
