### PR TITLE
volume-migration: fix migration from source RWX volumes

### LINKED ISSUE #12811: StorageMigrations fails from RWX to RWX DataVolume
**What happened**:
I try to make use of StorageMigration by following this guide: https://kubevirt.io/user-guide/storage/volume_migration/
Right now the migration gets triggered but then fails with this error message:
`Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=84, Domain=10, Message='Operation not supported: use of 'VIR_MIGRATE_PARAM_MIGRATE_DISKS' requires use of 'VIR_MIGRATE_NON_SHARED_DISK' or 'VIR_MIGRATE_NON_SHARED_INC' flag'`

**What you expected to happen**:
The LiveMigration should be successful and the new instance runs on the new DV.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two RWX StorageClasses
2. Create a VM with DataVolumeTemplate which uses one of the StorageClasses
3. Create a new DV on the other StorageClass
4. Update the VM spec to use the new DV
5. LiveMigration should get trigger and fail with the error.

**Additional context**:
I currently running KubeVirt on main branch version (image tag: 20240911_926edf646) because of this issue here: https://github.com/kubevirt/kubevirt/issues/12519

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): 1.30.0
- VM or VMI specifications: 
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-dv
  name: vm-dv
spec:
  updateVolumesStrategy: Migration
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
#        name: src-dv
        name: dst-dv
      spec:
        storage:
          accessModes:
            - ReadWriteMany
          volumeMode: Block
          resources:
            requests:
              storage: 10Gi
          storageClassName: sc-san-standard
        source:
          http:
            url: http://192.168.160.22/jammy-server-cloudimg-amd64.img
  runStrategy: "Always"
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-dv
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: datavolumedisk1
          interfaces:
            - masquerade: {}
              name: default
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
        - dataVolume:
#            name: src-dv
            name: dst-dv
          name: datavolumedisk1
      networks:
        - name: default
          pod: {}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 24.04 LTS
- Kernel (e.g. `uname -a`): Linux 6.8.0-40-generic
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by alicefr**
### What this PR does
Before this PR:
The libvirt option MIGRATE_NON_SHARED_INC wasn't set for volume migration

After this PR:
Consider block migration when there is a volume update change with shareable storage.

Fixes #12811

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-handler/vm.go [hunk 1]
```diff
@@ -2667,7 +2671,7 @@ func (d *VirtualMachineController) handleTargetMigrationProxy(vmi *v1.VirtualMac
 	baseDir := fmt.Sprintf(filepath.Join(d.virtLauncherFSRunDirPattern, "kubevirt"), res.Pid())
 	migrationTargetSockets = append(migrationTargetSockets, socketFile)
 
-	isBlockMigration := vmi.Status.MigrationMethod == v1.BlockMigration
+	isBlockMigration := vmi.Status.MigrationMethod == v1.BlockMigration || len(vmi.Status.MigratedVolumes) > 0
```
Comment (fossedihelm) [inline pkg/virt-handler/vm.go:2674]: It will be great to have a function that performs this in a centralized way. 
Like `vmi.IsMigratable()` we can have:
```go
func (v *VirtualMachineInstance) IsBlockMigration() bool {
	return v.Status.MigrationMethod == BlockMigration || len(v.Status.MigratedVolumes) > 0
}
```
and use it, instead of replicate the check.

File: tests/storage/migration.go [hunk 2]
```diff
@@ -296,6 +296,43 @@ var _ = SIGDescribe("[Serial]Volumes update with migration", Serial, func() {
 			waitForMigrationToSucceed(vm.Name, ns)
 		})
 
+		It("should migrate the source volume from a source and destination block RWX DVs", func() {
```
Comment (akalenyu) [inline tests/storage/migration.go:299]: So as you know, these kubevirt e2e tests get exercised on many other storage provisioners outside of this repository.
I wonder if us for example triggering a test run against trident would be equivalent to a dedicated test case for this scenario.

Just a thought ofc
``` 
{
    "storageClassRhel":        "trident-csi-fsx",
    "storageClassWindows":     "trident-csi-fsx",
    "storageRWXFileSystem":    "trident-csi-fsx",
    "storageRWOFileSystem":    "trident-csi-fsx",
    "storageSnapshot":         "trident-csi-fsx"
}
```
Or
```
{
    "storageClassRhel":        "ocs-storagecluster-ceph-rbd-virtualization",
    "storageClassWindows":     "ocs-storagecluster-ceph-rbd-virtualization",
    "storageRWXBlock":         "ocs-storagecluster-ceph-rbd-virtualization",
    "storageRWOFileSystem":    "ocs-storagecluster-ceph-rbd-virtualization",
    "storageRWOBlock":         "ocs-storagecluster-ceph-rbd-virtualization",
    "storageSnapshot":         "ocs-storagecluster-ceph-rbd-virtualization"
}
```

Comment (alicefr) [reply tests/storage/migration.go:299]: @akalenyu not sure I understand the comment and suggestion. I have tested this with ceph and got the same result as described in https://github.com/kubevirt/kubevirt/issues/12811

File: pkg/virt-handler/vm.go (hunk 1 above)
Comment (alicefr) [reply pkg/virt-handler/vm.go:2674]: @fossedihelm I'm not quite sure where the unit test should be. IMO, we are missing some unit tests for the migration parameters for `live-migration-source.go`

File: tests/storage/migration.go (hunk 2 above)
Comment (alicefr) [reply tests/storage/migration.go:299]: The issue was in kubevirt which wasn't setting correctly the storage copy options for the migration

File: pkg/virt-handler/vm.go (hunk 1 above)
Comment (fossedihelm) [reply pkg/virt-handler/vm.go]: Maybe somewhere here? https://github.com/kubevirt/kubevirt/blob/fba31d300a12e7c1973a965dd7f5cccda6e83cb2/pkg/virt-handler/vm_test.go#L2229

Comment (fossedihelm) [reply pkg/virt-handler/vm.go]: Ok, let's close the gap in a followup PR. Thanks

**Review by fossedihelm — APPROVED** [review]

File: tests/storage/migration.go (hunk 2 above)
Comment (akalenyu) [reply tests/storage/migration.go:299]: I am suggesting that we can avoid a specific functional test, and instead rely on the existing tests.
So given one of the config's above (which are real testing targets, btw, just not in kubevirt/kubevirt)
one of the existing tests would have caught this

Comment (alicefr) [reply tests/storage/migration.go:299]: I would generally agree, but in this case the 2 tests exercise 2 different paths (in KubeVirt code) for RWX and RWO code. Hence, I'd like to keep the new test

Comment (akalenyu) [reply tests/storage/migration.go:299]: So we can do that just want to generally gauge if we could follow up by cutting the amount of tests here.
I was thinking that maybe if we used the dv.spec.storage API here more, these tests could exercise different paths when ran against different test suite configs. WDYT? does this make any sense?

**Comment by fossedihelm** [comment]
/hold
Diuscussion with @akalenyu still ongoing

**Comment by akalenyu** [comment]
> /hold Diuscussion with @akalenyu still ongoing

Thanks that's fine though we can merge this and keep that discussion going async
/hold cancel

File: tests/storage/migration.go (hunk 2 above)
Comment (akalenyu) [reply tests/storage/migration.go:299]: ping @alicefr do you think this is worth the effort? I can give it a go

**Comment by vladikr** [comment]
:+1: fwiw, looks good to me.

File: tests/storage/migration.go (hunk 2 above)
Comment (alicefr) [reply tests/storage/migration.go:299]: @akalenyu if we can exercise the different combinations, I'm fine. I have another bug (https://github.com/kubevirt/kubevirt/issues/12823) which also need to test the migration from block to fs. I would have also added a similar functional test for this as well

Comment (alicefr) [reply tests/storage/migration.go:299]: FYI: https://github.com/kubevirt/kubevirt/pull/12851
