### PR TITLE
virtwrap, arm64: not add VMPort on Arm64 platform

### LINKED ISSUE #13436: arm lane: clustered failure
# What happened

Clustered failure detected: [1]

/kind flake
/priority critical-urgent

/wg arch-arm
/assign @zhlhahaha 

/sig compute

[1]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/13252/pull-kubevirt-e2e-arm64/1862481259553361920

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by zhlhahaha**
VMPort is not support by the qemu on Arm64, so skip setting it via libvirt.
```
vmport is not available with this QEMU binary
```
Fixes #13436 

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
cc: @dhiller @iholder101 @xpivarc

File: pkg/virt-launcher/virtwrap/api/defaults.go [hunk 1]
```diff
@@ -77,7 +77,9 @@ func (d *Defaulter) setDefaults_Features(spec *DomainSpec) {
 		spec.Features = &Features{}
 	}
 
-	spec.Features.VMPort = &FeatureState{State: "off"}
+	if spec.Features.VMPort != nil {
+		spec.Features.VMPort = &FeatureState{State: "off"}
+	}
```
Comment (iholder101) [inline pkg/virt-launcher/virtwrap/api/defaults.go:82]: I think we can simply do:
```go
	if !d.isARM64() {
		spec.Features.VMPort = &FeatureState{State: "off"}
	}
```

I find it more readable and less confusing. WDYT?

**Review by iholder101 — COMMENTED** [review]
Thanks very much @zhlhahaha!

File: pkg/virt-launcher/virtwrap/api/defaults.go (hunk 1 above)
Comment (iholder101) [reply pkg/virt-launcher/virtwrap/api/defaults.go:82]: Yeah, makes sense.
My problem is that when reading this code it is unclear on which circumstances `spec.Features.VMPort` would not be nil.

I think it's better to delete this code from here (i.e. not default it to anything) and instead deal with all cases in the same place under `Convert_v1_VirtualMachineInstance_To_api_Domain()`. Does that make sense?

I'm suggesting something like:
```go
		if c.Architecture.isVMPortNeeded() {
			domain.Spec.Features.VMPort = &api.FeatureState{}
		} else {
			spec.Features.VMPort = &FeatureState{State: "off"}
		}
```

Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/api/defaults.go:82]: I'm fine with it. Let's see if @xpivarc has any suggestions; otherwise, I'll modify the code.

Comment (fossedihelm) [reply pkg/virt-launcher/virtwrap/api/defaults.go:82]: We need to add a converter unit test to prevent this

**Comment by vamsikrishna-siddu** [comment]
Hi @zhlhahaha the vm port is also not supported for s390x as well. The vm creation is failing with this error.
```
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: vmport is not available with this QEMU binary","pos":"qemuValidateDomainDefFeatures:142","subcomponent":"libvirt","thread":"30","timestamp":"2024-12-05T13:32:00.405000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"vm-alpine","namespace":"default","pos":"libvirt_helper.go:136","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405200Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vm-alpine","namespace":"default","pos":"server.go:202","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405228Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
```
can you please disable this for s390x as well. I will test the changes for s390x from my side.

**Comment by zhlhahaha** [comment]
> Hi @zhlhahaha the vm port is also not supported for s390x as well. The vm creation is failing with this error.
> 
> ```
> {"component":"virt-launcher","level":"error","msg":"unsupported configuration: vmport is not available with this QEMU binary","pos":"qemuValidateDomainDefFeatures:142","subcomponent":"libvirt","thread":"30","timestamp":"2024-12-05T13:32:00.405000Z"}
> {"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"vm-alpine","namespace":"default","pos":"libvirt_helper.go:136","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405200Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
> {"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vm-alpine","namespace":"default","pos":"server.go:202","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405228Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
> ```
> 
> can you please disable this for s390x as well. I will test the changes for s390x from my side.

updated

**Comment by vamsikrishna-siddu** [comment]
> > Hi @zhlhahaha the vm port is also not supported for s390x as well. The vm creation is failing with this error.
> > ```
> > {"component":"virt-launcher","level":"error","msg":"unsupported configuration: vmport is not available with this QEMU binary","pos":"qemuValidateDomainDefFeatures:142","subcomponent":"libvirt","thread":"30","timestamp":"2024-12-05T13:32:00.405000Z"}
> > {"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"vm-alpine","namespace":"default","pos":"libvirt_helper.go:136","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405200Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
> > {"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vm-alpine","namespace":"default","pos":"server.go:202","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: vmport is not available with this QEMU binary')","timestamp":"2024-12-05T13:32:00.405228Z","uid":"074a74ac-327c-455f-9529-6a6d513569e4"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can you please disable this for s390x as well. I will test the changes for s390x from my side.
> 
> updated

I have built the kubevirt with your changes and created a vm in s390x. Now the vm creation is working. Thank you so much.

**Review by fossedihelm — APPROVED** [review]
Thank you!

**Review by fossedihelm — APPROVED** [review]
Thank you!

File: pkg/virt-launcher/virtwrap/converter/ppc64le.go [hunk 2]
```diff
@@ -81,3 +81,7 @@ func (archConverterPPC64) requiresMPXCPUValidation() bool {
 func (archConverterPPC64) shouldVerboseLogsBeEnabled() bool {
 	return false
 }
+
+func (archConverterPPC64) isVMPortNeeded() bool {
+	return true
+}
```
[the remark this answers is not in the document]
Comment (jschintag) [reply pkg/virt-launcher/virtwrap/converter/ppc64le.go:87]: I would guess not

File: pkg/virt-launcher/virtwrap/converter/archconverter.go [hunk 3]
```diff
@@ -40,6 +40,7 @@ type ArchConverter interface {
 	isUSBNeeded(vmi *v1.VirtualMachineInstance) bool
 	supportCPUHotplug() bool
 	isSMBiosNeeded() bool
+	isVMPortNeeded() bool
```
Comment (jschintag) [inline pkg/virt-launcher/virtwrap/converter/archconverter.go:43]: I would maybe rename this to `hasVMPort`, because we ultimately want to turn it off if yes.

**Review by jschintag — COMMENTED** [review]
Thank you @zhlhahaha, i had a few comments.

File: pkg/virt-launcher/virtwrap/converter/ppc64le.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/converter/ppc64le.go:87]: Can anyone help confirm this?

File: pkg/virt-launcher/virtwrap/converter/archconverter.go (hunk 3 above)
Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/converter/archconverter.go:43]: ok

File: pkg/virt-launcher/virtwrap/converter/ppc64le.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-launcher/virtwrap/converter/ppc64le.go:87]: I think @jschintag is right: https://github.com/utmapp/UTM/issues/277. I tend to think it's x86-specific TBH.
But I'm not 100% sure.

[the remark this answers is not in the document]
Comment (fossedihelm) [reply pkg/virt-launcher/virtwrap/converter/ppc64le.go:87]: Probably yes, I can only see vmport under https://github.com/qemu/qemu/blob/master/hw/i386/vmport.c,
nothing for the other architectures https://github.com/qemu/qemu/blob/master/hw

[the remark this answers is not in the document]
Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/converter/ppc64le.go:87]: Ok, I will disable it on ppc64le.

**Review by fossedihelm — APPROVED** [review]
Thank you!

**Comment by jschintag** [comment]
Thank you @zhlhahaha

/lgtm

**Comment by fossedihelm** [comment]
@iholder101 Can you take a look? Thank you
