### PR TITLE
Live Migration without tunneling

### LINKED ISSUE #1865: Live migrations fail when VMI has cloud-init user data defined
/kind bug

**What happened**:

Migrating a VMI that defines cloud-init userdata fails. The failure appears to be occurring from within libvirt.  

I believe this worked correctly when migrations were first introduced. I think this may be related to some of the libvirt changes that occurred recently. We recently updated the libvirt packages in our virt-launcher container from 4.2.0 to 4.10.0 which could be related. 

**How to reproduce it (as minimally and precisely as possible)**:

using this VMI

```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: vmi-ephemeral
  name: vmi-ephemeral
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
        volumeName: registryvolume
      - disk:
          bus: virtio
        name: cloudinitdisk
        volumeName: cloudinitvolume
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/cirros-container-disk-demo:devel
    name: registryvolume
  - cloudInitNoCloud:
      userData: |
        #!/bin/sh

        echo 'printed from cloud-init userdata'
    name: cloudinitvolume
```

and then migrating with this migration job.
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceMigration
metadata:
  creationTimestamp: null
  name: migration-job
spec:
  vmiName: vmi-ephemeral
status: {}
```

The migration job will fail and report a libvirt error.

### PR DESCRIPTION
**Pull request by vladikr**
**What this PR does / why we need it**:
This PR removes the need for tunneling VM migrations. It proxies all the direct connections between the source and the destination vmi pods. 
Having a direct connection between the source and the destination lets us switch to using Libvirt's virDomainMigrate3 API, which allows specifying a list of disks that are required to be copied during live migration. This will also remove the previous limitation which didn't allow us to migrate VMs with mixed (shared and non-shared) disks.

**Which issue(s) this PR fixes**
Fixes #1865 

**Special notes for your reviewer**:
Just wanted to mention a few adjustments that I had to make.

- Updating `/etc/hosts` file on the destination pod
Libvirt prevents migration between nodes with the same hostname and doesn't allow to migrate to localhost. When trying to initiate a direct migration, libvirt in the destination pods sets the pod name as a migration hostname that must be resolvable by the libvirt in the source pod. As a workaround, this PR appends the destination pod name to the /etc/hosts file to be resolved as localhost.  

 - MigrateDisks list construction
`VIR_MIGRATE_PARAM_MIGRATE_DISKS` accepts a list of disks (list of disk target names, such as /dev/vda, /dev/sdb, ...) that should be copied to the destination during the block live migration.
In order to use this method we need to filter out all the disks that shouldn't be copied, such as shared volumes, etc.. However, we don't store the disk target names anywhere. This PR contracts the disks list but comparing the domxml disk alias with the volume/disk (these are the same now) name (these should match.) 

 - Changes in the migration proxy
In addition to proxying the libvirt connection, the migration proxy will manage additional connections, via migration ports 49152 (direct connection) and 49153 (live block migration). 

**Release note**:
```release-note
Live migration direct connection will be proxied between the source and the destination pods without being tunneled via the libvirt connection.
```

### CODE REVIEW

File: pkg/virt-handler/vm.go [hunk 1]
```diff
@@ -1270,16 +1304,31 @@ func (d *VirtualMachineController) handleMigrationProxy(vmi *v1.VirtualMachineIn
...
 	}
 
+	for srcPort, destPort := range ports {
+		key := string(vmi.UID)
+		if srcPort != 0 {
+			key += fmt.Sprintf("-%d", srcPort)
+		}
+		if d.isMigrationSource(vmi) {
+			targetAddr := fmt.Sprintf("%s:%d", vmi.Status.MigrationState.TargetNodeAddress, destPort)
+			err := d.migrationProxy.StartSourceListener(key, targetAddr)
```
Comment (davidvossel) [inline pkg/virt-handler/vm.go]: I had a thought browsing through the code. It might be something you already have planned.

The migrationProxy interface was originally designed with the assumption that there's a single port for each source and target proxy. The "key" was meant to represent all the connections associate with the VMI. 

Now that each VMI can have multiple src/target proxies opened during a migration, we might want consider enhancing the migrationProxy abstraction so each key can manage multiple ports. This would be helpful in the processVmCleanup() function where it's possible we no longer have any state to provide hints regarding what migration connections were created.

Comment (vladikr) [reply pkg/virt-handler/vm.go]: Oh, absolutely. I need to find a way to improve this. So far I was just focusing on just making everything work.

Thanks!

**Comment by vladikr** [comment]
ci test please

File: pkg/virt-handler/vm.go [hunk 2]
```diff
@@ -58,6 +58,8 @@ import (
 	"kubevirt.io/kubevirt/pkg/watchdog"
 )
 
+var MigrationPortsRange = []int{49152, 49153}
```
Comment (cynepco3hahue) [inline pkg/virt-handler/vm.go]: I think you can get it from `migration-proxy` package.

Comment (davidvossel) [reply pkg/virt-handler/vm.go]: yeah, this one doesn't appear to be used anywhere right now.

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 3]
```diff
@@ -25,25 +25,29 @@ import (
...
 type ProxyManager interface {
-	StartTargetListener(key string, targetUnixFile string) error
-	GetTargetListenerPort(key string) int
+	StartTargetListener(key string, targetUnixFiles []string) error
+	GetTargetListenerPorts(key string) map[int]int
 	StopTargetListener(key string)
 
-	StartSourceListener(key string, targetAddress string) error
-	GetSourceListenerFile(key string) string
+	//StartSourceListener(key string, targetAddress string) error
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: Done

File: pkg/virt-handler/vm.go (hunk 2 above)
Comment (vladikr) [reply pkg/virt-handler/vm.go]: yeah, thanks, forgot about it.

File: pkg/virt-launcher/virtwrap/manager.go [hunk 4]
```diff
@@ -209,34 +209,109 @@ func prepateMigrationFlags(isBlockMigration bool) libvirt.DomainMigrateFlags {
...
+	sharedVols := gatherSharedVolumeForMigration(vmi)
+
+	disks, err := getAllDomainDisks(dom)
+	if err != nil {
+		log.Log.Object(vmi).Reason(err).Error("failed to parse domain XML to get disks.")
+	}
+	// the name of the volume should match the alias
+	for _, disk := range disks {
+		_, isSharedVolumeDisk := sharedVols[disk.Alias.Name]
+		if disk.ReadOnly != nil {
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/manager.go]: so cloud-init/configmap/secret disks will get copied if they aren't marked as ReadOnly?  Maybe we want to always consider migrating those ephemeral files over so we can be certain they are the binary equivalent to what's on the source.

File: tests/migration_test.go [hunk 5]
```diff
@@ -114,10 +114,10 @@ var _ = Describe("Migrations", func() {
 
 	Describe("Starting a VirtualMachineInstance ", func() {
 		Context("with an Alpine read only disk", func() {
-			It("should be successfully migrated multiple times", func() {
+			It("should be successfully migrated multiple times with cloud-init disk", func() {
 
 				vmi := tests.NewRandomVMIWithEphemeralDisk(tests.ContainerDiskFor(tests.ContainerDiskAlpine))
```
Comment (davidvossel) [inline tests/migration_test.go]: maybe we shoudl consider changing this from alpine to cirros since alpine doesn't interpret cloud-init noCloud.

File: tests/migration_test.go [hunk 6]
```diff
@@ -216,6 +224,34 @@ var _ = Describe("Migrations", func() {
...
 			})
+			It("should be successfully with a cloud init", func() {
+				// Start the VirtualMachineInstance with the PVC attached
+				vmi := tests.NewRandomVMIWithPVC(pvName)
+				tests.AddUserData(vmi, "cloud-init", "#!/bin/bash\necho 'hello'\n")
+
+				vmi = runVMIAndExpectLaunch(vmi, 180)
+
+				By("Checking that the VirtualMachineInstance console has expected output")
+				expecter, err := tests.LoggedInAlpineExpecter(vmi)
```
Comment (davidvossel) [inline tests/migration_test.go]: can we change this to cirros since it exercises cloud-init?

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 7]
```diff
@@ -60,123 +68,199 @@ type migrationProxy struct {
...
-	log.Log.Infof("Proxy Target listening on port %d for key %s", proxy.tcpBindPort, key)
-
-	m.targetProxies[key] = proxy
+	m.targetProxies[key] = proxiesList
 	return nil
-
 }
 
-func (m *migrationProxyManager) GetSourceListenerFile(key string) string {
+func (m *migrationProxyManager) GetSourceListenerFile(key string) []string {
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: done

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 8]
```diff
@@ -60,123 +68,199 @@ type migrationProxy struct {
...
+		// 0 means random port is used
+		proxy := NewTargetProxy("0.0.0.0", 0, targetUnixFile)
 
-	err := proxy.StartListening()
-	if err != nil {
-		proxy.StopListening()
-		return err
+		err := proxy.StartListening()
+		if err != nil {
+			proxy.StopListening()
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: Done

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 9]
```diff
@@ -60,123 +68,199 @@ type migrationProxy struct {
...
 
-	curProxy, exists := m.sourceProxies[key]
+	curProxies, exists := m.sourceProxies[key]
 	if exists {
-		curProxy.StopListening()
-		delete(m.sourceProxies, key)
+		for _, curProxy := range curProxies {
+			curProxy.StopListening()
+			os.RemoveAll(curProxy.unixSocketPath)
+			delete(m.sourceProxies, key)
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: ah, yeah :)

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 10]
```diff
@@ -60,123 +68,199 @@ type migrationProxy struct {
...
-		return err
-	}
+		os.RemoveAll(filePath)
+		proxy := NewSourceProxy(filePath, targetFullAddr)
 
-	log.Log.Infof("Proxy Source listening on unix file %s for key %s", filePath, key)
-	m.sourceProxies[key] = proxy
+		err := proxy.StartListening()
+		if err != nil {
+			proxy.StopListening()
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: done

File: pkg/virt-launcher/virtwrap/manager.go [hunk 11]
```diff
@@ -317,6 +419,27 @@ func (l *LibvirtDomainManager) PrepareMigrationTarget(vmi *v1.VirtualMachineInst
...
+	isBlockMigration := (vmi.Status.MigrationMethod == v1.BlockMigration)
+	migrationPortsRange := migrationproxy.GetMigrationPortsList(isBlockMigration)
+	for _, port := range migrationPortsRange {
+		// Prepare the direct migration proxy
+		key := fmt.Sprintf("%s-%d", string(vmi.UID), port)
+		curDirectAddress := fmt.Sprintf("%s:%d", "127.0.0.1", port)
+		unixSocketPath := migrationproxy.SourceUnixFile(l.virtShareDir, key)
+		migrationProxy := migrationproxy.NewSourceProxy(unixSocketPath, curDirectAddress)
+
+		err := migrationProxy.StartListening()
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-launcher/virtwrap/manager.go]: Yea. It's definitely something for future optimization. At the moment I don't see a way to make it listen on unix sockets instead of ports.

File: pkg/virt-handler/migration-proxy/migration-proxy.go [hunk 12]
```diff
@@ -60,123 +68,199 @@ type migrationProxy struct {
...
 
-func (m *migrationProxyManager) GetTargetListenerPort(key string) int {
+func (m *migrationProxyManager) GetTargetListenerPorts(key string) map[int]int {
 	m.managerLock.Lock()
 	defer m.managerLock.Unlock()
 
-	curProxy, exists := m.targetProxies[key]
+	getPortFromSocket := func(id string, path string) int {
+		for _, port := range migrationPortsRange {
+			key := fmt.Sprintf("%s-%d", id, port)
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-handler/migration-proxy/migration-proxy.go]: ok, done.

File: pkg/virt-launcher/virtwrap/manager.go [hunk 13]
```diff
@@ -209,34 +209,109 @@ func prepateMigrationFlags(isBlockMigration bool) libvirt.DomainMigrateFlags {
...
-		// For a tunnelled migration, this is always the uri
-		dstUri := "qemu+tcp://127.0.0.1:22222/system"
+		// Create a tcp server for each direct connection proxy and listen for incoming migration requests on port 22222
+		for _, port := range append([]int{22222}, ports...) {
+			if port == 0 {
+				continue
+			}
+			key := string(vmi.UID)
+			if port != 22222 {
+				key += fmt.Sprintf("-%d", port)
```
[the remark this answers is not in the document]
Comment (vladikr) [reply pkg/virt-launcher/virtwrap/manager.go]: Looking at this again, you're right, it just looks confusing.
This loop opened listeners for migrations ports and the main libvirt connection socket (which doesn't have a port and it's not part of the migration per se). I don't think we should expose all libvirt connection sockets with a port number.

I'll just re-write this part so it'll be less confusing.

File: pkg/virt-launcher/virtwrap/manager.go (hunk 4 above)
Comment (vladikr) [reply pkg/virt-launcher/virtwrap/manager.go]: > so cloud-init/configmap/secret disks will get copied if they aren't marked as ReadOnly?

Yes.

> Maybe we want to always consider migrating those ephemeral files over so we can be certain they are the binary equivalent to what's on the source.

Yes, It'll be better to just always copy it. I was worried that it'll be unexpected for the user. We will allow him to switch to virtio and set the disk to ReadOnly (none of it is a default) and then we will still copy the disks. Maybe we should just block setting these disks to readonly?
If you think that it's better to just copy it regardless, I can make it work here, it's not difficult.

File: tests/migration_test.go (hunk 5 above)
Comment (vladikr) [reply tests/migration_test.go]: Yep, done.

File: tests/migration_test.go (hunk 6 above)
Comment (vladikr) [reply tests/migration_test.go]: That's a bit tricky as we've built the cdi-http-import-server to only expose the alpine image in the target. So, I'll need to change that and everything that uses this pv to login to cirros.

Thing is, that we are only testing here that the disk is present and not if it's used by the guest OS...

**Comment by cynepco3hahue** [comment]
@vladikr I see some migration-related error under the https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/3467//artifact/check-patch.k8s-1.11.0.el7.x86_64/mock_logs/script/stdout_stderr.log

```
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed.","name":"testvmiz5n5ccg2g4whq588qmsdkzgqwbglkh85dd58mktfp8tnx444","namespace":"kubevirt-test-default","pos":"manager.go:331","reason":"virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'drive-mirror': Failed to read data: Unexpected end-of-file before all bytes were read')","timestamp":"2019-02-07T06:15:17.495426Z","uid":"a123bd05-2a9f-11e9-b56b-525500d15501"}
```

**Comment by vladikr** [comment]
> I see some migration-related error

Thanks. It's very odd that this test failed.  It only fails on one job and I can't reproduce it locally.
The problem here is that the destination virt-handler tried to connect to the listener in the dest. pod but failed as the socket file wasn't present:
```
{"component":"virt-handler","level":"error","msg":"unable to create outbound leg of proxy to host /var/run/kubevirt/migrationproxy/a123bd05-2a9f-11e9-b56b-525500d15501-49153-source.sock","pos":"migration-proxy.go:360","reason":"dial unix /var/run/kubevirt/migrationproxy/a123bd05-2a9f-11e9-b56b-525500d15501-49153-source.sock: connect: no such file or directory","timestamp":"2019-02-07T06:15:17.278322Z"}
```
However, the pod shows that the listener was created (and the socket) 28ms prior to that ...:
```
{"component":"virt-handler","level":"info","msg":"Proxy Source listening on unix file /var/run/kubevirt/migrationproxy/a123bd05-2a9f-11e9-b56b-525500d15501-49153-source.sock for key a123bd05-2a9f-11e9-b56b-525500d15501","pos":"migration-proxy.go:260","timestamp":"2019-02-07T06:15:16.987007Z"}
```

File: tests/migration_test.go (hunk 6 above)
Comment (davidvossel) [reply tests/migration_test.go]: ah, don't worry about it then.

File: pkg/virt-launcher/virtwrap/manager.go (hunk 4 above)
Comment (davidvossel) [reply pkg/virt-launcher/virtwrap/manager.go]: > We will allow him to switch to virtio and set the disk to ReadOnly (none of it is a default) and then we will still copy the disks. Maybe we should just block setting these disks to readonly?
If you think that it's better to just copy it regardless, I can make it work here, it's not difficult.

Yeah, if we dynamically create something during the launch flow like the cloud-init/secret/configmap disks, then I think we'll always need to copy those disks from the source to the target. Otherwise we can't guarantee they are binary equivalent. 

The different behavior based on the 'ReadOnly' flag here makes for a difficult to understand user story now that we're considering exceptions though. What are trying to optimize here for? If we're primarily just concerned about not copying ReadOnly ContainerDisks, maybe that should be what we key off of.

Comment (vladikr) [reply pkg/virt-launcher/virtwrap/manager.go]: Yeah, you're right. I've updated it to alway to copy the generated disks.

File: tests/migration_test.go (hunk 6 above)
Comment (vladikr) [reply tests/migration_test.go]: I saw it too late :)
I've updated the cdi-http-import-server to contain both alpine and cirros.
Had a strange problem with the LoggedInCirrosExpecter.
For some weird reason (in the tests) when the vm was started from a pv, it's hostname in the guest was set to `cirros`, and the expected failed as it was looking for a hostname + " login".
But when it was started from an image, everything was fine, the guest hostname was correct.
I couldn't figure it out and just set (in the test) the hostname to "cirros"... :/

**Comment by vladikr** [comment]
migration tests are passing, but looks like the cirros image got stuck (or timed out) on openshift)

**Comment by vladikr** [comment]
ci test please

**Comment by vladikr** [comment]
ci test please

File: pkg/virt-launcher/virtwrap/manager_test.go [hunk 14]
```diff
@@ -248,6 +256,83 @@ var _ = Describe("Manager", func() {
...
+					VolumeSource: v1.VolumeSource{
+						Ephemeral: &v1.EphemeralVolumeSource{
+							PersistentVolumeClaim: &k8sv1.PersistentVolumeClaimVolumeSource{
+								ClaimName: "testclaim",
+							},
+						},
+					},
+				},
+				{
+					Name: "myvolumehost",
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/manager_test.go]: can we get some of the generated volumes (like cloud-init) into this test too

Comment (vladikr) [reply pkg/virt-launcher/virtwrap/manager_test.go]: Yeah. It's there, line 328 -  `addCloudInitDisk(vmi, userData, networkData)`

**Comment by vladikr** [comment]
Ci test please

**Comment by vladikr** [comment]
migration tests are passing

**Comment by fabiand** [comment]
:rocket:
