### PR TITLE
bug-fix: add machine type to `NodeSelector` to prevent breaking changes on unsupported nodes 

### LINKED ISSUE #13664: Live Migration Fails to Select Compatible Target Node Based on Machine Type
**What happened**:
During the live migration of a VM, if the target node does not support the VM's machine type, the migration will fail, even if other nodes support the VM's original machine type.

**What you expected to happen**:
I would expect the live migration to use Kubernetes label selector logic to choose a compatible target node, similar to how KubeVirt handles CPU models.

**How to reproduce it (as minimally and precisely as possible)**:
For example, if a VM originally started with a machine type from before RHEL-9, attempting to migrate it to a node with a RHEL-10 machine type will result in a migration failure.

**Additional context**:
The supported machine types of nodes can be retrieved using the node labeler, which parses the `/var/lib/kubevirt-node-labeller/capabilities.xml` file in virt-handler. In fact, we are already parsing the relevant object here: [virt-handler.go line 311](https://github.com/kubevirt/kubevirt/blob/5ed7457531ef1ffa6e738fecad479056c9f987de/cmd/virt-handler/virt-handler.go#L311). The node labeller can then add labels for the supported machine types to each node. When a migration is triggered, the label selector can be applied to the virt-launcher, similar to the CPU model logic.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by dasionov**
### What this PR does
Before this PR:
Nodes labeled by the node labeller did not include supported machine types. As a result, a Virtual Machine (VM) with a specific machine type could be scheduled on a node that does not support it. This would cause the VM launcher to fail.

After this PR:
* Nodes are now labeled by the node-labeller with all supported machine types available on each node.
* When `virt-laucnher` pods being created during vmi starts or during migration, they will have a label in the `NodeSelector` indicating their specific machine type, which will allow the vms to be scheduled only on supported nodes, preventing breaking changes. 

Fixes #13664

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
bug-fix: add machine type to `NodeSelector` to prevent breaking changes on unsupported nodes 
```

### CODE REVIEW

**Comment by dasionov** [comment]
FYI @vladikr

File: tests/hotplug/affinity.go [hunk 1]
```diff
@@ -205,4 +207,46 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+			vm := libvmi.NewVirtualMachine(vmi, libvmi.WithRunStrategy(v1.RunStrategyAlways))
+			vm.Spec.Template.Spec.Domain.Machine = &v1.Machine{Type: "pc-q35-rhel7.0.0"} // old and not supported machine type
+			_, err := virtClient.VirtualMachine(vm.Namespace).Create(context.Background(), vm, k8smetav1.CreateOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			By("Verifying the pod does not start due to node affinity")
+			Eventually(func() bool {
+				pod, err := libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)
+				Expect(err).ToNot(HaveOccurred())
+				return pod.Status.Phase == k8sv1.PodPending
```
Comment (lyarwood) [inline tests/hotplug/affinity.go:225]: Do you want to assert anything about the pod node affinity here?

File: tests/hotplug/affinity.go [hunk 2]
```diff
@@ -205,4 +207,46 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
 
 	})
+
+	Context("Machine Type Affinity", func() {
+		It("should not start a pod for a VM with an old machine type", func() {
+			By("Creating a VM with an old machine type")
+			vmi := libvmifact.NewAlpineWithTestTooling(libnet.WithMasqueradeNetworking())
+			vmi.Namespace = testsuite.GetTestNamespace(vmi)
+			vm := libvmi.NewVirtualMachine(vmi, libvmi.WithRunStrategy(v1.RunStrategyAlways))
+			vm.Spec.Template.Spec.Domain.Machine = &v1.Machine{Type: "pc-q35-rhel7.0.0"} // old and not supported machine type
```
Comment (lyarwood) [inline tests/hotplug/affinity.go:217]: Maybe assert that this definitely isn't present as a node label anywhere before proceeding with the test?

File: tests/hotplug/affinity.go [hunk 3]
```diff
@@ -205,4 +207,46 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+			_, err := virtClient.VirtualMachine(vm.Namespace).Create(context.Background(), vm, k8smetav1.CreateOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			By("Verifying the pod does not start due to node affinity")
+			Eventually(func() bool {
+				pod, err := libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)
+				Expect(err).ToNot(HaveOccurred())
+				return pod.Status.Phase == k8sv1.PodPending
+			}, 120*time.Second, time.Second).Should(BeTrue())
```
[the remark this answers is not in the document]
Comment (dasionov) [reply tests/hotplug/affinity.go]: done

File: tests/hotplug/affinity.go (hunk 1 above)
Comment (dasionov) [reply tests/hotplug/affinity.go]: added

File: tests/hotplug/affinity.go (hunk 2 above)
Comment (dasionov) [reply tests/hotplug/affinity.go]: thanks, added in before each

**Comment by vladikr** [comment]
> FYI @vladikr

@dasionov The direction here looks very good.
Could you please take a look at the failing test before approving this?

File: pkg/virt-controller/services/template_test.go [hunk 4]
```diff
@@ -1776,27 +1838,6 @@ var _ = Describe("Template", func() {
 					},
 				))
 			})
-
-			It("should not add empty affinity to pod", func() {
```
Comment (iholder101) [inline pkg/virt-controller/services/template_test.go:1780]: If you adopt my earlier comment this test doesn't need to be deleted

File: tests/hotplug/affinity.go [hunk 5]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
 		})
 
 	})
+
+	Context("Machine Type Affinity", func() {
+
+		const unsupportedMachineType = "pc-q35-rhel7.0.0"
```
Comment (iholder101) [inline tests/hotplug/affinity.go:214]: How did you choose this value?
Maybe something that will obviously not be supported is better, i.e. `"pc-q35-test1.2.3"`

File: tests/hotplug/affinity.go [hunk 6]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+
+			var podList *k8sv1.PodList
+			Eventually(func() ([]k8sv1.Pod, error) {
+				podList, err = virtClient.CoreV1().Pods(vmi.Namespace).List(context.Background(), k8smetav1.ListOptions{
+					LabelSelector: fmt.Sprintf("%s=%s", v1.CreatedByLabel, string(vmi.UID)),
+				})
+				Expect(err).NotTo(HaveOccurred())
+				return podList.Items, nil
+			}, 10*time.Second, 1*time.Second).ShouldNot(BeEmpty(), "Pod should eventually be created for the VMI")
+			pod := podList.Items[0]
```
Comment (iholder101) [inline tests/hotplug/affinity.go:244]:
```suggestion
			pod := libvmi.GetPodByVirtualMachineInstance(vmi. vmi.namespace)
```

File: tests/hotplug/affinity.go [hunk 7]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+
+			By("Validating the pod has an unschedulable condition")
+			ExpectPodHasUnschedulableCondition(targetPod)
+
+			libmigration.EnsureMigrationRemainsInPhase(virtClient, migration.Namespace, migration.Name, v1.MigrationPending, 60*time.Second)
+		})
+	})
 })
+
+func ExpectPodAffinityContainsMachineType(pod k8sv1.Pod, machineType string) {
```
Comment (iholder101) [inline tests/hotplug/affinity.go:318]: can you please unexpose?

File: tests/hotplug/affinity.go [hunk 8]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+			if expr.Key == machineTypeKey {
+				found = true
+				break
+			}
+		}
+	}
+	Expect(found).To(BeTrue(), fmt.Sprintf("Pod affinity should include machine type label %s with values 'true' or 'deprecated'", machineTypeKey))
+}
+
+func ExpectPodHasUnschedulableCondition(pod k8sv1.Pod) {
```
Comment (iholder101) [inline tests/hotplug/affinity.go:336]: can you please unexpose?

File: tests/hotplug/affinity.go [hunk 9]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+		})
+
+		It("should fail migration if no node supports the VMI machine type", func() {
+			vmi := libvmifact.NewAlpineWithTestTooling(libnet.WithMasqueradeNetworking())
+			vmi.Namespace = testsuite.GetTestNamespace(vmi)
+
+			_, err := virtClient.VirtualMachineInstance(vmi.Namespace).Create(context.Background(), vmi, k8smetav1.CreateOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			vmi = libwait.WaitUntilVMIReady(vmi, console.LoginToAlpine)
```
Comment (iholder101) [inline tests/hotplug/affinity.go:261]:
```suggestion
			vmi = RunVMIAndExpectLaunch(vmi, 60)
```

File: tests/hotplug/affinity.go [hunk 10]
```diff
@@ -205,4 +208,138 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
...
+			}
+
+			DeferCleanup(func() {
+				By("Restoring the machine type label for all nodes")
+				for _, node := range nodeList.Items {
+					patchPayload := `[{"op": "add", "path": "/metadata/labels/machine-type.node.kubevirt.io~1q35", "value": "true"}]`
+					_, err := virtClient.CoreV1().Nodes().Patch(context.Background(), node.Name, types.JSONPatchType, []byte(patchPayload), k8smetav1.PatchOptions{})
+					Expect(err).ToNot(HaveOccurred())
+				}
+			})
```
Comment (iholder101) [inline tests/hotplug/affinity.go:289]: Please use libinfra.ExpectStoppingNodeLabellerToSucceed to stop/start node labeler to avoid it fighting with these tests

File: go.mod
Comment (iholder101) [inline go.mod:1]: can you explain why the bump is necessary?

File: pkg/virt-handler/node-labeller/testdata/capabilities.xml
Comment (iholder101) [inline pkg/virt-handler/node-labeller/testdata/capabilities.xml:1]: related to a different commit?

**Review by iholder101 — COMMENTED** [review]
Thank you very much @dasionov! Awesome stuff!

TBH, I'm a bit conflicted to whether we need e2e tests here. Perhaps unit tests are enough?

File: pkg/virt-handler/node-labeller/node_labeller.go [hunk 11]
```diff
@@ -243,6 +253,16 @@ func (n *NodeLabeller) prepareLabels(node *v1.Node, cpuModels []string, cpuFeatu
 		newLabels[kubevirtv1.SupportedHostModelMigrationCPU+value] = "true"
 	}
 
+	// Add labels for supported machine types and their deprecation status
+	for _, machine := range n.supportedMachines {
+		labelKey := kubevirtv1.SupportedMachineTypeLabel + machine.Name
+		if machine.Deprecated == "yes" {
+			newLabels[labelKey] = "deprecated"
+		} else {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-handler/node-labeller/node_labeller.go:260]: that's fair and I am open to discussion.
I added those for 2 specific reasons:

1.The fact that currently deprecated machine types still work, and only future upgrade of nodes will probably remove them from the supported list.

2. the idea of having them to provide some ground to identify running vms that we want to alert about using deprecated machine types, before they find out during a pending migration.. (give them a chance to upgrade the machine type, before they need to upgrade kubevirt)

File: pkg/virt-controller/services/template.go [hunk 12]
```diff
@@ -195,6 +196,42 @@ func setNodeAffinityForbiddenFeaturePolicy(vmi *v1.VirtualMachineInstance, pod *
...
+	terms := pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms
+
+	if len(terms) > 0 {
+		terms[0].MatchExpressions = append(terms[0].MatchExpressions, machineTypeMatchExpression)
+	} else {
+		newTerm := k8sv1.NodeSelectorTerm{
+			MatchExpressions: []k8sv1.NodeSelectorRequirement{machineTypeMatchExpression},
+		}
+		pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms = append(terms, newTerm)
+	}
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/template.go:232]: yep you are right, other option would be to use `NodeSelector` directly instead  `NodeAffinity`.
in my implementation i chose `NodeAffinity` to be able to allow deprecated machine to be scheduled.

if we choose to use only active supported machine types, then `NodeSelector` implementation is a bit simpler

File: pkg/virt-controller/watch/migration/migration.go [hunk 13]
```diff
@@ -2094,6 +2098,43 @@ func prepareNodeSelectorForHostCpuModel(node *k8sv1.Node, pod *k8sv1.Pod, source
...
+	} else {
+		newTerm := k8sv1.NodeSelectorTerm{
+			MatchExpressions: []k8sv1.NodeSelectorRequirement{machineTypeMatchExpression},
+		}
+		sourcePod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms = append(terms, newTerm)
+	}
+}
+
+func getEffectiveMachineType(vmi *virtv1.VirtualMachineInstance) string {
+	if vmi.Status.Machine != nil && vmi.Status.Machine.Type != vmi.Spec.Domain.Machine.Type {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go:2132]: works for me

File: pkg/virt-controller/services/template_test.go [hunk 14]
```diff
@@ -1250,6 +1292,7 @@ var _ = Describe("Template", func() {
 							Devices: v1.Devices{
 								DisableHotplug: true,
 							},
+							Machine: &v1.Machine{Type: "test"},
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/template_test.go:1295]: I wish this tip had hit me sooner.. would've saved me so much time and suffering! 😂

File: tests/hotplug/affinity.go (hunk 5 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:214]: yea, i don't mind

File: go.mod
Comment (dasionov) [reply go.mod:1]: your confusion is justified, the libvirtxml package we are using didn't have the `Deprecated` attribute in the struct 
```
type CapsGuestMachine struct {
	Name      string `xml:",chardata"`
	MaxCPUs   int    `xml:"maxCpus,attr,omitempty"`
	Canonical string `xml:"canonical,attr,omitempty"`
}
```
You can see [here](https://gitlab.com/libvirt/libvirt-go-xml-module/-/merge_requests/56) i fixed that, with @Barakmor1 help, and since they have a new tag that we can point to in our go mod, then we decided backport is unnecessary in this case.

File: pkg/virt-controller/watch/migration/migration.go [hunk 15]
```diff
@@ -755,6 +755,10 @@ func (c *Controller) createTargetPod(migration *virtv1.VirtualMachineInstanceMig
 		if err != nil {
 			return err
 		}
+
+		if machineType := getEffectiveMachineType(vmi); machineType != "" {
+			prepareNodeAffinityForMachineType(machineType, templatePod)
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go:760]: TBH I don't see any reason

File: pkg/virt-controller/watch/migration/migration.go [hunk 16]
```diff
@@ -755,6 +755,10 @@ func (c *Controller) createTargetPod(migration *virtv1.VirtualMachineInstanceMig
...
+		}
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go:761]: took me a couple of minutes to understand what are you even talking about.. i didn't even noticed i put that in the host model cpu block.. will be fixed

File: pkg/virt-controller/services/template_test.go (hunk 4 above)
Comment (dasionov) [reply pkg/virt-controller/services/template_test.go:1780]: you are right, will do !

File: tests/hotplug/affinity.go (hunk 6 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:244]: yep i started with that.. note that under the hood this function searches for a `running` pod while mine is stuck on pending since it is Unschedulable.

so i cant use that beautiful lib function as much as i wanted too.

File: tests/hotplug/affinity.go (hunk 7 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:318]: yep, sorry

File: tests/hotplug/affinity.go (hunk 8 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:336]: sure

File: tests/hotplug/affinity.go (hunk 10 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:289]: thanks!

File: pkg/virt-handler/node-labeller/testdata/capabilities.xml
Comment (dasionov) [reply pkg/virt-handler/node-labeller/testdata/capabilities.xml:1]: The testsdata `capabilities.xml` file i added is needed for the `node-labeller` unit tests to not fail when loading capabilities.

File: vendor/libvirt.org/go/libvirtxml/capabilities.go [hunk 17]
```diff
@@ -298,9 +298,10 @@ type CapsHostMemoryBandwidthMonitorFeature struct {
 }
 
 type CapsGuestMachine struct {
-	Name      string `xml:",chardata"`
-	MaxCPUs   int    `xml:"maxCpus,attr,omitempty"`
-	Canonical string `xml:"canonical,attr,omitempty"`
+	Name       string `xml:",chardata"`
+	MaxCPUs    int    `xml:"maxCpus,attr,omitempty"`
+	Deprecated string `xml:"deprecated,attr,omitempty"`
```
Comment (Barakmor1) [inline vendor/libvirt.org/go/libvirtxml/capabilities.go:303]: Great to see that you were able to fix it upstream :)

File: pkg/virt-controller/services/template.go [hunk 18]
```diff
@@ -195,6 +198,42 @@ func setNodeAffinityForbiddenFeaturePolicy(vmi *v1.VirtualMachineInstance, pod *
...
+}
+
+func prepareNodeAffinityForMachineType(machineType string, pod *k8sv1.Pod) {
+	machineTypeLabelKey := v1.SupportedMachineTypeLabel + machineType
+
+	machineTypeMatchExpression := k8sv1.NodeSelectorRequirement{
+		Key:      machineTypeLabelKey,
+		Operator: k8sv1.NodeSelectorOpIn,
+		Values:   []string{"true", "deprecated"},
+	}
```
[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go:213]: What do you mean? That all the map values should be `true`?
Isn't it important for users to distinguish between deprecated and non-deprecated machine types?

[the remark this answers is not in the document]
Comment (Barakmor1) [reply pkg/virt-controller/services/template.go:213]: You're right that users should know when they're using a deprecated machine type, but I think it would be better to handle this with a Prometheus alert or an event/condition, rather than using a label. If we include both `true` and `deprecated` values in the node's label, we would need to switch from label selectors to using Affinity in the launcher. Label selectors are already being used for CPU models and features. Using Affinity would mean adding more rules because they are combined with OR logic, which could make the launcher manifest larger and harder to manage

[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go:213]: But we are already using affinities, don't we?
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go#L654

In addition, can't we use an empty value to match every value? i.e. `"machine-type.node.kubevirt.io/my-machine": ""`

[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go:213]: > but I think it would be better to handle this with a Prometheus alert or an event/condition

FWIW this is not a bad idea IMO, but it serves a different purpose.
I think that for an admin to choose not to use deprecated machine types makes total sense.

**Comment by fossedihelm** [comment]
General (maybe silly) question: what if the nodes are labeled with `"node-labeller.kubevirt.io/skip-node"`, and hence the machine type label is not present? Should we switch from `Required` to `Preferred`? Thanks

File: pkg/virt-controller/services/template.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (Barakmor1) [reply pkg/virt-controller/services/template.go:213]: > But we are already using affinities, don't we?

Yes, we use them to avoid running on nodes with obsolete host models or when users set forbidden features. These situations are rare, so we don't see them often, but we could probably handle this with a label selector as well.

> In addition, can't we use an empty value to match every value? i.e. "machine-type.node.kubevirt.io/my-machine": ""

I'm not sure that this would work but it would be a great if it does.
I’m trying to avoid adding [boilerplate with node affinities](https://github.com/kubevirt/kubevirt/blob/eb8f9006c420ce289324c9e7450aecfe1adce44b/pkg/virt-controller/services/template.go#L216). It makes the manifest of virt-launcher very long and hard to follow. Perhaps we could publish this information through metrics instead.

[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go:213]: As said above metrics serve a different purpose as they can't be used for scheduling.
But I think we agree on the node selector with the empty value approach :+1:

**Comment by iholder101** [comment]
> General (maybe silly) question: what if the nodes are labeled with `"node-labeller.kubevirt.io/skip-node"`, and hence the machine type label is not present? Should we switch from `Required` to `Preferred`? Thanks

TBH I don't think that's concerning. If `"node-labeller.kubevirt.io/skip-node"` is set on the node then it's the responsibility of whoever added it to face consequences. FWIW many things might not work properly when node-labeller is disabled.

File: pkg/virt-controller/services/template.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go]: Spoke with @Barakmor1 offline. we seemed to not understand each other entirely.

> Isn't it important for users to distinguish between deprecated and non-deprecated machine types?

@Barakmor1 claims that the answer to this question is no.
If there is truly no difference to the user between a deprecated and a supported machine type, then it makes sense not to distinguish between them.

[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/template.go]: > As said above metrics serve a different purpose as they can't be used for scheduling. But I think we agree on the node selector with the empty value approach 👍

would you please consider to treat "deprecated" machine types (which still work) as equivalent to active machine types and I would label them with true, instead of "", i don't like the empty string since it's less readable to me.

also looks like other similar features like the host cpu model uses the convention of label with `true` the supported models, i just want to follow along

by doing so deprecated machine types (that still work) will be able to get scheduled normally, and the alert mechanism can be implemented later however we decide condition/metric/script.

WDYT?

[the remark this answers is not in the document]
Comment (iholder101) [reply pkg/virt-controller/services/template.go]: Sounds good :+1:

[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/template.go]: > > Isn't it important for users to distinguish between deprecated and non-deprecated machine types?
> 
> @Barakmor1 claims that the answer to this question is no. If there is truly no difference to the user between a deprecated and a supported machine type, then it makes sense not to distinguish between them.

IMHO users/admins don't care about the machine type, we have mutators that defaults the value for that, so when rendering manifest you don't even have to care about that.. which brings us to the following behavior

 1. user creates a vm with default machine type `q35` for example 
 2. vm gets scheduled no issues since the `q35` will always be supported
 3. admin upgrades the cluster and the vms starts to migrate
 4. node selector logic uses the `vmi.status.machine.type` to take the original machine type for example `pc-q35-something1.2.3`
 5. at this point the admin/user doesn't really care if the machine type is fully active or deprecated and will be removed next upgrade (since deprecated machines still work, only machines that aren't in the capabilities file wont be able to get scheduled) 
 6. if the machine is deprecated, we should probably find a way to alert using metrics or conditions.
 
 this is just my opinion, not sure if @Barakmor1 would completely agree, WDYT?

File: vendor/libvirt.org/go/libvirtxml/capabilities.go (hunk 17 above)
Comment (dasionov) [reply vendor/libvirt.org/go/libvirtxml/capabilities.go:303]: Thanks, it was thanks to you to begin with :pray:

File: tests/hotplug/affinity.go (hunk 9 above)
Comment (dasionov) [reply tests/hotplug/affinity.go]: done

File: pkg/virt-controller/services/template.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (Barakmor1) [reply pkg/virt-controller/services/template.go]: This is where we set the default machine type: https://github.com/kubevirt/kubevirt/blob/a7c2595a54149662e564d89fd377f60b210570a2/pkg/virt-config/virt-config.go#L142

IIUC Using a deprecated machine type doesn't affect the user, it only serves as a warning for machine types that will no longer be supported.

Maybe @andreabolognani can confirm do you know whether this field: https://gitlab.com/libvirt/libvirt-go-xml-module/-/blob/master/capabilities.go?ref_type=heads#L303

has any effect on the domains, or is it just a warning that the machine type won't be supported soon?

File: pkg/virt-controller/watch/migration/migration.go [hunk 19]
```diff
@@ -2094,6 +2098,22 @@ func prepareNodeSelectorForHostCpuModel(node *k8sv1.Node, pod *k8sv1.Pod, source
...
+	machineTypeLabelKey := virtv1.SupportedMachineTypeLabel + machineType
+
+	if sourcePod.Spec.NodeSelector == nil {
+		sourcePod.Spec.NodeSelector = make(map[string]string)
+	} else {
+		for key := range sourcePod.Spec.NodeSelector {
+			if strings.HasPrefix(key, virtv1.SupportedMachineTypeLabel) {
+				delete(sourcePod.Spec.NodeSelector, key)
+			}
+		}
```
Comment (Barakmor1) [inline pkg/virt-controller/watch/migration/migration.go:2111]: Does the target pod include the source pod selector at this point?
Can you explain why we need this?

File: pkg/virt-handler/node-labeller/cpu_plugin.go [hunk 20]
```diff
@@ -176,3 +178,30 @@ func (n *NodeLabeller) getStructureFromXMLFile(path string, structure interface{
...
+	capabilitiesFilePath := filepath.Join(n.volumePath, n.capabilitiesFileName)
+	capabilities := &libvirtxml.Caps{}
+
+	err := n.getStructureFromXMLFile(capabilitiesFilePath, capabilities)
+	if err != nil {
+		return nil, err
+	}
+
+	return capabilities, nil
+}
```
Comment (Barakmor1) [inline pkg/virt-handler/node-labeller/cpu_plugin.go:207]: Don't we already do something similar here:
https://github.com/kubevirt/kubevirt/blob/a7c2595a54149662e564d89fd377f60b210570a2/cmd/virt-handler/virt-handler.go#L304

Do you think we can parse this only once?

File: tests/hotplug/affinity.go [hunk 21]
```diff
@@ -205,4 +209,123 @@ var _ = Describe("[sig-compute]VM Affinity", decorators.SigCompute, decorators.S
 		})
 
 	})
+
+	Context("Machine Type Affinity", func() {
+
+		const unsupportedMachineType = "pc-q35-test1.2.3"
+
+		BeforeEach(func() {
```
Comment (Barakmor1) [inline tests/hotplug/affinity.go:217]: Why do we have these tests under hotplug?

I think we can change the Affinity since we decided to go with node selector also from the title/commits descriptions

**Review by Barakmor1 — COMMENTED** [review]
Thanks you!
Looks good in general, left some comments

File: pkg/virt-controller/watch/migration/migration.go (hunk 19 above)
Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go:2111]: yes, i notices this behavior when i run the e2e tests, i ended up with selector for 2 keys 

the default machine type from the web-hook that was used for the source pod, and in the migration I want to use only the original actual machine type from the status... so i am removing the what ever old one was.

```
machine-type.node.kubevirt.io/q35
machine-type.node.kubevirt.io/pc-q35-smoething1.2.3
```
in this case the q35 should be removed, just for clarity.. it wont allow the pod to be schdule on q35 supported nodes.. but i prefer not to have it if it's not needed

File: tests/hotplug/affinity.go (hunk 21 above)
Comment (dasionov) [reply tests/hotplug/affinity.go:217]: yea you are right

File: pkg/virt-controller/services/template.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (andreabolognani) [reply pkg/virt-controller/services/template.go]: @Barakmor1 using a deprecated machine type will have no impact for the user, but the VM will be marked as "tainted". AFAIK this simply results in messages like the ones below being added to the log.

```
Domain id=1 is tainted: deprecated-config (machine type 'pc-i440fx-6.2')
qemu-system-x86_64: warning: Machine type 'pc-i440fx-6.2' is deprecated: machines more than 3 years old are subject to deletion after 6 years
```

File: pkg/virt-handler/node-labeller/cpu_plugin.go (hunk 20 above)
Comment (dasionov) [reply pkg/virt-handler/node-labeller/cpu_plugin.go:207]: yes we can, on it

Comment (dasionov) [reply pkg/virt-handler/node-labeller/cpu_plugin.go]: done

File: pkg/virt-controller/watch/migration/migration.go [hunk 22]
```diff
@@ -2094,6 +2098,22 @@ func prepareNodeSelectorForHostCpuModel(node *k8sv1.Node, pod *k8sv1.Pod, source
 	return nil
 }
 
+func prepareNodeSelectorForMachineType(machineType string, sourcePod *k8sv1.Pod) {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go]: change it to pod, was left over from the migration logic

**Comment by dasionov** [comment]
[287cd77](https://github.com/kubevirt/kubevirt/commit/287cd770b7603bdde0d386eba7e5dde2a55eb567)
Just a Rebase.

File: pkg/virt-handler/node-labeller/cpu_plugin.go [hunk 23]
```diff
@@ -176,3 +178,13 @@ func (n *NodeLabeller) getStructureFromXMLFile(path string, structure interface{
...
+
+func (n *NodeLabeller) loadSupportedMachines() error {
+	var supportedMachines []libvirtxml.CapsGuestMachine
+	for _, guest := range n.guestCaps {
+		supportedMachines = append(supportedMachines, guest.Arch.Machines...)
+	}
+	n.supportedMachines = supportedMachines
+
+	return nil
+}
```
Comment (Barakmor1) [inline pkg/virt-handler/node-labeller/cpu_plugin.go:190]: nit: there is never error we don't need the return value

File: pkg/virt-handler/node-labeller/cpu_plugin.go [hunk 24]
```diff
@@ -176,3 +178,13 @@ func (n *NodeLabeller) getStructureFromXMLFile(path string, structure interface{
 
 	return xml.Unmarshal(rawFile, structure)
 }
+
+func (n *NodeLabeller) loadSupportedMachines() error {
+	var supportedMachines []libvirtxml.CapsGuestMachine
+	for _, guest := range n.guestCaps {
+		supportedMachines = append(supportedMachines, guest.Arch.Machines...)
```
Comment (Barakmor1) [inline pkg/virt-handler/node-labeller/cpu_plugin.go:185]: I see that there is also `guest.Arch.Domain.Machines...` can you please explain what is used for and why it is not needed?

File: pkg/virt-handler/node-labeller/node_labeller.go [hunk 25]
```diff
@@ -68,22 +69,24 @@ type NodeLabeller struct {
...
 	hypervFeatures          supportedFeatures
 	hostCapabilities        supportedFeatures
+	supportedMachines       []libvirtxml.CapsGuestMachine
 	queue                   workqueue.TypedRateLimitingInterface[string]
 	supportedFeatures       []string
 	cpuModelVendor          string
 	volumePath              string
 	domCapabilitiesFileName string
 	cpuCounter              *libvirtxml.CapsHostCPUCounter
+	guestCaps               []libvirtxml.CapsGuest
```
Comment (Barakmor1) [inline pkg/virt-handler/node-labeller/node_labeller.go:79]: I'm not sure how large these structs are, and they could grow in the future. If possible, I'd prefer not to keep them in memory for the entire handler lifecycle.

File: pkg/virt-handler/node-labeller/node_labeller.go [hunk 26]
```diff
@@ -243,6 +249,12 @@ func (n *NodeLabeller) prepareLabels(node *v1.Node, cpuModels []string, cpuFeatu
 		newLabels[kubevirtv1.SupportedHostModelMigrationCPU+value] = "true"
 	}
 
+	// Add labels for supported machine types and their deprecation status
```
Comment (Barakmor1) [inline pkg/virt-handler/node-labeller/node_labeller.go:252]:
```suggestion
	// Add labels for supported machine types
```

File: pkg/virt-handler/node-labeller/cpu_plugin.go (hunk 24 above)
Comment (dasionov) [reply pkg/virt-handler/node-labeller/cpu_plugin.go:185]: @andreabolognani do you know by any chance what is this `guest.arch.domain.machines`, and should we support those too, or is it the same machines? from the `guest.arch.machines `

Comment (dasionov) [reply pkg/virt-handler/node-labeller/cpu_plugin.go]: great :)

File: tests/node_selector_test.go [hunk 27]
```diff
@@ -0,0 +1,160 @@
...
+
+var _ = Describe("[sig-compute] Node Selector", decorators.SigCompute, decorators.SigComputeMigrations, decorators.RequiresTwoSchedulableNodes, decorators.VMLiveUpdateRolloutStrategy, Serial, func() {
+	var (
+		virtClient kubecli.KubevirtClient
+	)
+	BeforeEach(func() {
+		virtClient = kubevirt.Client()
+		kv := libkubevirt.GetCurrentKv(virtClient)
+		kv.Spec.Configuration.VMRolloutStrategy = pointer.P(v1.VMRolloutStrategyLiveUpdate)
+		testsuite.UpdateKubeVirtConfigValue(kv.Spec.Configuration)
```
Comment (Barakmor1) [inline tests/node_selector_test.go:40]: why do we need this?

File: tests/node_selector_test.go [hunk 28]
```diff
@@ -0,0 +1,160 @@
...
+			vmi, err := virtClient.VirtualMachineInstance(vmi.Namespace).Create(context.Background(), vmi, k8smetav1.CreateOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			var podList *k8sv1.PodList
+			Eventually(func() ([]k8sv1.Pod, error) {
+				podList, err = virtClient.CoreV1().Pods(vmi.Namespace).List(context.Background(), k8smetav1.ListOptions{
+					LabelSelector: fmt.Sprintf("%s=%s", v1.CreatedByLabel, string(vmi.UID)),
+				})
+				Expect(err).NotTo(HaveOccurred())
+				return podList.Items, nil
```
Comment (Barakmor1) [inline tests/node_selector_test.go:72]: `vmiPod, err := libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)`

File: tests/node_selector_test.go [hunk 29]
```diff
@@ -0,0 +1,160 @@
...
+			}, 10*time.Second, 1*time.Second).ShouldNot(BeEmpty(), "Pod should eventually be created for the VMI")
+			pod := podList.Items[0]
+
+			By("Validating the pod's affinity contains the machine type label")
+			expectPodNodeSelectorContainsMachineType(pod, unsupportedMachineType)
```
Comment (Barakmor1) [inline tests/node_selector_test.go:77]: `Expect(virtLauncherPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(unsupportedMachineType))`

File: tests/node_selector_test.go [hunk 30]
```diff
@@ -0,0 +1,160 @@
...
+
+			By("Validating the pod is in Pending state with Unschedulable condition")
+			Expect(pod.Status.Phase).To(Equal(k8sv1.PodPending), "Pod should remain in Pending state due to node affinity issues")
+			expectPodHasUnschedulableConditionForNodeSelector(pod)
```
Comment (Barakmor1) [inline tests/node_selector_test.go:81]: `Eventually(ThisPod(pod), 30*time.Second, 1*time.Second).To(HaveConditionFalse(k8sv1.PodScheduled))`

File: tests/node_selector_test.go [hunk 31]
```diff
@@ -0,0 +1,160 @@
...
+				Expect(err).NotTo(HaveOccurred())
+				return podList.Items, nil
+			}, 10*time.Second, 1*time.Second).ShouldNot(BeEmpty(), "Pod should eventually be created for the VMI")
+			pod := podList.Items[0]
+
+			By("Validating the pod's affinity contains the machine type label")
+			expectPodNodeSelectorContainsMachineType(pod, unsupportedMachineType)
+
+			By("Validating the pod is in Pending state with Unschedulable condition")
+			Expect(pod.Status.Phase).To(Equal(k8sv1.PodPending), "Pod should remain in Pending state due to node affinity issues")
```
Comment (Barakmor1) [inline tests/node_selector_test.go:80]: this doesn't make sure that the pod is stuck in `pending` , but IMO the next validation is enough.

File: tests/node_selector_test.go [hunk 32]
```diff
@@ -0,0 +1,160 @@
...
+			By("Verifying that no nodes have the unsupported machine type label")
+			unsupportedLabel := v1.SupportedMachineTypeLabel + unsupportedMachineType
+			nodes, err := virtClient.CoreV1().Nodes().List(context.Background(), k8smetav1.ListOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			for _, node := range nodes.Items {
+				Expect(node.Labels).ToNot(HaveKeyWithValue(unsupportedLabel, "true"))
+				Expect(node.Labels).ToNot(HaveKeyWithValue(unsupportedLabel, "deprecated"))
+			}
+		})
```
Comment (Barakmor1) [inline tests/node_selector_test.go:56]: I don't think we need this

File: tests/node_selector_test.go [hunk 33]
```diff
@@ -0,0 +1,160 @@
...
+
+			By("Validating the pod's affinity contains the machine type label")
+			expectPodNodeSelectorContainsMachineType(pod, unsupportedMachineType)
+
+			By("Validating the pod is in Pending state with Unschedulable condition")
+			Expect(pod.Status.Phase).To(Equal(k8sv1.PodPending), "Pod should remain in Pending state due to node affinity issues")
+			expectPodHasUnschedulableConditionForNodeSelector(pod)
+		})
+
+		It("should fail migration if no nodes support the VMI's machine type", func() {
```
Comment (Barakmor1) [inline tests/node_selector_test.go:84]: This should be serial

File: tests/node_selector_test.go [hunk 34]
```diff
@@ -0,0 +1,160 @@
...
+				_, err := virtClient.CoreV1().Nodes().Patch(context.Background(), nodeName, types.JSONPatchType, []byte(patchPayload), k8smetav1.PatchOptions{})
+				Expect(err).ToNot(HaveOccurred())
+			}
+
+			DeferCleanup(func() {
+				By("Restoring the machine type label for all nodes")
+				for _, node := range nodeList.Items {
+					libinfra.ExpectResumingNodeLabellerToSucceed(node.Name, virtClient)
+				}
+			})
```
Comment (Barakmor1) [inline tests/node_selector_test.go:113]: Please remove just the label in the vm status

File: tests/node_selector_test.go [hunk 35]
```diff
@@ -0,0 +1,160 @@
...
+			targetPodList, err := virtClient.CoreV1().Pods(vmi.Namespace).List(context.Background(), k8smetav1.ListOptions{
+				LabelSelector: fmt.Sprintf("%s=%s", v1.MigrationJobLabel, string(createdMigration.UID))})
+			Expect(err).ToNot(HaveOccurred())
+			Expect(targetPodList.Items).ToNot(BeEmpty(), "Target pod for migration should be created")
+
+			targetPod := targetPodList.Items[0]
+			Expect(targetPod).ToNot(BeNil(), "Target pod should be found")
+
+			By("Validating the pod's affinity")
+			expectPodNodeSelectorContainsMachineType(targetPod, machineType)
```
Comment (Barakmor1) [inline tests/node_selector_test.go:131]: Expect(virtLauncherPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(machineType))

File: tests/node_selector_test.go [hunk 36]
```diff
@@ -0,0 +1,160 @@
...
+
+			By("Validating the pod has an unschedulable condition")
+			expectPodHasUnschedulableConditionForNodeSelector(targetPod)
```
Comment (Barakmor1) [inline tests/node_selector_test.go:134]: Eventually(ThisPod(pod), 30*time.Second, 1*time.Second).To(HaveConditionFalse(k8sv1.PodScheduled))

**Review by Barakmor1 — COMMENTED** [review]
Hey Generally looks great!
Left some comments regarding the tests, i think we should have some unit tests as well.

File: tests/node_selector_test.go (hunk 28 above)
Comment (dasionov) [reply tests/node_selector_test.go:72]: This one won't work, this helper uses a `running` pod phase filter under the hood, while this test pod is stuck on pending.

Comment (Barakmor1) [reply tests/node_selector_test.go:72]: Are you sure?
I see that we also have function called `GetRunningPodByLabel`

File: tests/node_selector_test.go (hunk 34 above)
Comment (dasionov) [reply tests/node_selector_test.go:113]: not sure i understand

File: tests/node_selector_test.go [hunk 37]
```diff
@@ -0,0 +1,160 @@
...
+				for _, node := range nodeList.Items {
+					libinfra.ExpectResumingNodeLabellerToSucceed(node.Name, virtClient)
+				}
+			})
+
+			By("Initiating a migration")
+			migration := libmigration.New(vmi.Name, vmi.Namespace)
+			createdMigration := libmigration.RunMigration(virtClient, migration)
+
+			libmigration.WaitForMigrationPhase(virtClient, createdMigration.Namespace, createdMigration.Name, v1.MigrationScheduling, 30*time.Second)
```
[the remark this answers is not in the document]
Comment (dasionov) [reply tests/node_selector_test.go]: done

File: tests/node_selector_test.go [hunk 38]
```diff
@@ -0,0 +1,160 @@
...
+			targetPod := targetPodList.Items[0]
+			Expect(targetPod).ToNot(BeNil(), "Target pod should be found")
+
+			By("Validating the pod's affinity")
+			expectPodNodeSelectorContainsMachineType(targetPod, machineType)
+
+			By("Validating the pod has an unschedulable condition")
+			expectPodHasUnschedulableConditionForNodeSelector(targetPod)
+
+			libmigration.EnsureMigrationRemainsInPhase(virtClient, createdMigration.Namespace, createdMigration.Name, v1.MigrationScheduling, 60*time.Second)
```
[the remark this answers is not in the document]
Comment (dasionov) [reply tests/node_selector_test.go]: thanks

File: tests/node_selector_test.go (hunk 27 above)
Comment (dasionov) [reply tests/node_selector_test.go]: removed it

File: tests/node_selector_test.go (hunk 29 above)
Comment (dasionov) [reply tests/node_selector_test.go]: nice one

File: tests/node_selector_test.go (hunk 30 above)
Comment (dasionov) [reply tests/node_selector_test.go]: consistently make more sense to me

File: tests/node_selector_test.go (hunk 32 above)
Comment (dasionov) [reply tests/node_selector_test.go]: true

File: tests/node_selector_test.go (hunk 33 above)
Comment (dasionov) [reply tests/node_selector_test.go]: done

File: tests/node_selector_test.go (hunk 35 above)
Comment (dasionov) [reply tests/node_selector_test.go]: done

File: tests/node_selector_test.go (hunk 28 above)
Comment (dasionov) [reply tests/node_selector_test.go:56]: yea

```
func GetRunningPodByLabel(label, labelType, namespace, node string) (*k8sv1.Pod, error) {
	labelSelector := fmt.Sprintf("%s=%s", labelType, label)
	var fieldSelector string
	if node != "" {
		fieldSelector = fmt.Sprintf("status.phase==%s,spec.nodeName==%s", k8sv1.PodRunning, node)
	} else {
		fieldSelector = fmt.Sprintf("status.phase==%s", k8sv1.PodRunning)
	}
	pod, err := lookupPodBySelector(namespace, labelSelector, fieldSelector)
	if err != nil {
		return nil, fmt.Errorf("failed to find pod with the label %s", label)
	}
	return pod, nil
}
```

that `fieldSelector` is using `k8sv1.PodRunning` so it wont find my pod

File: tests/node_selector_test.go (hunk 36 above)
Comment (dasionov) [reply tests/node_selector_test.go]: i will use consistently to make sure the condition `PodScheduled` stays false

File: tests/node_selector_test.go [hunk 39]
```diff
@@ -0,0 +1,116 @@
...
+			By("Fetching the target pod for the migration")
+			targetPodList, err := virtClient.CoreV1().Pods(vmi.Namespace).List(context.Background(), k8smetav1.ListOptions{
+				LabelSelector: fmt.Sprintf("%s=%s", v1.MigrationJobLabel, string(createdMigration.UID))})
+			Expect(err).ToNot(HaveOccurred())
+			Expect(targetPodList.Items).ToNot(BeEmpty(), "Target pod for migration should be created")
+
+			targetPod := targetPodList.Items[0]
+			Expect(targetPod).ToNot(BeNil(), "Target pod should be found")
+
+			Expect(targetPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(v1.SupportedMachineTypeLabel + unsupportedMachineType)))
```
Comment (Barakmor1) [inline tests/node_selector_test.go:110]: `pod, err := virtClient.CoreV1().Pods(vmi.Namespace).Get(context.Background(), vmi.Status.MigrationState.TargetPod, metav1.GetOptions{})`

File: tests/node_selector_test.go (hunk 28 above)
Comment (Barakmor1) [reply tests/node_selector_test.go:56]: I was speaking about `GetPodByVirtualMachineInstance` and not `GetRunningPodByLabel`

File: tests/node_selector_test.go (hunk 36 above)
Comment (Barakmor1) [reply tests/node_selector_test.go]: I think we should avoid using "consistently" whenever possible, as it increases the testing time, especially during serial tests.

File: tests/node_selector_test.go (hunk 39 above)
Comment (dasionov) [reply tests/node_selector_test.go:110]: good one :rocket:

File: tests/node_selector_test.go (hunk 30 above)
Comment (Barakmor1) [reply tests/node_selector_test.go]: Why?

Comment (dasionov) [reply tests/node_selector_test.go]:
```
Eventually(ThisPod(&virtLauncherPod), 30*time.Second, 5*time.Second).Should(MatchFields(IgnoreExtras, Fields{
	"Status": Equal(k8sv1.ConditionFalse),
	"Reason": Equal(k8sv1.PodReasonUnschedulable),
}))
```
i like this one

File: tests/node_selector_test.go [hunk 40]
```diff
@@ -0,0 +1,111 @@
...
+				podList, err = virtClient.CoreV1().Pods(vmi.Namespace).List(context.Background(), k8smetav1.ListOptions{
+					LabelSelector: fmt.Sprintf("%s=%s", v1.CreatedByLabel, string(vmi.UID)),
+				})
+				Expect(err).NotTo(HaveOccurred())
+				return podList.Items, nil
+			}, 10*time.Second, 1*time.Second).ShouldNot(BeEmpty(), "Pod should eventually be created for the VMI")
+			virtLauncherPod := podList.Items[0]
+
+			Expect(virtLauncherPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(v1.SupportedMachineTypeLabel + unsupportedMachineType)))
+			Eventually(ThisPod(&virtLauncherPod), 30*time.Second, 5*time.Second).Should(HaveConditionFalse(k8sv1.PodScheduled))
```
Comment (Barakmor1) [inline tests/node_selector_test.go:61]: I was think about verifying the reason for the condition to make sure we hit this because of label selector,
i saw that in other tests we use something like:
```
				By("Waiting for the VirtualMachineInstance to be unschedulable")
				Eventually(func() string {
					curVMI, err := kubevirt.Client().VirtualMachineInstance(vmi.Namespace).Get(context.Background(), vmi.Name, metav1.GetOptions{})
					Expect(err).ToNot(HaveOccurred(), "Should get vmi")
					scheduledCond := controller.NewVirtualMachineInstanceConditionManager().
						GetCondition(curVMI, v1.VirtualMachineInstanceConditionType(k8sv1.PodScheduled))
					if scheduledCond != nil {
						return scheduledCond.Reason
					}
					return ""
				}, 60*time.Second, 1*time.Second).Should(Equal(k8sv1.PodReasonUnschedulable), "VMI should be unchedulable")
```

File: tests/node_selector_test.go [hunk 41]
```diff
@@ -0,0 +1,111 @@
...
+			Eventually(ThisMigration(migration), 30*time.Second, 1*time.Second).Should(BeInPhase(v1.MigrationScheduling))
+
+			vmi, err = virtClient.VirtualMachineInstance(testsuite.GetTestNamespace(nil)).Get(context.Background(), vmi.Name, k8smetav1.GetOptions{})
+			Expect(err).NotTo(HaveOccurred())
+
+			targetPod, err := virtClient.CoreV1().Pods(vmi.Namespace).Get(context.Background(), vmi.Status.MigrationState.TargetPod, k8smetav1.GetOptions{})
+			Expect(targetPod).To(Exist())
+			Expect(targetPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(v1.SupportedMachineTypeLabel + unsupportedMachineType)))
+			Eventually(ThisPod(targetPod), 30*time.Second, 5*time.Second).Should(HaveConditionFalse(k8sv1.PodScheduled))
+			Consistently(ThisMigration(migration), 60*time.Second, 5*time.Second).Should(BeInPhase(v1.MigrationScheduling))
```
Comment (Barakmor1) [inline tests/node_selector_test.go:108]: in here as well not sure if we should check both the migration and the target both

Comment (dasionov) [reply tests/node_selector_test.go:108]: i will remove the target pod check this test is more migration focused

File: tests/node_selector_test.go (hunk 28 above)
Comment (dasionov) [reply tests/node_selector_test.go:56]: both expect running phase pods

File: tests/node_selector_test.go (hunk 41 above)
Comment (Barakmor1) [reply tests/node_selector_test.go:108]: Do you think we can change this `Consistently` to `Eventually` as well?

File: tests/node_selector_test.go (hunk 28 above)
Comment (Barakmor1) [reply tests/node_selector_test.go:57]: Sounds like a bug to me but i guess it is out of the scope of this PR

File: tests/node_selector_test.go (hunk 41 above)
Comment (dasionov) [reply tests/node_selector_test.go]: i can remove the consistently and restore the target pod assertion, should be faster if that is the concern

Comment (Barakmor1) [reply tests/node_selector_test.go]: I like this idea

**Comment by Barakmor1** [comment]
Please consider adding unit tests

File: tests/libpod/query.go [hunk 42]
```diff
@@ -56,6 +56,14 @@ func GetPodByVirtualMachineInstance(vmi *v1.VirtualMachineInstance, namespace st
 	return pod, nil
 }
 
+func GetTargetPodForMigration(migration *v1.VirtualMachineInstanceMigration) (*k8sv1.Pod, error) {
+	pod, err := lookupPodBySelector(migration.Namespace, migrationLabelSelector(migration), "")
+	if err != nil {
+		return nil, fmt.Errorf("failed to find pod for migration %s (%s)", migration.Name, migration.UID)
+	}
+	return pod, nil
+}
```
Comment (Barakmor1) [inline tests/libpod/query.go:65]: How about just using something like:
```
pod, err := lookupPodBySelector(migration.Namespace, migrationLabelSelector(migration), "")
```

instead of having a new public function, i don't think we need this boilerplate

File: tests/libpod/query.go [hunk 43]
```diff
@@ -79,6 +87,10 @@ func vmiLabelSelector(vmi *v1.VirtualMachineInstance) string {
 	return fmt.Sprintf("%s=%s", v1.CreatedByLabel, string(vmi.GetUID()))
 }
 
+func migrationLabelSelector(migration *v1.VirtualMachineInstanceMigration) string {
+	return fmt.Sprintf("%s=%s", v1.MigrationJobLabel, migration.UID)
+}
+
```
Comment (Barakmor1) [inline tests/libpod/query.go:93]: nit: use a local var instead of a function

File: tests/migration/migration.go [hunk 44]
```diff
@@ -2402,6 +2403,58 @@ var _ = SIGMigrationDescribe("VM Live Migration", decorators.RequiresTwoSchedula
...
+				By("Patching all nodes to remove the supported machine type label")
+				for _, node := range nodeList.Items {
+					nodeName := node.Name
+					libinfra.ExpectStoppingNodeLabellerToSucceed(nodeName, virtClient)
+
+					// we remove the vmi specific machine type from all the labels on all nodes to render it unsupported for scheduling
+					labelKey := strings.Replace(v1.SupportedMachineTypeLabel+machineType, "/", "~1", 1)
+					patchPayload := fmt.Sprintf(`[{"op": "remove", "path": "/metadata/labels/%s"}]`, labelKey)
+					_, err := virtClient.CoreV1().Nodes().Patch(context.Background(), nodeName, types.JSONPatchType, []byte(patchPayload), metav1.PatchOptions{})
+					Expect(err).ToNot(HaveOccurred())
```
Comment (Barakmor1) [inline tests/migration/migration.go:2431]: please use `libnode.RemoveLabelFromNode`

File: tests/migration/migration.go [hunk 45]
```diff
@@ -2402,6 +2403,58 @@ var _ = SIGMigrationDescribe("VM Live Migration", decorators.RequiresTwoSchedula
...
+				migration := libmigration.New(vmi.Name, vmi.Namespace)
+				createdMigration := libmigration.RunMigration(virtClient, migration)
+
+				Eventually(ThisMigration(createdMigration), 30*time.Second, 1*time.Second).Should(BeInPhase(v1.MigrationScheduling))
+
+				targetPod, err := libpod.GetTargetPodForMigration(createdMigration)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(targetPod.Spec.NodeSelector).To(HaveKey(v1.SupportedMachineTypeLabel + machineType))
+
+				scheduledCond := controller.NewPodConditionManager().GetCondition(targetPod, k8sv1.PodScheduled)
```
Comment (Barakmor1) [inline tests/migration/migration.go:2451]: I'm a bit worried this might be flaky. Shouldn't we use an Eventually block to ensure we give the controller enough time to set this condition?

File: tests/vmi_lifecycle_test.go [hunk 46]
```diff
@@ -480,6 +480,43 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
+					Expect(virtLauncherPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(v1.SupportedMachineTypeLabel + unsupportedMachineType)))
+
+					var scheduledCond *v1.VirtualMachineInstanceCondition
+					Eventually(func() *v1.VirtualMachineInstanceCondition {
+						curVMI, err := kubevirt.Client().VirtualMachineInstance(vmi.Namespace).Get(context.Background(), vmi.Name, metav1.GetOptions{})
+						Expect(err).ToNot(HaveOccurred(), "Should get vmi")
+						scheduledCond = controller.NewVirtualMachineInstanceConditionManager().
+							GetCondition(curVMI, v1.VirtualMachineInstanceConditionType(k8sv1.PodScheduled))
+						return scheduledCond
+					}, 10*time.Second, 1*time.Second).ShouldNot(BeNil(), "The PodScheduled condition should eventually appear")
```
Comment (Barakmor1) [inline tests/vmi_lifecycle_test.go:513]: With the condition here you did use `Eventually`

File: tests/vmi_lifecycle_test.go [hunk 47]
```diff
@@ -480,6 +480,43 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
+						virtLauncherPod, err = libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)
+						return err
+					}, 10*time.Second, 1*time.Second).Should(Succeed(), "Pod should eventually be retrievable for the VMI")
+
+					Expect(virtLauncherPod.Spec.NodeSelector).To(HaveKey(ContainSubstring(v1.SupportedMachineTypeLabel + unsupportedMachineType)))
+
+					var scheduledCond *v1.VirtualMachineInstanceCondition
+					Eventually(func() *v1.VirtualMachineInstanceCondition {
+						curVMI, err := kubevirt.Client().VirtualMachineInstance(vmi.Namespace).Get(context.Background(), vmi.Name, metav1.GetOptions{})
+						Expect(err).ToNot(HaveOccurred(), "Should get vmi")
```
Comment (Barakmor1) [inline tests/vmi_lifecycle_test.go:509]: nit: 
`Expect(err).ToNot(HaveOccurred())`

File: tests/vmi_lifecycle_test.go (hunk 46 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go]: hmm, I was convinced that by the time I query the condition it would already be exist for sure, I don't know why tho..

File: tests/vmi_lifecycle_test.go (hunk 47 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go]: fixed

File: tests/migration/migration.go (hunk 45 above)
Comment (dasionov) [reply tests/migration/migration.go]: added eventually to init the condition

File: tests/migration/migration.go (hunk 44 above)
Comment (dasionov) [reply tests/migration/migration.go]: done

File: tests/migration/migration.go [hunk 48]
```diff
@@ -2402,6 +2403,61 @@ var _ = SIGMigrationDescribe("VM Live Migration", decorators.RequiresTwoSchedula
...
+				Expect(err).ToNot(HaveOccurred())
+				Expect(nodeList.Items).ToNot(BeEmpty())
+
+				By("Patching all nodes to remove the supported machine type label")
+				for _, node := range nodeList.Items {
+					nodeName := node.Name
+					libinfra.ExpectStoppingNodeLabellerToSucceed(nodeName, virtClient)
+
+					// we remove the vmi specific machine type from all the labels on all nodes to render it unsupported for scheduling
+					labelKey := strings.Replace(v1.SupportedMachineTypeLabel+machineType, "/", "~1", 1)
```
Comment (Barakmor1) [inline tests/migration/migration.go:2428]: I don't think we need this

File: tests/vmi_lifecycle_test.go [hunk 49]
```diff
@@ -480,6 +480,43 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
+					vmi.Spec.Domain.Machine = &v1.Machine{Type: unsupportedMachineType}
+
+					vmi, err := virtClient.VirtualMachineInstance(vmi.Namespace).Create(context.Background(), vmi, metav1.CreateOptions{})
+					Expect(err).ToNot(HaveOccurred())
+
+					var virtLauncherPod *k8sv1.Pod
+					Eventually(func() error {
+						virtLauncherPod, err = libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)
+						return err
+					}, 10*time.Second, 1*time.Second).Should(Succeed(), "Pod should eventually be retrievable for the VMI")
```
Comment (Barakmor1) [inline tests/vmi_lifecycle_test.go:502]: nit:

```suggestion
Eventually(matcher.ThisVMI(vmi), 30*time.Second,time.Second).Should(BeInPhase(v1.Scheduling)
virtLauncherPod, err = libpod.GetPodByVirtualMachineInstance(vmi, vmi.Namespace)
Expect(err).ToNot(HaveOccurred())
```

**Review by Barakmor1 — COMMENTED** [review]
/lgtm

File: tests/vmi_lifecycle_test.go (hunk 49 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go]: done

File: tests/migration/migration.go (hunk 48 above)
Comment (dasionov) [reply tests/migration/migration.go]: got rid of it

**Review by Barakmor1 — APPROVED** [review]

File: pkg/virt-controller/watch/migration/migration.go [hunk 50]
```diff
@@ -2094,6 +2098,22 @@ func prepareNodeSelectorForHostCpuModel(node *k8sv1.Node, pod *k8sv1.Pod, source
 	return nil
 }
 
+func prepareNodeSelectorForMachineType(machineType string, pod *k8sv1.Pod) {
```
Comment (jean-edouard) [inline pkg/virt-controller/watch/migration/migration.go:2101]: Sorry if this was previously discussed, but I'm wondering why we need specific migration code.
Shouldn't the main renderer just add the selector to virt-launcher always, regardless if it's a VMI start or a migration target?

Comment (Barakmor1) [reply pkg/virt-controller/watch/migration/migration.go:2101]: IIUC from my conversation with @dasionov, during VMI creation, the machine type is set to a default short name (e.g., q35) unless the user specifies it manually. Once the VMI starts running, the VMI status is updated with the full machine type name. This full name is what we should refer to in the label selector when migrating VMIs. The nodes contain both the short and full names for all supported machine types.

@dasionov can you confirm?

Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go:2101]: > @dasionov can you confirm?

Yes, you are correct, in addition to that from what we see in the code, the migration controller has a separate logic to create the target pod, so we had to adjust the node selector in both places.

Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go]: after taking a deeper look into the code, i believe i can make it so the logic would live only in the `renderLauncherManifest` to apply for both new vms, and existing one during migrations

Comment (dasionov) [reply pkg/virt-controller/watch/migration/migration.go]: @jean-edouard PTAL :pray:

File: tests/vmi_lifecycle_test.go [hunk 51]
```diff
@@ -480,6 +480,41 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
...
 			})
+
+			Context("for Machine Type", func() {
+
+				const unsupportedMachineType = "pc-q35-test1.2.3"
+				const expectedNodeSelectorErrorSubstr = "node(s) didn't match Pod's node affinity/selector."
+
+				It("should prevent scheduling of a pod for a VMI with an unsupported machine type", func() {
+					virtClient := kubevirt.Client()
+					vmi := libvmifact.NewAlpineWithTestTooling(libnet.WithMasqueradeNetworking())
```
Comment (iholder101) [inline tests/vmi_lifecycle_test.go:491]: Use guestless VMI?

File: tests/vmi_lifecycle_test.go [hunk 52]
```diff
@@ -480,6 +480,41 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
 					}
 				}
 			})
+
+			Context("for Machine Type", func() {
+
+				const unsupportedMachineType = "pc-q35-test1.2.3"
+				const expectedNodeSelectorErrorSubstr = "node(s) didn't match Pod's node affinity/selector."
```
Comment (iholder101) [inline tests/vmi_lifecycle_test.go:487]: nit: I would vote for inlining this one

File: tests/vmi_lifecycle_test.go [hunk 53]
```diff
@@ -480,6 +480,41 @@ var _ = Describe("[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:compon
 					}
 				}
 			})
+
+			Context("for Machine Type", func() {
```
Comment (iholder101) [inline tests/vmi_lifecycle_test.go:484]: I wonder if we should also add a positive test here. i.e. create a vmi with `vmi.Spec.Domain.Machine.Type = "q35"` (the unexpanded version) and ensure it gets scheduled (don't even have to wait for it to run). If we do this we might need to add a decorator for amd64 architecture. WDYT?

File: pkg/virt-controller/services/nodeselectorrenderer.go [hunk 54]
```diff
@@ -57,6 +58,12 @@ func (nsr *NodeSelectorRenderer) Render() map[string]string {
 	if nsr.cpuModelLabel != "" && nsr.cpuModelLabel != cpuModelLabel(v1.CPUModeHostModel) && nsr.cpuModelLabel != cpuModelLabel(v1.CPUModeHostPassthrough) {
 		nsr.enableSelectorLabel(nsr.cpuModelLabel)
 	}
+
+	if nsr.machineType != "" {
+		nsr.removeMachineTypeLabelFromNodeSelector() // remove old label
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/nodeselectorrenderer.go:63]: Good Catch!
when i had the migration specific code i was appending the machine type from the status to the existing node selectors and i wanted to remove the default one that gets picked from the spec. but in this current implantation it's redundant.

File: pkg/virt-controller/services/template_test.go [hunk 55]
```diff
@@ -1139,6 +1139,28 @@ var _ = Describe("Template", func() {
 				}
 			})
 
+			It("should add node selector for machine type to template", func() {
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/template_test.go:1142]: sure

File: tests/vmi_lifecycle_test.go (hunk 53 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go:484]: i think it is implicitly covered in the migration test i added. 

the flow of the test is a vmi being created with no machine type provided which makes the mutator give it the default `q35`, then we are waiting for it to be ready. 

so we should be good to go

File: tests/vmi_lifecycle_test.go (hunk 52 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go]: done

File: tests/vmi_lifecycle_test.go (hunk 51 above)
Comment (dasionov) [reply tests/vmi_lifecycle_test.go]: can i assume that if i don't need to login into the guest i should always try to use guestless?

File: tests/migration/migration.go [hunk 56]
```diff
@@ -2402,6 +2403,60 @@ var _ = SIGMigrationDescribe("VM Live Migration", decorators.RequiresTwoSchedula
 			})
 
 		})
+
+		Context("with unsupported machine type", Serial, func() {
+
+			It("should prevent migration scheduling", func() {
+				vmi := libvmifact.NewAlpineWithTestTooling(libnet.WithMasqueradeNetworking())
```
[the remark this answers is not in the document]
Comment (dasionov) [reply tests/migration/migration.go]: yep

File: tests/vmi_lifecycle_test.go (hunk 51 above)
Comment (iholder101) [reply tests/vmi_lifecycle_test.go]: > can i assume that if i don't need to login into the guest i should always try to use guestless?

Yes, if you don't need to interact with the guest in any way (execute a command through guest-agent, run stress, etc) and just check Kubevirt's infra (a VM object is being created, a pod is being scheduled, a condition is being added, etc) then guestless is the way to go  :+1:

File: pkg/virt-controller/services/nodeselectorrenderer.go [hunk 57]
```diff
@@ -121,6 +135,13 @@ func WithModelAndFeatureLabels(modelLabel string, cpuFeatureLabels ...string) No
 	}
 }
 
+func WithMachineTypeLabel(machineType string) NodeSelectorRendererOption {
```
Comment (iholder101) [inline pkg/virt-controller/services/nodeselectorrenderer.go:138]: nit: do you mind renaming to `WithMachineType()`?

File: pkg/virt-controller/services/template.go [hunk 58]
```diff
@@ -688,6 +688,17 @@ func (t *templateService) newNodeSelectorRenderer(vmi *v1.VirtualMachineInstance
...
+	var machineType string
+	if vmi.Status.Machine != nil && vmi.Status.Machine.Type != "" {
+		machineType = vmi.Status.Machine.Type
+	} else if vmi.Spec.Domain.Machine != nil && vmi.Spec.Domain.Machine.Type != "" {
+		machineType = vmi.Spec.Domain.Machine.Type
+	}
+
+	if machineType != "" {
+		opts = append(opts, WithMachineTypeLabel(machineType))
+	}
```
Comment (iholder101) [inline pkg/virt-controller/services/template.go:700]: nit: Could it ever happen that we will not set a machine type selector, since it's always being populated by creation webhooks? I wonder if we should add a warning log here

File: pkg/virt-controller/services/nodeselectorrenderer.go [hunk 59]
```diff
@@ -121,6 +135,13 @@ func WithModelAndFeatureLabels(modelLabel string, cpuFeatureLabels ...string) No
...
+	return func(renderer *NodeSelectorRenderer) {
+		machineTypeLabelKey := v1.SupportedMachineTypeLabel + machineType
+		renderer.machineType = machineTypeLabelKey
```
Comment (iholder101) [inline pkg/virt-controller/services/nodeselectorrenderer.go:141]: nit: since `renderer.machineType` represents the full label, do you mind renaming to `renderer.machineTypeLabel`?

**Review by iholder101 — COMMENTED** [review]
Awesome stuff!
Left some very minor comments, mostly nits and one unused function that's probably a left-over

File: tests/libpod/query.go (hunk 43 above)
Comment (dasionov) [reply tests/libpod/query.go]: sorry missed that one, done.

File: pkg/virt-controller/services/nodeselectorrenderer.go [hunk 60]
```diff
@@ -85,6 +91,14 @@ func (nsr *NodeSelectorRenderer) isManualTSCFrequencyRequired() bool {
 	return nsr.tscFrequency != nil
 }
 
+func (nsr *NodeSelectorRenderer) removeMachineTypeLabelFromNodeSelector() {
+	for key := range nsr.podNodeSelectors {
+		if strings.HasPrefix(key, v1.SupportedMachineTypeLabel) {
+			delete(nsr.podNodeSelectors, key)
+		}
+	}
+}
```
[the remark this answers is not in the document]
Comment (dasionov) [reply pkg/virt-controller/services/nodeselectorrenderer.go]: A leftover, removed.

File: pkg/virt-controller/services/nodeselectorrenderer.go (hunk 57 above)
Comment (dasionov) [reply pkg/virt-controller/services/nodeselectorrenderer.go]: sure

File: pkg/virt-controller/services/nodeselectorrenderer.go (hunk 59 above)
Comment (dasionov) [reply pkg/virt-controller/services/nodeselectorrenderer.go]: done

File: pkg/virt-controller/services/template.go (hunk 58 above)
Comment (dasionov) [reply pkg/virt-controller/services/template.go]: I want to think that I can rely on the mutation web-hook to always populate this field, if I cant rely on it 100% then I shouldn't be using it in the first place. 
won't you agree?

Comment (iholder101) [reply pkg/virt-controller/services/template.go]: Yeah, you can definitely rely on it to work. My concern is more about the webhook logic changing in the future, then we'd have an indication here that something is wrong. It will also make the code itself more understandable, if someone would wonder about when a machine type is expected to not be populated.

But this is just a nit :) feel free to ignore.

**Comment by dasionov** [comment]
> Thank you @dasionov! This PR looks really great!
> 
> Left some comments below

PTAL :pray:

**Comment by iholder101** [comment]
> > Thank you @dasionov! This PR looks really great!
> > Left some comments below
> 
> PTAL 🙏

Sorry for the delay and thanks a lot for your work!
/approve

FYI @jean-edouard @vladikr @Barakmor1. Let us know if there are more concerns before this goes in.
