### PR TITLE
pod-eviction-admitter, webhooks: handle eviction of volume hotplug pod

### LINKED ISSUE #12637: PodDisruptionBudget for hotlpug pod
**What happened**:
The disk hotplug pod is being evicted despite the VM being configured with `evictionStrategy: External`.

**What you expected to happen**:
A PodDisruptionBudget is also created for the disk hotplug pod and blocks the pod eviction.

**How to reproduce it (as minimally and precisely as possible)**:
- create VM with `evictionStrategy: External`
- attach disk to the VM via virtctl
- evict pod using https://github.com/rajatjindal/kubectl-evict-pod

### PR DESCRIPTION
**Pull request by Acedus**
#### Before this PR:
A recent transition from PDBs to using an admission webhook to intercept the eviction API[1] has made it possible to block evictions of virt-launcher Pods when the associated VMI is capable of live migration.

[1] https://github.com/kubevirt/kubevirt/pull/12214

#### After this PR:
Building on that foundation, this PR extends the same protection to hotplug pods owned by the virt-launcher, ensuring they are not prematurely terminated during an ongoing live migration. This prevents potential inconsistencies or failures caused by the hotplug pod shutting down before the migration completes.

### References

- Partially addresses:  https://issues.redhat.com/browse/CNV-63616
- Fixes #12637 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
Previously, it was assumed that any lingering host-level references to a volume, such as active mounts or open file descriptors, would naturally cause a CSI driver to fail the `NodeUnstageVolume` call with an `EBUSY` error or otherwise. This assumption holds true for _some_ drivers that perform safety checks before tearing down a volume. However, others, such as [Trident](https://github.com/NetApp/trident), do not enforce such protections. This behavior is technically compliant with the CSI specification, which does not mandate such checks. Moreover, Trident relies on low-level kernel mechanisms (e.g., direct sysfs device deletion) for some of its flows that operate independently of userland concepts like mounts or open file handles and provide no error feedback when a device is still in use[1]. As a result, volumes can be forcibly removed from the system even when they are not truly safe to detach, ergo the need for this PR.

Other operations that may take down the hotplug pod include:
- Hotplug volume addition/removal - Handled[2].
- Force majeure / accidental deletion - Irrelevant as that would be the user responsibility.

[1] https://github.com/NetApp/trident/blob/79510e1b18b3f29bda0050ce8173ebba97e8856b/utils/devices/devices.go#L709
[2] https://github.com/kubevirt/kubevirt/pull/10275

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
bugfix: volume hotplug pod is no longer evicted when associated VM can live migrate.
```

### CODE REVIEW

**Comment by Acedus** [comment]
/cc @akalenyu @xpivarc 

fyi: @awels

**Review by joao-krauchenco-mottu — APPROVED** [review]

File: pkg/virt-operator/resource/generate/components/webhooks.go [hunk 1]
```diff
@@ -357,7 +357,7 @@ func NewVirtAPIValidatingWebhookConfiguration(installNamespace string) *admissio
 				MatchConditions: []admissionregistrationv1.MatchCondition{
 					{
 						Name:       "only-vms",
-						Expression: `object.metadata.name.startsWith("virt-launcher")`,
+						Expression: `object.metadata.name.startsWith("virt-launcher") || object.metadata.name.startsWith("hp-volume-")`,
```
Comment (akalenyu) [inline pkg/virt-operator/resource/generate/components/webhooks.go]: Why don't we use a selector? I guess because our resource is `pods/eviction`? Just a bit of unrelated inefficiency that may have been fixed (k8s side?) since this was introduced. fyi @xpivarc

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go [hunk 2]
```diff
@@ -151,6 +157,10 @@ func isVirtLauncher(pod *k8scorev1.Pod) bool {
 	return pod.Labels[virtv1.AppLabel] == "virt-launcher"
 }
 
+func isHotplugPod(pod *k8scorev1.Pod) bool {
+	return pod.Labels[virtv1.AppLabel] == "hotplug-disk" && len(pod.OwnerReferences) == 1
+}
```
Comment (akalenyu) [inline pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go:189]: I think we can strengthen these conditions a bit by using the vmi name
(surely there's a util somewhere that helps with this)

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go [hunk 3]
```diff
@@ -55,6 +55,12 @@ func (admitter *PodEvictionAdmitter) Admit(ctx context.Context, ar *admissionv1.
 	if err != nil {
 		return validating_webhooks.NewPassingAdmissionResponse()
 	}
+	if isHotplugPod(pod) {
+		pod, err = admitter.kubeClient.CoreV1().Pods(ar.Request.Namespace).Get(ctx, pod.OwnerReferences[0].Name, metav1.GetOptions{})
+		if err != nil {
+			return validating_webhooks.NewPassingAdmissionResponse()
```
Comment (akalenyu) [inline pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go]: Are we okay with all errors here? Am I missing something?

File: pkg/virt-operator/resource/generate/components/webhooks.go (hunk 1 above)
Comment (Acedus) [reply pkg/virt-operator/resource/generate/components/webhooks.go]: Sure, I don't mind something like:
```
object.metadata.labels.filter(l, l.name == "kubevirt.io").all(l, l.value == "virt-launcher" || l.value == "hotplug-disk")
```

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go (hunk 3 above)
Comment (Acedus) [reply pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go]: Mmm I do wonder about that considering we don't deny the request when failing to obtain the request's Pod initially.

File: pkg/virt-operator/resource/generate/components/webhooks.go (hunk 1 above)
Comment (akalenyu) [reply pkg/virt-operator/resource/generate/components/webhooks.go]: I was hoping MatchConditions only fires off on resources that passed the ObjectSelector, I believe that's where we could gain some nice efficiency. But I suspect that wasn't/isn't possible https://github.com/kubevirt/kubevirt/blob/f759a37389b95114b2f5b7be1e6634eac7d0ec8b/vendor/k8s.io/api/admissionregistration/v1/types.go#L259-L260

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go (hunk 2 above)
Comment (Acedus) [reply pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go:189]: It technically gets checked once we resolve the virt-launcher pod from the hotplug owner reference. Do you have a better idea?

**Comment by Acedus** [comment]
@xpivarc I would very much appreciate your thoughts here.

File: pkg/virt-operator/resource/generate/components/webhooks.go (hunk 1 above)
Comment (xpivarc) [inline pkg/virt-operator/resource/generate/components/webhooks.go]: I would consider standalone webhook. I am wondering if you don't want to block the eviction all the time. 
Just thinking out loud.

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go (hunk 3 above)
Comment (xpivarc) [reply pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go]: +1 there can be intermittent error on API side. We probably want to consider only no exists errors

File: pkg/virt-operator/resource/generate/components/webhooks.go (hunk 1 above)
Comment (Acedus) [reply pkg/virt-operator/resource/generate/components/webhooks.go]: TBF, rethinking it, as it's a pod that is directly tied to the lifetime of the virt-launcher pod, I think we can just create a different eviction admitter path that straight up rejects eviction no-matter what.

Comment (xpivarc) [reply pkg/virt-operator/resource/generate/components/webhooks.go]: You still needs to authenticate legitimacy  of the Pod otherwise malicious user can protect workloads or block upgrade...

**Comment by Acedus** [comment]
[Change](https://github.com/kubevirt/kubevirt/compare/f759a37389b95114b2f5b7be1e6634eac7d0ec8b..48e2ce2deef8b2842d251ba9d119780e52f35bb6) - Address comments.

@xpivarc creating an entirely new admitter seemed a bit overkill so I repurposed `LauncherEvictionValidate` into a more generic `PodEvictionValidate` (name TBD) and extended it to handle either hotplug Pods or VMIs. WDYT?

File: pkg/virt-operator/resource/generate/components/webhooks.go (hunk 1 above)
Comment (fossedihelm) [reply pkg/virt-operator/resource/generate/components/webhooks.go]: >I would consider standalone webhook. I am wondering if you don't want to block the eviction all the time.
Just thinking out loud.

My preference: using or operator saving resources :)

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go (hunk 2 above)
Comment (vladikr) [reply pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go:189]: @Acedus maybe logging for now? just to say that it matches the label but owner refs are not 1.

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go [hunk 4]
```diff
@@ -55,19 +56,51 @@ func (admitter *PodEvictionAdmitter) Admit(ctx context.Context, ar *admissionv1.
...
+	case isVirtLauncher(pod) && !isCompleted(pod):
+		return admitter.admitLauncherPod(ctx, ar, pod)
+	}
+	return validating_webhooks.NewPassingAdmissionResponse()
+}
+
+func (admitter *PodEvictionAdmitter) admitHotplugPod(ctx context.Context, pod *k8scorev1.Pod) *admissionv1.AdmissionResponse {
+	ownerPod, err := admitter.kubeClient.CoreV1().Pods(pod.Namespace).Get(ctx, pod.OwnerReferences[0].Name, metav1.GetOptions{})
+	if err != nil {
+		if !k8serrors.IsNotFound(err) {
```
Comment (vladikr) [inline pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go:71]: I wonder if we should track these denials... maybe in prom?

**Comment by vladikr** [comment]
Thanks @Acedus !
Looks good to me. I have two minor nits, but maybe you can follow up.

/approve

**Comment by Acedus** [comment]
/hold
Thanks @vladikr, holding to address comments.

File: pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go (hunk 4 above)
Comment (Acedus) [reply pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go:71]: So supposedly a dispatcher warning should be logged in any of the kube-apiserver pods so long as auditing is enabled. One can then aggregate and analyze those logs via a log aggregation system such as Loki, but this extends beyond KubeVirt's scope. We could of course decorate the `denied` function to also log everything at a higher verbosity level, but if so I'd like to address it in a separate PR.
