### PR TITLE
Change snapshot and restore name generate methods in clone process

### LINKED ISSUE #10471: Snapshot will double create in clone process
**What happened**:
Snapshot will double create in some clone process just like this
 
image

Double create snapshot will not be delete when clone successed.

image

**What you expected to happen**:
Only create one snaphot obj for one clone. 

**How to reproduce it (as minimally and precisely as possible)**:
Create multiple clone obj.

**Additional context**:
I think this pr https://github.com/kubevirt/kubevirt/pull/10470 will fix it 

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by Longchuanzheng**
**What this PR does / why we need it**:
Change snapshot and restore name generate methods in clone process.

This will solve snapshot double create in clone process.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10471

**Special notes for your reviewer**:
Also removed some unused functions in pkg/virt-controller/watch/clone/util.go
**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-controller/watch/clone/util.go [hunk 1]
```diff
@@ -34,42 +35,15 @@ func getKey(name, namespace string) string {
...
-		generatedName = fmt.Sprintf("%s-%s", generatedName, name)
-	}
-
-	// Kubernetes' object names have limit of 252 characters.
-	// For more info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
-	if len(generatedName) > 252 {
-		generatedName = "clone-object"
-	}
-
-	generatedName = fmt.Sprintf("%s-%s", generatedName, rand.String(randomStringLength))
```
Comment (prnaraya) [inline pkg/virt-controller/watch/clone/util.go:55]: I'm hesitant about removing the random generated suffixes for these names; generally if a name isn't provided when creating something in KubeVirt, it will generate a name with a randomly generated suffix in this manner (also true when specifying a `GenerateName` in its ObjectMeta.

**Comment by prnaraya** [comment]
Thanks for your contribution! I've also left a couple comments inline.

Although I am not sure that changing the name generation function actually fixes the issue. Looking at #10471 it seems like this might be an issue with the `VMCloneController` where somehow an object is being reenqueued in an incorrect state, causing the controller to create another snapshot for the same VM clone. I would have to look into it a little closer but it might address the root of the problem.

**Comment by Longchuanzheng** [comment]
> Thanks for your contribution! I've also left a couple comments inline.
> 
> Although I am not sure that changing the name generation function actually fixes the issue. Looking at #10471 it seems like this might be an issue with the `VMCloneController` where somehow an object is being reenqueued in an incorrect state, causing the controller to create another snapshot for the same VM clone. I would have to look into it a little closer but it might address the root of the problem.

In implementation within our organization, I just add a specific suffix instead of randem suffix generate in naming.GetName method. At least on the surface, the phenomenon describe in the issue https://github.com/kubevirt/kubevirt/issues/10471 never appeared again. 
I very much hope to continue the discussion about the VMCloneController reenqueued problem. This is a bit of a challenge for me, but I'm more than happy to discuss it.

File: pkg/virt-controller/watch/clone/util.go (hunk 1 above)
Comment (Longchuanzheng) [reply pkg/virt-controller/watch/clone/util.go:55]: You're right, while the issue will appear if we use random suffix. I find resource in export package
```
//pkg/storage/export/export/export.go
// getDefaultTokenSecretName returns a secret name specifically created for the current export object
func getDefaultTokenSecretName(vme *exportv1.VirtualMachineExport) string {
	return naming.GetName("export-token", vme.Name, validation.DNS1035LabelMaxLength)
}

func (ctrl *VMExportController) getExportServiceName(vmExport *exportv1.VirtualMachineExport) string {
	return naming.GetName(exportPrefix, vmExport.Name, validation.DNS1035LabelMaxLength)
}

func (ctrl *VMExportController) getExportPodName(vmExport *exportv1.VirtualMachineExport) string {
	return naming.GetName(exportPrefix, vmExport.Name, validation.DNS1035LabelMaxLength)
}
```
all use GetName method. It create suffix with hash. 
In my opinion, use this method to generate name is ok, and we can use it to temporarily fix this problem which is likely to occur.

**Comment by prnaraya** [comment]
> I very much hope to continue the discussion about the VMCloneController reenqueued problem. This is a bit of a challenge for me, but I'm more than happy to discuss it.

I'm happy to continue discussing it as well; I need to take a closer look to see if I can pinpoint the issue but to start with I can give you a brief overview of the VMCloneController's workflow when cloning the VMs. Apologies if this is things you're already familiar with but I think it would be useful for us to be on the same page in terms of what I've looked into so far and what you have found/end up finding. I hope there is at least a little piece of information that can be helpful to you.

The `VMCloneController` contains an informer for VMClones; this tracks the creation and deletion of new VMClones, and any updates to VMClones, then calls a function `handleVMClone()` to handle these events (this controller also has informers for VMSnapshot and VMRestore that do the same thing). The event handler processes the add/update/delete of the VMClone, then adds its key to the workqueue (also contained in the controller) for further processing. When we run the controller, it starts all of these informers and waits for things to be added to its queue until it's asked to quit. When something is added to the queue, it processes the object's key and runs `execute(key)` to process the event. This can all be found in `pkg/virt-controller/watch/clone/clone_base.go`.

The execute function then gets the VMClone object and does two things to it: `sync()`, then `updateStatus()` (and then `sync()` once more after updating). If an error is returned from any of these functions, the controller will reenqueue the VMClone (i.e. add its key back into the workqueue) so that it can try to be processed again. This leads me to believe that there is something in either `updateStatus()` or `sync()` that is returning an error when it isn't supposed to, causing it to reenqueue when it shouldn't, OR there is some state changing between the time the error occurs to reenqueue the VMClone and the time when it is processed again, and this state change isn't being checked/accounted for before attempting to create a snapshot again (Snapshot and Restore creation happen in `sync()`, but both `sync()` and `updateStatus()` could be triggering the reenqueue so it might be good to investigate both). This is in `pkg/virt-controller/watch/clone/clone.go`.

Like I said, I would need to look at this closer to try pinpoint the issue but hopefully this can give you a good starting point to investigate this issue as well. It's possible that there is some other issue causing this, but based on what I see in the bug and in the code, I suspect that the issue is with how the `VMCloneController` is processing the VMClones. Let me know if there are any other questions or things you would like clarified, but this is pretty much the gist of how the controller is working (which is  how the informers and controllers are generally implemented).

**Comment by Longchuanzheng** [comment]
@prnaraya Thanks for your inspiration, I think snapshot double create because snapshot create for vmclone is quicker than vmclone update. The snapshot create action add a vmclone key enqueue. The vmclone reconcile with `vmClone.Status.SnapshotName == nil` because vmclone haven't update in updateStatus method.
We can add Expectations for snapshot and vmclone to avoid it.

**Comment by matthewei** [comment]
@prnaraya @Longchuanzheng  Hi all, In my opinion, I think this root cause is the use of multiple threads. Let'us use three threads as the initial condition and we named them "num-1","num-2","num-3", when they execute the function of [**createSnapshotFromVm**]<pkg/virt-controller/watch/clone/clone.go>at the same time. the function [**generateSnapshot**]</pkg/virt-controller/watch/clone/util.go> will generate different ***v1alpha1.VirtualMachineSnapshot** becase the suffix to the name is random. at last the system will keeps the last info.

**Comment by matthewei** [comment]
I thank we can use the lagic of **vmicontroller** to solve it. @prnaraya

**Comment by matthewei** [comment]
@Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot
image
we should wati cache has been updated at first and get the key.
if i am wrong, please notice it to me.

**Comment by Longchuanzheng** [comment]
> @Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot image we should wati cache has been updated at first and get the key. if i am wrong, please notice it to me.
 In `syncSourceVMTargetVM`:
```
case clonev1alpha1.PhaseUnset, clonev1alpha1.SnapshotInProgress:
		if vmClone.Status.SnapshotName == nil && snapshot == nil {
			_, syncInfo = ctrl.createSnapshotFromVm(vmClone, source, syncInfo)
			return syncInfo
		} else if vmClone.Status.SnapshotName == nil {
			syncInfo.snapshotName = snapshot.Name
			return syncInfo
		}

		snapshot, syncInfo = ctrl.verifySnapshotReady(vmClone, *vmClone.Status.SnapshotName, source.Namespace, syncInfo)
		if syncInfo.toReenqueue() || !syncInfo.snapshotReady {
			return syncInfo
		}

		fallthrough
```
`verifySnapshotReady` is after `createSnapshotFromVm`. Whether to enter the `createSnapshotFromVm` only related to `vmClone.Status.SnapshotName == nil ` and `vmClone.Status.Phase`.

File: pkg/virt-controller/watch/clone/util.go [hunk 2]
```diff
@@ -34,42 +35,15 @@ func getKey(name, namespace string) string {
...
-	return generatedName
-}
-
 func generateSnapshotName(cloneName, vmName string) string {
-	return generateNameWithRandomSuffix("clone", cloneName, "snapshot", vmName)
-}
+	generatedName := fmt.Sprintf("%s-%s-%s", cloneName, "snapshot", vmName)
+	return naming.GetName(clonePrefix, generatedName, validation.DNS1035LabelMaxLength)
```
Comment (mhenriks) [inline pkg/virt-controller/watch/clone/util.go:40]: why not `tmp-snapshot-<vm clone uid>`?

File: pkg/virt-controller/watch/clone/util.go [hunk 3]
```diff
@@ -34,42 +35,15 @@ func getKey(name, namespace string) string {
...
 
-func generateVolumeName(volumeName string) string {
-	return generateNameWithRandomSuffix("clone", "volume", volumeName)
-}
-
-func generateVMName(oldVMName string) string {
-	return generateNameWithRandomSuffix(oldVMName, "clone")
+func generateRestoreName(cloneName, vmName string) string {
+	generatedName := fmt.Sprintf("%s-%s-%s", cloneName, "restore", vmName)
+	return naming.GetName(clonePrefix, generatedName, validation.DNS1035LabelMaxLength)
```
Comment (mhenriks) [inline pkg/virt-controller/watch/clone/util.go:46]: why not `tmp-restore-<vm clone uid>?`

**Comment by matthewei** [comment]
> > @Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot image we should wati cache has been updated at first and get the key. if i am wrong, please notice it to me.
> 
> In `syncSourceVMTargetVM`:
> 
> ```
> 	switch vmClone.Status.Phase {
> 	case clonev1alpha1.PhaseUnset, clonev1alpha1.SnapshotInProgress:
> 
> 		if vmClone.Status.SnapshotName == nil {
> 			_, syncInfo = ctrl.createSnapshotFromVm(vmClone, source, syncInfo)
> 			return syncInfo
> 		}
> 
> 		snapshot, syncInfo = ctrl.verifySnapshotReady(vmClone, *vmClone.Status.SnapshotName, source.Namespace, syncInfo)
> 		if syncInfo.toReenqueue() || !syncInfo.snapshotReady {
> 			return syncInfo
> 		}
> 
> 		fallthrough
> ```
> 
> `verifySnapshotReady` is after `createSnapshotFromVm`. Whether to enter the `createSnapshotFromVm` only related to `vmClone.Status.SnapshotName == nil ` and `vmClone.Status.Phase`.

the root cause is that the cache can't be updated timely.

**Comment by matthewei** [comment]
> > > @Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot image we should wati cache has been updated at first and get the key. if i am wrong, please notice it to me.
> > 
> > 
> > In `syncSourceVMTargetVM`:
> > ```
> > 	switch vmClone.Status.Phase {
> > 	case clonev1alpha1.PhaseUnset, clonev1alpha1.SnapshotInProgress:
> > 
> > 		if vmClone.Status.SnapshotName == nil {
> > 			_, syncInfo = ctrl.createSnapshotFromVm(vmClone, source, syncInfo)
> > 			return syncInfo
> > 		}
> > 
> > 		snapshot, syncInfo = ctrl.verifySnapshotReady(vmClone, *vmClone.Status.SnapshotName, source.Namespace, syncInfo)
> > 		if syncInfo.toReenqueue() || !syncInfo.snapshotReady {
> > 			return syncInfo
> > 		}
> > 
> > 		fallthrough
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `verifySnapshotReady` is after `createSnapshotFromVm`. Whether to enter the `createSnapshotFromVm` only related to `vmClone.Status.SnapshotName == nil ` and `vmClone.Status.Phase`.
> 
> the root cause is that the cache can't be updated timely.

when the controller create snapshot and it return back to update the vmclone's status and the key would requeue.

**Comment by matthewei** [comment]
> > > > @Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot image we should wati cache has been updated at first and get the key. if i am wrong, please notice it to me.
> > > 
> > > 
> > > In `syncSourceVMTargetVM`:
> > > ```
> > > 	switch vmClone.Status.Phase {
> > > 	case clonev1alpha1.PhaseUnset, clonev1alpha1.SnapshotInProgress:
> > > 
> > > 		if vmClone.Status.SnapshotName == nil {
> > > 			_, syncInfo = ctrl.createSnapshotFromVm(vmClone, source, syncInfo)
> > > 			return syncInfo
> > > 		}
> > > 
> > > 		snapshot, syncInfo = ctrl.verifySnapshotReady(vmClone, *vmClone.Status.SnapshotName, source.Namespace, syncInfo)
> > > 		if syncInfo.toReenqueue() || !syncInfo.snapshotReady {
> > > 			return syncInfo
> > > 		}
> > > 
> > > 		fallthrough
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `verifySnapshotReady` is after `createSnapshotFromVm`. Whether to enter the `createSnapshotFromVm` only related to `vmClone.Status.SnapshotName == nil ` and `vmClone.Status.Phase`.
> > 
> > 
> > the root cause is that the cache can't be updated timely.
> 
> when the controller create snapshot and it return back to update the vmclone's status and the key would requeue.

image


> > > > @Longchuanzheng @prnaraya Hi all, the root cause may be from the following snapshot image we should wati cache has been updated at first and get the key. if i am wrong, please notice it to me.
> > > 
> > > 
> > > In `syncSourceVMTargetVM`:
> > > ```
> > > 	switch vmClone.Status.Phase {
> > > 	case clonev1alpha1.PhaseUnset, clonev1alpha1.SnapshotInProgress:
> > > 
> > > 		if vmClone.Status.SnapshotName == nil {
> > > 			_, syncInfo = ctrl.createSnapshotFromVm(vmClone, source, syncInfo)
> > > 			return syncInfo
> > > 		}
> > > 
> > > 		snapshot, syncInfo = ctrl.verifySnapshotReady(vmClone, *vmClone.Status.SnapshotName, source.Namespace, syncInfo)
> > > 		if syncInfo.toReenqueue() || !syncInfo.snapshotReady {
> > > 			return syncInfo
> > > 		}
> > > 
> > > 		fallthrough
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `verifySnapshotReady` is after `createSnapshotFromVm`. Whether to enter the `createSnapshotFromVm` only related to `vmClone.Status.SnapshotName == nil ` and `vmClone.Status.Phase`.
> > 
> > 
> > the root cause is that the cache can't be updated timely.
> 
> when the controller create snapshot and it return back to update the vmclone's status and the key would requeue.

image
Maybe we can push the key into the queue after updating the vmclone's status.

**Comment by mhenriks** [comment]
One note about using this method.  I think it would be nice to add some code that handles "already exists" errors.  Will just eliminate some spam in the log

File: pkg/virt-controller/watch/clone/clone.go [hunk 4]
```diff
@@ -359,9 +359,13 @@ func (ctrl *VMCloneController) createSnapshotFromVm(vmClone *clonev1alpha1.Virtu
...
 
-	snapshot, syncInfo.err = ctrl.client.VirtualMachineSnapshot(snapshot.Namespace).Create(context.Background(), snapshot, v1.CreateOptions{})
-	if syncInfo.err != nil {
-		return snapshot, addErrorToSyncInfo(syncInfo, fmt.Errorf("failed creating snapshot %s for clone %s: %v", snapshot.Name, vmClone.Name, syncInfo.err))
+	snapshot, err := ctrl.client.VirtualMachineSnapshot(snapshot.Namespace).Create(context.Background(), snapshot, v1.CreateOptions{})
+	if err != nil {
+		if !errors.IsAlreadyExists(err) {
+			return snapshot, addErrorToSyncInfo(syncInfo, fmt.Errorf("failed creating snapshot %s for clone %s: %v", snapshot.Name, vmClone.Name, err))
+		}
+		syncInfo.snapshotName = snapshot.Name
```
Comment (Longchuanzheng) [inline pkg/virt-controller/watch/clone/clone.go:367]: @mhenriks HI, do you think we need to log obj has already been created there?

Comment (mhenriks) [reply pkg/virt-controller/watch/clone/clone.go:367]: I don't think so.

**Comment by mhenriks** [comment]
can we add a unit test?

**Comment by Longchuanzheng** [comment]
> can we add a unit test?
Sorry, I overlooked this message. I think we can When updateStatus failed and return err, snapshot will also be multus created.

**Comment by Longchuanzheng** [comment]
hi,@mhenriks. I have done `make generate` and `make` but pull-kubevirt-generate test still log:
image
Also I find some error in storage test. Some are about clone. In my opinion, it is cased by storage problem and not my code.
Can you give me some advice? If you think it is caused by my pr, I will check more carefully.

**Comment by Longchuanzheng** [comment]
> hi,@mhenriks. I have done `make generate` and `make` but pull-kubevirt-generate test still log: image Also I find some error in storage test. Some are about clone. In my opinion, it is cased by storage problem and not my code. Can you give me some advice? If you think it is caused by my pr, I will check more carefully.

pull-kubevirt-generate test is my mistake, I have exported DOCKER_PREFIX before `make generate`.

File: hack/bazel-push-images.sh [hunk 5]
```diff
@@ -34,24 +34,6 @@ default_targets="
...
-    fedora-with-test-tooling-container-disk
-    alpine-with-test-tooling-container-disk
-    fedora-realtime-container-disk
-    disks-images-provider
-    nfs-server
-    vm-killer
-    winrmcli
-    sidecar-shim
-    network-slirp-binding
-    network-passt-binding
```
Comment (mhenriks) [inline hack/bazel-push-images.sh:54]: This must be a problem
