### PR TITLE
tests, libvmi: Support Alpine & Cirros VM/s on ARM64

### LINKED ISSUE #7635: VM failed to start when memory is less than 256M on Arm64
This issue is used to track this known memory issue on Arm64.

**What happened**:
When boot VMs on arm64 and set memory to 128M, get following error message:
```
EFI stub: Booting Linux Kernel...
EFI stub: EFI_RNG_PROTOCOL unavailable, no randomness supplied
EFI stub: ERROR: Failed to relocate kernel
EFI stub: ERROR: Failed to relocate kernel
```

**Anything else we need to know?**:
This issue only happens on ARM64 and is not related to kubevirt. Boot VM directly via qemu-kvm on arm64 server would also get this error.

**Reasons**
When using UEFI boot on Arm64, qemu would reserve 128M for loading UEFI boot firmware, so VM need additional 128M for VM boot. Assigning 256M memory ensures VM can boot successfully. When VM memory is less than 256M, VM boot may meet flaky error.

### PR DESCRIPTION
**Pull request by EdDev**
**What this PR does / why we need it**:

Alpine & Cirros images need 256M to boot on ARM64 [1].

[1] https://github.com/kubevirt/kubevirt/issues/7635

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7635 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
Thanks @EdDev 
/lgtm

**Comment by EdDev** [comment]
change: Fixed typo in commit message.

**Review by xpivarc — COMMENTED** [review]
Is 529c95dcd4c6a100798124f77390ee1a94fbe3d6 intentional?

**Comment by EdDev** [comment]
> Is [529c95d](https://github.com/kubevirt/kubevirt/commit/529c95dcd4c6a100798124f77390ee1a94fbe3d6) intentional?

I noted on the description that it depends on the other PR. Is this what you mean?

**Comment by EdDev** [comment]
> I missed that section. Usually, I would open a draft or put a hold on such PR

Putting a ‘hold’ also hints it is not reviewable/ready. It is.
Anyway, as both need rebase now, I will combine them into this PR and close the other.

**Comment by EdDev** [comment]
> Anyway, as both need rebase now, I will combine them into this PR and close the other.

Done

**Comment by EdDev** [comment]
Change: Rebase

**Comment by enp0s3** [comment]
ARM lane failed on build phase because of the greenhouse cache pollution. I've wiped the cache, will manually re-run the lane

**Comment by enp0s3** [comment]
Interesting... wiping doesn't help here, looking further into the caching issue

File: tests/libvmi/factory.go [hunk 1]
```diff
@@ -73,12 +76,20 @@ func NewAlpine(opts ...Option) *kvirtv1.VirtualMachineInstance {
 }
 
 func NewAlpineWithTestTooling(opts ...Option) *kvirtv1.VirtualMachineInstance {
+	alpineMemory := cirrosMemory
```
Comment (oshoval) [inline tests/libvmi/factory.go:79]: What about having an explicit function for `alpineMemory` please ?
both can call a common helper which does the function body (line 91)
or can simply call the `cirrosMemory`

Comment (EdDev) [reply tests/libvmi/factory.go:79]: What is the problem with an alias?

Comment (oshoval) [reply tests/libvmi/factory.go:79]: I find it less intuitive / less nice,
preferable imo a function that calls the other function or such

Comment (EdDev) [reply tests/libvmi/factory.go:79]: It is in the boundary of a few lines, I think it is readable.
- Common function: I do not have a good name for it.
- Wrapping with a function: I do not think it is worth the stack & code overhead.

Comment (oshoval) [reply tests/libvmi/factory.go:79]: > * Common function: I do not have a good name for it.

`vmiMemory()` or something likewise ?

Comment (EdDev) [reply tests/libvmi/factory.go:79]: > `vmiMemory()` or something likewise ?

It will be incorrect as we have Fedora which does not confirm to this at all.

> It will be better to have this helper / common because it is not more accurate than having
> cirrosMemory and aliasing it to alpine imo (semantically cirros is the subject where the subject is common)

Sorry, but this is not convincing me.
A common function I cannot describe well and a wrapper has no advantage over the simple aliasing.
Said that, if the maintainer that will approve this change will require it, I will comply for the sake of getting it in.

Comment (oshoval) [reply tests/libvmi/factory.go:79]: > It will be incorrect as we have Fedora which does not confirm to this at all.

Fwiw, both Cirros and Alpine are lightweight Linux so having this in the name can make it more accurate if desired

Comment (EdDev) [reply tests/libvmi/factory.go:79]: > Fwiw, both Cirros and Alpine are lightweight Linux so having this in the name can make it more accurate if desired
> (Cirros is consider minimal Linux as well)

I do not understand how it is related to the mentioning of Fedora, sorry.

Comment (oshoval) [reply tests/libvmi/factory.go:79]: > > Fwiw, both Cirros and Alpine are lightweight Linux so having this in the name can make it more accurate if desired
> > (Cirros is consider minimal Linux as well)
> 
> I do not understand how it is related to the mentioning of Fedora, sorry.

They are lightweight Linux, whereas Fedora isn't

**Review by oshoval — APPROVED** [review]
Thanks
