### PR TITLE
tests: Convert remaining kubectl tests to unit tests and drop kubectl_test.go

### LINKED ISSUE #12709: Drop oc/kubectl tests in tests/vm_test.go
**What happened**:

The cases testing `oc` and `kubectl` in vm_test.go (possibly also in other files) are questionable and should be either dropped or moved to `tests/kubectl_test.go` if deemed useful.

https://github.com/kubevirt/kubevirt/blob/bcd91649e91b0df8312d27725366823abdd2497c/tests/vm_test.go#L1499

**What you expected to happen**:

Drop unnecessary tests that test software (`oc` or `kubectl`) which is not developed in this repository.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

This converts the remaining kubectl tests in `tests/kubectl_test.go` to unit tests and drops `tests/kubectl_test.go` afterwards. We should not test `kubectl` in KubeVirt but only the parts that influence its behavior.

Before this PR:

kubectl is tested in functional tests.

After this PR:

Functionalities that influence the behavior of kubectl are tested in unit tests.

Fixes #12709

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

File: tests/kubectl_test.go [hunk 1]
```diff
@@ -90,137 +76,6 @@ var _ = Describe("[sig-compute]oc/kubectl integration", decorators.SigCompute, f
...
-				columnHeaders := resultFields[:len(expectedHeader)]
-				By("Verify the generated header is same as expected")
-				Expect(columnHeaders).To(Equal(expectedHeader))
-
-				By("Verify VMIM name")
-				Expect(resultFields[len(expectedHeader)]).To(Equal(migration.Name), "should match VMIM object name")
-				By("Verify VMIM phase")
-				Expect(resultFields[len(expectedHeader)+1]).To(Equal(string(v1.MigrationSucceeded)), "should have successful state")
-				By("Verify VMI name related to the VMIM")
-				Expect(resultFields[len(expectedHeader)+2]).To(Equal(vmi.Name), "should match the VMI name")
```
Comment (xpivarc) [inline tests/kubectl_test.go:219]: How do we these? The json path?

**Review by xpivarc — COMMENTED** [review]
Just one minor concern

File: tests/kubectl_test.go (hunk 1 above)
Comment (0xFelix) [reply tests/kubectl_test.go:219]: The added unit test asserts the exact order of additional printer columns. Meaning that after `Name` the `Phase` needs to come first and then the `VMI`.

**Review by fossedihelm — COMMENTED** [review]
/lgtm
@dhiller maybe you are interested in check tests for flakes failure

File: tests/kubectl_test.go (hunk 1 above)
Comment (xpivarc) [reply tests/kubectl_test.go:219]: That is one thing but how do we make sure we write correct json path?

Comment (0xFelix) [reply tests/kubectl_test.go:219]: We don't check the json path that was defined for additional printer columns. This was the only test that did this. I'm not sure if it's worth the effort, but if you insist, perhaps a unit test could be written for it.

Comment (xpivarc) [reply tests/kubectl_test.go:219]: Well either we have a test or we can verify it manually on each PR. Regressions can happen in many ways. Can we leave this test for now and merge the rest?

**Comment by dhiller** [comment]
> /lgtm @dhiller maybe you are interested in check tests for flakes failure

@fossedihelm @0xFelix sorry for the inconvenience - I've created a fix, and tested locally with this patch:

```diff
diff --git a/automation/repeated_test.sh b/automation/repeated_test.sh
index 65d57f48ed..d32c76e0fc 100755
--- a/automation/repeated_test.sh
+++ b/automation/repeated_test.sh
@@ -39,7 +39,7 @@ export IMAGE_PREFIX=''
 export IMAGE_PREFIX_ALT=''
 source hack/config-default.sh
 
-CANNIER_IMAGE="${CANNIER_IMAGE-quay.io/kubevirtci/cannier:v20250328-a1ef64e}"
+CANNIER_IMAGE="${CANNIER_IMAGE-quay.io/kubevirtci/cannier:v20250428-dc1823e}"
 
 export TIMESTAMP=${TIMESTAMP:-1}
 
```

maybe you can check whether this works for you, @0xFelix ?

**Comment by fossedihelm** [comment]
> maybe you can check whether this works for you, @0xFelix ?

@dhiller No issue!
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14606/pull-kubevirt-check-tests-for-flakes/1917498147760771072 Looks good!

**Comment by 0xFelix** [comment]
> maybe you can check whether this works for you, @0xFelix ?

Indeed, looks like the lane in this PR is now passing.

**Comment by fossedihelm** [comment]
> > maybe you can check whether this works for you, @0xFelix ?
> 
> Indeed, looks like the lane in this PR is now passing.

It was because of my first try in https://github.com/kubevirt/kubevirt/pull/14606 (I just pushed your changes).
Looks like that running it twice can be a way to bypass it.
But I would like to give a feedback to @dhiller in any case

**Comment by fossedihelm** [comment]
Side note: I found it interesting how CI results are connected between PRs if those have exactly the same commits

File: tests/kubectl_test.go (hunk 1 above)
Comment (0xFelix) [reply tests/kubectl_test.go:219]: @xpivarc Added tests in https://github.com/kubevirt/kubevirt/pull/14554/commits/59a53b12ca9a8828579020c0ae71b3d2c639eb20 to address your concern and fixed a regression I found in 9a292f2e968eaae6e7779032a6d9e3b1ce4bf3cb. PTAL.

File: pkg/virt-operator/resource/generate/components/crds.go [hunk 2]
```diff
@@ -596,7 +596,6 @@ func NewVirtualMachineRestoreCrd() (*extv1.CustomResourceDefinition, error) {
 		{Name: "TargetName", Type: "string", JSONPath: ".spec.target.name"},
 		{Name: "Complete", Type: "boolean", JSONPath: ".status.complete"},
 		{Name: "RestoreTime", Type: "date", JSONPath: ".status.restoreTime"},
-		{Name: "Error", Type: "string", JSONPath: errorMessageJSONPath},
```
Comment (xpivarc) [inline pkg/virt-operator/resource/generate/components/crds.go:599]: Nice

File: pkg/virt-operator/resource/generate/components/crds_test.go [hunk 3]
```diff
@@ -119,4 +137,316 @@ var _ = Describe("CRDs", func() {
 		Entry("for VirtualMachineClone", NewVirtualMachineCloneCrd, "Phase", "SourceVirtualMachine", "TargetVirtualMachine"),
 		Entry("for MigrationPolicy", NewMigrationPolicyCrd),
 	)
+
+	Context("Additional printer columns map to expected value", func() {
```
Comment (xpivarc) [inline pkg/virt-operator/resource/generate/components/crds_test.go:147]: I love it :)

File: pkg/virt-operator/resource/generate/components/crds_test.go [hunk 4]
```diff
@@ -119,4 +137,316 @@ var _ = Describe("CRDs", func() {
...
+
+			obj := serialize(vmi)
+			for _, version := range crd.Spec.Versions {
+				Expect(extract(version.AdditionalPrinterColumns[0].JSONPath, obj)).To(Equal(vmi.ObjectMeta.CreationTimestamp.UTC().Format(time.RFC3339)))
+				Expect(extract(version.AdditionalPrinterColumns[1].JSONPath, obj)).To(Equal(string(vmi.Status.Phase)))
+				Expect(extract(version.AdditionalPrinterColumns[2].JSONPath, obj)).To(Equal(vmi.Status.Interfaces[0].IP))
+				Expect(extract(version.AdditionalPrinterColumns[3].JSONPath, obj)).To(Equal(vmi.Status.NodeName))
+				Expect(extract(version.AdditionalPrinterColumns[4].JSONPath, obj)).To(Equal(string(vmi.Status.Conditions[0].Status)))
+				Expect(extract(version.AdditionalPrinterColumns[5].JSONPath, obj)).To(Equal(string(vmi.Status.Conditions[1].Status)))
+				Expect(extract(version.AdditionalPrinterColumns[6].JSONPath, obj)).To(Equal(string(vmi.Status.Conditions[2].Status)))
```
Comment (xpivarc) [inline pkg/virt-operator/resource/generate/components/crds_test.go:189]: nit: I would assert to concrete values and probably iterate over the `AdditionalPrinterColumns` to make it detect deletion or addition

**Review by xpivarc — COMMENTED** [review]
/hold cancel

**Comment by xpivarc** [comment]
@0xFelix It seems one more rebase is needed.

File: pkg/virt-operator/resource/generate/components/crds_test.go (hunk 3 above)
Comment (0xFelix) [reply pkg/virt-operator/resource/generate/components/crds_test.go]: :)
