### PR TITLE
webhooks: Return early when VirtualMachine is being deleted

### LINKED ISSUE #9438: Removing a namespace containing VirtualMachines using Instance Types or Preferences remains blocked
/area instancetype
/cc @fossedihelm 
/cc @0xFelix 

**What happened**:

This was initially reported downstream under https://bugzilla.redhat.com/show_bug.cgi?id=2178037

https://github.com/kubevirt/kubevirt/pull/8937 introduced a foreground finalizer to VirtualMachines. This included a skip of validations when deleting a VirtualMachine but does not skip running the mutation webhook.

As a result when deleting a namespace containing VirtualMachines that use Instance Types or Preferences we get into a situation where the actual `update` to remove the finalizer cannot complete as the mutation webhook constantly fails due to the now missing resources.

**What you expected to happen**:

Either the mutations webhook or instance type lookup code is skipped when `vm.DeletionTimestamp != nil` allowing the update to complete and the finalizer to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

The following example shows how the VirtualMachine isn't initially deleted during the removal of the namespace until the entire `spec.instancetype` section is dropped allowing the finalizer update to succeed:

```
./cluster-up/kubectl.sh apply -f https://k8s.io/examples/admin/namespace-dev.yaml
./cluster-up/kubectl.sh apply -f examples/csmall.yaml -f examples/vm-cirros-csmall.yaml -n development
[..]
./cluster-up/kubectl.sh get -n development vm/vm-cirros-csmall -o json | jq .spec.instancetype
selecting docker as container runtime
{
  "kind": "VirtualMachineInstancetype",
  "name": "csmall",
  "revisionName": "vm-cirros-csmall-csmall-6242f4e8-8855-4c33-8e07-c68840db36c7-1"
}
./cluster-up/kubectl.sh delete namespace/development
[..]
^C
./cluster-up/kubectl.sh get vms -n development vm-cirros-csmall -o json | jq .metadata.finalizers
selecting docker as container runtime
[
  "kubevirt.io/virtualMachineControllerFinalize"
]
./cluster-up/kubectl.sh get namespace/development -o json | jq .status
selecting docker as container runtime
{
  "conditions": [
    {
      "lastTransitionTime": "2023-03-15T13:15:18Z",
      "message": "All resources successfully discovered",
      "reason": "ResourcesDiscovered",
      "status": "False",
      "type": "NamespaceDeletionDiscoveryFailure"
    },
    {
      "lastTransitionTime": "2023-03-15T13:15:18Z",
      "message": "All legacy kube types successfully parsed",
      "reason": "ParsedGroupVersions",
      "status": "False",
      "type": "NamespaceDeletionGroupVersionParsingFailure"
    },
    {
      "lastTransitionTime": "2023-03-15T13:15:18Z",
      "message": "All content successfully deleted, may be waiting on finalization",
      "reason": "ContentDeleted",
      "status": "False",
      "type": "NamespaceDeletionContentFailure"
    },
    {
      "lastTransitionTime": "2023-03-15T13:15:18Z",
      "message": "Some resources are remaining: virtualmachines.kubevirt.io has 1 resource instances",
      "reason": "SomeResourcesRemain",
      "status": "True",
      "type": "NamespaceContentRemaining"
    },
    {
      "lastTransitionTime": "2023-03-15T13:15:18Z",
      "message": "Some content in the namespace has finalizers remaining: kubevirt.io/virtualMachineControllerFinalize in 1 resource instances",
      "reason": "SomeFinalizersRemain",
      "status": "True",
      "type": "NamespaceFinalizersRemaining"
    }
  ],
  "phase": "Terminating"
}

./cluster-up/kubectl.sh patch -n development vms/vm-cirros-csmall --type='json' -p '[{"op": "remove", "path": "/metadata/finalizers"}]'
selecting docker as container runtime
The request is invalid: spec.instancetype: Failure to find instancetype: controllerrevisions.apps "vm-cirros-csmall-csmall-0c56ded0-b207-4b39-9ab7-26e0ba1db944-1" not found

./cluster-up/kubectl.sh patch -n development vms/vm-cirros-csmall --type='json' -p '[{"op": "remove", "path": "/spec/instancetype/revisionName"}]'
selecting docker as container runtime
The request is invalid: spec.instancetype: Failure to find instancetype: virtualmachineinstancetypes.instancetype.kubevirt.io "csmall" not found

./cluster-up/kubectl.sh patch -n development vms/vm-cirros-csmall --type='json' -p '[{"op": "remove", "path": "/spec/instancetype"}]'
selecting docker as container runtime
virtualmachine.kubevirt.io/vm-cirros-csmall patched

./cluster-up/kubectl.sh get -n development vms/vm-cirros-csmall -o json | jq .status
selecting docker as container runtime
Error from server (NotFound): namespaces "development" not found
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @fossedihelm
/cc @0xFelix

**What this PR does / why we need it**:

As set out in issue #9438 previously attempts to remove a namespace would be blocked if it contained VirtualMachines using VirtualMachineInstancetypes. This was due to the update call to remove the virtualMachineControllerFinalizer being rejected as the ControllerRevision associated with the VirtualMachineInstancetype had already been deleted, causing admission of the request to be rejected.

This change adds basic logic to both the mutation and admission webhooks that returns early *if* the VirtualMachine is being deleted. Ensuring the update to remove the virtualMachineControllerFinalizer is successful and allowing the overall namespace removal to also complete.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9438

**Special notes for your reviewer**:

The alternative to this is to return early from specific instance type related flows but I'm interested to see if this earlier straight forward approach would be acceptable to folks before we go down that route.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
Sorry this was supposed to be a draft, I'll add func tests shortly.

File: tests/vm_test.go [hunk 1]
```diff
@@ -2460,45 +2459,105 @@ status:
...
 				vm, err = virtClient.VirtualMachine(vm.Namespace).Get(context.Background(), vm.Name, &k8smetav1.GetOptions{})
 				g.Expect(err).ToNot(HaveOccurred())
 				g.Expect(controller.HasFinalizer(vm, v1.VirtualMachineControllerFinalizer)).To(BeTrue())
+				g.Expect(controller.HasFinalizer(vm, customFinalizer)).To(BeTrue())
+				g.Expect(vm.Spec.Instancetype.RevisionName).ToNot(BeEmpty())
 			}, 2*time.Minute, 1*time.Second)
 
-			err = virtClient.VirtualMachine(testsuite.GetTestNamespace(vm)).Delete(context.Background(), vm.Name, &metav1.DeleteOptions{})
+			vm, err = virtClient.VirtualMachine(vm.Namespace).Get(context.Background(), vm.Name, &k8smetav1.GetOptions{})
+			Expect(err).ToNot(HaveOccurred())
```
Comment (fossedihelm) [inline tests/vm_test.go:2541]: nit: `vm` is already updated from previous `Eventually`

File: tests/vm_test.go [hunk 2]
```diff
@@ -2460,45 +2459,105 @@ status:
...
 			By("Ensure the vm has disappeared")
 			Eventually(func() bool {
 				vm, err = virtClient.VirtualMachine(vm.Namespace).Get(context.Background(), vm.Name, &k8smetav1.GetOptions{})
 				return errors.IsNotFound(err)
 			}, 2*time.Minute, 1*time.Second).Should(BeTrue(), fmt.Sprintf("vm %s is not deleted", vm.Name))
 		})
 
-		It("should be added when the vm is created", func() {
+		It("should be added when the vm is created and removed when the vm is being deleted", func() {
+			vm.Finalizers = append(vm.Finalizers, customFinalizer)
```
Comment (fossedihelm) [inline tests/vm_test.go:2470]: Since both tests has the `customFinalizer` this can be done in `BeforeEach` section. 
With this, we can also remove the `if controller.HasFinalizer(vm, customFinalizer)` check in the AfterEach.
WDYT?

**Review by fossedihelm — COMMENTED** [review]
Looks good to me. Just two small comments.
Thanks for addressing this

File: tests/vm_test.go (hunk 1 above)
Comment (lyarwood) [reply tests/vm_test.go:2541]: So I assumed the same but the value of `vm` here is still that returned by the `.Create()` call above without `vm.Spec.Instancetype.RevisionName` populated (the `VM` controller adds this after creation). Taking this additional `Get` out causes the `ControllerRevision` `Delete()` to fail as the name provided is empty.

Comment (fossedihelm) [reply tests/vm_test.go:2535]: I learned something new. Thanks

**Review by fossedihelm — APPROVED** [review]
Thanks!

**Review by 0xFelix — APPROVED** [review]
From what I can tell LGTM!

/lgtm

**Review by 0xFelix — APPROVED** [review]
/lgtm
/retest
