### PR TITLE
Provide all relevant POD routes to the guest

### LINKED ISSUE #824: Pod on one node can not ping VM on other node
On OpenShift.

Launching a pod on on node, then trying to ping running a VM on another node fails.

- pod tp pod on another node works
- pod to vm on same node works

### PR DESCRIPTION
**Pull request by vladikr**
This series will provide all relevant POD routes to the guest via
DHCP option 121 (RFC4332 - https://tools.ietf.org/html/rfc3442)

Should resolve #824 

Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by cynepco3hahue** [comment]
I miss functional test to start VM's on different nodes and ping one from another.
Or create an issue and I will add it :smile:

File: pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go [hunk 1]
```diff
@@ -100,3 +104,31 @@ func (h *DHCPHandler) ServeDHCP(p dhcp.Packet, msgType dhcp.MessageType, options
...
+	// For example:
+	// 		routes:
+	//				10.0.0.0/8 ,  gateway: 10.1.2.3
+	//              192.168.1/24, gateway: 192.168.2.3
+	//		would result in the following structure:
+	//      []byte{8, 10, 10, 1, 2, 3, 24, 192, 168, 1, 192, 168, 2, 3}
+
+	for _, route := range *routes {
+		if route.Dst == nil {
+			continue
```
Comment (stu-gott) [inline pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go]: A route without a destination... So this code basically discards the entire route... Having only skimmed RFC4332, is this the correct thing to do? (the other option being to raise an error). To be clear, I'm not suggesting a change, I'm simply hoping to clarify.

This condition wasn't covered by unit tests. Would it be difficult to add one?

Comment (vladikr) [reply pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go]: > A route without a destination...

The only route without a destination I know is a default gateway, which is set in OptionRouter , not via OptionClasslessRouteFormat. Are there any other cases?

**Comment by vladikr** [comment]
> I miss functional test to start VM's on different nodes and ping one from another.

@cynepco3hahue - It should be covered by [1], but you are welcome to improve it :)

[1] https://github.com/kubevirt/kubevirt/blob/master/tests/vm_networking_test.go#L172

File: pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go (hunk 1 above)
Comment (stu-gott) [reply pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go]: Not that I'm aware of. Thanks for clarifying!

**Comment by rmohr** [comment]
> @cynepco3hahue - It should be covered by [1], but you are welcome to improve it :)
> 
> [1] https://github.com/kubevirt/kubevirt/blob/master/tests/vm_networking_test.go#L172

VM to VM would indeed be great. it would cover a very relevant additional case where something can go wrong.

**Comment by cynepco3hahue** [comment]
@vladikr @rmohr will add it to my TODO list

**Comment by vladikr** [comment]
[BUG: pod can not ping VM on other node](https://trello.com/c/AXEnTYnE/43-bug-pod-can-not-ping-vm-on-other-node)

**Comment by vladikr** [comment]
[BUG: pod can not ping VM on other node](https://trello.com/c/AXEnTYnE/43-bug-pod-can-not-ping-vm-on-other-node)

**Comment by davidvossel** [comment]
> @cynepco3hahue - It should be covered by [1], but you are welcome to improve it :)
[1] https://github.com/kubevirt/kubevirt/blob/master/tests/vm_networking_test.go#L172

these unit tests verify
* pod -> VM
* node -> VM
* VM -> google

To finish the test matrix, we should add cases for  
* VM -> VM
* VM -> pod

**Comment by fabiand** [comment]
We also need to make sure that we ping from _different_ nodes

**Comment by vladikr** [comment]
> We also need to make sure that we ping from different nodes

We do ;)

**Comment by fabiand** [comment]
Darn. very good.

**Comment by davidvossel** [comment]
retest this please

**Comment by rmohr** [comment]
retest this please

**Comment by mlsorensen** [comment]
I may have run into an issue related to this. It seems I'm getting a static route to my gateway, and no default gateway.

My lease looks like this:

> lease {
>   interface "eth0";
>   fixed-address 172.16.52.146;
>   option subnet-mask 255.255.255.255;
>   option routers 169.254.1.1;
>   option dhcp-lease-time 86313600;
>   option dhcp-message-type 5;
>   option domain-name-servers 192.168.0.10;
>   option dhcp-server-identifier 10.11.12.13;
>   option classless-static-routes 32.169.254.1.1 169.254.1.1;
>   renew 3 2019/05/01 23:04:52;
>   rebind 0 2020/08/16 23:48:11;
>   expire 6 2020/12/19 20:48:11;
> }

And results in routing table like this:

> [root@fedora ~]# ip route show
> 169.254.1.1 via 169.254.1.1 dev eth0 proto static

And I can't get anywhere. Maybe in the "// Filter out irrelevant routes" it should skip routes with destination IP of the gateway? Or does that defeat your purpose?

I ran some debugging and I'm getting a VIF route entry of Src=<nil> Dst.IP=169.254.1.1/32

If I do filter out the Dst == router route I'm back in business:

> [root@fedora ~]# ip route show
> default via 169.254.1.1 dev eth0
