### PR TITLE
virtctl: Fix linting issues in pkg/virtctl/create/params

### LINKED ISSUE #14196: Resolve linting issues in pkg/virtctl/create/params
**What happened**:

Running the linter against `pkg/virtctl/create/params` fails.

**What you expected to happen**:

Running the linter against `pkg/virtctl/create/params` should succeed without errors or warnings.

**How to reproduce it (as minimally and precisely as possible)**:

Add `pkg/virtctl/create/params` to `hack/linter/lint-paths.txt` and run `make lint`.

/kind cleanup
/label good-first-issue

### PR DESCRIPTION
**Pull request by aks3213**
- Added named return values to SplitPrefixedName function

- Replaced magic numbers with constants

- Fixed formatting and line length issues in tests

Fixes #14196

### What this PR does
Before this PR:
* package `pkg/virtctl/create/params` was not formatted as per listing rules

After this PR:
* package `pkg/virtctl/create/params` is now formatted as per listing rules, `make lint` passes

Fixes #

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

File: pkg/virtctl/create/params/params.go [hunk 1]
```diff
@@ -189,15 +191,18 @@ func apply(paramsMap map[string]string, obj interface{}) error {
...
 // SplitPrefixedName splits prefixedName with "/" as a separator
-func SplitPrefixedName(prefixedName string) (string, string, error) {
-	name := ""
-	prefix := ""
+func SplitPrefixedName(prefixedName string) (
+	prefix string,
+	name string,
+	err error,
+) {
+	prefix = ""
```
Comment (0xFelix) [inline pkg/virtctl/create/params/params.go:199]: not required anymore when using named returns
```suggestion
```

File: pkg/virtctl/create/params/params.go [hunk 2]
```diff
@@ -14,6 +14,8 @@ import (
 
 const (
 	paramTag = "param"
+	// paramSeparatorCount is the expected number of parts when splitting parameters
```
Comment (0xFelix) [inline pkg/virtctl/create/params/params.go:17]: The comment is not accurate, since this const is also used to split names now. I'd drop it.

**Review by 0xFelix — COMMENTED** [review]
Please take care of the commit message and add a `None` release note to the PR description.

File: pkg/virtctl/create/params/params.go (hunk 2 above)
Comment (aks3213) [reply pkg/virtctl/create/params/params.go]: Removed the comment.

File: pkg/virtctl/create/params/params.go (hunk 1 above)
Comment (aks3213) [reply pkg/virtctl/create/params/params.go]: Removed initialisation as it was not required anymore.

**Comment by aks3213** [comment]
@0xFelix, updated commit message and release note.

**Comment by aks3213** [comment]
@0xFelix done.

**Review by 0xFelix — COMMENTED** [review]
/test all

**Comment by victortoso** [comment]
> Some tests failed, does it have to do anything with my changes

Indeed it does. If you click on the details [link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/14225/pull-kubevirt-build/1900579933130854400) you'll be able to access the logs.

```
16:16:28: Changes not staged for commit:
16:16:28:   (use "git add <file>..." to update what will be committed)
16:16:28:   (use "git restore <file>..." to discard changes in working directory)
16:16:28: 	modified:   pkg/virtctl/create/params/params.go
16:16:28: 
16:16:28: no changes added to commit (use "git add" and/or "git commit -a")
make: *** [Makefile:154: build-verify] Error 1 
```

> Because I didn't change any business logic anywhere!

But we do have generation as a build process.

Do try `make bazel-generate` git add & git commit those generated files. Better yet to be sure your local repo builds.

**Comment by victortoso** [comment]
> Do try make bazel-generate git add & git commit those generated files. Better yet to be sure your local repo builds.

Actually, `make generate` instead. Did it locally and the output

```diff
toso@tapioca ~/s/k/kubevirt (review-14225)> git diff
diff --git a/pkg/virtctl/create/params/params.go b/pkg/virtctl/create/params/params.go
index 5f5c303809..900f7288c4 100644
--- a/pkg/virtctl/create/params/params.go
+++ b/pkg/virtctl/create/params/params.go
@@ -13,7 +13,7 @@ import (
 )

 const (
-       paramTag = "param"
+       paramTag            = "param"
        paramSeparatorCount = 2
 )
```

**Comment by aks3213** [comment]
@0xFelix @victortoso Done.

**Comment by aks3213** [comment]
@0xFelix @victortoso anything required from me?

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!

**Comment by 0xFelix** [comment]
@victortoso Mind giving this a look again?

**Comment by victortoso** [comment]
/lgtm

Thanks!

**Comment by aks3213** [comment]
Hey @0xFelix, @victortoso, what's next?

**Comment by victortoso** [comment]
> what's next?

If you mean about this PR, it already got both `lgtm` and `approve` labels, so after the CI finish its testing it'll be merged to the main branch. Nothing else needed for now.
