### PR TITLE
sriov-lane: dedicated container disk image

### LINKED ISSUE #3850: Test suite: AfterSuite errors
/kind bug

**What happened**:
SRIOV lane Prow jobs are failing due to AfterSuite error, whether tests passed or not
it also happend once on k8s-1.18 lane:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3755/pull-kubevirt-e2e-k8s-1.18/1280142057649737728
```
[AfterSuite] AfterSuite 
/root/go/src/kubevirt.io/kubevirt/tests/tests_suite_test.go:55
  Timed out after 240.000s.
  Expected
      <bool>: false
  to be true
  /root/go/src/kubevirt.io/kubevirt/tests/utils.go:55
```

Debugging this error, I found that deleting the namespace `kubevirt-test-default` at AfterSuite
causing a timeout, during deletion process of that namespace there is a condition with an error:
```
 NamespaceDeletionDiscoveryFailure 
        True 
        2020-07-13 20:08:40 +0000 UTC 
        DiscoveryFailed 
        Discovery failed for some groups, 1 failing: 
            unable to retrieve the complete list of server APIs: 
                upload.cdi.kubevirt.io/v1alpha1: 
                    the server is currently unable to handle the request
```

**What you expected to happen**:
Not failing on AfterSuite.

**How to reproduce it (as minimally and precisely as possible)**:
Run sriov lane job on prow.

**Anything else we need to know?**:
This issue will not reproduce locally, only on prow.

**Environment**:
- Kubevirt Provider: kind-k8s-sriov-1.17.0
- KubeVirt version (use `virtctl version`): master
- Kubernetes version (use `kubectl version`): 1.17
- VM or VMI specifications: 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
In sriov-lane we use fedora container disk image, 
that image does not include `qemu-ga` package or sriov drivers.
Currently we install and config what necessary through in place before each test using cloud-init:
`quem-ga` package downloaded from internal http server `cdi-http-import-server`
sriov drivers are installed with dnf.

This PR uses new image that include all necessary packages and configurations
for sriov lane tests.
Using this kind of image instead of relaying on cloud-config and internal http server
is more efficient, take less time for VM to be ready and thus for tests to finish
and most important less prune to errors.

**Which issue(s) this PR fixes**:
Needed for #3797 
Fixes #3850 

**Special notes for your reviewer**:
At the moment I am pulling the image form private registry, 
once the image will be stored in kubevirt registry  I will update bazel container_pull rule

The image was create with https://github.com/ormergi/vm-image-builder
PR for adding it to kubevirtci https://github.com/kubevirt/kubevirtci/pull/428

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
pull-kubevirt-e2e-kind-1.17-sriov

**Comment by ormergi** [comment]
/pull-kubevirt-e2e-kind-1.17-sriov

**Review by phoracek — APPROVED** [review]
/lgtm

Huge kudos for the README, really helpful. And overall, the PR is nicely structured.

File: tests/vmi_multus_test.go [hunk 1]
```diff
@@ -623,33 +623,28 @@ var _ = Describe("SRIOV", func() {
...
 				network := v1.Network{Name: name, NetworkSource: v1.NetworkSource{Multus: &v1.MultusNetwork{NetworkName: name}}}
 				vmi.Spec.Domain.Devices.Interfaces = append(vmi.Spec.Domain.Devices.Interfaces, iface)
 				vmi.Spec.Networks = append(vmi.Spec.Networks, network)
 			}
 
-			// fedora requires some more memory to boot without kernel panics
-			vmi.Spec.Domain.Resources.Requests[k8sv1.ResourceName("memory")] = resource.MustParse("1024M")
-
-			return
+			return vmi
```
Comment (alonSadan) [inline tests/vmi_multus_test.go:647]: nit:
nit: since we specify the name of the return object, you can leave the return statement empty, or delete the name of the result parameter from the function signature.
further explanation can be found here:
https://golang.org/ref/spec#Return_statements

**Comment by ormergi** [comment]
Rebased 
Change vmi_multus_test.go, `getSriovVMI` - remove explicit return object type instance name

File: containerimages/container-disk-images.md [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+container image with `kubevirt/container-disk-v1alpha` layer, 
+so KubeVirt VM's can consume it according to  
+https://github.com/kubevirt/kubevirt/blob/master/docs/container-register-disks.md
+
+```bash
+cat > Dockerfile <<EOF
+FROM kubevirt/container-disk-v1alpha
+ADD fedora32.qcow2 /disk/
+
+docker build -t kubevirt/fedora-sriov-testing:latest .
```
Comment (phoracek) [inline containerimages/container-disk-images.md:57]: You miss EOF here

File: containerimages/container-disk-images.md [hunk 3]
```diff
@@ -0,0 +1,113 @@
+# KubeVirt container-disk images
+The following images stored at `dockerhub.com/kubevirt` and can be used in Kubevirt tests:
+
+- <b>alpine-container-disk-demo</b>
```
Comment (phoracek) [inline containerimages/container-disk-images.md:4]: You can make it **bold** with `**bold**`

**Review by phoracek — CHANGES_REQUESTED** [review]

File: containerimages/container-disk-images.md (hunk 2 above)
Comment (ormergi) [reply containerimages/container-disk-images.md:58]: Done

File: containerimages/container-disk-images.md (hunk 3 above)
Comment (ormergi) [reply containerimages/container-disk-images.md]: Done

**Review by phoracek — APPROVED** [review]
/lgtm

File: tests/vmi_multus_test.go (hunk 1 above)
Comment (alonSadan) [reply tests/vmi_multus_test.go:647]: answered [here](https://github.com/kubevirt/kubevirt/pull/3797#discussion_r474064821)

**Comment by alonSadan** [comment]
Let's override the SRIOV lane. the failures are known and are addressed in the [follow-up](https://github.com/kubevirt/kubevirt/pull/3797) for this PR and in  this [one](https://github.com/kubevirt/kubevirt/pull/4001).

**Comment by ormergi** [comment]
> /approve
Thanks!


> @danielBelenky what do you say we override the SRIOV lane. the failures are known and are addressed in the [follow-up](https://github.com/kubevirt/kubevirt/pull/3797) for this PR and in this [one](https://github.com/kubevirt/kubevirt/pull/4001).

@alonSadan  thanks for mentioning it

**Comment by ormergi** [comment]
Sriov lane fails due to flaky tests that will be resolved by [PR 4001](https://github.com/kubevirt/kubevirt/pull/4001) and afterSuite errors that will be resolved by [PR 3797](https://github.com/kubevirt/kubevirt/pull/3797).

Both PR's, 3797 and 4001, depend on this PR (3834), sriov-lane must be `/override` for this PR to merge.

Once all mentioned PR's will be merged we could enable it again.
