### PR TITLE
instancetype: Fix overcommit percent calculation

### LINKED ISSUE #9912: `overcommitPercent` not changing the requested memory of the `VirtualMachineInstance` or `virt-launcher` pod
/area instancetype

**What happened**:

While writing up a blog post for `v1beta1` I noticed that `overcommitPercent` didn't appear to be changing the requested memory of the `VirtualMachineInstance` or `virt-launcher` pod:

```
./cluster-up/kubectl.sh get virtualmachineinstancetype/overcommit -o json | jq .spec
selecting podman as container runtime
{
  "cpu": {
    "guest": 1
  },
  "memory": {
    "guest": "128Mi",
    "overcommitPercent": 15
  }
}
 
./cluster-up/kubectl.sh get vms/cirros -o json | jq .spec.instancetype
selecting podman as container runtime
{
  "kind": "virtualmachineinstancetype",
  "name": "overcommit",
  "revisionName": "cirros-overcommit-689628d4-fcbc-4c64-b9e2-cd464109e3ef-2"
}
 
./cluster-up/kubectl.sh get vmis/cirros -o json | jq .spec.domain.resources.requests
selecting podman as container runtime
{
  "memory": "128Mi"
}
 
./cluster-up/kubectl.sh get pods/virt-launcher-cirros-tw72g -o json | jq .spec.containers[].resources.requests
selecting podman as container runtime
{
  "cpu": "100m",
  "devices.kubevirt.io/kvm": "1",
  "devices.kubevirt.io/tun": "1",
  "devices.kubevirt.io/vhost-net": "1",
  "ephemeral-storage": "50M",
  "memory": "379136Ki"
}
{
  "cpu": "1m",
  "ephemeral-storage": "50M",
  "memory": "1M"
}
```
 Hacking around with the tests also shows the same:
 
```
$ git diff
diff --git a/pkg/instancetype/instancetype_test.go b/pkg/instancetype/instancetype_test.go
index 6065c196b..1ed958ddf 100644
--- a/pkg/instancetype/instancetype_test.go
+++ b/pkg/instancetype/instancetype_test.go
@@ -1122,6 +1122,7 @@ var _ = Describe("Instancetype and Preferences", func() {
                                instancetypeSpec.Memory.OvercommitPercent = 15
 
                                expectedOverhead := instancetypeSpec.Memory.Guest.Value() * (1 - int64(instancetypeSpec.Memory.OvercommitPercent)/int64(100))
+                               Expect(expectedOverhead).ToNot(Equal(instancetypeSpec.Memory.Guest.Value()))
 
                                conflicts := instancetypeMethods.ApplyToVmi(field, instancetypeSpec, preferenceSpec, &vmi.Spec)
                                Expect(conflicts).To(BeEmpty())

$ /home/lyarwood/go/bin/ginkgo --json-report ./ginkgo.report -focus "Instancetype and Preferences Apply instancetype.Spec.Memory should apply memory overcommit correctly to VMI"   -r
Running Suite: pkg/instancetype/instancetype_suite_test.go - /home/lyarwood/redhat/devel/src/k8s/kubevirt/kubevirt/pkg/instancetype
===================================================================================================================================
Random Seed: 1686754977
 
Will run 1 of 117 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
• [FAILED] [0.000 seconds]
Instancetype and Preferences Apply instancetype.Spec.Memory [It] should apply memory overcommit correctly to VMI
/home/lyarwood/redhat/devel/src/k8s/kubevirt/kubevirt/pkg/instancetype/instancetype_test.go:1120
 
  [FAILED] Expected
      <int64>: 512000000
  not to equal
      <int64>: 512000000
  In [It] at: /home/lyarwood/redhat/devel/src/k8s/kubevirt/kubevirt/pkg/instancetype/instancetype_test.go:1125 @ 06/14/23 16:02:59.526
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
 
Summarizing 1 Failure:
  [FAIL] Instancetype and Preferences Apply instancetype.Spec.Memory [It] should apply memory overcommit correctly to VMI
  /home/lyarwood/redhat/devel/src/k8s/kubevirt/kubevirt/pkg/instancetype/instancetype_test.go:1125
```

**What you expected to happen**:

`VirtualMachineInstance` or `virt-handler` pod should be updated with a smaller amount of memory given the overcommit percentage provided.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by vladikr**
**What this PR does / why we need it**:
As mentioned in #9912 the overcommit value is not calculated correctly.
This fix makes the value actually calculated.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9912

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: tests/instancetype_test.go [hunk 1]
```diff
@@ -240,7 +240,8 @@ var _ = Describe("[crit:medium][vendor:cnv-qe@redhat.com][level:component][sig-c
 			Expect(err).ToNot(HaveOccurred())
 
 			Expect(*vmi.Spec.Domain.Memory.Guest).To(Equal(instancetype.Spec.Memory.Guest))
-			expectedOverhead := instancetype.Spec.Memory.Guest.Value() * (1 - int64(instancetype.Spec.Memory.OvercommitPercent)/int64(100))
+			expectedOverhead := int64(float32(instancetypeSpec.Memory.Guest.Value()) * (1 - float32(instancetypeSpec.Memory.OvercommitPercent)/100))
```
Comment (lyarwood) [inline tests/instancetype_test.go:243]: `int64(float32(instancetype.Spec.Memory.Guest.Value())` and below.

**Review by lyarwood — CHANGES_REQUESTED** [review]

File: tests/instancetype_test.go (hunk 1 above)
Comment (vladikr) [reply tests/instancetype_test.go]: Done

**Comment by lyarwood** [comment]
/lgtm

```
./cluster-up/kubectl.sh apply -f - <<EOF
---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineInstancetype
metadata:
  name: overcommit
spec:
  cpu:
    guest: 1
  memory:
    guest: 128Mi
    overcommitPercent: 15
EOF

./cluster-up/virtctl.sh create vm --instancetype virtualmachineinstancetype/overcommit \
                    --volume-containerdisk name:cirros,src:registry:5000/kubevirt/cirros-container-disk-demo:devel \
                    --name cirros | ./cluster-up/kubectl.sh apply -f -

./cluster-up/kubectl.sh get vmi/cirros -o json | jq .spec.domain.memory,.spec.domain.resources
selecting podman as container runtime
{
  "guest": "128Mi"
}
{
  "requests": {
    "memory": "114085072"
  }
}
```

**Review by jean-edouard — COMMENTED** [review]
/approve
It would probably be best to use static values in the tests instead of redoing the exact same math as the main code does, but that could be addressed separately.
