### PR TITLE
virt-operator: Configure client rate limiting

### LINKED ISSUE #15835: virt-operator: error retrieving resource lock openshift-cnv/virt-operator: client rate limiter Wait returned an error: context deadline exceeded
/sig compute
/area operator
/assign

/cc @xpivarc 

**What happened**:

`virt-operator` hit the client rate limiter in the following downstream OpenShift periodic test lane during an early rehearsal of v4.21.0 using KubeVirt main (2f92d8ac0c5a2f2e2281fd6da4781eca9d471697).

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/69955/rehearse-69955-periodic-ci-openshift-ovn-kubernetes-release-4.21-periodics-e2e-metal-ipi-ovn-bgp-virt-ipv4/1975452464802959360

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/69955/rehearse-69955-periodic-ci-openshift-ovn-kubernetes-release-4.21-periodics-e2e-metal-ipi-ovn-bgp-virt-ipv4/1975452464802959360/artifacts/e2e-metal-ipi-ovn-bgp-virt-ipv4/gather-extra/artifacts/pods/openshift-cnv_virt-operator-6bd67758f-6l945_virt-operator_previous.log

```
2025-10-07T08:46:25.015595792Z E1007 08:46:25.014729       1 leaderelection.go:429] Failed to update lock optimistically: Put "[https://172.30.0.1:443/apis/coordination.k8s.io/v1/namespaces/openshift-cnv/leases/virt-operator](https://172.30.0.1/apis/coordination.k8s.io/v1/namespaces/openshift-cnv/leases/virt-operator)": context deadline exceeded, falling back to slow path
2025-10-07T08:46:25.015595792Z E1007 08:46:25.014963       1 leaderelection.go:436] error retrieving resource lock openshift-cnv/virt-operator: client rate limiter Wait returned an error: context deadline exceeded
2025-10-07T08:46:25.015595792Z I1007 08:46:25.014999       1 leaderelection.go:297] failed to renew lease openshift-cnv/virt-operator: context deadline exceeded
```

**What you expected to happen**:

virt-operator shouldn't hit this rate limiter during normal operations, if it does we need to consider raising the default burst and qps values as we have elsewhere.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

https://github.com/openshift/release/pull/69955#issuecomment-3377905262

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### LINKED ISSUE #16490: virt-operator: Default client rate limits cause slow instancetype/preference updates on generation bumps
**What happened**:

When the KubeVirt CR spec is modified (causing a generation bump), virt-operator updates the `kubevirt.io/generation` annotation on all 114+ instancetypes and preferences. These updates are subject to the default Kubernetes client-go rate limiter (5 QPS with burst of 10), which results in:

- First ~8-10 updates complete quickly (~8ms each, using burst bucket)
- Remaining 106+ updates are rate-limited to exactly 200ms each (5 QPS)
- **Total time: ~22 seconds** just to update generation annotations

This significantly extends the KubeVirt reconcile cycle. In a recent test failure investigation, we observed:
- Reconcile start: 11:58:34
- Instancetype updates start: 12:00:16
- Instancetype updates complete: 12:00:38 (22 seconds later)
- Status update success: 12:00:38

The 22-second delay was the second-largest bottleneck in a ~2 minute reconcile cycle (after an 85-second DaemonSet rollout).

**What you expected to happen**:

Updating metadata annotations on 114 resources should not take 22 seconds. Expected behavior would be:
1. Either use a higher QPS/burst configuration for virt-operator's Kubernetes client
2. Or batch update instancetypes/preferences to avoid sequential API calls
3. Or skip updating instancetypes/preferences when the generation change doesn't affect them

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy KubeVirt with default instancetypes/preferences (114 resources)
2. Modify any KubeVirt CR spec field (e.g., `virtualMachineInstancesPerNode: 10`)
3. Observe virt-operator logs for instancetype/preference updates
4. Note the ~200ms interval between updates after the initial burst

Expected log pattern:
```
12:00:16.873523Z - instancetype cx1.2xlarge updated      (8ms)
12:00:16.882267Z - instancetype cx1.2xlarge1gi updated   (9ms)
...8-10 fast updates...
12:00:17.025958Z - instancetype cx1.medium updated       (200ms)
12:00:17.226590Z - instancetype cx1.medium1gi updated    (200ms)
12:00:17.426684Z - instancetype cx1.xlarge updated       (200ms)
...106 updates at 200ms intervals...
```

**Root Cause Analysis**:

**Code location**: `pkg/virt-operator/resource/apply/instancetypes.go:41-72`

Every reconcile that changes the KubeVirt generation:

1. `injectOperatorMetadata()` stamps all instancetypes/preferences with new generation annotation
2. `equality.Semantic.DeepEqual()` comparison detects annotation mismatch ("36" vs "37")
3. Triggers `Update()` API call for each resource
4. Each Update() is subject to client-go rate limiting (default: 5 QPS, 10 burst)

**Client configuration**: `staging/src/kubevirt.io/client-go/kubecli/kubecli.go`
- Uses `clientcmd.BuildConfigFromFlags()` which applies default rate limits
- No explicit QPS/Burst configuration for virt-operator

**Impact**:

- **Slow reconcile loops**: Any KubeVirt spec change triggers 22+ seconds of instancetype updates
- **Test flakiness**: Tests expecting fast reconciles may timeout
- **Delayed rollouts**: Infrastructure changes blocked behind instancetype updates
- **Scales poorly**: With more custom instancetypes, the delay increases linearly

**Additional context**:

This is particularly problematic because:

1. **Generation annotations are metadata-only**: These updates don't change actual instancetype specs
2. **All resources updated on ANY change**: Even changes unrelated to instancetypes trigger all 114+ updates
3. **Sequential processing**: Updates happen one-by-one in a for loop
4. **Rate limiting is client-side**: The API server isn't the bottleneck - the client is throttling itself

**Potential Solutions**:

1. **Increase virt-operator client QPS/Burst**: Configure higher limits specifically for virt-operator
   - Example: QPS: 50, Burst: 100 (similar to controllers like kube-controller-manager)

2. **Batch updates**: Use `Patch()` with server-side apply or implement concurrent updates with rate limiting

3. **Skip unnecessary updates**: Only update instancetype/preference generation annotations when relevant spec changes occur

4. **Asynchronous updates**: Don't block reconcile completion on instancetype annotation updates

**Environment**:
- KubeVirt version: v1.7.0-26-g114d912ce2
- Kubernetes version: OpenShift 4.x
- Number of instancetypes: 58
- Number of preferences: 56
- Total resources updated: 114
- Observed reconcile delay: ~22 seconds for instancetype/preference updates

**Related Code References**:

- `pkg/virt-operator/resource/apply/instancetypes.go:66` - Sequential Update() calls
- `pkg/virt-operator/resource/apply/reconcile.go:103` - Generation annotation injection
- `staging/src/kubevirt.io/client-go/kubecli/kubecli.go:455-457` - Client configuration

### PR DESCRIPTION
**Pull request by lyarwood**
#### Before this PR:
The virt-operator component did not configure rate limiting for its Kubernetes API client calls. This resulted in very slow reconciliation times when updating generation annotations on large numbers of instancetypes and preferences. For example, updating 114+ objects took approximately 22 seconds to complete.

#### After this PR:
The virt-operator now uses configurable rate limiting for its Kubernetes API client, with defaults (200 QPS / 400 burst) matching virt-controller and virt-api. This reduces the update time for 114+ instancetypes and preferences from ~22 seconds to under 1 second.

Rate limits can be tuned via command line flags (`--client-qps`, `--client-burst`) or environment variables (`VIRT_OPERATOR_CLIENT_QPS`, `VIRT_OPERATOR_CLIENT_BURST`) to accommodate different cluster sizes and API server capacities without rebuilding.

### References
- Fixes #16490
- Fixes #15835

### Why we need it and why it was done in this way
The following tradeoffs were made:
- Used the same default rate limiting values (200 QPS / 400 burst) as virt-controller and virt-api for consistency across KubeVirt components
- Applied rate limiting at the client configuration level to affect all API calls made by virt-operator
- Made rate limits configurable via flags and environment variables to allow tuning for different deployment scenarios without code changes
- Used flag precedence over environment variables over defaults to provide flexibility in configuration

The following alternatives were considered:
- Hardcoded values only: Rejected because different cluster sizes and API server capacities may need different rate limits
- Different default QPS/burst values: Rejected in favor of consistency with other KubeVirt components
- No rate limiting configuration: This was the status quo, but it led to poor performance when reconciling large numbers of objects

The changes maintain consistency with how other KubeVirt components configure their Kubernetes clients, while adding runtime configurability to handle diverse deployment scenarios.

Links to places where the discussion took place: 

### Special notes for your reviewer

The implementation consists of two commits:

**First commit** (9bc73accf7): Initial rate limiting configuration
1. Added `DefaultVirtOperatorQPS` and `DefaultVirtOperatorBurst` constants in `pkg/virt-config/virt-config.go:85-86`
2. Configured the rate limiter when creating the REST config in `pkg/virt-operator/application.go:144-146`
3. Switched from `GetKubevirtClient()` to `GetKubevirtClientFromRESTConfig(config)` to use the rate-limited config

**Second commit** (f7d2da2d42): Add runtime configurability
1. Added `clientQPS` and `clientBurst` struct fields to `VirtOperatorApp` in `pkg/virt-operator/application.go:109-110`
2. Added `getClientRateLimiterConfig()` helper function that implements configuration precedence (flags > env vars > defaults) with validation in `pkg/virt-operator/application.go:113-157`
3. Added `--client-qps` and `--client-burst` command line flags in `pkg/virt-operator/application.go:523-526`
4. Updated `Execute()` to use the configuration helper and log the final rate limit values in `pkg/virt-operator/application.go:194-196`
5. Added comprehensive test coverage (17 test cases) in `pkg/virt-operator/application_test.go:89-233`

The configuration approach follows these principles:
- Flags take precedence over environment variables
- Environment variables take precedence over defaults
- Invalid values (negative, zero, non-numeric) trigger warnings and fall back to defaults
- Defaults match virt-controller and virt-api for consistency

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed (fully backwards compatible - defaults preserve existing behavior)
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
virt-operator now configures client rate limiting (default: 200 QPS / 400 burst) to improve reconciliation performance when processing large numbers of objects. Rate limits can be customized via --client-qps and --client-burst flags or VIRT_OPERATOR_CLIENT_QPS and VIRT_OPERATOR_CLIENT_BURST environment variables.
```

### CODE REVIEW

**Comment by lyarwood** [comment]
Nice, this speeds up the operator test lane by 20mins!

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/16491/pull-kubevirt-e2e-k8s-1.34-sig-operator/2009316484869787648 - Test started yesterday at 6:01 PM passed after 1h31m54s.

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.34-sig-operator - Avg ~1h50m

**Review by xpivarc — COMMENTED** [review]
/approve
/hold
Can we at least expose flags for the QPS/Burst?

**Comment by lyarwood** [comment]
@xpivarc @0xFelix - I've made these [limits configurable](https://github.com/kubevirt/kubevirt/pull/16491/commits/1e1fa9154e7ca540838600ec79c9671481db4d61) as [suggested](https://github.com/kubevirt/kubevirt/pull/16491#pullrequestreview-3670782139). Can you review again and unhold if you think it's ready?

**Review by 0xFelix — COMMENTED** [review]
Is it common to have both flags and env vars for the settings?

**Comment by lyarwood** [comment]
> Is it common to have both flags and env vars for the settings?

@0xFelix I think we typically provide env based configurables but Lubo asked for a flag so I assumed he wanted both? I can't see an issue providing both tbh.

File: pkg/virt-operator/application.go [hunk 1]
```diff
@@ -103,6 +105,55 @@ type VirtOperatorApp struct {
...
+
+	// Validate final values
+	if qps <= 0 {
+		log.Log.Warningf("Invalid QPS value %f, using default", qps)
+		qps = virtconfig.DefaultVirtOperatorQPS
+	}
+	if burst <= 0 {
+		log.Log.Warningf("Invalid Burst value %d, using default", burst)
+		burst = virtconfig.DefaultVirtOperatorBurst
+	}
```
Comment (0xFelix) [inline pkg/virt-operator/application.go]: If cases could be merged?

File: pkg/virt-operator/application_test.go [hunk 2]
```diff
@@ -83,3 +85,149 @@ var _ = Describe("Reinitialization conditions", func() {
 		Entry("when ServiceMonitor is removed and PrometheusRule is introduced", true, false, false, true, true, false, true),
 	)
 })
+
+var _ = Describe("Client rate limiter configuration", func() {
+	AfterEach(func() {
+		// Clean up environment variables after each test
+		os.Unsetenv("VIRT_OPERATOR_CLIENT_QPS")
```
Comment (0xFelix) [inline pkg/virt-operator/application_test.go]: Use consts for the envs in this file?

**Comment by lyarwood** [comment]
/hold cancel

@0xFelix comments [addressed](https://github.com/kubevirt/kubevirt/compare/68f43d0850d1e9af994eaccf8fbc2952933eb590..9be59d2ef99b22fca2d2bd8857bb00b6c1168686) would you mind taking another look?
