### PR TITLE
Fix flaky "[ref_id:1182]Probes for readiness should succeed [test_id:1202]with working HTTP probe and http server, no ip family is specified"

### LINKED ISSUE #5316: Flaky test "[ref_id:1182]Probes for readiness should succeed [test_id:1202]with working HTTP probe and http server, no ip family is specified"
**What happened**:
Failed twice:
 https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.18/1369425882703204352
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19/1370183121533669376

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
Currently the network readiness probes tests flow:
- Creating a VM with TCP/Network readiness probe.
- Wait for the VM to start.
- Start TCP/HTTP probe server inside VM.
- Assert on virt-launcher pod and VM not ready state; both virt-launcher pod have Condition PodReady==False
  or Condition Ready absence.
- Assert on virt-launcher pod and VM ready state; both virt-launcher pod and VM has Condition Ready==True.

Asserting pod and VM not-ready state after invoking probe server is start command might introduce flakes to those tests.
There might be a race between the time the probe server inside the VM is ready and the assertion on the pod/VM
Condition Ready sampling.

Currently both readiness and liveness tests the permutations of TCP/HTTP probe with blankIPFamily/IPv4/IPv6 address.
BlankIPFamily is passing en empty string.
Both IPv4 and blankIPFamily cases are treated the same and are basically the same test.
E2E tests are expensive and there is no actual benefit in testing both cases.
Moreover having both tests while CI isn't in its best shape cause more flakiness, the test:
`[test_id:1202]with working HTTP probe and http server, no ip family is specified`
is quarantined while the IPv4 version inst.

This PR changes the flow of these tests by moving the pod and VM not ready state assertion to be checked
before invoking probe server start command.
Also removes removes probes with "no IP family specified" tests cases.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5316

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ormergi** [comment]
@EdDev could you please take another look?

File: tests/network/probes.go [hunk 1]
```diff
@@ -84,21 +83,19 @@ var _ = SIGDescribe("[ref_id:1182]Probes", func() {
...
 
+				assertPodNotReady(virtClient, vmi)
+
+				// pod is not ready until our probe contacts the server
 				By("Starting the server inside the VMI")
 				serverStarter(vmi, readinessProbe, 1500)
 			}
 
-			// pod is not ready until our probe contacts the server
-			assertPodNotReady(virtClient, vmi)
```
Comment (oshoval) [inline tests/network/probes.go:92]: i am little confused,
IPv6 as well line 81 creates createReadyCirrosVMIWithReadinessProbe
which won't be ready until the server is started ?

if so, then u need to start the server on ipv6 as well don't you?
if the above is wrong, then maybe there will be still a flake on ipv4 even its moved to line 86,
because the pod might be ready without waiting for anything?

File: tests/network/probes.go [hunk 2]
```diff
@@ -84,21 +83,19 @@ var _ = SIGDescribe("[ref_id:1182]Probes", func() {
 				By("Specifying a VMI with a readiness probe")
 				vmi = createReadyCirrosVMIWithReadinessProbe(virtClient, readinessProbe)
 
+				assertPodNotReady(virtClient, vmi)
+
+				// pod is not ready until our probe contacts the server
```
Comment (oshoval) [inline tests/network/probes.go:88]: comment position is pretty confusing now, 
also should it be VM ? 
and maybe can be updated to explain better (depends on the answer of the 2nd comment)

File: tests/network/probes.go [hunk 3]
```diff
@@ -80,17 +80,19 @@ var _ = SIGDescribe("[ref_id:1182]Probes", func() {
 
 				By("Specifying a VMI with a readiness probe")
 				vmi = createReadyCirrosVMIWithReadinessProbe(virtClient, readinessProbe)
+
+				assertPodNotReady(virtClient, vmi)
```
Comment (EdDev) [inline tests/network/probes.go]: > - IPv6 path
>   The assersion is checked after the VMI is created as before
>   it just moved closer to the VMI creation.

What really matters here is that no logic has been changed and the race has not been resolved for IPv6.
Anything else is just distracting.

**Review by EdDev — CHANGES_REQUESTED** [review]
> Due to the fact that we create the backend for the prob
> before the VMI is up, the assertion for pod/VM not-ready
> state is redundant for IPv6 path.

It is not redundant, it is incorrect.
This is the reason you drop it.

I would also suggest adding a note about what is lost here: We do not check that the probe with IPv6 is showing the right state when the service is not up.
However, we do have other tests that check it (I think), so you can reason why it is fine to drop it.

> tests, network probes: Remove blankIPFamily tests 

There are several typos in the commit: `basicity`, `en`. Please check all your commits for typos.
You also repeat yourself in the commit.

> 
> Moreover having both tests while CI isn't in its best shape
> cause more flakiness, the test:
> [test_id:1202]with working HTTP probe and http server, no ip family is specified
> is quarantined while the IPv4 version inst.

I do not think we need to confuse the future readers with this. It is enough to say we are not interested to check a single test twice. I would drop this section.

**Comment by ormergi** [comment]
k8s-1.19 lane
```
[sig-network] [Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance expand_more6m5s | [sig-network] [Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance expand_more | 6m5s
-- | -- | --
[sig-network] [Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance expand_more | 6m5s
[sig-network] [Serial][rfe_id:150][crit:high][vendor:cnv-qe@redhat.com][level:component]Networkpolicy when three cirros VMs with default networking are started and serverVMI start an HTTP server on port 80 and 81 and connectivity between VMI/s is blocked by Default-deny networkpolicy [test_id:1511] should fail to reach serverVMI from clientVMI expand_more | [sig-network] [Serial][rfe_id:150][crit:high][vendor:cnv-qe@redhat.com][level:component]Networkpolicy when three cirros VMs with default networking are started and serverVMI start an HTTP server on port 80 and 81 and connectivity between VMI/s is blocked by Default-deny networkpolicy [test_id:1511] should fail to reach serverVMI from clientVMI expand_more
[sig-network] [Serial][rfe_id:150][crit:high][vendor:cnv-qe@redhat.com][level:component]Networkpolicy when three cirros VMs with default networking are started and serverVMI start an HTTP server on port 80 and 81 and connectivity between VMI/s is blocked by Default-deny networkpolicy [test_id:1511] should fail to reach serverVMI from clientVMI expand_more
```
On both tests VMI's did not created on time, their status was Scheduling/Pending

/retest

**Comment by ormergi** [comment]
> I would also suggest adding a note about what is lost here: We do not check that the probe with IPv6 is showing the right state when the service is not up.
> However, we do have other tests that check it (I think), so you can reason why it is fine to drop it.
> 

@EdDev Well for IPv6 tests it seems it never checked that the probe show the right state when the service is not up.
First we create the probe backend pod, which is basically a pod that runs tcp/http service that always report ready.
Then we create the VMI with a probe targeted to the backend pod service, as long the backend pod is alive
the VMI state reported as ready.
With this implementation there is no scenario where the VMI and probe backend are up but the service isnt -> VM reports not ready

I can push another commit or on a follow-up PR, to change the probe service implementation so we could control
when the service is up from the tests.
Then we could test the the VM report the right state according to the IPv6 probe service state.

> > tests, network probes: Remove blankIPFamily tests
> 
> There are several typos in the commit: `basicity`, `en`. Please check all your commits for typos.
> You also repeat yourself in the commit.
> 
> > Moreover having both tests while CI isn't in its best shape
> > cause more flakiness, the test:
> > [test_id:1202]with working HTTP probe and http server, no ip family is specified
> > is quarantined while the IPv4 version inst.
> 
> I do not think we need to confuse the future readers with this. It is enough to say we are not interested to check a single test twice. I would drop this section.

Sorry for this the commit message was messed up I fixed it.

**Review by EdDev — APPROVED** [review]
Thank you!

File: tests/network/probes.go [hunk 4]
```diff
@@ -80,8 +80,6 @@ var _ = SIGDescribe("[ref_id:1182]Probes", func() {
 
 				By("Specifying a VMI with a readiness probe")
 				vmi = createReadyCirrosVMIWithReadinessProbe(virtClient, readinessProbe)
-
```
Comment (AlonaKaplan) [inline tests/network/probes.go]: I'm ok with removing this assert. But if we want to be on the safe side, why not running an empty pod (with "while true sleep 1") and running the probe server on the pod just after the assert?

Comment (ormergi) [reply tests/network/probes.go]: @AlonaKaplan We also mentioned it on this thread https://github.com/kubevirt/kubevirt/pull/5317#issuecomment-813055162
If we want to be on the safe side we need to change the service inside the "backend pod" (netcat server)
so we could configure from the tests when it will actually work.
Then we can do the same flow as with the IPv4 test:
- Spin up VM with IPv6 readiness probe targeted to external service
- Assert that the VM&virt-launcher pod are not **not ready**
- Enable the service on the backend pod
- Asset VM&virt-launcher pod are **ready**
- 
I am planing to do this on a following PR, do you prefer to have it on this PR?

Comment (EdDev) [reply tests/network/probes.go]: There should be tests that check the probe fails when there is no service/ip, that should be enough.
