### PR TITLE
bazel-images: Split image targets per architecture

### LINKED ISSUE #12843: some tags in the 1.4 alpha release default to s390x on x86 hosts
**What happened**:
it seems like the newly created alpha images for kubevirt point to s390x by default
```
# docker pull quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
...
Digest: sha256:6997b5c464965939179f3a0636f5a28499d6c286b0865032673120593c9b111f
Status: Downloaded newer image for quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
# docker images | grep exportproxy
quay.io/kubevirt/virt-exportproxy                                                                       v1.4.0-alpha.0              a7ed475a0554   54 years ago    71.7MB
# TAG=$(docker create a7ed475a0554)
# docker cp $TAG:/usr/bin/virt-exportproxy .
# file virt-exportproxy 
virt-exportproxy: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, BuildID[sha1]=3886f3dc9ff0405009ffeab476ccd08f2560a5c0, for GNU/Linux 3.2.0, stripped
```
(this is done on an x86 machine)

**What you expected to happen**:
default tags are x86 / at least default to x86 if the host is

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
this is causing consumers of 1.4 to fail
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/3099/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp/1834458255884029952/artifacts/hco-e2e-operator-sdk-gcp/deploy-cr/artifacts/kubevirt-must-gather/quay-io-kubevirt-must-gather-sha256-290c9cb1ccd736c5f87cbea9400dea2870cbfccedd0a92900a4fa28876d90888/namespaces/kubevirt-hyperconverged/pods/virt-exportproxy-f5b4789f-n2wgr/exportproxy/exportproxy/logs/current.log

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jschintag**
### What this PR does
Before this PR:
Images not implemented by an architecture would result in broken "amd64" images, where the binary is the target arch, but the base image is amd64, even though the image should not have been built for the target-arch in the first place.
After this PR:
We only build image for an architecture if it is enabled.

Fixes #12843

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

Testing the PR requires to delete the kubevirt volume containing the bazel cache, as otherwise old images might be pulled into the manifest instead. Please run:
```
podman volume rm kubevirt
```
before testing.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Fixed additional broken amd64 image in some image manifests
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
/cc @zhlhahaha 

Can you check which images are needed for arm64?

**Comment by zhlhahaha** [comment]
> /cc @zhlhahaha
> 
> Can you check which images are needed for arm64?

I may not have time on this weekend, and I will review it on the next Monday.

File: hack/push-container-manifest.sh [hunk 1]
```diff
@@ -34,6 +34,9 @@ function podman_push_manifest() {
     ${KUBEVIRT_CRI} manifest create ${DOCKER_PREFIX}/${image}:${DOCKER_TAG}
     for ARCH in ${BUILD_ARCH//,/ }; do
         FORMATED_ARCH=$(format_archname ${ARCH})
+        if [ ! -f ${DIGESTS_DIR}/${FORMATED_ARCH}/bazel-bin/push-$image.digest ]; then
```
Comment (zhlhahaha) [inline hack/push-container-manifest.sh:37]: Shall we apply the same logic on the function `docker_push_manifest`?

Comment (jschintag) [reply hack/push-container-manifest.sh:37]: Yes, absolutely. I just don't use docker, so i forgot. I will add it there as well.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

File: hack/bazel-push-images.sh [hunk 2]
```diff
@@ -29,31 +29,41 @@ default_targets="
...
     vm-killer
-    winrmcli
     sidecar-shim
-    network-slirp-binding
-    network-passt-binding
 "
 
+case ${ARCHITECTURE} in
+"s390x" | "crossbuild-s390x") ;;
+#"aarch64" | "crossbuild-aarch64")
```
Comment (brianmcarey) [inline hack/bazel-push-images.sh:40]: @jschintag is this a leftover or is this something we want to enable?

Comment (jschintag) [reply hack/bazel-push-images.sh:40]: I mainly put it there in case there was something special we want to do with arm, but i can remove it as well.

Comment (brianmcarey) [reply hack/bazel-push-images.sh:40]: Lets remove it for now just to avoid confusion.

Comment (jschintag) [reply hack/bazel-push-images.sh]: Done

**Review by brianmcarey — COMMENTED** [review]
/lgtm 

thanks @jschintag

File: BUILD.bazel [hunk 3]
```diff
@@ -191,7 +191,54 @@ config_setting(
 )
 
 container_bundle(
-    name = "build-other-images",
+    name = "build-other-images_s390x",
+    images = {
```
Comment (xpivarc) [inline BUILD.bazel:195]: I think  `select` should work here and it would look more like Bazel. Also it will be clear that if one modifies one arch it needs to modify other...

Comment (xpivarc) [reply BUILD.bazel:195]: @jschintag we should remove the usage of default, ARM might be messed up in this way as well.

Comment (jschintag) [reply BUILD.bazel:195]: Select was my first choice here as well, unfortunately bazel did not accept it in this field...

Comment (xpivarc) [reply BUILD.bazel:195]: I'll have a look why is this the case later but it should work afaik

File: BUILD.bazel [hunk 4]
```diff
@@ -191,7 +191,54 @@ config_setting(
...
+        # Customized container-disk images
+        "$(container_prefix)/$(image_prefix)fedora-with-test-tooling-container-disk:$(container_tag)": "//containerimages:fedora-with-test-tooling",
+        # testing images
+        "$(container_prefix)/$(image_prefix)vm-killer:$(container_tag)": "//images/vm-killer:vm-killer-image",
+    },
+)
+
+container_bundle(
+    name = "build-other-images_aarch64",
+    images = {
```
Comment (xpivarc) [inline BUILD.bazel:211]: Can we define a variable such as
```
standard_images = {....}
```

and then use it for the archs...
```
container_bundle(
    name = "build-other-images_aarch64",
    images =  standard_images,
)
....
```

File: hack/bazel-push-images.sh [hunk 5]
```diff
@@ -29,31 +29,39 @@ default_targets="
...
-    disks-images-provider
-    nfs-server
     vm-killer
-    winrmcli
     sidecar-shim
-    network-slirp-binding
-    network-passt-binding
 "
 
+case ${ARCHITECTURE} in
```
Comment (xpivarc) [inline hack/bazel-push-images.sh:38]: I am not sure I understand this change.

File: hack/push-container-manifest.sh (hunk 1 above)
Comment (xpivarc) [inline hack/push-container-manifest.sh:37]: I would sleep better if we make this explicit.

**Review by xpivarc — COMMENTED** [review]
Just few asks.

File: BUILD.bazel (hunk 4 above)
Comment (jschintag) [reply BUILD.bazel:211]: I'm afraid i'm not an expert with bazel and what i find with google regarding variables just points to build variables from env. If there is an option to make a placeholder/variable that would of course make this change much more simple.

File: hack/bazel-push-images.sh (hunk 5 above)
Comment (jschintag) [reply hack/bazel-push-images.sh:38]: Since aarch64/x86_64 share the image list, the default values are already all the images we support currently for s390x. Therefore this case simply does nothing for s390x and adds the original images otherwise.
I choose a select instead of an if here because this makes it easier to expand for other arches if needed and reflects the use of select statements in the go code for arch specific cases as well.

File: hack/push-container-manifest.sh (hunk 1 above)
Comment (jschintag) [reply hack/push-container-manifest.sh:37]: I'm afraid this would make this script a lot bigger and forces us to either redefine the images from `bazel-push-images.sh` here or move them to a new script we source.
This change is much more simple instead.
Though to be fair it comes with the downside that if the cache already has a digest for an image you no longer want you need to manually delete it...

File: BUILD.bazel (hunk 4 above)
Comment (xpivarc) [reply BUILD.bazel:211]:
```
diff --git a/BUILD.bazel b/BUILD.bazel
index 9d2ce692bb..f417e91d3a 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -190,10 +190,8 @@ config_setting(
     values = {"define": "release=true"},
 )
 
-container_bundle(
-    name = "build-other-images",
-    images = {
-        # cmd images
+
+standard_images = {        # cmd images
         "$(container_prefix)/$(image_prefix)sidecar-shim:$(container_tag)": "//cmd/sidecars:sidecar-shim-image",
         "$(container_prefix)/$(image_prefix)example-hook-sidecar:$(container_tag)": "//cmd/sidecars/smbios:example-hook-sidecar-image",
         "$(container_prefix)/$(image_prefix)example-disk-mutation-hook-sidecar:$(container_tag)": "//cmd/sidecars/disk-mutation:example-disk-mutation-hook-sidecar-image",
@@ -216,7 +214,12 @@ container_bundle(
         "$(container_prefix)/$(image_prefix)nfs-server:$(container_tag)": "//images/nfs-server:nfs-server-image",
         "$(container_prefix)/$(image_prefix)vm-killer:$(container_tag)": "//images/vm-killer:vm-killer-image",
         "$(container_prefix)/$(image_prefix)winrmcli:$(container_tag)": "//images/winrmcli:winrmcli-image",
-    },
+}
+
+
+container_bundle(
+    name = "build-other-images",
+    images = standard_images,
 )
```
Basically I am asking for this, the `standard_images` can then be used across multiple targets (x86, amd,...).  You can go as far as having a dict for "cmd images" and such and than merge them. It just makes this easier to maintain and spot the difference

File: hack/push-container-manifest.sh (hunk 1 above)
Comment (xpivarc) [reply hack/push-container-manifest.sh:37]: Can you share how does this fail today?

File: hack/bazel-push-images.sh (hunk 5 above)
Comment (xpivarc) [reply hack/bazel-push-images.sh:38]: Ok, so s390x doesn't support this, thanks I was not synced...

File: BUILD.bazel (hunk 4 above)
Comment (jschintag) [reply BUILD.bazel:211]: Ok, thank you for the explanation, i will try it out.

Comment (jschintag) [reply BUILD.bazel:211]: I have pushed https://github.com/kubevirt/kubevirt/commit/6cbea391b96ad2cd11a9744c82e75f0a938ade64 to a new branch for testing.
What i found so far, i can use the variable as is for s390x, since it contains all the images. However i'm not sure how to re-use it for x86 and aarch64, since i need to add additional images. All i'm getting is syntax errors, as it seems to be expecting a new image definition and not a variable:
```
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:214:35: syntax error at ',': expected :
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:242:35: syntax error at ',': expected :
ERROR: /root/go/src/kubevirt.io/kubevirt/vendor/mvdan.cc/sh/v3/cmd/shfmt/BUILD.bazel:21:10: While resolving toolchains for target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt: invalid registered toolchain '//:py_toolchain': no such target '//:py_toolchain': target 'py_toolchain' not declared in package '' defined by /root/go/src/kubevirt.io/kubevirt/BUILD.bazel
ERROR: Analysis of target '//vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt' failed; build aborted:
INFO: Elapsed time: 0.196s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk ... (12 packages)
    Fetching @local_jdk; fetching
make: *** [Makefile:212: format] Error 1
```

Comment (xpivarc) [reply BUILD.bazel:211]: @jschintag This should help
```
diff --git a/BUILD.bazel b/BUILD.bazel
index 9d2ce692bb..a98aa93a5e 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -190,9 +190,8 @@ config_setting(
     values = {"define": "release=true"},
 )
 
-container_bundle(
-    name = "build-other-images",
-    images = {
+
+defualt_images = {
         # cmd images
         "$(container_prefix)/$(image_prefix)sidecar-shim:$(container_tag)": "//cmd/sidecars:sidecar-shim-image",
         "$(container_prefix)/$(image_prefix)example-hook-sidecar:$(container_tag)": "//cmd/sidecars/smbios:example-hook-sidecar-image",
@@ -215,8 +214,14 @@ container_bundle(
         "$(container_prefix)/$(image_prefix)disks-images-provider:$(container_tag)": "//images/disks-images-provider:disks-images-provider-image",
         "$(container_prefix)/$(image_prefix)nfs-server:$(container_tag)": "//images/nfs-server:nfs-server-image",
         "$(container_prefix)/$(image_prefix)vm-killer:$(container_tag)": "//images/vm-killer:vm-killer-image",
-        "$(container_prefix)/$(image_prefix)winrmcli:$(container_tag)": "//images/winrmcli:winrmcli-image",
-    },
+}
+
+
+load("@bazel_skylib//lib:dicts.bzl", "dicts")
+
+container_bundle(
+    name = "build-other-images",
+    images = dicts.add(defualt_images,{"$(container_prefix)/$(image_prefix)winrmcli:$(container_tag)": "//images/winrmcli:winrmcli-image"}),
 )

```

Comment (xpivarc) [reply BUILD.bazel:211]: Note that I have `defualt_images` variable defined and then I can just use it in function as `dicts.add(default_images, ...)`

Comment (jschintag) [reply BUILD.bazel]: Thank you @xpivarc that was the missing link. I have pushed my changes with the variable to this PR.

File: hack/push-container-manifest.sh (hunk 1 above)
Comment (xpivarc) [reply hack/push-container-manifest.sh:37]: Ah, I see. I was under the expression we list the images per arch but now I see we list all images and then have assumption to push them for all arch...

File: BUILD.bazel [hunk 6]
```diff
@@ -190,33 +190,84 @@ config_setting(
...
+            "$(container_prefix)/$(image_prefix)virtio-container-disk:$(container_tag)": "//containerimages:virtio-container-disk-image",
+            # Kernel boot container
+            "$(container_prefix)/$(image_prefix)alpine-ext-kernel-boot-demo:$(container_tag)": "//containerimages:alpine-ext-kernel-boot-demo-container",
+            # Customized container-disk images
+            "$(container_prefix)/$(image_prefix)alpine-with-test-tooling-container-disk:$(container_tag)": "//containerimages:alpine-with-test-tooling",
+            "$(container_prefix)/$(image_prefix)fedora-realtime-container-disk:$(container_tag)": "//containerimages:fedora-realtime",
+            # testing images
+            "$(container_prefix)/$(image_prefix)disks-images-provider:$(container_tag)": "//images/disks-images-provider:disks-images-provider-image",
+            "$(container_prefix)/$(image_prefix)nfs-server:$(container_tag)": "//images/nfs-server:nfs-server-image",
+            "$(container_prefix)/$(image_prefix)winrmcli:$(container_tag)": "//images/winrmcli:winrmcli-image",
```
Comment (xpivarc) [inline BUILD.bazel:238]: These are the same with arm, right? Please just extract them to something like `build_other_images_arm_x86 = {....}`

**Review by xpivarc — COMMENTED** [review]
Just one last ask.

File: BUILD.bazel (hunk 6 above)
Comment (jschintag) [reply BUILD.bazel:238]: Sure, i thought about that as well. I'll push those changes as soon as i finish testing them locally.

Comment (jschintag) [reply BUILD.bazel]: Done

File: BUILD.bazel [hunk 7]
```diff
@@ -190,11 +190,25 @@ config_setting(
...
+    "$(container_prefix)/$(image_prefix)fedora-with-test-tooling-container-disk:$(container_tag)": "//containerimages:fedora-with-test-tooling",
+    # testing images
+    "$(container_prefix)/$(image_prefix)vm-killer:$(container_tag)": "//images/vm-killer:vm-killer-image",
+}
+
+build_other_images_aarch64_x86_64 = dicts.add(
+    build_other_images_default,
+    {
         # cmd images
-        "$(container_prefix)/$(image_prefix)sidecar-shim:$(container_tag)": "//cmd/sidecars:sidecar-shim-image",
```
Comment (xpivarc) [inline BUILD.bazel:197]: Thank you @jschintag, the diff is now so much clearer.

**Review by xpivarc — COMMENTED** [review]
/approve
/lgtm
@jschintag thank you
