### PR TITLE
virt-handler: Avoid spam filter by sending one graceful shutdown event

### LINKED ISSUE #15758: virt-handler: Graceful shutdown event spam results in the eventual shutdown event being dropped
/assign @lyarwood 
/sig compute

**What happened**:

Attempting to gracefully shutdown a VMI with a large `TerminationGracePeriodSeconds` set leads to the event recorder being overwhelmed with `Signaled Graceful Shutdown` events leading to the eventual and important `The VirtualMachineInstance was shut down.` event being dropped:

```
$ ./kubevirtci/cluster-up/kubectl.sh get events --sort-by=.lastTimestamp -w
[..]
0s          Normal    SuccessfulDelete             virtualmachine/lyarwood                               Stopped the virtual machine by deleting the virtual machine instance 0cb6622a-ae91-496d-8323-588d733bcfd6
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
0s          Normal    Killing                      pod/virt-launcher-lyarwood-rfbb5                      Stopping container guest-console-log
0s          Normal    Killing                      pod/virt-launcher-lyarwood-rfbb5                      Stopping container compute
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
```

**What you expected to happen**:

There's little value in the repeat `Signaled Graceful Shutdown` messages so a single event for the initial request should be enough.

```
$ ./kubevirtci/cluster-up/kubectl.sh get events --sort-by=.lastTimestamp -w
[..]
0s          Normal    SuccessfulDelete             virtualmachine/lyarwood                               Stopped the virtual machine by deleting the virtual machine instance f6de6a5e-bd64-4e5f-920c-8ef0a451b193
0s          Normal    Killing                      pod/virt-launcher-lyarwood-l7xjk                      Stopping container guest-console-log
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
0s          Normal    Killing                      pod/virt-launcher-lyarwood-l7xjk                      Stopping container compute
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    Stopped                      virtualmachineinstance/lyarwood                       The VirtualMachineInstance was shut down.
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
```

**How to reproduce it (as minimally and precisely as possible)**:

```
$ virtctl create vm  \
  --name lyarwood \
  --run-strategy RerunOnFailure \
  --instancetype u1.nano \
  --ssh-key "$(<~/.ssh/id_rsa.pub)" \
  --volume-import type:registry,url:docker://quay.io/containerdisks/fedora:latest,size:10Gi' \
  --termination-grace-period 600  | ./kubevirtci/cluster-up/kubectl.sh apply -f -
[..]
$ virtctl ssh -lfedora vm/lyarwood
[..]
$ sudo su -
$ cat > /etc/systemd/system/sleep-on-shutdown.service << _EOF_
[Unit]
Description=Sleep 120 seconds during shutdown
Before=sshd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
ExecStop=/usr/bin/bash -c "/bin/echo 'Sleeping for 120 seconds before shutdown...'; /bin/sleep 120; /bin/echo 'Finished sleeping.'"
TimeoutStopSec=130

[Install]
WantedBy=multi-user.target
_EOF_
$ systemctl enable sleep-on-shutdown.service
$ systemctl daemon-reload
$ systemctl start sleep-on-shutdown.service
$ exit
[..]

$ virtctl stop lyarwood
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/sig compute

### What this PR does

As set out in #15758 the default event recorder spam filter of EventSourceObjectSpamFilter itself defaults to a burst limit of 25 and can easily be hit if we attempt to gracefully shutdown a guest with a large TerminationGracePeriodSeconds value set.

When hit additional events can be dropped resulting in important events such as the eventual shutdown of the VMI not being seen.

This PR attempts to avoid this by only sending a VMIGracefulShutdown event after the initial request. Repeat attempts to gracefully shutdown the guest are still logged within virt-handler.

#### Before this PR:
```
$ ./kubevirtci/cluster-up/kubectl.sh get events --sort-by=.lastTimestamp -w
[..]
0s          Normal    SuccessfulDelete             virtualmachine/lyarwood                               Stopped the virtual machine by deleting the virtual machine instance 0cb6622a-ae91-496d-8323-588d733bcfd6
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
0s          Normal    Killing                      pod/virt-launcher-lyarwood-rfbb5                      Stopping container guest-console-log
0s          Normal    Killing                      pod/virt-launcher-lyarwood-rfbb5                      Stopping container compute
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-rfbb5
```

#### After this PR:

```
$ ./kubevirtci/cluster-up/kubectl.sh get events --sort-by=.lastTimestamp -w
[..]
0s          Normal    SuccessfulDelete             virtualmachine/lyarwood                               Stopped the virtual machine by deleting the virtual machine instance f6de6a5e-bd64-4e5f-920c-8ef0a451b193
0s          Normal    Killing                      pod/virt-launcher-lyarwood-l7xjk                      Stopping container guest-console-log
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
0s          Normal    Killing                      pod/virt-launcher-lyarwood-l7xjk                      Stopping container compute
0s          Normal    ShuttingDown                 virtualmachineinstance/lyarwood                       Signaled Graceful Shutdown
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    Stopped                      virtualmachineinstance/lyarwood                       The VirtualMachineInstance was shut down.
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    Deleted                      virtualmachineinstance/lyarwood                       Signaled Deletion
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
0s          Normal    SuccessfulDelete             virtualmachineinstance/lyarwood                       Deleted virtual machine pod virt-launcher-lyarwood-l7xjk
```

### References
- Fixes #15758

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
Only a single `Signaled Graceful Shutdown` event is now sent to avoid spamming the event recorder during long graceful shutdown attempts
```

### CODE REVIEW

File: pkg/virt-handler/vm.go [hunk 1]
```diff
@@ -1544,6 +1544,8 @@ func (c *VirtualMachineController) processVmShutdown(vmi *v1.VirtualMachineInsta
 	return c.helperVmShutdown(vmi, domain, tryGracefully)
 }
 
+const firstGracefulShutdownAttempt = -1
```
Comment (dasionov) [inline pkg/virt-handler/vm.go:1547]: This was bugging me while reviewing your first commit. Glad to see this value is now properly defined as a constant. :+1:

**Review by dasionov — APPROVED** [review]
Thank you for the PR, @lyarwood — everything looks good to me.
/lgtm

File: pkg/virt-handler/vm.go (hunk 1 above)
Comment (lyarwood) [reply pkg/virt-handler/vm.go:1547]: Hate it admit it but the AI review bot picked this up under https://github.com/kubevirt/kubevirt/pull/15759#discussion_r2380137854, I did think about doing it beforehand but forgot and pushed. Nice to see it making useful suggestions for a change tbh :)

File: pkg/virt-handler/vm.go [hunk 2]
```diff
@@ -1648,8 +1650,17 @@ func (c *VirtualMachineController) shutdownVMI(vmi *v1.VirtualMachineInstance, c
 
 	c.logger.Object(vmi).Infof("Signaled graceful shutdown for %s", vmi.GetObjectMeta().GetName())
 
+	// Only create a VMIGracefulShutdown event for the first attempt as we can
+	// easily hit the default burst limit of 25 for the
+	// EventSourceObjectSpamFilter when gracefully shutting down VMIs with a
+	// large TerminationGracePeriodSeconds value set. Hitting this limit can
+	// result in the eventual VMIShutdown event being dropped.
+	if timeLeft == firstGracefulShutdownAttempt {
+		c.recorder.Event(vmi, k8sv1.EventTypeNormal, v1.ShuttingDown.String(), VMIGracefulShutdown)
```
Comment (0xFelix) [inline pkg/virt-handler/vm.go:1659]: nit: you could add this in the if case below

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!
