### PR TITLE
instancetype: Only return revision of currently referenced object

### LINKED ISSUE #14595: preference requirements not being checked with initial update of VirtualMachine
/area instancetype

**What happened**:

Preferences can define resource requirements for a given workload, for example with Fedora:

```
$ ./kubevirtci/cluster-up/kubectl.sh get virtualmachineclusterpreference/fedora -o json | jq .spec.requirements
selecting podman as container runtime
{
  "cpu": {
    "guest": 1
  },
  "memory": {
    "guest": "2Gi"
  }
}
```

The requirements are currently correctly checked on creation:

```
$ virtctl create vm \
  --instancetype u1.micro \
  --preference fedora \
  --volume-containerdisk name:fedora,src:quay.io/containerdisks/fedora:latest \
  --name fedora | ./kubevirtci/cluster-up/kubectl.sh apply -f -
selecting podman as container runtime
The request is invalid: spec.instancetype: failure checking preference requirements: insufficient Memory resources of 1Gi provided by instance type, preference requires 2Gi
```

However on the first update these checks are skipped before apparently being preformed on follow up updates:

```
$ virtctl create vm \
  --instancetype u1.small \
  --preference fedora \
  --volume-containerdisk name:fedora,src:quay.io/containerdisks/fedora:latest \
  --name fedora | ./kubevirtci/cluster-up/kubectl.sh apply -f -
selecting podman as container runtime
virtualmachine.kubevirt.io/fedora created

$ ./kubevirtci/cluster-up/kubectl.sh patch vm/fedora --type=merge -p '{"spec":{"instancetype":{"name": "u1.micro"}}}'
selecting podman as container runtime
virtualmachine.kubevirt.io/fedora patched

$ ./kubevirtci/cluster-up/kubectl.sh patch vm/fedora --type=merge -p '{"spec":{"instancetype":{"name": "u1.small"}}}'
selecting podman as container runtime
The request is invalid: spec.instancetype: failure checking preference requirements: insufficient Memory resources of 1Gi provided by instance type, preference requires 2Gi

```

These checks should be migrated to the core sync loop of the VirtualMachine anyway to support eventually consistency but for now we need to understand how this is happening.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does
We currently check that a given VirtualMachine meets any referenced
preference requirements within the admission webhook.

With the recent move of references to captured ControllerRevisions of
instance types and preferences into the status of the VirtualMachine we
no longer populate `spec.{instancetype,preference}.revisionName`. This
data is now held under
`status.{instancetypeRef,preferenceRef}.controllerRevisionRef` and is
maintained by the core VirtualMachine sync loop.

This causes an issue when checking any referenced preference
requirements within the admission webhook as these references will still
point to ControllerRevisions of different objects when switching between
instance types or preferences during a live update etc.

This change fixes this by ensuring the ControllerRevisions referenced by
the status of the VirtualMachine contain the instance type or preference
currently referenced from the spec of the VirtualMachine.

Fixes #14595

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer

Numerous follow ups are left for later PRs here to allow this bugfix to be backportable. These include:

* Moving preference resource requirement checks to the core VM sync loop
* Merging the seperate `revisionFinder` implementations for instance types and preferences into a single implementation like the `controllerRevisionFinder`
* Adding support to the instance type builder for `WithMemoryRequirement()`
* Removing duplication from `spec_test.go`
* Linting `tests/hotplug`

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: tests/hotplug/instancetype.go [hunk 1]
```diff
@@ -182,4 +184,111 @@ var _ = Describe("[sig-compute]Instance Type and Preference Hotplug", decorators
...
 	)
+
+	DescribeTable("should reject live update when preference requirements are no longer met - bug #14595",
+		func(
+			createVM func(*virtv1.VirtualMachineInstance, string) (*virtv1.VirtualMachine, error),
+			updateVM func(*virtv1.VirtualMachine) (*virtv1.VirtualMachine, error),
+			errMatcher gomegatypes.GomegaMatcher,
+		) {
+			vmi := libvmifact.NewAlpine(
+				libnet.WithMasqueradeNetworking(),
```
Comment (0xFelix) [inline tests/hotplug/instancetype.go:195]: nit: Do we need masquerade?

File: tests/hotplug/instancetype.go [hunk 2]
```diff
@@ -182,4 +184,111 @@ var _ = Describe("[sig-compute]Instance Type and Preference Hotplug", decorators
...
+				libvmi.WithResourceMemory("1Gi"),
+			)
+			vmi.Namespace = testsuite.GetTestNamespace(vmi)
```
Comment (0xFelix) [inline tests/hotplug/instancetype.go:198]: There should be `libvmi.WithNamespace`

File: tests/hotplug/instancetype.go [hunk 3]
```diff
@@ -182,4 +184,111 @@ var _ = Describe("[sig-compute]Instance Type and Preference Hotplug", decorators
...
+			preference, err := virtClient.VirtualMachinePreference(vmi.Namespace).Create(
+				context.Background(), preference, metav1.CreateOptions{})
+			Expect(err).ToNot(HaveOccurred())
+
+			vm, err := createVM(vmi, preference.Name)
+			Expect(err).ToNot(HaveOccurred())
+
+			_, err = updateVM(vm)
+			Expect(err).To(HaveOccurred())
+			Expect(err.Error()).To(errMatcher)
```
Comment (0xFelix) [inline tests/hotplug/instancetype.go:215]:
```suggestion
			Expect(err).To(MatchError(errMatcher), "unexpected error")
```

File: tests/hotplug/instancetype.go [hunk 4]
```diff
@@ -182,4 +184,111 @@ var _ = Describe("[sig-compute]Instance Type and Preference Hotplug", decorators
...
+					context.Background(),
+					builder.NewInstancetypeFromVMI(vmi),
+					metav1.CreateOptions{},
+				)
+				Expect(err).ToNot(HaveOccurred())
+
+				vm, err := virtClient.VirtualMachine(vmi.Namespace).Create(
+					context.Background(),
+					libvmi.NewVirtualMachine(
+						vmi,
```
Comment (0xFelix) [inline tests/hotplug/instancetype.go:252]: Will there be no conflict with the VMI's `libvmi.WithResourceMemory("1Gi")`?

File: tests/hotplug/instancetype.go [hunk 5]
```diff
@@ -182,4 +184,111 @@ var _ = Describe("[sig-compute]Instance Type and Preference Hotplug", decorators
...
+				)
+				Expect(err).ToNot(HaveOccurred())
+
+				patches := patch.New(
+					patch.WithTest("/spec/instancetype/name", origInstancetype.Name),
+					patch.WithReplace("/spec/instancetype/name", newInstancetype.Name),
+				)
+				patchData, err := patches.GeneratePayload()
+				Expect(err).NotTo(HaveOccurred())
+				return virtClient.VirtualMachine(vm.Namespace).Patch(context.Background(), vm.Name, types.JSONPatchType, patchData, metav1.PatchOptions{})
```
Comment (0xFelix) [inline tests/hotplug/instancetype.go:289]: Do we need to wait for updated CR refs to avoid flakes?

File: tests/hotplug/instancetype.go (hunk 1 above)
Comment (lyarwood) [reply tests/hotplug/instancetype.go:195]: for this specific test no, I'll remove.

File: tests/hotplug/instancetype.go (hunk 2 above)
Comment (lyarwood) [reply tests/hotplug/instancetype.go:198]: Yeah I didn't realise that `GetTestNamespace(nil)` was valid here, I'll fold it in.

File: tests/hotplug/instancetype.go (hunk 4 above)
Comment (lyarwood) [reply tests/hotplug/instancetype.go:252]: Yeah, `WithInstancetype` calls `resourcesRemovedFromVMI` to handle this:

https://github.com/kubevirt/kubevirt/blob/21ce93e095e3f183d939422dfe3cb661ae7525d4/pkg/libvmi/vm.go#L137-L145

https://github.com/kubevirt/kubevirt/blob/21ce93e095e3f183d939422dfe3cb661ae7525d4/pkg/libvmi/vm.go#L101-L105

File: tests/hotplug/instancetype.go (hunk 5 above)
Comment (lyarwood) [reply tests/hotplug/instancetype.go:289]: No, this patch will always fail in the webhook now so the updated VirtualMachine is never seen by the controller or sync loop.

File: tests/hotplug/instancetype.go (hunk 4 above)
Comment (0xFelix) [reply tests/hotplug/instancetype.go:250]: Interesting to know, I would have not expected `libvmi` to contain such logic.
