### PR TITLE
fix goroutine leak in virt-handler

### LINKED ISSUE #6056: [SIG-scale] Goroutine count and memory remains high after VMIs are removed
### Summary
Create n VMIs, wait until they are all running, delete n VMIs, wait until they are all deleted, sleep 5s, and repeat. Scenarios for 10, 20, 40, 60, 80, 100, 200, 300 VMIs shows an increase in virt-handler mem/cpu usage and go routines, however only cpu usage returns back to the expected level when there are 0 VMIs.

### KubeVirt control plane metrics
mem-leak-#5982

### Metric
| Name | Description | Metric |
|--|---|--|
| Memory | Amount of memory used | `sum(process_resident_memory_bytes{job=~".*kubevirt.*"}) by (instance, container)`|
| CPU usage | Tme spent using the CPU | `sum(rate(process_cpu_seconds_total{job=~".*kubevirt.*"}[5m])) by (instance, container)`|
| Goroutines | Amount of goroutines being used | `go_goroutines{job=~".*kubevirt.*", cluster="$cluster"}`|
| Network | Amount of network being used | `sum(rate(container_network_receive_bytes_total{namespace=~".*kubevirt.*"}[5m])) by (node, pod) + sum(rate(container_network_transmit_bytes_total{namespace=~".*kubevirt.*"}[5m])) by (node, pod)`

/kind bug

### PR DESCRIPTION
**Pull request by kwiesmueller**
**What this PR does / why we need it**:
As previously observed in https://github.com/kubevirt/kubevirt/issues/6056
and further confirmed in https://snapshot.raintank.io/dashboard/snapshot/M09k4WMjCr23lZDunw3tnbbE7JvyPvxD
`virt-handler` is leaking goroutines.

The main cause for this leak seems to be in the way we handle the domainNotifyPipe. In the current code we listen to a unix socket which is a blocking operation. This seems to prevent the code from ever reaching the cleanup part. As a solution we move the connection closing outside the loop into a seperate routine that will close the connection on a cleanup signal and cause the `Accept()` call to fail. Then we can check if it's a close error and return.

Another way to do this instead of the goroutine approach would be to set a ReadDeadline, but this has to happen at some point further up the tree.

To validate the fix there is a [Grafana Snapshot](https://snapshot.raintank.io/dashboard/snapshot/s2mWyECQ4hDfZ7xIVLr0lLmcL3otlwCy?orgId=2) showing goroutines after and before the fix.

**Release note**:

```release-note
Fix goroutine leak in virt-handler, potentially causing issues with a high turnover of VMIs.
```

### CODE REVIEW

File: pkg/virt-handler/vm.go [hunk 1]
```diff
@@ -286,21 +286,22 @@ func handleDomainNotifyPipe(domainPipeStopChan chan struct{}, ln net.Listener, v
...
-				} else {
-					fdChan <- fd
+			fd, err := ln.Accept()
+			if err != nil {
+				if goerror.Is(err, net.ErrClosed) {
+					return
 				}
+				log.Log.Reason(err).Error("Domain pipe accept error encountered.")
+				// keep listening until stop invoked
+				time.Sleep(1)
```
Comment (kwiesmueller) [inline pkg/virt-handler/vm.go:302]: @davidvossel @rmohr do you know if we really want to sleep for 1 Nanosecond here? I think this should probably be `1 * time.Millisecond` or more.

File: pkg/virt-handler/vm.go [hunk 2]
```diff
@@ -286,21 +286,22 @@ func handleDomainNotifyPipe(domainPipeStopChan chan struct{}, ln net.Listener, v
 	// Listen for new connections,
 	// Close listener and exit when stop encountered
 	go func(vmi *v1.VirtualMachineInstance, ln net.Listener, domainPipeStopChan chan struct{}) {
+		go func() {
+			<-domainPipeStopChan
+			log.Log.Object(vmi).Infof("closing notify pipe listener for vmi")
+			ln.Close()
```
Comment (davidvossel) [inline pkg/virt-handler/vm.go:292]: i just noticed that Close() can return an err. is that something we need to handle?

File: pkg/virt-handler/vm.go (hunk 1 above)
Comment (davidvossel) [reply pkg/virt-handler/vm.go:302]: use `1 * time.Second`. that was likely the original intent.

**Review by davidvossel — COMMENTED** [review]
great catch!

File: pkg/virt-handler/vm.go (hunk 2 above)
Comment (kwiesmueller) [reply pkg/virt-handler/vm.go:292]: We could at least log an error when it happens, but I don't think there is much else we can do.
It would probably error if the underlying socket is already closed or does not exist anymore. But in our case we should be fine either way?

File: pkg/virt-handler/vm.go [hunk 3]
```diff
@@ -286,21 +286,24 @@ func handleDomainNotifyPipe(domainPipeStopChan chan struct{}, ln net.Listener, v
...
-				return
-			default:
-				fd, err := ln.Accept()
-				if err != nil {
-					log.Log.Reason(err).Error("Domain pipe accept error encountered.")
-					// keep listening until stop invoked
-					time.Sleep(1)
-				} else {
-					fdChan <- fd
+			fd, err := ln.Accept()
```
Comment (rthallisey) [inline pkg/virt-handler/vm.go:297]: I understand the issue to be that we're trapped in this for loop and `<-domainPipeStopChan` never gets seen so the routine leaks.  Is that because we get stuck in the default clause?

Comment (kwiesmueller) [reply pkg/virt-handler/vm.go:297]: Correct, as `Accept()` is blocking, it would need to fail before the channel close gets observed.

Comment (rthallisey) [reply pkg/virt-handler/vm.go:297]: OK.  Probably more readable to have two different go routines instead of a nested one.  Also worth adding a comment explaining the importance of your change since it doesn't look like a unit test can cover what you fixed.

Comment (kwiesmueller) [reply pkg/virt-handler/vm.go:298]: Good point, I moved it out of here and added a comment to the error check below.

**Review by rthallisey — APPROVED** [review]

**Review by davidvossel — APPROVED** [review]
/approve
