### PR TITLE
network, dns: Support adding IPv6 Nameservers

### LINKED ISSUE #15011: No support for ipv6 dnsConfig nameserver addresses
**What happened**:
Unable to add ipv6 nameservers to /etc/resolv.conf. IPv4 addresses work just fine.

**What you expected to happen**:
Both IPv4 and IPv6 nameservers to be accepted.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with the following spec
```
spec:
  dnsConfig:
    nameservers:
      - '12.34.56.78'
      - 'a2c6:7638:979c:a8fa:7b5b:b2a9:ba87:3f46'
```

Note that only the IPv4 nameserver will be added to /etc/resolve.conf.

**Additional context**:
Looks like the regex here only accepts IPv4 addresses. https://github.com/kubevirt/kubevirt/blob/f8ec3b41426cf6df0eaba43447b39fd0b6dbd1da/pkg/network/dns/resolveconf.go#L42

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by oshoval**
### What this PR does
Currently, parsing the Pod's nameservers is limited to IPv4 nameservers.
Fix it to support also IPv6 ones.
In order to populate the IPv6 ones to the VM, add IPv6 DHCP modifier, option 23,
which is used to advertise the IPV6 nameservers.

Note: Since Kubevirt doesn't support RA, SLAAC won't work out of the box,
and the VM won't get global IPv6, nor nameservers.
Hence `dhcp` method should be used (see examples in the PR comments).

### References
Fixes #15011

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
Didn't add e2e, because we might not need e2e for it, and if we do
we can add it on the same test that  https://github.com/kubevirt/kubevirt/pull/14189 fixes,
once it is merged.
Because this mentioned PR purpose is also to use `method: dhcp` as required in this PR.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
according https://datatracker.ietf.org/doc/html/rfc2132#section-3.8

IPv4 option 6, is concatenation of 4 bytes IPv4s, I don't think it is correct, or even possible to use it to populate IPv6
We should use option 23 of IPv6.
Another benefit of that, is that it will be populated only if VM has a IPv6 [1].

[1] https://github.com/kubevirt/kubevirt/blob/c5e2a979acfc30513af91bc8f1e0066134f6ae34/pkg/network/driver/common.go#L196

**Comment by oshoval** [comment]
Tested with

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vmi
  labels:
    special: vmi
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vmi
    spec:
      dnsConfig:
        nameservers:
          - '12.34.56.78'
          - 'a2c6:7638:979c:a8fa:7b5b:b2a9:ba87:3f46'    
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: registry:5000/kubevirt/fedora-with-test-tooling-container-disk:devel
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                dhcp6: true
```

Had to configure NetworkManager to get IPv6 via `method=dhcp` (otherwise it doesnt get IPv6 because we don't support RA, this also explains why the `dhcp6: true` on cloud-init doesn't work, as it use default SLAAC  `method=auto`).
Need to configure routes manually because RA is not supported by Kubevirt.

```
nmcli con modify "$(nmcli -g NAME con show)" ipv6.method dhcp
nmcli con up "$(nmcli -g NAME con show)"
```
And after few seconds we can see
```
[root@vmi fedora]# ip a | grep global
    inet 10.0.2.2/24 brd 10.0.2.255 scope global dynamic noprefixroute eth0
    inet6 fd10:0:2::2/128 scope global dynamic noprefixroute 
[root@vmi fedora]# 

[root@vmi fedora]# cat /etc/resolv.conf 
# Generated by NetworkManager
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
nameserver 12.34.56.78
nameserver a2c6:7638:979c:a8fa:7b5b:b2a9:ba87:3f46
```

Note `dhclient -6` also shows it works, but then it overrides the /etc/resolv.conf with just ipv6 information, so better to configure NM to do both.

File: pkg/network/dns/resolveconf.go [hunk 1]
```diff
@@ -146,27 +151,38 @@ func DomainNameWithSubdomain(searchDomains []string, subdomain string) string {
 }
 
 // GetResolvConfDetailsFromPod reads and parses the DNS resolver's configuration file.
-func GetResolvConfDetailsFromPod() ([][]byte, []string, error) {
-	// #nosec No risk for path injection. resolvConf is static "/etc/resolve.conf"
+func GetResolvConfDetailsFromPod() ([][]byte, [][]byte, []string, error) {
```
Comment (nirdothan) [inline pkg/network/dns/resolveconf.go]: This raises linter errors:
```
pkg/network/dns/resolveconf.go:37:1: unnamedResult: consider giving a name to these results (gocritic)
func ParseNameservers(content string) ([][]byte, [][]byte, error) {
^
pkg/network/dns/resolveconf.go:154:1: unnamedResult: consider giving a name to these results (gocritic)
func GetResolvConfDetailsFromPod() ([][]byte, [][]byte, []string, error) {
^
pkg/network/dns/resolveconf_test.go:170: File is not `gofumpt`-ed with `-extra` (gofumpt)
                        searchDomains := []string{"default.svc.cluster.local", "svc.cluster.local",
                                "cluster.local", "this.is.a.very.very.very.long.entry"}
pkg/network/dns/resolveconf.go:47:22: Magic number: 2, in <condition> detected (mnd)
                        if len(fields) != 2 {
                                          ^
```

File: pkg/network/dns/resolveconf_test.go [hunk 2]
```diff
@@ -31,23 +31,46 @@ var _ = Describe("Resolveconf", func() {
...
 			resolvConf := "nameserver 8.8.8.8\nnameserver 8.8.4.4\n"
-			nameservers, err := ParseNameservers(resolvConf)
-			Expect(nameservers).To(Equal([][]byte{ns1, ns2}))
+			ipv4Nameservers, ipv6Nameservers, err := ParseNameservers(resolvConf)
+			Expect(ipv4Nameservers).To(Equal([][]byte{ns1, ns2}))
+			Expect(ipv6Nameservers).To(BeEmpty())
 			Expect(err).ToNot(HaveOccurred())
 		})
 
+		It("should return a byte array of IPv6 nameservers", func() {
```
Comment (nirdothan) [inline pkg/network/dns/resolveconf_test.go:40]: nit: Please consider a table test here.

**Comment by oshoval** [comment]
About e2e, once https://github.com/kubevirt/kubevirt/pull/14189 is merged we can consider, atm it is not crucial, as we don't officially support IPv6 yet, lets hear more opinion if needed please, this what was discussed offline so far.

File: pkg/network/dns/resolveconf.go (hunk 1 above)
Comment (oshoval) [reply pkg/network/dns/resolveconf.go]: we don't run linter and dont need to use named results, i will look on the rest if they are crucial, but as long as we don't have a linter we don't need to enforce beside the ones that make sense

Comment (nirdothan) [reply pkg/network/dns/resolveconf.go]: We've been through this before: https://github.com/kubevirt/kubevirt/pull/13153#discussion_r1896742245.
@orelmisan WDYT?

I personally try to avoid returning 4 values from a function.

Comment (oshoval) [reply pkg/network/dns/resolveconf.go]: we dont lint this directory atm fwiw so we wont need to add those pragmas

imo named variables aren't desired, nor a struct here, so best method is to split the function
follow-ups can refactor it, this way or another, i dont think its crucial for this PR

Comment (oshoval) [reply pkg/network/dns/resolveconf.go]: about the other linter problems, first one isnt affected by this PR (please try to not include those)

the 2nd one is nit, and no need to define const for such number

File: pkg/network/dns/resolveconf_test.go (hunk 2 above)
Comment (oshoval) [reply pkg/network/dns/resolveconf_test.go:40]: would just complicate stuff imho

File: pkg/network/dns/resolveconf.go (hunk 1 above)
Comment (nirdothan) [reply pkg/network/dns/resolveconf.go]: Please consider returning a struct like so:
```go

type Nameservers struct {
	IPv4 [][]byte
	IPv6 [][]byte
}

func ParseNameservers(content string) (*Nameservers, error) {
	var ipv4Nameservers [][]byte
	var ipv6Nameservers [][]byte

	...

	return &Nameservers{
		IPv4: ipv4Nameservers,
		IPv6: ipv6Nameservers,
	}, nil
}
```

**Comment by oshoval** [comment]
addressed https://github.com/kubevirt/kubevirt/pull/15045#discussion_r2224766951

**Comment by nirdothan** [comment]
Thank you @oshoval. Nice work!
/LGTM

**Comment by oshoval** [comment]
Thanks Nir
@EdDev / @orelmisan can you please take a look ?

**Comment by oshoval** [comment]
oops, it was 2 commits and i squashed by mistake, unless it doesnt matter

**Comment by nirdothan** [comment]
> oops, it was 2 commits and i squashed by mistake, unless it doesnt matter

I don't mind the squash but now there's no description at all.

**Comment by oshoval** [comment]
returned the commits

File: pkg/network/dns/resolveconf.go [hunk 3]
```diff
@@ -36,36 +34,48 @@ const (
...
+type Nameservers struct {
+	IPv4 [][]byte
+	IPv6 [][]byte
+}
 
-	re, err := regexp.Compile("([0-9]{1,3}.?){4}")
-	if err != nil {
-		return nameservers, err
-	}
+func ParseNameservers(content string) ([][]byte, [][]byte, error) {
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go]: Since the `Nameservers` type was introduced, any reason not to use it here?

File: pkg/network/dns/resolveconf.go [hunk 4]
```diff
@@ -36,36 +34,48 @@ const (
...
 		line := scanner.Text()
 		if strings.HasPrefix(line, nameserverPrefix) {
-			nameserver := re.FindString(line)
-			if nameserver != "" {
-				nameservers = append(nameservers, net.ParseIP(nameserver).To4())
+			fields := strings.Fields(line)
+			if len(fields) != 2 {
+				log.Log.Warningf("Invalid resolv.conf format: nameserver line should have only one value per line '%s'", line)
+				continue
+			}
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go:55]: Was this behavior allowed before the change? (silently skipping invalid lines)

File: pkg/network/dns/resolveconf.go [hunk 5]
```diff
@@ -36,36 +34,48 @@ const (
...
+
+			nameserver := fields[1]
+			parsedIP := net.ParseIP(nameserver)
+			if parsedIP != nil {
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go]: Please consider reversing the condition in order to reduce indentation.

File: pkg/network/dns/resolveconf.go [hunk 6]
```diff
@@ -36,36 +34,48 @@ const (
...
-		return nameservers, err
+	if err := scanner.Err(); err != nil {
+		return ipv4Nameservers, ipv6Nameservers, err
 	}
 
 	// apply a default DNS if none found from pod
-	if len(nameservers) == 0 {
-		nameservers = append(nameservers, net.ParseIP(defaultDNS).To4())
+	if len(ipv4Nameservers) == 0 && len(ipv6Nameservers) == 0 {
+		ipv4Nameservers = append(ipv4Nameservers, net.ParseIP(defaultDNS).To4())
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go:77]: Is there also a default IPv6 name server?

Comment (oshoval) [reply pkg/network/dns/resolveconf.go:77]: There is `2001:4860:4860::8888` but since we don't support IPv6 as required, nor have routes (due to missing RA),
I dont think we should add it now

there are only max 3 NS allowed, we dont need to enforce that one
users might want to add more (they can always override, but it will force them to add configurations to override)

**Comment by oshoval** [comment]
For e2e we need https://github.com/kubevirt/kubevirt/pull/14189 first
and imo it is not required (I think Edy agreed about that atm, since we don't fully support IPv6 yet out of the box, due to missing RA)
Moreover this behavior is corner case, and doesn't need to be tested on each and every push, but we can delegate it to future discussion

File: pkg/network/dns/resolveconf.go (hunk 4 above)
Comment (oshoval) [reply pkg/network/dns/resolveconf.go:55]: It had `re, err := regexp.Compile("([0-9]{1,3}.?){4}")`
```
nameserver := re.FindString(line)
if nameserver != "" {
    nameservers = append(nameservers, net.ParseIP(nameserver).To4())
```

so it did skip some errors, but didnt find them all
i.e `nameserver1.2.3.4` was ok, where it shouldn't because it doesnt have space

anyhow since we read the pod, i dont think we need extra caution here
it is just nicer to have it correct (we dont use regex anymore, so used other means for syntax checking and corrected few on the way)

we can reverse logic to make sure there are 2 fields, and that the first field is 
`nameserverPrefix`, and 2nd is a valid IP (as done already) - anyhow it is equivalent

**Comment by oshoval** [comment]
addressed comments

File: pkg/network/dns/resolveconf.go (hunk 4 above)
Comment (orelmisan) [reply pkg/network/dns/resolveconf.go:55]: I think we should return an error in case the line is invalid - as it would probably be a K8s bug.
We can handle it in a follow up.

File: pkg/network/dns/resolveconf.go [hunk 7]
```diff
@@ -36,36 +34,53 @@ const (
...
+			} else {
+				ipv6Nameservers = append(ipv6Nameservers, parsedIP.To16())
 			}
 		}
 	}
 
-	if err = scanner.Err(); err != nil {
-		return nameservers, err
+	if err := scanner.Err(); err != nil {
+		return nil, err
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go:72]: Thank you for addressing this bug.

File: pkg/network/dns/resolveconf.go [hunk 8]
```diff
@@ -36,36 +34,53 @@ const (
...
+type Nameservers struct {
+	IPv4 [][]byte
+	IPv6 [][]byte
+}
 
-	re, err := regexp.Compile("([0-9]{1,3}.?){4}")
-	if err != nil {
-		return nameservers, err
-	}
+func ParseNameservers(content string) (*Nameservers, error) {
```
Comment (orelmisan) [inline pkg/network/dns/resolveconf.go:42]: nit: No need to return a pointer here.

**Review by orelmisan — COMMENTED** [review]
Thank you @oshoval!
/approve

File: pkg/network/dns/resolveconf.go (hunk 8 above)
Comment (oshoval) [reply pkg/network/dns/resolveconf.go:42]: onef of the reasons, it copies less data
8 bytes instead 24x2 = 48
and data will be mutable anyhow, so * is more explicit, and the deref is the same anyhow

even that [this](https://cs.opensource.google/go/go/+/refs/tags/go1.24.5:src/reflect/value.go;l=2558) struct is deprecated, slice is 24B on 64bit machine

```
type slice struct {
    ptr uintptr  // 8 bytes - pointer to underlying array  
    len int      // 8 bytes - length
    cap int      // 8 bytes - capacity
}
```

it also allows returning nil which is the cleanest and easiest

**Comment by nirdothan** [comment]
/LGTM 

Although I liked it better before:
```go
if parsedIP == nil {
	continue
}
```
