### PR TITLE
Corrected issue with external boot which only kernelPath is specified without initrd path

### LINKED ISSUE #8191: Booting from an external source  (Kernel) causes error
**What happened**:
 
Currently, when attempting to deploy a Virtual Machine that has been provided an explicit kernel, kernel artifact verification fails and consequently the VM fails to start. The only way that this issue was able to be rectified was by disabling verification inside the `mountKernelArtifacts` function called in [pkg/virt-handler/container-disk/mount.go](https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go). Manually going into the virt-handler container and checking the path that has been mounted containing the kernel confirms that the mount was successful but in the environment tested, the verification is failing. Specifically, https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go#L512 is the line that returns back an error. The return from the mount command on https://github.com/kubevirt/kubevirt/blob/c4b6ae63c5a7f642ab86b0755dabca3b814ecb39/pkg/virt-handler/container-disk/mount.go#L502 is successful so it would appear the criteria for verifying mount status is not working as intended.

**What you expected to happen**:

I would expect the kernel mount verification to complete successfully and for the VM to start without issue given that I was able to manually confirm that the mount was successful and the kernel is visible at the expected path. 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Simply deploy a VM/VMI which contains the following kernel block:

```yml
spec:
  domain:
    devices: {}
    firmware:
      kernelBoot:
        container:
              image: [ANY KERNEL CONTAINER IMAGE SHOULD DO]
              kernelPath: /boot/vmlinuz-virt
              imagePullPolicy: Always
              imagePullSecret: IfNotPresent
        kernelArgs: console=ttyS0
```

**Additional context**:

N/A

**Environment**:
- KubeVirt version (use `virtctl version`): Currently working off the main branch as of 7/26/22
- Kubernetes version (use `kubectl version`): 1.21
- VM or VMI specifications: N/A

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: my-test-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: testdomain
    spec:
      domain:
        firmware:
          kernelBoot:
            container:
              imagePullPolicy: IfNotPresent
              image: kubevirtvrack/alpine-ext-kernel-boot-demo
              kernelPath: /boot/vmlinuz-virt
            kernelArgs: console=ttyS0
        memory:
          guest: 1300M
        devices:
          disks:
          - name: disk-1
            disk:
              bus: virtio
          - name: disk-2
            disk:
              bus: virtio
          interfaces:
          - name: network1
            bridge: {}
          - name: network2
            bridge: {}
          - name: network3
            bridge: {}
          - name: network4
            bridge: {}
        resources:
          overcommitGuestOverhead: true
          limits:
            cpu: 3
            memory: 1500M
          requests:
            cpu: 3
            memory: 1Gi
      networks:
              - name: network1
                multus:
                  networkName: testdomain/my-test-vm
              - name: network2
                multus:
                  networkName: testdomain/my-test-vm
              - name: network3
                multus:
                  networkName: testdomain/my-test-vm
              - name: network4
                multus:
                  networkName: testdomain/my-test-vm
      volumes:
           - name: disk-1
             emptyDisk:
               capacity: 50G
           - name: disk-2
             emptyDisk:
               capacity: 50G
```

- Cloud provider or hardware configuration:  AWS EKS with Non-Fargate EC2 Instances
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`):  `Linux ip-10-2-169-42 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by daghaian**
**What this PR does / why we need it**:
This PR aims to resolve an issue that was discovered involving booting from external source functionality. Currently, Kubevirt provides the ability for the user to specify options for booting directly from a kernel/initrd as part of the VM spec. An issue was identified in which scenarios where the user opts to boot from a kernel (`kernelPath` argument provided) but does not have a need to specify a path for initrd, the verification of kernel artifact mount success will fail. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
fixes #8191

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: tests/vmi_kernel_boot_test.go [hunk 1]
```diff
@@ -122,4 +122,60 @@ var _ = Describe("[sig-compute]VMI with external kernel boot", func() {
 			Expect(err.Error()).To(ContainSubstring("denied the request: spec.domain.firmware.kernelBoot.container must be defined with at least one of the following: kernelPath, initrdPath"))
 		})
 	})
+
+	Context("with external alpine-based kernel only", func() {
+		It("ensure successful boot", func() {
+			vmi := utils.GetVMIKernelBoot()
+			// Remove initrd path from vmi spec
+			kernelBoot := vmi.Spec.Domain.Firmware.KernelBoot
+			kernelBoot.Container.InitrdPath = ""
```
Comment (iholder-redhat) [inline tests/vmi_kernel_boot_test.go:131]: nit: you can add the following function under `Context("with external alpine-based kernel only", func() {`:
```go
getVMIKernelBoot := func() *VirtualMachineInstance {
	vmi := utils.GetVMIKernelBoot()
	// Remove initrd path from vmi spec
	kernelBoot := vmi.Spec.Domain.Firmware.KernelBoot
	kernelBoot.Container.InitrdPath = ""
}
```

That way anyone writing tests in these context wouldn't have to worry about removing initrd path + code wouldn't be duplicated.

File: pkg/virt-handler/container-disk/mount.go [hunk 2]
```diff
@@ -448,7 +448,6 @@ func (m *mounter) mountKernelArtifacts(vmi *v1.VirtualMachineInstance, verify bo
 	var targetKernelPath *safepath.Path
 
 	if kb.InitrdPath != "" {
-
```
Comment (iholder-redhat) [inline pkg/virt-handler/container-disk/mount.go]: :+1: 
Please squash this with the first commit

**Review by iholder-redhat — COMMENTED** [review]
Thanks a lot @daghaian!
Great job finding the bug and solving it! Code is well written and root cause well identified.

Left some comments below.
Also, please squash 3rd commit with the first one

**Comment by daghaian** [comment]
@iholder-redhat I have made all of the requested updates, with the exception of the squashing of commit and the extraneous space you pointed out. I think we're nitpicking a smidge at this point but if you really would like those changes I'll be more than happy to make them. Thanks.

**Comment by iholder-redhat** [comment]
> @iholder-redhat I have made all of the requested updates, with the exception of the squashing of commit and the extraneous space you pointed out. I think we're nitpicking a smidge at this point but if you really would like those changes I'll be more than happy to make them. Thanks.

Great work!
Thanks very much for addressing my comments. With `nit` I mean that it's a minute comment that you're welcome to ignore :)

/lgtm

**Comment by iholder-redhat** [comment]
@daghaian I see that `make` fails here, specifically `make build-verify` with this error:
```
no changes added to commit (use "git add" and/or "git commit -a")
```

Can you add all files into a commit and run `make build-verify` locally to see it passes?

**Comment by mhenriks** [comment]
/lgtm
/approve

Thanks @daghaian!

File: tests/vmi_kernel_boot_test.go [hunk 3]
```diff
@@ -122,4 +124,65 @@ var _ = Describe("[sig-compute]VMI with external kernel boot", func() {
...
+			return vmi
+		}
+
+		It("ensure successful boot", func() {
+			vmi := getVMIKernelBoot()
+
+			obj, err := virtClient.VirtualMachineInstance(util.NamespaceTestDefault).Create(vmi)
+			Expect(err).ToNot(HaveOccurred())
+			tests.WaitForSuccessfulVMIStart(obj)
```
Comment (xpivarc) [inline tests/vmi_kernel_boot_test.go:142]: Don't you need to login here to verify if it is actually booted? Same below.

File: tests/vmi_kernel_boot_test.go [hunk 4]
```diff
@@ -122,4 +124,65 @@ var _ = Describe("[sig-compute]VMI with external kernel boot", func() {
...
+			Expect(err).ToNot(HaveOccurred())
+			tests.WaitForSuccessfulVMIStart(vmi)
+
+			By("Fetching virt-launcher pod")
+			virtLauncherPod := tests.GetRunningPodByVirtualMachineInstance(vmi, vmi.Namespace)
+
+			By("Ensuring VMI is deleted")
+			err = virtClient.VirtualMachineInstance(util.NamespaceTestDefault).Delete(vmi.Name, &v1.DeleteOptions{})
+			Expect(err).ToNot(HaveOccurred())
+			Eventually(func() (isVmiDeleted bool) {
```
Comment (xpivarc) [inline tests/vmi_kernel_boot_test.go:168]: You can use `tests.WaitForVirtualMachineToDisappearWithTimeout(vmi, 120)`

**Review by xpivarc — COMMENTED** [review]
/hold
I have just one question and one nit.

File: tests/vmi_kernel_boot_test.go (hunk 3 above)
Comment (rmohr) [reply tests/vmi_kernel_boot_test.go:142]: Is the VM now actually booting into the OS or would it need the initrd too? If we would need a specific kernel to test it, I guess it would be ok to go without, since that would be quite some overhead for @daghaian. If it boots into the OS, I agree.

Comment (mhenriks) [reply tests/vmi_kernel_boot_test.go:142]: Yeah I think we would need a new kernel.  Without this patch we don't get to running state.  To me that is good enough.

Comment (mhenriks) [reply tests/vmi_kernel_boot_test.go:142]: Also @xpivarc the tests with initrd don't login either

Comment (daghaian) [reply tests/vmi_kernel_boot_test.go:142]: @rmohr We can check to identify whether or not we're actually making it into the OS but as @mhenriks mentioned already, it would not appear that any login checks are being performed even with the original kernel+initrd scenario. If we want to modify both the test involving this proposed patch and the previous, we can discuss that further.

File: tests/vmi_kernel_boot_test.go (hunk 4 above)
Comment (rmohr) [reply tests/vmi_kernel_boot_test.go:168]: Let's keep that for now. The file does not use the normal cleanup procedures. We can switch over the whole file to it at in another PR.

File: tests/vmi_kernel_boot_test.go (hunk 3 above)
Comment (rmohr) [reply tests/vmi_kernel_boot_test.go:142]: Fine by me. Let's see what @xpivarc says.

Comment (xpivarc) [reply tests/vmi_kernel_boot_test.go:142]: I apologize I was interrupted in the morning when I was trying to reply.

I was under the impression we have it(but maybe we had a custom kernel for something else...).
I have only one objection and that is the name of the test `ensure successful **boot**` which might be confusing in the future.

Thank you for the fix!

File: tests/vmi_kernel_boot_test.go (hunk 4 above)
Comment (xpivarc) [reply tests/vmi_kernel_boot_test.go:168]: I should really start writing `Nit: You can....`

File: tests/vmi_kernel_boot_test.go (hunk 3 above)
Comment (mhenriks) [reply tests/vmi_kernel_boot_test.go:142]: @xpivarc what, exactly is confusing?  The other test, which is exactly the same, but with initrd, has the same name.  I think we should be extra friendly to new contributors and we're perhaps being a little too pedantic here.

**Review by xpivarc — COMMENTED** [review]
/hold cancel

File: tests/vmi_kernel_boot_test.go (hunk 3 above)
Comment (xpivarc) [reply tests/vmi_kernel_boot_test.go:142]: Forgot to unhold. 
@mhenriks Well, the other test is confusing to me too. We can clean it up altogether(in the next one). The confusing part is the name. It should tell me what the test is trying to test. I would expect it to verify that OS is correctly booted if it says so. (This test however only verifies we do not crash) It happened to me at least once that the test was actually not testing what it was stating and it can confuse a lot...

I was holding only because I thought we have a possibility to test this better. Thank you for correcting me.
