### PR TITLE
Watch VM resource for status change instead of polling in tests/vm_test.go

### LINKED ISSUE #14566: flake: VirtualMachine A valid VirtualMachine given should report an error status when image pull error occurs
# What happened

Flaky test detected: VirtualMachine A valid VirtualMachine given should report an error status when image pull error occurs [1]

/kind flake
/priority critical-urgent

/sig compute

[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2025-04-22-168h.html#row67

## Additional context

Quarantine PR: https://github.com/kubevirt/kubevirt/pull/14559

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by harshitgupta1337**
### What this PR does
Before this PR: The test used the `Eventually` construct of Ginkgo to poll the VM status until it was in the desired state. However, the polling period of 1 second was missing the intermediate status of `ErrImagePull` (between two occurrences of the `ImagePullBackOff` status) in the second retry of image pull. This resulted in the `Eventually` assertion failure.

After this PR: The test relies on a Watch on the VM resource, so that no status updates are missed.

Fixes #14566

### Why we need it and why it was done in this way
The following tradeoffs were made: At the

The following alternatives were considered: One alternative that was considered involved reducing the polling interval to detect VM status changes more quickly. However, this approach does not resolve the underlying race condition and would result in increased resource usage due to more frequent polling.

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note

```

### CODE REVIEW

File: tests/vm_test.go [hunk 1]
```diff
@@ -519,7 +519,7 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
 			),
 		)
 
-		It("[test_id:6869][QUARANTINE]should report an error status when image pull error occurs", decorators.Conformance, decorators.Quarantine, func() {
```
Comment (0xFelix) [inline tests/vm_test.go:522]: Please do not remove `[QUARANTINE]` yet. We can do it once we are sure the test is stable again.

File: tests/vm_test.go [hunk 2]
```diff
@@ -528,11 +528,16 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
...
-			for i := 0; i < times; i++ {
-				Eventually(ThisVM(vm), 300*time.Second, 1*time.Second).Should(HavePrintableStatus(v1.VirtualMachineStatusErrImagePull))
-				Eventually(ThisVM(vm), 300*time.Second, 1*time.Second).Should(HavePrintableStatus(v1.VirtualMachineStatusImagePullBackOff))
+			maxImgPullRetries := 2 // max number of image pull (re)tries
+			expectedStates := []v1.VirtualMachinePrintableStatus{}
+			for range maxImgPullRetries {
+				// each image pull (re)try should take the VM
+				// from status ErrImagePull to ImagePullBackOff
+				expectedStates = append(expectedStates, v1.VirtualMachineStatusErrImagePull)
+				expectedStates = append(expectedStates, v1.VirtualMachineStatusImagePullBackOff)
```
Comment (0xFelix) [inline tests/vm_test.go:537]: You can fold this

```suggestion
			expectedStates := []v1.VirtualMachinePrintableStatus{
				v1.VirtualMachineStatusErrImagePull,
				v1.VirtualMachineStatusImagePullBackOff,
			}
```

File: tests/vm_test.go [hunk 3]
```diff
@@ -1267,3 +1272,40 @@ func createRunningVM(virtClient kubecli.KubevirtClient, template *v1.VirtualMach
 	Expect(err).ToNot(HaveOccurred())
 	return vm
 }
+
+func waitForVMStateTransition(virtClient kubecli.KubevirtClient, vm *v1.VirtualMachine, expectedStates []v1.VirtualMachinePrintableStatus, timeoutDuration time.Duration) {
```
Comment (0xFelix) [inline tests/vm_test.go:1276]:
```suggestion
func waitForVMStateTransition(vm *v1.VirtualMachine, expectedStates []v1.VirtualMachinePrintableStatus, timeoutDuration time.Duration) {
```

Consider using `virtClient := kubevirt.Client()` instead.

File: tests/vm_test.go [hunk 4]
```diff
@@ -528,11 +528,16 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
...
+			maxImgPullRetries := 2 // max number of image pull (re)tries
+			expectedStates := []v1.VirtualMachinePrintableStatus{}
+			for range maxImgPullRetries {
+				// each image pull (re)try should take the VM
+				// from status ErrImagePull to ImagePullBackOff
+				expectedStates = append(expectedStates, v1.VirtualMachineStatusErrImagePull)
+				expectedStates = append(expectedStates, v1.VirtualMachineStatusImagePullBackOff)
 			}
+
+			waitForVMStateTransition(virtClient, vm, expectedStates, 600*time.Second)
```
Comment (0xFelix) [inline tests/vm_test.go:540]: Can we lower the timeout?

**Review by 0xFelix — COMMENTED** [review]
Thanks! Got some questions.

File: tests/vm_test.go (hunk 2 above)
Comment (harshitgupta1337) [reply tests/vm_test.go:537]: I would like to retain the logic wherein the test checks the expected state transitions over 2 image pull retries. Will update accordingly with your suggestion!

File: tests/vm_test.go (hunk 4 above)
Comment (harshitgupta1337) [reply tests/vm_test.go:540]: Previously this test had 4 timeout checks, each 5 mins long. 5 mins is the longest backoff duration in K8s. 
In its updated form, the testcase code does not guarantee exactly when in the ` `... -> ErrImagePull -> ImagePullBackOff -> ...` state-transition sequence the Watch starts. So I am assuming the worst case scenario, where the max backoff grace period (5 mins) is used.
Since we need to verify one full transition from `ErrImagePull -> ImagePullBackOff`, we should wait atleast 5 mins plus the time taken to attempt image pull twice and other K8s/KubeVirt overheads. I can change the timeout to be 6 minutes to account for that.

Comment (harshitgupta1337) [reply tests/vm_test.go]: To address another comment, we are now setting per state-transition timeout. I have set it to account for the worst-case backoff grace period and expected worst-case time to attempt image pull. That comes down to 330 seconds.

File: tests/vm_test.go (hunk 2 above)
Comment (harshitgupta1337) [reply tests/vm_test.go]: Applied the suggested change.

File: tests/vm_test.go (hunk 1 above)
Comment (harshitgupta1337) [reply tests/vm_test.go]: Applied the suggested change.

File: tests/vm_test.go (hunk 3 above)
Comment (harshitgupta1337) [reply tests/vm_test.go]: Applied the suggested change.

File: tests/vm_test.go [hunk 5]
```diff
@@ -528,11 +529,14 @@ var _ = Describe("[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:com
...
 			By("Verifying that the status toggles between ErrImagePull and ImagePullBackOff")
-			const times = 2
-			for i := 0; i < times; i++ {
-				Eventually(ThisVM(vm), 300*time.Second, 1*time.Second).Should(HavePrintableStatus(v1.VirtualMachineStatusErrImagePull))
-				Eventually(ThisVM(vm), 300*time.Second, 1*time.Second).Should(HavePrintableStatus(v1.VirtualMachineStatusImagePullBackOff))
+			expectedStates := []v1.VirtualMachinePrintableStatus{
+				// State transitions a single image pull attempt
+				v1.VirtualMachineStatusErrImagePull,
+				v1.VirtualMachineStatusImagePullBackOff,
 			}
```
Comment (fossedihelm) [inline tests/vm_test.go:536]:
```suggestion
			expectedStates := []v1.VirtualMachinePrintableStatus{
				// State transitions a single image pull attempt
				v1.VirtualMachineStatusErrImagePull,
				v1.VirtualMachineStatusImagePullBackOff,
				v1.VirtualMachineStatusErrImagePull,
				v1.VirtualMachineStatusImagePullBackOff,
			}
```

Comment (fossedihelm) [reply tests/vm_test.go:536]: Don't we need to test the toggle twice?

**Review by fossedihelm — COMMENTED** [review]
Thank you! 
last thing from my side

File: tests/vm_test.go (hunk 5 above)
Comment (harshitgupta1337) [reply tests/vm_test.go:536]: Yeah, that's what the original test case checks. Will do that, and increase the timeout.

**Review by 0xFelix — COMMENTED** [review]
/approve

Please add a `None` release note.
