### PR TITLE
fix(virt-controller): Skip ControllerRevisionRef capture if Matchers nil

### LINKED ISSUE #16071: Unsafe reference check when copying preferences/instance data
**What happened**:
virt-controller crash with panic when it tries to copy `preferenceRef` into not defined `preference` stanza in `spec` of the VirtualMachine yaml.

Following chunk of code (even in latest release) make an assumption that when `preferenceRef` is present in `status` that accompanied `preference` is present in `spec` also, but that might not be a case and it will panic:
https://github.com/kubevirt/kubevirt/blob/v1.6.2/pkg/virt-controller/watch/vm/vm.go#L1694:L1700

virt-controller panic log:
```
{"component":"virt-controller","kind":"VirtualMachine","level":"info","msg":"Starting VM due to runStrategy: Always","name":"vm-name-1","namespace":"default","pos":"vm.go:988","timestamp":"2025-09-04T08:08:14.719933Z","uid":"46c6e0c7-9c73-4c4e-9a3e-c0b96816b7cd"}
E0904 08:08:14.720145       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
  goroutine 1537 [running]:
  k8s.io/apimachinery/pkg/util/runtime.logPanic({0x291b898, 0x3ecf7c0}, {0x219f580, 0x3d66b60})
    /remote-source/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
  k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x291b898, 0x3ecf7c0}, {0x219f580, 0x3d66b60}, {0x3ecf7c0, 0x0, 0x10000000000002b?})
    /remote-source/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
  k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2b?})
    /remote-source/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
  panic({0x219f580?, 0x3d66b60?})
    /usr/lib/golang/src/runtime/panic.go:791 +0x132
  kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.patchVMRevision(0xc00b232248?)
    /remote-source/app/pkg/virt-controller/watch/vm/vm.go:1644 +0xc1
  kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.(*Controller).createVMRevision(0xc0051983c0, 0xc00b232248)
```

VirtualMachine yaml definition:
```
spec:
  runStrategy: Always
  template: ...
status:
  preferenceRef:
    controllerRevisionRef:
      name: vm-name-1-windows.2k19-v1beta1-509e1d2d-6d7f-4ab3-9eab-a324cc2369a8-3
    kind: virtualmachineclusterpreference
    name: windows.2k19
```

P.S. I'm willing to provide patch for this, depending on approach that is accepted as resolution:
- Either create Preference object if non exising
- Skip setting if Preference object is not present

**What you expected to happen**:
For virt-controller not to panic, but either report error or skip. In current situation the whole cluster is in problematic state, as virt-controller pods are crash looping and you cannot do any VM management.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VM with `spec.preference` populated.`
2. Start VM
3. Stop VM - Verify that `preferenceRef` is present in `status`
4. Update VM resource and remove `preference` stanza
5. Start VM - Observe panic in virt-controller

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v1.5.2-46-g571e29909b", GitCommit:"571e29909ba7c44c07a1a6e7b55c39146cd6e91f", GitTreeState:"clean", BuildDate:"2025-08-02T19:33:00Z", GoVersion:"go1.23.9 (Red Hat 1.23.9-1.el9_6) X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.5.3-31-gbc1d1e0386", GitCommit:"bc1d1e0386117bd307f675db871dcf58ff405e27", GitTreeState:"clean", BuildDate:"2025-10-18T18:19:04Z", GoVersion:"go1.23.9 (Red Hat 1.23.9-1.el9_6) X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.32.6
```
- VM or VMI specifications: Added above
- Cloud provider or hardware configuration: OpenShift

### PR DESCRIPTION
**Pull request by lyarwood**
### What this PR does
As set out in bug #16071 virt-controller would previously panic if a user removed an instance type or preference from the spec from an existing VM before restarting it to force a new VM ControllerRevision to be captured.

This fix avoids the panic for now by skipping the attempted capture of instance type and preference ControllerRevisionRefs if the associated spec fields are already nil.

A follow up fix will also handle clearing of these ControllerRevisionRefs from status when the spec fields are initially removed from the VM.

### References
- Fixes #16071

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-controller/watch/vm/vm.go [hunk 1]
```diff
@@ -1678,10 +1678,10 @@ func getVMRevisionName(vmUID types.UID, generation int64) string {
 
 func patchVMRevision(vm *virtv1.VirtualMachine) ([]byte, error) {
 	vmCopy := vm.DeepCopy()
-	if revision.HasControllerRevisionRef(vmCopy.Status.InstancetypeRef) {
+	if vmCopy.Spec.Instancetype != nil && revision.HasControllerRevisionRef(vmCopy.Status.InstancetypeRef) {
```
Comment (xpivarc) [inline pkg/virt-controller/watch/vm/vm.go:1681]:
```
func HasControllerRevisionRef(ref *virtv1.InstancetypeStatusRef) bool {
	return ref != nil && ref.ControllerRevisionRef != nil && ref.ControllerRevisionRef.Name != ""
}
```
Isn't this handled already?

Comment (lyarwood) [reply pkg/virt-controller/watch/vm/vm.go:1681]: That's checking `vm.status.{instancetypeRef,preferenceRef}` the issue here is that we didn't check that `vm.spec.{instancetype,preference}` wasn't `nil` before trying to set `vm.spec.{instancetype,preference}.revisionName`.

Comment (xpivarc) [reply pkg/virt-controller/watch/vm/vm.go:1681]: oh my

**Review by jean-edouard — APPROVED** [review]

**Comment by victortoso** [comment]
There was an issue with the bot + retest.
https://github.com/kubevirt/project-infra/pull/4533

I'm just trying to help move some forward...

/unhold
/test pull-kubevirt-e2e-k8s-1.34-sig-compute-serial
/test pull-kubevirt-e2e-k8s-1.34-sig-network
