### PR TITLE
e2e, net, vmi_networking: Adjust IPv6 tests to fedora 39

### LINKED ISSUE #15886: [IPv6] Networking VirtualMachineInstance with masquerade binding mechanism [test_id:1780]
# What happened
Different tests in this table have been flaking randomly since Oct 8th 2025, with close correlation to the merge of https://github.com/kubevirt/kubevirt/pull/13322.
Note that only ipv6 lane has been demonstrating this flake. 

Flaky test detected: test_id:1780 [1]

/kind flake

/sig network

[1]: https://prow.ci.kubevirt.io/job-history/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network

## Additional context

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

### PR DESCRIPTION
**Pull request by frenzyfriday**
### What this PR does
Fedora version of the VMI under test was upgraded to 39 in #13322. Passing an empty `nameserver:{}` to the newer (23.2.1) version of cloud-init causes it to fail. It is recommended to either pass a value or omit the field. 

Additionally, the VMI is not able to get a IPv4 address from DHCP in a single stack environment. This causes Network manager to fail and the interface does not receive its static IPv6 address. DHCP4 is not supposed to work in a single stack environment. Removing DHCP4 from the network data does not affect the test as only IPv6 connectivity is being tested.

### References
- Fixes #15886

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
According to  https://pkg.go.dev/encoding/json, 
`The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any array, slice, map, or string of length zero.`
omitempty does not work on structs, so nameservers is passed as {} instead of being omitted in the current code.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by frenzyfriday** [comment]
/test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus "should allow regular network connection IPv6 with custom CIDR \[IPv6\]"

/test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus  "should allow regular network connection IPv6 without a specific port number \[IPv6\]"

**Comment by oshoval** [comment]
/test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus "should allow regular network connection IPv6"

just want to see if it triggers the lane

**Comment by oshoval** [comment]
/test-subset pull-kubevirt-e2e-k8s-1.34-sig-network --filter USB

this one worked, the other one didnt

**Comment by oshoval** [comment]
> /test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus "should allow regular network connection IPv6"

Hi @dhiller 
can you look please if you see something in the logs ?
it didnt work with this command
thnaks

**Comment by dhiller** [comment]
> pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network

log message:
```
{"event-guid":"97d7a6a0-b330-11f0-97c6-aa8abac2daf7","level":"error","msg":"comment does not match the expected syntax, /test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus \"should allow regular network connection IPv6\"\r\n\r\njust want to see if it triggers the lane","time":"2025-10-27T12:29:35Z"}
```

**Comment by dhiller** [comment]
> omment does not match the expected syntax

https://github.com/kubevirt/project-infra/blob/8ad3cfef4aab20777c05bc6e2ce2b15b20efca18/external-plugins/test-subset/plugin/handler/handler.go#L185

FYI @oshoval

**Comment by oshoval** [comment]
> > omment does not match the expected syntax
> 
> https://github.com/kubevirt/project-infra/blob/8ad3cfef4aab20777c05bc6e2ce2b15b20efca18/external-plugins/test-subset/plugin/handler/handler.go#L185
> 
> FYI @oshoval

Thanks Daniel !

**Comment by oshoval** [comment]
/test-subset pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network --focus "should allow regular network connection IPv6"


EDIT - now it works
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/15955/test-subset-pull-kubevirt-e2e-k8s-1.34-ipv6-sig-network/1984967502194544640

problem was that no other text than the command is allowed

File: tests/libnet/cloudinit/cloudinit.go [hunk 1]
```diff
@@ -133,19 +133,19 @@ type CloudInitNetworkData struct {
...
-	Routes         []CloudInitRoute     `json:"routes,omitempty"`
-	SetName        string               `json:"set-name,omitempty"`
+	AcceptRA       *bool                 `json:"accept-ra,omitempty"`
+	Addresses      []string              `json:"addresses,omitempty"`
+	DHCP4          *bool                 `json:"dhcp4,omitempty"`
+	DHCP6          *bool                 `json:"dhcp6,omitempty"`
+	DHCPIdentifier string                `json:"dhcp-identifier,omitempty"` // "duid" or  "mac"
+	Gateway4       string                `json:"gateway4,omitempty"`
+	Gateway6       string                `json:"gateway6,omitempty"`
+	Nameservers    *CloudInitNameservers `json:"nameservers,omitempty"`
```
Comment (nirdothan) [inline tests/libnet/cloudinit/cloudinit.go:143]: Are you suggesting that there was a bug here and that the type has to be a pointer? The commit message only describes an issue with empty nameservers.

File: tests/network/vmi_networking.go [hunk 2]
```diff
@@ -411,7 +411,6 @@ var _ = Describe(SIG("[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:
 			}
 			networkData, err := cloudinit.NewNetworkData(
 				cloudinit.WithEthernet("eth0",
-					cloudinit.WithDHCP4Enabled(),
```
Comment (nirdothan) [inline tests/network/vmi_networking.go:414]: I've tested it with both flannel and calico and did not notice a difference. In both cases NetworkManager service was in failed status.  Hence I think that it is not the root cause.
I would just write that DHCP4 is not expected to work in a single stack cluster and that since it's an IPV6 test, the VM does not need an IPv4 address anyway.

File: tests/network/vmi_networking.go [hunk 3]
```diff
@@ -525,7 +524,7 @@ var _ = Describe(SIG("[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:
 				Expect(libnet.PingFromVMConsole(vmi, dns, "-c 5", "-w 15")).To(Succeed())
 			})
 
-			DescribeTable("[QUARANTINE] IPv6", decorators.Quarantine, func(ports []v1.Port, tcpPort int, networkCIDR string) {
```
Comment (nirdothan) [inline tests/network/vmi_networking.go:528]: Please consider separating the de-quarantine to a separate commit.

File: tests/libnet/cloudinit/cloudinit.go (hunk 1 above)
Comment (frenzyfriday) [reply tests/libnet/cloudinit/cloudinit.go:143]: I just want that `nameservers` field should be omitted when we are not passing any value there. 
Example: right now we are passing this `{'ethernets': {'eth0': {'addresses': ['fd10:0:2::2/120'], 'dhcp4': True, 'gateway6': 'fd10:0:2::1', 'match': {}, 'nameservers': {}}}, 'version': 2}` . 
Instead we should be passing `{'ethernets': {'eth0': {'addresses': ['fd10:0:2::2/120'], 'dhcp4': True, 'gateway6': 'fd10:0:2::1', 'match': {}, }}, 'version': 2}`

I thought one of the ways to do it was changing `CloudInitNameservers` to pointer. Do you have an alternate approach in mind?

File: tests/network/vmi_networking.go (hunk 3 above)
Comment (frenzyfriday) [reply tests/network/vmi_networking.go:528]: ack, updated now.

File: tests/network/vmi_networking.go (hunk 2 above)
Comment (frenzyfriday) [reply tests/network/vmi_networking.go:414]: ack, updated now.

File: tests/libnet/cloudinit/cloudinit.go (hunk 1 above)
Comment (nirdothan) [reply tests/libnet/cloudinit/cloudinit.go:143]: I tried to find a simple alternative approach, but the only solution I could find involved re-implementing the json marshaller.

**Review by nirdothan — APPROVED** [review]
Thank you!
/cc @EdDev

File: tests/libnet/cloudinit/cloudinit.go (hunk 1 above)
Comment (oshoval) [reply tests/libnet/cloudinit/cloudinit.go:143]: Worth to add this to the PR desc please

Cloud init error

```
cloudinit.net.network_state.InvalidCommand: Command missing {'address'} of required keys ['address']
```

```
2025-10-27 14:50:45,039 - network_state.py[WARNING]: Skipping invalid command: {'eth0': {'addresses': ['fd10:0:2::2/120'], 'dhcp4': True, 'dhcp6': False, 'gateway6': 'fd10:0:2::1', 'match': {}, 'nameservers': {}}}
```

It comes from `@ensure_command_keys(["address"])`
https://raw.githubusercontent.com/canonical/cloud-init/23.2.1/cloudinit/net/network_state.py

```
    @ensure_command_keys(["address"])
    def handle_nameserver(self, command):
```

File: tests/network/vmi_networking.go (hunk 2 above)
Comment (EdDev) [reply tests/network/vmi_networking.go:414]: The function this resides in does not hint this is an IPv6 special VM, which makes the whole things very confusing.

In a follow up, please extract this out to a regular function and name it accordingly.
