### PR TITLE
Fix behaivor of MaxCpuSockets

### LINKED ISSUE #12394: Unable to start VMs with more CPUs than defined in LiveUpdateConfiguration
**What happened**:
A VM cannot be created.
Configuration
```
kv.Spec.Configuration.LiveUpdateConfiguration = &v1.LiveUpdateConfiguration{
		MaxCpuSockets: kvpointer.P(uint32(4)),
	}
```

VM with
```
corev1.ResourceCPU:    resource.MustParse("5"),
```

Leads to 
```
Failure while starting VMI: admission webhook \"virtualmachineinstances-create-validator.kubevirt.io\" denied the request: Number of sockets in CPU topology is greater than the maximum sockets allowed
```

**What you expected to happen**:
Be able to create VMs with more CPUs than what is default in LiveUpdateConfiguration. 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by xpivarc**
### What this PR does
See issue for background. Now `MaxCpuSockets` will no be used if a VM defines more sockets but rather the #of sockets will be used for `MaxSockets`.

Fixes #12394

Links to places where the discussion took place: 

### Release note

```release-note
MaxCpuSockets won't block creation of VMs with more Sockets than MaxCpuSockets declare
```

### CODE REVIEW

**Comment by xpivarc** [comment]
Based on https://github.com/kubevirt/kubevirt/pull/12583

File: pkg/virt-api/webhooks/defaults.go [hunk 1]
```diff
@@ -69,7 +69,11 @@ func setupHotplug(clusterConfig *virtconfig.ClusterConfig, vmi *v1.VirtualMachin
 
 func setupCPUHotplug(clusterConfig *virtconfig.ClusterConfig, vmi *v1.VirtualMachineInstance) {
 	if vmi.Spec.Domain.CPU.MaxSockets == 0 {
-		vmi.Spec.Domain.CPU.MaxSockets = clusterConfig.GetMaximumCpuSockets()
+		maxSockets := clusterConfig.GetMaximumCpuSockets()
+		if vmi.Spec.Domain.CPU.Sockets > maxSockets && maxSockets != 0 {
```
Comment (acardace) [inline pkg/virt-api/webhooks/defaults.go:73]: nit: why do you need to check that `maxSockets != 0` ?

Comment (lyarwood) [reply pkg/virt-api/webhooks/defaults.go:73]: I'm not a huge fan of helpers like `GetMaximumCpuSockets` hiding that `MaxCpuSockets` is actually a pointer. It doesn't massively matter in this case but it's much easier to assert if something isn't configured by checking for `nil` as opposed to default values like `0` or `false` with bools.

File: staging/src/kubevirt.io/api/core/v1/types.go [hunk 2]
```diff
@@ -3010,7 +3010,8 @@ type LiveUpdateConfiguration struct {
 	// defined and MaxHotplugRatio is 2 then MaxGuest = 1Gi
 	// defaults to 4
 	MaxHotplugRatio uint32 `json:"maxHotplugRatio,omitempty"`
-	// MaxCpuSockets holds the maximum amount of sockets that can be hotplugged
+	// MaxCpuSockets holds the maximum amount of sockets that can be hotplugged for VMs that don't specify MaxSockets.
```
Comment (lyarwood) [inline staging/src/kubevirt.io/api/core/v1/types.go:3013]:
```suggestion
	// MaxCpuSockets provides a MaxSockets value for VMs that do not provide their own.
        // MaxSockets defining the total number of sockets that can be hot-plugged into a running VM.
	// MaxCpuSockets is ignored if a VM requests more sockets than MaxCpuSockets with the VM requested number of sockets being used as the MaxSockets value instead.

**Comment by xpivarc** [comment]
@lyarwood  Can't reply directly https://github.com/kubevirt/kubevirt/pull/12599#discussion_r1763757824 so here I go. I agree with you, the fact Antonio asked about the same proves this is wrong but I want to backport this so I am keeping it small intentionally.

PTAL
