### PR TITLE
unit, arm64: skip cpu hotplug unit test on Arm64

### LINKED ISSUE #13451: The Arm64 unit test lane Failed
**What happened**:
The Arm64 unit test lane keep failing. [Arm64 Unit Test](https://prow.ci.kubevirt.io/?job=pull-kubevirt-unit-test-arm64)
All failures caused by one test
```
//pkg/virt-launcher/virtwrap/converter:go_default_test: Converter with v1.VirtualMachineInstance when CPU spec defined should define hotplugable default topology
```

**What you expected to happen**:
Make it pass

### PR DESCRIPTION
**Pull request by zhlhahaha**
Arm64 does not support CPU hotplug now, we can skip the test

Fixes #13451

### Release note
```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
cc: @dhiller @brianmcarey @xpivarc

**Review by 0xFelix — COMMENTED** [review]
This should not be dependent on the architecture of the host running the test. Can you make this a table that explicitly provides converters for all architectures that support hotplug instead? (similar to how it is done in L709)

**Review by 0xFelix — COMMENTED** [review]
Looks good to me but I'd like to ask @fossedihelm for confirmation.

File: pkg/virt-launcher/virtwrap/converter/converter_test.go [hunk 1]
```diff
@@ -917,13 +917,15 @@ var _ = Describe("Converter", func() {
...
-			It("should define hotplugable default topology", func() {
+			DescribeTable("should define hotplugable default topology", func(arch string) {
 				v1.SetObjectDefaults_VirtualMachineInstance(vmi)
 				vmi.Spec.Domain.CPU = &v1.CPU{
 					Cores:      2,
 					MaxSockets: 3,
 					Sockets:    2,
 				}
+				c.Architecture = NewArchConverter(arch)
+				vmiArchMutate(arch, vmi, c)
```
Comment (fossedihelm) [inline pkg/virt-launcher/virtwrap/converter/converter_test.go:928]: I think this is not needed and can be dropped

Comment (zhlhahaha) [reply pkg/virt-launcher/virtwrap/converter/converter_test.go]: Updated

**Review by fossedihelm — APPROVED** [review]
Thank you!

**Comment by fossedihelm** [comment]
Oh god!I totally forgot about this PR... my bad... https://github.com/kubevirt/kubevirt/pull/13488

**Review by xpivarc — COMMENTED** [review]
/approve
