### PR TITLE
webhooks: Fix setPreferenceStorageClassName during mutation

### LINKED ISSUE #9868: Runtime error when creating a `VirtualMachine` using a `VirtualMachinePreference` with `preferredStorageClassName` set but no `PVC` provided within the spec of a DVT
/area instancetype

**What happened**:

`PVC` is an optional attribute of `DataVolumeSpec`:

https://github.com/kubevirt/kubevirt/blob/bce7bee3cd33b98ab1647e56464d8e7267aa1869/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go#L52-L53

At the moment `setPreferenceStorageClassName` doesn't check if it's set and checks the storage class:

https://github.com/kubevirt/kubevirt/blob/bce7bee3cd33b98ab1647e56464d8e7267aa1869/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go#L202

That leads to the following runtime error:

```
$ ./cluster-up/kubectl.sh apply -f - <<EOF
 ---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: storageclass
spec:
  volumes:
    preferredStorageClassName: ocs-storagecluster-ceph-rbd
EOF
$ ./cluster-up/virtctl.sh create vm --preference storageclass --volume-import type:registry,name:cirros,url:registry:5000/kubevirt/cirros-container-disk-demo:devel,size:1G 
selecting podman as container runtime
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: vm-dgz9f
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: cirros
    spec:
      source:
        registry:
          url: registry:5000/kubevirt/cirros-container-disk-demo:devel
      storage:
        resources:
          requests:
            storage: 1G
  preference:
    name: storageclass
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices: {}
        memory:
          guest: 512Mi
        resources: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: cirros
        name: cirros
status: {}
$ ./cluster-up/virtctl.sh create vm --preference storageclass --volume-import type:registry,name:cirros,url:registry:5000/kubevirt/cirros-container-disk-demo:devel,size:1G | ./cluster-up/kubectl.sh apply -f -
selecting podman as container runtime
selecting podman as container runtime
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": EOF
```
```
$ ./cluster-up/kubectl.sh -n kubevirt logs virt-api-547fb7bcf8-hptg4 | grep panic
[..]
 {"component":"virt-api","level":"info","msg":"http: panic serving 192.168.66.101:24791: runtime error: invalid memory address or nil pointer dereference\ngoroutine 2644 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1850 +0xbf\npanic({0x1f6a0c0, 0x3a40800})\n\tGOROOT/src/runtime/panic.go:890 +0x262\nkubevir │
│ t.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook/mutators.(*VMsMutator).setPreferenceStorageClassName(...)\n\tpkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:202\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook/mutators.(*VMsMutator).Mutate(0xc005507600?, 0xc0043118c0)\n\tpkg/virt-api/webhooks/mutating-web │
│ hook/mutators/vm-mutator.go:125 +0xf65\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook.serve({0x28a2ec0, 0xc004fe4fc0}, 0x800?, {0x2883a60, 0xc0028c7950})\n\tpkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go:57 +0xfc\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/mutating-webhook.ServeVMs(...)\n\tpkg/virt-api/webhook │
│ s/mutating-webhook/mutating-webhook.go:80\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerMutatingWebhook.func1({0x28a2ec0, 0xc004fe4fc0}, 0x21d73e0?)\n\tpkg/virt-api/api.go:887 +0xfc\nnet/http.HandlerFunc.ServeHTTP(0xc004fe4fc0?, {0x28a2ec0?, 0xc004fe4fc0?}, 0x22804f9?)\n\tGOROOT/src/net/http/server.go:2109 +0x2f\nnet/http.(* │
│ ServeMux).ServeHTTP(0xc003fbc75d?, {0x28a2ec0, 0xc004fe4fc0}, 0xc005507600)\n\tGOROOT/src/net/http/server.go:2487 +0x149\nnet/http.serverHandler.ServeHTTP({0x2892ba0?}, {0x28a2ec0, 0xc004fe4fc0}, 0xc005507600)\n\tGOROOT/src/net/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc005dce8c0, {0x28a4058, 0xc003453170})\n\tGOROOT/src/net │
│ /http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\tGOROOT/src/net/http/server.go:3102 +0x4db\n","pos":"server.go:3230","timestamp":"2023-06-07T12:32:48.216529Z"}      
```

**What you expected to happen**:
We should create the `PVC` object if it isn't already present within `DataVolumeSpec`.

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @opokornyy 

**What this PR does / why we need it**:

PersistentVolumeClaimSpec is an optional attribute of DataVolumeSpec but wasn't previously checked by setPreferenceStorageClassName. This change fixes this and reworks unit tests that were also not correctly asserting the behaviour of setPreferenceStorageClassName as the VirtualMachine provided contained no DataVolumeTemplates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9868

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by opokornyy** [comment]
Thanks for the fix Lee!

/lgtm

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 1]
```diff
@@ -196,11 +196,11 @@ func (mutator *VMsMutator) setPreferenceStorageClassName(vm *v1.VirtualMachine,
...
-	if preferenceSpec != nil && preferenceSpec.Volumes != nil {
-		datavolumes := vm.Spec.DataVolumeTemplates
-		for _, dv := range datavolumes {
-			if dv.Spec.PVC.StorageClassName == nil {
-				dv.Spec.PVC.StorageClassName = &preferenceSpec.Volumes.PreferredStorageClassName
+	if preferenceSpec != nil && preferenceSpec.Volumes != nil && preferenceSpec.Volumes.PreferredStorageClassName != "" {
+		preferredStorageClassName := preferenceSpec.Volumes.PreferredStorageClassName
+		for _, dv := range vm.Spec.DataVolumeTemplates {
+			if dv.Spec.PVC != nil && dv.Spec.PVC.StorageClassName == nil {
+				dv.Spec.PVC.StorageClassName = &preferredStorageClassName
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:203]: Would `dv.Spec.PVC.StorageClassName = &preferenceSpec.Volumes.PreferredStorageClassName` work too?

Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go]: Done
