### PR TITLE
Let the operator remove virt-controller generated traces

### LINKED ISSUE #1491: Uninstall/cleanup procedures
I don't have a lot of logs backing this because my lab cluster has been in a lot of flux lately but I was running into an issue where the kube-controller-manager pods were crashing whenever a newer version of kubevirt was installed which would cause complete unstability within the cluster.  

```
E0813 19:17:56.372793       1 memcache.go:153] couldn't get resource list for subresources.kubevirt.io/v1alpha1: the server could not find the requested resource
E0813 19:17:56.422505       1 memcache.go:153] couldn't get resource list for subresources.kubevirt.io/v1alpha2: <nil>
```

I had no idea where those were coming from until today when I looked at the apiservice objects.

```
 gageorsburn@mbp  ~/Projects/osi/slackforward   master  kubectl get apiservices | grep kubevirt
v1alpha1.cdi.kubevirt.io                3d
v1alpha1.subresources.kubevirt.io       103d
v1alpha2.subresources.kubevirt.io       33d
```

I think older versions are causing issues. Kind of a weird issue/hard to word. It might be good to start some documentation keeping track of all of the resources that need to be cleaned up across version upgrades, uninstalls, etc.

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

virt-api registers apiservices and webhooks which it does not delete. On
uninstall during the operator this lead to incomplete uninstalls which
could block future namespace deletions.

While letting still virt-api creating all these objects, let
virt-operator now manage their removal. The control is still not fully
handed over to virt-operator since there are still people using the
manifest-only installation path without the operator.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1491 

**Special notes for your reviewer**:

**Release note**:

```release-note
Uninstall via the operator catches now all artifacts. Deleted namespaces should no longer be stuck forever after uninstalling kubevirt correctly.
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

Functional test is there but some unit tests are missing.

File: pkg/virt-api/api.go [hunk 1]
```diff
@@ -776,6 +778,10 @@ func (app *virtAPIApp) createValidatingWebhook() error {
 		}
 	} else {
 
+		// Ensure that we have the operator label attached, so that the operator can manage the resource later
+		// This is part of a soft transition from behing controlled by the apiserver, to being controlled by the operator
+		webhookRegistration.Labels[v1.ManagedByLabel] = v1.ManagedByLabelOperatorValue
```
Comment (danielBelenky) [inline pkg/virt-api/api.go]: Are webhooks namespaced? won't we hit the namespaced owner which owns a non-namespaced resource issue?

Comment (rmohr) [reply pkg/virt-api/api.go]: We only add a label, no owner references.

Comment (danielBelenky) [reply pkg/virt-api/api.go]: Right! :smile:

File: tests/operator_test.go [hunk 2]
```diff
@@ -873,6 +873,18 @@ spec:
 			By("Sanity Checking Deployments infrastructure is deleted")
 			sanityCheckDeploymentsDeleted()
 
+			By("ensuring that namespaces can be successfully created and deleted")
```
Comment (rmohr) [inline tests/operator_test.go]: This should in future prevent that we leave anything behind which can block namespace management.

File: pkg/virt-operator/creation/rbac/operator.go [hunk 3]
```diff
@@ -231,6 +231,18 @@ func NewOperatorClusterRole() *rbacv1.ClusterRole {
 				},
 				Resources: []string{
 					"validatingwebhookconfigurations",
+					"mutatingwebhookconfigurations",
```
Comment (danielBelenky) [inline pkg/virt-operator/creation/rbac/operator.go]: I'm not sure that this should be a ClusterRole... can it be just a role in the deployment namespace?

Comment (rmohr) [reply pkg/virt-operator/creation/rbac/operator.go]: I don't think it changes anything regarding to security and we would have to maintain an extra role for the virt-operator service account.

Comment (danielBelenky) [reply pkg/virt-operator/creation/rbac/operator.go]: It does allow kubevirt to create `mutatingwebhookconfigurations` across the entire cluster unnecessarily. Though it's not a security issue by it's own, some cluster admin may wonder why this is needed.

With that said, since we currently do not maintain a role, I agree that it shouldn't be part of this PR

Comment (rmohr) [reply pkg/virt-operator/creation/rbac/operator.go]: webhook configurations are not namespaced.

**Comment by rmohr** [comment]
/approve

@danielBelenky thx for the review.

File: pkg/virt-operator/creation/rbac/operator.go (hunk 3 above)
Comment (danielBelenky) [reply pkg/virt-operator/creation/rbac/operator.go]: :+1: good point. :smile: 
so forget my comment.
