### PR TITLE
vmsnapshot: when checking if a VM is running, ignore runStrategy

### LINKED ISSUE #12515: Snapshot Creation Fails for Powered-Off VM with RerunOnFailure RunStrategy
**What happened**:
The snapshot creation failed for a vm that is powered off with runStrategy of RerunOnFailure.

**What you expected to happen**:
create snapshot for stopped vm with  runStrategy of RerunOnFailure successfully. 

**How to reproduce it (as minimally and precisely as possible)**:
```
# kubectl get vm -n vm-4c1f62f0 i-a6rrn1s8  -o json | jq .status.printableStatus
"Stopped"
# kubectl get vm -n vm-4c1f62f0 i-a6rrn1s8 -o json | jq .spec.runStrategy
"RerunOnFailure"

# cat create.yaml 
apiVersion: snapshot.kubevirt.io/v1alpha1
kind: VirtualMachineSnapshot
metadata:
  name: wyw-snap-3
  namespace: vm-4c1f62f0
spec:
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: i-a6rrn1s8

# kubectl apply -f create.yaml 
virtualmachinesnapshot.snapshot.kubevirt.io/wyw-snap-3 created

after 5 minutes...
# kubectl get vmsnapshots  -n vm-4c1f62f0 
NAME           SOURCEKIND       SOURCENAME   PHASE       READYTOUSE   CREATIONTIME   ERROR            
wyw-snap-3     VirtualMachine   i-a6rrn1s8   Failed      false                    

# kubectl describe  vmsnapshots  -n vm-4c1f62f0 wyw-snap-3 
Name:         wyw-snap-3
Namespace:    vm-4c1f62f0
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.kubevirt.io/v1alpha1
Kind:         VirtualMachineSnapshot
Metadata:
  Creation Timestamp:  2024-08-01T23:04:56Z
  Finalizers:
    snapshot.kubevirt.io/vmsnapshot-protection
  Generation:        3
  Resource Version:  11509507
  UID:               7a7407c6-1b77-48fb-8348-543bb9c264cd
Spec:
  Source:
    API Group:  kubevirt.io
    Kind:       VirtualMachine
    Name:       i-a6rrn1s8
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2024-08-01T23:04:56Z
    Reason:                Source not locked
    Status:                False
    Type:                  Progressing
    Last Probe Time:       <nil>
    Last Transition Time:  2024-08-01T23:04:56Z
    Reason:                Not ready
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  2024-08-01T23:10:24Z
    Reason:                snapshot deadline exceeded
    Status:                True
    Type:                  Failure
  Indications:
    Online
    NoGuestAgent
  Phase:         Failed
  Ready To Use:  false
  Source UID:    a67a5317-cbe4-4025-9a54-dfd1c264fdc6
Events:          <none>
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.0
- Kubernetes version (use `kubectl version`): 1.27.6
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 5.10.0-136.12.0.86.4.hl202.x86_64

### PR DESCRIPTION
**Pull request by mhenriks**
Just look for a VMI

### What this PR does
Before this PR:

Would check the VM run strategy when determining when a VM is running. Current code has faulty assumption that `Always` or `RerunOnFailure` means that VM cannot be stopped

After this PR:

Don't check .

Fixes #12515

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
vmsnapshot: when checking if a VM is running, ignore runStrategy
```

### CODE REVIEW

**Comment by alicefr** [comment]
@mhenriks should we add a functional test that create a snapshot from a stopped VM with the RunStrategy=`RerunOnFailur`?
Otherwise, the code looks good.

**Comment by mhenriks** [comment]
> @mhenriks should we add a functional test that create a snapshot from a stopped VM with the RunStrategy=`RerunOnFailur`? Otherwise, the code looks good.

I thought about it but given that we are trying to be more deliberate and purposeful with func tests I'm not sure it makes sense here.  The goal of the PR is to make vm run strategy irrelevant so why create a new test with a specific runstrategy? I'm certainly open to it though

**Comment by alicefr** [comment]
Fine to me
/approve

File: pkg/storage/snapshot/source.go [hunk 1]
```diff
@@ -286,17 +286,12 @@ func (s *vmSnapshotSource) Spec() (snapshotv1.SourceSpec, error) {
 }
 
 func (s *vmSnapshotSource) Online() (bool, error) {
-	vmRunning, err := checkVMRunning(s.vm)
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/source.go:289]: I get that the runstrategy now doesnt promise us the status of the vm if it is stopped/stopping/starting/started.
But the existence of VMI doesnt ensure it either since its racefull.. I am a bit concerned of unexpected behaviors in case of someone stopping/starting a VM and do vmsnapshot at the same time. WDYT?

Comment (mhenriks) [reply pkg/storage/snapshot/source.go:289]: I don't think there is any way to avoid a race. In the case you describe, the controller may attempt to freeze the VM and fail but on subsequent reconcile, `source.Online()` will be false and freeze will be skipped.

Comment (ShellyKa13) [reply pkg/storage/snapshot/source.go:289]: Im more worried on the opposite case where it will skip freeze because it was marked as offline..

Comment (mhenriks) [reply pkg/storage/snapshot/source.go:289]: What's the problem there exactly?  If the snapshot is completed before the VMI exists it is technically an offline snapshot.

Comment (ShellyKa13) [reply pkg/storage/snapshot/source.go:289]: If the vmi didnt exist right at the time where the freeze didnt occur and then was created and written to then the snapshot is taken then the snapshot might not be valid.. I know its a longshot and possibly a very (very) small window but theoretically possible

Comment (mhenriks) [reply pkg/storage/snapshot/source.go:289]: I'm not sure how we can entirely eliminate that race without having some higher level synchronization. Creating a restore and starting a VMI are fundamentally two independent operations.  Checking VM runStrategy is not helpful and can cause problems like described in the linked issue. The goal of this PR is to eliminate the downsides of checking runStrategy

Comment (ShellyKa13) [reply pkg/storage/snapshot/source.go:289]: You are right this is a race we can't entirely eliminate. So I'm not against merging this PR, but how about thinking of a way to check if there was a change in the snapshot "online/offline" vm state after "locking" the vm from changing state since as we said its a bit racefull. Something like comparing the state of the vm before "unlocking" it and see if it changed comparing to how we expected it to be, specifically if we marked it as offline but it got online somehow and if so to mark the snapshot as failed.

Comment (mhenriks) [reply pkg/storage/snapshot/source.go:289]: Yeah maybe that is something we can handle in another PR

**Review by ShellyKa13 — APPROVED** [review]
/lgtm
