### PR TITLE
VMI: Sort network interfaces to avoid patch flood

### LINKED ISSUE #14442: High rate of patch requests to kube API for VM pod
**What happened**:

We are seeing ~30Mbps of network traffic from kube-apiserver inbound to our worker node (TCP port 6443). Analysis of the kubernetes API audit log revealed that almost all traffic is related to requests by user`system:serviceaccount:kubevirt:kubevirt-controller` sending patch requests to update a VM pod annotation with path `/metadata/annotations/kubevirt.io~1network-info`. The API response contains a large payload, which I believe explains the high volume of data being sent to the worker node.

See attached file 'patch.json' - an example request/response taken from the k8s api audit log.

**What you expected to happen**:

This volume of patching seems way too high.

**How to reproduce it (as minimally and precisely as possible)**:

Create a k0s cluster with 2 controllers (kine backend) and 1 worker node. Deploy a VM that uses SRIOV interfaces. After some time the API traffic will appear.

**Additional context**:

The cluster has a single VM deployed with 16 SRIOV VFs attached. We have observed the same behaviour on another, identical cluster. We are using [sriov-network-operator](https://github.com/k8snetworkplumbingwg/sriov-network-operator]) and [multus](https://github.com/k8snetworkplumbingwg/multus-cni) for the CNI components.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.4.0
- Kubernetes version (use `kubectl version`): v1.31.2+k0s
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: AWS ec2 instance for controllers, bare metal for worker
- OS (e.g. from /etc/os-release): Debian 12
- Kernel (e.g. `uname -a`): controller: 6.1.0-31-cloud-amd64, worker: 6.1.0-27-amd64
- Install tools: N/A
- Others: N/A

[patch.json](https://github.com/user-attachments/files/19642276/patch.json)

<details>
<summary>vm.yaml</summary>

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  creationTimestamp: "2025-03-20T20:10:17Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  generation: 1
  name: vm-102737
  namespace: vms
  resourceVersion: "3509086"
  uid: fe30c52f-3752-4b26-8d9a-f6b2d6afc999
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: 102737-data-volume-template-image
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://xxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/esp-vm-images:mve_6wind-vsr-x86_64-v3.8.4.1
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 29Gi
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 6
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
        devices:
          disks:
          - disk:
              bus: virtio
            name: volume-image
          - disk:
              bus: virtio
            name: volume-day0
          interfaces:
          - bridge: {}
            macAddress: 02:c6:2b:64:54:40
            name: mgmt-bridge
            pciAddress: "0000:09:00.0"
          - macAddress: 02:cf:2b:01:ed:67
            name: sriov-if-102737-1123
            pciAddress: "0000:10:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:68
            name: sriov-if-102737-3826
            pciAddress: "0000:11:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:69
            name: sriov-if-102737-3551
            pciAddress: "0000:12:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6a
            name: sriov-if-102737-2895
            pciAddress: "0000:13:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6b
            name: sriov-if-102737-1804
            pciAddress: "0000:14:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6c
            name: sriov-if-102737-3428
            pciAddress: "0000:15:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6d
            name: sriov-if-102737-2342
            pciAddress: "0000:16:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6e
            name: sriov-if-102737-2286
            pciAddress: "0000:17:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:6f
            name: sriov-if-102737-1803
            pciAddress: "0000:18:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:70
            name: sriov-if-102737-508
            pciAddress: "0000:19:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:71
            name: sriov-if-102737-513
            pciAddress: "0000:20:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:72
            name: sriov-if-102737-1057
            pciAddress: "0000:21:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:73
            name: sriov-if-102737-507
            pciAddress: "0000:22:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:74
            name: sriov-if-102737-1186
            pciAddress: "0000:23:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:75
            name: sriov-if-102737-3940
            pciAddress: "0000:24:00.0"
            sriov: {}
          - macAddress: 02:cf:2b:01:ed:76
            name: sriov-if-102737-407
            pciAddress: "0000:25:00.0"
            sriov: {}
          rng: {}
        machine:
          type: q35
        memory:
          hugepages:
            pageSize: 1Gi
        resources:
          requests:
            memory: 24Gi
      networks:
      - multus:
          networkName: default/mgmt-bridge
        name: mgmt-bridge
      - multus:
          networkName: default/sriov-net-102737-1123
        name: sriov-if-102737-1123
      - multus:
          networkName: default/sriov-net-102737-3826
        name: sriov-if-102737-3826
      - multus:
          networkName: default/sriov-net-102737-3551
        name: sriov-if-102737-3551
      - multus:
          networkName: default/sriov-net-102737-2895
        name: sriov-if-102737-2895
      - multus:
          networkName: default/sriov-net-102737-1804
        name: sriov-if-102737-1804
      - multus:
          networkName: default/sriov-net-102737-3428
        name: sriov-if-102737-3428
      - multus:
          networkName: default/sriov-net-102737-2342
        name: sriov-if-102737-2342
      - multus:
          networkName: default/sriov-net-102737-2286
        name: sriov-if-102737-2286
      - multus:
          networkName: default/sriov-net-102737-1803
        name: sriov-if-102737-1803
      - multus:
          networkName: default/sriov-net-102737-508
        name: sriov-if-102737-508
      - multus:
          networkName: default/sriov-net-102737-513
        name: sriov-if-102737-513
      - multus:
          networkName: default/sriov-net-102737-1057
        name: sriov-if-102737-1057
      - multus:
          networkName: default/sriov-net-102737-507
        name: sriov-if-102737-507
      - multus:
          networkName: default/sriov-net-102737-1186
        name: sriov-if-102737-1186
      - multus:
          networkName: default/sriov-net-102737-3940
        name: sriov-if-102737-3940
      - multus:
          networkName: default/sriov-net-102737-407
        name: sriov-if-102737-407
      nodeSelector:
        kubernetes.io/hostname: ams-tc5-vr-4
      terminationGracePeriodSeconds: 10
      volumes:
      - dataVolume:
          name: 102737-data-volume-template-image
        name: volume-image
      - cloudInitNoCloud:
          secretRef:
            name: 102737-cloudinitdata
        name: volume-day0
```
</details>

### PR DESCRIPTION
**Pull request by ianb-mp**
### What this PR does
Before this PR:

`/status/interfaces` would be constantly patched due to the non-deterministic network interface slices causing DeepEqual to return false.

After this PR:

Patch flood is prevented.

Fixes #14442 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-controller/watch/vmi/lifecycle.go [hunk 1]
```diff
@@ -548,6 +549,14 @@ func prepareVMIPatch(oldVMI, newVMI *virtv1.VirtualMachineInstance) *patch.Patch
 		}
 	}
 
+	// Sort network interfaces by name to ensure that the order does not affect the equality check.
+	// Prior to this an API patch flood would occur - see: https://github.com/kubevirt/kubevirt/issues/14442
+	cmpFunc := func(a, b virtv1.VirtualMachineInstanceNetworkInterface) int {
+		return strings.Compare(a.Name, b.Name)
+	}
+	slices.SortFunc(oldVMI.Status.Interfaces, cmpFunc)
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/lifecycle.go:557]: Could this possibly corrupt the cache? Do we need to copy `oldVMI.Status.Interfaces`?

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 2]
```diff
@@ -830,6 +831,41 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
 		})
 	})
 
+	Context("VMI patch", func() {
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi_test.go:834]: Can you test this from a "higher" level, i.e. running `sanityExecute` on the controller to assert this behavior? This would ensure we are not corrupting the cache.

File: pkg/virt-controller/watch/vmi/lifecycle.go (hunk 1 above)
Comment (orelmisan) [reply pkg/virt-controller/watch/vmi/lifecycle.go:557]: I agree that it would be preferable to sort a copy of `oldVMI.Status.Interfaces`.

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 3]
```diff
@@ -830,6 +831,41 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
+		oldVMI := newPendingVirtualMachine("oldvmi")
+		newVMI := newPendingVirtualMachine("newvmi")
+
+		oldVMI.Status.Interfaces = []virtv1.VirtualMachineInstanceNetworkInterface{
+			{Name: "stubNetStatusUpdate1"},
+			{Name: "stubNetStatusUpdate2"},
+		}
```
Comment (orelmisan) [inline pkg/virt-controller/watch/vmi/vmi_test.go:841]: Currently, these three variables are shared between the tests in a way that creates a dependency between them.
Please consider using a [BeforeEach](https://onsi.github.io/ginkgo/#extracting-common-setup-beforeeach) stanza to initialize the variables, or alternatively - repeat the initialization in both tests.

**Review by orelmisan — COMMENTED** [review]
Thank you for the PR @ianb-mp!
Just two small comments.

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 2 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vmi/vmi_test.go:834]: You could do it as a follow up if it's to hard to do right now. But please address the issue mentioned above.

File: pkg/virt-controller/watch/vmi/lifecycle.go (hunk 1 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/lifecycle.go]: I've pushed a fix which uses `slices.SortedFunc()` instead.

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 3 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: I've pushed a fix for this now.

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 2 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go:834]: I've pushed a fix which sorts a copy of each slice, so as not to corrupt any cache.

**Comment by ianb-mp** [comment]
It'd be ideal if this fix could be back ported to 1.4 and included in a future 1.4.1 release. @orelmisan is that feasible?
It will mean moving the changes from lifecycle.go to vmi.go due to the changes made as part of PR https://github.com/kubevirt/kubevirt/pull/14238

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 4]
```diff
@@ -830,6 +831,47 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
 		})
 	})
 
+	Context("VMI patch", func() {
+		var oldVMI *virtv1.VirtualMachineInstance
+		var newVMI *virtv1.VirtualMachineInstance
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi_test.go:836]: nit: Use var block

```suggestion
		var (
			oldVMI *virtv1.VirtualMachineInstance
			newVMI *virtv1.VirtualMachineInstance
		)
```

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 5]
```diff
@@ -830,6 +831,47 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
+
+		BeforeEach(func() {
+			oldVMI = newPendingVirtualMachine("oldvmi")
+			newVMI = newPendingVirtualMachine("newvmi")
+
+			oldVMI.Status.Interfaces = []virtv1.VirtualMachineInstanceNetworkInterface{
+				{Name: "stubNetStatusUpdate1"},
+				{Name: "stubNetStatusUpdate2"},
+			}
+
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi_test.go:846]: nit: empty line

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 6]
```diff
@@ -830,6 +831,47 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
+		})
+
+		It("should create empty status network interfaces patch, regardless of interfaces order", func() {
+
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi_test.go:850]: nit: Same

File: pkg/virt-controller/watch/vmi/vmi_test.go [hunk 7]
```diff
@@ -830,6 +831,47 @@ var _ = Describe("VirtualMachineInstance watcher", func() {
...
+			slices.Reverse(newVMI.Status.Interfaces)
+
+			patch := prepareVMIPatch(oldVMI, newVMI)
+
+			Expect(patch).ToNot(BeNil(), "Patch should not be nil")
+			Expect(patch.IsEmpty()).To(BeTrue(), "Patch should be empty")
+		})
+
+		It("should create non empty status network interfaces patch", func() {
+
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi_test.go:862]: nit: Same again

**Review by 0xFelix — COMMENTED** [review]
Some nits, otherwise looks good. 

/test pull-kubevirt-unit-test

File: pkg/virt-controller/watch/vmi/lifecycle.go [hunk 8]
```diff
@@ -548,8 +549,16 @@ func prepareVMIPatch(oldVMI, newVMI *virtv1.VirtualMachineInstance) *patch.Patch
 		}
 	}
 
+	// Sort network interfaces by name to ensure that the order does not affect the equality check.
+	// Prior to this an API patch flood would occur - see: https://github.com/kubevirt/kubevirt/issues/14442
+	cmpFunc := func(a, b virtv1.VirtualMachineInstanceNetworkInterface) int {
+		return strings.Compare(a.Name, b.Name)
+	}
+	newInterfaces := slices.SortedFunc(slices.Values(newVMI.Status.Interfaces), cmpFunc)
+	oldInterfaces := slices.SortedFunc(slices.Values(oldVMI.Status.Interfaces), cmpFunc)
```
Comment (orelmisan) [inline pkg/virt-controller/watch/vmi/lifecycle.go:558]: I'm unsure if `slices.Values` actually copies the slice.
`slices.Clone()` [2] performs a shallow copy which will work in this case.

[1] https://pkg.go.dev/slices#Values
[2] https://pkg.go.dev/slices#Clone

**Review by orelmisan — COMMENTED** [review]
Thank you for the changes @ianb-mp.
Just one small thing from my side, otherwise looks good.

File: pkg/virt-controller/watch/vmi/lifecycle.go (hunk 8 above)
Comment (0xFelix) [reply pkg/virt-controller/watch/vmi/lifecycle.go:558]: > SortedFunc collects values from seq into a new slice, sorts the slice using the comparison function, and returns it.

Sounds like it but now we're back to `sanityExecute`

Comment (fossedihelm) [reply pkg/virt-controller/watch/vmi/lifecycle.go:558]: I cannot see the `sanityExecute` usage in the test

Comment (orelmisan) [reply pkg/virt-controller/watch/vmi/lifecycle.go:558]: Using `sanityExecute` is probably preferable but is not that simple.
I think that cloning the slices is sufficient for this PR, and we could consider adjusting the test in a follow-up.

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 4 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: fixed

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 5 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go]: fixed

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 7 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go:860]: fixed

File: pkg/virt-controller/watch/vmi/vmi_test.go (hunk 6 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/vmi_test.go:849]: fixed

File: pkg/virt-controller/watch/vmi/lifecycle.go (hunk 8 above)
Comment (ianb-mp) [reply pkg/virt-controller/watch/vmi/lifecycle.go:558]: > I'm unsure if `slices.Values` actually copies the slice. `slices.Clone()` [2] performs a shallow copy which will work in this case.
> 
> [1] https://pkg.go.dev/slices#Values [2] https://pkg.go.dev/slices#Clone

`slices.Values` doesn't copy the slice, but `slices.SortedFunc` does - that should be sufficient right?

**Review by 0xFelix — COMMENTED** [review]
Can you please squash commits?

/approve

File: pkg/virt-controller/watch/vmi/lifecycle.go (hunk 8 above)
Comment (orelmisan) [reply pkg/virt-controller/watch/vmi/lifecycle.go:558]: > > I'm unsure if `slices.Values` actually copies the slice. `slices.Clone()` [2] performs a shallow copy which will work in this case.
> > [1] https://pkg.go.dev/slices#Values [2] https://pkg.go.dev/slices#Clone
> 
> `slices.Values` doesn't copy the slice, but `slices.SortedFunc` does - that should be sufficient right?

Thank you for explaining, I haven't had a chance to use this function yet.

**Review by orelmisan — APPROVED** [review]
Thank you for your contribution @ianb-mp!

**Review by orelmisan — APPROVED** [review]

**Comment by EdDev** [comment]
> It'd be ideal if this fix could be back ported to 1.4 and included in a future 1.4.1 release. @orelmisan is that feasible? (I'm happy to create the PR). It will mean moving the changes from lifecycle.go to vmi.go due to the changes made as part of PR #14238

Yes, we should backport to 1.5 and then to 1.4.
Can be done automatically to 1.5?

**Comment by orelmisan** [comment]
> It'd be ideal if this fix could be back ported to 1.4 and included in a future 1.4.1 release. @orelmisan is that feasible? (I'm happy to create the PR). It will mean moving the changes from lifecycle.go to vmi.go due to the changes made as part of PR #14238

@ianb-mp Please see https://github.com/kubevirt/kubevirt/pull/14687.
