### PR TITLE
Dockerized build

### LINKED ISSUE #628: Build executables on the same environment used for running
While building on F27 and deploying, the virt-handler pod fails to start, with below error message

```
/virt-handler: /lib64/libvirt.so.0: version `LIBVIRT_3.7.0' not found (required by /virt-handler)
/virt-handler: /lib64/libvirt.so.0: version `LIBVIRT_3.4.0' not found (required by /virt-handler)
```
Following are the steps used:
On the host F27, execute the following commands
```
cd $GOPATH/src/kubevirt.io/kubevirt
vagrant up
make vagrant-deploy
```
The virt-handler is built using F27 which is referring to higher libvirt-libs version, where as the docker image is built on top of F26 with libvirt-libs-3.2.1-7.fc26 version. 

Modifying the virt-handler Dockerfile to F27 is working fine, but wondering if there is a better solution - to use the same os version to build on which it will be deployed.

### PR DESCRIPTION
**Pull request by rmohr**
Allow building kubevirt in a docker container:

```bash
git clone https://github.com/kubevirt/kubevirt
cd kubevirt
./hack/dockerized make generate fmt fmt-bash build
./hack/dockerized make apidocs
```
 * Fixes #628 in a not completely elegant way, since we would still have to make sure that the LIBVIRT_VERSION alligns in the virt-handler Dockerfile and the builder dockerfile.
 * Groud work for #534 .
 * Brings in a new enough mercural version for travis to work
 * The vagrant provider does not yet use the dockerized builder for synchronization

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
@nertpinx @petrkotas

**Comment by petrkotas** [comment]
I must say, great job. I like it. Just some minor question.

File: builder.sh [hunk 1]
```diff
@@ -0,0 +1,3 @@
+#!/bin/bash
+
+docker run --rm -v "${PWD}:/go/src/kubevirt.io/kubevirt" -w "/go/src/kubevirt.io/kubevirt" -v "${HOME}/.glide:/home/user/.glide" -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -it kubevirt/builder "$@"
```
Comment (petrkotas) [inline builder.sh]: In general, do we want project dependencies to be on the dev machine?
I see benefit in both, having it inside of the container and having it on the dev machine.
The first would lead to more stable builds, the second for more flexible dev environment.

I am tempted to vote for the stable one, to create single stable environment for each developer to work with.

**Comment by rmohr** [comment]
@mpolednik created a script which copies the kubernetes way of doing dockerized builds: https://github.com/mpolednik/byoc. I think I want to adopt that pattern.

**Comment by rmohr** [comment]
@mpolednik it is still a little bit ugly but it mostly works now. Maybe you can give it an initial review?

File: hack/dockerized [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+(cd ${DOCKER_DIR} && docker build . -t ${BUILDER})
+docker volume create --name ${BUILDER}
+docker run -v "${BUILDER}:/root:rw,z" --rm -it ${BUILDER} mkdir -p /root/go/src/kubevirt.io/kubevirt/_out
+
+_rsync() {
+    RSYNC_CID=$(docker run -d -v "${BUILDER}:/root:rw,z" -p 127.0.0.1:10873:873 ${BUILDER} /usr/bin/rsync --no-detach --daemon --verbose)
+    echo "Syncing ..."
+    # TODO improve that
+    sleep 1
```
Comment (mpolednik) [inline hack/dockerized]: Why the sleep here?

File: hack/docker-builder/Dockerfile [hunk 3]
```diff
@@ -0,0 +1,33 @@
+FROM fedora:27
```
Comment (mpolednik) [inline hack/docker-builder/Dockerfile]: (++code below) I find this approach a bit too `packed`. Having separate container dedicated for rsync and building scales better to the future - different builds (such as generator) can be handled by their own container. Although not visible now, the dockerfile could eventually grow to un-manageable size.

File: hack/dockerized [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    docker rm ${RSYNC_CID}
+}
+
+_rsync --delete --exclude '.glide*' --exclude "cluster/vagrant/.kubeconfig" --exclude "cluster/vagrant/.kubectl" --exclude "vendor" --exclude "_out" --exclude ".vagrant" --exclude ".git" ${KUBEVIRT_DIR}/ "rsync://root@127.0.0.1:10873/build"
+
+set -e
+docker run --rm -v "${BUILDER}:/root:rw,z" -w "/root/go/src/kubevirt.io/kubevirt" -it ${BUILDER} "$@"
+set +e
+
+# TODO do this in one call
```
Comment (mpolednik) [inline hack/dockerized]: Should be done before we get this in IMHO.

**Comment by mpolednik** [comment]
In general, I'm happy with the current direction. After fiddling around with kubernetes builds, I've found several `architectural decisions` that aren't obvious initially but help in the long run - such as having separate rsync container and build containers. The artifact caching is handled by using a single volume, and the whole reason for that is to keep the bash scripts and dockerfile(s) manageable. That could be considered future improvement though - I believe this change is needed asap to streamline builds.

File: hack/dockerized (hunk 2 above)
Comment (rmohr) [reply hack/dockerized]: I wonder why that ever worked for you without the `sleep`. the rsync daemon is just not ready fast enough, that is the reason why the follow up rsync fails for me if I don't wait.

File: hack/docker-builder/Dockerfile (hunk 3 above)
Comment (rmohr) [reply hack/docker-builder/Dockerfile]: I totally understand what you mean and I agree. As you mentioned, let's do that in the future.

**Comment by rmohr** [comment]
@mpolednik thx for the quick review. Will send the updates tomorrow. :+1:

**Comment by rmohr** [comment]
ok to test

**Comment by rmohr** [comment]
ok to test

File: hack/dockerized [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+# Build the build container
+(cd ${DOCKER_DIR} && docker build . -q -t ${BUILDER})
+
+# Create the persistent docker volume
+if [ -z "$(docker volume list | grep ${BUILDER})" ]; then
+    docker volume create --name ${BUILDER}
+fi
+
+# Make sure that the output directory exists
+docker run -v "${BUILDER}:/root:rw,z" --rm -it ${BUILDER} mkdir -p /root/go/src/kubevirt.io/kubevirt/_out
```
Comment (davidvossel) [inline hack/dockerized]: It's unclear to me why we need this persistent volume and why we're rsyncing to it. At first glance this all seems a bit more complicated than it needs to be. maybe I'm missing something?

If I was approaching building kubevirt assents using a docker container, I'd just bind mount the src tree directly into the docker container and then run the normal build steps in the container rather than directly on the host. The container would have all the build tools, but it would be working directly on the src tree in the host file system.

Comment (rmohr) [reply hack/dockerized]: > If I was approaching building kubevirt assents using a docker container, I'd just bind mount the src tree directly into the docker container and then run the normal build steps in the container rather than directly on the host. The container would have all the build tools, but it would be working directly on the src tree in the host file system.

I had exactly that before, but there are a few issues with it (I erased the commit history of it in this PR). Issues are:
 * It is not possible to bind-mount with the right uid/gid
 * It is then extremely complex to synchronize uids und gids
 * Bind mounts are extremely slow. Surprisingly rsyncing in- and out and building inside is much-much faster (except from the rsync overhead pretty much the same like direct building)
 * With the docker volume in place, a developer gets dependency caching for free
 * It works pretty nice, k8s does it too

Comment (nertpinx) [reply hack/dockerized]: - If you run the container as your UID/GID it just works, there is no uid/gid sync you need to do. That's how I do it. Maybe your docker daemon is missing something?
- How are bind mounts slow? Aren't you missing some kernel functionality? Do you mean the mounting is slow or the access to thos files is then slow? What filesystem are you using?

**Comment by nertpinx** [comment]
So what's the way to deploy kubevirt into the vagrant maching with this in place?

I started with clean tree, did `make cluster-up`, then `hack/dockerized make build`, but then how should I do cluster-sync? If I do it in the docker image it won't have access to the config files. If I do it on the host it starts rebuilding the binaries again.

**Comment by rmohr** [comment]
> So what's the way to deploy kubevirt into the vagrant maching with this in place?

with this PR merged, the cluster sync still builds everything without docker. Once #647 is merged `make cluster-sync` will work transparently with docker.
