### PR TITLE
fix: Do not panic when specifying preferSpread without instancetype

### LINKED ISSUE #11057: VirtualMachine with Preference using preferSpread but without Instancetype cannot be created
**What happened**:

When trying to create a VirtualMachine which is using a VirtualMachinePreference that sets the CPU topology to `preferSpread` but not specifying a VirtualMachineInstancetype, the VM creation fails and the `virt-api` VM admitter panics/crashes.

```
{"component":"virt-api","level":"info","msg":"http: panic serving 192.168.66.101:64673: runtime error: invalid memory address or nil pointer dereference\ngoroutine 621 [running]:\nnet/http.(*conn).serve.func1()\n\tGOROOT/src/net/http/server.go:1868 +0xb9\npanic({0x1fee540?, 0x3a3f480?})\n\tGOROOT/src/runtime/panic.go:920 +0x270\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.(*VMsAdmitter).applyInstancetypeToVm(0xc0034d5220, 0xc004b2dc00)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:280 +0x26b\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook/admitters.(*VMsAdmitter).Admit(0xc0034d5220, 0xc000e662d0)\n\tpkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:146 +0x2a5\nkubevirt.io/kubevirt/pkg/util/webhooks/validating-webhooks.Serve({0x2805d70, 0xc003514380}, 0x0?, {0x27f3b80, 0xc0034d5220})\n\tpkg/util/webhooks/validating-webhooks/validating-webhook.go:73 +0xba\nkubevirt.io/kubevirt/pkg/virt-api/webhooks/validating-webhook.ServeVMs({0x2805d70, 0xc003514380}, 0x0?, 0xc003c5e7e0, {0x2833908?, 0xc0002b4500}, 0xc005a9c9c0)\n\tpkg/virt-api/webhooks/validating-webhook/validating-webhook.go:43 +0x167\nkubevirt.io/kubevirt/pkg/virt-api.(*virtAPIApp).registerValidatingWebhooks.func3({0x2805d70?, 0xc003514380?}, 0x7e2f8d?)\n\tpkg/virt-api/api.go:874 +0x31\nnet/http.HandlerFunc.ServeHTTP(0x10?, {0x2805d70?, 0xc003514380?}, 0xc0022f64ac?)\n\tGOROOT/src/net/http/server.go:2136 +0x29\nnet/http.(*ServeMux).ServeHTTP(0x412065?, {0x2805d70, 0xc003514380}, 0xc00353a300)\n\tGOROOT/src/net/http/server.go:2514 +0x142\nnet/http.serverHandler.ServeHTTP({0x27fa120?}, {0x2805d70?, 0xc003514380?}, 0x6?)\n\tGOROOT/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc000e8b710, {0x2814258, 0xc0052acd80})\n\tGOROOT/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 205\n\tGOROOT/src/net/http/server.go:3086 +0x5cb\n","pos":"server.go:3214","timestamp":"2024-01-22T09:25:53.523171Z"}
```

**What you expected to happen**:

The VirtualMachine was created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Use attached YAML to create a VM and observe `virt-api` logs. 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-9htzn
spec:
  preference:
    name: centos.stream9.dpdk
  running: false
  template:
    spec:
      domain:
        devices: {}
        memory:
          guest: 1536Mi
        resources: {}
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/centos-stream:9
        name: vm-9htzn-containerdisk-0
status: {}
```

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

This fixes the VMI admitter, so VMs with a preference specifying preferSpread as the CPU topology and without an instancetype can be created without the VMI admitter panicking.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #11057 

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [x] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [x] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go [hunk 1]
```diff
@@ -43,6 +43,7 @@ import (
 	k8sfake "k8s.io/client-go/kubernetes/fake"
 	"k8s.io/client-go/testing"
 	"k8s.io/client-go/tools/cache"
+	"k8s.io/utils/ptr"
```
Comment (fossedihelm) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go:46]: This cam be avoided. There is already the `"kubevirt.io/kubevirt/pkg/pointer"` package, which can be used as
```
pointer.P(instancetypev1beta1.PreferSpread)
```

Comment (0xFelix) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go]: Updated

**Review by fossedihelm — APPROVED** [review]
Thanks!

**Review by enp0s3 — APPROVED** [review]
/approve

@0xFelix Thank you for taking care of it!

File: pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go [hunk 2]
```diff
@@ -267,11 +267,7 @@ func (admitter *VMsAdmitter) applyInstancetypeToVm(vm *v1.VirtualMachine) (*inst
 		}}
 	}
 
-	if instancetypeSpec == nil && preferenceSpec == nil {
-		return nil, nil, nil
-	}
-
-	if topology := instancetype.GetPreferredTopology(preferenceSpec); topology == instancetypev1beta1.PreferSpread {
+	if topology := instancetype.GetPreferredTopology(preferenceSpec); instancetypeSpec != nil && topology == instancetypev1beta1.PreferSpread {
```
Comment (alicefr) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: nit: can we split this into 2 lines. I find it a bit complex with 2 conditions

Comment (0xFelix) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: I wanted to, but `make format` did have another opinion. Want me to move it out of the if condition?

Comment (alicefr) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: Ah I see, mh... do you know if at a certain point we want to make it mandatory or are those only suggestions?

Comment (alicefr) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: Anyway, it is just a nit comment, feel free to ignore it

Comment (0xFelix) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: I think it is already sort of mandatory. Once you run `make format` it will format the whole code base (not just your changes) and IDE's usually run formatting on every save too.

Comment (alicefr) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go:270]: ok, then let's leave it like this
