### PR TITLE
virt-controller/watch/vmi: Bug Fix: Ensure Stuck Finalized Launcher Pods Are Deleted in virt-controller

### LINKED ISSUE #12931: proposal: fix or delete quarantined flaky test `[test_id:3007][QUARANTINE] Should force restart a VM with terminationGracePeriodSeconds>0`
**What happened**:
The test `[test_id:3007][QUARANTINE] Should force restart a VM with terminationGracePeriodSeconds>0` [1] has been quarantined [2] in May 2024. Attempts to fix it seem to haven't had any effect.

Therefore we are asking for 

/sig compute

to either fix the test within four weeks or give

/sig ci

the ack for deletion of the 

/kind flake

test.

Evidence:
* https://search.ci.kubevirt.io/?search=test_id%3A3007&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
* https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.31-sig-compute&width=5
* https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.30-sig-compute&width=5
* https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.29-sig-compute&width=5

[1]: https://github.com/kubevirt/kubevirt/blob/b09f8ce0865120437d6ef452c177ff2fb155c4a4/tests/subresource_api_test.go#L225
[2]: https://github.com/kubevirt/kubevirt/pull/11910/

**What you expected to happen**:
Test should have been repaired.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
FYI @fossedihelm @akalenyu @jean-edouard @xpivarc

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by dasionov**
This PR fixes a bug in virt-controller where finalized launcher pods (Succeeded/Failed) could remain stuck in the cluster.

Previously, the controller only checked for pod deletion but did not handle cases where terminated pods were lingering due to slow garbage collection, collection thresholds, or other factors.

Now, the controller explicitly deletes finalized pods if they are detected as stuck, ensuring they do not block further operations.

Fixes #12931

### Release note
```release-note
Ensure launcher pods are finalized and deleted before removing the VMI finalizer when the VMI is marked for deletion.  
```

### CODE REVIEW

File: tests/compute/vm_lifecycle.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ var _ = SIGDescribe("[rfe_id:1177][crit:medium] VirtualMachine", func() {
 		virtClient = kubevirt.Client()
 	})
 
-	It("[test_id:3007][QUARANTINE] Should force restart a VM with terminationGracePeriodSeconds>0", decorators.Quarantine, func() {
+	It("[test_id:3007] Should force restart a VM with terminationGracePeriodSeconds>0", func() {
```
Comment (fossedihelm) [inline tests/compute/vm_lifecycle.go:51]: Shouldn't we wait for some data from periodic before remove from quarantine?
@brianmcarey keep me honest here

**Review by fossedihelm — COMMENTED** [review]
Thank you @dasionov 
I only have one question to the sig-ci

File: pkg/virt-controller/watch/vmi/vmi.go [hunk 2]
```diff
@@ -1504,11 +1507,11 @@ func (c *Controller) deleteAllMatchingPods(vmi *virtv1.VirtualMachineInstance) e
...
 	for _, pod := range pods {
-		if pod.DeletionTimestamp != nil {
+		if !controller.IsControlledBy(pod, vmi) {
 			continue
 		}
 
-		if !controller.IsControlledBy(pod, vmi) {
+		if pod.DeletionTimestamp != nil && !isPodFinal(pod) {
 			continue
 		}
```
Comment (dasionov) [inline pkg/virt-controller/watch/vmi/vmi.go:1516]: Flipped the order here cause it seemed more important to check if the pod is actually owned by the VMI before checking if it has a `DeletionTimestamp`

File: tests/compute/vm_lifecycle.go (hunk 1 above)
Comment (dasionov) [reply tests/compute/vm_lifecycle.go:51]: Great question!

**Comment by fossedihelm** [comment]
/test pull-kubevirt-check-tests-for-flakes

@dasionov Let's run the check tests for flakes lane several times so that we can ensure the fix works

File: pkg/virt-controller/watch/vmi/vmi.go [hunk 3]
```diff
@@ -1504,22 +1507,26 @@ func (c *Controller) deleteAllMatchingPods(vmi *virtv1.VirtualMachineInstance) e
 	vmiKey := controller.VirtualMachineInstanceKey(vmi)
 
 	for _, pod := range pods {
-		if pod.DeletionTimestamp != nil {
+		if !controller.IsControlledBy(pod, vmi) {
 			continue
 		}
 
-		if !controller.IsControlledBy(pod, vmi) {
+		if pod.DeletionTimestamp != nil && !isPodFinal(pod) {
```
Comment (xpivarc) [inline pkg/virt-controller/watch/vmi/vmi.go:1514]: Please leave a comment (and commit message on why it is required)

File: tests/compute/vm_lifecycle.go (hunk 1 above)
Comment (xpivarc) [reply tests/compute/vm_lifecycle.go:51]: FYI https://github.com/kubevirt/kubevirt/blob/main/docs/quarantine.md#getting-tests-out-of-quarantine

File: pkg/virt-controller/watch/vmi/vmi.go (hunk 3 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vmi/vmi.go:1516]: Added a comment and also explained here why i flipped the order of the checks https://github.com/kubevirt/kubevirt/pull/13870#discussion_r1963326900

File: pkg/virt-controller/watch/vmi/vmi.go [hunk 4]
```diff
@@ -1504,22 +1507,28 @@ func (c *Controller) deleteAllMatchingPods(vmi *virtv1.VirtualMachineInstance) e
...
 
 		c.podExpectations.ExpectDeletions(vmiKey, []string{controller.PodKey(pod)})
 		err := c.clientset.CoreV1().Pods(vmi.Namespace).Delete(context.Background(), pod.Name, v1.DeleteOptions{})
 		if err != nil {
-			c.podExpectations.DeletionObserved(vmiKey, controller.PodKey(pod))
-			c.recorder.Eventf(vmi, k8sv1.EventTypeWarning, controller.FailedDeletePodReason, "Failed to delete virtual machine pod %s", pod.Name)
-			return err
+			if k8serrors.IsNotFound(err) {
+				c.podExpectations.DeletionObserved(vmiKey, controller.PodKey(pod))
+			} else {
```
Comment (xpivarc) [inline pkg/virt-controller/watch/vmi/vmi.go:1525]: The expectations cannot be conditioned otherwise you will block the next re-sync. So lets keep the original code.

**Comment by xpivarc** [comment]
@vladikr can you have a look as well?

File: pkg/virt-controller/watch/vmi/vmi.go (hunk 4 above)
Comment (dasionov) [reply pkg/virt-controller/watch/vmi/vmi.go]: fixed

File: pkg/virt-controller/watch/vmi/vmi.go [hunk 5]
```diff
@@ -1484,23 +1484,29 @@ func (c *Controller) deleteAllMatchingPods(vmi *virtv1.VirtualMachineInstance) e
...
 
-		if !controller.IsControlledBy(pod, vmi) {
+		if pod.DeletionTimestamp != nil && !isPodFinal(pod) {
 			continue
 		}
 
 		if err = c.deletePod(vmiKey, pod, v1.DeleteOptions{}); err != nil {
-			c.recorder.Eventf(vmi, k8sv1.EventTypeWarning, controller.FailedDeletePodReason, "Failed to delete virtual machine pod %s", pod.Name)
-			return err
+			if !k8serrors.IsNotFound(err) { // Skip the warning if the pod was already deleted, as this is an expected condition.
```
Comment (0xFelix) [inline pkg/virt-controller/watch/vmi/vmi.go:1496]: It might be cleaner to not emit the `SuccessfulDelete` event again, when it was already deleted?

File: tests/compute/vm_lifecycle.go (hunk 1 above)
Comment (0xFelix) [reply tests/compute/vm_lifecycle.go:51]: IIUC docs recommend to keep the quarantine for now?

Comment (fossedihelm) [reply tests/compute/vm_lifecycle.go:51]: @dasionov Please keep the QUARANTINE label.
We could create a un-quarantine PR once we get some results from the periodic lanes.
Thanks

Comment (dasionov) [reply tests/compute/vm_lifecycle.go]: done

**Comment by fossedihelm** [comment]
/lgtm
@0xFelix PTAL

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!
