### PR TITLE
Fix device manager test race

### LINKED ISSUE #2132: unit test device manager data race condition
/kind bug

**What happened**:

unit tests are failing due to a data race condition

```
••==================
WARNING: DATA RACE
Write at 0x00c0003a2120 by goroutine 7:
  kubevirt.io/kubevirt/pkg/virt-handler/device-manager.glob..func1.4.3()
      /root/go/src/kubevirt.io/kubevirt/pkg/virt-handler/device-manager/device_controller_test.go:108 +0x21e
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xbd
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x16a
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xa2
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:215 +0x766
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x145
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x172
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x4b6
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x149
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x3e1
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:221 +0x367
  kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.RunSpecs()
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:202 +0x99
  kubevirt.io/kubevirt/pkg/virt-handler/device-manager_test.TestDeviceManager()
      /root/go/src/kubevirt.io/kubevirt/pkg/virt-handler/device-manager/device_manager_suite_test.go:15 +0x148
  testing.tRunner()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x162

Previous read at 0x00c0003a2120 by goroutine 12:
  kubevirt.io/kubevirt/pkg/virt-handler/device-manager.(*DeviceController).startDevicePlugin()
      /root/go/src/kubevirt.io/kubevirt/pkg/virt-handler/device-manager/device_controller.go:85 +0x15c

Goroutine 7 (running) created at:
  testing.(*T).Run()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:878 +0x659
  testing.runTests.func1()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:827 +0x162
  testing.runTests()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /gimme/.gimme/versions/go1.11.5.linux.amd64/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:44 +0x221

Goroutine 12 (running) created at:
  kubevirt.io/kubevirt/pkg/virt-handler/device-manager.(*DeviceController).Run()
      /root/go/src/kubevirt.io/kubevirt/pkg/virt-handler/device-manager/device_controller.go:95 +0x179
==================

```

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Fix device manager tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2132 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-handler/device-manager/device_controller_test.go [hunk 1]
```diff
@@ -105,9 +104,9 @@ var _ = Describe("Device Controller", func() {
 
 		It("should restart the device plugin with delays if it returns errors", func() {
 			plugin2 = NewFakePlugin("fake-device2", devicePath2)
-			deviceController.backoff = []time.Duration{10 * time.Millisecond, 100 * time.Millisecond}
```
Comment (rmohr) [inline pkg/virt-handler/device-manager/device_controller_test.go]: This line was the cause.
