### PR TITLE
fix migration metrics being reported once per migration

### LINKED ISSUE #16437: virt-handler and virt-launcher consume CPU extremely high
**What happened**:
Three virtual machines were created with specifications of 1 vCPU/1 GB RAM, 1 vCPU/1 GB RAM, and 4 vCPUs/5 GB RAM, respectively. After powering on the VMs without running any workloads, it was observed that the CPU usage of virt-handler and virt-launcher was extremely high.The output of the top command is as follows:

Image

**Environment**:
- KubeVirt version (use `virtctl version`): 1.6.2
- Kubernetes version (use `kubectl version`): 1.32.0
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-119-generic

### PR DESCRIPTION
**Pull request by akalenyu**
### What this PR does
due to a logical error in the conditional for removing a finished
migrated vmi, migration metrics cannot be scraped more than once
per migration:
```
$ k -n kubevirt exec -it virt-handler-bfjxs -- curl -L -k https://localhost:8443/metrics | grep kubevirt_vmi_migration_data_processed_bytes
Defaulted container "virt-handler" out of: virt-handler, virt-launcher (init)
kubevirt_vmi_migration_data_processed_bytes{name="simple-vm",namespace="default",node="node02"} 8.406433792e+09 1767563479467
...
kubevirt_vmi_migration_data_processed_bytes{name="simple-vm",namespace="default",node="node02"} 8.963876263e+09 1767563524472
$ k -n kubevirt exec -it virt-handler-bfjxs -- curl -L -k https://localhost:8443/metrics | grep kubevirt_vmi_migration_data_processed_bytes
$
```

### References

- Fixes #16437

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
BugFix: migration metrics missing
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
trying to figure out functests so they catch continuous metric reporting

**Comment by akalenyu** [comment]
/hold

the functests will be in a separate PR, there's some challenges with slowing down the migration to catch that
(even with 1Ki policy and stress-ng)

File: pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go [hunk 1]
```diff
@@ -23,21 +23,27 @@ import (
 
 	"k8s.io/client-go/tools/cache"
 	v1 "kubevirt.io/api/core/v1"
+	"kubevirt.io/client-go/log"
 
 	"kubevirt.io/kubevirt/pkg/controller"
 )
 
+type vmiQueue interface {
```
Comment (xpivarc) [inline pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go:31]: I would prefer to no create an interface here, you can use https://github.com/kubevirt/kubevirt/pull/16471/commits/8d177e43d02c23d2a4d263c238b105e66df7c4d5

Comment (akalenyu) [reply pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go:31]: why not? we're unit testing the handler, queue is out of scope

File: tests/storage/migration.go [hunk 2]
```diff
@@ -401,6 +405,81 @@ var _ = Describe(SIG("Volumes update with migration", decorators.RequiresTwoSche
 			Entry("with post-copy", true),
 		)
 
+		It("should continously report storage migration metrics", func() {
```
Comment (machadovilaca) [inline tests/storage/migration.go:408]: why did you decide to not create this test in the monitoring folder?
i think since its basically validating metrics it would fit better there

Comment (akalenyu) [reply tests/storage/migration.go:408]: what we care about in sig-storage ecosystem is that storage migration reports properly. that is a bit domain specific to be under monitoring in my taste, but it's not a big deal to me. remember I could also make this a sig-monitoring test under sig-storage.

File: pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go (hunk 1 above)
Comment (xpivarc) [reply pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go:31]: It's merely preference but
1. There is no coverage of queue with your solution
2. There isn't really abstraction of handler and queue here anyway and there is no complexity that requires it really. 
3. It's just all in one package. 
4. It's straight forward to use the queue

Comment (akalenyu) [reply pkg/monitoring/metrics/virt-handler/migrationdomainstats/handler.go:31]: the queue deserves it's own tests, it's a dep of the handler
this unit test is isolating the issue in the handler (fails pre change succeeds post change) without ever involving the queue

**Review by xpivarc — COMMENTED** [review]
/approve
Can you link https://github.com/kubevirt/kubevirt/issues/16437 ?

File: tests/storage/migration.go (hunk 2 above)
Comment (sradco) [reply tests/storage/migration.go:408]: We should add monitoring related tests under the monitoring folder.
When we would separate monitoring out of core kubevirt it would make sense to have it in monitoring.

Comment (akalenyu) [reply tests/storage/migration.go:408]: I really want this test always running against kubevirt/kubevirt and under sig-storage. It's vital for us to be able to build upon this and shift left.
/cc @awels

**Review by dasionov — APPROVED** [review]
Hi @akalenyu, Thanks for this PR.
/lgtm

File: tests/storage/migration.go (hunk 2 above)
Comment (sradco) [reply tests/storage/migration.go:408]: what should we do then? Why is it vital to be in kubevirt/kubevirt ?

Comment (akalenyu) [reply tests/storage/migration.go:408]: these metrics are key for storage migrations, it's almost as if the feature is incomplete without them. it is because you move around large amount of data as opposed to regular migrations where disk is not transferred, just state

**Comment by vladikr** [comment]
@akalenyu @xpivarc should we backport this all the way to the original commit in 1.4?

**Comment by akalenyu** [comment]
> @akalenyu @xpivarc should we backport this all the way to the original commit in 1.4?

I think so, according to my investigation it looked like this dates back to the PR which introduced the mechanism. Would just like to double check with @machadovilaca if that makes sense.
