### PR TITLE
make use of context for vnc

### LINKED ISSUE #13414: virtctl vnc does not use a context
**What happened**:

virtctl vnc does not use a context and potentially leaks goroutines.

**What you expected to happen**:

virtctl vnc should use a context so that it can be shut down in a controlled manner and not leak any goroutines.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

See #13378 

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by mohit-nagaraj**
### What this PR does
Before this PR:
- `virtctl vnc` does not use a context, potentially leaking goroutines.

After this PR:
- `virtctl vnc` now uses a context, ensuring it can be shut down in a controlled manner without leaking goroutines.

Fixes #13414 

### Why we need it and why it was done in this way
Using a context ensures that virtctl vnc can be canceled gracefully, avoiding goroutine leaks. This approach follows idiomatic Go practices for managing the lifecycle of operations.

Links to places where the discussion took place: https://github.com/kubevirt/kubevirt/pull/13378#discussion_r1863782022

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by victortoso** [comment]
/cc

Feel free to ping when ready for review

**Comment by mohit-nagaraj** [comment]
@victortoso could you please give out a intial review? much appreciated

File: pkg/virtctl/vnc/vnc.go [hunk 1]
```diff
@@ -156,33 +163,46 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
 		if err != nil {
 			log.Log.V(2).Infof("Failed to accept unix sock connection. %s", err.Error())
 			listenResChan <- err
+			return
 		}
-		defer fd.Close()
+		go func() {
+			<-ctx.Done()
+			fd.Close()
```
Comment (victortoso) [inline pkg/virtctl/vnc/vnc.go:170]: And this one [5] should have a commit on its own. They were missing from the existing code base and are not part of adding the context.

Why fd.Close() in a goroutine instead of defer outside?

**Review by victortoso — COMMENTED** [review]
Looking good so far, just a suggestion about having a explicit commit for missing Close()

File: pkg/virtctl/vnc/vnc.go (hunk 1 above)
Comment (victortoso) [reply pkg/virtctl/vnc/vnc.go:170]: Just to make it clear, my suggestion for this PR is to have two commits:
1. virtctl: vnc: do close chan and handlers
2. virtctl: vnc: use cmd's context

File: pkg/virtctl/vnc/vnc.go [hunk 2]
```diff
@@ -130,21 +133,25 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 	writeStop := make(chan error)
 	readStop := make(chan error)
 
 	go func() {
 		// transfer data from/to the VM
-		k8ResChan <- vnc.Stream(kvcorev1.StreamOptions{
+		defer close(k8ResChan)
+		select {
+		case <-ctx.Done():
+			k8ResChan <- ctx.Err()
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:144]: Not sure we need to forward this error

File: pkg/virtctl/vnc/vnc.go (hunk 1 above)
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:170]: Looks wrong to me, why introduce another goroutine?

File: pkg/virtctl/vnc/vnc.go [hunk 3]
```diff
@@ -192,18 +212,19 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
-		go checkAndRunVNCViewer(doneChan, viewResChan, port)
+		go checkAndRunVNCViewer(ctx, viewResChan, port)
 	}
 
 	go func() {
-		defer close(stopChan)
 		interrupt := make(chan os.Signal, 1)
 		signal.Notify(interrupt, os.Interrupt)
 		<-interrupt
+		cancel()
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:222]: This routine can still leak, if the select below receives an error.

Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:222]: It needs a select of its own that watches ctx.Done()

File: pkg/virtctl/vnc/vnc.go (hunk 1 above)
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:170]: I thought since this is involved in closing, I thought after it recieves the done from ctx, it shud initiate the close call and not hold up. Even keeping it as defer does almost the same by executing it at the end. Which approach is better?

File: pkg/virtctl/vnc/vnc.go (hunk 2 above)
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:144]: cuz there might be a issue cuz both of them is uses same channel? this may lead to issue when its cancelled...... righttttttt got it got it

**Comment by mohit-nagaraj** [comment]
@victortoso @0xFelix 
I have implemented ur changes, if u cud take time again to re-review this, it wud be awesome. Thanks again

**Review by victortoso — COMMENTED** [review]
Could not find an issue. I tested locally with and without --proxy-only option. Works as expected.
/lgtm

File: pkg/virtctl/vnc/vnc.go [hunk 4]
```diff
@@ -89,7 +90,9 @@ func NewCommand() *cobra.Command {
 type VNC struct{}
 
 func (o *VNC) Run(cmd *cobra.Command, args []string) error {
-	virtCli, namespace, _, err := clientconfig.ClientAndNamespaceFromContext(cmd.Context())
+	ctx, cancel := context.WithCancel(cmd.Context())
+	defer cancel()
+	virtCli, namespace, _, err := clientconfig.ClientAndNamespaceFromContext(ctx)
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:95]: nit: add empty line between

File: pkg/virtctl/vnc/vnc.go [hunk 5]
```diff
@@ -130,21 +133,25 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 	viewResChan := make(chan error)
-	stopChan := make(chan struct{}, 1)
-	doneChan := make(chan struct{}, 1)
 	writeStop := make(chan error)
 	readStop := make(chan error)
 
 	go func() {
 		// transfer data from/to the VM
-		k8ResChan <- vnc.Stream(kvcorev1.StreamOptions{
+		defer close(k8ResChan)
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:141]: I don't think we need to close this chan. But it should be buffered to not block `vnc.Stream` when `Run` already exited.

[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:141]: The pipes should be closed with `defer` I suppose.

File: pkg/virtctl/vnc/vnc.go [hunk 6]
```diff
@@ -130,21 +133,25 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 			In:  pipeInReader,
 			Out: pipeOutWriter,
-		})
+		}):
+		}
 	}()
 
 	// wait for vnc client to connect to our local proxy server
 	go func() {
+		defer close(listenResChan)
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:150]: Again, I don't think there is a need to close this chan. But it probably needs to be buffered too.

File: pkg/virtctl/vnc/vnc.go [hunk 7]
```diff
@@ -156,54 +159,71 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
-		log.Log.V(2).Infof("VNC Client connected in %v", time.Now().Sub(start))
+		log.Log.V(2).Infof("VNC Client connected in %v", time.Since(start))
 		templates.PrintWarningForPausedVMI(virtCli, vmi, namespace)
 
 		// write to FD <- pipeOutReader
 		go func() {
+			defer close(readStop)
 			_, err := io.Copy(fd, pipeOutReader)
-			readStop <- err
+			select {
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:173]: No need for this select, just write the err to `readStop`.

File: pkg/virtctl/vnc/vnc.go [hunk 8]
```diff
@@ -156,33 +163,46 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
+			<-ctx.Done()
+			fd.Close()
+		}()
 
 		log.Log.V(2).Infof("VNC Client connected in %v", time.Now().Sub(start))
 		templates.PrintWarningForPausedVMI(virtCli, vmi, namespace)
 
 		// write to FD <- pipeOutReader
 		go func() {
+			defer close(readStop)
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:171]: Same

File: pkg/virtctl/vnc/vnc.go [hunk 9]
```diff
@@ -156,33 +163,46 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
+			select {
+			case <-ctx.Done():
+				return
+			case readStop <- err:
+			}
 		}()
 
 		// read from FD -> pipeInWriter
 		go func() {
+			defer close(writeStop)
```
[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:182]: Same

File: pkg/virtctl/vnc/vnc.go [hunk 10]
```diff
@@ -156,54 +159,71 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 			_, err := io.Copy(pipeInWriter, fd)
-			writeStop <- err
+			select {
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:184]: Same

File: pkg/virtctl/vnc/vnc.go (hunk 7 above)
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:173]: This routine will exit when the outer routine exits and calls `fd.Close`.

**Review by 0xFelix — COMMENTED** [review]
I don't think this solves the issue with routines leaking or being blocked. Most of the channels need to be buffered, so the routines can write to them without blocking. Please try to carefully analyze when each routine is going to exit and if it needs to watch `ctx.Done()` or if it can exit in another way already (e.g. `io.Copy` will return when a pipe or fd is closed).

File: pkg/virtctl/vnc/vnc.go [hunk 11]
```diff
@@ -168,25 +170,32 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
-		<-doneChan
-		listenResChan <- err
+		<-ctx.Done()
+		listenResChan <- ctx.Err()
 	}()
 
 	port := ln.Addr().(*net.TCPAddr).Port
 
 	if proxyOnly {
-		defer close(doneChan)
```
[the remark this answers is not in the document]
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:185]: previously we didnt have ctx so we had to rely on done channel, however we dont require it now, hence it was removed

File: pkg/virtctl/vnc/vnc.go [hunk 12]
```diff
@@ -212,13 +229,13 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
 	}
 
 	if err != nil {
-		return fmt.Errorf("Error encountered: %s", err.Error())
+		return fmt.Errorf("error encountered: %s", err.Error())
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:232]: Will it always exit with context cancelled now? e.g. if an interrupt was received? That's shoult not be handeled as error.

File: pkg/virtctl/vnc/vnc.go [hunk 13]
```diff
@@ -126,17 +130,20 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
-
-	k8ResChan := make(chan error)
-	listenResChan := make(chan error)
-	viewResChan := make(chan error)
-	stopChan := make(chan struct{}, 1)
-	doneChan := make(chan struct{}, 1)
+	defer pipeInReader.Close()
+	defer pipeInWriter.Close()
+	defer pipeOutReader.Close()
+	defer pipeOutWriter.Close()
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:136]: It should suffice to close one side of each pipe.

File: pkg/virtctl/vnc/vnc.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:146]: Btw regarding the closing of channels, while it's not necessarily required, isn't it a good practice to close them manually? Ik it wud have been required when we were watching them using select but isn't it good to have now as well

[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:146]: Makes sense, let's keep it.

File: pkg/virtctl/vnc/vnc.go (hunk 12 above)
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:232]: Yess makes sense!! Thanks for the pointer

File: pkg/virtctl/vnc/vnc.go [hunk 14]
```diff
@@ -126,17 +130,18 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 
-	k8ResChan := make(chan error)
-	listenResChan := make(chan error)
-	viewResChan := make(chan error)
-	stopChan := make(chan struct{}, 1)
-	doneChan := make(chan struct{}, 1)
+	k8ResChan := make(chan error, 1)
+	listenResChan := make(chan error, 1)
+	viewResChan := make(chan error, 1)
```
[the remark this answers is not in the document]
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:138]: Sure this looks good when implemented as well! On it

[the remark this answers is not in the document]
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:138]: Coming to 5 buffer size... the possible errors come from these go routines
1 error each from vnc.Stream, ln.Accept, copying data to the client, copying data from the client, checkAndRunVNCViewer

But if context is also cancelled at the same time, then need one more for this right

[the remark this answers is not in the document]
Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go]: For which line with context do you think we need another slot in the buffer? If it's about L212 I don't think we need it.

File: pkg/virtctl/vnc/vnc.go [hunk 15]
```diff
@@ -155,70 +155,71 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
 
 	go func() {
-		defer close(stopChan)
 		interrupt := make(chan os.Signal, 1)
 		signal.Notify(interrupt, os.Interrupt)
-		<-interrupt
+		defer signal.Stop(interrupt)
+
+		select {
+		case <-interrupt:
```
Comment (0xFelix) [inline pkg/virtctl/vnc/vnc.go:203]: Another one last question (hopefully): Do we even need a separate goroutine for this? Can we put `case <-interrupt` into our select below (L210)?

File: pkg/virtctl/vnc/vnc.go [hunk 16]
```diff
@@ -155,70 +155,65 @@ func (o *VNC) Run(cmd *cobra.Command, args []string) error {
...
-	case <-stopChan:
-	case err = <-readStop:
-	case err = <-writeStop:
-	case err = <-k8ResChan:
-	case err = <-viewResChan:
-	case err = <-listenResChan:
+	case err = <-errChan:
+	case <-interrupt:
+		cancel()
+		err = ctx.Err()
```
Comment (mohit-nagaraj) [inline pkg/virtctl/vnc/vnc.go:205]: This feels a lil hacky for me, cuz ideally we shud be waiting for goroutines to be done after cancel() is triggered. right? do let me kno if this is wrong

Comment (0xFelix) [reply pkg/virtctl/vnc/vnc.go:205]: Tbh. I think we can get away without doing `err = ctx.Err()` in both cases. Otherwise it looks good!

**Comment by mohit-nagaraj** [comment]
not sure abt the test why it failed so just updated the fork, rerunning tests on my local

**Comment by 0xFelix** [comment]
@victortoso Can you give it another look as well?

File: pkg/virtctl/vnc/vnc.go [hunk 17]
```diff
@@ -20,6 +20,7 @@
 package vnc
 
 import (
+	"context"
```
Comment (victortoso) [inline pkg/virtctl/vnc/vnc.go:23]: This should belong to the previous commit.

**Review by victortoso — COMMENTED** [review]
Only a single comment, looks fine besides that.

File: pkg/virtctl/vnc/vnc.go (hunk 17 above)
Comment (mohit-nagaraj) [reply pkg/virtctl/vnc/vnc.go:23]: On it

**Comment by 0xFelix** [comment]
Ping @victortoso for another review
