### PR TITLE
Ensure optimal CPU pinning with dedicated CPUs

### LINKED ISSUE #4687: Hyperthreads are pinned incorrectly
>/kind bug

**What happened**:
When trying to create a VMI with dedicatedCpuPlacement and hyperthreading, I noticed that the hyperthreads are pinned incorrectly.

VMI spec :
```
    spec:
      domain:
        cpu:
          dedicatedCpuPlacement: true
          sockets: 1
          cores: 2
          threads: 2
        resources:
          limits:
            cpu: 4
            memory: 1024M
```
In the compute container in the virt-launcher pod, this is the domain xml:
```
  <cputune>
    <vcpupin vcpu='0' cpuset='3'/>
    <vcpupin vcpu='1' cpuset='4'/>
    <vcpupin vcpu='2' cpuset='11'/>
    <vcpupin vcpu='3' cpuset='12'/>
  </cputune>
```
The VM has this topology:
```
$ lscpu --extended
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE
  0    0      0    0 0:0:0:0          yes
  1    0      0    0 1:1:0:0          yes
  2    0      0    1 2:2:1:0          yes
  3    0      0    1 3:3:1:0          yes
```

The node on which the VM is Running has this topology:
```
#  lscpu --extended
CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE MAXMHZ    MINMHZ
0   0    0      0    0:0:0:0       yes    3500.0000 800.0000
1   0    0      1    1:1:1:0       yes    3500.0000 800.0000
2   0    0      2    2:2:2:0       yes    3500.0000 800.0000
3   0    0      3    3:3:3:0       yes    3500.0000 800.0000
4   0    0      4    4:4:4:0       yes    3500.0000 800.0000
5   0    0      5    5:5:5:0       yes    3500.0000 800.0000
6   0    0      6    6:6:6:0       yes    3500.0000 800.0000
7   0    0      7    7:7:7:0       yes    3500.0000 800.0000
8   0    0      0    0:0:0:0       yes    3500.0000 800.0000
9   0    0      1    1:1:1:0       yes    3500.0000 800.0000
10  0    0      2    2:2:2:0       yes    3500.0000 800.0000
11  0    0      3    3:3:3:0       yes    3500.0000 800.0000
12  0    0      4    4:4:4:0       yes    3500.0000 800.0000
13  0    0      5    5:5:5:0       yes    3500.0000 800.0000
14  0    0      6    6:6:6:0       yes    3500.0000 800.0000
15  0    0      7    7:7:7:0       yes    3500.0000 800.0000
```

**What you expected to happen**:
The <cputune> element should look like the following to ensure that host and guest hyperthreads fall on the same cores.
```
  <cputune>
    <vcpupin vcpu='0' cpuset='3'/>
    <vcpupin vcpu='1' cpuset='11'/>
    <vcpupin vcpu='2' cpuset='4'/>
    <vcpupin vcpu='3' cpuset='12'/>
  </cputune>
```
I can also verify that the pinning on the VM is incorrect by doing some CPU intensive work in the VM (for example `taskset -c 0 bash -c 'while :; do :; done'`) and monitoring the `mpstat` on the node. 

Further , you can check on the thread's sibling on the node 
```
# cat /sys/devices/system/cpu/cpu3/topology/thread_siblings_list
3,11
```

**How to reproduce it**:
Creating a VMI with dedicated cpu placement and hyperthreads. 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.24.0
- Kubernetes version (use `kubectl version`): v1.17.8

### LINKED ISSUE #6159: v0.43 - CPU pinning return wrong CPU topology on VMI
> /kind bug

@rmohr @vladikr 

**What happened**:
I'm able to see a strange CPU topology in my VMI  that show me wrong allocation of socket|thread|core
it happen after i changed the kubelet "reservedSystemCPUs" from "1" to "0,56,28,84" ( the first vcpu from each NUMA)

server:
```
CPU(s):                          112
On-line CPU(s) list:             0-111
Thread(s) per core:              2
Core(s) per socket:              28
Socket(s):                       2
NUMA node(s):                    2
```

VMI
```
 cpu:
          cores: 24
          sockets: 2
          threads: 2
          model: host-passthrough
```

VMI instance
```
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              1
Core(s) per socket:              25
Socket(s):                       2
NUMA node(s):                    2
```

**What you expected to happen**:
allocation of CPU(s):    according to the VMI config 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

The algorithm first creates buckets based on the following cpu
attributes:

 * thread junks in the cpuSet
 * cores per numa node

Then the algorithm will assign threads to vCPU cores with the following
priority:

 1) try to assign a consecutive junk of threads from a singl host core.
 2) if no full set of sibling threads could be assigned, assign threads
    from a single numa node.
 3) If numa passthrough is requested, fail on this step, since we must
    not cross numa node boundaries.
 4) if not enough threads are available on any numa node, try to assign
    threads from different numa nodes to form a full vCPU core.
 5) go back to (1) and repeat until all threads are assigned.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6159
Fixes #4687
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1987329
Replaces #4757

**Special notes for your reviewer**:

**Release note**:

```release-note
Better place vcpu threads on host cpus to form more efficient passthrough architectures
```

### CODE REVIEW

**Comment by rmohr** [comment]
Should be ready for review.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 1]
```diff
@@ -0,0 +1,282 @@
...
+			}
+		}
+	}
+	return threads, requested
+}
+
+func (p *cpuPool) fitCellBound(requested int) (threads []uint32, remainingCores int) {
+	for _, cell := range p.cells {
+		for {
+			if cell.IsEmpty() {
```
Comment (kwiesmueller) [inline pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:235]: This looks like duplicated logic from above.
Could move into a function taking a `type junkAllocator func() []uint32`.
Like 
```
for _, cell := range p.cells {
  threads, requested = getCellJunk(requested, threads, cell.GetCellBoundJunk)
  if requested < 1 {
    return threads, 0
  }
}
```
Correct me if I'm wrong :-)

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+		cores = append(cores, coresOnCell)
+	}
+	return cores
+}
+
+func (p *cpuPool) FitCores() (cpuTune *api.CPUTune, err error) {
+	threads, remaining := p.fitCores(p.cores)
+
+	if remaining > 0 {
+		if p.allowCellCrossing {
```
Comment (kwiesmueller) [inline pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:164]: Is that differentiation just to cause different output and verify it in tests? Or do the two errors have functional impact?

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 3]
```diff
@@ -0,0 +1,282 @@
...
+
+type cell struct {
+	bigThreadJunks [][]uint32
+	smallJunks     []uint32
+	threadsPerCore int
+}
+
+// GetCPUBoundJunk consumes the amount of threadsPerCore from the numa cell
+// or none if it can't be fit on the numa cell
+func (c *cell) GetCPUBoundJunk() []uint32 {
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:28]: what does the term `junk` mean in relation to all this cpu mapping?

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 4]
```diff
@@ -0,0 +1,282 @@
...
+	}
+	return cores
+}
+
+func (p *cpuPool) FitCores() (cpuTune *api.CPUTune, err error) {
+	threads, remaining := p.fitCores(p.cores)
+
+	if remaining > 0 {
+		if p.allowCellCrossing {
+			return nil, fmt.Errorf("not enough exclusive threads provided, could not fit %v core(s)", remaining)
```
Comment (davidvossel) [inline pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:165]: what would be a scenario where allowCellCrossing == true but remaining cores > 0.  Is this only possible when someone requests threads per core where the number of threads can't possibly match the number of cores?

I'm just trying to understand if this is something that can be caught in validation webhook.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 3 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:28]: As @kwiesmueller mentioned I meant `chunk` :D

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 4 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:165]: This is one of the main issues with all this. We don't know what we get until the kubelet is done and everything is started. We do not know up to this point if we can map cpu threads in a reasonable way. Note that for cpu pinning (so no numa mapping), we should always get a working pinning but it can be inefficient. For numa passthrough it is more likely that it will fail, because there are cases where we can't create a correct mapping out of the assigned CPUs because we can't form via libvirt topologies where cpus have different amounts of threads.

File: pkg/virt-handler/node-labeller/api/capabilities.go [hunk 5]
```diff
@@ -32,11 +36,11 @@ type Counter struct {
...
-	ID       uint32 `xml:"id,attr"`
-	SocketID uint32 `xml:"socket_id,attr"`
-	DieID    uint32 `xml:"die_id,attr"`
-	CoreID   uint32 `xml:"core_id,attr"`
-	Siblings string `xml:"siblings,attr"`
+	ID       uint32      `xml:"id,attr"`
+	SocketID uint32      `xml:"socket_id,attr"`
+	DieID    uint32      `xml:"die_id,attr"`
+	CoreID   uint32      `xml:"core_id,attr"`
+	Siblings CPUSiblings `xml:"siblings,attr"`
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/node-labeller/api/capabilities.go:43]: We were reading this field so far but it was nowhere used, and most important, it was never serialized over grpc and passed on to virt-launcher. Therefore we can just change it.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:28]: Yes, `chunk` :)

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 6]
```diff
@@ -0,0 +1,282 @@
...
+}
+
+// GetThread will first try to allocate a thread from fragmented cores
+// but fall back to not fragmented cores if the request can't be satisfied otherwise
+func (c *cell) GetThread() *uint32 {
+	if len(c.smallJunks) > 0 {
+		thread := c.smallJunks[0]
+		c.smallJunks = c.smallJunks[1:]
+		return &thread
+	} else if len(c.bigThreadJunks) > 0 {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:72]: I think I keep the logical flow in the code.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 2 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:164]: It is meant to log the correct reason and help users identify why the workload does not start. I think I have to slightly iterate over that because also in the first case there could just not be enough threads.

File: pkg/virt-launcher/virtwrap/converter/converter.go [hunk 7]
```diff
@@ -1845,13 +1855,13 @@ func appendDomainIOThreadPin(domain *api.Domain, thread uint32, cpuset string) {
...
-func formatDomainIOThreadPin(vmi *v1.VirtualMachineInstance, domain *api.Domain, c *ConverterContext) error {
+func formatDomainIOThreadPin(vmi *v1.VirtualMachineInstance, domain *api.Domain, emulatorThread uint32, c *ConverterContext) error {
 	iothreads := int(domain.Spec.IOThreads.IOThreads)
-	vcpus := int(calculateRequestedVCPUs(domain.Spec.CPU.Topology))
+	vcpus := int(vcpu.CalculateRequestedVCPUs(domain.Spec.CPU.Topology))
 
 	if vmi.IsCPUDedicated() && vmi.Spec.Domain.CPU.IsolateEmulatorThread {
 		// pin the IOThread on the same pCPU as the emulator thread
-		cpuset := fmt.Sprintf("%d", *c.EmulatorThreadCpu)
+		cpuset := fmt.Sprintf("%d", emulatorThread)
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/converter.go]: Done.

File: pkg/virt-launcher/virtwrap/converter/converter.go [hunk 8]
```diff
@@ -1628,27 +1629,36 @@ func Convert_v1_VirtualMachineInstance_To_api_Domain(vmi *v1.VirtualMachineInsta
...
+				domain.Spec.CPUTune = cpuTune
 			}
+			var emulatorThread uint32
 			if vmi.Spec.Domain.CPU.IsolateEmulatorThread {
-				if c.EmulatorThreadCpu == nil {
-					err := fmt.Errorf("no CPUs allocated for the emulation thread")
-					log.Log.Reason(err).Error("failed to format emulation thread pin")
-					return err
-
+				if emulatorThread, err = cpuPool.FitThread(); err == nil {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/converter.go]: Done.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 2 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go]: Done.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 3 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go]: Renamed.

File: pkg/virt-launcher/virtwrap/converter/converter.go [hunk 9]
```diff
@@ -1628,27 +1629,36 @@ func Convert_v1_VirtualMachineInstance_To_api_Domain(vmi *v1.VirtualMachineInsta
...
+			var cpuPool vcpu.VCPUPool
+			if isNumaPassthrough(vmi) {
+				cpuPool = vcpu.NewStrictCPUPool(domain.Spec.CPU.Topology, c.Topology, c.CPUSet)
+			} else {
+				cpuPool = vcpu.NewRelaxedCPUPool(domain.Spec.CPU.Topology, c.Topology, c.CPUSet)
+			}
+			if cpuTune, err := cpuPool.FitCores(); err != nil {
 				log.Log.Reason(err).Error("failed to format domain cputune.")
 				return err
+			} else {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/converter.go]: Done.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 1 above)
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go]: Done. I chose a slightly different way to avoid having to pass in and out expanding fields. In general if two small code parts are almost identical I sometimes prefer keeping it separate to reduce the magic, but de-duplicated now.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 10]
```diff
@@ -0,0 +1,282 @@
...
+			}
+			junk := cell.GetCPUBoundJunk()
+			if len(junk) > 0 {
+				threads = append(threads, junk...)
+				requested--
+			} else {
+				// go to the next cell
+				break
+			}
+			if requested == 0 {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:228]: I added a panic since that must never happen. Should at least block any hot-looping.

**Comment by rmohr** [comment]
@kwiesmueller @davidvossel PTAL

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 11]
```diff
@@ -0,0 +1,282 @@
...
+}
+
+func (p *cpuPool) fitCPUBound(requested int) (threads []uint32, remainingCores int) {
+	for _, cell := range p.cells {
+		for {
+			if cell.IsEmpty() {
+				break
+			}
+			junk := cell.GetCPUBoundJunk()
+			if len(junk) > 0 {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go]: Done.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (kwiesmueller) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:228]: You added the panic here: https://github.com/kubevirt/kubevirt/pull/6251/files#diff-770be27cf2d6dd3b86265236daa60480efc09ce100e00ec7c003051a8572dc9bR262
But not on this line, should it be both places?

**Comment by kwiesmueller** [comment]
Just got some of the small nits remaining from before.
Feel free to resolve if necessary.

/retest

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:228]: I think in this case it is pretty clear that we can't hot-loop. we only ever  do `request--` in the same loop.

[the remark this answers is not in the document]
Comment (kwiesmueller) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:228]: Alright, if we are sure requested can never be 0 from the start.

**Review by davidvossel — COMMENTED** [review]
/approve

**Comment by vladikr** [comment]
I'd like to have some more time to finish going over this before it goes in...

**Comment by davidvossel** [comment]
/hold

waiting for @vladikr

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go [hunk 12]
```diff
@@ -0,0 +1,280 @@
...
+
+func newCPUPool(requestedToplogy *api.CPUTopology, nodeTopology *v1.Topology, cpuSet []int, allowCellCrossing bool) *cpuPool {
+	pool := &cpuPool{threadsPerCore: int(requestedToplogy.Threads), cores: int(requestedToplogy.Cores * requestedToplogy.Sockets), allowCellCrossing: allowCellCrossing, availableThreads: len(cpuSet)}
+	cores := cpuChunksToCells(cpuSet, nodeTopology)
+
+	for _, coresOnCell := range cores {
+		c := cell{threadsPerCore: int(requestedToplogy.Threads)}
+		for j, core := range coresOnCell {
+			if len(core) >= c.threadsPerCore {
+				c.bigThreadChunks = append(c.bigThreadChunks, coresOnCell[j])
```
Comment (vladikr) [inline pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go:121]: perhaps we didn't need to make this generic and simply call this fullCoreThreads and s/smallChunks/partialCoreThreads all over the code - this would make it more clear from my pov.
There are no real systems that have more than 2 hyper-threads and if it's a virtual system is pretty much not useful if the guest threads are not pinned directly to the L0 host - but there are no L0 hosts with threads > 2... maybe we should just reject cases where threads > 2

**Review by vladikr — COMMENTED** [review]
Thanks @rmohr !

Sorry, it took me a while.
We could add more logging for it will be easier to follow when something goes wrong.
/lgtm
lgtm

**Comment by rmohr** [comment]
@vladikr added the API validation which limits the vCPU threads to a maximum of two.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go [hunk 13]
```diff
@@ -0,0 +1,354 @@
...
+
+	v1 "kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1"
+	"kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api"
+)
+
+type factoryFunc func(requestedToplogy *api.CPUTopology, nodeTopology *v1.Topology, cpuSet []int) VCPUPool
+
+var _ = Describe("VCPU pinning", func() {
+
+	rand.Seed(time.Now().UnixNano())
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go:24]: Let me check the libvirt source if that can happen.

[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go:24]: Yes can happen. Will address it.

File: pkg/virt-handler/node-labeller/api/capabilities.go [hunk 14]
```diff
@@ -100,3 +104,16 @@ func (b *yesnobool) UnmarshalXMLAttr(attr xml.Attr) error {
 	}
 	return fmt.Errorf("value %v of %v is not (yes|no)", attr.Value, attr.Name)
 }
+
+func (b *CPUSiblings) UnmarshalXMLAttr(attr xml.Attr) error {
+	if attr.Value != "" {
+		for _, cpuStr := range strings.Split(attr.Value, ",") {
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/node-labeller/api/capabilities.go:110]: Yes can happen. Just checked the libvirt sources. Will fix it.

File: pkg/virt-handler/node-labeller/capabilities_test.go [hunk 15]
```diff
@@ -28,6 +28,17 @@ var _ = Describe("Capabilities", func() {
 		Expect(bool(counter.Scaling)).To(BeFalse())
 	})
 
+	It("should properly read cpu siblings", func() {
+		f, err := os.Open("testdata/capabilities.xml")
```
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/node-labeller/capabilities_test.go:33]: Fixed. :+1:

File: pkg/virt-handler/node-labeller/api/capabilities.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-handler/node-labeller/api/capabilities.go]: Fixed.

File: pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (rmohr) [reply pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go]: Fixed. In case a test fails the seed is printed now.

File: pkg/util/hardware/hw_utils.go [hunk 16]
```diff
@@ -59,6 +59,9 @@ func ParseCPUSetLine(cpusetLine string) (cpusList []int, err error) {
 			}
 			cpusList = append(cpusList, cpuNum)
 		}
+		if len(cpusList) > limit {
+			return nil, fmt.Errorf("rejecting expanding CPU array for safety reasons, limit is %v", limit)
```
Comment (vasiliy-ul) [inline pkg/util/hardware/hw_utils.go:63]: Wouldnt it be better to do the safety check before allocating the array? I.e. inside `if len(cpuRange) > 1 {...}`:
```go
if len(cpuRange) > 1 {
			start, err := strconv.Atoi(cpuRange[0])
			if err != nil {
				return nil, err
			}
			end, err := strconv.Atoi(cpuRange[1])
			if err != nil {
				return nil, err
			}
                        // do not allow to exceed the limit
                        if len(cpusList) > limit {
			        return nil, fmt.Errorf("rejecting expanding CPU array for safety reasons, limit is %v", limit)
                        }                        
                        ...
}
```

Comment (rmohr) [reply pkg/util/hardware/hw_utils.go:63]: yes, I missed the embedded loop. :+1:

Comment (rmohr) [reply pkg/util/hardware/hw_utils.go]: Fixed. Also changed the unit test in a way that it would bring down the machine or at least loop for ages.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go [hunk 17]
```diff
@@ -1015,6 +1015,16 @@ func validateNUMA(field *k8sfield.Path, spec *v1.VirtualMachineInstanceSpec, con
 				Field: field.Child("domain", "cpu", "numa", "guestMappingPassthrough").String(),
 			})
 		}
+		if spec.Domain.CPU != nil && spec.Domain.CPU.Threads > 2 {
```
Comment (vladikr) [inline pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go:1018]: Can we also add this validation to `validateCpuPinning`?

File: pkg/virt-handler/node-labeller/api/capabilities.go [hunk 18]
```diff
@@ -100,3 +104,17 @@ func (b *yesnobool) UnmarshalXMLAttr(attr xml.Attr) error {
 	}
 	return fmt.Errorf("value %v of %v is not (yes|no)", attr.Value, attr.Name)
 }
+
+func (b *CPUSiblings) UnmarshalXMLAttr(attr xml.Attr) error {
+	if attr.Value != "" {
+		if list, err := hwutil.ParseCPUSetLine(attr.Value, 100); err == nil {
```
Comment (vladikr) [inline pkg/virt-handler/node-labeller/api/capabilities.go:110]: Can't this easily be more than 100?
I think the limit is much higher, around 8192

**Review by vladikr — COMMENTED** [review]
Overall, it all looks very good to me.
I think we should add the number of threads validation for dedicatedCPUs as well. 

I would also suggest renaming the bigThreadChunks and smallChunks to fullCoresList or fragmentedCoresList - or anything similar. I think it would make it easier for anyone who will read this code to faster understand the context - but it's up to you :)

File: pkg/virt-handler/node-labeller/api/capabilities.go (hunk 18 above)
Comment (rmohr) [reply pkg/virt-handler/node-labeller/api/capabilities.go:110]: 100 is just the limit for cpu threads. For `GetPodCPUSet` where we are reading what we assign to the pods it is set to `50000`.

Comment (vladikr) [reply pkg/virt-handler/node-labeller/api/capabilities.go:110]: ah, I see.

File: pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go (hunk 17 above)
Comment (rmohr) [reply pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go]: Done.

**Comment by rmohr** [comment]
> I would also suggest renaming the bigThreadChunks and smallChunks to fullCoresList or fragmentedCoresList - or anything similar. I think it would make it easier for anyone who will read this code to faster understand the context - but it's up to you :)


Done.

**Comment by vladikr** [comment]
:+1: 
/lgtm
