### PR TITLE
virt-handler: Fix entry duplication in vmiMountTargetRecord

### LINKED ISSUE #16532: virt-handler: vmiMountTargetRecord grows unbounded due to duplicate TargetFile entries on reconcile retries
### Summary
When virt-handler resolves an incorrect hotplug volume mountpoint on the node (see #16520), it may repeatedly append duplicate entries to the per-VMI mount target record. The file grows unbounded because `writePathToMountRecord()` appends a new `vmiMountTargetEntry` without deduplicating by `TargetFile`. This is amplified by reconcile retries: every sync failure that re-enqueues the VM adds another duplicate entry for the same (incorrectly resolved) target path.

### What happened
This issue is one of the outcomes of #16520, where virt-handler can incorrectly resolve hotplug volume mount points on the node when multiple attachment pods share a common mount root.
When a (possibly incorrect) node mountpoint is resolved, `writePathToMountRecord()` is called from either `mountFileSystemHotplugVolume()` or `mountBlockHotplugVolume()`. `writePathToMountRecord()` currently behaves as an append-only update: it idempotently appends a new `vmiMountTargetEntry` to the `vmiMountTargetRecord` and does not check whether an entry with the same `TargetFile` already exists.

In the failure scenario described in #16520:
- `volumeMounter.Unmount()` fails during VMI sync (e.g. because cleanup targets the wrong directory and hits device or resource busy).
- The VMI is re-enqueued and processed again.
- On each new reconcile attempt, virt-handler may resolve the same incorrect mountpoint again and call `writePathToMountRecord()`.
- Because there is no deduplication, each reconcile appends another entry whose `TargetFile` corresponds to the (incorrectly resolved) mountpoint.

As a result, the mount target record file on the node filesystem can grow rapidly in size due to accumulating duplicate entries.

### Impact
- Unbounded growth of the mount target record file on the node.
- Increased disk usage and potentially slower parsing/processing of the record over time.
- Makes recovery harder because the record becomes polluted with many stale/duplicated targets.
At [Nebius](https://nebius.com/), we've had repros of this issue when mount target record grew beyond 12MB.

### What is expected to happen
- The mount target record should not grow unbounded due to reconcile retries.
- `writePathToMountRecord()` (or the call sites) should be idempotent with respect to `TargetFile`:
  - If an entry for the same TargetFile already exists, it should be updated (or skipped), not appended again.
- Ideally, incorrect mountpoint resolution should not lead to persistent accumulation of bad entries in the record.

### Additional context
This issue is likely secondary to mountpoint mis-resolution (#16520), but the record growth behavior appears to be an independent robustness problem: any repeated mount/reconcile that calls `writePathToMountRecord()` with the same `TargetFile` can append duplicates.

### Environment
- KubeVirt version: 1.1.0
- Kubernetes version: 1.31.13
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS: Ubuntu 24.04.2
- Kernel: 6.14.8-5
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by keinsword**
### What this PR does
This PR fixes the issue when in certain circumstances a per-VMI mount target record file grows unbounded because `writePathToMountRecord()` appends a new `vmiMountTargetEntry` without deduplicating by `TargetFile`.
#### Before this PR:
When virt-handler resolves an incorrect hotplug volume mountpoint on the node (see #16520), it may repeatedly append duplicate entries to the per-VMI mount target record. The file grows unbounded because `writePathToMountRecord()` appends a new `vmiMountTargetEntry` without deduplicating by `TargetFile`. This is amplified by reconcile retries: every sync failure that re-enqueues the VM adds another duplicate entry for the same (incorrectly resolved) target path.
See #16532.
#### After this PR:
Now `writePathToMountRecord()` calls `appendPathToMountRecord()` that verifies whether there's already an entry with the same `TargetFile` in the `vmiMountTargetRecord` record before calling `append()`.
### References
- Fixes #16532.
- Partially addresses #16520.

### Why we need it and why it was done in this way
The per-VMI mount target record drives hotplug cleanup. When virt-handler repeatedly resolves the same (potentially incorrect) target path across retries, `writePathToMountRecord()` could append duplicate `TargetFile` entries and the record file could grow unbounded. This PR makes the operation idempotent by deduplicating on `TargetFile` before appending.

**The following tradeoffs were made:**
Deduplication is done in-memory (simple, low risk) and keeps the existing record format/ordering (“first entry wins”).

**Links to places where the discussion took place:** #16532, #16520.

### Special notes for your reviewer
Included a unit test ensuring `writePathToMountRecord()` is idempotent for an already-recorded path.

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [x] Design: A design document is not required, this is a targeted bug fix
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [x] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [x] Testing: Included a unit test ensuring `writePathToMountRecord()` is idempotent for an already-recorded path
- [x] Documentation: A user-guide update is not required
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note
```release-note
Fix virt-handler hotplug mount target record growth by preventing duplicate TargetFile entries.
```

### CODE REVIEW

**Comment by 0xFelix** [comment]
Failures are related

**Comment by keinsword** [comment]
> Failures are related

```
10:58:23: Build is not clean:
<...>
10:58:23: On branch main
10:58:23: Changes not staged for commit:
10:58:23:   (use "git add <file>..." to update what will be committed)
10:58:23:   (use "git restore <file>..." to discard changes in working directory)
10:58:23: 	modified:   pkg/virt-handler/hotplug-disk/mount.go
10:58:23: 
10:58:23: no changes added to commit (use "git add" and/or "git commit -a")
make: *** [Makefile:150: build-verify] Error 1
```
@0xFelix does that mean that something (e.g. gofmt/goimport) has modified this file during the build?

**Comment by 0xFelix** [comment]
Yes, you need to run `make fmt` locally and append the changes.

**Comment by keinsword** [comment]
@0xFelix done, thanks for pointing this out.

**Comment by 0xFelix** [comment]
@keinsword Can you please squash commits?

**Comment by keinsword** [comment]
@0xFelix Sure, done ✅

**Comment by keinsword** [comment]
@0xFelix, I do not see any failures related to my changes. Could you have a look and possibly rerun tests?

**Comment by keinsword** [comment]
Hi @0xFelix,

Looking at the checks' statuses, I'm not sure, what's the PR status now? Is there any failures that block the merge and thus need to be addressed?

UPD: looks like `/lgtm` label is missing.

File: pkg/virt-handler/hotplug-disk/mount.go [hunk 1]
```diff
@@ -284,9 +293,7 @@ func (m *volumeMounter) setMountTargetRecord(vmi *v1.VirtualMachineInstance, rec
 }
 
 func (m *volumeMounter) writePathToMountRecord(path string, vmi *v1.VirtualMachineInstance, record *vmiMountTargetRecord) error {
-	record.MountTargetEntries = append(record.MountTargetEntries, vmiMountTargetEntry{
-		TargetFile: path,
-	})
+	record.appendPath(path)
```
Comment (lyarwood) [inline pkg/virt-handler/hotplug-disk/mount.go]: nit - could we avoid the following call to `m.setMountTargetRecord` if `appendPath` returned a bool to indicate if the path already existed?

**Review by lyarwood — COMMENTED** [review]
/lgtm
/hold

Just a quick nit, not sure if it's possible so feel free to unhold.

File: pkg/virt-handler/hotplug-disk/mount.go (hunk 1 above)
Comment (keinsword) [reply pkg/virt-handler/hotplug-disk/mount.go]: Nice catch @lyarwood!
Done that, please have a look.

**Comment by 0xFelix** [comment]
/hold cancel

Ping @lyarwood

**Comment by keinsword** [comment]
Got a failure one of the virt-operator tests:
```log
2026/02/24 13:28:20 http: TLS handshake error from 127.0.0.1:40884: remote error: tls: bad certificate
```
Looks completely unrelated. @awels could you initiate re-run?

**Comment by 0xFelix** [comment]
@keinsword The bot will take care of it.

**Comment by keinsword** [comment]
@awels @lyarwood could you unhold/retest this PR?

**Comment by keinsword** [comment]
@awels now that all tests seem to have been passed, could you unhold this PR to make the tide check happy? :)

**Comment by awels** [comment]
Something must be wrong with the infra, since doing a retest doesn't even work. removing cancel again and hopefully once it gets fixed it will continue
/hold cancel

**Comment by keinsword** [comment]
@awels @0xFelix @lyarwood the only issues according to tide are presence of `hold` label and absence of `skip-review` label. Am I correct that all tests are good now?
May we get this one merged now?

Screenshot 2026-03-12 at 12 40 40

**Comment by dhiller** [comment]
/unhold

CI is green

**Comment by keinsword** [comment]
@dhiller thank you for unholding the PR. But even though GH shows CI as green, it will eventually rerun all the checks/tests, some of them will most likely fail (and those failures will be unrelated to changes in this PR), and the bot will put it on hold once again. I'm stuck in this loop for a couple of weeks now. Is it a common thing here? I mean, I'm quite new to the KubeVirt development, and I don't now exactly how CI is setup here, but it feels like either something went wrong with this particular PR, and it may be worth closing/reopening it, or it's just the way it is and I should patiently wait until eventually stars align and all checks are passed 😄

**Comment by 0xFelix** [comment]
@keinsword CI is not in the best state right now due to high load, please don't close this PR. This has nothing to do with your PR in particular, everyone is experiencing these issues right now.
