### PR TITLE
instancetype: Create ControllerRevisions earlier within VM reconcile loop

### LINKED ISSUE #8142: Users able to delete instancetype when referenced by a VirtualMachine that hasn't started causing failures when an attempt is later made to start
**What happened**:

At present during the admission of a `VirtualMachine` there is a basic check to ensure that any instancetype and/or preferences both exist and don't conflict with the `VirtualMachine` definition: 

https://github.com/kubevirt/kubevirt/blob/74781324b726a6d58799be1257a34f61e6749513/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L102-L105

Later when the `VirtualMachine` is started the `VirtualMachine` controller creates `ControllerRevisions` containing a point in time copy of the referenced instancetype or preference before applying them to the `VirtualMachineInstance` before submission:

https://github.com/kubevirt/kubevirt/blob/74781324b726a6d58799be1257a34f61e6749513/pkg/virt-controller/watch/vm.go#L1011-L1016

This currently allows a user to delete or update a referenced instancetype or preference from the cluster before starting a `VirtualMachine` causing failures if an attempt to start is eventually made.

**What you expected to happen**:

 Requests to delete or update any instancetypes or preferences that are referenced by a `VirtualMachine` but not stashed in a `ControllerRevision` need to be blocked to avoid this.

**How to reproduce it (as minimally and precisely as possible)**:

```
# ./cluster-up/kubectl.sh apply -f examples/csmall.yaml 
virtualmachineinstancetype.instancetype.kubevirt.io/csmall created
# ./cluster-up/kubectl.sh apply -f examples/vm-cirros-csmall.yaml 
virtualmachine.kubevirt.io/vm-cirros-csmall created
# ./cluster-up/kubectl.sh delete virtualmachineinstancetype/csmall
virtualmachineinstancetype.instancetype.kubevirt.io "csmall" deleted
# ./cluster-up/virtctl.sh start vm-cirros-csmall
Error starting VirtualMachine Internal error occurred: admission webhook "virtualmachine-validator.kubevirt.io" denied the request: Failure to find instancetype: virtualmachineinstancetypes.instancetype.kubevirt.io "csmall" not found
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.55.0 / main
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @akrejcir 
/cc @davidvossel 
/cc @rmohr 

**What this PR does / why we need it**:

Until now ControllerRevisions for instancetypes and preferences had only
been created by the VirtualMachine controller when starting the
VirtualMachine and initially creating the VirtualMachineInstance. This
delay allowed users to potentially update or delete any referenced
instancetype or preference before a copy was made in a
ControllerRevision.

This change moves the creation of the ControllerRevisions to earlier
within the reconcile loop, ensuring they are created as soon as the
VirtualMachine is seen by the controller. This should help avoid
races with user modifications or removals that could then cause
the VirtualMachine to fail to launch at a later time.

A single VirtualMachine controller unit test is updated as we now expect
the VirtualMachine to be patched with ControllerRevision details ahead
of any conflict check occurring at runtime.

The main ControllerRevision functional test is also updated to assert
that the ControllerRevisions are captured, their details are patched
into the VirtualMachine and with any modifications made after this not
being reflected in the VirtualMachineInstance created at runtime.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8142

**Special notes for your reviewer**:

Marked as a draft until https://github.com/kubevirt/kubevirt/pull/8282 lands.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/virt-controller/watch/vm.go [hunk 1]
```diff
@@ -2317,13 +2312,23 @@ func (c *VMController) sync(vm *virtv1.VirtualMachine, vmi *virtv1.VirtualMachin
 		return nil, err
 	}
 
-	dataVolumesReady, err := c.handleDataVolumes(vm, dataVolumes)
+	// Ensure we have ControllerRevisions of any instancetype or preferences referenced by the VM
+	err = c.instancetypeMethods.StoreControllerRevisions(vm)
```
Comment (davidvossel) [inline pkg/virt-controller/watch/vm.go:2316]: makes sense to me

File: staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go [hunk 2]
```diff
@@ -71,19 +71,6 @@ type VirtualMachineClusterInstancetypeList struct {
 	Items           []VirtualMachineClusterInstancetype `json:"items"`
 }
 
-// VirtualMachineInstancetypeSpecRevision is used to capture a versioned copy of VirtualMachineInstancetypeSpec within a ControllerRevision
-//
-// **WARNING** This struct should never change ensuring it can always be unmarshaled from a ControllerRevision
-type VirtualMachineInstancetypeSpecRevision struct {
```
Comment (davidvossel) [inline staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go:77]: why was this removed, and what has changed as a result? Also, what impact would this have on upgrades if someone was using an instancetype with a previous controller revision that used this structure?

Comment (lyarwood) [reply staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go:77]: Lets discuss this in https://github.com/kubevirt/kubevirt/pull/8282 that introduced these changes, I've just included the series here as I wanted that PR to land first hopefully avoiding conflicts.

Comment (lyarwood) [reply staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go:77]: https://github.com/kubevirt/kubevirt/pull/8282#discussion_r955229409

Comment (davidvossel) [reply staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go:77]: @lyarwood your approach here with taking the revision early in the VM's lifecycle (similar to how DVs are handled) looks totally fine to me. If you want to revise this PR to only include those changes, i think we can get it in

Comment (lyarwood) [reply staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go:77]: ACK I'll do that today then, thanks.

Comment (lyarwood) [reply staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go]: @davidvossel Done.

File: pkg/virt-controller/watch/vm_test.go [hunk 3]
```diff
@@ -3558,6 +3558,13 @@ var _ = Describe("VirtualMachine", func() {
 
 			It("should reject the request if a VirtualMachineInstancetype conflicts with the VirtualMachineInstance", func() {
 
+				expectedInstancetypeRevisionName := instancetype.GetRevisionName(vm.Name, f.Name, f.UID, f.Generation)
+				expectedInstancetypeRevision, err := instancetype.CreateInstancetypeControllerRevision(vm, expectedInstancetypeRevisionName, f.TypeMeta.APIVersion, &f.Spec)
+				Expect(err).ToNot(HaveOccurred())
+
+				expectedRevisionNamePatch, err := instancetype.GenerateRevisionNamePatch(expectedInstancetypeRevision, nil)
+				Expect(err).ToNot(HaveOccurred())
+
```
Comment (davidvossel) [inline pkg/virt-controller/watch/vm_test.go:3567]: I didn't catch this the first time I looked at this PR.

previously, we'd never store the controller revision unless it could be successfully applied to the vm. Do you think it's important to maintain this behavior? If the webhook validator already performs this check at admission time, then it might not be terribly important to do it again here before storing the revision

Comment (lyarwood) [reply pkg/virt-controller/watch/vm_test.go:3567]: > I didn't catch this the first time I looked at this PR.
> 
> previously, we'd never store the controller revision unless it could be successfully applied to the vm. Do you think it's important to maintain this behavior? If the webhook validator already performs this check at admission time, then it might not be terribly important to do it again here before storing the revision

Yeah apologies I did mean to expand the comment in the commit message about this but lost context over the long weekend here in the UK. You are correct that we do have an existing check in the validating webhook ensuring things apply cleaning before the VM is accepted [1]. The test here is asserting the behaviour of the controller during application of an instancetype when starting a VM [2].

There's still a tiny chance of a race between the validating webhook checking an instancetype, someone updating the instancetype in a way that could cause a conflict and the controller then capturing a now invalid instancetype in a ControllerRevision when it first sees the VM. As a result I think this test is still valid however unlikely it is to ever actually happen. 

[1] https://github.com/kubevirt/kubevirt/blob/099709e16f4b23507cd3551c115dbe56a5af3c30/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L102-L105
[2] https://github.com/kubevirt/kubevirt/blob/ca6a597a9c2e2e6060a721ecbecbb5660a6b49a5/pkg/virt-controller/watch/vm.go#L978-L985

Comment (lyarwood) [reply pkg/virt-controller/watch/vm_test.go:3567]: @davidvossel does my comment clarify things?

Comment (davidvossel) [reply pkg/virt-controller/watch/vm_test.go:3567]: > @davidvossel does my comment clarify things?

yeah, i get the logic. My point was that we could potentially store a revision that can't be applied to the VM since we never verify the revision we're about to store can successfully be applied to the VM. it's an unlikely scenario, but possible now that the revision is kind of "blindly" stored before the controller validates that it applies cleanly.

**Review by davidvossel — COMMENTED** [review]
/approve

it's up to you if you think https://github.com/kubevirt/kubevirt/pull/8346#discussion_r965213010 should be addressed or not.
