### PR TITLE
Handle freeze on paused VMs during snapshot

### LINKED ISSUE #10759: Paused vm can't make a VirtualMachineSnapshot
**What happened**:
I would like to pause my vm and make a VirtualMachineSnapshot but it failed. It seems like this operation is not allowed to a vm with qemu-guest-agent installed.

**What you expected to happen**:
Making a VirtualMachineSnapshot after pausing is allowed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start a vm with qemu-guest-agent installed
2. Pause this vm
3. Make a VirtualMachineSnapshot for this vm
4. This VirtualMachineSnapshot will fail, because there is a `freeze` operation during this process. The `freeze` will time out due to the vm is in the paused state. virt-controller keeps producing this log:
``` json
{"component":"virt-controller","level":"info","msg":"Freeze VMI pw-vm-centos7","pos":"vmi.go:244","timestamp":"2023-11-22T03:15:22.819445Z"}
{"component":"virt-controller","level":"info","msg":"Freezing vmi pw-vm-centos7 took 39.555493ms","pos":"util.go:44","timestamp":"2023-11-22T03:15:22.858992Z"}
E1122 03:15:22.859168       1 util.go:72] Internal error occurred: unexpected return code 400 (400 Bad Request)
```
**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.26.6
- Kernel (e.g. `uname -a`): `Linux pw1 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by noamasu**
VM snapshot with qemu-guest-agent fails when the domain is paused, because virt-controller sends a freeze/unfreeze request during snapshotting. This freeze/unfreeze is handled by virt-launcher, but it currently fails on paused VMs. Since paused VMs have a consistent filesystem state (similar to frozen), this change makes virt-launcher treat freeze as successful when the domain is paused. This allows snapshotting to continue safely.

#### Before this PR:

- VM snapshot with qemu-guest-agent fails when the domain is paused. This happens since the snapshot flow trigger a freeze but since the VM is paused, freeze fails causing snapshot flow to also fail. since a Paused VM is considered a safe state to perform a snapshot, we expect it to pass when the VM is paused, but it doesnt.
- it is possible to unpause a VM during snapshot, which is not desired.
- a false warning message is being printed saying it is not safe to snapshot a running VM (without qemu-guest-agent) even though the VM is paused.
- virt-launcher's agent poller is spamming qemu-gest-agent command failures when VM is paused.

#### After this PR:

- Possible to complete a VM (with qemu-guest-agent) snapshot successfully even if the VM is paused.
- Make sure unpause will be rejected if `vm.Status.SnapshotInProgress` is not nil.
- prevent a warning message from being printed for when snapshot is being taken while VM (without qemu-guest-agent)  is still running even though the VM is paused.
- virt-launcher's agent poller skips qemu-guest-agent commands if the VM is paused.

### References
Fixes #10759

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Special notes for your reviewer
@ShellyKa13
@codingben (check out the change for agent_poller.go)

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
bugfix: Enable vmsnapshot for paused VMs
```

### CODE REVIEW

File: pkg/virt-launcher/virtwrap/manager.go [hunk 1]
```diff
@@ -1850,6 +1850,24 @@ func (l *LibvirtDomainManager) FreezeVMI(vmi *v1.VirtualMachineInstance, unfreez
 	domainName := api.VMINamespaceKeyFunc(vmi)
 	safetyUnfreezeTimeout := time.Duration(unfreezeTimeoutSeconds) * time.Second
 
+	domain, err := l.virConn.LookupDomainByName(domainName)
+	if err != nil {
+		if domainerrors.IsNotFound(err) {
+			return fmt.Errorf("Domain not found.")
+		} else {
+			return err
+		}
```
Comment (0xFelix) [inline pkg/virt-launcher/virtwrap/manager.go]:
```suggestion
		}
		return err
```

nit: additional else not required

File: pkg/virt-launcher/virtwrap/manager.go [hunk 2]
```diff
@@ -1895,6 +1906,25 @@ func (l *LibvirtDomainManager) FreezeVMI(vmi *v1.VirtualMachineInstance, unfreez
...
 	l.cancelSafetyUnfreeze()
 	domainName := api.VMINamespaceKeyFunc(vmi)
+
+	domain, err := l.virConn.LookupDomainByName(domainName)
+	if err != nil {
+		if domainerrors.IsNotFound(err) {
+			return fmt.Errorf("Domain not found.")
+		} else {
+			return err
+		}
```
Comment (0xFelix) [inline pkg/virt-launcher/virtwrap/manager.go]: Same

File: tests/storage/snapshot.go [hunk 3]
```diff
@@ -565,7 +565,76 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
 			})
+			DescribeTable("should succeed snapshot when VM is paused (freeze will be skipped)",
+				func(hasGuestAgent bool) {
+					var vmi *v1.VirtualMachineInstance
+					if hasGuestAgent {
+						vmi = libvmifact.NewFedora(libnet.WithMasqueradeNetworking())
+					} else {
+						vmi = libvmifact.NewAlpine(libnet.WithMasqueradeNetworking())
+					}
+					vmi.Namespace = testsuite.GetTestNamespace(nil)
```
Comment (0xFelix) [inline tests/storage/snapshot.go]: There's also `libvmi.WithNamespace`. Can you put both libvmi Options into an `opts` slice?

File: tests/storage/snapshot.go [hunk 4]
```diff
@@ -565,7 +565,76 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
+						},
+					})
+					vm.Spec.Template.Spec.Volumes = append(vm.Spec.Template.Spec.Volumes, v1.Volume{
+						Name: "blank",
+						VolumeSource: v1.VolumeSource{
+							DataVolume: &v1.DataVolumeSource{
+								Name: "dv-" + vm.Name,
+							},
+						},
+					})
```
Comment (0xFelix) [inline tests/storage/snapshot.go]: Add that DV to the vmi first (with libvmi) and then create a VM from it?

File: tests/storage/snapshot.go [hunk 5]
```diff
@@ -565,7 +565,76 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
 
+					vm = libvmi.NewVirtualMachine(vmi)
```
Comment (0xFelix) [inline tests/storage/snapshot.go]: You call this func twice, also in L577

File: tests/storage/snapshot.go [hunk 6]
```diff
@@ -565,7 +565,76 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
+					updatedVMI, err := virtClient.VirtualMachineInstance(vmi.Namespace).
+						Get(context.Background(), vmi.Name, metav1.GetOptions{})
+					Expect(err).ToNot(HaveOccurred())
+					Expect(updatedVMI.Status.FSFreezeStatus).To(BeEmpty())
+
+					contentName := *snapshot.Status.VirtualMachineSnapshotContentName
+					checkOnlineSnapshotExpectedContentSource(vm, contentName, hasGuestAgent)
+				},
+				Entry("[test_id:7000] with guest-agent", true),
+				Entry("[test_id:7001] no guest-agent", false),
```
Comment (0xFelix) [inline tests/storage/snapshot.go]: Provide the libvmifact function here instead of a boolean?

File: pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go [hunk 7]
```diff
@@ -353,6 +354,21 @@ func (p *AgentPoller) Stop() {
 // GET_AGENT - According to libvirt engineers this command shouldn't be used
 // by KubeVirt, because it provides irrelevant information (version and supported commands).
 func executeAgentCommands(commands []AgentCommand, agentPoller *AgentPoller) {
+	dom, err := agentPoller.Connection.LookupDomainByName(agentPoller.domainName)
```
Comment (0xFelix) [inline pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: Is it correct that these changes are for `virt-launcher's agent poller is spamming qemu-gest-agent command failures when VM is paused.`? If so, can you put them into a separate commit please?

Comment (0xFelix) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: Is there a way to test this behavior?

Comment (noamasu) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: Yes, i will make a separate commit for this, and add relevant tests to it :)

File: pkg/virt-api/rest/lifecycle.go [hunk 8]
```diff
@@ -313,6 +313,19 @@ func (app *SubresourceAPIApp) PauseVMIRequestHandler(request *restful.Request, r
 
 func (app *SubresourceAPIApp) UnpauseVMIRequestHandler(request *restful.Request, response *restful.Response) {
```
Comment (ShellyKa13) [inline pkg/virt-api/rest/lifecycle.go:314]: should add this case to the subresource unit test

File: pkg/virt-api/rest/lifecycle.go [hunk 9]
```diff
@@ -313,6 +313,19 @@ func (app *SubresourceAPIApp) PauseVMIRequestHandler(request *restful.Request, r
...
 
+	name := request.PathParameter("name")
+	namespace := request.PathParameter("namespace")
+
+	vm, statusErr := app.fetchVirtualMachine(name, namespace)
+	if statusErr != nil {
+		writeError(statusErr, response)
+		return
+	}
+	if vm.Status.SnapshotInProgress != nil {
```
Comment (ShellyKa13) [inline pkg/virt-api/rest/lifecycle.go]: I wonder if we want to add such a check in every state change subresource, I assume it is possible that the subresource will be used directly without modifing the vm yaml (where we deny with the admitter), @mhenriks wdyt?

File: pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go (hunk 7 above)
Comment (ShellyKa13) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: nice addition to the PR, thanks

File: pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go [hunk 10]
```diff
@@ -353,6 +354,21 @@ func (p *AgentPoller) Stop() {
...
+	if err != nil {
+		log.Log.Errorf("Error getting domain: %v", err)
+		return
+	}
+	defer dom.Free()
+
+	if paused, err := util.DomainIsPaused(dom); err != nil {
+		log.Log.Errorf("cannot determine domain state: %v", err)
+		return
+	} else if paused {
```
Comment (ShellyKa13) [inline pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: no need for the else
just do if paused

File: pkg/virt-launcher/virtwrap/manager.go (hunk 1 above)
Comment (ShellyKa13) [reply pkg/virt-launcher/virtwrap/manager.go]: why do we need to check for not found and do a new error? why not return the error which is not found anyways?

File: pkg/virt-launcher/virtwrap/manager.go [hunk 11]
```diff
@@ -1895,6 +1906,25 @@ func (l *LibvirtDomainManager) FreezeVMI(vmi *v1.VirtualMachineInstance, unfreez
...
+	}
+	defer domain.Free()
+
+	if paused, err := util.DomainIsPaused(domain); err != nil {
```
Comment (ShellyKa13) [inline pkg/virt-launcher/virtwrap/manager.go]: since you added this function you can also use it in other places which check if domain is pause like:
UnpauseVMI

File: tests/storage/snapshot.go (hunk 6 above)
Comment (ShellyKa13) [reply tests/storage/snapshot.go]: +1

File: pkg/storage/snapshot/source.go [hunk 12]
```diff
@@ -100,6 +101,8 @@ func (s *vmSnapshotSource) UpdateSourceState() error {
 
 	online := exists
 
+	running := exists && s.vm.Status.PrintableStatus == kubevirtv1.VirtualMachineStatusRunning
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/source.go]: @mhenriks what do you think about using PrintableStatus? its not being relied upon to a big thing just whether to print on not the error message, but usually we prefer not to rely on it

Comment (mhenriks) [reply pkg/storage/snapshot/source.go]: It's probably okay for `Running` but I wouldn't rely on it for anything else

File: pkg/virt-api/rest/lifecycle.go (hunk 9 above)
Comment (mhenriks) [reply pkg/virt-api/rest/lifecycle.go]: hmm as far as I know, the subresources usually update something in the status and then a controller applies the change to the spec. When that happen the webhook will be invoked, no?

File: pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go [hunk 13]
```diff
@@ -353,6 +354,21 @@ func (p *AgentPoller) Stop() {
...
 // by KubeVirt, because it provides irrelevant information (version and supported commands).
 func executeAgentCommands(commands []AgentCommand, agentPoller *AgentPoller) {
+	dom, err := agentPoller.Connection.LookupDomainByName(agentPoller.domainName)
+	if err != nil {
+		log.Log.Errorf("Error getting domain: %v", err)
+		return
+	}
+	defer dom.Free()
+
+	if paused, err := util.DomainIsPaused(dom); err != nil {
```
Comment (codingben) [inline pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: Why did you added these changes only to `executeAgentCommands()`? because of the relevant QEMU commands in this function?

Comment (noamasu) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: thanks for the response! 
i added it because the agent poller's executeAgentCommands spam the logs with failed qemu agent command failures when the VM is paused (qemu guest agent cannot execute commands if the VM is not running). do you think we need to add it to other places?

Comment (codingben) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: There is also `fetchAndStoreGuestInfo()` that is using libvirt API to get relevant info instead of QEMU directly as an abstraction above it.

Comment (noamasu) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: It seems that since fetchAndStoreGuestInfo() doesn't rely on QEMU guest agent commands, so it's acceptable to retrieve information via the libvirt API even when the VM is paused.

File: tests/storage/snapshot.go (hunk 6 above)
Comment (noamasu) [reply tests/storage/snapshot.go]: @0xFelix , i tried to do:
```
	Entry("[test_id:7000] with guest-agent", libvmifact.NewFedora),
	Entry("[test_id:7001] without guest-agent", libvmifact.NewAlpine),
```
insead of boolean, 
but becuase i need this condition to wait for the guest agent:
```
		if imageFunc == libvmifact.NewFedora {
			Eventually(matcher.ThisVMI(vmi), 12*time.Minute, 2*time.Second).
				Should(matcher.HaveConditionTrue(v1.VirtualMachineInstanceAgentConnected))
		}
```
I cannot compare a function like ` imageFunc == libvmifact.NewFedora ` ... so seems like i have to pass a boolean anyways?
wondering what how to handle this if statement if i dont have the boolean

File: pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go (hunk 13 above)
Comment (noamasu) [reply pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go]: actually, i take it  back, you are right.
`domain.GetGuestInfo(infoTypes, 0)` will also fail when the VM is paused, as these messages are also being spammed
```
{"component":"virt-launcher","level":"info","msg":"Polling API operations: 1","pos":"agent_poller.go:417","timestamp":"2025-06-29T18:45:50.316563Z"}
{"component":"virt-launcher","level":"error","msg":"Fetching guest info failed: virError(Code=55, Domain=10, Message='Requested operation is not valid: domain is not running')","pos":"agent_poller.go:432","times
```

i will work on a fix that will cover both `fetchAndStoreGuestInfo` and `executeAgentCommands`
sorry for the confusion :)

**Comment by mhenriks** [comment]
> Since paused VMs have a consistent filesystem state (similar to frozen),

@noamasu can you supply some documentation for this? I don't think buffers are flushed when a VM is paused. Consider that a VM may be paused automatically by an I/O error

File: pkg/storage/snapshot/source.go (hunk 12 above)
Comment (mhenriks) [reply pkg/storage/snapshot/source.go]: maybe it would be best to just check the VMI conditions instead

File: pkg/storage/snapshot/source.go [hunk 14]
```diff
@@ -114,6 +117,7 @@ func (s *vmSnapshotSource) UpdateSourceState() error {
 
 	s.state = &sourceState{
 		online:     online,
+		running:    running,
```
Comment (mhenriks) [inline pkg/storage/snapshot/source.go]: can we just have online be false if the VM is paused and not add a new state?

Comment (mhenriks) [reply pkg/storage/snapshot/source.go]: asked another way, why can't we simply treat a paused VM as offline?

**Comment by noamasu** [comment]
Hey @mhenriks, thank you for the feedback. 

> Since paused VMs have a consistent filesystem state (similar to frozen),
the assumption was according to the Jira ticket's expected result - "VMSnapshot completed skipping freeze if VM is paused, and not fail".

after looking into this - sorry for this inaccuracy, you are right, pause will keep memory unflushed - risking a non-stable snapshot of the filesystem.

looks like just flushing the suspended vm is also not possible since you need a running VM to do so.

indeed snapshot of a paused VM is not safe, much like a running VM (memory not flushed to disk)...

knowing that's the case what do you think is the best way to deal with this as I see 2 options here:
1. treat "paused" the same as "running"... which means to check if VM is paused/running (online) and print the existing warning message of "not safe to snapshot a paused/running VM". do you think a `quesedFailed` indication should be presented in that case?
2. in the freeze function (snapshot/source.go):  if the vm is paused - unpause the vm before freeze, then do the freeze -> snapshot  -> unfreeze regularly, then pause the vm again. (I dont think its ok to change the the VM state tbh)

**Comment by mhenriks** [comment]
> 1. treat "paused" the same as "running"... which means to check if VM is paused/running (online) and print the existing warning message of "not safe to snapshot a paused/running VM". do you think a `quesedFailed` indication should be presented in that case?

@noamasu I think this is the better option, may even want to create a new indication for this case

**Comment by mhenriks** [comment]
I think this is looking pretty good, what are your thoughts @ShellyKa13?

File: pkg/storage/snapshot/snapshot.go [hunk 15]
```diff
@@ -843,6 +843,12 @@ func updateSnapshotIndications(snapshot *snapshotv1.VirtualMachineSnapshot, sour
 		} else {
 			indications = sets.Insert(indications, snapshotv1.VMSnapshotNoGuestAgentIndication)
 		}
+
+		// Check for paused VM
+		if source.Paused() {
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/snapshot.go]: What do you say about checking this before the guestagent and in case of paused not add the guestagent indication since it doesnt affect the snapshot. i.e
if source.Paused{
...
else if source.GuestAgent{
...
} else{
...
}

File: pkg/storage/snapshot/source.go [hunk 16]
```diff
@@ -454,6 +467,10 @@ func (s *vmSnapshotSource) Unfreeze() error {
 		return nil
 	}
 
+	if s.Paused() {
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/source.go]: why not add it to the first if:
if !s.Locked() || !s.GuestAgent() || s.Paused() {

File: staging/src/kubevirt.io/api/snapshot/v1beta1/types.go [hunk 17]
```diff
@@ -82,6 +82,7 @@ const (
 	VMSnapshotNoGuestAgentIndication   Indication = "NoGuestAgent"
 	VMSnapshotGuestAgentIndication     Indication = "GuestAgent"
 	VMSnapshotQuiesceFailedIndication  Indication = "QuiesceFailed"
+	VMSnapshotPausedIndication         Indication = "Paused"
```
Comment (ShellyKa13) [inline staging/src/kubevirt.io/api/snapshot/v1beta1/types.go:85]: This should probable be in the previous commit, or move the indications part from previous commit to this commit

File: pkg/virt-api/rest/lifecycle.go (hunk 9 above)
Comment (ShellyKa13) [reply pkg/virt-api/rest/lifecycle.go]: I verified with Cursor :) and as I thought in this cases the subresource call itself doesnt change vm/vmi which doesnt call the webhook and then the subresource passes the request directly to virt-handler which passes it right away to trough the grpc connection to the virt-handler to libvirt..

File: pkg/virt-api/rest/lifecycle.go (hunk 8 above)
Comment (ShellyKa13) [reply pkg/virt-api/rest/lifecycle.go:314]: dont we also need to prevent from doing pause during snapshot? it might fail but should we even pass it along if it will just fail?

**Review by ShellyKa13 — COMMENTED** [review]
Couple of suggestions

File: pkg/virt-api/rest/lifecycle.go (hunk 9 above)
Comment (mhenriks) [reply pkg/virt-api/rest/lifecycle.go]: far be it from me to question the AI but I'm pretty sure not "every state change subresource" is processed like that. That may be the case for pause because that is fundamentally an operation on the VMI

File: pkg/virt-api/rest/lifecycle.go (hunk 8 above)
Comment (mhenriks) [reply pkg/virt-api/rest/lifecycle.go:314]: more I think about it I'm a bit conflicted on doing anything special in pause/unpause subresource since the VMI is not just paused/unpaused by users may happen when internal error occurs like disk i/o error

File: pkg/storage/snapshot/source.go [hunk 18]
```diff
@@ -434,6 +442,11 @@ func (s *vmSnapshotSource) Freeze() error {
...
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/source.go]: probably should first check the paused condition before the guestagent one

File: tests/storage/snapshot.go [hunk 19]
```diff
@@ -562,11 +562,71 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
 				Eventually(func() string {
 					updatedVMI, err := virtClient.VirtualMachineInstance(vm.Namespace).Get(context.Background(), vm.Name, metav1.GetOptions{})
 					Expect(err).ToNot(HaveOccurred())
-					return updatedVMI.Status.FSFreezeStatus
-				}, 30*time.Second, 2*time.Second).Should(BeEmpty())
-			})
+								return updatedVMI.Status.FSFreezeStatus
+		}, 30*time.Second, 2*time.Second).Should(BeEmpty())
+	})
+	DescribeTable("should succeed snapshot when VM is paused with Paused indication",
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go]: missing new line before this block

File: tests/storage/snapshot.go [hunk 20]
```diff
@@ -562,11 +562,71 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
+
+			updatedVMI, err := virtClient.VirtualMachineInstance(vmi.Namespace).Get(context.Background(), vmi.Name, metav1.GetOptions{})
+			Expect(err).ToNot(HaveOccurred())
+			Expect(updatedVMI.Status.FSFreezeStatus).To(BeEmpty())
+
+			contentName := *snapshot.Status.VirtualMachineSnapshotContentName
+			checkOnlineSnapshotExpectedContentSource(vm, contentName, true)
+		},
+
+		Entry("[test_id:7000] with guest-agent", libvmifact.NewFedora, true),
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go]: not sure if we really need to run this test twice for with or without guest agent.. I think with guest agent is enough

File: pkg/storage/snapshot/snapshot.go [hunk 21]
```diff
@@ -833,7 +833,9 @@ func updateSnapshotIndications(snapshot *snapshotv1.VirtualMachineSnapshot, sour
 		indications := sets.New(snapshot.Status.Indications...)
 		indications = sets.Insert(indications, snapshotv1.VMSnapshotOnlineSnapshotIndication)
 
-		if source.GuestAgent() {
+		if source.Paused() {
+			indications = sets.Insert(indications, snapshotv1.VMSnapshotPausedIndication)
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/snapshot.go:837]: what about a unit test for this?

File: pkg/virt-api/rest/lifecycle.go (hunk 8 above)
Comment (ShellyKa13) [reply pkg/virt-api/rest/lifecycle.go:314]: @mhenriks I think we should at least handle cases of unpause done by users..

File: pkg/virt-api/rest/lifecycle.go (hunk 9 above)
Comment (ShellyKa13) [reply pkg/virt-api/rest/lifecycle.go]: @mhenriks technically any vm state change can come from virtctl(and I would assume UI also) bypassing the vm/vmi yaml change directly using the subresource. I think in such case the cases mentioned in the commit should be avoided is possible. We already do that in the webhook level so why not also subresource level?

File: pkg/virt-api/rest/lifecycle.go [hunk 22]
```diff
@@ -360,6 +377,19 @@ func (app *SubresourceAPIApp) FreezeVMIRequestHandler(request *restful.Request,
...
```
Comment (ShellyKa13) [inline pkg/virt-api/rest/lifecycle.go]: Dont think we can do this in the unfreeze since the snapshot is still in progress when you call unfreeze to complete the snapshot. And also there is an automatic unfreeze mechanism we use the prevent a case the vm is kept frozen if something happen to the snapshot and it for some reason doesnt unfreeze.

File: pkg/virt-api/rest/lifecycle.go [hunk 23]
```diff
@@ -533,11 +563,15 @@ func (app *SubresourceAPIApp) MigrateVMRequestHandler(request *restful.Request,
 			return
 		}
 	}
-	_, err := app.fetchVirtualMachine(name, namespace)
+	vm, err := app.fetchVirtualMachine(name, namespace)
```
Comment (ShellyKa13) [inline pkg/virt-api/rest/lifecycle.go]: also in this case Im not sure we want to prevent migrate vm call.. I believe the snapshot will just fail if the vm was migrated in the process and if not dont think it will cause data change anyways

File: pkg/virt-api/rest/lifecycle.go (hunk 9 above)
Comment (mhenriks) [reply pkg/virt-api/rest/lifecycle.go]: Can you be more specific about what subresource calls? I know that VM start/stop subresource updates the VM spec/status which should invoke the validating webhook

Comment (ShellyKa13) [reply pkg/virt-api/rest/lifecycle.go]: right I see you are right, they call the subresource directly and the subresource patches the vm with start and stop. So I guess only pause/unpause does not go through the yaml

File: pkg/virt-api/rest/lifecycle.go (hunk 8 above)
Comment (mhenriks) [reply pkg/virt-api/rest/lifecycle.go:314]: Yeah I guess unpause is fine

File: tests/storage/snapshot.go [hunk 24]
```diff
@@ -566,6 +566,56 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
...
+				Expect(err).ToNot(HaveOccurred())
+				snapshot = libstorage.WaitSnapshotSucceeded(virtClient, vm.Namespace, snapshot.Name)
+
+				By("Verifying snapshot has Paused indication")
+				expectedIndications := []snapshotv1.Indication{snapshotv1.VMSnapshotOnlineSnapshotIndication, snapshotv1.VMSnapshotPausedIndication}
+				Expect(snapshot.Status.Indications).To(ContainElements(expectedIndications))
+
+				updatedVMI, err := virtClient.VirtualMachineInstance(vmi.Namespace).Get(context.Background(), vmi.Name, metav1.GetOptions{})
+				Expect(err).ToNot(HaveOccurred())
+				Expect(updatedVMI.Status.FSFreezeStatus).To(BeEmpty())
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go]: dont think this check it related that much to the test. it doesnt check if a freeze occurred or not. and also we know that it could not have occurred since its not allowed by libvirt. so this check seems redundant

File: pkg/virt-api/rest/subresource_test.go [hunk 25]
```diff
@@ -1344,6 +1346,8 @@ var _ = Describe("VirtualMachineInstance Subresources", func() {
 			)
 			expectVMI(Running, Paused)
 
+			vmClient.EXPECT().Get(context.Background(), testVMIName, k8smetav1.GetOptions{}).Return(newVirtualMachineWithRunning(pointer.P(Running)), nil)
+
 			bytesRepresentation, _ := json.Marshal(unpauseOptions)
 			request.Request.Body = io.NopCloser(bytes.NewReader(bytesRepresentation))
```
Comment (ShellyKa13) [inline pkg/virt-api/rest/subresource_test.go]: what about adding a case to see when a vm has snapshot in progress it returns an error?

File: pkg/storage/snapshot/snapshot_test.go [hunk 26]
```diff
@@ -1524,6 +1524,170 @@ var _ = Describe("Snapshot controlleer", func() {
...
+				updateStatusCalls := expectVMSnapshotContentUpdateStatus(vmSnapshotClient, updatedContent)
+				vmSnapshotSource.Add(vmSnapshot)
+				addVolumeSnapshotClass(volumeSnapshotClass)
+				controller.processVMSnapshotContentWorkItem()
+				testutils.ExpectEvent(recorder, "SuccessfulVolumeSnapshotCreate")
+				Expect(*updateStatusCalls).To(Equal(1))
+				Expect(*snapshotCreates).To(Equal(1))
+			})
+
+			It("should set only Paused indication for paused VM without guest agent", func() {
```
Comment (ShellyKa13) [inline pkg/storage/snapshot/snapshot_test.go]: can we merge the next 3 tests regarding indications to a describe table?

File: tests/storage/snapshot.go [hunk 27]
```diff
@@ -566,6 +566,52 @@ var _ = Describe(SIG("VirtualMachineSnapshot Tests", func() {
 				}, 30*time.Second, 2*time.Second).Should(BeEmpty())
 			})
 
+			FIt("[test_id:12182] should succeed snapshot when VM is paused with Paused indication", func() {
```
Comment (ShellyKa13) [inline tests/storage/snapshot.go]: need to remove F

**Comment by ShellyKa13** [comment]
And please add the release note :)

**Review by ShellyKa13 — COMMENTED** [review]
/lgtm

**Comment by ShellyKa13** [comment]
I think we should backport it the relevant issue https://github.com/kubevirt/kubevirt/issues/10759 was opened several versions ago
