### PR TITLE
instancetype: Reject Matcher updates without updating RevisionName

### LINKED ISSUE #9132: Updates to the `name` referenced by `{Instancetype,Preference}Matchers` are allowed even when a `revisionName` is already present
/area instancetype

**What happened**:

https://kubevirt.io/user-guide/virtual_machines/instancetypes/#versioning

When a `VirtualMachine` is initially created the `{Instancetype,Preference}Matchers` are expanded to include a reference to a `ControllerRevision` containing a point in time copy of the underlying instance type or preference resource.

Users can opt into moving between instance types or preferences by modifying the `{Instancetype,Preference}Matchers` of their `VirtualMachine` but they must clear any `revisionName` defined when doing so for their changes to have an effect.

At present there are no validations carried out on update to ensure that this is done, allowing users to update the `name` without removing the `revisionName`. This will lead to the existing `ControllerRevision` being used. 

**What you expected to happen**:
Attempts to update the `name` referenced by `{Instancetype,Preference}Matchers` without removing the `revisionName` should be rejected.

**How to reproduce it (as minimally and precisely as possible)**:
```
./cluster-up/kubectl.sh kustomize https://github.com/kubevirt/common-instancetypes.git/VirtualMachineClusterInstancetypes | ./cluster-up/kubectl.sh apply -f -
[..]
$ ./cluster-up/kubectl.sh apply -f - << EOF
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  instancetype:
    name: server.micro
  running: false
  template:
    spec:
      domain:
        devices: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: containerdisk
EOF

$ ./cluster-up/kubectl.sh get vm/vm-cirros -o json | jq .spec.instancetype
selecting docker as container runtime
{
  "kind": "virtualmachineclusterinstancetype",
  "name": "server.micro",
  "revisionName": "vm-cirros-server.micro-5c383e54-3d92-46e8-9648-652911a12219-1"
}

$ ./cluster-up/kubectl.sh patch vm/vm-cirros --type merge -p '{"spec":{"instancetype":{"name":"server.tiny"}}}'
selecting docker as container runtime
virtualmachine.kubevirt.io/vm-cirros patched

$ ./cluster-up/kubectl.sh get vm/vm-cirros -o json | jq .spec.instancetype
selecting docker as container runtime
{
  "kind": "virtualmachineclusterinstancetype",
  "name": "server.tiny",
  "revisionName": "vm-cirros-server.micro-5c383e54-3d92-46e8-9648-652911a12219-1"
}

$ ./cluster-up/virtctl.sh start vm-cirros
selecting docker as container runtime
VM vm-cirros was scheduled to start

$ ./cluster-up/kubectl.sh get vmi/vm-cirros -o json | jq .spec.domain.memory
selecting docker as container runtime
{
  "guest": "256Mi"
}

$ ./cluster-up/kubectl.sh get virtualmachineclusterinstancetype/server.micro -o json | jq .spec.memory
selecting docker as container runtime
{
  "guest": "256Mi"
}

$ ./cluster-up/kubectl.sh get virtualmachineclusterinstancetype/server.tiny -o json | jq .spec.memory
selecting docker as container runtime
{
  "guest": "1.5Gi"
}
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype 

**What this PR does / why we need it**:

As set out in issue #9132 requests to update the `Name` of an `{Instancetype,Preference}Matcher` were always accepted regardless of the `RevisionName` also being updated. This would result in an older and likely unwanted `ControllerRevision` being used containing an outdated or completely wrong `Instancetype` or `Preference`.

With this change the VM mutation webhook will now reject requests to update the target `Name` of a `{Instancetype,Preference}Matcher` without also updating the `RevisionName`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9132

**Special notes for your reviewer**:

**Release note**:

```release-note
 Requests to update the target `Name` of a `{Instancetype,Preference}Matcher` without also updating the `RevisionName` are now rejected.
```

### CODE REVIEW

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 1]
```diff
@@ -225,6 +240,48 @@ func (mutator *VMsMutator) setDefaultPreferenceKind(vm *v1.VirtualMachine) {
...
+func validateMatcherUpdate[M v1.Matcher](oldMatcher M, newMatcher M) error {
+	// Do not check anything when the original matcher didn't have a revisionName as this is likely the VM Controller updating the matcher
+	if oldMatcher.GetRevisionName() == "" {
+		return nil
+	}
+	// If the matchers have changed ensure that the RevisionName is cleared when updating the Name
+	if !equality.Semantic.DeepEqual(newMatcher, oldMatcher) {
+		if oldMatcher.GetName() != newMatcher.GetName() && newMatcher.GetRevisionName() != "" {
+			return fmt.Errorf("the Matcher Name has been updated without clearing the RevisionName")
+		}
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:280]: Change this to

```
		if oldMatcher.GetName() != newMatcher.GetName() && oldMatcher.GetRevisionName() == newMatcher.GetRevisionName() {
			return fmt.Errorf("the Matcher Name has been updated without updating the RevisionName")
		}
```

to allow changing to a different matcher with a specific revision in one go?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 2]
```diff
@@ -225,6 +240,48 @@ func (mutator *VMsMutator) setDefaultPreferenceKind(vm *v1.VirtualMachine) {
...
+		return []metav1.StatusCause{{
+			Type:    metav1.CauseTypeFieldValueInvalid,
+			Message: err.Error(),
+			Field:   k8sfield.NewPath("spec", "preference", "revisionName").String(),
+		}}
+	}
+	return nil
+}
+
+func validateMatcherUpdate[M v1.Matcher](oldMatcher M, newMatcher M) error {
```
Comment (xpivarc) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:271]: Why generic?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go [hunk 3]
```diff
@@ -125,6 +147,7 @@ var _ = Describe("VirtualMachine Mutator", func() {
 
 		k8sClient = k8sfake.NewSimpleClientset()
 		virtClient.EXPECT().CoreV1().Return(k8sClient.CoreV1()).AnyTimes()
+		virtClient.EXPECT().AppsV1().Return(k8sClient.AppsV1()).AnyTimes()
```
Comment (xpivarc) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:150]: Why is this required?

Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go:150]: Good question, the mutation webhook will attempt to lookup any preference related `ControllerRevisions` but ultimately swallow any errors later in the mutation flow:

https://github.com/kubevirt/kubevirt/blob/7d903296560a4ce19fdd7e2d5368b9f9374ed658/pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go#L136-L141

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 2 above)
Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:271]: @xpivarc hopefully that answered your question, would you mind taking another look?

**Review by xpivarc — COMMENTED** [review]
Sorry I forgot to submit my review

**Review by xpivarc — COMMENTED** [review]
/approve
@0xFelix Can you give this one proper look?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 4]
```diff
@@ -225,6 +240,48 @@ func (mutator *VMsMutator) setDefaultPreferenceKind(vm *v1.VirtualMachine) {
...
+			Type:    metav1.CauseTypeFieldValueInvalid,
+			Message: err.Error(),
+			Field:   k8sfield.NewPath("spec", "instancetype", "revisionName").String(),
+		}}
+	}
+	return nil
+}
+
+func validatePreferenceMatcherUpdate(oldPreferenceMatcher *v1.PreferenceMatcher, newPreferenceMatcher *v1.PreferenceMatcher) []metav1.StatusCause {
+	if oldPreferenceMatcher == nil && newPreferenceMatcher == nil {
```
Comment (0xFelix) [inline pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:258]: What happens if only one matcher is nil? Will it panic?

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go [hunk 5]
```diff
@@ -225,6 +240,48 @@ func (mutator *VMsMutator) setDefaultPreferenceKind(vm *v1.VirtualMachine) {
...
+		return nil
+	}
+	if err := validateMatcherUpdate(*oldPreferenceMatcher, *newPreferenceMatcher); err != nil {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go:263]: Yeah good catch, updated the `&&` above, should be `||` to skip the check when one side isn't provided when they are initially introduced or later dropped.

File: pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go (hunk 4 above)
Comment (lyarwood) [reply pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go]: As above, thanks!

**Comment by 0xFelix** [comment]
Thanks!

/lgtm
/retest
