### PR TITLE
fix: lint: pkg/virtctl/create/clone errors

### LINKED ISSUE #14194: Resolve linting issues in pkg/virtctl/create/clone
**What happened**:

Running the linter against `pkg/virtctl/create/clone` fails.

**What you expected to happen**:

Running the linter against `pkg/virtctl/create/clone` should succeed without errors or warnings.

**How to reproduce it (as minimally and precisely as possible)**:

Add `pkg/virtctl/create/clone` to `hack/linter/lint-paths.txt` and run `make lint`.

/kind cleanup
/label good-first-issue

### PR DESCRIPTION
**Pull request by mohit-nagaraj**
#### Before this PR:
Running the linter against pkg/virtctl/create/clone gives errors.
#### After this PR:
Added  pkg/virtctl/create/clone to hack/linter/lint-paths.txt and ran make lint. Fixed the lint issue in this package

### References
- Fixes #14194

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least one e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
NONE
```

### CODE REVIEW

**Comment by mohit-nagaraj** [comment]
/cc @0xFelix 
This pr has been open for quite some time. Could you please provide your inputs on this one as well? Much appreciated

File: pkg/virtctl/create/clone/clone.go [hunk 1]
```diff
@@ -271,15 +291,15 @@ func (c *createClone) typeToTypedLocalObjectReference(sourceOrTargetType, source
...
 		apiGroup = "kubevirt.io"
-	case "snapshot", "VirtualMachineSnapshot", "vmsnapshot", "VMSnapshot":
+	case "snapshot", virtualMachineSnapshotKind, "vmsnapshot", "VMSnapshot":
 		if !isSource {
 			return nil, generateErr()
 		}
 
-		kind = "VirtualMachineSnapshot"
+		kind = virtualMachineSnapshotKind
 		apiGroup = "snapshot.kubevirt.io"
```
Comment (0xFelix) [inline pkg/virtctl/create/clone/clone.go:304]: Looks inconsistent to me, did the linter complain only about the two literals you've added consts for?

File: pkg/virtctl/create/clone/clone.go [hunk 2]
```diff
@@ -323,4 +345,4 @@ func (c *createClone) validateFlags() error {
 	}
 
 	return nil
-}
+}
```
Comment (0xFelix) [inline pkg/virtctl/create/clone/clone.go]: Keep newline at end of file please

File: pkg/virtctl/create/clone/clone.go [hunk 3]
```diff
@@ -292,6 +312,8 @@ func (c *createClone) typeToTypedLocalObjectReference(sourceOrTargetType, source
 	}, nil
 }
 
+const cloneRandomSuffixLength = 5
```
Comment (0xFelix) [inline pkg/virtctl/create/clone/clone.go]: Put it closer to where it's used

File: pkg/virtctl/create/clone/clone_test.go [hunk 4]
```diff
@@ -278,4 +274,4 @@ func newCommand(createCloneFlags ...string) (*clone.VirtualMachineClone, error)
 
 func getSourceNameFlags() []string {
 	return addFlag(nil, virtctlclone.SourceNameFlag, "source-vm")
-}
+}
```
Comment (0xFelix) [inline pkg/virtctl/create/clone/clone_test.go]: Same

File: pkg/virtctl/create/clone/clone.go (hunk 1 above)
Comment (mohit-nagaraj) [reply pkg/virtctl/create/clone/clone.go:304]: Yes it does raise this error
```
pkg/virtctl/create/clone/clone.go:291:19: string `VirtualMachine` has 2 occurrences, make it a constant (goconst)
        case "vm", "VM", "VirtualMachine", "virtualmachine":
                         ^
pkg/virtctl/create/clone/clone.go:294:19: string `VirtualMachineSnapshot` has 2 occurrences, make it a constant (goconst)
        case "snapshot", "VirtualMachineSnapshot", "vmsnapshot", "VMSnapshot":
```

**Review by 0xFelix — COMMENTED** [review]
/test all

**Review by 0xFelix — COMMENTED** [review]
/approve

File: pkg/virtctl/create/clone/clone_test.go [hunk 5]
```diff
@@ -262,9 +258,9 @@ func addFlag(s []string, flag, value string) []string {
 
 func newCommand(createCloneFlags ...string) (*clone.VirtualMachineClone, error) {
 	baseArgs := []string{create, virtctlclone.Clone}
-	args := append(baseArgs, createCloneFlags...)
+	baseArgs = append(baseArgs, createCloneFlags...)
 
-	bytes, err := testing.NewRepeatableVirtctlCommandWithOut(args...)()
+	bytes, err := testing.NewRepeatableVirtctlCommandWithOut(baseArgs...)()
```
Comment (fossedihelm) [inline pkg/virtctl/create/clone/clone_test.go]: I would prefer:
```go
args := append([]string{create, virtctlclone.Clone}, createCloneFlags...)
```

**Comment by fossedihelm** [comment]
Looks good.
Giving the chance to address my comment

**Comment by fossedihelm** [comment]
/lgtm
Thanks
