### PR TITLE
Remove /var/lib/kubelet before kubeadm init

### LINKED ISSUE #483: kubelet failed to pass pre-flight checks
```
==> master: [preflight] WARNING: Running with swap on is not supported. Please disable swap or set kubelet's --fail-swap-on flag to false.
==> master: [preflight] Some fatal errors occurred:
==> master:     /var/lib/kubelet is not empty
==> master: [preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
```

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Fixes #483 
Temporary W/A until https://github.com/kubernetes/kubernetes/issues/53356 will be fixed.

Signed-off-by: Lukianov Artyom <alukiano@redhat.com>

### CODE REVIEW

File: cluster/vagrant/setup_kubernetes_master.sh [hunk 1]
```diff
@@ -24,6 +24,9 @@ bash ./setup_kubernetes_common.sh
 yum install -y cockpit cockpit-kubernetes
 systemctl enable cockpit.socket && systemctl start cockpit.socket
 
+# W/A for https://github.com/kubernetes/kubernetes/issues/53356
+rm -rf /var/lib/kubelet
```
Comment (vladikr) [inline cluster/vagrant/setup_kubernetes_master.sh]: yea, that should work. 
I've added kubeadm reset and it did the trick as well
