### PR TITLE
tests: wait for operator reconciliation in BlockUninstallIfWorkloadsExist

### LINKED ISSUE #17258: [sig-operator] BlockUninstallIfWorkloadsExist "should be blocked if a workload exists" flakes with webhook timeout
# What happened

Flaky test detected: `[sig-operator]Operator infrastructure management deleting with BlockUninstallIfWorkloadsExist [test_id:3683]should be blocked if a workload exists` [1]

/kind flake
/priority critical-urgent
/area operator

[1]: https://search.ci.kubevirt.io/?context=1&groupBy=job&maxAge=336h&maxBytes=20971520&maxMatches=200&search=virtualmachineinstances-create-validator.kubevirt.io.%2Acontext+deadline+exceeded&type=junit

## Additional context

**21 hits across 4 sig-operator jobs in the last 14 days:**

| Job | Matches | Impact |
|-----|---------|--------|
| `pull-kubevirt-e2e-k8s-1.33-sig-operator` | 9 | 2% of runs |
| `pull-kubevirt-e2e-k8s-1.35-sig-operator` | 6 | 1% of runs |
| `pull-kubevirt-e2e-k8s-1.34-sig-operator-1.8` | 3 | 3% of runs |
| `periodic-kubevirt-e2e-k8s-1.33-sig-operator` | 3 | 2% of runs |

The test fails with:
```
Internal error occurred: failed calling webhook
  "virtualmachineinstances-create-validator.kubevirt.io":
  Post "https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=10s":
  context deadline exceeded
```

### Root Cause

The `BeforeEach` patches the KubeVirt CR to set `uninstallStrategy: BlockUninstallIfWorkloadsExist`, then only waits for the *spec* to reflect the change. It does not wait for the virt-operator to finish reconciling after the patch.

The patch triggers a full operator reconciliation (hundreds of resource updates — CRDs, RBAC, services, webhooks, certificates, configmaps) which saturates the kube-apiserver. The test then immediately creates a VMI, which goes through the virt-api validating webhook. The apiserver cannot complete the webhook round-trip within the 10s deadline because it is busy processing the operator's update requests.

Artifact analysis from [a representative failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/16860/pull-kubevirt-e2e-k8s-1.33-sig-operator/2033528161798459392) confirms:
- **virt-api pods were healthy** — both running, 0 restarts, serving HTTP 200s
- **kube-apiserver was overloaded** — logged "client disconnected" and "Handler timeout" errors at 14:35:03 UTC
- **virt-operator was mid-reconciliation** — all deployments and the virt-handler DaemonSet were rolling at the time of failure
- **KubeVirt CR status**: `Available=True` (reason: `UpdateInProgress`), `Progressing=True`, `Degraded=True`

# Flake Action Plan

### The flake is a bug

The fix is to call `allKvInfraPodsAreReady(originalKv)` after the `Eventually` that confirms the uninstall strategy spec change, ensuring the operator reconciliation completes before the test proceeds to create a VMI.

### PR DESCRIPTION
**Pull request by lyarwood**
#### Before this PR:

The `BlockUninstallIfWorkloadsExist` `BeforeEach` calls `allKvInfraPodsAreReady` and `sanityCheckDeploymentsExist` before patching the KubeVirt CR. This catches any pending reconciliation from the previous test's `AfterEach` but does not wait for the reconciliation triggered by the `BeforeEach` patch itself. The `AfterEach` also doesn't wait for reconciliation after removing the uninstall strategy.

This means the test can attempt to create a VMI while the operator is still reconciling, saturating the kube-apiserver and causing the virt-api webhook to timeout.

#### After this PR:

- `BeforeEach`: `allKvInfraPodsAreReady` and `sanityCheckDeploymentsExist` are moved from before the patch to after it, so they wait for the reconciliation triggered by setting the uninstall strategy.
- `AfterEach`: `allKvInfraPodsAreReady` and `sanityCheckDeploymentsExist` are added after removing the uninstall strategy, ensuring reconciliation completes before the next test cycle.

### References

- Fixes #17258

### Why we need it and why it was done in this way

The flake has **21 hits across 4 sig-operator jobs in the last 14 days**. Artifact analysis of [a representative failure](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/16860/pull-kubevirt-e2e-k8s-1.33-sig-operator/2033528161798459392) confirmed:

- virt-api pods were healthy (running, 0 restarts, serving HTTP 200s)
- The kube-apiserver logged "client disconnected" and "Handler timeout" errors during the failure
- The virt-operator was mid-reconciliation with all deployments and the virt-handler DaemonSet rolling

### Special notes for your reviewer

Both `BeforeEach` and `AfterEach` patch the KubeVirt CR, each triggering an operator reconciliation. Both now wait for reconciliation to complete with `allKvInfraPodsAreReady` and `sanityCheckDeploymentsExist` after their respective patches.

### Checklist

- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] AI Contributions: The PR abides by the [KubeVirt AI Contribution Policy](https://github.com/kubevirt/community/blob/main/ai-contribution-policy.md).

### Release note
```release-note
NONE
```

### CODE REVIEW

File: tests/operator/operator.go
Comment (dankenigsberg) [inline tests/operator/operator.go:1063]: wouldn't you need the same thing here, so as not to affect future tests?

File: tests/operator/operator.go [hunk 1]
```diff
@@ -1048,6 +1048,9 @@ var _ = Describe("[sig-operator]Operator", Serial, decorators.SigOperator, func(
 					kv, err := virtClient.KubeVirt(originalKv.Namespace).Get(context.Background(), originalKv.Name, metav1.GetOptions{})
 					return kv.Spec.UninstallStrategy, err
 				}, 60*time.Second, time.Second).Should(Equal(v1.KubeVirtUninstallStrategyBlockUninstallIfWorkloadsExist))
+
+				By("waiting for the operator to finish reconciling after the patch")
+				allKvInfraPodsAreReady(originalKv)
```
Comment (0xFelix) [inline tests/operator/operator.go:1050]: What's the point of waiting for all Pods twice? Can you not remove the call to `allKvInfraPodsAreReady` on L1039 then?

File: tests/operator/operator.go
Comment (0xFelix) [reply tests/operator/operator.go:1063]: True, this could affect tests after this `Describe`.

File: tests/operator/operator.go (hunk 1 above)
Comment (lyarwood) [reply tests/operator/operator.go:1050]: There's a patch in-between so it makes sense to wait here, it looks like L1039 was an attempt to wait on similar previous events but as you and Dan both point out below we should be doing that directly in the AfterEach. I'll sort that out now but it isn't directly related to the flake.

File: tests/operator/operator.go [hunk 2]
```diff
@@ -1060,6 +1061,10 @@ var _ = Describe("[sig-operator]Operator", Serial, decorators.SigOperator, func(
 					kv, err := virtClient.KubeVirt(originalKv.Namespace).Get(context.Background(), originalKv.Name, metav1.GetOptions{})
 					return kv.Spec.UninstallStrategy, err
 				}, 60*time.Second, time.Second).Should(BeEmpty())
+
+				By("waiting for the operator to finish reconciling after the patch")
```
Comment (dankenigsberg) [inline tests/operator/operator.go:1065]: ByTheWay("I find these `By` lines self-evident and distracting the reader")

/lgtm
