### PR TITLE
fix(virtctl): Ensure the log verbosity flag is supported

### LINKED ISSUE #12779: virtctl: Log verbosity cannot be set anymore
**What happened**:

Since https://github.com/kubevirt/kubevirt/pull/12070 was merged it is no longer possible to set the log verbosity in virtctl by providing the `-v` flag.

**What you expected to happen**:

The log verbosity in virtctl can be set by providing the `-v` flag.

**How to reproduce it (as minimally and precisely as possible)**:

Run virtctl with `-v` flag and observe the following error: `unknown shorthand flag: 'v' in -v`

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by 0xFelix**
### What this PR does

The log verbosity flag is added initially to the default flag set by init() of glog. With this change the flag is re-added to virtctl's root command flag set, so it can be used within virtctl.

Before this PR:

virtctl does not support the `-v` / `--v` log verbosity flag.

After this PR:

virtctl supports setting the log verbosity with the `-v` / `--v` flag.

Fixes #12779 

### Why we need it and why it was done in this way
The following tradeoffs were made:

The following alternatives were considered:

Links to places where the discussion took place: 

### Checklist

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### Release note

```release-note
None
```

### CODE REVIEW

File: pkg/virtctl/root.go [hunk 1]
```diff
@@ -131,6 +134,17 @@ func NewVirtctlCommandFn() (*cobra.Command, clientcmd.ClientConfig) {
 	return rootCmd, clientConfig
 }
 
+func addGLogVerbosityFlag(fs *pflag.FlagSet) {
+	// The glog verbosity flag is added to the default flag set
+	// by init() in vendor/github.com/golang/glog/glog.go.
+	// We re-add it here to make it available in virtctl commands.
+	if f := flag.CommandLine.Lookup("v"); f != nil {
+		fs.AddFlag(pflag.PFlagFromGoFlag(f))
```
Comment (jcanocan) [inline pkg/virtctl/root.go:142]: Silly question: is it valid a log verbosity of 0? i.e., `-v=0`.

Comment (0xFelix) [reply pkg/virtctl/root.go:142]: It is, but this is all encapsulated within glog. This change only makes the flag accessible through virtctl again.

Comment (jcanocan) [reply pkg/virtctl/root.go:142]: Ah okay, got it. Thanks for the clarification.

**Comment by jcanocan** [comment]
Great job! Thanks!
/lgtm

**Comment by alicefr** [comment]
Looks great!
/approve
